function result = check_e_cap_stream(attempt,input_path)
%CHECK_E_CAP_STREAM Run the thin REV_F same-trial evaluation-cap dispatcher.
% Purpose:
%   Dispatch the frozen certificate, lifting, wall, circle, full-P/cap, and
%   publication modules while enforcing resource and append-only contracts.
% Input:
%   attempt    - The sole append-only tag, 'ecap-a3'.
%   input_path - Explicit staged fbie-a1 certificate MAT file.
% Output:
%   result     - Compact diagnostics and empirical candidate; all certified
%                and reliability claims remain false.
% Main algorithm:
%   Merge each typed module result before clearing its private payload and
%   before applying the next resource gate.  The entry contains no boundary
%   action, quadrature, full-P, or cap formula.
% Based on:
%   check_e_cap.m Revision E and design-3-2c.md REV_F.
% Main changes:
%   Replaces the monolithic evaluator with one thin entry and five science
%   modules plus an independently ledgered publication function.
% Numerical goal:
%   Execute one memory-bounded same-trial empirical-cap attempt after review.

  if nargin~=2||~strcmp(char(attempt),'ecap-a3')|| ...
      ~(ischar(input_path)||isstring(input_path))
    error('i32f:Arguments', ...
      'The frozen call is check_e_cap_stream(''ecap-a3'',explicit_input).');
  end
  if exist('OCTAVE_VERSION','builtin')~=0
    error('i32f:MATLABRequired','This experiment requires MATLAB.');
  end
  here=fileparts(mfilename('fullpath')); output=fullfile(here,'output','ecap-a3');
  if exist(output,'file')||exist(output,'dir')
    error('i32f:OutputExists','The whole ecap-a3 directory must be absent.');
  end
  c=LOCAL_config(); timer=tic; result=LOCAL_empty_result(c,char(input_path));
  before=LOCAL_entry_retained_mib();
  consumption=i32_result_output( ...
    'consume',result,c,output,before,0);
  result.resources.attempt_consumption=consumption;
  cumulative=consumption.cumulative_peak_candidate_mib;
  clear consumption;
  dispatch=true; staged=struct(); lift_private=struct();
  wall_private=struct(); circle_private=struct();
  module=struct(); current_module='none'; module_merged=false;
  module_entry_before=NaN;
  try
    % --- stage 1: certificate identity and exact pruning ---
    current_module='certificate'; module_merged=false;
    clear before; before=LOCAL_entry_retained_mib();
    module_entry_before=before;
    module=i32_certificate_input(char(input_path),c,before);
    module=LOCAL_audit_return(module,'certificate');
    [result,cumulative]=LOCAL_merge_module(result,'certificate',module,cumulative);
    module_merged=true;
    if module.available
      staged=module.finest_factors.staged;
    else
      [result,dispatch]=LOCAL_stop_from_module(result,module,'certificate');
    end
    clear module; module=struct(); current_module='none';
    [result,cumulative]=LOCAL_close_resource( ...
      result,'certificate',LOCAL_entry_retained_mib(),cumulative);
    if dispatch&&(c.expected_seconds>c.preflight_seconds_max|| ...
        cumulative>c.preflight_mib_max)
      [result,dispatch]=LOCAL_execution_stop(result,'RESOURCE_PREFLIGHT_UNAVAILABLE', ...
        'The frozen 1500-second/520-MiB preflight refused science dispatch.');
    end
    [result,dispatch]=LOCAL_resource_gate(result,dispatch,timer,cumulative,c);

    % --- stage 2: frozen one-dimensional lift weights ---
    if dispatch
      current_module='lifting'; module_merged=false;
      clear before; before=LOCAL_entry_retained_mib();
      module_entry_before=before;
      module=i32_lifting_quadrature(c,staged,timer,before);
      module=LOCAL_audit_return(module,'lifting');
      [result,cumulative]=LOCAL_merge_module(result,'lifting',module,cumulative);
      module_merged=true;
      if module.available
        lift_private=module.finest_factors;
      else
        [result,dispatch]=LOCAL_stop_from_module(result,module,'lifting');
      end
      clear module; module=struct(); current_module='none';
      [result,cumulative]=LOCAL_close_resource( ...
        result,'lifting',LOCAL_entry_retained_mib(),cumulative);
      [result,dispatch]=LOCAL_resource_gate(result,dispatch,timer,cumulative,c);
    end

    % --- stage 3: artificial-wall action and signatures ---
    if dispatch
      current_module='wall'; module_merged=false;
      clear before; before=LOCAL_entry_retained_mib();
      module_entry_before=before;
      module=i32_wall_module(c,staged,lift_private,timer,before);
      module=LOCAL_audit_return(module,'wall');
      [result,cumulative]=LOCAL_merge_module(result,'wall',module,cumulative);
      module_merged=true;
      if module.available
        wall_private=LOCAL_private_science(module);
      else
        [result,dispatch]=LOCAL_stop_from_module(result,module,'wall');
      end
      clear module; module=struct(); current_module='none';
      if dispatch
        [staged,death]=LOCAL_after_wall_prune(staged);
        result.audit.last_use_death.after_wall=death;
      end
      [result,cumulative]=LOCAL_close_resource(result,'wall', ...
        LOCAL_entry_retained_mib(),cumulative);
      [result,dispatch]=LOCAL_resource_gate(result,dispatch,timer,cumulative,c);
    end

    % --- stage 4: material-circle action, oracles, and signatures ---
    if dispatch
      current_module='circle'; module_merged=false;
      clear before; before=LOCAL_entry_retained_mib();
      module_entry_before=before;
      module=i32_circle_module(c,staged,lift_private, ...
        wall_private.public_metrics,timer,before);
      module=LOCAL_audit_return(module,'circle');
      [result,cumulative]=LOCAL_merge_module(result,'circle',module,cumulative);
      module_merged=true;
      if module.available
        circle_private=LOCAL_private_science(module);
      else
        [result,dispatch]=LOCAL_stop_from_module(result,module,'circle');
      end
      clear module; module=struct(); current_module='none';
      if dispatch
        [staged,death]=LOCAL_after_circle_prune(staged);
        result.audit.last_use_death.after_circle=death;
      end
      [result,cumulative]=LOCAL_close_resource(result,'circle', ...
        LOCAL_entry_retained_mib(),cumulative);
      [result,dispatch]=LOCAL_resource_gate(result,dispatch,timer,cumulative,c);
    end

    % --- stage 5: full-P tails, caps, and empirical nominal transform ---
    if dispatch
      current_module='fullp_cap'; module_merged=false;
      clear before; before=LOCAL_entry_retained_mib();
      module_entry_before=before;
      module=i32_fullp_cap(c,staged,lift_private,wall_private, ...
        circle_private,timer,before);
      module=LOCAL_audit_return(module,'fullp_cap');
      [result,cumulative]=LOCAL_merge_module(result,'fullp_cap',module,cumulative);
      module_merged=true;
      if module.available
        result=LOCAL_merge_cap(result,module.public_metrics);
      else
        [result,dispatch]=LOCAL_stop_from_module(result,module,'fullp_cap');
      end
      clear module; module=struct(); current_module='none';
    end
  catch ME
    if ~module_merged&&~strcmp(current_module,'none')
      [result,cumulative]=LOCAL_salvage_failed_module( ...
        result,module,current_module,module_entry_before,cumulative,c);
    end
    [result,dispatch]=LOCAL_execution_stop(result,ME.identifier,ME.message); %#ok<ASGLU>
  end

  % --- stage 6: finally-style owner cleanup and retained-memory snapshot ---
  result.audit.final_cleanup=struct('trigger_module',current_module, ...
    'unreturned_local_peak_mib',LOCAL_unreturned_peak(module,module_merged), ...
    'preclear_owner_inventory',struct([]),'retained_before_clear_mib',NaN, ...
    'postclear_owner_inventory',struct([]),'retained_after_clear_mib',NaN, ...
    'postclear_private_owner_names',{{}}, ...
    'registered_owner_policy',[ ...
      'All reachable dense/science owners are registered; omitted entry ', ...
      'locals are control scalars, text, timers, or compact ledgers.'], ...
    'result_has_no_private_module_payload',false, ...
    'cumulative_peak_candidate_mib',NaN,'all_private_owners_cleared',false);
  for pass=1:2
    inventory=LOCAL_entry_owner_inventory();
    retained_before_clear=sum([inventory.mib]);
    result.audit.final_cleanup.preclear_owner_inventory=inventory;
    result.audit.final_cleanup.retained_before_clear_mib=retained_before_clear;
  end
  cumulative=max(cumulative,retained_before_clear);
  clear staged lift_private wall_private circle_private module;
  cleanup_death=struct( ...
    'staged_cleared',true,'lifting_factors_cleared',true, ...
    'wall_factors_and_signatures_cleared',true, ...
    'circle_factors_and_signatures_cleared',true, ...
    'current_module_payload_cleared',true);
  result.audit.last_use_death.final_cleanup=cleanup_death;
  if isfield(result.modules,'fullp_cap')
    result.audit.last_use_death.after_fullp_cap=cleanup_death;
  end
  clear cleanup_death;
  resource_names=fieldnames(result.resources.modules);
  for j=1:numel(resource_names)
    name=resource_names{j}; record=result.resources.modules.(name);
    if isfield(record,'retained_after_mib')&& ...
        (~isfinite(record.retained_after_mib)||isnan(record.retained_after_mib))
      [result,cumulative]=LOCAL_close_resource(result,name, ...
        LOCAL_entry_retained_mib(),cumulative);
    end
  end
  clear resource_names name record;
  for pass=1:2
    inventory=LOCAL_entry_owner_inventory();
    retained_after_clear=sum([inventory.mib]);
    result.audit.final_cleanup.postclear_owner_inventory=inventory;
    result.audit.final_cleanup.retained_after_clear_mib=retained_after_clear;
  end
  cumulative=max(cumulative,retained_after_clear);
  private_names={'staged','lift_private','wall_private','circle_private','module'};
  live_names={inventory.name};
  result.audit.final_cleanup.postclear_private_owner_names= ...
    intersect(live_names,private_names,'stable');
  result.audit.final_cleanup.result_has_no_private_module_payload= ...
    LOCAL_result_private_payload_absent(result);
  result.audit.final_cleanup.cumulative_peak_candidate_mib=cumulative;
  result.audit.final_cleanup.all_private_owners_cleared= ...
    isempty(result.audit.final_cleanup.postclear_private_owner_names)&& ...
    result.audit.final_cleanup.result_has_no_private_module_payload;
  if ~result.audit.final_cleanup.all_private_owners_cleared
    [result,dispatch]=LOCAL_execution_stop(result, ...
      'PRIVATE_OWNER_CLEANUP_UNAVAILABLE', ...
      'A registered private science owner remained reachable after cleanup.'); %#ok<ASGLU>
  end
  clear private_names live_names;

  result.elapsed_seconds=toc(timer);
  result.resources.actual.elapsed_seconds=result.elapsed_seconds;
  result.resources.actual.cumulative_peak_candidate_mib=cumulative;
  result.resources.actual.frozen_streaming_transient_mib=c.worst_transient_mib;
  result.resources.actual.sequential_module_peaks_combined_by_max=true;
  result.resources.actual.proxy_is_not_RSS_or_reference_count=true;
  result.peak_active_mib=cumulative;
  if result.elapsed_seconds>c.hard_seconds||cumulative>c.memory_mib_max
    [result,~]=LOCAL_execution_stop(result,'RESOURCE_LIMIT_EXCEEDED', ...
      'The hard time or 640 MiB active-object proxy was exceeded.');
  end
  result=LOCAL_finalize_status(result,c);
  result.audit.no_resolve=LOCAL_no_resolve_audit(result.call_counters);
  result.audit.allowlisted_eig=LOCAL_allowlisted_eig_audit(result.call_counters);
  if ~result.audit.no_resolve.pass
    [result,~]=LOCAL_execution_stop(result,'CERTIFICATE_IDENTITY_MISMATCH', ...
      'At least one of the eight NO_RESOLVE counters is nonzero.');
  elseif ~result.audit.allowlisted_eig.pass&& ...
      isfield(result.modules,'fullp_cap')&&result.modules.fullp_cap.available
    [result,~]=LOCAL_execution_stop(result,'ALLOWLISTED_EIG_IDENTITY_UNAVAILABLE', ...
      'The exact Gauss6/small-Gram274/total280 ledger failed.');
  end
  result=LOCAL_finalize_status(result,c);
  result.first_nonblocking_warning=LOCAL_first_warning(result.nonblocking_warnings);
  result.reliability=LOCAL_reliability_flags();
  result.qualification=LOCAL_result_qualification(result);
  result.resources.actual.hard_limits_respected= ...
    result.elapsed_seconds<=c.hard_seconds&&cumulative<=c.memory_mib_max;

  % Publication is always the last module; directory creation consumes the tag.
  clear before inventory retained_before_clear retained_after_clear;
  before=LOCAL_entry_retained_mib();
  publication=i32_result_output( ...
    'publish',result,c,output,before,cumulative);
  result.resources.modules.result_output=publication;
  result.peak_active_mib=max(result.peak_active_mib, ...
    publication.cumulative_peak_candidate_mib);
  result.resources.actual.cumulative_peak_candidate_mib= ...
    publication.cumulative_peak_candidate_mib;
  if publication.cumulative_peak_candidate_mib>c.memory_mib_max
    [result,~]=LOCAL_execution_stop(result, ...
      'RESOURCE_LIMIT_EXCEEDED_DURING_PUBLICATION', ...
      'The publication active-object proxy exceeded 640 MiB.');
    result.resources.actual.hard_limits_respected=false;
  end
end

%% ==================== Frozen dispatch contract ====================
% This entry-level configuration contains no scientific evaluation formula.

function c=LOCAL_config()
  c=struct('schema','TEP_I3_2_SAME_TRIAL_EVALUATION_CAP_REV_F', ...
    'input_schema','TEP_I3_2_STAGED_FBIE_A1_CERTIFICATE_V1', ...
    'attempt','ecap-a3','source_attempt','fbie-a1', ...
    'khat',1.832770289108157,'beta',0.5,'d',1.0,'R',0.2, ...
    'rho_disk',17,'X_L',-0.5,'X_R',0.5,'L',1.0, ...
    'M',48,'K',97,'delta_c',0.04,'delta_w',0.04, ...
    'anchor_components',[1.8732026085453917e-10, ...
      2.9776880587814564e-15,4.246327820844503e-11], ...
    'anchor_M',2.29786516751043e-10,'anchor_N',4.959111810675795, ...
    'circle_levels',[512,1024,2048], ...
    'image_levels',[32,48,64,96,128,192,256], ...
    'wall_levels',[1024,2048,4096], ...
    'riccati_levels',[512,1024,2048], ...
    'gauss_levels',[32,64,128],'full_p_levels',[8,16,32], ...
    'image_ratio_max',0.80,'spectral_ratio_max',0.50, ...
    'image_remainder_factor',5,'spectral_remainder_factor',2, ...
    'action_ratio_max',0.50,'kernel_oracle_tol',1e-8, ...
    'identity_tol',1e-10,'tail_share_warning',1e-6,'width_target',1e-6, ...
    'pair_batch',4096,'mode_batch',16, ...
    'expected_seconds',1320,'preflight_seconds_max',1500, ...
    'expected_peak_mib',420,'worst_transient_mib',360, ...
    'preflight_mib_max',520,'soft_seconds',1500,'hard_seconds',1800, ...
    'memory_mib_max',640,'retry_count',0);
  c.command=[ ...
    'matlab -batch "addpath(fullfile(pwd,''test'',''i3'',''e-cap'')); ', ...
    'check_e_cap_stream(''ecap-a3'',fullfile(pwd,''test'',''i3'',''e-cap'',', ...
    '''input'',''fbie-a1-certificate.mat''));"'];
end

function result=LOCAL_empty_result(c,input_path)
  result=struct('schema',c.schema,'attempt',c.attempt, ...
    'source_attempt',c.source_attempt,'input_path',input_path, ...
    'command',c.command,'status','I3_2_EXECUTION_UNAVAILABLE', ...
    'scientific_outcome','UNAVAILABLE','cap_status','EMPIRICAL_CAP_UNRESOLVED', ...
    'execution_pass',true,'elapsed_seconds',NaN,'peak_active_mib',0, ...
    'first_execution_blocker',LOCAL_condition('NONE','No execution blocker.'), ...
    'first_empirical_unavailable',LOCAL_condition( ...
      'NOT_REACHED','The empirical cap stage has not been reached.'), ...
    'first_nonblocking_warning',LOCAL_condition('NONE','No warning.'), ...
    'modules',struct(),'certificate_summary',struct(), ...
    'components',struct(),'caps',struct(),'estimator', ...
      struct('interval_available',false), ...
    'tails',struct(),'axis_metrics',struct(),'arithmetic',struct(), ...
    'field_same_partial',struct(),'coverage',LOCAL_empty_coverage(), ...
    'qualification',struct(),'reliability',LOCAL_reliability_flags(), ...
    'nonblocking_warnings',LOCAL_empty_warnings(), ...
    'call_counters',LOCAL_zero_counters(), ...
    'no_resolve_call_counts',LOCAL_zero_counters(), ...
    'audit',struct('module_return_audits',struct(), ...
      'last_use_death',struct(),'no_resolve',struct(), ...
      'allowlisted_eig',struct()), ...
    'resources',struct('modules',struct(),'actual',struct()), ...
    'M_role','artificial-wall total Dirichlet trace order only', ...
    'wall_trace_order_M',48,'wall_trace_coefficient_count',97, ...
    'frozen_certificate_recomputed',false,'trial_redefined',false, ...
    'thresholds_or_levels_tuned',false);
end

%% ==================== Typed module merge and liveness ====================
% Compact diagnostics merge before private owners are cleared and gated.

function [result,cumulative]=LOCAL_merge_module(result,name,module,cumulative)
  result.modules.(name)=struct('available',module.available, ...
    'first_unavailable',module.first_unavailable, ...
    'public_metrics',module.public_metrics, ...
    'audit_summary',module.audit_summary, ...
    'resource_record',module.resource_record);
  result.audit.module_return_audits.(name)=module.audit_summary;
  result.resources.modules.(name)=module.resource_record;
  result.nonblocking_warnings=[result.nonblocking_warnings,module.warnings];
  result.call_counters=LOCAL_add_counters( ...
    result.call_counters,module.call_counters);
  result.no_resolve_call_counts=result.call_counters;
  result.coverage.module_completed.(name)=true;
  result.coverage.module_available.(name)=module.available;
  if strcmp(name,'certificate')
    result.certificate_summary=module.public_metrics;
    result.coverage.fixed_certificate_consumed=module.available;
  end
  cumulative=max(cumulative,module.resource_record.concurrent_peak_candidate_mib);
end

function private=LOCAL_private_science(module)
  private=struct('available',module.available, ...
    'public_metrics',module.public_metrics, ...
    'finest_factors',module.finest_factors, ...
    'cap_signatures',module.cap_signatures);
end

function result=LOCAL_merge_cap(result,cap)
  names={'components','caps','estimator','tails','axis_metrics','arithmetic', ...
    'field_same_partial'};
  for j=1:numel(names), result.(names{j})=cap.(names{j}); end
  result.first_empirical_unavailable=cap.first_empirical_unavailable;
  result.coverage.same_density_actions_computed=true;
  result.coverage.actual_DeltaT_actions_computed= ...
    cap.qualification.actual_T_qualified;
  result.coverage.finite_image_Bloch_actions_computed= ...
    cap.qualification.finite_bloch_qualified;
  result.coverage.all_fresh_computed_modes_included=cap.all_modes_included;
  result.coverage.empirical_numerator_cap_computed=cap.numerator_available;
  result.coverage.empirical_denominator_cap_computed=cap.denominator_available;
  result.coverage.nominal_transform_computed=cap.estimator.interval_available;
end

function [result,cumulative]= ...
    LOCAL_close_resource(result,name,retained_after,cumulative)
  record=result.resources.modules.(name);
  record.retained_after_mib=retained_after;
  candidates=[cumulative,record.concurrent_peak_candidate_mib,retained_after];
  candidates=candidates(isfinite(candidates));
  if isempty(candidates), cumulative=NaN; else, cumulative=max(candidates); end
  record.cumulative_peak_candidate_mib=cumulative;
  result.resources.modules.(name)=record;
  if isfield(result.modules,name)
    result.modules.(name).resource_record=record;
  end
end

function record=LOCAL_unreturned_resource(before,c)
  record=struct( ...
    'retained_before_mib',before,'input_alias_nominal_mib',NaN, ...
    'local_workspace_peak_mib',NaN,'module_exclusive_peak_mib',NaN, ...
    'frozen_streaming_transient_mib',c.worst_transient_mib, ...
    'concurrent_peak_candidate_mib',before+c.worst_transient_mib, ...
    'return_payload_mib',NaN,'retained_after_mib',NaN, ...
    'cumulative_peak_candidate_mib',NaN, ...
    'proxy_semantics',[ ...
      'entry checkpoint with unknown unreturned local peak; deterministic ', ...
      'active-object proxy, not RSS/refcount/allocator accounting']);
end

function [staged,record]=LOCAL_after_wall_prune(staged)
  removed={}; names={'wall_input_unit_512','q_center','branch_port'};
  for j=1:numel(names)
    if isfield(staged.certificate,names{j})
      staged.certificate=rmfield(staged.certificate,names{j});
      removed{end+1}=['finest_factors.staged.certificate.',names{j}]; %#ok<AGROW>
    end
  end
  record=struct('removed_paths',{removed},'unique_last_consumer','wall', ...
    'reachable_owner_after_clear',false);
end

function [staged,record]=LOCAL_after_circle_prune(staged)
  removed={}; names={'eta_unit_256','xi_left_unit_512','xi_right_unit_512', ...
    'center_actual_left_trace','center_actual_right_trace'};
  for j=1:numel(names)
    if isfield(staged.certificate,names{j})
      staged.certificate=rmfield(staged.certificate,names{j});
      removed{end+1}=['finest_factors.staged.certificate.',names{j}]; %#ok<AGROW>
    end
  end
  record=struct('removed_paths',{removed},'unique_last_consumer','circle', ...
    'reachable_owner_after_clear',false);
end

%% ==================== Recursive returned-payload audit ====================
% Exact dense paths are allowlisted; no module receives a blanket exception.

function module=LOCAL_audit_return(module,name)
  expected_root={'available','first_unavailable','public_metrics', ...
    'finest_factors','cap_signatures','audit_summary','warnings', ...
    'call_counters','resource_record'};
  if ~isstruct(module)||~isscalar(module)|| ...
      ~isequal(sort(fieldnames(module)),sort(expected_root(:)))
    error('i32f:ReturnedPayloadSchema', ...
      'Module %s did not return the exact typed root schema.',name);
  end
  if strcmp(name,'certificate')&&module.available
    shapes=module.audit_summary.exact_shape_contract;
    if isempty(shapes)||~all([shapes.pass])
      error('i32f:CertificateExactShape', ...
        'A canonical certificate return path has the wrong mechanical shape.');
    end
  end
  context=LOCAL_shape_context(module,name);
  [fields,numeric,prohibited_field,prohibited_shape]= ...
    LOCAL_inventory(module,name,name,module,context);
  module.audit_summary.returned_field_inventory=fields;
  module.audit_summary.returned_numeric_shape_inventory=numeric;
  module.audit_summary.prohibited_field_count=numel(prohibited_field);
  module.audit_summary.prohibited_shape_count=numel(prohibited_shape);
  module.audit_summary.prohibited_fields={prohibited_field};
  module.audit_summary.prohibited_shapes={prohibited_shape};
  if ~isempty(prohibited_field)||~isempty(prohibited_shape)
    error('i32f:ReturnedPayloadAudit', ...
      'Module %s returned an unregistered dense or raw field.',name);
  end
  info=whos('module');
  module.resource_record.return_payload_mib=info.bytes/2^20;
end

function [fields,numeric,bad_field,bad_shape]= ...
    LOCAL_inventory(value,module,path,root,context)
  fields=struct('path',{},'class',{}); numeric=struct( ...
    'path',{},'class',{},'size',{},'bytes',{});
  bad_field={}; bad_shape={};
  if isstruct(value)
    for k=1:numel(value)
      names=fieldnames(value(k));
      for j=1:numel(names)
        child=[path,'.',names{j}]; item=value(k).(names{j});
        fields(end+1)=struct('path',child,'class',class(item)); %#ok<AGROW>
        if ~LOCAL_registered_schema_path(child,module)
          bad_field{end+1}=child; %#ok<AGROW>
        end
        [f,n,bf,bs]=LOCAL_inventory(item,module,child,root,context);
        fields=[fields,f]; numeric=[numeric,n]; %#ok<AGROW>
        bad_field=[bad_field,bf]; bad_shape=[bad_shape,bs]; %#ok<AGROW>
      end
    end
  elseif iscell(value)
    for j=1:numel(value)
      [f,n,bf,bs]=LOCAL_inventory(value{j},module, ...
        sprintf('%s{%d}',path,j),root,context);
      fields=[fields,f]; numeric=[numeric,n]; %#ok<AGROW>
      bad_field=[bad_field,bf]; bad_shape=[bad_shape,bs]; %#ok<AGROW>
    end
  elseif isnumeric(value)||islogical(value)
    info=whos('value');
    numeric=struct('path',path,'class',class(value), ...
      'size',size(value),'bytes',info.bytes);
    if ismatrix(value)&&all(size(value)>1)&& ...
        ~LOCAL_exact_matrix_shape(path,module,root,context,size(value))
      bad_shape={path};
    end
  end
end

function pass=LOCAL_registered_schema_path(path,module)
  relative=extractAfter(path,strlength(module)+1); relative=char(relative);
  root_fields={'available','first_unavailable','public_metrics', ...
    'finest_factors','cap_signatures','audit_summary','warnings', ...
    'call_counters','resource_record'};
  first=regexp(relative,'^[^.{]+','match','once');
  if isempty(first), pass=false; return; end
  if ~contains(relative,'.')
    pass=ismember(relative,root_fields); return;
  end
  token=regexp(relative,'\.([^.{]+)$','tokens','once');
  if isempty(token), pass=false; return; end
  field=token{1};
  switch first
    case 'first_unavailable'
      pass=ismember(field,{'code','message'});
    case 'warnings'
      pass=ismember(field,{'code','value','blocking'});
    case 'call_counters'
      pass=ismember(field,LOCAL_counter_schema_fields());
    case 'resource_record'
      pass=ismember(field,LOCAL_resource_schema_fields());
    case 'audit_summary'
      pass=ismember(field,LOCAL_audit_schema_fields());
    case 'finest_factors'
      pass=LOCAL_private_schema_path(path,module,'finest_factors');
    case 'cap_signatures'
      pass=LOCAL_private_schema_path(path,module,'cap_signatures');
    case 'public_metrics'
      pass=LOCAL_public_schema_path(path,module);
    otherwise
      pass=false;
  end
end

function fields=LOCAL_counter_schema_fields()
  fields={'candidate_solve_calls','qz_solve_calls','coordinate_solve_calls', ...
    'propagation_solve_calls','wall_density_solve_calls', ...
    'circle_density_solve_calls','schur_solve_calls','proxy_build_calls', ...
    'harmonic_action_calls','image_pair_updates','kress_oracle_calls', ...
    'linton_oracle_calls','actual_deltaT_action_calls', ...
    'finite_bloch_image_updates','riccati_calls','gauss_factor_calls', ...
    'full_p_contraction_calls','full_p_contraction_category', ...
    'small_hermitian_gram_diagnostic_eig_calls', ...
    'gauss_golub_welsch_eig_calls','n_op_signature_parity', ...
    'n_op_combined_gram_parity','final','state','artifact','image', ...
    'three_axis','interaction','shell','field'};
end

function fields=LOCAL_resource_schema_fields()
  fields={'retained_before_mib','input_alias_nominal_mib', ...
    'local_workspace_peak_mib','module_exclusive_peak_mib', ...
    'frozen_streaming_transient_mib','concurrent_peak_candidate_mib', ...
    'return_payload_mib','retained_after_mib', ...
    'cumulative_peak_candidate_mib','proxy_semantics'};
end

function fields=LOCAL_audit_schema_fields()
  fields={'returned_field_inventory','returned_numeric_shape_inventory', ...
    'path','class','size','bytes','prohibited_field_count', ...
    'prohibited_shape_count','prohibited_fields','prohibited_shapes', ...
    'last_use_clear_ledger','field_path','consumer_set', ...
    'unique_last_consumer','last_use','death','clear_status', ...
    'post_clear_local_owner_inventory','name','finest_factor_whitelist', ...
    'compact_signature_whitelist','signature_parity_coverage', ...
    'storage_normalized','mechanical_dimensions','pruning', ...
    'exact_shape_contract','expected_shape','actual_shape', ...
    'registered_consumer_death','certificate_blanket_exception', ...
    'raw_map_blanket_exception','denominator_factor_whitelist', ...
    'retained_certificate_fields','removed_certificate_summary', ...
    'removed_branch_identity_fields','removed_center_duplicate_fields', ...
    'retained_raw_map_whitelist','retained_raw_map_count', ...
    'removed_raw_maps','retained_anchor_fields', ...
    'removed_anchor_dense_summary','canonical_certificate_prefix', ...
    'canonical_raw_map_prefix','no_unregistered_dense_owner_retained', ...
    'compact_provenance_removed_from_private_staged','norm','pass', ...
    'golub_welsch_expression','golub_welsch_parenthesization_frozen', ...
    'common_row_order','raw_native_maps_returned', ...
    'dense_coefficient_ladders_returned','raw_target_samples_returned', ...
    'repaired_conformity_parenthesization_frozen', ...
    'identity_summary_used_as_substitute','small_gram_eig_expression', ...
    'small_gram_eig_is_candidate_solve','dense_augmented_vectors_returned', ...
    'full_matrix_P_powers_retained'};
  fields=[fields,{'normal_orientation','density_coordinate', ...
    'raw_samples_returned','coefficient_ladders_returned','records', ...
    'required_count','total_operations','coverage','coverage_class', ...
    'label','actual','representative','long_value','signature_value', ...
    'n_op','scale','allowance','numerator','ratio','pass', ...
    'maximum_allowance_ratio','expected','observed_exactly_once', ...
    'duplicate_expected','missing_count','duplicate_count','empty_records', ...
    'unexpected_count', ...
    'wall_coverage','circle_coverage','producer_required_count', ...
    'cap_required_count','cap_observed_unique_count', ...
    'producer_coverage_pass','cap_coverage'}];
  fields=[fields,{'K','rminus','rplus','Pminus_shape','Pplus_shape', ...
    'Gminus_shape','Gplus_shape'}];
end

function pass=LOCAL_private_schema_path(path,module,top)
  if strcmp(top,'finest_factors')
    switch module
      case 'certificate'
        prefix='certificate.finest_factors.staged.';
        exact={ ...
          'certificate','certificate.source_attempt','certificate.khat', ...
          'certificate.mu_h','certificate.gamma','certificate.beta', ...
          'certificate.d','certificate.R','certificate.rho_disk', ...
          'certificate.X_L','certificate.X_R','certificate.L', ...
          'certificate.M','certificate.K','certificate.delta_c', ...
          'certificate.delta_w','certificate.q_center','certificate.Pplus', ...
          'certificate.Pminus','certificate.cplus','certificate.cminus', ...
          'certificate.Gplus','certificate.Gminus','certificate.branch_port', ...
          'certificate.branch_port.gamma_m','certificate.eta_unit_256', ...
          'certificate.xi_left_unit_512','certificate.xi_right_unit_512', ...
          'certificate.wall_input_unit_512', ...
          'certificate.center_actual_left_trace', ...
          'certificate.center_actual_right_trace', ...
          'certificate.center_shared_left_trace', ...
          'certificate.center_shared_right_trace', ...
          'certificate.center_left_value_mismatch', ...
          'certificate.center_right_value_mismatch', ...
          'certificate.center_wall_jumps', ...
          'certificate.center_wall_jumps.left_coefficients', ...
          'certificate.center_wall_jumps.right_coefficients', ...
          'certificate.center_wall_jumps.field_lower_uses_shared_trace', ...
          'ordinary_anchor','ordinary_anchor.B_wall','ordinary_anchor.B_circle', ...
          'ordinary_anchor.B_volume','ordinary_anchor.M_tilde', ...
          'ordinary_anchor.N_tilde','ordinary_anchor.lead_field_factor_plus', ...
          'ordinary_anchor.lead_field_factor_minus','ordinary_anchor.tail_minus', ...
          'ordinary_anchor.tail_minus.selected_N','ordinary_anchor.tail_plus', ...
          'ordinary_anchor.tail_plus.selected_N','ordinary_anchor.first_level_indices', ...
          'ordinary_anchor.first_level_indices.minus_physical_start', ...
          'ordinary_anchor.first_level_indices.plus_physical_start', ...
          'ordinary_anchor.first_level_indices.minus_selected_N', ...
          'ordinary_anchor.first_level_indices.plus_selected_N','raw_maps', ...
          'raw_maps.delta_plus','raw_maps.delta_minus', ...
          'raw_maps.circle_jump_plus','raw_maps.circle_jump_minus', ...
          'raw_maps.Jplus','raw_maps.Jminus','raw_maps.wall_common_y_1024', ...
          'raw_maps.wall_common_value_1024','raw_maps.wall_input_unit_512'};
        if strcmp(path,'certificate.finest_factors')|| ...
            strcmp(path,'certificate.finest_factors.staged')
          pass=true; return;
        end
        suffix=char(extractAfter(path,strlength(prefix)));
        pass=startsWith(path,prefix)&&ismember(suffix,exact);
      case 'lifting'
        pass=ismember(path,{'lifting.finest_factors', ...
          'lifting.finest_factors.circle_weights', ...
          'lifting.finest_factors.collar_weights', ...
          'lifting.finest_factors.wall_lift_weights', ...
          'lifting.finest_factors.wall_trace'});
      case 'wall'
        pass=ismember(path,{'wall.finest_factors', ...
          'wall.finest_factors.normal_minus','wall.finest_factors.normal_plus', ...
          'wall.finest_factors.defect_left_minus', ...
          'wall.finest_factors.defect_left_plus', ...
          'wall.finest_factors.defect_right_minus', ...
          'wall.finest_factors.defect_right_plus', ...
          'wall.finest_factors.center_wall', ...
          'wall.finest_factors.center_wall.left', ...
          'wall.finest_factors.center_wall.right'});
      case 'circle'
        pass=ismember(path,{'circle.finest_factors', ...
          'circle.finest_factors.jump_minus','circle.finest_factors.jump_plus', ...
          'circle.finest_factors.delta_minus','circle.finest_factors.delta_plus'});
      case 'fullp_cap'
        pass=strcmp(path,'fullp_cap.finest_factors');
      otherwise
        pass=false;
    end
    return;
  end
  if ismember(module,{'certificate','lifting'})
    pass=strcmp(path,[module,'.cap_signatures']); return;
  end
  if strcmp(module,'wall')
    roots={'wall.cap_signatures','wall.cap_signatures.output', ...
      'wall.cap_signatures.output_pairs','wall.cap_signatures.joint'};
  elseif strcmp(module,'circle')
    roots={'circle.cap_signatures','circle.cap_signatures.image', ...
      'circle.cap_signatures.image_pairs','circle.cap_signatures.angular', ...
      'circle.cap_signatures.angular_pairs','circle.cap_signatures.joint'};
  else
    roots={'fullp_cap.cap_signatures','fullp_cap.cap_signatures.final_norms', ...
      'fullp_cap.cap_signatures.artifact_norms', ...
      'fullp_cap.cap_signatures.producer_parity', ...
      'fullp_cap.cap_signatures.endpoint_parity'};
  end
  if any(strcmp(path,roots)), pass=true; return; end
  if strcmp(module,'fullp_cap')
    relative=extractAfter(path,'fullp_cap.cap_signatures.');
    relative=char(relative); branch=regexp(relative,'^[^.{]+','match','once');
    token=regexp(path,'\.([^.{]+)$','tokens','once');
    if isempty(branch)||isempty(token), pass=false; return; end
    if ismember(branch,{'final_norms','artifact_norms'})
      allowed={'wall_norm','circle_norm','volume_norm','wall_length', ...
        'circle_length','volume_length'};
    elseif ismember(branch,{'producer_parity','endpoint_parity'})
      allowed={'records','required_count','pass','total_operations', ...
        'maximum_allowance_ratio','coverage','expected', ...
        'observed_exactly_once','duplicate_expected','missing_count', ...
        'duplicate_count','unexpected_count','empty_records', ...
        'wall_coverage','circle_coverage', ...
        'producer_required_count','cap_required_count', ...
        'cap_observed_unique_count','producer_coverage_pass','cap_coverage', ...
        'label','coverage_class','actual','representative','long_value', ...
        'signature_value','n_op','scale','allowance','numerator','ratio'};
    else
      allowed={};
    end
    pass=ismember(token{1},allowed); return;
  end
  token=regexp(path,'\.([^.{]+)$','tokens','once');
  if isempty(token), pass=false; return; end
  allowed={'wall','circle','volume','volume_wall','volume_circle', ...
    'output','output_pairs','image','image_pairs','angular','angular_pairs', ...
    'joint','pair_to_final','actual_output_N','actual_output_N','J', ...
    'target_nodes','image_J','angular_nodes','riccati_level','gauss_level', ...
    'selected_full_p_N','common_row_order','producer_parity_required', ...
    'endpoint_id','component','row_order','Nminus','Nplus','center_squared', ...
    'augmented_length', ...
    'minus','plus','W','direct_squared_terms','tail_input_audit','rows', ...
    'state_dimension','finite','signature_parity','left_endpoint_id', ...
    'right_endpoint_id','center_difference_squared', ...
    'minus_direct_difference_squared_terms', ...
    'plus_direct_difference_squared_terms','left_norm_scale', ...
    'right_norm_scale','label','coverage_class','actual','representative', ...
    'long_value','signature_value','n_op','scale','allowance','numerator', ...
    'ratio','pass','records','required_count','total_operations', ...
    'maximum_allowance_ratio','coverage','expected','observed_exactly_once', ...
    'duplicate_expected','missing_count','duplicate_count','empty_records', ...
    'unexpected_count', ...
    'wall_coverage','circle_coverage','producer_required_count', ...
    'cap_required_count','cap_observed_unique_count','producer_coverage_pass', ...
    'cap_coverage','wall_norm','circle_norm','volume_norm','wall_length', ...
    'circle_length','volume_length'};
  pass=ismember(token{1},allowed);
end

function pass=LOCAL_public_schema_path(path,module)
  prefix=[module,'.public_metrics.'];
  if ~startsWith(path,prefix), pass=false; return; end
  relative=char(extractAfter(path,strlength(prefix)));
  branch=regexp(relative,'^[^.{]+','match','once');
  top=LOCAL_public_top_fields(module);
  if isempty(branch)||~ismember(branch,top), pass=false; return; end
  if ~contains(relative,'.'), pass=true; return; end
  parts=strsplit(relative,'.');
  child=regexp(parts{2},'^[^\{]+','match','once');
  if isempty(child)|| ...
      ~ismember(child,LOCAL_public_branch_children(module,branch))
    pass=false; return;
  end
  token=regexp(relative,'\.([^.{]+)$','tokens','once');
  if isempty(token), pass=false; return; end
  % Each recursive leaf is scoped by module, top branch, and a literal
  % immediate child.  The terminal vocabulary is therefore not a global
  % leaf-name exception and cannot migrate between public branches.
  pass=ismember(token{1},LOCAL_public_schema_fields(module));
end

function fields=LOCAL_public_branch_children(module,branch)
  metric={'numerator','left_norm','right_norm','zero_component','scale', ...
    'ratio','threshold','pass'};
  parity={'records','required_count','pass','total_operations', ...
    'maximum_allowance_ratio','coverage','expected', ...
    'observed_exactly_once','duplicate_expected','missing_count', ...
    'duplicate_count','unexpected_count','empty_records', ...
    'wall_coverage','circle_coverage','producer_required_count', ...
    'cap_required_count','cap_observed_unique_count', ...
    'producer_coverage_pass','cap_coverage'};
  switch module
    case 'certificate'
      switch branch
        case 'identity'
          fields={'finite','dimensions','labels','rminus','rplus','K', ...
            'rminus_equals_K','rplus_equals_K', ...
            'frozen_scalar_relative_defect','q_norm_defect', ...
            'Gplus_relative_defect','Gminus_relative_defect', ...
            'mu_relative_defect','gamma_relative_defect', ...
            'branch_and_Wood','center_traces','raw_map_schema', ...
            'ordinary_anchor','M_role','circle_density_nodes', ...
            'wall_density_orders','certificate_trial_redefined','pass'};
        case 'input_storage_conversion'
          fields={'path','original_class','original_size','semantic_range', ...
            'original_scalar_value','original_min','original_max', ...
            'maximum_absolute_value','within_flintmax','exact_roundtrip', ...
            'converted_class','downstream_arithmetic','pass'};
        case 'input_contract'
          fields={'schema','source_attempt','staging_only', ...
            'formal_runtime_must_not_read_historical_output', ...
            'no_resolve_required','M_role','eta_source_nodes', ...
            'wall_source_orders','density_coordinate','circle_basis', ...
            'wall_basis','circle_ordering','wall_output_ordering', ...
            'branch_classification_encoding','circle_value_only_lift', ...
            'wall_value_only_lift','lift_shape','exact_lift_amplitude_rule'};
        case 'historical_diagnostics'
          fields={'circle_action_metric','circle_angular_tail_metric', ...
            'outside_M_metric'};
        case 'ordinary_anchor'
          fields={'B_wall','B_circle','B_volume','M_tilde','N_tilde', ...
            'tail_minus_selected_N','tail_plus_selected_N','ordinary_double'};
        otherwise
          fields={};
      end
    case 'lifting'
      switch branch
        case 'circle'
          fields={'steps','order_min','order_max','count','positive', ...
            'minimum','maximum','norm','energy_identity_defect', ...
            'low_order_bessel_metric'};
        case {'collar','wall_lift'}
          fields={'gauss','order_min','order_max','count','finite', ...
            'nonnegative','minimum','maximum','norm'};
        case 'wall_trace'
          fields={'count','finite','positive','minimum','maximum','norm'};
        case 'refinement'
          fields={'riccati','collar_gauss','wall_lift_gauss'};
        case 'gauss_eig_category'
          fields={'n32','n64','n128'};
        otherwise
          fields={};
      end
    case 'wall'
      switch branch
        case 'final'
          fields={'N','order_min','order_max','finite','raw_left_norm', ...
            'raw_right_norm','flux_left_norm','flux_right_norm', ...
            'defect_left_norm','defect_right_norm'};
        case 'refinement'
          fields={'from_orders','to_orders','raw_left','raw_right', ...
            'flux_left','flux_right'};
        case 'repaired_value_metric'
          fields=metric;
        case 'producer_signature_parity'
          fields=parity;
        otherwise
          fields={};
      end
    case 'circle'
      switch branch
        case {'image_levels','angular_levels'}
          fields={'label','J','target_nodes','order_min','order_max', ...
            'delta_norm','jump_norm','actual_deltaT_norm', ...
            'dS_difference_zeta_norm','wall_normal_norm', ...
            'normal_decomposition_metric','finite'};
        case 'wronskian'
          fields={'exterior','interior', ...
            'minus_S_exterior_minus_interior_jump_is_plus_zeta'};
        case {'repaired_value_metric','angular_action_metric'}
          fields=metric;
        case 'actual_T_action'
          fields={'available','qualified','orientation','definition', ...
            'image_metrics','angular_metrics','image_omega','angular_omega', ...
            'image_ratio_threshold','angular_ratio_threshold','dyadic_pass', ...
            'staggered_pass','cross_finite','angular_pass', ...
            'maximum_contraction_ratio','all_level_maps_stored_separately'};
        case 'finite_image_bloch'
          fields={'available','qualified','levels','safe_target_x','paired_y', ...
            'physical_Bloch_phase','derivative', ...
            'same_fixed_eta_and_xi_consumed','finite_image_J','threshold', ...
            'angular_target_grid_dependency','maximum_final_ratio', ...
            'fail_open','exact_continuous_QP_Bloch_is_structural', ...
            'finite_image_action_enclosed','message'};
        case 'oracles'
          fields={'free_singular','linton_off_axis','high_order_recurrence', ...
            'circle_1024_to_2048','production_uses_oracle_matrix', ...
            'independent_reference'};
        case 'structural_metrics'
          fields={'wall_repaired_identity','circle_repaired_identity', ...
            'circle_raw_value_jump_norm','circle_value_lift_plus_norm', ...
            'circle_value_lift_minus_norm','center_left_repaired_identity', ...
            'center_right_repaired_identity','safe_rim_value', ...
            'safe_rim_derivative','jump_sign_maximum', ...
            'zeta_equals_minus_sigma_semantic','density_scale_roundtrip', ...
            'bloch','circle_normal_decomposition_maximum', ...
            'circle_normal_decomposition','free_oracle', ...
            'maximum_required_ratio','pass','eta_coefficient_size', ...
            'repaired_conformity_parenthesization_frozen', ...
            'identity_summary_used_as_substitute'};
        case 'producer_signature_parity'
          fields=parity;
        otherwise
          fields={};
      end
    case 'fullp_cap'
      switch branch
        case 'components'
          fields={'wall','circle','volume'};
        case 'caps'
          fields={'M_tilde','N_tilde','epsilon_W_emp','epsilon_Gamma_emp', ...
            'epsilon_V_emp','epsilon_M_emp','epsilon_N_emp', ...
            'numerator_triangle_combination','same_trial_evaluation_cap', ...
            'rigorous_cap','directed_rounding'};
        case 'estimator'
          fields={'available','q_emp','interval_available', ...
            'lambda_lower','lambda_upper', ...
            'k_lower','k_upper','width','width_target','resolution_pass', ...
            'label','ordinary_double','strict_conditional_theorem_triggered', ...
            'reliable'};
        case 'tails'
          fields={'components','state'};
        case 'axis_metrics'
          fields={'axes','shells'};
        case 'arithmetic'
          fields={'wall','circle','volume'};
        case 'field_same_partial'
          fields={'available','artifact_N_tilde','same_partial', ...
            'absolute_discrepancy','downward_observed', ...
            'comparison_operations','comparison_omega','arithmetic_paths', ...
            'arithmetic_spread','arithmetic_operations','arithmetic_omega', ...
            'R_N','epsilon_N_emp','growth_N','growth_values', ...
            'growth_increments','growth_roundoff_tolerance', ...
            'growth_is_diagnostic_only','omitted_positive_tail_added_to_cap', ...
            'dependency_audit'};
        case 'artifact_association'
          fields={'wall','circle','volume'};
        case 'artifact_audit'
          fields={'wall_common','circle_delta_plus_norm', ...
            'circle_delta_minus_norm','circle_jump_plus_norm', ...
            'circle_jump_minus_norm','wall_jump_plus_norm', ...
            'wall_jump_minus_norm','first_level_index_contract_pass', ...
            'raw_maps_returned','common_coordinate_reconstruction'};
        case 'signature_parity'
          fields=parity;
        case 'combined_gram_parity'
          fields={'records','required_count','pass','total_operations', ...
            'maximum_allowance_ratio','actual_count', ...
            'representative_count','coverage'};
        case 'qualification'
          fields={'kernel_oracle_available','kernel_qualified', ...
            'conformity_qualified','actual_T_qualified', ...
            'finite_bloch_qualified','signature_parity_qualified', ...
            'combined_gram_parity_qualified'};
        case 'first_empirical_unavailable'
          fields={'code','message'};
        case 'full_p_counter_audit'
          fields={'categories','recorded','expected','pass'};
        case 'allowlisted_eig_audit'
          fields={'small_hermitian_gram_diagnostic_eig_calls', ...
            'expected_small_gram','gauss_golub_welsch_eig_calls_here', ...
            'candidate_solve_calls','pass'};
        otherwise
          fields={};
      end
    otherwise
      fields={};
  end
end

function fields=LOCAL_public_top_fields(module)
  switch module
    case 'certificate'
      fields={'identity','input_storage_conversion','input_contract', ...
        'historical_diagnostics','ordinary_anchor','M_role', ...
        'wall_trace_order_M','wall_trace_coefficient_count', ...
        'certificate_trial_redefined'};
    case 'lifting'
      fields={'circle','collar','wall_lift','wall_trace','refinement', ...
        'gauss_eig_category','gauss_golub_welsch_eig_calls', ...
        'gauss_eig_identity_pass','weights_available'};
    case 'wall'
      fields={'levels','source_orders','source_coefficients_fixed','final', ...
        'refinement','repaired_value_metric','producer_signature_parity', ...
        'repaired_value_qualified','dense_native_ladders_returned'};
    case 'circle'
      fields={'image_levels','angular_levels','wronskian', ...
        'repaired_value_metric','actual_T_action','finite_image_bloch', ...
        'angular_action_metric','oracles','structural_metrics', ...
        'producer_signature_parity','core_maps_available', ...
        'kernel_oracles_available','kernel_qualified', ...
        'actual_T_action_qualified','finite_image_Bloch_qualified', ...
        'conformity_qualified','all_computed_circle_modes_retained', ...
        'circle_order_min','circle_order_max','circle_order_count', ...
        'wall_M_role','dense_coefficient_ladders_returned', ...
        'raw_target_samples_returned'};
    case 'fullp_cap'
      fields={'components','caps','estimator','tails','axis_metrics', ...
        'arithmetic','field_same_partial','artifact_association', ...
        'artifact_audit','signature_parity','combined_gram_parity', ...
        'qualification','numerator_available','denominator_available', ...
        'all_modes_included','first_empirical_unavailable', ...
        'unresolved_axes','full_p_counter_audit','allowlisted_eig_audit', ...
        'raw_value_enters_volume_only','raw_wall_normal_enters_wall_only', ...
        'raw_circle_normal_enters_circle_only', ...
        'uncomputed_tails_outward_enclosed'};
    otherwise
      fields={};
  end
end

function fields=LOCAL_public_schema_fields(module)
  common={'available','pass','finite','qualified','label','code','message', ...
    'value','numerator','left_norm','right_norm','zero_component','scale', ...
    'ratio','threshold','allowance','remainder','maximum_ratio', ...
    'maximum_relative_defect','minimum','maximum','norm','count','levels', ...
    'order_min','order_max','source_nodes','target_nodes','actual','expected', ...
    'recorded','records','required_count','total_operations','coverage', ...
    'coverage_class','representative','actual_count','representative_count', ...
    'maximum_allowance_ratio','observed_exactly_once','duplicate_expected', ...
    'missing_count','duplicate_count','empty_records','long_value', ...
    'unexpected_count', ...
    'signature_value','n_op','n_gram','object_class','side','stack_norm', ...
    'sum_norm','absolute_threshold','left_endpoint_id','right_endpoint_id', ...
    'endpoint_identity_match','scalar_shift','factor_shift','left_norm_scale', ...
    'right_norm_scale','center_difference_squared', ...
    'minus_direct_difference_squared_terms', ...
    'plus_direct_difference_squared_terms','zero_scale','roundoff_allowance', ...
    'finite_partial','tail_share','certified','N','Nminus','Nplus','Nmax', ...
    'minus','plus','center_squared','direct_minus_squares', ...
    'direct_plus_squares','first_four_direct_quadratic_actions', ...
    'direct_rows_zero_padded','tail_slots_separate','a_hi', ...
    'power_association_defect','gram_association_defect','left_WN_norm', ...
    'alternate_WN_norm','rows','state_dimension','family_grams_added_before_tail', ...
    'component','axis','family','omega','near_zero','contraction_pass', ...
    'available','d1','d2','differences','dyadic_pass','staggered_pass', ...
    'cross_finite','all_projected_endpoint_parity','endpoint_parity', ...
    'signature_parity','combined_gram_parity','actual_shape','expected_shape'};
  switch module
    case 'certificate'
      specific={'identity','input_storage_conversion','input_contract', ...
        'historical_diagnostics','ordinary_anchor','M_role', ...
        'wall_trace_order_M','wall_trace_coefficient_count', ...
        'certificate_trial_redefined','finite','dimensions','labels','rminus', ...
        'rplus','K','rminus_equals_K','rplus_equals_K', ...
        'frozen_scalar_relative_defect','q_norm_defect', ...
        'Gplus_relative_defect','Gminus_relative_defect', ...
        'mu_relative_defect','gamma_relative_defect','branch_and_Wood', ...
        'center_traces','raw_map_schema','circle_density_nodes', ...
        'wall_density_orders','fields_available','exact_Wood', ...
        'relative_Wood_margin','beta_relative_defect','gamma_relative_defect', ...
        't_relative_defect','reference_relative_defect','class_pass', ...
        'sign_and_axis_pass','stored_qualification_pass','relative_defects', ...
        'stored_center_relative_defects','certificate_metrics', ...
        'stored_center_metrics','left_parent_trace_scale', ...
        'right_parent_trace_scale','stored_center_fields_available', ...
        'jump_dimensions','actual_trace_formula','shared_trace_formula', ...
        'actual_left','actual_right','shared_left','shared_right', ...
        'mismatch_left','mismatch_right','repaired_left','repaired_right', ...
        'absolute_defect','wall_order_relative_defect', ...
        'circle_order_relative_defect','circle_theta_relative_defect', ...
        'wall_common_grid_relative_defect','center_wall_jump_association_defect', ...
        'scalar_relative_defect','factor_dimensions','factor_finite', ...
        'selected_N_minus_plus','index_contract_pass', ...
        'same_finite_field_partial_center','path','original_class', ...
        'original_size','semantic_range','original_scalar_value', ...
        'original_min','original_max','maximum_absolute_value', ...
        'within_flintmax','exact_roundtrip','converted_class', ...
        'downstream_arithmetic','class','size','name','schema', ...
        'source_attempt','staging_only','formal_runtime_must_not_read_historical_output', ...
        'no_resolve_required','density_coordinate','circle_basis','wall_basis', ...
        'circle_ordering','wall_output_ordering', ...
        'branch_classification_encoding','circle_value_only_lift', ...
        'wall_value_only_lift','lift_shape','exact_lift_amplitude_rule', ...
        'B_wall','B_circle','B_volume','M_tilde','N_tilde', ...
        'selected_N','tail_minus_selected_N','tail_plus_selected_N', ...
        'circle_action_metric','circle_angular_tail_metric', ...
        'outside_M_metric','computed_modes_all_in_residual'};
    case 'lifting'
      specific={'circle','collar','wall_lift','wall_trace','refinement', ...
        'gauss_eig_category','gauss_golub_welsch_eig_calls', ...
        'gauss_eig_identity_pass','weights_available','steps','positive', ...
        'energy_identity_defect','low_order_bessel_metric','gauss', ...
        'nonnegative','riccati','collar_gauss','wall_lift_gauss', ...
        'n32','n64','n128'};
    case 'wall'
      specific={'source_orders','source_coefficients_fixed','final', ...
        'refinement','repaired_value_metric','producer_signature_parity', ...
        'repaired_value_qualified','dense_native_ladders_returned', ...
        'actual_output_N','raw_left_norm','raw_right_norm','flux_left_norm', ...
        'flux_right_norm','defect_left_norm','defect_right_norm', ...
        'from_orders','to_orders','raw_left','raw_right','flux_left', ...
        'flux_right','wall_coverage','circle_coverage'};
    case 'circle'
      specific={'image_levels','angular_levels','image_metrics','angular_metrics', ...
        'actual_T_action','actual_T_action_qualified','finite_image_bloch', ...
        'finite_image_Bloch_qualified','oracles','kernel_oracles_available', ...
        'kernel_qualified','structural_metrics','conformity_qualified', ...
        'angular_action_metric','producer_signature_parity', ...
        'all_computed_circle_modes_retained','M_role','wall_M_role', ...
        'wronskian','circle_order_min','circle_order_max','circle_order_count', ...
        'raw_target_samples_returned','dense_coefficient_ladders_returned', ...
        'image_public','angular_public','J','delta_norm','jump_norm', ...
        'actual_deltaT_norm','dS_difference_zeta_norm','wall_normal_norm', ...
        'normal_decomposition_metric','raw_value_jump_norm','actions_finite', ...
        'image_J','angular_nodes','riccati_level','gauss_level', ...
        'selected_full_p_N','image_omega','angular_omega', ...
        'image_ratio_threshold','angular_ratio_threshold', ...
        'maximum_required_ratio','actual_T_out_minus_T_in', ...
        'metric_records','columns','modes','D_jump','dS_jump', ...
        'streamed_active_Kress_circulant_row','production_matrix_reused', ...
        'both_wavenumbers_all_one_sided_actions_checked', ...
        'normal_orientation','density_coordinate','free_singular', ...
        'Ntheta','minus_S_zeta_exterior_minus_interior_jump_is_plus_zeta', ...
        'minus_S_exterior_minus_interior_jump_is_plus_zeta', ...
        'D_jump_defect','dS_jump_defect','scaled_log_products', ...
        'linton_off_axis','high_order_recurrence','circle_1024_to_2048', ...
        'production_uses_oracle_matrix','points','tuples','project_sign', ...
        'relative_wood_margin','branch_ledger','production_image_tail_holdout', ...
        'manufactured_total_image_tail_holdout', ...
        'manufactured_termwise_harmonic_actions', ...
        'wall_circle_cross_action_oracle','image_tail_holdout_maximum', ...
        'image_tail_holdout_enters_kernel_1e8_gate', ...
        'Bloch_Helmholtz_branch_identities','coordinate_map','orders', ...
        'boundary','image_radii','image','scaled_log_coordinate', ...
        'clipping_used','argument','with_J','H_recurrence', ...
        'H_derivative_identity','J_recurrence','J_derivative_identity', ...
        'Wronskian','a','M1','M2','beta_m','t_m','gamma_m', ...
        'classification','outgoing_sign_pass','axis_pass','exact_Wood', ...
        'production','reference','mixed_derivative_reference', ...
        'target_finite_difference_used','zero_reference','images','target', ...
        'circle_to_wall_D_and_minusS', ...
        'wall_to_circle_value_and_global_r_normal','circle_source_nodes', ...
        'wall_source_nodes', ...
        'target_Bloch_phase','source_inverse_phase','Helmholtz_identity', ...
        'propagating_count','evanescent_count','outgoing_gamma_sign_pass', ...
        'top_value','bottom_value','top_global_y_derivative', ...
        'bottom_global_y_derivative','physical_Bloch_phase', ...
        'safe_target_x','paired_y','derivative', ...
        'same_fixed_eta_and_xi_consumed','value_metric','flux_metric', ...
        'physical_to_periodic_gauge_roundtrip','source_inverse_phase', ...
        'target_phase','source_phase','core_maps_available', ...
        'free_oracle','linton_off_axis','recurrence_oracle_attached_separately', ...
        'circle_repaired_identity','wall_repaired_identity', ...
        'center_left_repaired_identity','center_right_repaired_identity', ...
        'safe_rim_value','safe_rim_derivative','jump_sign_maximum', ...
        'zeta_equals_minus_sigma_semantic','density_scale_roundtrip', ...
        'bloch','eta_coefficient_size', ...
        'raw_value_jump_norm','circle_value_lift_minus_norm', ...
        'circle_value_lift_plus_norm','circle_normal_decomposition', ...
        'circle_normal_decomposition_maximum','wall_fourier_part_structural', ...
        'finite_image_target_Bloch_consumed_here', ...
        'repaired_conformity_parenthesization_frozen', ...
        'identity_summary_used_as_substitute','maximum_final_ratio', ...
        'finite_image_J','angular_target_grid_dependency', ...
        'exact_continuous_QP_Bloch_is_structural', ...
        'finite_image_action_enclosed','fail_open','orientation','definition', ...
        'angular_pass','maximum_contraction_ratio', ...
        'all_level_maps_stored_separately'};
    case 'fullp_cap'
      specific={'components','caps','estimator','tails','axis_metrics', ...
        'arithmetic','field_same_partial','artifact_association', ...
        'artifact_audit','qualification','numerator_available', ...
        'denominator_available','all_modes_included', ...
        'first_empirical_unavailable','unresolved_axes','full_p_counter_audit', ...
        'allowlisted_eig_audit','raw_value_enters_volume_only', ...
        'raw_wall_normal_enters_wall_only','raw_circle_normal_enters_circle_only', ...
        'uncomputed_tails_outward_enclosed','wall','circle','volume', ...
        'caps','epsilon_W_emp','epsilon_Gamma_emp','epsilon_V_emp', ...
        'epsilon_M_emp','epsilon_N_emp','M_tilde','N_tilde', ...
        'numerator_triangle_combination','same_trial_evaluation_cap', ...
        'rigorous_cap','directed_rounding','q_emp','interval_available', ...
        'lambda_lower','lambda_upper','k_lower','k_upper','width', ...
        'width_target','resolution_pass','ordinary_double', ...
        'strict_conditional_theorem_triggered','reliable','components', ...
        'state','mandatory_state_tail','selected_index','selected_N', ...
        'ordinary_candidate','artifact_scalar','artifact_common_factor_norm', ...
        'fresh_final','observed_shift','comparison_operations', ...
        'comparison_omega','A','association_pass','reverse_triangle_pass', ...
        'factor_metric', ...
        'wall_common','grid_nodes','canonical_output_orders', ...
        'Fourier_evaluation_not_nearest_node','shared_left_norm', ...
        'shared_right_norm','circle_delta_plus_norm','circle_delta_minus_norm', ...
        'circle_jump_plus_norm','circle_jump_minus_norm','wall_jump_plus_norm', ...
        'wall_jump_minus_norm','first_level_index_contract_pass', ...
        'raw_maps_returned','common_coordinate_reconstruction','axes','shells', ...
        'image_circle','image_volume','angular_circle','angular_volume', ...
        'wall_wall','wall_volume','riccati_circle','gauss_volume', ...
        'fullp_wall','fullp_circle','fullp_volume','interaction', ...
        'axis','component','dyadic_pass','staggered_pass','cross_finite', ...
        'maximum_ratio','shell_1','shell_2','shell_1_metric','shell_2_metric', ...
        'fourier_tail_allowance','arithmetic_remainder','epsilon_emp', ...
        'axis_remainder_sum','anchor','paths','maximum_pairwise_spread', ...
        'operations','component_scale','compensated_squared', ...
        'compensated_negative_significant','artifact_N_tilde','same_partial', ...
        'absolute_discrepancy','downward_observed','arithmetic_paths', ...
        'arithmetic_spread','arithmetic_operations','arithmetic_omega','R_N', ...
        'growth_N','growth_values','growth_increments', ...
        'growth_roundoff_tolerance','growth_is_diagnostic_only', ...
        'omitted_positive_tail_added_to_cap','dependency_audit', ...
        'consumed_objects','excluded_evaluator_objects','formula', ...
        'same_partial_only','structural_zero_axes_proved', ...
        'evaluator_boundary_actions_consumed','kernel_oracle_available', ...
        'kernel_qualified','conformity_qualified','actual_T_qualified', ...
        'finite_bloch_qualified','signature_parity_qualified', ...
        'combined_gram_parity_qualified','categories','unit', ...
        'small_hermitian_gram_diagnostic_eig_calls','expected_small_gram', ...
        'gauss_golub_welsch_eig_calls_here', ...
        'candidate_solve_calls','producer_required_count','cap_required_count', ...
        'cap_observed_unique_count','producer_coverage_pass','cap_coverage', ...
        'wall_coverage','circle_coverage','joint_shift', ...
        'official_final_leg_sum','joint_metrics','official_leg_metrics', ...
        'representative_finest_N16_to_N32_signature_parity', ...
        'joint_actual_producer_parity','maximum_share', ...
        'center_QZ_value_mismatch_shell_structural_zero', ...
        'center_QZ_source_bandwidth', ...
        'combined_joint_end_to_end_representative_only'};
    otherwise
      specific={};
  end
  fields=unique([common,specific]);
end

function context=LOCAL_shape_context(module,name)
  context=struct('K',NaN,'rminus',NaN,'rplus',NaN, ...
    'wall_rows',4096,'circle_rows',2048);
  if strcmp(name,'certificate')&&module.available
    z=module.finest_factors.staged.certificate;
    context.K=z.K; context.rminus=size(z.Pminus,1); ...
      context.rplus=size(z.Pplus,1);
  elseif strcmp(name,'wall')&&module.available
    e=module.cap_signatures.output{1}.wall;
    context.rminus=e.minus.tail_input_audit.state_dimension;
    context.rplus=e.plus.tail_input_audit.state_dimension;
    context.K=max(context.rminus,context.rplus);
  elseif strcmp(name,'circle')&&module.available
    e=module.cap_signatures.image{1}.circle;
    context.rminus=e.minus.tail_input_audit.state_dimension;
    context.rplus=e.plus.tail_input_audit.state_dimension;
    context.K=max(context.rminus,context.rplus);
  end
end

function pass=LOCAL_exact_matrix_shape(path,module,root,context,actual)
  pass=false;
  if strcmp(module,'certificate')
    contract=root.audit_summary.exact_shape_contract;
    for j=1:numel(contract)
      full=['certificate.',contract(j).field_path];
      if strcmp(path,full)
        pass=contract(j).pass&&isequal(actual,contract(j).expected_shape);
        return;
      end
    end
    return;
  end
  if strcmp(module,'lifting'), return; end
  if strcmp(module,'wall')
    exact={ ...
      'wall.finest_factors.normal_minus',[context.wall_rows,context.rminus]; ...
      'wall.finest_factors.normal_plus',[context.wall_rows,context.rplus]; ...
      'wall.finest_factors.defect_left_minus',[context.wall_rows,context.rminus]; ...
      'wall.finest_factors.defect_left_plus',[context.wall_rows,context.rplus]; ...
      'wall.finest_factors.defect_right_minus',[context.wall_rows,context.rminus]; ...
      'wall.finest_factors.defect_right_plus',[context.wall_rows,context.rplus]};
    pass=LOCAL_match_exact_shape(path,actual,exact);
    if pass, return; end
    minus='^wall\.cap_signatures\.(output\{[1-3]\}|joint)\.(wall|volume_wall)\.minus\.W$';
    plus='^wall\.cap_signatures\.(output\{[1-3]\}|joint)\.(wall|volume_wall)\.plus\.W$';
    if ~isempty(regexp(path,minus,'once'))
      pass=isequal(actual,[context.rminus,context.rminus]); return;
    elseif ~isempty(regexp(path,plus,'once'))
      pass=isequal(actual,[context.rplus,context.rplus]); return;
    end
    return;
  end
  if strcmp(module,'circle')
    exact={ ...
      'circle.finest_factors.jump_minus',[context.circle_rows,context.rminus]; ...
      'circle.finest_factors.jump_plus',[context.circle_rows,context.rplus]; ...
      'circle.finest_factors.delta_minus',[context.circle_rows,context.rminus]; ...
      'circle.finest_factors.delta_plus',[context.circle_rows,context.rplus]; ...
      'circle.public_metrics.oracles.linton_off_axis.points',[5,2]; ...
      'circle.public_metrics.oracles.linton_off_axis.tuples',[3,4]; ...
      'circle.public_metrics.oracles.linton_off_axis.production_image_tail_holdout',[5,6]; ...
      'circle.public_metrics.oracles.linton_off_axis.manufactured_total_image_tail_holdout.relative_defects',[5,4]};
    exact(end+1,:)={ ...
      'circle.public_metrics.oracles.linton_off_axis.wall_circle_cross_action_oracle.circle_to_wall_D_and_minusS',[5,2]};
    exact(end+1,:)={ ...
      'circle.public_metrics.oracles.linton_off_axis.wall_circle_cross_action_oracle.wall_to_circle_value_and_global_r_normal',[5,2]};
    pass=LOCAL_match_exact_shape(path,actual,exact);
    if pass, return; end
    if ~isempty(regexp(path, ...
        '^circle\.cap_signatures\.(image\{[1-7]\}|angular\{[1-3]\}|joint)\.(circle|volume_circle)\.minus\.W$','once'))
      pass=isequal(actual,[context.rminus,context.rminus]); return;
    elseif ~isempty(regexp(path, ...
        '^circle\.cap_signatures\.(image\{[1-7]\}|angular\{[1-3]\}|joint)\.(circle|volume_circle)\.plus\.W$','once'))
      pass=isequal(actual,[context.rplus,context.rplus]); return;
    elseif ~isempty(regexp(path, ...
        '^circle\.public_metrics\.oracles\.free_singular\.levels\.relative_defects$','once'))
      pass=isequal(actual,[5,13]); return;
    end
    return;
  end
  if strcmp(module,'fullp_cap')
    if ~isempty(regexp(path, ...
        '^fullp_cap\.public_metrics\.tails\.components\.(wall|circle|volume)\.first_four_direct_quadratic_actions$','once'))
      pass=isequal(actual,[4,3]);
    end
  end
end

function pass=LOCAL_match_exact_shape(path,actual,exact)
  pass=false;
  for j=1:size(exact,1)
    if strcmp(path,exact{j,1})
      pass=isequal(actual,exact{j,2}); return;
    end
  end
end

%% ==================== Resource, counter, and status gates ====================
% Failure publication preserves all already merged diagnostics and counters.

function [result,dispatch]=LOCAL_resource_gate(result,dispatch,timer,cumulative,c)
  if ~dispatch, return; end
  if toc(timer)>c.hard_seconds||cumulative>c.memory_mib_max
    [result,dispatch]=LOCAL_execution_stop(result,'RESOURCE_LIMIT_EXCEEDED', ...
      'The hard time or 640 MiB active-object proxy was exceeded.');
  elseif toc(timer)>c.soft_seconds
    [result,dispatch]=LOCAL_execution_stop(result,'SOFT_STAGE_START_UNAVAILABLE', ...
      'The 1500-second soft stage-start gate refused another module.');
  end
end

function [result,dispatch]=LOCAL_stop_from_module(result,module,name)
  code=module.first_unavailable.code;
  if strcmp(code,'NONE'), code=[upper(name),'_UNAVAILABLE']; end
  [result,dispatch]=LOCAL_execution_stop(result,code, ...
    module.first_unavailable.message);
end

function [result,cumulative]= ...
    LOCAL_salvage_failed_module(result,module,name,before,cumulative,c)
  snapshot=struct('module',name,'typed_payload_returned',false, ...
    'available',false,'first_unavailable',LOCAL_condition( ...
      'UNRETURNED_MODULE','The module did not return a typed payload.'), ...
    'call_counters_preserved',false,'warnings_preserved',false, ...
    'resource_record_preserved',false,'local_peak_mib',NaN);
  if ~isstruct(module)||~isscalar(module)
    record=LOCAL_unreturned_resource(before,c);
    result.resources.modules.(name)=record;
    cumulative=LOCAL_cumulative_candidate(cumulative, ...
      record.concurrent_peak_candidate_mib);
    result.audit.failed_module=snapshot; return;
  end
  required={'available','first_unavailable','warnings','call_counters', ...
    'resource_record'};
  if ~all(isfield(module,required))
    record=LOCAL_unreturned_resource(before,c);
    result.resources.modules.(name)=record;
    cumulative=LOCAL_cumulative_candidate(cumulative, ...
      record.concurrent_peak_candidate_mib);
    result.audit.failed_module=snapshot; return;
  end
  snapshot.typed_payload_returned=true;
  snapshot.available=logical(module.available);
  snapshot.first_unavailable=module.first_unavailable;
  if isstruct(module.call_counters)
    result.call_counters=LOCAL_add_counters(result.call_counters,module.call_counters);
    result.no_resolve_call_counts=result.call_counters;
    snapshot.call_counters_preserved=true;
  end
  if isstruct(module.warnings)
    result.nonblocking_warnings=[result.nonblocking_warnings,module.warnings];
    snapshot.warnings_preserved=true;
  end
  if isstruct(module.resource_record)
    snapshot.resource_record_preserved=true;
    result.resources.modules.(name)=module.resource_record;
    if isfield(module.resource_record,'local_workspace_peak_mib')
      snapshot.local_peak_mib=module.resource_record.local_workspace_peak_mib;
    end
    if isfield(module.resource_record,'concurrent_peak_candidate_mib')&& ...
        isfinite(module.resource_record.concurrent_peak_candidate_mib)
      cumulative=LOCAL_cumulative_candidate(cumulative, ...
        module.resource_record.concurrent_peak_candidate_mib);
    end
  end
  result.audit.failed_module=snapshot;
end

function value=LOCAL_cumulative_candidate(previous,candidate)
  values=[previous,candidate]; values=values(isfinite(values));
  if isempty(values), value=NaN; else, value=max(values); end
end

function pass=LOCAL_result_private_payload_absent(result)
  pass=isstruct(result.modules)&&isscalar(result.modules);
  names=fieldnames(result.modules);
  expected={'available','first_unavailable','public_metrics', ...
    'audit_summary','resource_record'};
  for j=1:numel(names)
    value=result.modules.(names{j});
    pass=pass&&isstruct(value)&&isscalar(value)&& ...
      isequal(sort(fieldnames(value)),sort(expected(:)))&& ...
      ~isfield(value,'finest_factors')&&~isfield(value,'cap_signatures');
  end
end

function value=LOCAL_unreturned_peak(module,module_merged)
  value=NaN;
  if module_merged||~isstruct(module)||~isscalar(module)|| ...
      ~isfield(module,'resource_record')||~isstruct(module.resource_record)
    return;
  end
  if isfield(module.resource_record,'local_workspace_peak_mib')
    value=module.resource_record.local_workspace_peak_mib;
  end
end

function [result,dispatch]=LOCAL_execution_stop(result,code,message)
  dispatch=false; result.execution_pass=false;
  if strcmp(result.first_execution_blocker.code,'NONE')
    result.first_execution_blocker=LOCAL_condition(code,message);
  end
  if contains(code,'RESOURCE')||contains(code,'HardTime')|| ...
      contains(code,'SOFT_STAGE')
    result.status='I3_2_RESOURCE_BUDGET_UNAVAILABLE';
    result.scientific_outcome='RESOURCE_BUDGET_UNAVAILABLE';
  else
    result.status='I3_2_EXECUTION_UNAVAILABLE';
    result.scientific_outcome='EXECUTION_UNAVAILABLE';
  end
end

function result=LOCAL_finalize_status(result,c)
  if ~result.execution_pass, return; end
  if ~isfield(result.modules,'fullp_cap')
    result.status='I3_2_EXECUTION_UNAVAILABLE';
    result.scientific_outcome='EXECUTION_UNAVAILABLE';
    return;
  end
  cap=result.modules.fullp_cap.public_metrics;
  if ~cap.numerator_available
    result.status='I3_2_EMPIRICAL_CAP_UNRESOLVED';
    result.scientific_outcome='EMPIRICAL_CAP_UNRESOLVED';
    result.cap_status='EMPIRICAL_CAP_UNRESOLVED';
  elseif ~cap.denominator_available
    result.status='I3_2_FIELD_PARTIAL_EMPIRICALLY_UNRESOLVED';
    result.scientific_outcome='FIELD_PARTIAL_EMPIRICALLY_UNRESOLVED';
    result.cap_status='EMPIRICAL_CAP_UNRESOLVED';
  elseif ~cap.estimator.interval_available
    result.status='I3_2_EMPIRICAL_NOMINAL_INTERVAL_UNAVAILABLE';
    result.scientific_outcome='EMPIRICAL_NOMINAL_INTERVAL_UNAVAILABLE';
    result.cap_status='EMPIRICALLY_SUPPORTED_EVALUATION_CAP';
  elseif cap.estimator.width>c.width_target
    result.status='I3_2_EMPIRICAL_RESOLUTION_INSUFFICIENT';
    result.scientific_outcome='EMPIRICAL_RESOLUTION_INSUFFICIENT';
    result.cap_status='EMPIRICALLY_SUPPORTED_EVALUATION_CAP';
  else
    result.status='I3_2_EMPIRICAL_NOMINAL_TRANSFORM';
    result.scientific_outcome='EMPIRICAL_NOMINAL_TRANSFORM';
    result.cap_status='EMPIRICALLY_SUPPORTED_EVALUATION_CAP';
  end
end

function out=LOCAL_add_counters(a,b)
  out=a; names=fieldnames(b);
  for j=1:numel(names)
    name=names{j};
    if isstruct(b.(name))
      if ~isfield(out,name)||~isstruct(out.(name)), out.(name)=struct(); end
      out.(name)=LOCAL_add_counters(out.(name),b.(name));
    elseif isnumeric(b.(name))&&isscalar(b.(name))
      if ~isfield(out,name), out.(name)=0; end
      out.(name)=out.(name)+b.(name);
    end
  end
end

function out=LOCAL_no_resolve_audit(calls)
  names={'candidate_solve_calls','qz_solve_calls','coordinate_solve_calls', ...
    'propagation_solve_calls','wall_density_solve_calls', ...
    'circle_density_solve_calls','schur_solve_calls','proxy_build_calls'};
  values=zeros(1,numel(names));
  for j=1:numel(names), values(j)=calls.(names{j}); end
  out=struct('names',{names},'values',values,'expected',zeros(size(values)), ...
    'pass',all(values==0),'exact_counter_count',numel(names));
end

function out=LOCAL_allowlisted_eig_audit(calls)
  small=calls.small_hermitian_gram_diagnostic_eig_calls;
  gauss=calls.gauss_golub_welsch_eig_calls; total=small+gauss;
  out=struct('small_gram',small,'expected_small_gram',274, ...
    'gauss_golub_welsch',gauss,'expected_gauss',6, ...
    'total',total,'expected_total',280, ...
    'small_gram_path','i32_fullp_cap>LOCAL_psd_root', ...
    'gauss_path','i32_lifting_quadrature>LOCAL_gauss', ...
    'pass',small==274&&gauss==6&&total==280);
end

function out=LOCAL_result_qualification(result)
  out=struct('strict_conditional_theorem',true, ...
    'empirical_caps_are_strict_upper_bounds',false, ...
    'conditional_prediction_interval', ...
      isfield(result.estimator,'interval_available')&& ...
      result.estimator.interval_available, ...
    'reliable_interval',false,'outward_residual_upper',false, ...
    'field_lower_enclosure',false,'tail_enclosure',false, ...
    'projected_gap_certified',false,'spectral_existence_certified',false);
end

function out=LOCAL_reliability_flags()
  out=struct('reliable',false,'certified',false, ...
    'outward_enclosure',false,'residual_upper_bound',false, ...
    'field_lower_enclosure',false,'infinite_tail_enclosure',false, ...
    'projected_gap_certified',false,'essential_spectrum_gap_certified',false, ...
    'eigenvalue_existence_certified',false,'independent_reference',false, ...
    'effectivity_validated',false,'I3_3_independent_method',false, ...
    'I3_4_reliable_enclosure',false);
end

function out=LOCAL_empty_coverage()
  out=struct('module_completed',struct(),'module_available',struct(), ...
    'fixed_certificate_consumed',false,'same_density_actions_computed',false, ...
    'actual_DeltaT_actions_computed',false, ...
    'finite_image_Bloch_actions_computed',false, ...
    'all_fresh_computed_modes_included',false, ...
    'empirical_numerator_cap_computed',false, ...
    'empirical_denominator_cap_computed',false, ...
    'nominal_transform_computed',false,'mathematical_trial_redefined',false, ...
    'continuous_error_enclosed',false, ...
    'uncomputed_fourier_tail_enclosed',false, ...
    'uncomputed_image_tail_enclosed',false,'independent_reference',false);
end

function out=LOCAL_first_warning(warnings)
  if isempty(warnings), out=LOCAL_condition('NONE','No nonblocking warning.');
  else
    out=LOCAL_condition(warnings(1).code, ...
      sprintf('First nonblocking scientific warning; value %.17g.', ...
      warnings(1).value));
  end
end

function out=LOCAL_condition(code,message)
  out=struct('code',char(code),'message',char(message));
end

function out=LOCAL_empty_warnings()
  out=struct('code',{},'value',{},'blocking',{});
end

function out=LOCAL_zero_counters()
  category=struct('final',0,'state',0,'artifact',0,'image',0, ...
    'three_axis',0,'interaction',0,'shell',0,'field',0);
  out=struct('candidate_solve_calls',0,'qz_solve_calls',0, ...
    'coordinate_solve_calls',0,'propagation_solve_calls',0, ...
    'wall_density_solve_calls',0,'circle_density_solve_calls',0, ...
    'schur_solve_calls',0,'proxy_build_calls',0, ...
    'harmonic_action_calls',0,'image_pair_updates',0, ...
    'kress_oracle_calls',0,'linton_oracle_calls',0, ...
    'actual_deltaT_action_calls',0,'finite_bloch_image_updates',0, ...
    'riccati_calls',0,'gauss_factor_calls',0, ...
    'full_p_contraction_calls',0,'full_p_contraction_category',category, ...
    'small_hermitian_gram_diagnostic_eig_calls',0, ...
    'gauss_golub_welsch_eig_calls',0, ...
    'n_op_signature_parity',0,'n_op_combined_gram_parity',0);
end

function value=LOCAL_entry_retained_mib()
  info=evalin('caller','whos'); inventory=LOCAL_registered_inventory(info);
  if isempty(inventory), value=0; else, value=sum([inventory.mib]); end
end

function out=LOCAL_entry_owner_inventory()
  info=evalin('caller','whos'); out=LOCAL_registered_inventory(info);
end

function out=LOCAL_registered_inventory(info)
  owners={'result','staged','lift_private','wall_private','circle_private', ...
    'module','c','output'};
  out=struct('name',{},'class',{},'size',{},'bytes',{},'mib',{});
  for j=1:numel(info)
    if ~ismember(info(j).name,owners), continue; end
    out(end+1)=struct('name',info(j).name,'class',info(j).class, ... %#ok<AGROW>
      'size',info(j).size,'bytes',info(j).bytes, ...
      'mib',info(j).bytes/2^20);
  end
end
