function result = check_e_cap(attempt,input_path)
%CHECK_E_CAP Evaluate the frozen I3.2 same-trial empirical cap.
% Purpose:
%   Consume one explicit staged fbie-a1 certificate, re-evaluate only its
%   fixed-density boundary actions, and form an empirical evaluation cap.
% Input:
%   attempt    - The sole Revision E tag, 'ecap-a2'.
%   input_path - Explicit staged certificate MAT file.
% Output:
%   result     - Append-only diagnostics, empirical caps, nominal transform,
%                and a complete reliability-false claim ledger.
% Main algorithm:
%   Validate immutable certificate coordinates, evaluate the same trial on
%   preregistered nested levels, assemble canonical full-P factors, and apply
%   the frozen empirical remainder rules without any solve.
% Based on:
%   research/projects/eig-apost/implementation/i3/design-3-2b.md.
% Main changes:
%   Replaces every solve by staged immutable arrays and a direct harmonic-
%   image evaluator for the already-defined continuous QP kernel.
% Numerical goal:
%   Produce an ordinary same-trial evaluation cap, never a rigorous bound.

  if nargin~=2 || ~strcmp(char(attempt),'ecap-a2') || ...
      ~(ischar(input_path)||isstring(input_path))
    error('i32e:Arguments', ...
      'The frozen call is check_e_cap(''ecap-a2'',explicit_input).');
  end
  if exist('OCTAVE_VERSION','builtin')~=0
    error('i32e:MATLABRequired','This experiment requires MATLAB.');
  end
  input_path=char(input_path);
  here=fileparts(mfilename('fullpath'));
  output=fullfile(here,'output',char(attempt));
  if exist(output,'file')||exist(output,'dir')
    error('i32e:OutputExists','Output already exists: %s.',output);
  end
  staged_original=LOCAL_load_input(input_path);
  c=LOCAL_config();
  timer=tic; result=LOCAL_empty_result(char(attempt),c,staged_original);
  original_staged_mib=LOCAL_mib({staged_original});
  peak_mib=original_staged_mib;
  converted_staged_mib=NaN; conversion_ledger_mib=NaN;
  normalization_peak_mib=NaN;
  evaluation_helper_peak_mib=0; cap_helper_peak_mib=0;
  retained_before_evaluation_mib=NaN; retained_after_evaluation_mib=NaN;
  retained_before_cap_mib=NaN; retained_after_cap_mib=NaN;
  try
    % --- stage 1: storage normalization, identity, and resource preflight ---
    [staged,storage_conversion]=LOCAL_normalize_integer_storage(staged_original);
    converted_staged_mib=LOCAL_mib({staged});
    conversion_ledger_mib=LOCAL_mib({storage_conversion});
    normalization_peak_mib=original_staged_mib+converted_staged_mib+ ...
      conversion_ledger_mib;
    peak_mib=max(peak_mib,normalization_peak_mib);
    clear staged_original;
    result.input_storage_conversion=storage_conversion;
    LOCAL_input_gate(staged,c);
    identity=LOCAL_identity(staged,c); result.identity=identity;
    result.certificate_summary=identity;
    result.call_counters=LOCAL_zero_counters();
    preflight=LOCAL_preflight(c,staged,storage_conversion, ...
      original_staged_mib,normalization_peak_mib);
    result.resource_preflight=preflight;
    result.resources.preflight=preflight;
    if isfield(identity,'branch_and_Wood')&& ...
        isfield(identity.branch_and_Wood,'pass')&& ...
        ~identity.branch_and_Wood.pass
      error('i32e:BranchUnavailable', ...
        'The frozen branch/Wood identity is unavailable.');
    end
    if ~identity.pass
      error('i32e:CertificateIdentity','The staged certificate identity failed.');
    end
    if ~preflight.pass
      error('i32e:ResourcePreflight','The frozen resource preflight refused execution.');
    end
    LOCAL_resource_gate(timer,peak_mib,c);

    % --- stage 2: fixed-density harmonic-image and cross actions ---
    evaluation=i32_same_eval(c,staged.certificate,staged.raw_maps,timer);
    result.evaluation=evaluation.public;
    result.audit.evaluation=evaluation.audit;
    result.call_counters=LOCAL_add_counters(result.call_counters, ...
      evaluation.call_counters);
    result.nonblocking_warnings=[result.nonblocking_warnings, ...
      evaluation.warnings];
    retained_before_evaluation_mib=LOCAL_mib({staged})+conversion_ledger_mib;
    retained_after_evaluation_mib=LOCAL_mib({staged,evaluation})+ ...
      conversion_ledger_mib;
    evaluation_helper_peak_mib=evaluation.record.peak_local_workspace_mib;
    evaluation_transient_mib=max( ...
      c.worst_transient_mib,evaluation_helper_peak_mib);
    peak_mib=max([peak_mib,retained_after_evaluation_mib, ...
      retained_before_evaluation_mib+evaluation_transient_mib]);
    LOCAL_resource_gate(timer,peak_mib,c);

    % --- stage 3: canonical factors, empirical caps, and nominal transform ---
    if evaluation.core_available
      LOCAL_soft_gate(timer,c,'cap and full-P contractions');
      cap=i32_cap_tail(c,staged,evaluation,timer);
    else
      cap=LOCAL_unstarted_cap();
    end
    result.components=cap.components;
    result.caps=cap.caps;
    result.estimator=cap.estimator;
    result.tails=cap.tails;
    result.axis_metrics=cap.axis_metrics;
    result.unresolved_axes=cap.unresolved_axes;
    result.arithmetic=cap.arithmetic;
    result.audit.cap=cap.audit;
    result.call_counters=LOCAL_add_counters(result.call_counters, ...
      cap.call_counters);
    result.nonblocking_warnings=[result.nonblocking_warnings,cap.warnings];
    retained_before_cap_mib=LOCAL_mib({staged,evaluation})+conversion_ledger_mib;
    retained_after_cap_mib=LOCAL_mib({staged,evaluation,cap})+ ...
      conversion_ledger_mib;
    cap_helper_peak_mib=cap.peak_local_workspace_mib;
    cap_transient_mib=max(c.worst_transient_mib,cap_helper_peak_mib);
    peak_mib=max([peak_mib,retained_after_cap_mib, ...
      retained_before_cap_mib+cap_transient_mib]);
    LOCAL_resource_gate(timer,peak_mib,c);

    result.coverage.fixed_certificate_consumed=true;
    result.coverage.same_density_actions_computed=evaluation.core_available;
    result.coverage.actual_DeltaT_actions_computed= ...
      isfield(evaluation.circle,'actual_T_action')&& ...
      evaluation.circle.actual_T_action.available;
    result.coverage.finite_image_Bloch_actions_computed= ...
      isfield(evaluation.circle,'finite_image_bloch')&& ...
      evaluation.circle.finite_image_bloch.available;
    result.coverage.all_fresh_computed_modes_included=cap.all_modes_included;
    result.coverage.empirical_numerator_cap_computed=cap.numerator_available;
    result.coverage.empirical_denominator_cap_computed=cap.denominator_available;
    result.coverage.nominal_transform_computed=cap.estimator.interval_available;
    result.coverage.mathematical_trial_redefined=false;
    result.coverage.continuous_error_enclosed=false;
    result.coverage.uncomputed_fourier_tail_enclosed=false;
    result.coverage.uncomputed_image_tail_enclosed=false;
    result.coverage.independent_reference=false;

    if ~LOCAL_all_zero(result.call_counters)
      result.status='I3_2_CERTIFICATE_IDENTITY_MISMATCH';
      result.scientific_outcome='CERTIFICATE_IDENTITY_MISMATCH';
      result.first_empirical_unavailable=LOCAL_condition( ...
        'CERTIFICATE_IDENTITY_MISMATCH', ...
        'At least one forbidden solve/build counter is nonzero.');
    elseif ~evaluation.core_available&&any(strcmp(evaluation.first_unavailable_code, ...
        {'i32e:BranchUnavailable','i32e:ExactWood'}))
      result.status='I3_2_BRANCH_OR_WOOD_UNAVAILABLE';
      result.scientific_outcome='BRANCH_OR_WOOD_UNAVAILABLE';
      result.first_empirical_unavailable=LOCAL_condition( ...
        evaluation.first_unavailable_code,evaluation.first_unavailable_message);
    elseif ~evaluation.core_available
      result.status='I3_2_EVALUATION_UNAVAILABLE';
      result.scientific_outcome='SAME_TRIAL_EVALUATION_UNAVAILABLE';
      result.first_empirical_unavailable=LOCAL_condition( ...
        evaluation.first_unavailable_code,evaluation.first_unavailable_message);
    elseif ~cap.numerator_available
      result.status='I3_2_EMPIRICAL_CAP_UNRESOLVED';
      result.scientific_outcome='EMPIRICAL_CAP_UNRESOLVED';
      result.first_empirical_unavailable=cap.first_unavailable;
    elseif ~cap.denominator_available
      result.status='I3_2_FIELD_PARTIAL_EMPIRICALLY_UNRESOLVED';
      result.scientific_outcome='FIELD_PARTIAL_EMPIRICALLY_UNRESOLVED';
      result.first_empirical_unavailable=cap.first_unavailable;
    elseif cap.estimator.q_emp>=1
      result.status='I3_2_EMPIRICAL_NOMINAL_INTERVAL_UNAVAILABLE';
      result.scientific_outcome='EMPIRICAL_NOMINAL_INTERVAL_UNAVAILABLE';
      result.first_empirical_unavailable=LOCAL_condition('NONE', ...
        'The empirical evaluation cap is available.');
    elseif cap.estimator.width>c.width_target
      result.status='I3_2_EMPIRICAL_RESOLUTION_INSUFFICIENT';
      result.scientific_outcome='EMPIRICAL_RESOLUTION_INSUFFICIENT';
      result.first_empirical_unavailable=LOCAL_condition('NONE', ...
        'The empirical evaluation cap is available.');
    else
      result.status='I3_2_EMPIRICAL_NOMINAL_TRANSFORM';
      result.scientific_outcome='EMPIRICAL_NOMINAL_TRANSFORM';
      result.first_empirical_unavailable=LOCAL_condition('NONE', ...
        'The empirical evaluation cap is available.');
    end
    if cap.numerator_available&&cap.denominator_available
      result.cap_status='EMPIRICALLY_SUPPORTED_EVALUATION_CAP';
    else
      result.cap_status='EMPIRICAL_CAP_UNRESOLVED';
    end
    result.first_nonblocking_warning=LOCAL_first_warning( ...
      result.nonblocking_warnings);
    result.no_resolve_call_counts=result.call_counters;
    result.execution_pass=true;
  catch ME
    result=LOCAL_execution_fail(result,ME);
  end

  result.elapsed_seconds=toc(timer);
  result.peak_active_mib=peak_mib;
  result.soft_time_exceeded=result.elapsed_seconds>c.soft_seconds;
  if result.elapsed_seconds>c.hard_seconds||peak_mib>c.memory_mib_max
    result.execution_pass=false;
    result.status='I3_2_RESOURCE_BUDGET_UNAVAILABLE';
    result.scientific_outcome='RESOURCE_BUDGET_UNAVAILABLE';
    result.first_execution_blocker=LOCAL_condition( ...
      'RESOURCE_LIMIT_EXCEEDED', ...
      'The hard time or active-object memory budget was exceeded.');
  end
  result.reliability=LOCAL_reliability_flags();
  result.qualification=LOCAL_qualification(result);
  result.resources.actual=struct('elapsed_seconds',result.elapsed_seconds, ...
    'peak_active_mib',peak_mib,'soft_time_exceeded', ...
    result.elapsed_seconds>c.soft_seconds,'hard_limits_respected', ...
    result.elapsed_seconds<=c.hard_seconds&&peak_mib<=c.memory_mib_max, ...
    'peak_accounting', ...
      ['max(retained-after-stage, retained-before-stage + ', ...
      'max(frozen transient, measured helper-local peak))'], ...
    'frozen_transient_mib',c.worst_transient_mib, ...
    'original_integer_storage_staged_mib',original_staged_mib, ...
    'double_expanded_staged_mib',converted_staged_mib, ...
    'conversion_ledger_mib',conversion_ledger_mib, ...
    'normalization_peak_mib',normalization_peak_mib, ...
    'evaluation_helper_peak_mib',evaluation_helper_peak_mib, ...
    'cap_helper_peak_mib',cap_helper_peak_mib, ...
    'retained_before_evaluation_mib',retained_before_evaluation_mib, ...
    'retained_after_evaluation_mib',retained_after_evaluation_mib, ...
    'retained_before_cap_mib',retained_before_cap_mib, ...
    'retained_after_cap_mib',retained_after_cap_mib, ...
    'helper_peak_combined_by_max_not_sum_with_frozen_transient',true, ...
    'helper_local_peak_added_to_returned_object',false);
  if exist(output,'file')||exist(output,'dir')
    error('i32e:OutputExists','Output appeared during the run: %s.',output);
  end
  mkdir(output);
  save(fullfile(output,'result.mat'),'result','-v7.3');
  LOCAL_report(fullfile(output,'report.md'),result);
end

function out=LOCAL_unstarted_cap()
  out=struct('components',struct(),'caps',struct(), ...
    'estimator',struct('interval_available',false),'tails',struct(), ...
    'axis_metrics',struct(),'unresolved_axes',{{'EVALUATION_UNAVAILABLE'}}, ...
    'arithmetic',struct(),'audit',struct(),'call_counters',LOCAL_zero_counters(), ...
    'warnings',struct('code',{},'value',{},'blocking',{}), ...
    'peak_local_workspace_mib',0,'all_modes_included',false, ...
    'numerator_available',false,'denominator_available',false, ...
    'first_unavailable',LOCAL_condition('SAME_TRIAL_EVALUATION_UNAVAILABLE', ...
      'Cap construction was not started because evaluation is unavailable.'));
end

%% ==================== Frozen runtime contract ====================
% These helpers validate the explicit input without reading repository state.

function staged=LOCAL_load_input(path)
  if ~isfile(path)
    error('i32e:InputMissing','The explicit staged input is unavailable.');
  end
  loaded=load(path,'staged');
  if ~isfield(loaded,'staged')||~isstruct(loaded.staged)
    error('i32e:InputSchema','The input does not contain staged.');
  end
  staged=loaded.staged;
end

function [staged,ledger]=LOCAL_normalize_integer_storage(staged)
  specs=LOCAL_integer_storage_contract();
  template=struct('path','','original_class','','original_size',[], ...
    'semantic_range',[],'original_scalar_value',NaN,'original_min',NaN, ...
    'original_max',NaN,'maximum_absolute_value',NaN, ...
    'within_flintmax',false,'exact_roundtrip',false, ...
    'converted_class','','downstream_arithmetic','','pass',false);
  ledger=repmat(template,numel(specs),1);
  for j=1:numel(specs)
    spec=specs(j); value=LOCAL_nested_value(staged,spec.path);
    if ~isinteger(value)||~strcmp(class(value),spec.original_class)|| ...
        ~isequal(size(value),spec.expected_size)
      error('i32e:InputStorageClass', ...
        'Integer storage class/size mismatch at %s.',spec.path);
    end
    converted=double(value); maximum=max(abs(converted),[],'all');
    within_flintmax=maximum<=flintmax;
    roundtrip=within_flintmax&& ...
      isequal(feval(spec.original_class,converted),value);
    range_pass=all(converted>=spec.minimum&converted<=spec.maximum,'all');
    if ~roundtrip||~range_pass
      error('i32e:InputStorageValue', ...
        'Integer storage value/range mismatch at %s.',spec.path);
    end
    scalar_value=NaN;
    if isscalar(converted), scalar_value=converted; end
    ledger(j)=struct('path',spec.path, ...
      'original_class',spec.original_class,'original_size',size(value), ...
      'semantic_range',[spec.minimum,spec.maximum], ...
      'original_scalar_value',scalar_value, ...
      'original_min',min(converted,[],'all'), ...
      'original_max',max(converted,[],'all'), ...
      'maximum_absolute_value',maximum, ...
      'within_flintmax',within_flintmax,'exact_roundtrip',roundtrip, ...
      'converted_class','double', ...
      'downstream_arithmetic',spec.downstream_arithmetic,'pass',true);
    staged=LOCAL_nested_assign(staged,spec.path,converted);
  end
end

function specs=LOCAL_integer_storage_contract()
  rows={ ...
    'input_contract.eta_source_nodes','int64',[1,1],256,256, ...
      'input node-count equality'; ...
    'input_contract.wall_source_orders','int64',[1,1],512,512, ...
      'input order-count equality'; ...
    'certificate.d','int64',[1,1],1,1,'scalar and Fourier-grid identity'; ...
    'certificate.rho_disk','int64',[1,1],17,17,'material scalar identity'; ...
    'certificate.L','int64',[1,1],1,1,'phase and center-trace identity'; ...
    'certificate.M','int64',[1,1],48,48,'retained-order identity'; ...
    'certificate.K','int64',[1,1],97,97,'state-dimension arithmetic'; ...
    'certificate.wall_input_unit_512','uint8',[1024,194],0,1, ...
      'fresh shared-wall action arithmetic'; ...
    'certificate.wall_orders_512','int16',[512,1],-256,255, ...
      'wall-order common-map comparison'; ...
    'raw_maps.circle_orders_512','int64',[512,1],-256,255, ...
      'circle-order common-map comparison'; ...
    'raw_maps.wall_input_unit_512','uint8',[1024,194],0,1, ...
      'artifact wall-defect arithmetic'; ...
    'certificate.branch_port.classification','int8',[97,1],-1,1, ...
      'branch-class equality'; ...
    'certificate.branch_port.outgoing_sign_pass','uint8',[97,1],0,1, ...
      'branch sign Boolean reduction'; ...
    'certificate.branch_port.axis_pass','uint8',[97,1],0,1, ...
      'branch axis Boolean reduction'; ...
    'certificate.branch_port.available','int64',[1,1],0,1, ...
      'branch availability Boolean'; ...
    'certificate.branch_port.pass','int64',[1,1],0,1, ...
      'branch qualification Boolean'; ...
    'certificate.center_wall_jumps.field_lower_uses_shared_trace', ...
      'int64',[1,1],0,1,'center field-lower audit Boolean'; ...
    'ordinary_anchor.center_wall_jumps.field_lower_uses_shared_trace', ...
      'int64',[1,1],0,1,'anchor field-lower audit Boolean'; ...
    'ordinary_anchor.tail_minus.selected_N','int64',[1,1],1,32, ...
      'minus full-P association'; ...
    'ordinary_anchor.tail_plus.selected_N','int64',[1,1],1,32, ...
      'plus full-P association'; ...
    'ordinary_anchor.first_level_indices.minus_physical_start', ...
      'uint8',[5,1],0,1,'minus first-level index identity'; ...
    'ordinary_anchor.first_level_indices.plus_physical_start', ...
      'uint8',[5,1],0,1,'plus first-level index identity'; ...
    'ordinary_anchor.first_level_indices.minus_selected_N', ...
      'int64',[1,1],1,32,'minus selected-level equality'; ...
    'ordinary_anchor.first_level_indices.plus_selected_N', ...
      'int64',[1,1],1,32,'plus selected-level equality'; ...
    'historical_diagnostics.circle_action_metric.zero_component', ...
      'int64',[1,1],0,1,'historical metric Boolean'; ...
    'historical_diagnostics.circle_angular_tail_metric.zero_component', ...
      'int64',[1,1],0,1,'historical metric Boolean'; ...
    'historical_diagnostics.outside_M_metric.zero_component', ...
      'int64',[1,1],0,1,'historical metric Boolean'; ...
    'historical_diagnostics.outside_M_metric.computed_modes_all_in_residual', ...
      'int64',[1,1],0,1,'historical inclusion Boolean'};
  template=struct('path','','original_class','','expected_size',[], ...
    'minimum',NaN,'maximum',NaN,'downstream_arithmetic','');
  specs=repmat(template,size(rows,1),1);
  for j=1:size(rows,1)
    specs(j)=struct('path',rows{j,1},'original_class',rows{j,2}, ...
      'expected_size',rows{j,3},'minimum',rows{j,4}, ...
      'maximum',rows{j,5},'downstream_arithmetic',rows{j,6});
  end
end

function value=LOCAL_nested_value(staged,path)
  chain=LOCAL_nested_chain(path);
  try
    value=subsref(staged,chain);
  catch ME
    error('i32e:InputStoragePath', ...
      'Required integer storage path is unavailable: %s (%s).',path,ME.message);
  end
end

function staged=LOCAL_nested_assign(staged,path,value)
  chain=LOCAL_nested_chain(path);
  staged=subsasgn(staged,chain,value);
end

function chain=LOCAL_nested_chain(path)
  parts=strsplit(path,'.');
  chain=repmat(struct('type','.','subs',''),1,numel(parts));
  for j=1:numel(parts), chain(j).subs=parts{j}; end
end

function c=LOCAL_config()
  prior_events=repmat(struct('order',0,'stage','','code','','message','', ...
    'location','','shell_status',NaN,'result_present',true, ...
    'report_present',false,'result_size_bytes',115936, ...
    'result_sha256', ...
      '8dc98c1d830d92e2d5885a1e38dda6205cf5673ad7919034c951685a2f88490f', ...
    'saved_elapsed_seconds',0.038080041666666668, ...
    'saved_peak_active_mib',44.56219482421875),2,1);
  prior_events(1).order=1;
  prior_events(1).stage='saved scientific pipeline result';
  prior_events(1).code='MATLAB:mixedClasses';
  prior_events(1).message= ...
    'Integers can only be combined with integers of the same class, or scalar doubles.';
  prior_events(1).location='LOCAL_identity at frozen a1 check_e_cap.m:378';
  prior_events(2).order=2;
  prior_events(2).stage='report publication after saved result';
  prior_events(2).code='FOPEN_INVALID_PERMISSION';
  prior_events(2).message='Invalid permission.';
  prior_events(2).location='LOCAL_report at frozen a1 check_e_cap.m:872';
  prior_events(2).shell_status=1;
  prior=struct('attempt','ecap-a1', ...
    'status','I3_2_EXECUTION_UNAVAILABLE', ...
    'scientific_outcome','UNAVAILABLE', ...
    'first_execution_blocker','MATLAB:mixedClasses', ...
    'first_empirical_unavailable','NOT_REACHED', ...
    'saved_result_present',true,'saved_report_present',false, ...
    'shell_status',1,'retry_count',0,'ordered_events',prior_events, ...
    'message',[ ...
      'Saved result stopped at integer/double identity arithmetic; ', ...
      'the later unsupported fopen permission caused shell exit 1.']);
  c=struct('schema','TEP_I3_2_SAME_TRIAL_EVALUATION_CAP_REV_E', ...
    'input_schema','TEP_I3_2_STAGED_FBIE_A1_CERTIFICATE_V1', ...
    'attempt','ecap-a2','source_attempt','fbie-a1', ...
    'khat',1.832770289108157,'beta',0.5,'d',1.0,'R',0.2, ...
    'rho_disk',17,'X_L',-0.5,'X_R',0.5,'L',1.0, ...
    'M',48,'K',97,'delta_c',0.04,'delta_w',0.04, ...
    'anchor_components',[1.8732026085453917e-10, ...
      2.9776880587814564e-15,4.246327820844503e-11], ...
    'anchor_M',2.29786516751043e-10, ...
    'anchor_N',4.959111810675795, ...
    'circle_levels',[512,1024,2048], ...
    'image_levels',[32,48,64,96,128,192,256], ...
    'wall_levels',[1024,2048,4096], ...
    'riccati_levels',[512,1024,2048], ...
    'gauss_levels',[32,64,128],'full_p_levels',[8,16,32], ...
    'image_ratio_max',0.80,'spectral_ratio_max',0.50, ...
    'image_remainder_factor',5,'spectral_remainder_factor',2, ...
    'action_ratio_max',0.50,'kernel_oracle_tol',1e-8, ...
    'identity_tol',1e-10, ...
    'tail_share_warning',1e-6,'width_target',1e-6, ...
    'pair_batch',4096,'mode_batch',16, ...
    'expected_seconds',1320,'preflight_seconds_max',1500, ...
    'expected_peak_mib',420,'worst_transient_mib',360, ...
    'preflight_mib_max',520, ...
    'soft_seconds',1500,'hard_seconds',1800,'memory_mib_max',640, ...
    'retry_count',0,'prior_failed_attempt_count',1, ...
    'prior_attempts',prior);
  c.command="matlab -batch ""addpath(fullfile(pwd,'test','i3','e-cap')); "+ ...
    "check_e_cap('ecap-a2',fullfile(pwd,'test','i3','e-cap','input',"+ ...
    "'fbie-a1-certificate.mat'));""";
end

function LOCAL_input_gate(s,c)
  required={'input_contract','certificate','ordinary_anchor','raw_maps', ...
    'historical_diagnostics'};
  for j=1:numel(required)
    if ~isfield(s,required{j})||~isstruct(s.(required{j}))
      error('i32e:InputSchema','Missing staged struct %s.',required{j});
    end
  end
  contract_fields={'schema','source_attempt','staging_only', ...
    'formal_runtime_must_not_read_historical_output', ...
    'no_resolve_required','M_role', ...
    'eta_source_nodes','wall_source_orders','density_coordinate', ...
    'circle_basis','wall_basis','circle_ordering','wall_output_ordering', ...
    'branch_classification_encoding', ...
    'circle_value_only_lift','wall_value_only_lift','lift_shape', ...
    'exact_lift_amplitude_rule'};
  certificate_fields={'source_attempt','khat','mu_h','gamma','beta','d','R', ...
    'rho_disk','X_L','X_R','L','M','K','delta_c','delta_w', ...
    'q_center','Pplus','Pminus','cplus','cminus','Dplus','Dminus', ...
    'Gplus','Gminus','branch_port','eta_unit_256','xi_left_unit_512', ...
    'xi_right_unit_512','wall_input_unit_512','wall_orders_512', ...
    'center_actual_left_trace','center_actual_right_trace', ...
    'center_shared_left_trace','center_shared_right_trace', ...
    'center_left_value_mismatch','center_right_value_mismatch', ...
    'center_wall_jumps','density_coordinate','global_normal_label', ...
    'lift_contract'};
  raw_fields={'delta_plus','delta_minus','circle_jump_plus', ...
    'circle_jump_minus','QLplus','QRplus','QLminus','QRminus','Jplus', ...
    'Jminus','wall_flux_left_unit_512','wall_flux_right_unit_512', ...
    'circle_delta_D_unit_wall_512','circle_j_Gamma_unit_wall_512', ...
    'circle_orders_512','circle_theta_512','wall_common_y_1024', ...
    'wall_common_value_1024','wall_common_flux_1024', ...
    'wall_input_unit_512','circle_value_residual_unit_512', ...
    'circle_normal_residual_unit_512'};
  anchor_fields={'B_wall','B_circle','B_volume','M_tilde','N_tilde', ...
    'lead_wall_factor_plus','lead_wall_factor_minus', ...
    'lead_circle_factor_plus','lead_circle_factor_minus', ...
    'lead_volume_factor_plus','lead_volume_factor_minus', ...
    'lead_field_factor_plus','lead_field_factor_minus', ...
    'center_plus_wall_lift_factor','center_minus_wall_lift_factor', ...
    'center_left_value_lift_source','center_right_value_lift_source', ...
    'center_wall_jumps','tail_minus','tail_plus','first_level_indices'};
  if ~all(isfield(s.input_contract,contract_fields))|| ...
      ~all(isfield(s.certificate,certificate_fields))|| ...
      ~all(isfield(s.raw_maps,raw_fields))|| ...
      ~all(isfield(s.ordinary_anchor,anchor_fields))|| ...
      ~isstruct(s.certificate.lift_contract)|| ...
      ~all(isfield(s.ordinary_anchor.tail_minus,{'selected_N'}))|| ...
      ~all(isfield(s.ordinary_anchor.tail_plus,{'selected_N'}))|| ...
      ~all(isfield(s.ordinary_anchor.first_level_indices, ...
        {'minus_physical_start','plus_physical_start', ...
        'minus_selected_N','plus_selected_N'}))
    error('i32e:InputSchema','A required semantic input field is missing.');
  end
  if ~strcmp(char(s.input_contract.schema),c.input_schema)|| ...
      ~strcmp(char(s.input_contract.source_attempt),c.source_attempt)
    error('i32e:InputIdentity','The staged schema/source identity is wrong.');
  end
  if ~logical(s.input_contract.staging_only)|| ...
      ~logical(s.input_contract.formal_runtime_must_not_read_historical_output)|| ...
      ~logical(s.input_contract.no_resolve_required)|| ...
      round(s.certificate.M)~=48||round(s.certificate.K)~=97
    error('i32e:InputIdentity','The frozen no-resolve/M/K contract is wrong.');
  end
  arrays={s.certificate.q_center,s.certificate.Pplus, ...
    s.certificate.Pminus,s.certificate.cplus,s.certificate.cminus, ...
    s.certificate.Dplus,s.certificate.Dminus,s.certificate.Gplus, ...
    s.certificate.Gminus,s.certificate.eta_unit_256, ...
    s.certificate.xi_left_unit_512,s.certificate.xi_right_unit_512, ...
    s.raw_maps.delta_plus,s.raw_maps.delta_minus, ...
    s.raw_maps.circle_jump_plus,s.raw_maps.circle_jump_minus, ...
    s.raw_maps.QLplus,s.raw_maps.QRplus,s.raw_maps.QLminus, ...
    s.raw_maps.QRminus,s.raw_maps.Jplus,s.raw_maps.Jminus, ...
    s.raw_maps.wall_flux_left_unit_512, ...
    s.raw_maps.wall_flux_right_unit_512, ...
    s.raw_maps.circle_delta_D_unit_wall_512, ...
    s.raw_maps.circle_j_Gamma_unit_wall_512, ...
    s.raw_maps.wall_input_unit_512,s.raw_maps.wall_common_y_1024, ...
    s.raw_maps.wall_common_value_1024,s.raw_maps.wall_common_flux_1024, ...
    s.raw_maps.circle_value_residual_unit_512, ...
    s.raw_maps.circle_normal_residual_unit_512};
  for j=1:numel(arrays)
    if isempty(arrays{j})||~isnumeric(arrays{j})||any(~isfinite(arrays{j}),'all')
      error('i32e:InputValues','A required certificate array is unavailable.');
    end
  end
  a=s.ordinary_anchor;
  values=[a.B_wall,a.B_circle,a.B_volume,a.M_tilde,a.N_tilde];
  if any(~isfinite(values))||any(values<=0)|| ...
      abs(a.M_tilde-sum(values(1:3)))>100*eps*sum(values(1:3))
    error('i32e:InputAnchors','The ordinary component anchors are inconsistent.');
  end
end

function out=LOCAL_identity(s,c)
  z=s.certificate; q=z.q_center; K=round(z.K);
  finite=all(isfinite([z.khat,z.mu_h,z.gamma,z.beta,z.d,z.R, ...
    z.rho_disk,z.delta_c,z.delta_w]));
  scalars=[z.khat,z.beta,z.d,z.R,z.rho_disk,z.X_L,z.X_R,z.L, ...
    z.M,z.K,z.delta_c,z.delta_w];
  references=[c.khat,c.beta,c.d,c.R,c.rho_disk,c.X_L,c.X_R,c.L, ...
    c.M,c.K,c.delta_c,c.delta_w];
  scalar_relative_defect=max(abs(scalars-references)./ ...
    max(realmin,abs(references)));
  dims=isequal(size(z.Pplus),[K,K])&&isequal(size(z.Pminus),[K,K])&& ...
    isequal(size(z.Dplus),[K,K])&&isequal(size(z.Dminus),[K,K])&& ...
    isequal(size(z.Gplus),[2*K,K])&&isequal(size(z.Gminus),[2*K,K])&& ...
    numel(z.cplus)==K&&numel(z.cminus)==K&&numel(q)==2*K&& ...
    isequal(size(z.eta_unit_256),[512,2*K])&& ...
    isequal(size(z.xi_left_unit_512),[512,2*K])&& ...
    isequal(size(z.xi_right_unit_512),[512,2*K]);
  scalar=max([realmin,abs(z.mu_h),abs(z.khat^2)]);
  mu_defect=abs(z.mu_h-z.khat^2)/scalar;
  gamma_defect=abs(z.gamma-z.mu_h)/max([realmin,abs(z.gamma),abs(z.mu_h)]);
  q_norm_defect=abs(norm(q)-1);
  Gplus_reference=[z.Dplus;z.Dplus*z.Pplus];
  Gminus_reference=[z.Dminus*z.Pminus;z.Dminus];
  Gplus_defect=LOCAL_relative_difference(z.Gplus,Gplus_reference);
  Gminus_defect=LOCAL_relative_difference(z.Gminus,Gminus_reference);
  [branch_pass,branch_record,E]=LOCAL_branch_identity(z,c);
  [center_pass,center_record]=LOCAL_center_identity(z,q,E,c);
  [raw_pass,raw_record]=LOCAL_raw_map_identity(s.raw_maps,z,c);
  [anchor_pass,anchor_record]=LOCAL_anchor_identity(s.ordinary_anchor,c);
  labels=strcmp(char(z.density_coordinate),'[tau;zeta], zeta=-sigma')&& ...
    contains(lower(char(z.global_normal_label)),'global +r')&& ...
    contains(lower(char(z.global_normal_label)),'cell outward')&& ...
    strcmp(char(s.input_contract.M_role),'97 retained QZ wall-input modes only')&& ...
    strcmp(char(s.input_contract.density_coordinate),'[tau;zeta], zeta=-sigma')&& ...
    round(s.input_contract.eta_source_nodes)==256&& ...
    round(s.input_contract.wall_source_orders)==512&& ...
    strcmp(char(s.input_contract.circle_basis), ...
      'exp(i*l*theta)/sqrt(2*pi*R) in L2(ds)')&& ...
    strcmp(char(s.input_contract.wall_basis), ...
      'd^(-1/2)*exp(i*(beta+2*pi*m/d)*y)')&& ...
    strcmp(char(s.input_contract.circle_ordering), ...
      '-N/2:N/2-1 with negative Nyquist retained')&& ...
    strcmp(char(s.input_contract.wall_output_ordering), ...
      '-N/2:N/2-1 with negative Nyquist retained')&& ...
    strcmp(char(s.input_contract.branch_classification_encoding), ...
      'int8: +1 propagating, -1 evanescent, 0 Wood')&& ...
    logical(s.input_contract.circle_value_only_lift)&& ...
    logical(s.input_contract.wall_value_only_lift)&& ...
    strcmp(char(s.input_contract.lift_shape),'chi(t)=1-3*t^2+2*t^3')&& ...
    strcmp(char(s.input_contract.exact_lift_amplitude_rule), ...
      'shared value minus exact continuous raw trace')&& ...
    logical(z.lift_contract.circle_value_only)&& ...
    logical(z.lift_contract.wall_value_only)&& ...
    strcmp(char(z.lift_contract.shape),'chi(t)=1-3*t^2+2*t^3')&& ...
    strcmp(char(z.lift_contract.exact_amplitude_rule), ...
      'shared value minus exact continuous raw trace');
  levels=isequal(c.circle_levels,[512,1024,2048])&& ...
    isequal(c.wall_levels,[1024,2048,4096]);
  pass=finite&&dims&&labels&&levels&&branch_pass&&center_pass&&raw_pass&& ...
    anchor_pass&& ...
    scalar_relative_defect<=c.identity_tol&&q_norm_defect<=c.identity_tol&& ...
    mu_defect<=c.identity_tol&&gamma_defect<=c.identity_tol&& ...
    Gplus_defect<=c.identity_tol&&Gminus_defect<=c.identity_tol;
  out=struct('pass',pass,'finite',finite,'dimensions',dims,'labels',labels, ...
    'frozen_scalar_relative_defect',scalar_relative_defect, ...
    'q_norm_defect',q_norm_defect,'Gplus_relative_defect',Gplus_defect, ...
    'Gminus_relative_defect',Gminus_defect, ...
    'mu_relative_defect',mu_defect,'gamma_relative_defect',gamma_defect, ...
    'branch_and_Wood',branch_record,'center_traces',center_record, ...
    'raw_map_schema',raw_record,'ordinary_anchor',anchor_record, ...
    'M_role','QZ wall-state input K=97 only', ...
    'circle_density_nodes',256,'wall_density_orders',512, ...
    'certificate_trial_redefined',false);
end

function [pass,out]=LOCAL_anchor_identity(a,c)
  values=[a.B_wall,a.B_circle,a.B_volume,a.M_tilde,a.N_tilde];
  reference=[c.anchor_components,c.anchor_M,c.anchor_N];
  scalar_defect=max(abs(values-reference)./max(realmin,abs(reference)));
  factor_names={'lead_wall_factor_plus','lead_wall_factor_minus', ...
    'lead_circle_factor_plus','lead_circle_factor_minus', ...
    'lead_volume_factor_plus','lead_volume_factor_minus', ...
    'lead_field_factor_plus','lead_field_factor_minus'};
  factor_dims=true; factor_finite=true;
  for j=1:numel(factor_names)
    value=a.(factor_names{j});
    factor_dims=factor_dims&&size(value,2)==c.K&&~isempty(value);
    factor_finite=factor_finite&&all(isfinite(value),'all');
  end
  selected=[a.tail_minus.selected_N,a.tail_plus.selected_N];
  selected_pass=all(isfinite(selected))&&all(selected==round(selected))&& ...
    all(selected>=1)&&all(selected<=max(c.full_p_levels));
  index=a.first_level_indices;
  index_pass=isequal(index.minus_physical_start(:).',[0,0,0,1,0])&& ...
    isequal(index.plus_physical_start(:).',[0,0,0,1,0])&& ...
    index.minus_selected_N==selected(1)&&index.plus_selected_N==selected(2);
  center_dims=numel(a.center_left_value_lift_source)==512&& ...
    numel(a.center_right_value_lift_source)==512;
  pass=scalar_defect<=c.identity_tol&&factor_dims&&factor_finite&& ...
    selected_pass&&index_pass&&center_dims;
  out=struct('pass',pass,'scalar_relative_defect',scalar_defect, ...
    'factor_dimensions',factor_dims,'factor_finite',factor_finite, ...
    'selected_N_minus_plus',selected,'index_contract_pass',index_pass, ...
    'same_finite_field_partial_center',true);
end

function [pass,out,E]=LOCAL_branch_identity(z,c)
  b=z.branch_port; required={'beta_m','gamma_m','t_m','classification', ...
    'outgoing_reference','outgoing_relative_defects','outgoing_sign_pass', ...
    'axis_pass','available','pass'};
  fields=all(isfield(b,required)); E=[];
  if ~fields
    pass=false;
    out=struct('pass',false,'fields_available',false);
    return;
  end
  orders=(-c.M:c.M).'; beta=c.beta+2*pi*orders/c.d;
  t=c.khat^2-beta.^2; gamma=sqrt(complex(t));
  flip=imag(gamma)<0|(imag(gamma)==0&real(gamma)<0); gamma(flip)=-gamma(flip);
  exact_wood=any(t==0); prop=t>0; evan=t<0;
  classes=zeros(c.K,1,'int8'); classes(prop)=1; classes(evan)=-1;
  stored_class=int8(b.classification(:));
  beta_defect=LOCAL_relative_difference(b.beta_m(:),beta);
  gamma_defect=LOCAL_relative_difference(b.gamma_m(:),gamma);
  t_defect=LOCAL_relative_difference(b.t_m(:),t);
  ref_defect=LOCAL_relative_difference(b.outgoing_reference(:),gamma);
  class_pass=numel(stored_class)==c.K&&all(stored_class==classes);
  sign_pass=numel(b.outgoing_sign_pass)==c.K&&all(b.outgoing_sign_pass(:))&& ...
    numel(b.axis_pass)==c.K&&all(b.axis_pass(:));
  wood_margin=min(abs(t)./(c.khat^2+beta.^2));
  E=diag(exp(1i*b.gamma_m(:)*c.L));
  finite=all(isfinite([b.beta_m(:);b.gamma_m(:);b.t_m(:); ...
    b.outgoing_reference(:);b.outgoing_relative_defects(:);wood_margin]));
  pass=fields&&finite&&~exact_wood&&logical(b.available)&& ...
    beta_defect<=c.identity_tol&&gamma_defect<=c.identity_tol&& ...
    t_defect<=c.identity_tol&&ref_defect<=c.identity_tol&& ...
    class_pass&&sign_pass;
  out=struct('pass',pass,'fields_available',fields,'exact_Wood',exact_wood, ...
    'relative_Wood_margin',wood_margin,'beta_relative_defect',beta_defect, ...
    'gamma_relative_defect',gamma_defect,'t_relative_defect',t_defect, ...
    'reference_relative_defect',ref_defect,'class_pass',class_pass, ...
    'sign_and_axis_pass',sign_pass,'stored_qualification_pass',logical(b.pass));
end

function [pass,out]=LOCAL_center_identity(z,q,E,c)
  orders=(-256:255).'; retained=(-c.M:c.M).';
  embed=zeros(512,c.K);
  for j=1:c.K, embed(orders==retained(j),j)=1; end
  I=eye(c.K); qL=q(1:c.K); qR=q(c.K+1:end);
  actual_left=embed*(qL+E*qR); actual_right=embed*(E*qL+qR);
  shared_left=embed*z.Dminus*z.cminus;
  shared_right=embed*z.Dplus*z.cplus;
  left_parent_scale=max(norm(actual_left,'fro'),norm(shared_left,'fro'));
  right_parent_scale=max(norm(actual_right,'fro'),norm(shared_right,'fro'));
  certificate_metrics=struct( ...
    'actual_left',LOCAL_center_metric(z.center_actual_left_trace,actual_left, ...
      max(norm(z.center_actual_left_trace,'fro'),norm(actual_left,'fro')),c), ...
    'actual_right',LOCAL_center_metric(z.center_actual_right_trace,actual_right, ...
      max(norm(z.center_actual_right_trace,'fro'),norm(actual_right,'fro')),c), ...
    'shared_left',LOCAL_center_metric(z.center_shared_left_trace,shared_left, ...
      max(norm(z.center_shared_left_trace,'fro'),norm(shared_left,'fro')),c), ...
    'shared_right',LOCAL_center_metric(z.center_shared_right_trace,shared_right, ...
      max(norm(z.center_shared_right_trace,'fro'),norm(shared_right,'fro')),c), ...
    'mismatch_left',LOCAL_center_metric(z.center_left_value_mismatch, ...
      shared_left-actual_left,left_parent_scale,c), ...
    'mismatch_right',LOCAL_center_metric(z.center_right_value_mismatch, ...
      shared_right-actual_right,right_parent_scale,c), ...
    'repaired_left',LOCAL_center_metric(z.center_actual_left_trace+ ...
      z.center_left_value_mismatch,z.center_shared_left_trace, ...
      left_parent_scale,c), ...
    'repaired_right',LOCAL_center_metric(z.center_actual_right_trace+ ...
      z.center_right_value_mismatch,z.center_shared_right_trace, ...
      right_parent_scale,c));
  certificate_names=fieldnames(certificate_metrics);
  defects=zeros(1,numel(certificate_names));
  certificate_pass=true;
  for j=1:numel(certificate_names)
    metric=certificate_metrics.(certificate_names{j});
    defects(j)=metric.ratio;
    certificate_pass=certificate_pass&&metric.pass;
  end
  center=z.center_wall_jumps; required={'left_coefficients','right_coefficients', ...
    'actual_left_trace','actual_right_trace','shared_left_trace', ...
    'shared_right_trace','left_value_mismatch','right_value_mismatch'};
  fields=all(isfield(center,required)); center_defects=Inf(1,8); jump_dims=false;
  center_metrics=struct(); center_pass=false;
  if fields
    center_metrics=struct( ...
      'actual_left',LOCAL_center_metric(center.actual_left_trace,actual_left, ...
        max(norm(center.actual_left_trace,'fro'),norm(actual_left,'fro')),c), ...
      'actual_right',LOCAL_center_metric(center.actual_right_trace,actual_right, ...
        max(norm(center.actual_right_trace,'fro'),norm(actual_right,'fro')),c), ...
      'shared_left',LOCAL_center_metric(center.shared_left_trace,shared_left, ...
        max(norm(center.shared_left_trace,'fro'),norm(shared_left,'fro')),c), ...
      'shared_right',LOCAL_center_metric(center.shared_right_trace,shared_right, ...
        max(norm(center.shared_right_trace,'fro'),norm(shared_right,'fro')),c), ...
      'mismatch_left',LOCAL_center_metric(center.left_value_mismatch, ...
        shared_left-actual_left,left_parent_scale,c), ...
      'mismatch_right',LOCAL_center_metric(center.right_value_mismatch, ...
        shared_right-actual_right,right_parent_scale,c), ...
      'repaired_left',LOCAL_center_metric(center.actual_left_trace+ ...
        center.left_value_mismatch,center.shared_left_trace, ...
        left_parent_scale,c), ...
      'repaired_right',LOCAL_center_metric(center.actual_right_trace+ ...
        center.right_value_mismatch,center.shared_right_trace, ...
        right_parent_scale,c));
    center_names=fieldnames(center_metrics); center_pass=true;
    for j=1:numel(center_names)
      metric=center_metrics.(center_names{j});
      center_defects(j)=metric.ratio;
      center_pass=center_pass&&metric.pass;
    end
    jump_dims=numel(center.left_coefficients)==512&& ...
      numel(center.right_coefficients)==512;
  end
  finite=all(isfinite([defects,center_defects]));
  pass=fields&&jump_dims&&finite&&certificate_pass&&center_pass;
  out=struct('pass',pass,'relative_defects',defects, ...
    'stored_center_relative_defects',center_defects, ...
    'certificate_metrics',certificate_metrics, ...
    'stored_center_metrics',center_metrics, ...
    'left_parent_trace_scale',left_parent_scale, ...
    'right_parent_trace_scale',right_parent_scale, ...
    'stored_center_fields_available',fields,'jump_dimensions',jump_dims, ...
    'actual_trace_formula','embed*[I,E]q / embed*[E,I]q', ...
    'shared_trace_formula','embed*Dminus*cminus / embed*Dplus*cplus');
end

function out=LOCAL_center_metric(x,y,parent_scale,c)
  compatible=isequal(size(x),size(y))&&isfinite(parent_scale)&& ...
    parent_scale>=0&&all(isfinite([x(:);y(:)]));
  if compatible
    numerator=norm(x-y,'fro'); scale=max(realmin,parent_scale);
    allowance=100*eps*parent_scale;
    ratio=numerator/scale;
  else
    numerator=Inf; scale=realmin; allowance=0; ratio=Inf;
  end
  threshold=c.identity_tol;
  pass=compatible&&isfinite(ratio)&& ...
    numerator<=threshold*scale+allowance;
  out=struct('absolute_defect',numerator,'left_norm',norm(x,'fro'), ...
    'right_norm',norm(y,'fro'),'scale',scale, ...
    'roundoff_allowance',allowance,'ratio',ratio, ...
    'threshold',threshold,'zero_scale',parent_scale==0,'pass',pass);
end

function [pass,out]=LOCAL_raw_map_identity(a,z,c)
  K=c.K; dimensions=struct( ...
    'delta_plus',isequal(size(a.delta_plus),[512,K]), ...
    'delta_minus',isequal(size(a.delta_minus),[512,K]), ...
    'circle_jump_plus',isequal(size(a.circle_jump_plus),[512,K]), ...
    'circle_jump_minus',isequal(size(a.circle_jump_minus),[512,K]), ...
    'QLplus',isequal(size(a.QLplus),[512,K]), ...
    'QRplus',isequal(size(a.QRplus),[512,K]), ...
    'QLminus',isequal(size(a.QLminus),[512,K]), ...
    'QRminus',isequal(size(a.QRminus),[512,K]), ...
    'Jplus',isequal(size(a.Jplus),[512,K]), ...
    'Jminus',isequal(size(a.Jminus),[512,K]), ...
    'wall_flux_left_unit',isequal(size(a.wall_flux_left_unit_512),[512,2*K]), ...
    'wall_flux_right_unit',isequal(size(a.wall_flux_right_unit_512),[512,2*K]), ...
    'circle_delta_unit',isequal(size(a.circle_delta_D_unit_wall_512),[512,2*K]), ...
    'circle_jump_unit',isequal(size(a.circle_j_Gamma_unit_wall_512),[512,2*K]), ...
    'wall_input_unit',isequal(size(a.wall_input_unit_512),[1024,2*K]), ...
    'circle_value_residual_unit', ...
      isequal(size(a.circle_value_residual_unit_512),[512,2*K]), ...
    'circle_normal_residual_unit', ...
      isequal(size(a.circle_normal_residual_unit_512),[512,2*K]), ...
    'wall_common_value',isequal(size(a.wall_common_value_1024),[2048,2*K]), ...
    'wall_common_flux',isequal(size(a.wall_common_flux_1024),[2048,2*K]));
  names=fieldnames(dimensions); dim_pass=true;
  for j=1:numel(names), dim_pass=dim_pass&&dimensions.(names{j}); end
  wall_orders=(-256:255).'; circle_theta=(0:511)'*2*pi/512;
  order_defect=LOCAL_relative_difference(z.wall_orders_512(:),wall_orders);
  circle_order_defect=LOCAL_relative_difference( ...
    a.circle_orders_512(:),wall_orders);
  theta_defect=LOCAL_relative_difference(a.circle_theta_512(:),circle_theta);
  y=a.wall_common_y_1024(:); y_reference=-c.d/2+c.d*(0:1023)'/1024;
  y_defect=LOCAL_relative_difference(y,y_reference);
  q=z.q_center; qL=q(1:K); qR=q(K+1:end); gamma=z.branch_port.gamma_m(:);
  E=exp(1i*gamma*z.L); dxL=1i*gamma.*(qL-E.*qR);
  dxR=1i*gamma.*(E.*qL-qR); embed=zeros(512,K);
  retained=(-c.M:c.M).'; for j=1:K, embed(wall_orders==retained(j),j)=1; end
  reconstructed_left=a.QRminus*z.cminus-embed*dxL;
  reconstructed_right=embed*dxR+a.QLplus*z.cplus;
  center_jump_defect=max( ...
    LOCAL_relative_difference(reconstructed_left, ...
      z.center_wall_jumps.left_coefficients), ...
    LOCAL_relative_difference(reconstructed_right, ...
      z.center_wall_jumps.right_coefficients));
  finite=all(isfinite([order_defect,circle_order_defect,theta_defect, ...
    y_defect,center_jump_defect]));
  pass=dim_pass&&finite&&max([order_defect,circle_order_defect, ...
    theta_defect,y_defect,center_jump_defect])<=c.identity_tol;
  out=struct('pass',pass,'dimensions',dimensions, ...
    'wall_order_relative_defect',order_defect, ...
    'circle_order_relative_defect',circle_order_defect, ...
    'circle_theta_relative_defect',theta_defect, ...
    'wall_common_grid_relative_defect',y_defect, ...
    'center_wall_jump_association_defect',center_jump_defect);
end

function value=LOCAL_relative_difference(x,y)
  if ~isequal(size(x),size(y))||any(~isfinite([x(:);y(:)]))
    value=Inf;
  else
    value=norm(x-y,'fro')/max([realmin,norm(x,'fro'),norm(y,'fro')]);
  end
end

function out=LOCAL_preflight(c,s,conversion,original_mib,normalization_peak)
  staged_mib=LOCAL_mib({s}); ledger_mib=LOCAL_mib({conversion});
  estimate=max(normalization_peak, ...
    staged_mib+ledger_mib+c.worst_transient_mib);
  out=struct('estimated_seconds',c.expected_seconds, ...
    'estimated_peak_mib',estimate, ...
    'original_integer_storage_staged_mib',original_mib, ...
    'double_expanded_staged_mib',staged_mib, ...
    'conversion_ledger_mib',ledger_mib, ...
    'normalization_peak_mib',normalization_peak, ...
    'staged_input_active_mib',staged_mib, ...
    'worst_streaming_transient_mib',c.worst_transient_mib, ...
    'allocation_combination',[ ...
      'max(original + double-expanded + ledger during normalization, ', ...
      'double-expanded staged input + ledger + worst simultaneous transient)'], ...
    'maximum_seconds',c.preflight_seconds_max, ...
    'maximum_peak_mib',c.preflight_mib_max, ...
    'streamed_target_mode_image_contributions',470e6, ...
    'pass',c.expected_seconds<=c.preflight_seconds_max&& ...
      estimate<=c.preflight_mib_max,'no_fallback_levels',true);
end

function out=LOCAL_zero_counters()
  out=struct('candidate_solve_calls',0,'qz_solve_calls',0, ...
    'coordinate_solve_calls',0,'propagation_solve_calls',0, ...
    'wall_density_solve_calls',0,'circle_density_solve_calls',0, ...
    'schur_solve_calls',0,'proxy_build_calls',0, ...
    'harmonic_action_calls',0,'image_pair_updates',0, ...
    'kress_oracle_calls',0,'linton_oracle_calls',0, ...
    'actual_deltaT_action_calls',0,'finite_bloch_image_updates',0, ...
    'riccati_calls',0,'gauss_factor_calls',0, ...
    'full_p_contraction_calls',0);
end

function out=LOCAL_add_counters(out,new)
  names=fieldnames(new);
  for j=1:numel(names)
    if ~isfield(out,names{j}), out.(names{j})=0; end
    out.(names{j})=out.(names{j})+new.(names{j});
  end
end

function pass=LOCAL_all_zero(counters)
  names={'candidate_solve_calls','qz_solve_calls','coordinate_solve_calls', ...
    'propagation_solve_calls','wall_density_solve_calls', ...
    'circle_density_solve_calls','schur_solve_calls','proxy_build_calls'};
  values=zeros(size(names));
  for j=1:numel(names), values(j)=counters.(names{j}); end
  pass=all(values==0);
end

%% ==================== Result and resource ledger ====================
% Failures preserve completed ordinary diagnostics without upgrading claims.

function result=LOCAL_empty_result(attempt,c,s)
  empty=LOCAL_condition('NONE','None.');
  not_reached=LOCAL_condition('NOT_REACHED', ...
    'Scientific evaluation was not reached.');
  result=struct('schema',c.schema,'attempt',attempt,'command',c.command, ...
    'retry_count',c.retry_count, ...
    'prior_failed_attempt_count',c.prior_failed_attempt_count, ...
    'prior_attempts',c.prior_attempts, ...
    'input_contract',s.input_contract, ...
    'input_schema',char(s.input_contract.schema), ...
    'source_attempt',char(s.input_contract.source_attempt), ...
    'status','I3_2_EXECUTION_UNAVAILABLE','scientific_outcome','UNAVAILABLE', ...
    'cap_status','EMPIRICAL_CAP_UNRESOLVED','execution_pass',false, ...
    'first_execution_blocker',empty, ...
    'first_empirical_unavailable',not_reached, ...
    'first_nonblocking_warning',not_reached, ...
    'nonblocking_warnings',struct('code',{},'value',{},'blocking',{}), ...
    'coverage',LOCAL_coverage(),'qualification',struct(), ...
    'reliability',LOCAL_reliability_flags(),'resources',struct(), ...
    'call_counters',LOCAL_zero_counters(),'identity',struct(), ...
    'resource_preflight',struct(),'evaluation',struct(),'components',struct(), ...
    'caps',struct(),'estimator',struct(),'tails',struct(), ...
    'axis_metrics',struct(),'unresolved_axes',{{'NOT_REACHED'}}, ...
    'arithmetic',struct(), ...
    'audit',struct(),'certificate_summary',struct(), ...
    'input_storage_conversion',struct(), ...
    'ordinary_anchor',LOCAL_anchor_summary(s.ordinary_anchor), ...
    'historical_diagnostics',s.historical_diagnostics, ...
    'no_resolve_call_counts',LOCAL_zero_counters(), ...
    'levels',struct('circle',c.circle_levels,'image',c.image_levels, ...
      'wall',c.wall_levels,'riccati',c.riccati_levels, ...
      'gauss',c.gauss_levels,'full_p',c.full_p_levels), ...
    'level_ledger',struct('circle',c.circle_levels,'images',c.image_levels, ...
      'wall',c.wall_levels,'riccati',c.riccati_levels, ...
      'gauss',c.gauss_levels,'full_P',c.full_p_levels), ...
    'elapsed_seconds',NaN,'peak_active_mib',NaN,'soft_time_exceeded',false);
end

function out=LOCAL_qualification(r)
  evaluation_available=isfield(r.evaluation,'record')&& ...
    isfield(r.evaluation.record,'core_maps_available')&& ...
    r.evaluation.record.core_maps_available;
  kernel=false; conformity=false; actual_T=false; finite_bloch=false;
  if evaluation_available
    kernel=r.evaluation.record.kernel_qualified;
    conformity=r.evaluation.record.conformity_qualified;
    actual_T=r.evaluation.record.actual_T_action_qualified;
    finite_bloch=r.evaluation.record.finite_image_Bloch_qualified;
  end
  out=struct('certificate_identity',isfield(r.identity,'pass')&&r.identity.pass, ...
    'same_trial_evaluation_available',evaluation_available, ...
    'kernel_oracles_qualified',kernel,'conformity_qualified',conformity, ...
    'actual_DeltaT_action_qualified',actual_T, ...
    'finite_image_Bloch_qualified',finite_bloch, ...
    'empirical_cap_supported',strcmp(r.cap_status, ...
      'EMPIRICALLY_SUPPORTED_EVALUATION_CAP'), ...
    'all_nonblocking_warnings_clear', ...
      evaluation_available&&isempty(r.nonblocking_warnings), ...
    'ordinary_double_only',true,'strict_theorem_hypotheses_instantiated',false);
end

function out=LOCAL_anchor_summary(a)
  out=struct('B_wall',a.B_wall,'B_circle',a.B_circle, ...
    'B_volume',a.B_volume,'M_tilde',a.M_tilde,'N_tilde',a.N_tilde, ...
    'tail_minus_selected_N',a.tail_minus.selected_N, ...
    'tail_plus_selected_N',a.tail_plus.selected_N, ...
    'ordinary_double',true);
end

function out=LOCAL_coverage()
  out=struct('fixed_certificate_consumed',false, ...
    'same_density_actions_computed',false, ...
    'actual_DeltaT_actions_computed',false, ...
    'finite_image_Bloch_actions_computed',false, ...
    'all_fresh_computed_modes_included',false, ...
    'empirical_numerator_cap_computed',false, ...
    'empirical_denominator_cap_computed',false, ...
    'nominal_transform_computed',false, ...
    'mathematical_trial_redefined',false, ...
    'continuous_error_enclosed',false, ...
    'uncomputed_fourier_tail_enclosed',false, ...
    'uncomputed_image_tail_enclosed',false, ...
    'independent_reference',false);
end

function out=LOCAL_reliability_flags()
  out=struct('rigorous_cap',false,'residual_upper_enclosed',false, ...
    'field_lower_enclosed',false,'image_tail_enclosed',false, ...
    'fourier_tail_enclosed',false,'arithmetic_directed',false, ...
    'same_operator_gap_certified',false,'spectral_interval_certified',false, ...
    'eigenvalue_exists',false,'independent_reference',false, ...
    'effectivity_validated',false);
end

function result=LOCAL_execution_fail(result,ME)
  result.execution_pass=false;
  switch ME.identifier
    case {'i32e:CertificateIdentity','i32e:InputStorageClass', ...
        'i32e:InputStorageValue','i32e:InputStoragePath'}
      result.status='I3_2_CERTIFICATE_IDENTITY_MISMATCH';
      result.scientific_outcome='CERTIFICATE_IDENTITY_MISMATCH';
    case {'i32e:ExactWood','i32e:BranchUnavailable'}
      result.status='I3_2_BRANCH_OR_WOOD_UNAVAILABLE';
      result.scientific_outcome='BRANCH_OR_WOOD_UNAVAILABLE';
    case {'i32e:ResourcePreflight','i32e:Resource','i32e:HardTime','i32e:SoftTime'}
      result.status='I3_2_RESOURCE_BUDGET_UNAVAILABLE';
      result.scientific_outcome='RESOURCE_BUDGET_UNAVAILABLE';
    otherwise
      result.status='I3_2_EXECUTION_UNAVAILABLE';
      result.scientific_outcome='UNAVAILABLE';
  end
  result.first_execution_blocker=LOCAL_condition(ME.identifier,ME.message);
  result.exception=struct('identifier',ME.identifier,'message',ME.message, ...
    'stack',{ME.stack});
end

function out=LOCAL_condition(code,message)
  out=struct('code',char(code),'message',char(message));
end

function out=LOCAL_first_warning(warnings)
  if isempty(warnings)
    out=LOCAL_condition('NONE','No nonblocking warning was recorded.');
  else
    out=LOCAL_condition(warnings(1).code, ...
      sprintf('Nonblocking metric value %.17g.',warnings(1).value));
  end
end

function LOCAL_soft_gate(timer,c,next_stage)
  if toc(timer)>c.soft_seconds
    error('i32e:SoftTime', ...
      'The soft limit forbids starting %s.',next_stage);
  end
end

function LOCAL_resource_gate(timer,peak,c)
  if toc(timer)>c.hard_seconds||peak>c.memory_mib_max
    error('i32e:Resource','The hard time or memory budget was exceeded.');
  end
end

function value=LOCAL_mib(items)
  value=0;
  for j=1:numel(items)
    item=items{j}; info=whos('item'); value=value+info.bytes/2^20;
  end
end

%% ==================== Append-only report ====================
% The report distinguishes empirical evaluation support from reliability.

function LOCAL_report(path,r)
  if exist(path,'file')||exist(path,'dir')
    error('i32e:ReportExists','Refusing to overwrite an existing report.');
  end
  [fid,message]=fopen(path,'w');
  if fid<0
    error('i32e:ReportOpen','Could not create report: %s.',message);
  end
  cleanup=onCleanup(@() fclose(fid));
  fprintf(fid,'# I3.2 same-trial evaluation-cap report\n\n');
  fprintf(fid,'- Attempt: `%s`\n',r.attempt);
  fprintf(fid,'- Status: `%s`\n',r.status);
  fprintf(fid,'- Scientific outcome: `%s`\n',r.scientific_outcome);
  fprintf(fid,'- Cap status: `%s`\n',r.cap_status);
  fprintf(fid,'- Elapsed: %.17g s\n',r.elapsed_seconds);
  fprintf(fid,'- Peak active memory: %.17g MiB\n',r.peak_active_mib);
  if isfield(r,'resources')&&isfield(r.resources,'preflight')&& ...
      isfield(r.resources.preflight,'estimated_peak_mib')
    fprintf(fid,'- Preflight estimated time / peak: %.17g s / %.17g MiB\n', ...
      r.resources.preflight.estimated_seconds, ...
      r.resources.preflight.estimated_peak_mib);
  end
  if isfield(r,'resources')&&isfield(r.resources,'actual')&& ...
      isfield(r.resources.actual,'evaluation_helper_peak_mib')
    fprintf(fid,'- Measured evaluation / cap helper-local peaks: %.17g / %.17g MiB\n', ...
      r.resources.actual.evaluation_helper_peak_mib, ...
      r.resources.actual.cap_helper_peak_mib);
  end
  fprintf(fid,'- First execution blocker: `%s` -- %s\n', ...
    r.first_execution_blocker.code,r.first_execution_blocker.message);
  fprintf(fid,'- First empirical unavailable: `%s` -- %s\n', ...
    r.first_empirical_unavailable.code,r.first_empirical_unavailable.message);
  fprintf(fid,'- First warning: `%s` -- %s\n\n', ...
    r.first_nonblocking_warning.code,r.first_nonblocking_warning.message);
  if isfield(r,'certificate_summary')&&isfield(r.certificate_summary,'pass')
    fprintf(fid,'- Certificate identity pass: `%d`\n',r.certificate_summary.pass);
  end
  if isfield(r,'historical_diagnostics')&& ...
      isfield(r.historical_diagnostics,'circle_action_metric')
    h=r.historical_diagnostics.circle_action_metric;
    if isstruct(h)&&all(isfield(h,{'ratio','numerator','left_norm','right_norm'}))
      fprintf(fid,['- Historical fbie-a1 circle-action ratio / numerator / ', ...
        'side norms (background only): %.17g / %.17g / %.17g / %.17g\n'], ...
        h.ratio,h.numerator,h.left_norm,h.right_norm);
    else
      fprintf(fid,'- Historical fbie-a1 circle-action background unavailable.\n');
    end
  end
  if isfield(r,'qualification')
    fprintf(fid,['- Kernel / conformity / actual Delta-T / finite-image ', ...
      'Bloch / cap qualified: `%d` / `%d` / `%d` / `%d` / `%d`\n'], ...
      r.qualification.kernel_oracles_qualified, ...
      r.qualification.conformity_qualified, ...
      r.qualification.actual_DeltaT_action_qualified, ...
      r.qualification.finite_image_Bloch_qualified, ...
      r.qualification.empirical_cap_supported);
  end
  if isfield(r.evaluation,'circle')&& ...
      isfield(r.evaluation.circle,'actual_T_action')
    fprintf(fid,'- Actual fixed-density Delta-T maximum contraction ratio: %.17g\n', ...
      r.evaluation.circle.actual_T_action.maximum_contraction_ratio);
  end
  if isfield(r.evaluation,'circle')&& ...
      isfield(r.evaluation.circle,'finite_image_bloch')
    fprintf(fid,'- Finite-image physical Bloch final value/flux ratio: %.17g\n', ...
      r.evaluation.circle.finite_image_bloch.maximum_final_ratio);
  end
  if isfield(r,'unresolved_axes')&&~isempty(r.unresolved_axes)
    fprintf(fid,'- Unresolved axes: `%s`\n',strjoin(r.unresolved_axes,', '));
  else
    fprintf(fid,'- Unresolved axes: `NONE`\n');
  end
  fprintf(fid,'- Forbidden NO_RESOLVE call counters all zero: `%d`\n\n', ...
    LOCAL_all_zero(r.no_resolve_call_counts));
  fprintf(fid,['- Actual Delta-T actions / finite-image Bloch updates / ', ...
    'full-P contraction sequences: %.0f / %.0f / %.0f\n\n'], ...
    r.no_resolve_call_counts.actual_deltaT_action_calls, ...
    r.no_resolve_call_counts.finite_bloch_image_updates, ...
    r.no_resolve_call_counts.full_p_contraction_calls);
  fprintf(fid,'## Nonblocking warnings\n\n');
  if isempty(r.nonblocking_warnings)
    fprintf(fid,'- `NONE`\n\n');
  else
    for j=1:numel(r.nonblocking_warnings)
      fprintf(fid,'- `%s`: %.17g\n',r.nonblocking_warnings(j).code, ...
        r.nonblocking_warnings(j).value);
    end
    fprintf(fid,'\n');
  end
  if isfield(r,'caps')&&isfield(r.caps,'epsilon_M_emp')
    fprintf(fid,'## Ordinary centers and empirical evaluation caps\n\n');
    fprintf(fid,'- M tilde: %.17g\n',r.caps.M_tilde);
    fprintf(fid,'- N tilde: %.17g\n',r.caps.N_tilde);
    fprintf(fid,'- epsilon W/Gamma/V: %.17g / %.17g / %.17g\n', ...
      r.caps.epsilon_W_emp,r.caps.epsilon_Gamma_emp,r.caps.epsilon_V_emp);
    fprintf(fid,'- epsilon M: %.17g\n',r.caps.epsilon_M_emp);
    fprintf(fid,'- epsilon N: %.17g\n',r.caps.epsilon_N_emp);
  end
  if isfield(r,'estimator')&&isfield(r.estimator,'q_emp')
    fprintf(fid,'- q emp: %.17g\n',r.estimator.q_emp);
    fprintf(fid,'- Nominal k interval: [%.17g, %.17g]\n', ...
      r.estimator.k_lower,r.estimator.k_upper);
    fprintf(fid,'- Nominal width: %.17g\n',r.estimator.width);
  end
  fprintf(fid,'\n## Claim boundary\n\n');
  fprintf(fid,['This output is ordinary-double, same-chain, and empirical. ', ...
    'It is not a rigorous cap, reliable residual upper bound, certified ', ...
    'field lower bound, spectral enclosure, gap certificate, existence ', ...
    'result, independent reference, or effectivity validation.\n']);
  clear cleanup;
end
