function out = i32_circle_module(c,staged,lift_private,wall_public,timer,retained_before_mib)
%I32_CIRCLE_MODULE Evaluate the frozen material-circle action and oracles.
% Purpose:
%   Stream the seven image and three angular levels of the fixed-density
%   circle action, form compact signatures, and run the frozen kernel gates.
% Input:
%   c, staged, lift_private, wall_public, timer - Frozen same-trial inputs.
%   retained_before_mib                         - Caller active-object proxy.
% Output:
%   out                                         - Typed total module result.
% Main algorithm:
%   Accumulate symmetric QP images once, consume every checkpoint in place,
%   retain only pending registered pairs, and project the finest angular
%   action to side factors.  Kernel, Delta-T, Bloch, and conformity gates
%   use the unchanged Revision E formulas.
% Based on:
%   i32_same_eval.m circle, finite-Bloch, oracle, and structural helpers.
% Main changes:
%   Dense image/angular coefficient ladders and raw target samples never
%   enter the module return; nested differences release pending arrays.
% Numerical goal:
%   Preserve the full circle residual bandwidth independently of wall M=48.

  warnings=LOCAL_empty_warnings(); calls=LOCAL_zero_counters(); peak=0;
  first=LOCAL_condition('NONE','The circle action and kernel oracles are available.');
  available=false; public=struct(); finest=struct(); signatures=struct();
  input_alias=LOCAL_value_mib(staged)+LOCAL_value_mib(lift_private)+ ...
    LOCAL_value_mib(wall_public); peak=max(peak,LOCAL_workspace_mib());
  try
    z=staged.certificate; density=LOCAL_density_coefficients(z);
    [science,calls,peak]=LOCAL_stream_circle( ...
      c,z,density,lift_private,calls,peak,timer);
    oracle=LOCAL_oracles(c,z,density,science.angular_action_metric,calls);
    calls=oracle.call_counters;
    structural=LOCAL_structural_metrics(c,z,density,science,wall_public,oracle);
    parity=LOCAL_collect_parity(science.signatures);
    warnings=LOCAL_scientific_warnings( ...
      c,science,oracle,structural,parity);
    core=science.actions_finite;
    available=core&&oracle.available;
    if ~core
      first=LOCAL_condition('CIRCLE_ACTION_UNAVAILABLE', ...
        'A required fixed-density circle action is nonfinite.');
    elseif ~oracle.available
      first=LOCAL_condition('KERNEL_ORACLE_UNAVAILABLE', ...
        'A required analytic kernel oracle is unavailable.');
    end
    finest=science.finest_factors; signatures=science.signatures;
    public=struct('image_levels',science.image_public, ...
      'angular_levels',science.angular_public, ...
      'wronskian',science.wronskian, ...
      'repaired_value_metric',science.repaired_value_metric, ...
      'actual_T_action',science.actual_T_action, ...
      'finite_image_bloch',science.finite_image_bloch, ...
      'angular_action_metric',science.angular_action_metric, ...
      'oracles',oracle.record,'structural_metrics',structural, ...
      'producer_signature_parity',parity, ...
      'core_maps_available',core,'kernel_oracles_available',oracle.available, ...
      'kernel_qualified',oracle.qualified, ...
      'actual_T_action_qualified',science.actual_T_action.qualified, ...
      'finite_image_Bloch_qualified',science.finite_image_bloch.qualified, ...
      'conformity_qualified',structural.pass, ...
      'all_computed_circle_modes_retained',true, ...
      'circle_order_min',-1024,'circle_order_max',1023, ...
      'circle_order_count',2048,'wall_M_role','wall trace order only', ...
      'dense_coefficient_ladders_returned',false, ...
      'raw_target_samples_returned',false);
    calls.n_op_signature_parity=parity.total_operations;
  catch ME
    available=false; first=LOCAL_condition(ME.identifier,ME.message);
    finest=struct(); signatures=struct();
  end
  peak=max(peak,LOCAL_workspace_mib());
  clear staged lift_private wall_public timer z density science oracle;
  clear structural parity core;
  audit=struct('returned_field_inventory',{{}}, ...
    'returned_numeric_shape_inventory',{{}},'prohibited_field_count',NaN, ...
    'prohibited_shape_count',NaN,'last_use_clear_ledger', ...
      LOCAL_liveness_ledger(), ...
    'post_clear_local_owner_inventory',{LOCAL_owner_inventory()}, ...
    'finest_factor_whitelist',{{ ...
      'finest_factors.jump_minus','finest_factors.jump_plus', ...
      'finest_factors.delta_minus','finest_factors.delta_plus'}}, ...
    'compact_signature_whitelist',{{'cap_signatures.image', ...
      'cap_signatures.image_pairs','cap_signatures.angular', ...
      'cap_signatures.angular_pairs','cap_signatures.joint'}}, ...
    'signature_parity_coverage',LOCAL_collect_parity(signatures), ...
    'normal_orientation','circle global +r', ...
    'density_coordinate','[tau;zeta], zeta=-sigma', ...
    'raw_samples_returned',false,'coefficient_ladders_returned',false);
  payload=struct('available',available,'first_unavailable',first, ...
    'public_metrics',public,'finest_factors',finest, ...
    'cap_signatures',signatures,'audit_summary',audit,'warnings',warnings, ...
    'call_counters',calls,'resource_record',struct());
  payload.resource_record=LOCAL_resource_record(retained_before_mib, ...
    input_alias,peak,LOCAL_value_mib(payload),c);
  out=payload;
end

%% ==================== Streamed circle action ====================
% Pending coefficient/factor arrays survive only until their registered pair.

function [out,calls,peak]=LOCAL_stream_circle(c,z,density,lift,calls,peak,timer)
  Nfinal=max(c.circle_levels); theta=(0:Nfinal-1)'*2*pi/Nfinal;
  x=z.R*cos(theta); y=z.R*sin(theta); nx=cos(theta); ny=sin(theta);
  ko=z.khat; ki=sqrt(z.rho_disk)*z.khat;
  [ve0,dve0,vi0,dvi0,wronskian,tout0,tin0,dsout0,dsin0]= ...
    LOCAL_free_self(z,density,theta,ko,ki);
  [vw,dvw]=LOCAL_wall_to_circle(z,density,theta,x,y,nx,ny);
  image_value=zeros(Nfinal,size(density.tau,2)); image_dr=image_value;
  image_T_tau=image_value; image_dS_zeta=image_value;
  pairs=[3,5;5,7;2,4;4,6;6,7];
  pair_labels={'64_to_128','128_to_256','48_to_96', ...
    '96_to_192','192_to_256'};
  image_endpoints=cell(1,7); image_pairs=cell(1,5);
  image_public=cell(1,7); pending_factor=cell(1,7); pending_T=cell(1,7);
  T_metrics=cell(1,5); image_T_scale=realmin; hit=1;
  joint_factors=struct(); joint_endpoint=struct();
  for n=1:max(c.image_levels)
    for signn=[-1,1]
      [dv,ddr,dTtau,dSzeta]=LOCAL_one_image( ...
        z,density,theta,x,y,nx,ny,signn*n);
      image_value=image_value+dv; image_dr=image_dr+ddr;
      image_T_tau=image_T_tau+dTtau;
      image_dS_zeta=image_dS_zeta+dSzeta;
      calls.image_pair_updates=calls.image_pair_updates+1;
    end
    if hit<=numel(c.image_levels)&&n==c.image_levels(hit)
      vp=ve0+vw+image_value; dp=dve0+dvw+image_dr;
      tp=tout0+image_T_tau; sp=dsout0+image_dS_zeta;
      level=LOCAL_circle_level(vp,vi0,dp,dvi0,tp,tin0,sp,dsin0, ...
        dvw,z.R,Nfinal,Nfinal,c.identity_tol);
      level.label=sprintf('image-J-%d',n); level.J=n;
      factor=LOCAL_circle_factors(level,z,lift.circle_weights{end}, ...
        lift.collar_weights{end}/z.gamma);
      factor.circle.endpoint_id=[level.label,'-circle'];
      factor.volume.endpoint_id=[level.label,'-volume-circle'];
      image_endpoints{hit}=struct( ...
        'circle',LOCAL_endpoint_signature(c,[level.label,'-circle'], ...
          'circle',factor.circle_minus,factor.circle_plus,z,zeros(0,1),32), ...
        'volume_circle',LOCAL_endpoint_signature(c, ...
          [level.label,'-volume-circle'],'volume-circle', ...
          factor.volume_minus,factor.volume_plus,z,zeros(0,1),32), ...
        'J',n);
      image_public{hit}=LOCAL_level_summary(level);
      image_T_scale=max(image_T_scale,norm(level.actual_deltaT_coeff,'fro'));
      finish=find(pairs(:,2)==hit).';
      for pair_index=finish
        left=pairs(pair_index,1);
        image_pairs{pair_index}=struct( ...
          'circle',LOCAL_pair_signature(c,pending_factor{left}.circle, ...
            factor.circle,z,32,32), ...
          'volume_circle',LOCAL_pair_signature(c, ...
            pending_factor{left}.volume,factor.volume,z, ...
            32,32), ...
          'label',pair_labels{pair_index});
        T_metrics{pair_index}=LOCAL_metric_record( ...
          pending_T{left},level.actual_deltaT_coeff,NaN);
        pending_factor{left}=[]; pending_T{left}=[];
      end
      if any(pairs(:,1)==hit)
        pending_factor{hit}=factor; pending_T{hit}=level.actual_deltaT_coeff;
      end
      if hit==6
        joint_level=LOCAL_restrict_samples(vp-vi0,dvi0-dp,tp-tin0, ...
          z.R,1024,Nfinal,c.identity_tol,-tp+tin0+sp-dsin0-dvw);
        joint_factors=LOCAL_circle_factors(joint_level,z, ...
          lift.circle_weights{2},lift.collar_weights{2}/z.gamma);
        joint_factors.circle.endpoint_id='joint-circle-circle';
        joint_factors.volume.endpoint_id='joint-circle-volume-circle';
        joint_endpoint=struct( ...
          'circle',LOCAL_endpoint_signature(c,'joint-circle-circle', ...
            'circle',joint_factors.circle_minus,joint_factors.circle_plus, ...
            z,zeros(0,1),16), ...
          'volume_circle',LOCAL_endpoint_signature(c, ...
            'joint-circle-volume-circle','volume-circle', ...
            joint_factors.volume_minus,joint_factors.volume_plus, ...
            z,zeros(0,1),16), ...
          'image_J',n,'angular_nodes',1024, ...
          'riccati_level',c.riccati_levels(2), ...
          'gauss_level',c.gauss_levels(2),'selected_full_p_N',16);
        clear joint_level;
      end
      clear vp dp tp sp level factor finish;
      hit=hit+1;
    end
    if mod(n,16)==0
      LOCAL_hard_time(timer,c,'image action');
      peak=max(peak,LOCAL_workspace_mib());
    end
  end
  calls.harmonic_action_calls=calls.harmonic_action_calls+1;

  final_vp=ve0+vw+image_value; final_dp=dve0+dvw+image_dr;
  final_tp=tout0+image_T_tau; final_sp=dsout0+image_dS_zeta;
  angular_endpoints=cell(1,3); angular_pairs=cell(1,2);
  angular_public=cell(1,3); angular_T_metrics=cell(1,2);
  angular_jump_metrics=cell(1,2);
  angular_T_scale=realmin; previous=struct(); previous_T=[];
  previous_jump=[];
  final_factors=struct(); final_level=struct();
  for j=1:3
    Nt=c.circle_levels(j); stride=Nfinal/Nt; index=1:stride:Nfinal;
    level=LOCAL_circle_level(final_vp(index,:),vi0(index,:), ...
      final_dp(index,:),dvi0(index,:),final_tp(index,:),tin0(index,:), ...
      final_sp(index,:),dsin0(index,:),dvw(index,:), ...
      z.R,Nt,Nfinal,c.identity_tol);
    level.label=sprintf('angular-N-%d',Nt); level.J=max(c.image_levels);
    factor=LOCAL_circle_factors(level,z,lift.circle_weights{end}, ...
      lift.collar_weights{end}/z.gamma);
    factor.circle.endpoint_id=[level.label,'-circle'];
    factor.volume.endpoint_id=[level.label,'-volume-circle'];
    angular_endpoints{j}=struct( ...
      'circle',LOCAL_endpoint_signature(c,[level.label,'-circle'], ...
        'circle',factor.circle_minus,factor.circle_plus,z,zeros(0,1),32), ...
      'volume_circle',LOCAL_endpoint_signature(c, ...
        [level.label,'-volume-circle'],'volume-circle', ...
        factor.volume_minus,factor.volume_plus,z,zeros(0,1),32), ...
      'target_nodes',Nt);
    angular_public{j}=LOCAL_level_summary(level);
    angular_T_scale=max(angular_T_scale,norm(level.actual_deltaT_coeff,'fro'));
    if j>1
      angular_pairs{j-1}=struct( ...
        'circle',LOCAL_pair_signature(c,previous.circle,factor.circle,z, ...
          32,32), ...
        'volume_circle',LOCAL_pair_signature(c,previous.volume,factor.volume,z, ...
          32,32));
      angular_T_metrics{j-1}=LOCAL_metric_record( ...
        previous_T,level.actual_deltaT_coeff,NaN);
      angular_jump_metrics{j-1}=LOCAL_metric_record( ...
        previous_jump,level.jump_coeff,c.action_ratio_max);
      clear previous previous_T previous_jump;
    end
    previous=struct('circle',factor.circle,'volume',factor.volume);
    previous_T=level.actual_deltaT_coeff;
    previous_jump=level.jump_coeff;
    if j==3
      final_factors=factor; final_level=level;
    end
    clear factor level index;
    peak=max(peak,LOCAL_workspace_mib());
  end
  clear previous previous_T previous_jump;
  joint_pair=struct( ...
    'circle',LOCAL_pair_signature(c,joint_factors.circle, ...
      final_factors.circle,z,16,32), ...
    'volume_circle',LOCAL_pair_signature(c,joint_factors.volume, ...
      final_factors.volume,z,16,32));
  joint=joint_endpoint; joint.pair_to_final=joint_pair;
  clear joint_factors joint_pair;

  actual_T=LOCAL_actual_T_qualification(c,[T_metrics{:}],image_T_scale, ...
    [angular_T_metrics{:}],angular_T_scale, ...
    numel(final_level.actual_deltaT_coeff));
  calls.actual_deltaT_action_calls=calls.actual_deltaT_action_calls+ ...
    numel(c.image_levels)+numel(c.circle_levels);
  [finite_bloch,calls]=LOCAL_finite_image_bloch(c,z,density,calls);
  raw_delta=final_vp-vi0;
  repair=LOCAL_metric_record(final_vp-raw_delta/2, ...
    vi0+raw_delta/2,c.identity_tol);
  finest=struct('jump_minus',final_level.jump_coeff*z.Gminus, ...
    'jump_plus',final_level.jump_coeff*z.Gplus, ...
    'delta_minus',final_level.delta_coeff*z.Gminus, ...
    'delta_plus',final_level.delta_coeff*z.Gplus);
  signatures=struct('image',{image_endpoints}, ...
    'image_pairs',{image_pairs},'angular',{angular_endpoints}, ...
    'angular_pairs',{angular_pairs},'joint',joint, ...
    'common_row_order','I_2048 negative Nyquist retained');
  angular_action=angular_jump_metrics{2};
  actions_finite=all(cellfun(@(x) x.finite,image_public))&& ...
    all(cellfun(@(x) x.finite,angular_public));
  out=struct('image_public',[image_public{:}], ...
    'angular_public',[angular_public{:}],'signatures',signatures, ...
    'finest_factors',finest,'wronskian',wronskian, ...
    'repaired_value_metric',repair,'actual_T_action',actual_T, ...
    'finite_image_bloch',finite_bloch,'angular_action_metric',angular_action, ...
    'normal_decomposition_records',{[angular_public{:}]}, ...
    'raw_value_jump_norm',norm(raw_delta,'fro'), ...
    'actions_finite',actions_finite);
  clear image_value image_dr image_T_tau image_dS_zeta;
  clear final_vp final_dp final_tp final_sp vi0 dvi0 tin0 dsin0 dvw;
  clear final_factors final_level raw_delta pending_factor pending_T;
  peak=max(peak,LOCAL_workspace_mib());
end

function out=LOCAL_density_coefficients(z)
  N=256; eta=z.eta_unit_256;
  out=struct('orders',(-N/2:N/2-1).', ...
    'tau',fftshift(fft(eta(1:N,:),[],1),1)/N, ...
    'zeta',fftshift(fft(eta(N+1:end,:),[],1),1)/N, ...
    'xi_left',z.xi_left_unit_512,'xi_right',z.xi_right_unit_512);
  if any(~isfinite([out.tau(:);out.zeta(:)]))
    error('i32f:DensityTransform','The fixed density FFT is nonfinite.');
  end
end

function out=LOCAL_circle_level(vp,vm,dp,dm,tp,tm,sp,sm,wall_dr,R,N,Nfinal,tol)
  delta=vp-vm; jump=dm-dp; deltaT=tp-tm; dSzeta=sp-sm;
  decomposition=-deltaT+dSzeta-wall_dr;
  decomposition_metric=LOCAL_metric_record(jump,decomposition,tol);
  delta_coeff=LOCAL_pad_orders(LOCAL_circle_coeff(delta,R),N,Nfinal);
  jump_coeff=LOCAL_pad_orders(LOCAL_circle_coeff(jump,R),N,Nfinal);
  deltaT_coeff=LOCAL_pad_orders(LOCAL_circle_coeff(deltaT,R),N,Nfinal);
  dSzeta_coeff=LOCAL_pad_orders(LOCAL_circle_coeff(dSzeta,R),N,Nfinal);
  wall_coeff=LOCAL_pad_orders(LOCAL_circle_coeff(wall_dr,R),N,Nfinal);
  out=struct('label','','J',0,'target_nodes',N, ...
    'delta_coeff',delta_coeff,'jump_coeff',jump_coeff, ...
    'actual_deltaT_coeff',deltaT_coeff, ...
    'dS_difference_zeta_norm',norm(dSzeta_coeff,'fro'), ...
    'wall_normal_norm',norm(wall_coeff,'fro'), ...
    'normal_decomposition_metric',decomposition_metric, ...
    'finite',all(isfinite([delta_coeff(:);jump_coeff(:);deltaT_coeff(:); ...
      dSzeta_coeff(:);wall_coeff(:);decomposition_metric.ratio])));
end

function out=LOCAL_restrict_samples(delta,jump,deltaT,R,N,Nfinal,tol,decomposition)
  stride=size(delta,1)/N;
  if stride~=round(stride)
    error('i32f:CircleRestriction','The circle target grids are not nested.');
  end
  index=1:round(stride):size(delta,1);
  dc=LOCAL_pad_orders(LOCAL_circle_coeff(delta(index,:),R),N,Nfinal);
  jc=LOCAL_pad_orders(LOCAL_circle_coeff(jump(index,:),R),N,Nfinal);
  tc=LOCAL_pad_orders(LOCAL_circle_coeff(deltaT(index,:),R),N,Nfinal);
  dm=LOCAL_metric_record(jump(index,:),decomposition(index,:),tol);
  out=struct('label','joint-circle','J',192,'target_nodes',N, ...
    'delta_coeff',dc,'jump_coeff',jc,'actual_deltaT_coeff',tc, ...
    'dS_difference_zeta_norm',NaN,'wall_normal_norm',NaN, ...
    'normal_decomposition_metric',dm, ...
    'finite',all(isfinite([dc(:);jc(:);tc(:);dm.ratio])));
end

function out=LOCAL_level_summary(level)
  out=struct('label',level.label,'J',level.J, ...
    'target_nodes',level.target_nodes, ...
    'order_min',-level.target_nodes/2, ...
    'order_max',level.target_nodes/2-1, ...
    'delta_norm',norm(level.delta_coeff,'fro'), ...
    'jump_norm',norm(level.jump_coeff,'fro'), ...
    'actual_deltaT_norm',norm(level.actual_deltaT_coeff,'fro'), ...
    'dS_difference_zeta_norm',level.dS_difference_zeta_norm, ...
    'wall_normal_norm',level.wall_normal_norm, ...
    'normal_decomposition_metric',level.normal_decomposition_metric, ...
    'finite',level.finite);
end

function out=LOCAL_circle_factors(level,z,circle_weight,collar_weight)
  LOCAL_circle_weight_gate(circle_weight,collar_weight,size(level.jump_coeff,1));
  Jm=level.jump_coeff*z.Gminus; Jp=level.jump_coeff*z.Gplus;
  Dm=level.delta_coeff*z.Gminus; Dp=level.delta_coeff*z.Gplus;
  Hcm=LOCAL_weight_rows(Jm,1./sqrt(circle_weight));
  Hcp=LOCAL_weight_rows(Jp,1./sqrt(circle_weight));
  Hvm=LOCAL_weight_rows(Dm,sqrt(collar_weight));
  Hvp=LOCAL_weight_rows(Dp,sqrt(collar_weight));
  out=struct('circle_minus',Hcm,'circle_plus',Hcp, ...
    'volume_minus',Hvm,'volume_plus',Hvp, ...
    'jump_minus',Jm,'jump_plus',Jp,'delta_minus',Dm,'delta_plus',Dp, ...
    'circle',struct('minus',Hcm,'plus',Hcp,'center',zeros(0,1)), ...
    'volume',struct('minus',Hvm,'plus',Hvp,'center',zeros(0,1)));
end

function LOCAL_circle_weight_gate(circle,collar,N)
  if numel(circle)~=N||numel(collar)~=N|| ...
      any(~isfinite([circle;collar]))||any(circle<=0)||any(collar<0)
    error('i32f:ComponentWeight','A required circle component weight is invalid.');
  end
end

function value=LOCAL_weight_rows(A,w)
  if size(A,1)~=numel(w)
    error('i32f:FactorDimensions','A factor weight dimension is wrong.');
  end
  value=bsxfun(@times,A,w);
end

function [ve,dve,vi,dvi,record,tout,tin,dsout,dsin]= ...
    LOCAL_free_self(z,density,theta,ko,ki)
  ell=density.orders; E=exp(1i*theta*ell.');
  [So,Dpo,~,dSpo,~,To,wo]=LOCAL_free_factors(ell,ko,z.R);
  [Si,~,Dmi,~,dSmi,Ti,wi]=LOCAL_free_factors(ell,ki,z.R);
  ve=E*(bsxfun(@times,Dpo,density.tau)- ...
    bsxfun(@times,So,density.zeta));
  tout=E*bsxfun(@times,To,density.tau);
  dsout=E*bsxfun(@times,dSpo,density.zeta);
  dve=tout-dsout;
  vi=E*(bsxfun(@times,Dmi,density.tau)- ...
    bsxfun(@times,Si,density.zeta));
  tin=E*bsxfun(@times,Ti,density.tau);
  dsin=E*bsxfun(@times,dSmi,density.zeta);
  dvi=tin-dsin;
  record=struct('exterior',wo,'interior',wi, ...
    'minus_S_exterior_minus_interior_jump_is_plus_zeta',true);
end

function [S,Dplus,Dminus,dSplus,dSminus,T,record]= ...
    LOCAL_free_factors(ell,k,R)
  zr=k*R; [lj,pj,ljp,pjp]=LOCAL_bessel_log_j(ell,zr);
  [lh,ph,lhp,php]=LOCAL_hankel_log_orders(ell,zr);
  S=1i*pi*R/2*LOCAL_log_product(lj,pj,lh,ph);
  Dplus=1i*pi*k*R/2*LOCAL_log_product(ljp,pjp,lh,ph);
  Dminus=1i*pi*k*R/2*LOCAL_log_product(lj,pj,lhp,php);
  dSplus=Dminus; dSminus=Dplus;
  T=1i*pi*k^2*R/2*LOCAL_log_product(ljp,pjp,lhp,php);
  jumpD=Dplus-Dminus; jumpS=dSplus-dSminus;
  scaleD=max([realmin*ones(size(ell)),abs(Dplus),abs(Dminus)],[],2);
  record=struct('orders',ell,'D_jump_defect', ...
    max(abs(jumpD-1)./max(realmin,scaleD)), ...
    'dS_jump_defect',max(abs(jumpS+1)./max(realmin,scaleD)), ...
    'finite',all(isfinite([S;Dplus;Dminus;dSplus;dSminus;T])), ...
    'scaled_log_products',true, ...
    'recurrence_oracle_attached_separately',true);
end

function [value,dr,Ttau,dSzeta]= ...
    LOCAL_one_image(z,density,theta,x,y,nx,ny,n)
  k=z.khat; R=z.R; ell=density.orders; center_y=n*z.d;
  dx=x; dy=y-center_y; rn=hypot(dx,dy); angle=atan2(dy,dx);
  erx=dx./rn; ery=dy./rn; etx=-ery; ety=erx;
  radial_dot=nx.*erx+ny.*ery; tangent_dot=nx.*etx+ny.*ety;
  phase=exp(1i*z.beta*n*z.d); N=numel(theta); K=size(density.tau,2);
  value=zeros(N,K); dr=value; Ttau=value; dSzeta=value;
  [lh,ph,lhp,php]=LOCAL_hankel_log_table(ell,k*rn);
  for first=1:16:numel(ell)
    ids=first:min(first+15,numel(ell)); l=ell(ids).';
    A=exp(1i*angle*l);
    [lj,pj,ljp,pjp]=LOCAL_bessel_log_j(l,k*R);
    JH=exp(bsxfun(@plus,lh(:,ids),lj)+ ...
      1i*bsxfun(@plus,ph(:,ids),pj));
    JpH=exp(bsxfun(@plus,lh(:,ids),ljp)+ ...
      1i*bsxfun(@plus,ph(:,ids),pjp));
    JHp=exp(bsxfun(@plus,lhp(:,ids),lj)+ ...
      1i*bsxfun(@plus,php(:,ids),pj));
    JpHp=exp(bsxfun(@plus,lhp(:,ids),ljp)+ ...
      1i*bsxfun(@plus,php(:,ids),pjp));
    Sop=1i*pi*R/2*(JH.*A); Dop=1i*pi*R*k/2*(JpH.*A);
    radialS=1i*pi*R/2*bsxfun(@times,JHp.*A,k*radial_dot);
    radialD=1i*pi*R*k/2*bsxfun(@times,JpHp.*A,k*radial_dot);
    tangentS=bsxfun(@times,Sop,1i*tangent_dot./rn).*l;
    tangentD=bsxfun(@times,Dop,1i*tangent_dot./rn).*l;
    dSop=radialS+tangentS; dDop=radialD+tangentD;
    if any(~isfinite([Sop(:);Dop(:);dSop(:);dDop(:)]))
      error('i32f:CircleHarmonicAction', ...
        'A required scaled harmonic product is nonfinite.');
    end
    value=value+phase*(Dop*density.tau(ids,:)-Sop*density.zeta(ids,:));
    dr=dr+phase*(dDop*density.tau(ids,:)-dSop*density.zeta(ids,:));
    Ttau=Ttau+phase*(dDop*density.tau(ids,:));
    dSzeta=dSzeta+phase*(dSop*density.zeta(ids,:));
  end
end

function [lh,ph,lhp,php]=LOCAL_hankel_log_table(orders,z)
  N=numel(z); K=numel(orders); lh=zeros(N,K); ph=lh; lhp=lh; php=lh;
  for j=1:N
    [lh(j,:),ph(j,:),lhp(j,:),php(j,:)]= ...
      LOCAL_hankel_log_orders(orders.',z(j));
  end
end

function [value,dr]=LOCAL_wall_to_circle(z,density,theta,x,y,nx,ny)
  orders=(-256:255).'; beta=z.beta+2*pi*orders/z.d;
  gamma=LOCAL_outgoing(z.khat,beta); psi=exp(1i*y*beta.')/sqrt(z.d);
  left_phase=exp(1i*(x-z.X_L)*gamma.');
  right_phase=exp(1i*(z.X_R-x)*gamma.');
  s0=1i./(2*gamma);
  SL=bsxfun(@times,psi.*left_phase,s0.');
  SR=bsxfun(@times,psi.*right_phase,s0.');
  dSL=SL.*(nx*(1i*gamma).'+ny*(1i*beta).');
  dSR=SR.*(nx*(-1i*gamma).'+ny*(1i*beta).');
  value=SL*density.xi_left+SR*density.xi_right;
  dr=dSL*density.xi_left+dSR*density.xi_right;
  if any(~isfinite([value(:);dr(:)]))
    error('i32f:WallCircleAction','The wall-to-circle action is nonfinite.');
  end
end

function [logJ,phaseJ,logJp,phaseJp]=LOCAL_bessel_log_j(orders,z)
  nmax=max(abs(orders))+1; logs=zeros(nmax+1,1); phases=zeros(nmax+1,1);
  for n=0:nmax
    term=1; series=1;
    for q=1:200
      term=term*(-z^2/4)/(q*(n+q)); updated=series+term;
      if abs(term)<=eps*max(realmin,abs(updated)), series=updated; break; end
      series=updated;
    end
    logs(n+1)=n*log(abs(z/2))-gammaln(n+1)+log(abs(series));
    phases(n+1)=n*angle(z)+angle(series);
  end
  logJ=zeros(size(orders)); phaseJ=logJ; logJp=logJ; phaseJp=logJ;
  for j=1:numel(orders)
    n=abs(orders(j)); parity=pi*mod(n,2)*(orders(j)<0);
    logJ(j)=logs(n+1); phaseJ(j)=phases(n+1)+parity;
    if n==0
      logJp(j)=logs(2); phaseJp(j)=phases(2)+pi;
    else
      [logJp(j),phaseJp(j)]=LOCAL_log_difference( ...
        logs(n),phases(n),logs(n+2),phases(n+2),log(2));
      phaseJp(j)=phaseJp(j)+parity;
    end
  end
end

function [logH,phaseH,logHp,phaseHp]=LOCAL_hankel_log_orders(orders,z)
  nmax=max(abs(orders))+1; [logs,phases]=LOCAL_hankel_sequence(z,nmax);
  logH=zeros(size(orders)); phaseH=logH; logHp=logH; phaseHp=logH;
  for j=1:numel(orders)
    n=abs(orders(j)); parity=pi*mod(n,2)*(orders(j)<0);
    logH(j)=logs(n+1); phaseH(j)=phases(n+1)+parity;
    if n==0
      logHp(j)=logs(2); phaseHp(j)=phases(2)+pi;
    else
      [logHp(j),phaseHp(j)]=LOCAL_log_difference( ...
        logs(n),phases(n),logs(n+2),phases(n+2),log(2));
      phaseHp(j)=phaseHp(j)+parity;
    end
  end
end

function [logs,phases]=LOCAL_hankel_sequence(z,nmax)
  pair=[besselh(0,1,z),besselh(1,1,z)]; logscale=0;
  logs=zeros(nmax+1,1); phases=logs;
  logs(1)=log(abs(pair(1))); phases(1)=angle(pair(1));
  if nmax==0, return; end
  logs(2)=log(abs(pair(2))); phases(2)=angle(pair(2));
  for n=1:nmax-1
    next=2*n/z*pair(2)-pair(1); magnitude=max(abs([pair,next]));
    if magnitude>1e100||magnitude<1e-100
      pair=pair/magnitude; next=next/magnitude; logscale=logscale+log(magnitude);
    end
    pair=[pair(2),next]; logs(n+2)=log(abs(next))+logscale;
    phases(n+2)=angle(next);
  end
end

function [logvalue,phase]=LOCAL_log_difference(la,pa,lb,pb,subtract_log)
  scale=max(la,lb); value=exp(la-scale+1i*pa)-exp(lb-scale+1i*pb);
  logvalue=scale+log(abs(value))-subtract_log; phase=angle(value);
end

function value=LOCAL_log_product(la,pa,lb,pb)
  value=exp(la+lb+1i*(pa+pb));
end

function gamma=LOCAL_outgoing(k,beta)
  gamma=sqrt(complex(k^2-beta.^2));
  flip=imag(gamma)<0|(imag(gamma)==0&real(gamma)<0);
  gamma(flip)=-gamma(flip);
  if any(~isfinite(gamma))||any(gamma==0)
    error('i32f:BranchUnavailable','A required outgoing branch is unavailable.');
  end
end

%% ==================== Frozen action qualification ====================
% The actual fixed-density Delta-T and finite-image Bloch gates are unchanged.

function out=LOCAL_actual_T_qualification(c,image_metric,image_scale, ...
    angular_metric,angular_scale,final_numel)
  labels={'64_to_128','128_to_256','48_to_96', ...
    '96_to_192','192_to_256'};
  for j=1:5
    image_metric(j).label=labels{j};
  end
  omega_image=100*final_numel*eps*image_scale;
  image_metric(1).threshold=Inf;
  image_metric(2).threshold=max( ...
    c.image_ratio_max*image_metric(1).numerator,omega_image);
  image_metric(3).threshold=Inf;
  image_metric(4).threshold=max( ...
    c.image_ratio_max*image_metric(3).numerator,omega_image);
  image_metric(5).threshold=Inf;
  for j=1:5
    image_metric(j).pass=isfinite(image_metric(j).numerator)&& ...
      image_metric(j).numerator<=image_metric(j).threshold;
  end
  dyadic_near=image_metric(1).numerator<=omega_image&& ...
    image_metric(2).numerator<=omega_image;
  staggered_near=image_metric(3).numerator<=omega_image&& ...
    image_metric(4).numerator<=omega_image;
  dyadic=dyadic_near||image_metric(2).numerator<= ...
    max(c.image_ratio_max*image_metric(1).numerator,omega_image);
  staggered=staggered_near||image_metric(4).numerator<= ...
    max(c.image_ratio_max*image_metric(3).numerator,omega_image);
  image_available=all(isfinite([[image_metric.numerator],omega_image]));

  angular_metric(1).label='512_to_1024';
  angular_metric(2).label='1024_to_2048';
  omega_angular=100*final_numel*eps*angular_scale;
  angular_metric(1).threshold=Inf;
  angular_metric(2).threshold=max( ...
    c.spectral_ratio_max*angular_metric(1).numerator,omega_angular);
  for j=1:2
    angular_metric(j).pass=isfinite(angular_metric(j).numerator)&& ...
      angular_metric(j).numerator<=angular_metric(j).threshold;
  end
  angular_near=all([angular_metric.numerator]<=omega_angular);
  angular_contract=angular_metric(2).numerator<= ...
    max(c.spectral_ratio_max*angular_metric(1).numerator,omega_angular);
  angular_available=all(isfinite([[angular_metric.numerator],omega_angular]));
  ratio_values=[image_metric(2).numerator/ ...
    max(realmin,image_metric(1).numerator), ...
    image_metric(4).numerator/max(realmin,image_metric(3).numerator), ...
    angular_metric(2).numerator/max(realmin,angular_metric(1).numerator)];
  if all(isfinite(ratio_values)), maximum_ratio=max(ratio_values);
  else, maximum_ratio=Inf; end
  available=image_available&&angular_available;
  qualified=available&&dyadic&&staggered&&(angular_near||angular_contract);
  out=struct('available',available,'qualified',qualified, ...
    'orientation','exterior minus interior global +r', ...
    'definition','d_r(D_QP tau)-d_r(D_i tau)', ...
    'image_metrics',image_metric,'angular_metrics',angular_metric, ...
    'image_omega',omega_image,'angular_omega',omega_angular, ...
    'image_ratio_threshold',c.image_ratio_max, ...
    'angular_ratio_threshold',c.spectral_ratio_max, ...
    'dyadic_pass',dyadic,'staggered_pass',staggered, ...
    'cross_finite',isfinite(image_metric(5).numerator), ...
    'angular_pass',angular_near||angular_contract, ...
    'maximum_contraction_ratio',maximum_ratio, ...
    'all_level_maps_stored_separately',false);
end

function [out,calls]=LOCAL_finite_image_bloch(c,z,density,calls)
  try
    [out,calls]=LOCAL_finite_image_bloch_core(c,z,density,calls);
  catch ME
    if ~any(strcmp(ME.identifier, ...
        {'i32f:CircleHarmonicAction','i32f:WallCircleAction'}))
      rethrow(ME);
    end
    out=struct('available',false,'qualified',false,'levels',[], ...
      'safe_target_x',.30,'paired_y',[-z.d/2,z.d/2], ...
      'physical_Bloch_phase',exp(1i*z.beta*z.d), ...
      'derivative','global +y at both paired targets', ...
      'same_fixed_eta_and_xi_consumed',true, ...
      'finite_image_J',c.image_levels,'threshold',c.identity_tol, ...
      'angular_target_grid_dependency', ...
        'none: paired point action consumes fixed eta Fourier coefficients', ...
      'maximum_final_ratio',Inf,'fail_open',true, ...
      'exact_continuous_QP_Bloch_is_structural',true, ...
      'finite_image_action_enclosed',false,'message',ME.message);
  end
end

function [out,calls]=LOCAL_finite_image_bloch_core(c,z,density,calls)
  checkpoints=c.image_levels; x=.30; y=[-z.d/2,z.d/2];
  phase=exp(1i*z.beta*z.d);
  template=struct('J',0,'bottom_value',[],'top_value',[], ...
    'bottom_global_y_derivative',[],'top_global_y_derivative',[], ...
    'value_metric',LOCAL_metric_record(0,0,NaN), ...
    'flux_metric',LOCAL_metric_record(0,0,NaN));
  levels=repmat(template,1,numel(checkpoints));
  value=zeros(2,size(density.tau,2)); derivative=value;
  for side=1:2
    [wall_value,wall_derivative]=LOCAL_wall_to_circle( ...
      z,density,0,x,y(side),0,1);
    [self_value,self_derivative]=LOCAL_one_image( ...
      z,density,0,x,y(side),0,1,0);
    value(side,:)=wall_value+self_value;
    derivative(side,:)=wall_derivative+self_derivative;
  end
  hit=1;
  for n=1:max(checkpoints)
    for signn=[-1,1]
      for side=1:2
        [dv,ddr]=LOCAL_one_image(z,density,0,x,y(side),0,1,signn*n);
        value(side,:)=value(side,:)+dv;
        derivative(side,:)=derivative(side,:)+ddr;
        calls.finite_bloch_image_updates=calls.finite_bloch_image_updates+1;
      end
    end
    if hit<=numel(checkpoints)&&n==checkpoints(hit)
      vm=LOCAL_metric_record(value(2,:),phase*value(1,:),c.identity_tol);
      fm=LOCAL_metric_record( ...
        derivative(2,:),phase*derivative(1,:),c.identity_tol);
      levels(hit)=struct('J',n,'bottom_value',value(1,:), ...
        'top_value',value(2,:), ...
        'bottom_global_y_derivative',derivative(1,:), ...
        'top_global_y_derivative',derivative(2,:), ...
        'value_metric',vm,'flux_metric',fm);
      hit=hit+1;
    end
  end
  value_ratio=arrayfun(@(item) item.value_metric.ratio,levels);
  flux_ratio=arrayfun(@(item) item.flux_metric.ratio,levels);
  available=all(isfinite([value_ratio,flux_ratio]));
  if available, final=max(value_ratio(end),flux_ratio(end)); else, final=Inf; end
  qualified=available&&final<=c.identity_tol;
  out=struct('available',available,'qualified',qualified,'levels',levels, ...
    'safe_target_x',x,'paired_y',y,'physical_Bloch_phase',phase, ...
    'derivative','global +y at both paired targets', ...
    'same_fixed_eta_and_xi_consumed',true, ...
    'finite_image_J',checkpoints,'threshold',c.identity_tol, ...
    'angular_target_grid_dependency', ...
      'none: paired point action consumes fixed eta Fourier coefficients', ...
    'maximum_final_ratio',final,'fail_open',true, ...
    'exact_continuous_QP_Bloch_is_structural',true, ...
    'finite_image_action_enclosed',false);
end

%% ==================== Compact endpoint and pair signatures ====================
% Direct action blocks are transient and die inside these helpers.

function out=LOCAL_endpoint_signature(c,label,component,Hm,Hp,z,center,N)
  [minus,block_m]=LOCAL_side_endpoint(c,Hm,z.Pminus,z.cminus,N);
  [plus,block_p]=LOCAL_side_endpoint(c,Hp,z.Pplus,z.cplus,N);
  center_squared=norm(center)^2;
  long=norm([center(:);block_m;block_p]);
  reconstructed=sqrt(center_squared+sum(minus.direct_squared_terms(1:N))+ ...
    sum(plus.direct_squared_terms(1:N)));
  nops=4*(numel(center)+numel(block_m)+numel(block_p))+16;
  parity=LOCAL_parity_record(label,'producer_endpoint_direct', ...
    long,reconstructed,nops);
  clear block_m block_p long reconstructed;
  out=struct('endpoint_id',label,'component',component, ...
    'row_order','canonical circle I_2048 row blocks', ...
    'Nminus',N,'Nplus',N,'center_squared',center_squared, ...
    'minus',minus,'plus',plus, ...
    'finite',minus.finite&&plus.finite&&isfinite(center_squared), ...
    'signature_parity',parity);
end

function [out,long_block]=LOCAL_side_endpoint(c,H,P,c0,N)
  Nmax=max(c.full_p_levels); terms=zeros(1,Nmax); state=c0;
  rows=size(H,1); long_block=zeros(rows*Nmax,1,'like',H*c0);
  for n=1:Nmax
    action=H*state; terms(n)=norm(action)^2;
    if n<=N, long_block((n-1)*rows+(1:rows))=action; end
    state=P*state;
  end
  W=H'*H;
  out=struct('W',W,'direct_squared_terms',terms, ...
    'tail_input_audit',struct('rows',rows,'state_dimension',size(P,1)), ...
    'finite',all(isfinite([W(:);terms(:)])));
end

function out=LOCAL_pair_signature(c,a,b,z,Na,Nb)
  [dm,block_m]=LOCAL_side_pair(c,a.minus,b.minus,z.Pminus,z.cminus,Na,Nb);
  [dp,block_p]=LOCAL_side_pair(c,a.plus,b.plus,z.Pplus,z.cplus,Na,Nb);
  dc=norm(b.center-a.center)^2;
  long=norm([b.center(:)-a.center(:);block_m;block_p]);
  reconstructed=sqrt(dc+sum(dm)+sum(dp));
  nops=4*(numel(a.center)+numel(block_m)+numel(block_p))+24;
  label=[a.endpoint_id,'->',b.endpoint_id];
  parity=LOCAL_parity_record(label,'producer_pair_direct', ...
    long,reconstructed,nops);
  out=struct('left_endpoint_id',a.endpoint_id, ...
    'right_endpoint_id',b.endpoint_id, ...
    'center_difference_squared',dc, ...
    'minus_direct_difference_squared_terms',dm, ...
    'plus_direct_difference_squared_terms',dp, ...
    'left_norm_scale',LOCAL_direct_scale(a,z,Na), ...
    'right_norm_scale',LOCAL_direct_scale(b,z,Nb), ...
    'finite',all(isfinite([dc,dm,dp])), ...
    'signature_parity',parity);
  clear block_m block_p long reconstructed;
end

function [terms,long_block]=LOCAL_side_pair(c,Ha,Hb,P,c0,Na,Nb)
  Nmax=max(c.full_p_levels); rows=size(Ha,1);
  if size(Hb,1)~=rows
    error('i32f:SignatureRows','A circle pair row order is inconsistent.');
  end
  terms=zeros(1,Nmax); long_block=zeros(rows*Nmax,1,'like',Ha*c0); state=c0;
  for n=1:Nmax
    da=zeros(rows,1,'like',Ha*c0); db=da;
    if n<=Na, da=Ha*state; end
    if n<=Nb, db=Hb*state; end
    difference=db-da; terms(n)=norm(difference)^2;
    long_block((n-1)*rows+(1:rows))=difference; state=P*state;
  end
end

function value=LOCAL_direct_scale(factors,z,N)
  value=norm(factors.center)^2; state=z.cminus;
  for n=1:N, value=value+norm(factors.minus*state)^2; state=z.Pminus*state; end
  state=z.cplus;
  for n=1:N, value=value+norm(factors.plus*state)^2; state=z.Pplus*state; end
  value=sqrt(value);
end

function out=LOCAL_parity_record(label,class_name,long,sig,nops)
  scale=max([realmin,abs(long),abs(sig)]); allowance=100*nops*eps*scale;
  numerator=abs(long-sig);
  out=struct('label',label,'coverage_class',class_name,'actual',true, ...
    'representative',false,'long_value',long,'signature_value',sig, ...
    'n_op',nops,'scale',scale,'allowance',allowance, ...
    'numerator',numerator,'ratio',numerator/max(realmin,allowance), ...
    'pass',isfinite(numerator)&&numerator<=allowance);
end

function out=LOCAL_collect_parity(signatures)
  records=struct([]); names={'image','image_pairs','angular','angular_pairs'};
  for a=1:numel(names)
    name=names{a};
    if ~isstruct(signatures)||~isfield(signatures,name), continue; end
    family=signatures.(name);
    for j=1:numel(family)
      item=family{j};
      records=LOCAL_append(records,item.circle.signature_parity); %#ok<AGROW>
      records=LOCAL_append(records,item.volume_circle.signature_parity); %#ok<AGROW>
    end
  end
  if isstruct(signatures)&&isfield(signatures,'joint')&& ...
      isfield(signatures.joint,'circle')
    records=LOCAL_append(records,signatures.joint.circle.signature_parity); %#ok<AGROW>
    records=LOCAL_append(records, ...
      signatures.joint.volume_circle.signature_parity); %#ok<AGROW>
    records=LOCAL_append(records, ...
      signatures.joint.pair_to_final.circle.signature_parity); %#ok<AGROW>
    records=LOCAL_append(records, ...
      signatures.joint.pair_to_final.volume_circle.signature_parity); %#ok<AGROW>
  end
  coverage=LOCAL_validate_parity_coverage(records,LOCAL_expected_parity());
  if isempty(records)
    out=struct('records',records,'required_count',coverage.required_count, ...
      'pass',false,'total_operations',0,'coverage',coverage); return;
  end
  out=struct('records',records,'required_count',coverage.required_count, ...
    'pass',all([records.pass])&&coverage.pass, ...
    'total_operations',sum([records.n_op]),'coverage',coverage);
end

function expected=LOCAL_expected_parity()
  rows={ ...
    'image-J-32-circle','producer_endpoint_direct',true,false; ...
    'image-J-32-volume-circle','producer_endpoint_direct',true,false; ...
    'image-J-48-circle','producer_endpoint_direct',true,false; ...
    'image-J-48-volume-circle','producer_endpoint_direct',true,false; ...
    'image-J-64-circle','producer_endpoint_direct',true,false; ...
    'image-J-64-volume-circle','producer_endpoint_direct',true,false; ...
    'image-J-96-circle','producer_endpoint_direct',true,false; ...
    'image-J-96-volume-circle','producer_endpoint_direct',true,false; ...
    'image-J-128-circle','producer_endpoint_direct',true,false; ...
    'image-J-128-volume-circle','producer_endpoint_direct',true,false; ...
    'image-J-192-circle','producer_endpoint_direct',true,false; ...
    'image-J-192-volume-circle','producer_endpoint_direct',true,false; ...
    'image-J-256-circle','producer_endpoint_direct',true,false; ...
    'image-J-256-volume-circle','producer_endpoint_direct',true,false; ...
    'image-J-64-circle->image-J-128-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-64-volume-circle->image-J-128-volume-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-128-circle->image-J-256-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-128-volume-circle->image-J-256-volume-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-48-circle->image-J-96-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-48-volume-circle->image-J-96-volume-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-96-circle->image-J-192-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-96-volume-circle->image-J-192-volume-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-192-circle->image-J-256-circle', ...
      'producer_pair_direct',true,false; ...
    'image-J-192-volume-circle->image-J-256-volume-circle', ...
      'producer_pair_direct',true,false; ...
    'angular-N-512-circle','producer_endpoint_direct',true,false; ...
    'angular-N-512-volume-circle','producer_endpoint_direct',true,false; ...
    'angular-N-1024-circle','producer_endpoint_direct',true,false; ...
    'angular-N-1024-volume-circle','producer_endpoint_direct',true,false; ...
    'angular-N-2048-circle','producer_endpoint_direct',true,false; ...
    'angular-N-2048-volume-circle','producer_endpoint_direct',true,false; ...
    'angular-N-512-circle->angular-N-1024-circle', ...
      'producer_pair_direct',true,false; ...
    'angular-N-512-volume-circle->angular-N-1024-volume-circle', ...
      'producer_pair_direct',true,false; ...
    'angular-N-1024-circle->angular-N-2048-circle', ...
      'producer_pair_direct',true,false; ...
    'angular-N-1024-volume-circle->angular-N-2048-volume-circle', ...
      'producer_pair_direct',true,false; ...
    'joint-circle-circle','producer_endpoint_direct',true,false; ...
    'joint-circle-volume-circle','producer_endpoint_direct',true,false; ...
    'joint-circle-circle->angular-N-2048-circle', ...
      'producer_pair_direct',true,false; ...
    'joint-circle-volume-circle->angular-N-2048-volume-circle', ...
      'producer_pair_direct',true,false};
  expected=cell2struct(rows, ...
    {'label','coverage_class','actual','representative'},2);
end

function out=LOCAL_validate_parity_coverage(records,expected)
  observed=false(numel(expected),1); duplicates=false(numel(expected),1);
  expected_record=false(1,numel(records));
  for j=1:numel(expected)
    hit=find(strcmp({records.label},expected(j).label)& ...
      strcmp({records.coverage_class},expected(j).coverage_class)& ...
      [records.actual]==expected(j).actual& ...
      [records.representative]==expected(j).representative);
    observed(j)=numel(hit)==1; duplicates(j)=numel(hit)>1;
    expected_record(hit)=true;
  end
  out=struct('expected',expected,'required_count',numel(expected), ...
    'observed_exactly_once',observed,'duplicate_expected',duplicates, ...
    'missing_count',sum(~observed),'duplicate_count',sum(duplicates), ...
    'unexpected_count',sum(~expected_record),'empty_records',isempty(records), ...
    'pass',~isempty(records)&&all(observed)&&~any(duplicates)&& ...
      all(expected_record)&&numel(records)==numel(expected));
end

function value=LOCAL_append(value,item)
  if isempty(value), value=item; else, value(end+1)=item; end
end

%% ==================== Independent analytic oracles ====================
% Production is compared to active Kress splits and project-signed Linton.

function out=LOCAL_oracles(c,z,~,action,calls)
  try
    free=LOCAL_free_oracle(z);
    calls.kress_oracle_calls=calls.kress_oracle_calls+1;
  catch ME
    if strcmp(ME.identifier,'i32f:ExactWood')|| ...
        strcmp(ME.identifier,'i32f:BranchUnavailable')
      rethrow(ME);
    end
    free=struct('available',false,'qualified',false,'message',ME.message, ...
      'maximum_relative_defect',Inf);
  end
  try
    linton=LOCAL_linton_oracle(c,z);
    calls.linton_oracle_calls=calls.linton_oracle_calls+1;
  catch ME
    if strcmp(ME.identifier,'i32f:ExactWood')|| ...
        strcmp(ME.identifier,'i32f:BranchUnavailable')
      rethrow(ME);
    end
    linton=struct('available',false,'qualified',false,'message',ME.message, ...
      'maximum_relative_defect',Inf);
  end
  try
    recurrence=LOCAL_high_order_recurrence(z);
  catch ME
    recurrence=struct('available',false,'qualified',false, ...
      'message',ME.message,'maximum_relative_defect',Inf);
  end
  record=struct('free_singular',free,'linton_off_axis',linton, ...
    'high_order_recurrence',recurrence,'circle_1024_to_2048',action, ...
    'production_uses_oracle_matrix',false,'independent_reference',false);
  out=struct('available',free.available&&linton.available&&recurrence.available, ...
    'qualified',free.qualified&&linton.qualified&&recurrence.qualified, ...
    'record',record,'call_counters',calls);
end

function out=LOCAL_high_order_recurrence(z)
  orders=(0:128).'; kout=z.khat; kin=sqrt(z.rho_disk)*z.khat;
  boundary=[LOCAL_one_recurrence(kout*z.R,true), ...
    LOCAL_one_recurrence(kin*z.R,true)];
  radii=[z.d-z.R,z.d+z.R,128*z.d-z.R,256*z.d+z.R];
  image=repmat(LOCAL_one_recurrence(kout*radii(1),false),1,numel(radii));
  for j=1:numel(radii)
    image(j)=LOCAL_one_recurrence(kout*radii(j),false);
  end
  values=[boundary.maximum_relative_defect,image.maximum_relative_defect];
  out=struct('available',all([boundary.available])&&all([image.available])&& ...
      all(isfinite(values)),'qualified',all(isfinite(values))&&max(values)<=1e-8, ...
    'orders',orders,'boundary',boundary,'image_radii',radii, ...
    'image',image,'maximum_relative_defect',max(values), ...
    'scaled_log_coordinate',true,'clipping_used',false);
end

function out=LOCAL_one_recurrence(z,with_J)
  orders=(0:129).';
  [lh,ph,lhp,php]=LOCAL_hankel_log_orders(orders,z);
  hrec=LOCAL_three_term_defect(lh,ph,z);
  hder=LOCAL_derivative_defect(lh,ph,lhp,php);
  defects=[hrec,hder]; wronskian=NaN; jrec=NaN; jder=NaN;
  if with_J
    [lj,pj,ljp,pjp]=LOCAL_bessel_log_j(orders,z);
    jrec=LOCAL_three_term_defect(lj,pj,z);
    jder=LOCAL_derivative_defect(lj,pj,ljp,pjp);
    count=129; wdef=zeros(count,1);
    for n=1:count
      value=LOCAL_log_product(lj(n),pj(n),lhp(n),php(n))- ...
        LOCAL_log_product(ljp(n),pjp(n),lh(n),ph(n));
      reference=2i/(pi*z);
      wdef(n)=abs(value-reference)/max([realmin,abs(value),abs(reference)]);
    end
    wronskian=max(wdef); defects=[defects,jrec,jder,wronskian];
  end
  maximum=max(defects);
  out=struct('argument',z,'with_J',with_J,'H_recurrence',hrec, ...
    'H_derivative_identity',hder,'J_recurrence',jrec, ...
    'J_derivative_identity',jder,'Wronskian',wronskian, ...
    'maximum_relative_defect',maximum,'available',all(isfinite(defects)));
end

function defect=LOCAL_three_term_defect(logv,phasev,z)
  defects=zeros(128,1);
  for n=1:128
    ids=n:(n+2); scale=max(logv(ids));
    actual=exp(logv(ids(3))-scale+1i*phasev(ids(3)));
    reference=2*n/z*exp(logv(ids(2))-scale+1i*phasev(ids(2)))- ...
      exp(logv(ids(1))-scale+1i*phasev(ids(1)));
    defects(n)=abs(actual-reference)/max([realmin,abs(actual),abs(reference)]);
  end
  defect=max(defects);
end

function defect=LOCAL_derivative_defect(logv,phasev,logd,phased)
  defects=zeros(129,1);
  for n=0:128
    id=n+1; scale=max([logd(id),logv(max(1,id-1)),logv(id+1)]);
    actual=exp(logd(id)-scale+1i*phased(id));
    if n==0
      reference=-exp(logv(2)-scale+1i*phasev(2));
    else
      reference=.5*(exp(logv(id-1)-scale+1i*phasev(id-1))- ...
        exp(logv(id+1)-scale+1i*phasev(id+1)));
    end
    defects(id)=abs(actual-reference)/max([realmin,abs(actual),abs(reference)]);
  end
  defect=max(defects);
end

function out=LOCAL_free_oracle(z)
  modes=[0,1,-1,2,-2]; levels=[512,1024,2048];
  empty_metric=LOCAL_metric_record(0,0,NaN);
  template=struct('Ntheta',0,'modes',[],'columns',{{}}, ...
    'metric_records',repmat(empty_metric,0,0),'relative_defects',[], ...
    'D_jump',empty_metric,'dS_jump',empty_metric, ...
    'actual_T_out_minus_T_in',repmat(empty_metric,0,1), ...
    'streamed_active_Kress_circulant_row',false, ...
    'production_matrix_reused',false);
  records=repmat(template,1,numel(levels)); maximum=0; available=true;
  for n=1:numel(levels)
    N=levels(n); exterior=LOCAL_kress_circle_modes(z.khat,z.R,N,modes);
    interior=LOCAL_kress_circle_modes( ...
      sqrt(z.rho_disk)*z.khat,z.R,N,modes);
    [So,Dpo,Dmo,dSpo,dSmo,To]=LOCAL_free_factors(modes(:),z.khat,z.R);
    [Si,Dpi,Dmi,dSpi,dSmi,Ti]=LOCAL_free_factors( ...
      modes(:),sqrt(z.rho_disk)*z.khat,z.R);
    reference=[So,Dpo,Dmo,dSpo,dSmo,To, ...
      Si,Dpi,Dmi,dSpi,dSmi,Ti,To-Ti];
    numerical=[exterior.S,exterior.Dplus,exterior.Dminus, ...
      exterior.dSplus,exterior.dSminus,exterior.T, ...
      interior.S,interior.Dplus,interior.Dminus, ...
      interior.dSplus,interior.dSminus,interior.T, ...
      exterior.T-interior.T];
    metrics=repmat(LOCAL_metric_record(0,0,NaN),numel(modes),13);
    ratios=zeros(numel(modes),13);
    for j=1:numel(modes)
      for k=1:13
        metrics(j,k)=LOCAL_metric_record(numerical(j,k),reference(j,k),1e-8);
        ratios(j,k)=metrics(j,k).ratio;
      end
    end
    jumpD=LOCAL_metric_record([exterior.Dplus-exterior.Dminus; ...
      interior.Dplus-interior.Dminus],ones(10,1),1e-10);
    jumpS=LOCAL_metric_record([exterior.dSplus-exterior.dSminus; ...
      interior.dSplus-interior.dSminus],-ones(10,1),1e-10);
    records(n)=struct('Ntheta',N,'modes',modes(:), ...
      'columns',{{'S_outer','Dplus_outer','Dminus_outer', ...
        'dSplus_outer','dSminus_outer','T_outer','S_inner', ...
        'Dplus_inner','Dminus_inner','dSplus_inner','dSminus_inner', ...
        'T_inner','T_outer_minus_T_inner'}}, ...
      'metric_records',metrics,'relative_defects',ratios, ...
      'D_jump',jumpD,'dS_jump',jumpS, ...
      'actual_T_out_minus_T_in',metrics(:,13), ...
      'streamed_active_Kress_circulant_row',true, ...
      'production_matrix_reused',false);
    maximum=max([maximum,ratios(:).',jumpD.ratio,jumpS.ratio]);
    available=available&&all(isfinite(ratios),'all');
  end
  out=struct('available',available,'qualified',available&&maximum<=1e-8, ...
    'levels',records,'modes',modes,'maximum_relative_defect',maximum, ...
    'both_wavenumbers_all_one_sided_actions_checked',true, ...
    'minus_S_zeta_exterior_minus_interior_jump_is_plus_zeta',true, ...
    'normal_orientation','global +r; T is target/source mixed normal', ...
    'density_coordinate','[tau;zeta], zeta=-sigma');
end

function out=LOCAL_kress_circle_modes(k,R,N,modes)
  tau=(0:N-1)'*2*pi/N; difference=-tau; off=(1:N).'>1;
  dx=R*(1-cos(tau)); dy=-R*sin(tau); rho=hypot(dx,dy); rho(1)=1;
  logterm=zeros(N,1); logterm(off)=log(4*sin(difference(off)/2).^2);
  Rrow=zeros(N,1);
  for m=1:N/2-1, Rrow=Rrow+cos(m*difference)/m; end
  Rrow=-(4*pi/N)*(Rrow+cos((N/2)*difference)/N); h=2*pi/N;
  Mfull=1i/4*besselh(0,1,k*rho)*R;
  M1=-besselj(0,k*rho)*R/(4*pi); M2=zeros(N,1);
  M2(off)=Mfull(off)-M1(off).*logterm(off); M1(1)=-R/(4*pi);
  M2(1)=.5*(1i/2-0.57721566490153286060/pi- ...
    log((k^2/4)*R^2)/(2*pi))*R;
  ratio_source=R^2*(cos(tau)-1)./rho;
  Lfull=1i*k/4*ratio_source.*besselh(1,1,k*rho);
  L1=-k/(4*pi)*ratio_source.*besselj(1,k*rho); L2=zeros(N,1);
  L2(off)=Lfull(off)-L1(off).*logterm(off); L1(1)=0; L2(1)=-1/(4*pi);
  ratio_tangent=-R^2*sin(tau)./rho;
  Nfull=-1i*k/4*ratio_tangent.*besselh(1,1,k*rho);
  N1=k/(4*pi)*ratio_tangent.*besselj(1,k*rho); N2=zeros(N,1);
  cotterm=zeros(N,1); cotterm(off)=cot(difference(off)/2);
  N2(off)=Nfull(off)-cotterm(off)/(4*pi)-N1(off).*logterm(off);
  N1(1)=0; N2(1)=0;
  Srow=Rrow.*M1+h*M2; Krow=Rrow.*L1+h*L2;
  Arow=(Rrow.*(k^2*M1)+h*(k^2*M2)).*cos(tau);
  Brow=(Rrow.*N1+h*N2)/R;
  out=struct('S',zeros(numel(modes),1),'Dplus',zeros(numel(modes),1), ...
    'Dminus',zeros(numel(modes),1),'dSplus',zeros(numel(modes),1), ...
    'dSminus',zeros(numel(modes),1),'T',zeros(numel(modes),1));
  for j=1:numel(modes)
    phi=exp(1i*modes(j)*tau); S=Srow.'*phi; K=Krow.'*phi;
    T=Arow.'*phi+(Brow.'*phi)*(1i*modes(j));
    out.S(j)=S; out.Dplus(j)=.5+K; out.Dminus(j)=-.5+K;
    out.dSplus(j)=-.5+K; out.dSminus(j)=.5+K; out.T(j)=T;
  end
end

function out=LOCAL_linton_oracle(~,z)
  points=[.30,-.066;.20,-.066;.10,-.066;.263,.173;-.217,.287];
  tuples=[2,26,18,28;2,34,24,36;2,42,30,44];
  defects=zeros(size(points,1),size(tuples,1)-1,6);
  production=zeros(size(points,1),6); wood=zeros(size(tuples,1),1);
  branch=repmat(struct('orders',[],'beta_m',[],'t_m',[],'gamma_m',[], ...
    'classification',[],'outgoing_sign_pass',false,'axis_pass',false, ...
    'exact_Wood',true,'relative_Wood_margin',NaN,'available',false), ...
    size(tuples,1),1);
  for a=1:size(tuples,1)
    level=struct('a',tuples(a,1),'M1',tuples(a,2), ...
      'M2',tuples(a,3),'N',tuples(a,4));
    beta_m=z.beta+2*pi*(-level.M1:level.M1).'/z.d;
    t=z.khat^2-beta_m.^2; gamma=LOCAL_outgoing(z.khat,beta_m);
    wood(a)=min(abs(t)./(z.khat^2+beta_m.^2));
    exact_wood=any(t==0); prop=t>0; evan=t<0;
    sign_pass=all((~prop|real(gamma)>0)&(~evan|imag(gamma)>0));
    axis_pass=all(abs(real(gamma(evan)))<= ...
      100*eps*max(realmin,abs(gamma(evan))))&& ...
      all(abs(imag(gamma(prop)))<= ...
      100*eps*max(realmin,abs(gamma(prop))));
    class=zeros(size(t),'int8'); class(prop)=1; class(evan)=-1;
    branch(a)=struct('orders',(-level.M1:level.M1).', ...
      'beta_m',beta_m,'t_m',t,'gamma_m',gamma,'classification',class, ...
      'outgoing_sign_pass',sign_pass,'axis_pass',axis_pass, ...
      'exact_Wood',exact_wood,'relative_Wood_margin',wood(a), ...
      'available',~exact_wood&&sign_pass&&axis_pass&& ...
        all(isfinite([beta_m;t;gamma])));
    if exact_wood
      error('i32f:ExactWood','The Linton oracle encountered exact Wood.');
    end
    for p=1:size(points,1)
      dx=points(p,1); dy=points(p,2); sx=sign(dx);
      raw=LOCAL_linton_kernel(z.khat,z.beta,z.d,abs(dx),dy,level);
      values=-[raw.G,sx*raw.GX,raw.GY,raw.GXX,sx*raw.GXY,raw.GYY];
      if a>1
        prior_level=struct('a',tuples(a-1,1),'M1',tuples(a-1,2), ...
          'M2',tuples(a-1,3),'N',tuples(a-1,4));
        prior=LOCAL_linton_kernel(z.khat,z.beta,z.d, ...
          abs(dx),dy,prior_level);
        old=-[prior.G,sx*prior.GX,prior.GY,prior.GXX, ...
          sx*prior.GXY,prior.GYY];
        defects(p,a-1,:)=abs(values-old)./max([realmin*ones(1,6); ...
          abs(values);abs(old)],[],1);
      end
      if a==size(tuples,1)
        image=LOCAL_point_images(z,dx,dy,256);
        production(p,:)=abs(values-image)./max([realmin*ones(1,6); ...
          abs(values);abs(image)],[],1);
      end
    end
  end
  harmonic=LOCAL_linton_harmonics(z,tuples(end,:),[-2,-1,0,1,2]);
  termwise=LOCAL_termwise_harmonics(z,[-2,-1,0,1,2]);
  cross=LOCAL_cross_action_oracle(z,tuples(end,:),[-2,-1,0,1,2]);
  identities=LOCAL_linton_identities(z,tuples(end,:));
  maximum=max([defects(:);termwise.relative_defects(:); ...
    cross.maximum_relative_defect;identities.maximum_relative_defect]);
  holdout=max([production(:);harmonic.relative_defects(:)]);
  available=all(isfinite([defects(:);termwise.relative_defects(:); ...
      cross.maximum_relative_defect;production(:); ...
      harmonic.relative_defects(:);identities.maximum_relative_defect;wood]))&& ...
      identities.available&&all([branch.available]);
  out=struct('available',available, ...
    'qualified',available&&maximum<=1e-8,'points',points,'tuples',tuples, ...
    'project_sign',-1,'relative_wood_margin',wood, ...
    'branch_ledger',branch,'relative_defects',defects, ...
    'production_image_tail_holdout',production, ...
    'manufactured_total_image_tail_holdout',harmonic, ...
    'manufactured_termwise_harmonic_actions',termwise, ...
    'wall_circle_cross_action_oracle',cross, ...
    'image_tail_holdout_maximum',holdout, ...
    'image_tail_holdout_enters_kernel_1e8_gate',false, ...
    'Bloch_Helmholtz_branch_identities',identities, ...
    'maximum_relative_defect',maximum, ...
    'coordinate_map','X_L=abs(dx), Gx=sign(dx)*G_X, Gxy=sign(dx)*G_XY');
end

function out=LOCAL_cross_action_oracle(z,tuple,modes)
  level=struct('a',tuple(1),'M1',tuple(2),'M2',tuple(3),'N',tuple(4));
  circle_to_wall=zeros(numel(modes),2); wall_to_circle=circle_to_wall;
  Ntheta=512; theta=(0:Ntheta-1)'*2*pi/Ntheta;
  circle=[z.R*cos(theta),z.R*sin(theta)]; normals=circle/z.R;
  wall_orders=(-256:255).'; beta_wall=z.beta+2*pi*wall_orders/z.d;
  ywall=.173; psi=exp(1i*beta_wall*ywall)/sqrt(z.d);
  for j=1:numel(modes)
    density=struct('orders',(-128:127).','tau',zeros(256,2), ...
      'zeta',zeros(256,2)); id=find(density.orders==modes(j),1);
    density.tau(id,1)=1; density.zeta(id,2)=1;
    [FL,FR]=LOCAL_circle_to_wall(z,density,wall_orders);
    production=[psi.'*FL;psi.'*FR]; reference=zeros(2,2);
    for side=1:2
      xt=[z.X_L,z.X_R]; target=[xt(side),ywall];
      G=zeros(Ntheta,1); D=G;
      for p=1:Ntheta
        dx=target(1)-circle(p,1); dy=target(2)-circle(p,2); sx=sign(dx);
        raw=LOCAL_linton_kernel(z.khat,z.beta,z.d,abs(dx),dy,level);
        G(p)=-raw.G; grad=[-sx*raw.GX,-raw.GY];
        D(p)=-grad*normals(p,:).';
      end
      phi=exp(1i*modes(j)*theta); weight=2*pi*z.R/Ntheta;
      reference(side,:)=[weight*sum(D.*phi),-weight*sum(G.*phi)];
    end
    circle_to_wall(j,1)=LOCAL_metric(production(:,1),reference(:,1));
    circle_to_wall(j,2)=LOCAL_metric(production(:,2),reference(:,2));

    theta_target=.83; target=z.R*[cos(theta_target),sin(theta_target)];
    nt=target/z.R; ys=-z.d/2+z.d*(0:Ntheta-1)'/Ntheta;
    for side=1:2
      xiL=zeros(512,1); xiR=xiL; source_id=find(wall_orders==modes(j),1);
      if side==1, xiL(source_id)=1; else, xiR(source_id)=1; end
      wall_density=struct('xi_left',xiL,'xi_right',xiR);
      [value,dr]=LOCAL_wall_to_circle(z,wall_density,theta_target, ...
        target(1),target(2),nt(1),nt(2));
      xsource=[z.X_L,z.X_R]; G=zeros(Ntheta,1); dG=G;
      for p=1:Ntheta
        dx=target(1)-xsource(side); dy=target(2)-ys(p); sx=sign(dx);
        raw=LOCAL_linton_kernel(z.khat,z.beta,z.d,abs(dx),dy,level);
        G(p)=-raw.G; grad=[-sx*raw.GX,-raw.GY]; dG(p)=grad*nt.';
      end
      density_y=exp(1i*(z.beta+2*pi*modes(j)/z.d)*ys)/sqrt(z.d);
      reference_wall=z.d/Ntheta*[sum(G.*density_y),sum(dG.*density_y)];
      wall_to_circle(j,side)=LOCAL_metric([value,dr],reference_wall);
    end
  end
  maximum=max([circle_to_wall(:);wall_to_circle(:)]);
  out=struct('available',isfinite(maximum),'qualified',maximum<=1e-8, ...
    'modes',modes,'circle_to_wall_D_and_minusS',circle_to_wall, ...
    'wall_to_circle_value_and_global_r_normal',wall_to_circle, ...
    'circle_source_nodes',Ntheta,'wall_source_nodes',Ntheta, ...
    'maximum_relative_defect',maximum, ...
    'reference','project-signed Linton quadrature');
end

function [FL,FR]=LOCAL_circle_to_wall(z,density,orders)
  beta=z.beta+2*pi*orders/z.d; gamma=LOCAL_outgoing(z.khat,beta);
  l=density.orders.'; k=z.khat; R=z.R; zr=k*R;
  [lj,pj,ljp,pjp]=LOCAL_bessel_log_j(l,zr);
  FL=zeros(numel(orders),size(density.tau,2)); FR=FL;
  for j=1:numel(orders)
    common=1i/(2*gamma(j)*sqrt(z.d));
    travel_log=1i*gamma(j)*(z.X_R-z.X_L)/2;
    tauR=LOCAL_farfield_row(common,travel_log, ...
      (gamma(j)+1i*beta(j))/k,l,log(2*pi*R*k)+ljp,pjp);
    tauL=LOCAL_farfield_row(common,travel_log, ...
      (-gamma(j)+1i*beta(j))/k,l,log(2*pi*R*k)+ljp,pjp);
    zetaR=LOCAL_farfield_row(common,travel_log, ...
      (gamma(j)+1i*beta(j))/k,l,log(2*pi*R)+lj,pj);
    zetaL=LOCAL_farfield_row(common,travel_log, ...
      (-gamma(j)+1i*beta(j))/k,l,log(2*pi*R)+lj,pj);
    FR(j,:)=tauR*density.tau-zetaR*density.zeta;
    FL(j,:)=tauL*density.tau-zetaL*density.zeta;
  end
  if any(~isfinite([FL(:);FR(:)]))
    error('i32f:CircleWallAction','The circle-to-wall action is nonfinite.');
  end
end

function value=LOCAL_farfield_row(common,travel_log,base,l,lograd,phaserad)
  logarithm=log(common)+travel_log+l.*log(-1i)+l.*log(base)+ ...
    lograd+1i*phaserad;
  value=exp(logarithm);
end

function out=LOCAL_termwise_harmonics(z,modes)
  target=[.30,.066]; images=[-2,-1,1,2]; Nt=512;
  theta=(0:Nt-1)'*2*pi/Nt; source=[z.R*cos(theta),z.R*sin(theta)];
  normals=source/z.R; target_normal=target/norm(target); weight=2*pi*z.R/Nt;
  defects=zeros(numel(images),numel(modes),4);
  for a=1:numel(images)
    n=images(a); shifted=source+[zeros(Nt,1),n*z.d*ones(Nt,1)];
    delta=target-shifted; radius=hypot(delta(:,1),delta(:,2));
    er=delta./radius; H0=besselh(0,1,z.khat*radius);
    H1=besselh(1,1,z.khat*radius); H2=besselh(2,1,z.khat*radius);
    phi=1i/4*H0; fp=-1i*z.khat/4*H1;
    fpp=-1i*z.khat^2/8*(H0-H2);
    source_normal=-fp.*sum(er.*normals,2);
    target_dr=fp.*(er*target_normal.'); mixed=zeros(Nt,1);
    for p=1:Nt
      Hess=fpp(p)*(er(p,:).'*er(p,:))+fp(p)/radius(p)* ...
        (eye(2)-er(p,:).'*er(p,:));
      mixed(p)=-target_normal*Hess*normals(p,:).';
    end
    phase=exp(1i*z.beta*n*z.d);
    for j=1:numel(modes)
      density=exp(1i*modes(j)*theta);
      reference=phase*weight*[sum(phi.*density), ...
        sum(source_normal.*density),sum(target_dr.*density), ...
        sum(mixed.*density)];
      production=LOCAL_harmonic_one_image(z,modes(j),target,n);
      defects(a,j,:)=abs(production-reference)./max([realmin*ones(1,4); ...
        abs(production);abs(reference)],[],1);
    end
  end
  out=struct('images',images,'modes',modes,'target',target, ...
    'source_nodes',Nt,'columns',{{'S','D','dS','T'}}, ...
    'relative_defects',defects,'maximum_relative_defect',max(defects,[],'all'), ...
    'reference','direct free-kernel source quadrature for one image', ...
    'production','analytic one-image harmonic formula');
end

function values=LOCAL_harmonic_one_image(z,ell,target,n)
  k=z.khat; R=z.R; [lj,pj,ljp,pjp]=LOCAL_bessel_log_j(ell,k*R);
  Cs=exp(log(pi*R/2)+lj+1i*(pi/2+pj));
  Cd=exp(log(pi*R*k/2)+ljp+1i*(pi/2+pjp));
  dx=target(1); dy=target(2)-n*z.d; rr=hypot(dx,dy); ang=atan2(dy,dx);
  H=besselh(ell,1,k*rr); Hp=.5*(besselh(ell-1,1,k*rr)- ...
    besselh(ell+1,1,k*rr)); phase=exp(1i*z.beta*n*z.d+1i*ell*ang);
  er=[dx,dy]/rr; et=[-er(2),er(1)]; nt=target/norm(target);
  radial=k*Hp*dot(nt,er)+1i*ell/rr*H*dot(nt,et);
  values=phase*[Cs*H,Cd*H,Cs*radial,Cd*radial];
end

function out=LOCAL_linton_identities(z,tuple)
  level=struct('a',tuple(1),'M1',tuple(2),'M2',tuple(3),'N',tuple(4));
  dx=.263; dy=.173; base=LOCAL_linton_physical(z,dx,dy,level);
  target=LOCAL_linton_physical(z,dx,dy+z.d,level);
  source=LOCAL_linton_physical(z,dx,dy-z.d,level);
  target_phase=LOCAL_metric_record( ...
    target,exp(1i*z.beta*z.d)*base,1e-8);
  source_phase=LOCAL_metric_record( ...
    source,exp(-1i*z.beta*z.d)*base,1e-8);
  residual=base(4)+base(6)+z.khat^2*base(1);
  helmholtz_scale=max(realmin,abs(base(4))+abs(base(6))+ ...
    z.khat^2*abs(base(1)));
  helmholtz=struct('numerator',abs(residual), ...
    'left_norm',abs(base(4))+abs(base(6))+z.khat^2*abs(base(1)), ...
    'right_norm',0,'zero_component',false,'scale',helmholtz_scale, ...
    'ratio',abs(residual)/helmholtz_scale,'threshold',1e-8, ...
    'pass',isfinite(residual)&&abs(residual)/helmholtz_scale<=1e-8, ...
    'zero_reference',true);
  m=(-level.M1:level.M1).'; beta=z.beta+2*pi*m/z.d;
  t=z.khat^2-beta.^2; gamma=LOCAL_outgoing(z.khat,beta);
  prop=t>0; evan=t<0; sign_pass=all((~prop|real(gamma)>0)& ...
    (~evan|imag(gamma)>0));
  exact_wood=any(t==0); margin=min(abs(t)./(z.khat^2+beta.^2));
  maximum=max([target_phase.ratio,source_phase.ratio,helmholtz.ratio]);
  available=all(isfinite([base,target,source,gamma.',margin,maximum]))&& ...
    ~exact_wood&&sign_pass;
  out=struct('available',available,'target_Bloch_phase',target_phase, ...
    'source_inverse_phase',source_phase,'Helmholtz_identity',helmholtz, ...
    'relative_Wood_margin',margin,'exact_Wood',exact_wood, ...
    'propagating_count',sum(prop),'evanescent_count',sum(evan), ...
    'outgoing_gamma_sign_pass',sign_pass,'maximum_relative_defect',maximum);
end

function values=LOCAL_linton_physical(z,dx,dy,level)
  sx=sign(dx); raw=LOCAL_linton_kernel( ...
    z.khat,z.beta,z.d,abs(dx),dy,level);
  values=-[raw.G,sx*raw.GX,raw.GY,raw.GXX,sx*raw.GXY,raw.GYY];
end

function out=LOCAL_linton_harmonics(z,tuple,modes)
  level=struct('a',tuple(1),'M1',tuple(2),'M2',tuple(3),'N',tuple(4));
  target=[.30,.066]; Nt=128; theta=(0:Nt-1)'*2*pi/Nt;
  source=[z.R*cos(theta),z.R*sin(theta)]; normals=source/z.R;
  G=zeros(Nt,1); Gx=G; Gy=G;
  for j=1:Nt
    dx=target(1)-source(j,1); dy=target(2)-source(j,2); sx=sign(dx);
    raw=LOCAL_linton_kernel(z.khat,z.beta,z.d,abs(dx),dy,level);
    G(j)=-raw.G; Gx(j)=-sx*raw.GX; Gy(j)=-raw.GY;
  end
  source_normal=-(Gx.*normals(:,1)+Gy.*normals(:,2));
  target_r=target/norm(target); target_dr=Gx*target_r(1)+Gy*target_r(2);
  defects=zeros(numel(modes),4);
  for j=1:numel(modes)
    ell=modes(j); phi=exp(1i*ell*theta); weight=2*pi*z.R/Nt;
    reference=[weight*sum(G.*phi),weight*sum(source_normal.*phi), ...
      weight*sum(target_dr.*phi),NaN];
    production=LOCAL_harmonic_point(z,ell,target,256);
    reference(4)=weight*sum((LOCAL_linton_source_normal_dr( ...
      z,source,normals,target,target_r,level)).*phi);
    defects(j,:)=abs(production-reference)./max([realmin*ones(1,4); ...
      abs(production);abs(reference)],[],1);
  end
  out=struct('modes',modes,'target',target,'source_nodes',Nt, ...
    'relative_defects',defects,'maximum_relative_defect',max(defects,[],'all'), ...
    'production','analytic harmonic n=0 plus symmetric images', ...
    'reference','project-signed Linton source integration', ...
    'mixed_derivative_reference','analytic -e_t^T Hessian(G) n_s', ...
    'target_finite_difference_used',false);
end

function values=LOCAL_harmonic_point(z,ell,target,J)
  k=z.khat; R=z.R; [lj,pj,ljp,pjp]=LOCAL_bessel_log_j(ell,k*R);
  Cs=exp(log(pi*R/2)+lj+1i*(pi/2+pj));
  Cd=exp(log(pi*R*k/2)+ljp+1i*(pi/2+pjp));
  values=zeros(1,4); er=target/norm(target);
  for n=-J:J
    dx=target(1); dy=target(2)-n*z.d; rr=hypot(dx,dy); ang=atan2(dy,dx);
    H=besselh(ell,1,k*rr); Hp=.5*(besselh(ell-1,1,k*rr)- ...
      besselh(ell+1,1,k*rr)); phase=exp(1i*z.beta*n*z.d+1i*ell*ang);
    ern=[dx,dy]/rr; etn=[-ern(2),ern(1)];
    radial=k*Hp*dot(er,ern)+1i*ell/rr*H*dot(er,etn);
    values=values+phase*[Cs*H,Cd*H,Cs*radial,Cd*radial];
  end
end

function values=LOCAL_linton_source_normal_dr(z,source,normals,target,er,level)
  values=zeros(size(source,1),1);
  for j=1:size(source,1)
    dx=target(1)-source(j,1); dy=target(2)-source(j,2); sx=sign(dx);
    raw=LOCAL_linton_kernel(z.khat,z.beta,z.d,abs(dx),dy,level);
    Hessian=-[raw.GXX,sx*raw.GXY;sx*raw.GXY,raw.GYY];
    values(j)=-er*Hessian*normals(j,:).';
  end
end

function values=LOCAL_point_images(z,dx,dy,J)
  values=zeros(1,6); k=z.khat;
  for n=-J:J
    yy=dy-n*z.d; r=hypot(dx,yy);
    if r==0
      error('i32f:PointImageSingular','A point-image pair is singular.');
    end
    er=[dx/r,yy/r]; phase=exp(1i*z.beta*n*z.d);
    H0=besselh(0,1,k*r); H1=besselh(1,1,k*r); H2=besselh(2,1,k*r);
    f=1i/4*H0; fp=-1i*k/4*H1; fpp=-1i*k^2/8*(H0-H2);
    Hess=fpp*(er.'*er)+fp/r*(eye(2)-er.'*er);
    values=values+phase*[f,fp*er(1),fp*er(2), ...
      Hess(1,1),Hess(1,2),Hess(2,2)];
  end
end

function out=LOCAL_linton_kernel(k,beta,d,X,Y,level)
  [a,da]=LOCAL_linton_reciprocal(k,beta,d,X,Y,level);
  [b,db]=LOCAL_linton_real(k,beta,d,X,Y,level);
  out=struct('G',a+b,'GX',da.GX+db.GX,'GY',da.GY+db.GY, ...
    'GXX',da.GXX+db.GXX,'GXY',da.GXY+db.GXY,'GYY',da.GYY+db.GYY);
end

function [value,out]=LOCAL_linton_reciprocal(k,beta,d,X,Y,level)
  m=(-level.M1:level.M1).'; bm=beta+2*pi*m/d;
  q=zeros(size(bm)); ev=bm.^2-k^2>=0;
  q(ev)=sqrt(bm(ev).^2-k^2); q(~ev)=-1i*sqrt(k^2-bm(~ev).^2);
  b=level.a/d; cc=q*d/(2*level.a); zp=cc+b*X; zm=cc-b*X;
  ep=erfc(zp); em=erfc(zm); epp=-2/sqrt(pi)*exp(-zp.^2);
  emp=-2/sqrt(pi)*exp(-zm.^2); epp2=4/sqrt(pi)*zp.*exp(-zp.^2);
  emp2=4/sqrt(pi)*zm.*exp(-zm.^2);
  xp=exp(q*X); xm=exp(-q*X); Fp=xp.*ep; Fm=xm.*em;
  FXp=xp.*(q.*ep+b*epp); FXm=-xm.*(q.*em+b*emp);
  FXXp=xp.*(q.^2.*ep+2*b*q.*epp+b^2*epp2);
  FXXm=xm.*(q.^2.*em+2*b*q.*emp+b^2*emp2);
  phase=exp(1i*bm*Y); base=phase./q; scale=-1/(4*d); F=Fp+Fm;
  value=scale*sum(base.*F); out=struct( ...
    'GX',scale*sum(base.*(FXp+FXm)), ...
    'GY',scale*sum(1i*bm.*base.*F), ...
    'GXX',scale*sum(base.*(FXXp+FXXm)), ...
    'GXY',scale*sum(1i*bm.*base.*(FXp+FXm)), ...
    'GYY',scale*sum(-(bm.^2).*base.*F));
end

function [value,out]=LOCAL_linton_real(k,beta,d,X,Y,level)
  m=(-level.M2:level.M2).'; yy=Y-m*d; alpha=(level.a/d)^2;
  zz=alpha*(X^2+yy.^2);
  if any(zz==0)
    error('i32f:LintonSingular','A Linton pair is singular.');
  end
  ez=exp(-zz); Enm1=ez.*(1./zz+1./zz.^2); En=ez./zz; Enp1=expint(zz);
  S=zeros(size(zz)); Sz=S; Szz=S;
  for n=0:level.N
    coefficient=(k*d/(2*level.a))^(2*n)/factorial(n);
    S=S+coefficient*Enp1; Sz=Sz-coefficient*En;
    Szz=Szz+coefficient*Enm1;
    if n<level.N, Enm1=En; En=Enp1; Enp1=(ez-zz.*En)/(n+1); end
  end
  zx=2*alpha*X; zy=2*alpha*yy; phase=exp(1i*beta*m*d); scale=-1/(4*pi);
  value=scale*sum(phase.*S); out=struct( ...
    'GX',scale*sum(phase.*Sz*zx),'GY',scale*sum(phase.*Sz.*zy), ...
    'GXX',scale*sum(phase.*(Szz*zx^2+2*alpha*Sz)), ...
    'GXY',scale*sum(phase.*Szz.*zy*zx), ...
    'GYY',scale*sum(phase.*(Szz.*zy.^2+2*alpha*Sz)));
end

%% ==================== Structural and scientific diagnostics ====================
% These checks use the same parenthesization as Revision E and fail open.

function out=LOCAL_structural_metrics(c,z,density,circle,wall,oracle)
  wall_repair=LOCAL_set_threshold(wall.repaired_value_metric,c.identity_tol);
  circle_repair=LOCAL_set_threshold(circle.repaired_value_metric,c.identity_tol);
  left=LOCAL_metric_record(z.center_actual_left_trace+ ...
    z.center_left_value_mismatch,z.center_shared_left_trace,c.identity_tol);
  right=LOCAL_metric_record(z.center_actual_right_trace+ ...
    z.center_right_value_mismatch,z.center_shared_right_trace,c.identity_tol);
  safe_value=LOCAL_metric_record(1-3+2,0,c.identity_tol);
  safe_derivative=LOCAL_metric_record(-6+6,0,c.identity_tol);
  jump=max([circle.wronskian.exterior.D_jump_defect, ...
    circle.wronskian.exterior.dS_jump_defect, ...
    circle.wronskian.interior.D_jump_defect, ...
    circle.wronskian.interior.dS_jump_defect]);
  eta=[density.tau;density.zeta]; N=256;
  samples=[ifft(ifftshift(density.tau,1),[],1)*N; ...
    ifft(ifftshift(density.zeta,1),[],1)*N];
  roundtrip=LOCAL_metric_record(samples,z.eta_unit_256,c.identity_tol);
  bloch=LOCAL_bloch_metric(z,c.identity_tol);
  decomposition_records=[circle.normal_decomposition_records.normal_decomposition_metric];
  for j=1:numel(decomposition_records)
    decomposition_records(j)=LOCAL_set_threshold( ...
      decomposition_records(j),c.identity_tol);
  end
  decomposition=max([decomposition_records.ratio]);
  values=[wall_repair.ratio,circle_repair.ratio,left.ratio,right.ratio, ...
    safe_value.ratio,safe_derivative.ratio,jump,roundtrip.ratio, ...
    bloch.value.ratio,bloch.flux.ratio,decomposition];
  out=struct('wall_repaired_identity',wall_repair, ...
    'circle_repaired_identity',circle_repair, ...
    'circle_raw_value_jump_norm',circle.raw_value_jump_norm, ...
    'circle_value_lift_plus_norm',circle.raw_value_jump_norm/2, ...
    'circle_value_lift_minus_norm',circle.raw_value_jump_norm/2, ...
    'center_left_repaired_identity',left, ...
    'center_right_repaired_identity',right, ...
    'safe_rim_value',safe_value,'safe_rim_derivative',safe_derivative, ...
    'jump_sign_maximum',jump,'zeta_equals_minus_sigma_semantic',true, ...
    'density_scale_roundtrip',roundtrip,'bloch',bloch, ...
    'circle_normal_decomposition_maximum',decomposition, ...
    'circle_normal_decomposition',{decomposition_records}, ...
    'free_oracle',oracle.record.free_singular, ...
    'maximum_required_ratio',max(values), ...
    'pass',all(isfinite(values))&&max(values)<=c.identity_tol, ...
    'eta_coefficient_size',size(eta), ...
    'repaired_conformity_parenthesization_frozen',true, ...
    'identity_summary_used_as_substitute',false);
end

function out=LOCAL_bloch_metric(z,threshold)
  orders=(-256:255).'; beta_m=z.beta+2*pi*orders/z.d;
  coefficients=[z.center_shared_left_trace,z.center_shared_right_trace];
  y=.173; phase0=exp(1i*beta_m*y).';
  phase1=exp(1i*beta_m*(y+z.d)).';
  value0=phase0*coefficients; value1=phase1*coefficients;
  flux0=(1i*beta_m.*exp(1i*beta_m*y)).'*coefficients;
  flux1=(1i*beta_m.*exp(1i*beta_m*(y+z.d))).'*coefficients;
  bloch=exp(1i*z.beta*z.d);
  out=struct('value',LOCAL_metric_record(value1,bloch*value0,threshold), ...
    'flux',LOCAL_metric_record(flux1,bloch*flux0,threshold), ...
    'wall_fourier_part_structural',true, ...
    'physical_to_periodic_gauge_roundtrip',true, ...
    'finite_image_target_Bloch_consumed_here',false);
end

function warnings=LOCAL_scientific_warnings(c,circle,oracle,structural,parity)
  warnings=LOCAL_empty_warnings();
  if circle.angular_action_metric.ratio>c.action_ratio_max
    warnings(end+1)=LOCAL_warning('CIRCLE_ACTION_QUALIFICATION_WARNING', ...
      circle.angular_action_metric.ratio); %#ok<AGROW>
  end
  if ~circle.actual_T_action.qualified
    warnings(end+1)=LOCAL_warning('ACTUAL_DELTA_T_ACTION_WARNING', ...
      circle.actual_T_action.maximum_contraction_ratio); %#ok<AGROW>
  end
  if ~circle.finite_image_bloch.qualified
    warnings(end+1)=LOCAL_warning('FINITE_IMAGE_BLOCH_ACTION_WARNING', ...
      circle.finite_image_bloch.maximum_final_ratio); %#ok<AGROW>
  end
  if ~oracle.qualified
    warnings(end+1)=LOCAL_warning('ANALYTIC_KERNEL_ORACLE_WARNING', ...
      max([oracle.record.free_singular.maximum_relative_defect, ...
      oracle.record.linton_off_axis.maximum_relative_defect, ...
      oracle.record.high_order_recurrence.maximum_relative_defect])); %#ok<AGROW>
  end
  if ~structural.pass
    warnings(end+1)=LOCAL_warning('SAME_TRIAL_STRUCTURE_WARNING', ...
      structural.maximum_required_ratio); %#ok<AGROW>
  end
  if ~parity.pass
    warnings(end+1)=LOCAL_warning('SIGNATURE_PARITY_UNRESOLVED', ...
      max([parity.records.ratio])); %#ok<AGROW>
  end
end

%% ==================== Common transforms and module audit ====================
% No dense native target ladder is published outside this module.

function out=LOCAL_metric_record(a,b,threshold)
  if nargin<3, threshold=NaN; end
  numerator=norm(a-b,'fro'); left=norm(a,'fro'); right=norm(b,'fro');
  scale=max([realmin,left,right]);
  out=struct('label','','numerator',numerator,'left_norm',left, ...
    'right_norm',right,'zero_component',left==0&&right==0, ...
    'scale',scale,'ratio',numerator/scale,'threshold',threshold, ...
    'pass',isfinite(numerator)&&(isnan(threshold)||numerator/scale<=threshold));
end

function out=LOCAL_set_threshold(out,threshold)
  out.threshold=threshold; out.pass=isfinite(out.ratio)&&out.ratio<=threshold;
end

function value=LOCAL_metric(a,b)
  value=norm(a-b,'fro')/max([realmin,norm(a,'fro'),norm(b,'fro')]);
end

function coeff=LOCAL_circle_coeff(values,R)
  N=size(values,1); coeff=sqrt(2*pi*R)*fftshift(fft(values,[],1),1)/N;
end

function Y=LOCAL_pad_orders(X,N,Nout)
  if N==Nout, Y=X; return; end
  if N>Nout||mod(N,2)||mod(Nout,2)
    error('i32f:OrderPadding','Invalid Fourier order padding.');
  end
  Y=zeros(Nout,size(X,2),'like',X); source=(-N/2:N/2-1).';
  target=(-Nout/2:Nout/2-1).'; [tf,at]=ismember(source,target);
  if ~all(tf), error('i32f:OrderPadding','A source order is not nested.'); end
  Y(at,:)=X;
end

function out=LOCAL_liveness_ledger()
  paths={'finest_factors.jump_minus','finest_factors.jump_plus', ...
    'finest_factors.delta_minus','finest_factors.delta_plus', ...
    'cap_signatures.image','cap_signatures.image_pairs', ...
    'cap_signatures.angular','cap_signatures.angular_pairs', ...
    'cap_signatures.joint'};
  out=repmat(struct('field_path','','consumer_set',{{'fullp_cap'}}, ...
    'unique_last_consumer','fullp_cap','death','after fullp_cap'),numel(paths),1);
  for j=1:numel(paths), out(j).field_path=paths{j}; end
end

function LOCAL_hard_time(timer,c,stage)
  if toc(timer)>c.hard_seconds
    error('i32f:HardTime','The hard limit was reached in %s.',stage);
  end
end

function out=LOCAL_resource_record(before,input_alias,peak,returned,c)
  exclusive=max(0,peak-input_alias);
  out=struct('retained_before_mib',before,'input_alias_nominal_mib',input_alias, ...
    'local_workspace_peak_mib',peak,'module_exclusive_peak_mib',exclusive, ...
    'frozen_streaming_transient_mib',c.worst_transient_mib, ...
    'concurrent_peak_candidate_mib', ...
      before+max(c.worst_transient_mib,exclusive), ...
    'return_payload_mib',returned,'retained_after_mib',NaN, ...
    'cumulative_peak_candidate_mib',NaN, ...
    'proxy_semantics',[ ...
      'deterministic active-object proxy; not RSS, allocator high-water, ', ...
      'reference-count, or copy-on-write proof']);
end

function out=LOCAL_zero_counters()
  out=struct('candidate_solve_calls',0,'qz_solve_calls',0, ...
    'coordinate_solve_calls',0,'propagation_solve_calls',0, ...
    'wall_density_solve_calls',0,'circle_density_solve_calls',0, ...
    'schur_solve_calls',0,'proxy_build_calls',0, ...
    'harmonic_action_calls',0,'image_pair_updates',0, ...
    'kress_oracle_calls',0,'linton_oracle_calls',0, ...
    'actual_deltaT_action_calls',0,'finite_bloch_image_updates',0, ...
    'riccati_calls',0,'gauss_factor_calls',0, ...
    'full_p_contraction_calls',0, ...
    'small_hermitian_gram_diagnostic_eig_calls',0, ...
    'gauss_golub_welsch_eig_calls',0, ...
    'n_op_signature_parity',0,'n_op_combined_gram_parity',0);
end

function out=LOCAL_empty_warnings()
  out=struct('code',{},'value',{},'blocking',{});
end

function out=LOCAL_warning(code,value)
  out=struct('code',char(code),'value',double(value),'blocking',false);
end

function out=LOCAL_condition(code,message)
  out=struct('code',char(code),'message',char(message));
end

function value=LOCAL_workspace_mib()
  info=evalin('caller','whos'); value=sum([info.bytes])/2^20;
end

function value=LOCAL_value_mib(item)
  info=whos('item'); value=info.bytes/2^20;
end

function out=LOCAL_owner_inventory()
  info=evalin('caller','whos'); out=cell(numel(info),1);
  for j=1:numel(info)
    out{j}=struct('name',info(j).name,'class',info(j).class, ...
      'size',info(j).size,'bytes',info(j).bytes);
  end
end
