function out = i32_fullp_cap(c,staged,lift,wall,circle,timer,retained_before_mib)
%I32_FULLP_CAP Project compact signatures and form the frozen empirical cap.
% Purpose:
%   Consume the fixed certificate, finest boundary factors, and compact
%   nested signatures, then reproduce the full-P tail, cap, field, and
%   nominal-transform formulas without retaining augmented vectors.
% Input:
%   c, staged, lift, wall, circle, timer - Frozen REV_F objects.
%   retained_before_mib                 - Caller active-object proxy.
% Output:
%   out                                 - Typed total compact cap result.
% Main algorithm:
%   Reconstruct endpoint and pair norms from orthogonal squared signatures,
%   combine circle and wall volume Grams before one tail per side, preserve
%   all 292 contraction categories, and run the two arithmetic parity gates.
% Based on:
%   i32_cap_tail.m Revision E and design-3-2c.md REV_F.
% Main changes:
%   No endpoint vector or dense nested level leaves its producer.  Full-P
%   powers remain complete matrices and the sole eig allowlist is the small
%   Hermitian Gram diagnostic in LOCAL_psd_root.
% Numerical goal:
%   Produce the same ordinary empirical candidate with bounded retained memory.

  calls=LOCAL_zero_counters(); warnings=LOCAL_empty_warnings(); peak=0;
  first=LOCAL_condition('NONE','All compact cap objects are available.');
  available=false; public=LOCAL_unavailable_public(); signatures=struct();
  input_alias=LOCAL_value_mib(staged)+LOCAL_value_mib(lift)+ ...
    LOCAL_value_mib(wall)+LOCAL_value_mib(circle);
  peak=max(peak,LOCAL_workspace_mib());
  try
    z=staged.certificate;
    [final_factors,final_sig,gram_parity]= ...
      LOCAL_final_objects(c,z,lift,wall.finest_factors, ...
      circle.finest_factors);
    [final,calls]=LOCAL_project_components(c,z,final_sig,calls,'final',true);
    [state,calls]=LOCAL_state_tail(c,z,calls);
    [artifact,artifact_pair,artifact_audit,calls,artifact_gram]= ...
      LOCAL_artifact(c,staged,lift,final_factors,final,calls);
    gram_parity=LOCAL_concat(gram_parity,artifact_gram);
    [anchors,anchor_warnings]=LOCAL_anchors(c,staged,artifact,final,artifact_pair);
    warnings=[warnings,anchor_warnings];
    [axes,axis_warnings,calls,axis_gram]=LOCAL_axes( ...
      c,z,lift,wall,circle,final_factors,final_sig,final,calls,timer);
    warnings=[warnings,axis_warnings]; gram_parity=LOCAL_concat(gram_parity,axis_gram);
    [shells,shell_warnings,calls,shell_gram]=LOCAL_shells( ...
      c,z,lift,wall.finest_factors,circle.finest_factors,calls);
    warnings=[warnings,shell_warnings];
    gram_parity=LOCAL_concat(gram_parity,shell_gram);
    [arithmetic,arith_warnings]=LOCAL_arithmetic(c,final);
    warnings=[warnings,arith_warnings];
    components=LOCAL_component_caps(anchors,axes,shells,arithmetic);
    [field,field_warnings,calls]=LOCAL_field_cap(c,staged,calls);
    warnings=[warnings,field_warnings];
    producer_parity=LOCAL_producer_parity(wall,circle);
    endpoint_parity=LOCAL_collect_endpoint_parity( ...
      final_sig,artifact,artifact_pair,axes,shells);
    signature_parity=LOCAL_join_parity(producer_parity,endpoint_parity);
    combined_gram=LOCAL_gram_parity_summary(gram_parity);
    calls.n_op_signature_parity=endpoint_parity.total_operations;
    calls.n_op_combined_gram_parity=combined_gram.total_operations;
    qualification=LOCAL_qualification(wall,circle,signature_parity,combined_gram);
    numerator_available=components.wall.available&&components.circle.available&& ...
      components.volume.available&&axes.interaction.pass&&state.available&& ...
      qualification.kernel_oracle_available&&qualification.kernel_qualified&& ...
      qualification.conformity_qualified&&qualification.actual_T_qualified&& ...
      qualification.finite_bloch_qualified&&signature_parity.pass&& ...
      combined_gram.pass;
    denominator_available=field.available;
    if ~numerator_available
      first=LOCAL_first_unavailable(components,axes,shells,arithmetic,state, ...
        qualification,signature_parity,combined_gram);
    elseif ~denominator_available
      first=LOCAL_condition('FIELD_PARTIAL_EMPIRICALLY_UNRESOLVED', ...
        'The same finite field partial did not form a one-sided empirical cap.');
    end
    caps=LOCAL_caps(staged,components,field,numerator_available, ...
      denominator_available);
    estimator=LOCAL_estimator(staged,c,caps,numerator_available, ...
      denominator_available);
    warnings=[warnings,LOCAL_tail_warnings(c,final,state)];
    category=LOCAL_category_audit(calls);
    if ~category.pass
      first=LOCAL_condition('FULL_P_CONTRACTION_IDENTITY_UNAVAILABLE', ...
        'The full-P category ledger is not the frozen 292 allocation.');
    end
    eig_audit=LOCAL_eig_audit(calls);
    if ~eig_audit.pass
      first=LOCAL_condition('GRAM_EIG_CALL_IDENTITY_UNAVAILABLE', ...
        'The small-Gram eig ledger is not 274.');
    end
    available=category.pass&&eig_audit.pass;
    public=struct('components',components,'caps',caps,'estimator',estimator, ...
      'tails',struct('components',LOCAL_public_tails(final),'state',state), ...
      'axis_metrics',struct('axes',axes,'shells',shells), ...
      'arithmetic',arithmetic,'field_same_partial',field, ...
      'artifact_association',anchors,'artifact_audit',artifact_audit, ...
      'signature_parity',signature_parity, ...
      'combined_gram_parity',combined_gram, ...
      'qualification',qualification,'numerator_available',numerator_available, ...
      'denominator_available',denominator_available, ...
      'all_modes_included',circle.public_metrics.all_computed_circle_modes_retained, ...
      'first_empirical_unavailable',first, ...
      'unresolved_axes',{LOCAL_unresolved(axes,shells,arithmetic,state, ...
        qualification,signature_parity,combined_gram)}, ...
      'full_p_counter_audit',category,'allowlisted_eig_audit',eig_audit, ...
      'raw_value_enters_volume_only',true, ...
      'raw_wall_normal_enters_wall_only',true, ...
      'raw_circle_normal_enters_circle_only',true, ...
      'uncomputed_tails_outward_enclosed',false);
    signatures=struct('final_norms',LOCAL_public_components(final), ...
      'artifact_norms',LOCAL_public_components(artifact), ...
      'producer_parity',producer_parity,'endpoint_parity',endpoint_parity);
    clear final_factors final_sig artifact_pair artifact gram_parity;
    clear axes shells final state;
  catch ME
    available=false; first=LOCAL_condition(ME.identifier,ME.message);
    signatures=struct();
  end
  peak=max(peak,LOCAL_workspace_mib());
  clear staged lift wall circle timer z final_factors final_sig final state;
  clear artifact artifact_pair artifact_audit gram_parity anchors axes shells;
  clear arithmetic components field producer_parity endpoint_parity;
  clear signature_parity combined_gram qualification caps estimator;
  clear category eig_audit;
  audit=struct('returned_field_inventory',{{}}, ...
    'returned_numeric_shape_inventory',{{}},'prohibited_field_count',NaN, ...
    'prohibited_shape_count',NaN,'last_use_clear_ledger',LOCAL_liveness_ledger(), ...
    'post_clear_local_owner_inventory',{LOCAL_owner_inventory()}, ...
    'finest_factor_whitelist',{{}}, ...
    'compact_signature_whitelist',{{'cap_signatures.final_norms', ...
      'cap_signatures.artifact_norms','cap_signatures.producer_parity', ...
      'cap_signatures.endpoint_parity'}}, ...
    'small_gram_eig_expression','eig((W+W'')/2)', ...
    'small_gram_eig_is_candidate_solve',false, ...
    'dense_augmented_vectors_returned',false, ...
    'full_matrix_P_powers_retained',true);
  payload=struct('available',available,'first_unavailable',first, ...
    'public_metrics',public,'finest_factors',struct(), ...
    'cap_signatures',signatures,'audit_summary',audit,'warnings',warnings, ...
    'call_counters',calls,'resource_record',struct());
  payload.resource_record=LOCAL_resource_record(retained_before_mib, ...
    input_alias,peak,LOCAL_value_mib(payload),c);
  out=payload;
end

%% ==================== Final finest-factor objects ====================
% Final factors remain live only for parity, artifact association, and shells.

function [factors,sig,gram]=LOCAL_final_objects(c,z,lift,wall,circle)
  bw=lift.wall_trace; bc=lift.circle_weights{end};
  cv=lift.collar_weights{end}/z.gamma;
  wv=lift.wall_lift_weights{end}/z.gamma;
  LOCAL_weight_gate(bw,bc,cv,wv);
  factors.wall=struct('minus',LOCAL_weight_rows(wall.normal_minus,1./sqrt(bw)), ...
    'plus',LOCAL_weight_rows(wall.normal_plus,1./sqrt(bw)), ...
    'center',[wall.center_wall.left./sqrt(bw);wall.center_wall.right./sqrt(bw)], ...
    'endpoint_id','final-wall');
  factors.circle=struct( ...
    'minus',LOCAL_weight_rows(circle.jump_minus,1./sqrt(bc)), ...
    'plus',LOCAL_weight_rows(circle.jump_plus,1./sqrt(bc)), ...
    'center',zeros(0,1),'endpoint_id','final-circle');
  factors.volume_circle=struct( ...
    'minus',LOCAL_weight_rows(circle.delta_minus,sqrt(cv)), ...
    'plus',LOCAL_weight_rows(circle.delta_plus,sqrt(cv)), ...
    'center',zeros(0,1),'endpoint_id','final-volume-circle', ...
    'combined_endpoint_id','final-volume');
  factors.volume_wall=LOCAL_volume_wall_factors(z,wall,wv);
  factors.volume_wall.endpoint_id='final-volume-wall';
  factors.volume_wall.combined_endpoint_id='final-volume';
  sig.wall=LOCAL_factor_signature(c,'final-wall','wall',factors.wall,z,32);
  sig.circle=LOCAL_factor_signature(c,'final-circle','circle',factors.circle,z,32);
  sc=LOCAL_factor_signature(c,'final-volume-circle','volume-circle', ...
    factors.volume_circle,z,32);
  sw=LOCAL_factor_signature(c,'final-volume-wall','volume-wall', ...
    factors.volume_wall,z,32);
  [sig.volume,gram]=LOCAL_combine_volume(c,'final-volume',sc,sw, ...
    factors.volume_circle,factors.volume_wall,z,32,true,'actual-final');
end

function out=LOCAL_volume_wall_factors(z,wall,wv)
  DLp=LOCAL_weight_rows(wall.defect_left_plus,sqrt(wv));
  DRp=LOCAL_weight_rows(wall.defect_right_plus,sqrt(wv));
  DLm=LOCAL_weight_rows(wall.defect_left_minus,sqrt(wv));
  DRm=LOCAL_weight_rows(wall.defect_right_minus,sqrt(wv));
  left=LOCAL_pad_orders(z.center_left_value_mismatch,512,numel(wv));
  right=LOCAL_pad_orders(z.center_right_value_mismatch,512,numel(wv));
  out=struct('minus',[DLm;DRm*z.Pminus], ...
    'plus',[DRp;DLp*z.Pplus], ...
    'center',[sqrt(wv).*left;sqrt(wv).*right; ...
      DLp*z.cplus;DRm*z.cminus]);
end

function sig=LOCAL_factor_signature(c,label,component,f,z,N)
  if isfield(f,'endpoint_id')&&~strcmp(label,f.endpoint_id)
    error('i32f:EndpointIdentity', ...
      'The factor endpoint identity differs from its signature identity.');
  end
  if isscalar(N), Nm=N; Np=N; else, Nm=N(1); Np=N(2); end
  class_name=LOCAL_endpoint_parity_class(label,false);
  parity_required=~isempty(class_name);
  [sm,bm]=LOCAL_side_factor_signature( ...
    c,f.minus,z.Pminus,z.cminus,Nm,parity_required);
  [sp,bp]=LOCAL_side_factor_signature( ...
    c,f.plus,z.Pplus,z.cplus,Np,parity_required);
  center_squared=norm(f.center)^2;
  parity=struct([]);
  if parity_required
    tm=LOCAL_tail_slot(z.Pminus,sm.W,z.cminus,Nm,c);
    tp=LOCAL_tail_slot(z.Pplus,sp.W,z.cplus,Np,c);
    long=norm([f.center(:);bm;sqrt(tm.value);bp;sqrt(tp.value)]);
    reconstructed=sqrt(center_squared+sum(sm.direct_squared_terms(1:Nm))+ ...
      tm.value+sum(sp.direct_squared_terms(1:Np))+tp.value);
    nops=4*(numel(f.center)+numel(bm)+numel(bp)+2)+16;
    parity=LOCAL_parity_record(label,class_name,long,reconstructed,nops);
    clear tm tp long reconstructed;
  end
  sig=struct('endpoint_id',label,'component',component, ...
    'row_order','frozen canonical row blocks','Nminus',Nm,'Nplus',Np, ...
    'center_squared',center_squared,'minus',sm,'plus',sp, ...
    'finite',sm.finite&&sp.finite&&isfinite(center_squared), ...
    'signature_parity',parity, ...
    'augmented_length',numel(f.center)+32*size(f.minus,1)+1+ ...
      32*size(f.plus,1)+1);
  clear bm bp;
end

function [out,block]=LOCAL_side_factor_signature(c,H,P,c0,N,need_block)
  Nmax=max(c.full_p_levels); rows=size(H,1); terms=zeros(1,Nmax);
  if need_block, block=zeros(rows*Nmax,1,'like',H*c0); else, block=[]; end
  state=c0;
  for n=1:Nmax
    action=H*state; terms(n)=norm(action)^2;
    if need_block&&n<=N, block((n-1)*rows+(1:rows))=action; end
    state=P*state;
  end
  W=H'*H;
  out=struct('W',W,'direct_squared_terms',terms, ...
    'tail_input_audit',struct('rows',rows,'state_dimension',size(P,1)), ...
    'finite',all(isfinite([W(:);terms(:)])));
end

function [out,records]=LOCAL_combine_volume(c,label,a,b,fa,fb,z,N,actual,class_name)
  if isscalar(N), Nm=N; Np=N; else, Nm=N(1); Np=N(2); end
  records=struct([]);
  if isempty(fa)&&isempty(fb)
    label=[a.endpoint_id,'+',b.endpoint_id];
  end
  if ~isempty(fa)&&~isempty(fb)&& ...
      (~strcmp(fa.combined_endpoint_id,label)|| ...
      ~strcmp(fb.combined_endpoint_id,label))
    error('i32f:CombinedEndpointIdentity', ...
      'A combined-volume endpoint identity is inconsistent.');
  end
  minus=LOCAL_combine_side(a.minus,b.minus); plus=LOCAL_combine_side(a.plus,b.plus);
  center_squared=a.center_squared+b.center_squared;
  parity=LOCAL_combined_direct_parity( ...
    c,label,a,b,fa,fb,z,[Nm,Np],center_squared,actual);
  if nargin>=10&&~isempty(fa)&&~isempty(fb)&&~isempty(class_name)
    records=LOCAL_concat(records,LOCAL_gram_parity(label,'minus', ...
      fa.minus,fb.minus,minus.W,actual,class_name));
    records=LOCAL_concat(records,LOCAL_gram_parity(label,'plus', ...
      fa.plus,fb.plus,plus.W,actual,class_name));
  end
  out=struct('endpoint_id',label,'component','volume', ...
    'row_order','[volume-circle; volume-wall] before single tail', ...
    'Nminus',Nm,'Nplus',Np,'center_squared',center_squared, ...
    'minus',minus,'plus',plus,'finite',a.finite&&b.finite&& ...
      all(isfinite([minus.W(:);plus.W(:);center_squared])), ...
    'signature_parity',parity, ...
    'augmented_length',LOCAL_signature_length(a)+LOCAL_signature_length(b)-2);
end

function out=LOCAL_combine_side(a,b)
  out=struct('W',a.W+b.W, ...
    'direct_squared_terms',a.direct_squared_terms+b.direct_squared_terms, ...
    'tail_input_audit',struct('rows',a.tail_input_audit.rows+ ...
      b.tail_input_audit.rows,'state_dimension',a.tail_input_audit.state_dimension, ...
      'family_grams_added_before_tail',true), ...
    'finite',a.finite&&b.finite);
end

function out=LOCAL_combined_direct_parity(c,label,a,b,fa,fb,z,N,center,actual)
  if isscalar(N), Nm=N; Np=N; else, Nm=N(1); Np=N(2); end
  class_name=LOCAL_endpoint_parity_class(label,true);
  if isempty(class_name)||isempty(fa)||isempty(fb)
    out=struct([]); return;
  end
  Hm=[fa.minus;fb.minus]; Hp=[fa.plus;fb.plus];
  minus=LOCAL_direct_blocks(Hm,z.Pminus,z.cminus,Nm,c);
  plus=LOCAL_direct_blocks(Hp,z.Pplus,z.cplus,Np,c);
  long_tm=LOCAL_tail_slot(z.Pminus,Hm'*Hm,z.cminus,Nm,c);
  long_tp=LOCAL_tail_slot(z.Pplus,Hp'*Hp,z.cplus,Np,c);
  sig_tm=LOCAL_tail_slot(z.Pminus,a.minus.W+b.minus.W,z.cminus,Nm,c);
  sig_tp=LOCAL_tail_slot(z.Pplus,a.plus.W+b.plus.W,z.cplus,Np,c);
  center_block=[fa.center(:);fb.center(:)];
  long=norm([center_block;minus;sqrt(long_tm.value); ...
    plus;sqrt(long_tp.value)]);
  reconstructed=sqrt(center+ ...
    sum(a.minus.direct_squared_terms(1:Nm))+ ...
    sum(b.minus.direct_squared_terms(1:Nm))+sig_tm.value+ ...
    sum(a.plus.direct_squared_terms(1:Np))+ ...
    sum(b.plus.direct_squared_terms(1:Np))+sig_tp.value);
  nops=4*(numel(center_block)+numel(minus)+numel(plus)+2)+32;
  out=LOCAL_parity_record(label,class_name,long,reconstructed,nops);
  out.actual=actual; out.representative=~actual;
  clear center_block minus plus;
end

function block=LOCAL_direct_blocks(H,P,c0,N,c)
  rows=size(H,1); block=zeros(rows*max(c.full_p_levels),1,'like',H*c0);
  state=c0;
  for j=1:N
    block((j-1)*rows+(1:rows))=H*state; state=P*state;
  end
end

function out=LOCAL_gram_parity(label,side,A,B,Wsum,actual,class_name)
  stacked=[A;B]; Wstack=stacked'*stacked;
  nops=4*(numel(A)+numel(B))+2*numel(Wsum);
  stack_norm=norm(Wstack,2); sum_norm=norm(Wsum,2);
  scale=max([realmin,stack_norm,sum_norm]); allowance=100*nops*eps*scale;
  numerator=norm(Wstack-Wsum,2);
  out=struct('label',label,'side',side,'object_class',class_name, ...
    'actual',actual,'representative',~actual,'n_gram',nops, ...
    'stack_norm',stack_norm,'sum_norm',sum_norm,'numerator',numerator, ...
    'scale',scale,'allowance',allowance, ...
    'ratio',numerator/max(realmin,allowance), ...
    'pass',isfinite(numerator)&&numerator<=allowance);
end

function [out,calls]=LOCAL_project_components(c,z,sig,calls,category,diagnostic)
  names={'wall','circle','volume'};
  for j=1:3
    [out.(names{j}),calls]=LOCAL_project_endpoint( ...
      c,z,sig.(names{j}),calls,category,diagnostic);
  end
  out.tail_records=struct('wall',out.wall.tail, ...
    'circle',out.circle.tail,'volume',out.volume.tail);
end

function [out,calls]=LOCAL_project_endpoint(c,z,sig,calls,category,diagnostic)
  if diagnostic
    calls=LOCAL_increment(calls,'small_hermitian_gram_diagnostic_eig_calls',2);
    LOCAL_psd_root(sig.minus.W); LOCAL_psd_root(sig.plus.W);
  end
  tm=LOCAL_tail_slot(z.Pminus,sig.minus.W,z.cminus,sig.Nminus,c);
  tp=LOCAL_tail_slot(z.Pplus,sig.plus.W,z.cplus,sig.Nplus,c);
  calls=LOCAL_category_increment(calls,category,2);
  direct_squared=sig.center_squared+ ...
    sum(sig.minus.direct_squared_terms(1:sig.Nminus))+tm.value+ ...
    sum(sig.plus.direct_squared_terms(1:sig.Nplus))+tp.value;
  if direct_squared<0&&direct_squared>=-100*eps*max(realmin,abs(direct_squared))
    direct_squared=0;
  end
  B=sqrt(direct_squared);
  tail=struct('label',sig.endpoint_id,'Nminus',sig.Nminus, ...
    'Nplus',sig.Nplus,'minus',tm,'plus',tp, ...
    'Nmax',max(c.full_p_levels),'direct_rows_zero_padded',true, ...
    'center_squared',sig.center_squared, ...
    'direct_minus_squares',sig.minus.direct_squared_terms(1:sig.Nminus).', ...
    'direct_plus_squares',sig.plus.direct_squared_terms(1:sig.Nplus).', ...
    'first_four_direct_quadratic_actions',LOCAL_first_four(sig), ...
    'tail_slots_separate',true,'available',tm.available&&tp.available);
  out=struct('B',B,'tail',tail,'finite',isfinite(B)&&tail.available, ...
    'signature',sig,'augmented_length',LOCAL_signature_length(sig));
end

function LOCAL_psd_root(W)
  scale=norm(W,2); herm=norm(W-W','fro')/max(realmin,scale);
  [~,D]=eig((W+W')/2); eigen=real(diag(D));
  tol=100*eps*max(realmin,scale);
  if any(~isfinite(W),'all')||herm>1e-10||min(eigen)<-tol
    error('i32e:ComponentGram','A squared-norm Gram is invalid.');
  end
end

function out=LOCAL_tail_slot(P,W,c0,N,c)
  PN=eye(size(P)); WN=zeros(size(W)); state=c0; direct=0;
  for j=1:N
    direct=direct+real(state'*W*state); WN=WN+PN'*W*PN;
    state=P*state; PN=P*PN;
  end
  alternate=LOCAL_binary_power(P,N); defect=norm(PN-alternate,2);
  [Walternate,Pcheck]=LOCAL_gram_doubling(W,P,N);
  gram_defect=norm(WN-Walternate,2);
  defect=max(defect,norm(PN-Pcheck,2));
  pscale=max([1,norm(PN,2),norm(alternate,2)]);
  ahi=norm(PN,2)+defect+100*numel(c0)*eps*pscale;
  left_scale=norm(WN,2); association_scale=max(left_scale,norm(Walternate,2));
  omega=gram_defect;
  if association_scale>0
    omega=omega+100*numel(c0)*eps*association_scale;
  end
  if ahi<1&&isfinite(ahi)
    tail=ahi^2/(1-ahi^2)*(left_scale+omega)*norm(c0)^2;
  else
    tail=Inf;
  end
  tolerance=100*numel(c0)*eps*norm(W,2)*norm(c0)^2;
  if direct<0&&direct>=-tolerance, direct=0; end
  out=struct('value',tail,'finite_partial',direct,'a_hi',ahi, ...
    'power_association_defect',defect,'roundoff_allowance',omega, ...
    'gram_association_defect',gram_defect,'left_WN_norm',left_scale, ...
    'alternate_WN_norm',norm(Walternate,2), ...
    'tail_share',tail/max(realmin,direct),'available', ...
    isfinite(tail)&&tail>=0&&isfinite(direct)&&direct>=0, ...
    'certified',false);
end

function [WN,PN]=LOCAL_gram_doubling(W,P,N)
  if N<1||N~=2^round(log2(N))
    WN=zeros(size(W)); PN=eye(size(P)); state=eye(size(P));
    for j=1:N, WN=WN+state'*W*state; state=P*state; end
    PN=state; return;
  end
  WN=W; PN=P; count=1;
  while count<N
    WN=WN+PN'*WN*PN; PN=PN*PN; count=2*count;
  end
end

function value=LOCAL_binary_power(P,N)
  if N==0, value=eye(size(P)); return; end
  value=eye(size(P)); base=P; count=N;
  while count>0
    if mod(count,2)==1, value=value*base; end
    count=floor(count/2);
    if count>0, base=base*base; end
  end
end

function out=LOCAL_first_four(sig)
  out=NaN(4,3); out(:,1)=(0:3).';
  out(1:min(4,sig.Nminus),2)= ...
    sig.minus.direct_squared_terms(1:min(4,sig.Nminus)).';
  out(1:min(4,sig.Nplus),3)= ...
    sig.plus.direct_squared_terms(1:min(4,sig.Nplus)).';
end

function n=LOCAL_signature_length(sig)
  if isfield(sig,'augmented_length'), n=sig.augmented_length; return; end
  rowsm=sig.minus.tail_input_audit.rows;
  rowsp=sig.plus.tail_input_audit.rows;
  if strcmp(sig.component,'circle')||strcmp(sig.component,'volume-circle')
    center=0;
  elseif strcmp(sig.component,'wall')
    center=2*rowsm;
  else
    center=2*rowsm;
  end
  n=center+32*rowsm+1+32*rowsp+1;
end

%% ==================== State and artifact association ====================
% Artifact raw maps are reconstructed once and die after compact association.

function [out,calls]=LOCAL_state_tail(c,z,calls)
  template=struct('N',0,'minus',struct(),'plus',struct(), ...
    'available',false,'maximum_share',Inf);
  levels=repmat(template,1,numel(c.full_p_levels)); selected=NaN;
  for j=1:numel(c.full_p_levels)
    N=c.full_p_levels(j);
    tm=LOCAL_tail_slot(z.Pminus,eye(size(z.Pminus)),z.cminus,N,c);
    tp=LOCAL_tail_slot(z.Pplus,eye(size(z.Pplus)),z.cplus,N,c);
    calls=LOCAL_category_increment(calls,'state',2);
    share=max(tm.tail_share,tp.tail_share);
    levels(j)=struct('N',N,'minus',tm,'plus',tp, ...
      'available',tm.available&&tp.available,'maximum_share',share);
    if isnan(selected)&&levels(j).available, selected=j; end
  end
  if isnan(selected), selected_N=NaN; else, selected_N=levels(selected).N; end
  out=struct('available',~isnan(selected),'selected_index',selected, ...
    'selected_N',selected_N,'levels',levels, ...
    'ordinary_candidate',true,'certified',false);
end

function [out,pair,audit,calls,gram]= ...
    LOCAL_artifact(c,staged,lift,final_factors,final,calls)
  z=staged.certificate; a=staged.raw_maps; Nw=4096; Nc=2048;
  bw=lift.wall_trace; bc=lift.circle_weights{end};
  cv=lift.collar_weights{end}/z.gamma;
  wv=lift.wall_lift_weights{end}/z.gamma;
  Jp=LOCAL_pad_orders(a.Jplus,512,Nw); Jm=LOCAL_pad_orders(a.Jminus,512,Nw);
  f.wall=struct('minus',LOCAL_weight_rows(Jm,1./sqrt(bw)), ...
    'plus',LOCAL_weight_rows(Jp,1./sqrt(bw)), ...
    'center',LOCAL_artifact_wall_center(z,bw),'endpoint_id','artifact-wall');
  f.circle=struct( ...
    'minus',LOCAL_weight_rows(LOCAL_pad_orders( ...
      a.circle_jump_minus,512,Nc),1./sqrt(bc)), ...
    'plus',LOCAL_weight_rows(LOCAL_pad_orders( ...
      a.circle_jump_plus,512,Nc),1./sqrt(bc)), ...
    'center',zeros(0,1),'endpoint_id','artifact-circle');
  f.volume_circle=struct( ...
    'minus',LOCAL_weight_rows(LOCAL_pad_orders(a.delta_minus,512,Nc),sqrt(cv)), ...
    'plus',LOCAL_weight_rows(LOCAL_pad_orders(a.delta_plus,512,Nc),sqrt(cv)), ...
    'center',zeros(0,1),'endpoint_id','artifact-volume-circle', ...
    'combined_endpoint_id','artifact-volume');
  [defL,defR,wall_audit]=LOCAL_artifact_wall_defects(staged,Nw);
  wall_unweighted=struct('defect_left_minus',defL*z.Gminus, ...
    'defect_left_plus',defL*z.Gplus, ...
    'defect_right_minus',defR*z.Gminus, ...
    'defect_right_plus',defR*z.Gplus);
  f.volume_wall=LOCAL_volume_wall_factors(z,wall_unweighted,wv);
  f.volume_wall.endpoint_id='artifact-volume-wall';
  f.volume_wall.combined_endpoint_id='artifact-volume';
  Nm=round(staged.ordinary_anchor.tail_minus.selected_N);
  Np=round(staged.ordinary_anchor.tail_plus.selected_N); selected=[Nm,Np];
  index=staged.ordinary_anchor.first_level_indices;
  first_level_pass=index.minus_selected_N==Nm&& ...
    index.plus_selected_N==Np&& ...
    isequal(index.minus_physical_start(:).',[0,0,0,1,0])&& ...
    isequal(index.plus_physical_start(:).',[0,0,0,1,0]);
  if ~first_level_pass
    error('i32f:ArtifactIndexAssociation', ...
      'The frozen first-level artifact index association is unavailable.');
  end
  sig.wall=LOCAL_factor_signature(c,'artifact-wall','wall',f.wall,z,selected);
  sig.circle=LOCAL_factor_signature(c,'artifact-circle','circle',f.circle,z,selected);
  sc=LOCAL_factor_signature(c,'artifact-volume-circle','volume-circle', ...
    f.volume_circle,z,selected);
  sw=LOCAL_factor_signature(c,'artifact-volume-wall','volume-wall', ...
    f.volume_wall,z,selected);
  [sig.volume,gram]=LOCAL_combine_volume(c,'artifact-volume',sc,sw, ...
    f.volume_circle,f.volume_wall,z,selected,true,'actual-artifact');
  [out,calls]=LOCAL_project_components(c,z,sig,calls,'artifact',true);
  pair.wall=LOCAL_factor_pair(c,f.wall,final_factors.wall,z,selected,32);
  pair.circle=LOCAL_factor_pair(c,f.circle,final_factors.circle,z,selected,32);
  pair.volume=LOCAL_combined_factor_pair(c, ...
    f.volume_circle,f.volume_wall,final_factors.volume_circle, ...
    final_factors.volume_wall,z,selected,32);
  audit=struct('wall_common',wall_audit, ...
    'circle_delta_plus_norm',norm(a.delta_plus,'fro'), ...
    'circle_delta_minus_norm',norm(a.delta_minus,'fro'), ...
    'circle_jump_plus_norm',norm(a.circle_jump_plus,'fro'), ...
    'circle_jump_minus_norm',norm(a.circle_jump_minus,'fro'), ...
    'wall_jump_plus_norm',norm(a.Jplus,'fro'), ...
    'wall_jump_minus_norm',norm(a.Jminus,'fro'), ...
    'first_level_index_contract_pass',first_level_pass, ...
    'raw_maps_returned',false,'common_coordinate_reconstruction',true);
  clear f sig sc sw defL defR wall_unweighted;
end

function center=LOCAL_artifact_wall_center(z,bw)
  left=LOCAL_pad_orders(z.center_wall_jumps.left_coefficients,512,numel(bw));
  right=LOCAL_pad_orders(z.center_wall_jumps.right_coefficients,512,numel(bw));
  center=[left./sqrt(bw);right./sqrt(bw)];
end

function [defL,defR,record]=LOCAL_artifact_wall_defects(s,Nout)
  a=s.raw_maps; y=a.wall_common_y_1024(:); beta=s.certificate.beta;
  values=a.wall_common_value_1024; N=numel(y);
  if size(values,1)~=2*N
    error('i32f:ArtifactWallMap','The artifact common wall map has wrong size.');
  end
  rawL=LOCAL_physical_coeff(values(1:N,:),y,beta,s.certificate.d);
  rawR=LOCAL_physical_coeff(values(N+1:end,:),y,beta,s.certificate.d);
  input=a.wall_input_unit_512;
  gL=LOCAL_pad_orders(input(1:512,:),512,N);
  gR=LOCAL_pad_orders(input(513:end,:),512,N);
  nativeL=gL-rawL; nativeR=gR-rawR;
  defL=LOCAL_pad_orders(nativeL,N,Nout);
  defR=LOCAL_pad_orders(nativeR,N,Nout);
  record=struct('grid_nodes',N,'order_min',-N/2,'order_max',N/2-1, ...
    'defect_left_norm',norm(nativeL,'fro'), ...
    'defect_right_norm',norm(nativeR,'fro'), ...
    'raw_left_norm',norm(rawL,'fro'),'raw_right_norm',norm(rawR,'fro'), ...
    'shared_left_norm',norm(gL,'fro'),'shared_right_norm',norm(gR,'fro'), ...
    'canonical_output_orders',Nout,'Fourier_evaluation_not_nearest_node',true);
end

function coeff=LOCAL_physical_coeff(values,y,beta,d)
  N=numel(y); gauge=bsxfun(@times,values,exp(-1i*beta*y));
  shift=exp(-1i*2*pi*(-N/2:N/2-1).'*y(1)/d);
  coeff=sqrt(d)*fftshift(fft(gauge,[],1),1)/N;
  coeff=bsxfun(@times,coeff,shift);
end

function out=LOCAL_factor_pair(c,a,b,z,Na,Nb)
  if isscalar(Na), Nam=Na; Nap=Na; else, Nam=Na(1); Nap=Na(2); end
  if isscalar(Nb), Nbm=Nb; Nbp=Nb; else, Nbm=Nb(1); Nbp=Nb(2); end
  label=[a.endpoint_id,'->',b.endpoint_id];
  class_name=LOCAL_pair_parity_class(label,false);
  parity_required=~isempty(class_name);
  [dm,bm]=LOCAL_side_factor_pair( ...
    c,a.minus,b.minus,z.Pminus,z.cminus,Nam,Nbm,parity_required);
  [dp,bp]=LOCAL_side_factor_pair( ...
    c,a.plus,b.plus,z.Pplus,z.cplus,Nap,Nbp,parity_required);
  dc=norm(b.center-a.center)^2;
  parity=struct([]);
  if parity_required
    am=LOCAL_tail_slot(z.Pminus,a.minus'*a.minus,z.cminus,Nam,c);
    bm_tail=LOCAL_tail_slot(z.Pminus,b.minus'*b.minus,z.cminus,Nbm,c);
    ap=LOCAL_tail_slot(z.Pplus,a.plus'*a.plus,z.cplus,Nap,c);
    bp_tail=LOCAL_tail_slot(z.Pplus,b.plus'*b.plus,z.cplus,Nbp,c);
    long=norm([b.center(:)-a.center(:);bm; ...
      sqrt(bm_tail.value)-sqrt(am.value);bp; ...
      sqrt(bp_tail.value)-sqrt(ap.value)]);
    reconstructed=sqrt(dc+sum(dm)+ ...
      (sqrt(bm_tail.value)-sqrt(am.value))^2+sum(dp)+ ...
      (sqrt(bp_tail.value)-sqrt(ap.value))^2);
    nops=4*(numel(a.center)+numel(bm)+numel(bp)+2)+24;
    parity=LOCAL_parity_record(label,class_name,long,reconstructed,nops);
    clear am bm_tail ap bp_tail long reconstructed;
  end
  out=struct('left_endpoint_id',a.endpoint_id, ...
    'right_endpoint_id',b.endpoint_id, ...
    'center_difference_squared',dc, ...
    'minus_direct_difference_squared_terms',dm, ...
    'plus_direct_difference_squared_terms',dp, ...
    'left_norm_scale',NaN,'right_norm_scale',NaN, ...
    'finite',all(isfinite([dc,dm,dp])), ...
    'signature_parity',parity);
  clear bm bp;
end

function [terms,block]=LOCAL_side_factor_pair(c,A,B,P,c0,Na,Nb,need_block)
  rows=size(A,1); Nmax=max(c.full_p_levels);
  if size(B,1)~=rows
    error('i32f:SignatureRows','A factor pair has inconsistent row order.');
  end
  terms=zeros(1,Nmax);
  if need_block, block=zeros(rows*Nmax,1,'like',A*c0); else, block=[]; end
  state=c0;
  for n=1:Nmax
    da=zeros(rows,1,'like',A*c0); db=da;
    if n<=Na, da=A*state; end
    if n<=Nb, db=B*state; end
    difference=db-da; terms(n)=norm(difference)^2;
    if need_block, block((n-1)*rows+(1:rows))=difference; end
    state=P*state;
  end
end

function out=LOCAL_combine_pair(a,b)
  out=struct('left_endpoint_id',[a.left_endpoint_id,'+',b.left_endpoint_id], ...
    'right_endpoint_id',[a.right_endpoint_id,'+',b.right_endpoint_id], ...
    'center_difference_squared',a.center_difference_squared+ ...
      b.center_difference_squared, ...
    'minus_direct_difference_squared_terms', ...
      a.minus_direct_difference_squared_terms+ ...
      b.minus_direct_difference_squared_terms, ...
    'plus_direct_difference_squared_terms', ...
      a.plus_direct_difference_squared_terms+ ...
      b.plus_direct_difference_squared_terms, ...
    'left_norm_scale',max(a.left_norm_scale,b.left_norm_scale), ...
    'right_norm_scale',max(a.right_norm_scale,b.right_norm_scale), ...
    'finite',a.finite&&b.finite,'signature_parity',struct([]));
end

function out=LOCAL_combined_factor_pair(c,ac,aw,bc,bw,z,Na,Nb)
  if isscalar(Na), Nam=Na; Nap=Na; else, Nam=Na(1); Nap=Na(2); end
  if isscalar(Nb), Nbm=Nb; Nbp=Nb; else, Nbm=Nb(1); Nbp=Nb(2); end
  if ~strcmp(ac.combined_endpoint_id,aw.combined_endpoint_id)|| ...
      ~strcmp(bc.combined_endpoint_id,bw.combined_endpoint_id)
    error('i32f:CombinedEndpointIdentity', ...
      'Combined-volume factor families do not share an endpoint identity.');
  end
  label=[ac.combined_endpoint_id,'->',bc.combined_endpoint_id];
  class_name=LOCAL_pair_parity_class(label,true);
  parity_required=~isempty(class_name);
  Am=[ac.minus;aw.minus]; Bm=[bc.minus;bw.minus];
  Ap=[ac.plus;aw.plus]; Bp=[bc.plus;bw.plus];
  [dm,bm]=LOCAL_side_factor_pair( ...
    c,Am,Bm,z.Pminus,z.cminus,Nam,Nbm,parity_required);
  [dp,bp]=LOCAL_side_factor_pair( ...
    c,Ap,Bp,z.Pplus,z.cplus,Nap,Nbp,parity_required);
  center_difference=[bc.center(:)-ac.center(:);bw.center(:)-aw.center(:)];
  dc=norm(center_difference)^2; parity=struct([]);
  if parity_required
    old_am=LOCAL_tail_slot(z.Pminus,Am'*Am,z.cminus,Nam,c);
    old_bm=LOCAL_tail_slot(z.Pminus,Bm'*Bm,z.cminus,Nbm,c);
    old_ap=LOCAL_tail_slot(z.Pplus,Ap'*Ap,z.cplus,Nap,c);
    old_bp=LOCAL_tail_slot(z.Pplus,Bp'*Bp,z.cplus,Nbp,c);
    sig_am=LOCAL_tail_slot(z.Pminus, ...
      ac.minus'*ac.minus+aw.minus'*aw.minus,z.cminus,Nam,c);
    sig_bm=LOCAL_tail_slot(z.Pminus, ...
      bc.minus'*bc.minus+bw.minus'*bw.minus,z.cminus,Nbm,c);
    sig_ap=LOCAL_tail_slot(z.Pplus, ...
      ac.plus'*ac.plus+aw.plus'*aw.plus,z.cplus,Nap,c);
    sig_bp=LOCAL_tail_slot(z.Pplus, ...
      bc.plus'*bc.plus+bw.plus'*bw.plus,z.cplus,Nbp,c);
    long=norm([center_difference;bm; ...
      sqrt(old_bm.value)-sqrt(old_am.value);bp; ...
      sqrt(old_bp.value)-sqrt(old_ap.value)]);
    reconstructed=sqrt(dc+sum(dm)+ ...
      (sqrt(sig_bm.value)-sqrt(sig_am.value))^2+sum(dp)+ ...
      (sqrt(sig_bp.value)-sqrt(sig_ap.value))^2);
    nops=4*(numel(center_difference)+numel(bm)+numel(bp)+2)+24;
    parity=LOCAL_parity_record(label,class_name,long,reconstructed,nops);
    clear old_am old_bm old_ap old_bp sig_am sig_bm sig_ap sig_bp;
    clear long reconstructed;
  end
  out=struct('left_endpoint_id',ac.combined_endpoint_id, ...
    'right_endpoint_id',bc.combined_endpoint_id, ...
    'center_difference_squared',dc, ...
    'minus_direct_difference_squared_terms',dm, ...
    'plus_direct_difference_squared_terms',dp, ...
    'left_norm_scale',NaN,'right_norm_scale',NaN, ...
    'finite',all(isfinite([dc,dm,dp])), ...
    'signature_parity',parity);
  clear center_difference bm bp;
end

function out=LOCAL_project_pair(a,b,pair)
  left_match=strcmp(LOCAL_canonical_endpoint_id(pair.left_endpoint_id), ...
    LOCAL_canonical_endpoint_id(a.signature.endpoint_id));
  right_match=strcmp(LOCAL_canonical_endpoint_id(pair.right_endpoint_id), ...
    LOCAL_canonical_endpoint_id(b.signature.endpoint_id));
  if ~left_match||~right_match
    error('i32f:PairEndpointIdentity', ...
      'A pair signature does not name the projected endpoint identities.');
  end
  scalar=abs(b.B-a.B);
  factor=sqrt(pair.center_difference_squared+ ...
    sum(pair.minus_direct_difference_squared_terms)+ ...
    (sqrt(b.tail.minus.value)-sqrt(a.tail.minus.value))^2+ ...
    sum(pair.plus_direct_difference_squared_terms)+ ...
    (sqrt(b.tail.plus.value)-sqrt(a.tail.plus.value))^2);
  numerator=max(scalar,factor); scale=max([realmin,a.B,b.B]);
  out=struct('left_endpoint_id',pair.left_endpoint_id, ...
    'right_endpoint_id',pair.right_endpoint_id, ...
    'endpoint_identity_match',left_match&&right_match, ...
    'scalar_shift',scalar,'factor_shift',factor, ...
    'left_norm',a.B,'right_norm',b.B,'zero_component',a.B==0&&b.B==0, ...
    'value',numerator,'numerator',numerator,'scale',scale, ...
    'ratio',numerator/scale,'threshold',NaN,'absolute_threshold',NaN, ...
    'pass',isfinite(numerator),'signature_parity',pair.signature_parity);
end

function [out,warnings]=LOCAL_anchors(c,s,artifact,final,pair)
  warnings=LOCAL_empty_warnings(); names={'wall','circle','volume'};
  fields={'B_wall','B_circle','B_volume'};
  for j=1:3
    name=names{j}; a=artifact.(name); f=final.(name);
    anchor=s.ordinary_anchor.(fields{j}); metric=LOCAL_project_pair(a,f,pair.(name));
    scale=max([realmin,anchor,f.B,a.B]); nops=2*f.augmented_length+8;
    omega=100*nops*eps*scale; observed=max(abs(f.B-anchor),metric.factor_shift);
    association=abs(f.B-a.B)<=metric.factor_shift+omega;
    out.(name)=struct('artifact_scalar',anchor, ...
      'artifact_common_factor_norm',a.B,'fresh_final',f.B, ...
      'scalar_shift',abs(f.B-anchor),'factor_shift',metric.factor_shift, ...
      'observed_shift',observed,'comparison_operations',nops, ...
      'comparison_omega',omega,'A',observed+omega, ...
      'numerator',abs(f.B-a.B),'scale',max(realmin,metric.factor_shift+omega), ...
      'ratio',abs(f.B-a.B)/max(realmin,metric.factor_shift+omega), ...
      'threshold',1,'pass',association,'reverse_triangle_pass',association, ...
      'available',a.finite&&f.finite&&association&&isfinite(observed+omega), ...
      'factor_metric',metric);
    if ~out.(name).available
      warnings(end+1)=LOCAL_warning('COMPONENT_NORM_ASSOCIATION_UNRESOLVED', ...
        out.(name).ratio); %#ok<AGROW>
    end
  end
end

%% ==================== Nested axes and interaction ====================
% Every old build still projects all three components for the 292 ledger.

function [out,warnings,calls,gram]= ...
    LOCAL_axes(c,z,lift,wall,circle,final_factors,final_sig,final,calls,timer)
  warnings=LOCAL_empty_warnings(); gram=struct([]);
  image=cell(1,7);
  for j=1:7
    [sig,g]=LOCAL_existing_choice(c,z,wall,circle,j,3,3,32);
    gram=LOCAL_concat(gram,g);
    [image{j},calls]=LOCAL_project_components(c,z,sig,calls,'image',true);
  end
  out.image_circle=LOCAL_image_axis(c,image,circle.cap_signatures.image_pairs, ...
    'circle','circle');
  volume_pairs=cell(1,5);
  for j=1:5
    volume_pairs{j}=LOCAL_combine_pair( ...
      circle.cap_signatures.image_pairs{j}.volume_circle, ...
      LOCAL_zero_pair_like(wall.cap_signatures.output_pairs{2}.volume_wall, ...
        wall.cap_signatures.output{3}.volume_wall.endpoint_id));
  end
  out.image_volume=LOCAL_image_axis(c,image,volume_pairs,'volume','volume');

  [out.angular_circle,calls,g]=LOCAL_module_three_axis(c,z,wall,circle, ...
    'angular','circle',calls); gram=LOCAL_concat(gram,g);
  [out.angular_volume,calls,g]=LOCAL_module_three_axis(c,z,wall,circle, ...
    'angular','volume',calls); gram=LOCAL_concat(gram,g);
  [out.wall_wall,calls,g]=LOCAL_module_three_axis(c,z,wall,circle, ...
    'wall','wall',calls); gram=LOCAL_concat(gram,g);
  [out.wall_volume,calls,g]=LOCAL_module_three_axis(c,z,wall,circle, ...
    'wall','volume',calls); gram=LOCAL_concat(gram,g);
  [out.riccati_circle,calls,g]=LOCAL_weight_three_axis( ...
    c,z,lift,wall,circle,'riccati','circle',calls); gram=LOCAL_concat(gram,g);
  [out.gauss_volume,calls,g]=LOCAL_weight_three_axis( ...
    c,z,lift,wall,circle,'gauss','volume',calls); gram=LOCAL_concat(gram,g);
  [fullp_sig,fullp_pairs,~,g]= ...
    LOCAL_fullp_signature_lattice(c,z,final_factors);
  gram=LOCAL_concat(gram,g);
  [out.fullp_wall,calls]=LOCAL_fullp_three_axis( ...
    c,z,fullp_sig,fullp_pairs,'wall',calls);
  [out.fullp_circle,calls]=LOCAL_fullp_three_axis( ...
    c,z,fullp_sig,fullp_pairs,'circle',calls);
  [out.fullp_volume,calls]=LOCAL_fullp_three_axis( ...
    c,z,fullp_sig,fullp_pairs,'volume',calls);
  [out.interaction,calls,g]=LOCAL_interaction( ...
    c,z,lift,wall,circle,final_sig,final,fullp_sig,fullp_pairs,calls);
  gram=LOCAL_concat(gram,g);
  names=fieldnames(out);
  for j=1:numel(names)
    item=out.(names{j});
    if isfield(item,'available'), pass=item.available; else, pass=item.pass; end
    if ~pass
      warnings(end+1)=LOCAL_warning(LOCAL_axis_code(names{j}), ...
        item.ratio); %#ok<AGROW>
    end
  end
  LOCAL_hard_time(timer,c,'full-P axes');
end

function id=LOCAL_canonical_endpoint_id(id)
  final_wall={'wall-output-4096-wall','final-wall-N32'};
  final_circle={'angular-N-2048-circle','image-J-256-circle', ...
    'final-circle-N32'};
  final_volume={ ...
    'angular-N-2048-volume-circle+wall-output-4096-volume-wall', ...
    'image-J-256-volume-circle+wall-output-4096-volume-wall', ...
    'final-volume-N32'};
  if any(strcmp(id,final_wall)), id='final-wall';
  elseif any(strcmp(id,final_circle)), id='final-circle';
  elseif any(strcmp(id,final_volume)), id='final-volume';
  end
end

function [sig,gram]=LOCAL_existing_choice(c,z,wall,circle,image,angular,windex,N)
  if image>0
    ce=circle.cap_signatures.image{image};
  else
    ce=circle.cap_signatures.angular{angular};
  end
  we=wall.cap_signatures.output{windex}; gram=struct([]);
  sig.wall=LOCAL_set_N(we.wall,N);
  sig.circle=LOCAL_set_N(ce.circle,N);
  [sig.volume,g]=LOCAL_combine_volume(c,'existing-volume', ...
    LOCAL_set_N(ce.volume_circle,N),LOCAL_set_N(we.volume_wall,N), ...
    [],[],z,N,false,'producer-combined');
  gram=LOCAL_concat(gram,g);
end

function sig=LOCAL_set_N(sig,N)
  sig.Nminus=N; sig.Nplus=N;
end

function out=LOCAL_image_axis(c,values,pairs,component,label)
  map=[3,5;5,7;2,4;4,6;6,7]; labels={ ...
    '64_to_128','128_to_256','48_to_96','96_to_192','192_to_256'};
  metrics=cell(1,5); scale=realmin;
  for j=1:7, scale=max(scale,values{j}.(component).B); end
  for j=1:5
    metrics{j}=LOCAL_project_pair(values{map(j,1)}.(component), ...
      values{map(j,2)}.(component),pairs{j});
    metrics{j}.label=labels{j};
  end
  metrics=[metrics{:}]; omega=100*values{end}.(component).augmented_length*eps*scale;
  for j=[1,3,5], metrics(j).threshold=Inf; metrics(j).absolute_threshold=Inf; end
  metrics(2).threshold=c.image_ratio_max;
  metrics(2).absolute_threshold=max(c.image_ratio_max*metrics(1).numerator,omega);
  metrics(4).threshold=c.image_ratio_max;
  metrics(4).absolute_threshold=max(c.image_ratio_max*metrics(3).numerator,omega);
  for j=1:5
    metrics(j).pass=isfinite(metrics(j).numerator)&& ...
      metrics(j).numerator<=metrics(j).absolute_threshold;
  end
  dyadic_near=metrics(1).value<=omega&&metrics(2).value<=omega;
  staggered_near=metrics(3).value<=omega&&metrics(4).value<=omega;
  dyadic=dyadic_near||metrics(2).value<= ...
    max(c.image_ratio_max*metrics(1).value,omega);
  staggered=staggered_near||metrics(4).value<= ...
    max(c.image_ratio_max*metrics(3).value,omega);
  available=dyadic&&staggered&&all(isfinite([[metrics.value],omega]));
  if available
    remainder=c.image_remainder_factor*max([metrics(2).value, ...
      metrics(4).value,metrics(5).value,omega]);
  else, remainder=NaN; end
  ratio=max(metrics(2).value/max(realmin,metrics(1).value), ...
    metrics(4).value/max(realmin,metrics(3).value));
  out=struct('axis','image','component',label,'differences',metrics, ...
    'omega',omega,'dyadic_pass',dyadic,'staggered_pass',staggered, ...
    'cross_finite',isfinite(metrics(5).value), ...
    'numerator',max(metrics(2).value,metrics(4).value), ...
    'scale',max([realmin,metrics(1).value,metrics(3).value]), ...
    'ratio',ratio,'threshold',c.image_ratio_max,'pass',available, ...
    'maximum_ratio',ratio,'remainder',remainder,'available',available, ...
    'all_projected_endpoint_parity',LOCAL_component_value_parity(values));
end

function zero=LOCAL_zero_pair_like(pair,endpoint_id)
  zero=pair; zero.center_difference_squared=0;
  zero.minus_direct_difference_squared_terms(:)=0;
  zero.plus_direct_difference_squared_terms(:)=0;
  zero.left_endpoint_id=endpoint_id; zero.right_endpoint_id=endpoint_id;
  zero.signature_parity=struct([]);
end

function [out,calls,gram]=LOCAL_module_three_axis( ...
    c,z,wall,circle,axis,component,calls)
  values=cell(1,3); pairs=cell(1,2); gram=struct([]);
  for j=1:3
    if strcmp(axis,'angular')
      ce=circle.cap_signatures.angular{j}; we=wall.cap_signatures.output{3};
    else
      ce=circle.cap_signatures.angular{3}; we=wall.cap_signatures.output{j};
    end
    sig.wall=we.wall; sig.circle=ce.circle;
    [sig.volume,g]=LOCAL_combine_volume(c,[axis,'-volume'], ...
      ce.volume_circle,we.volume_wall,[],[],z,32,false,'producer-combined');
    gram=LOCAL_concat(gram,g);
    [values{j},calls]=LOCAL_project_components( ...
      c,z,sig,calls,'three_axis',true);
  end
  for j=1:2
    if strcmp(axis,'angular')
      base=circle.cap_signatures.angular_pairs{j};
      if strcmp(component,'circle')
        pairs{j}=base.circle;
      else
        pairs{j}=LOCAL_combine_pair( ...
          base.volume_circle, ...
          LOCAL_zero_pair_like(wall.cap_signatures.output_pairs{2}.volume_wall, ...
            wall.cap_signatures.output{3}.volume_wall.endpoint_id));
      end
    else
      base=wall.cap_signatures.output_pairs{j};
      if strcmp(component,'wall')
        pairs{j}=base.wall;
      else
        pairs{j}=LOCAL_combine_pair( ...
          LOCAL_zero_pair_like( ...
            circle.cap_signatures.angular_pairs{2}.volume_circle, ...
            circle.cap_signatures.angular{3}.volume_circle.endpoint_id), ...
          base.volume_wall);
      end
    end
  end
  out=LOCAL_three_axis_metric(c,values,pairs,axis,component);
end

function [out,calls,gram]=LOCAL_weight_three_axis( ...
    c,z,lift,wall,circle,axis,component,calls)
  values=cell(1,3); factors=cell(1,3); pairs=cell(1,2); gram=struct([]);
  base_wall=wall.cap_signatures.output{3}.wall;
  base_circle=circle.cap_signatures.angular{3}.circle;
  base_volume_circle=circle.cap_signatures.angular{3}.volume_circle;
  base_volume_wall=wall.cap_signatures.output{3}.volume_wall;
  for j=1:3
    sig.wall=base_wall; sig.circle=base_circle;
    if strcmp(axis,'riccati')
      bc=lift.circle_weights{j};
      factors{j}=struct('minus',LOCAL_weight_rows( ...
        circle.finest_factors.jump_minus,1./sqrt(bc)), ...
        'plus',LOCAL_weight_rows(circle.finest_factors.jump_plus,1./sqrt(bc)), ...
        'center',zeros(0,1),'endpoint_id',sprintf('riccati-circle-%d',j));
      sig.circle=LOCAL_factor_signature(c,sprintf('riccati-circle-%d',j), ...
        'circle',factors{j},z,32);
      sig.volume=LOCAL_existing_combined_volume(c,z, ...
        base_volume_circle,base_volume_wall,32);
    else
      cv=lift.collar_weights{j}/z.gamma;
      wv=lift.wall_lift_weights{j}/z.gamma;
      fc=struct('minus',LOCAL_weight_rows( ...
        circle.finest_factors.delta_minus,sqrt(cv)), ...
        'plus',LOCAL_weight_rows(circle.finest_factors.delta_plus,sqrt(cv)), ...
        'center',zeros(0,1));
      fw=LOCAL_volume_wall_factors(z,wall.finest_factors,wv);
      fc.endpoint_id=sprintf('gauss-volume-circle-%d',j);
      fc.combined_endpoint_id=sprintf('gauss-volume-%d',j);
      fw.endpoint_id=sprintf('gauss-volume-wall-%d',j);
      fw.combined_endpoint_id=sprintf('gauss-volume-%d',j);
      factors{j}=struct('circle',fc,'wall',fw);
      sc=LOCAL_factor_signature(c,sprintf('gauss-volume-circle-%d',j), ...
        'volume-circle',fc,z,32);
      sw=LOCAL_factor_signature(c,sprintf('gauss-volume-wall-%d',j), ...
        'volume-wall',fw,z,32);
      [sig.volume,g]=LOCAL_combine_volume(c,sprintf('gauss-volume-%d',j), ...
        sc,sw,fc,fw,z,32,true,'actual-gauss-axis');
      gram=LOCAL_concat(gram,g);
    end
    [values{j},calls]=LOCAL_project_components( ...
      c,z,sig,calls,'three_axis',true);
  end
  for j=1:2
    if strcmp(axis,'riccati')
      pairs{j}=LOCAL_factor_pair(c,factors{j},factors{j+1},z,32,32);
    else
      pairs{j}=LOCAL_combined_factor_pair(c, ...
        factors{j}.circle,factors{j}.wall, ...
        factors{j+1}.circle,factors{j+1}.wall,z,32,32);
    end
  end
  out=LOCAL_three_axis_metric(c,values,pairs,axis,component);
  clear factors;
end

function out=LOCAL_existing_combined_volume(c,z,a,b,N)
  [out,~]=LOCAL_combine_volume(c,'existing-final-volume', ...
    LOCAL_set_N(a,N),LOCAL_set_N(b,N),[],[],z,N,false,'producer-combined');
end

function [signatures,pairs,records,gram]= ...
    LOCAL_fullp_signature_lattice(c,z,final_factors)
  signatures=cell(1,3); pairs=cell(1,2); records=struct([]); gram=struct([]);
  for j=1:3
    N=c.full_p_levels(j); f=final_factors;
    f.wall.endpoint_id=sprintf('final-wall-N%d',N);
    f.circle.endpoint_id=sprintf('final-circle-N%d',N);
    f.volume_circle.endpoint_id=sprintf('final-volume-circle-N%d',N);
    f.volume_wall.endpoint_id=sprintf('final-volume-wall-N%d',N);
    f.volume_circle.combined_endpoint_id=sprintf('final-volume-N%d',N);
    f.volume_wall.combined_endpoint_id=sprintf('final-volume-N%d',N);
    sig.wall=LOCAL_factor_signature(c,f.wall.endpoint_id,'wall',f.wall,z,N);
    sig.circle=LOCAL_factor_signature(c,f.circle.endpoint_id,'circle',f.circle,z,N);
    sc=LOCAL_factor_signature(c,f.volume_circle.endpoint_id, ...
      'volume-circle',f.volume_circle,z,N);
    sw=LOCAL_factor_signature(c,f.volume_wall.endpoint_id, ...
      'volume-wall',f.volume_wall,z,N);
    if N==32, class_name='actual-fullp-final'; else, class_name=''; end
    [sig.volume,g]=LOCAL_combine_volume(c, ...
      f.volume_circle.combined_endpoint_id,sc,sw,f.volume_circle, ...
      f.volume_wall,z,N,true,class_name);
    gram=LOCAL_concat(gram,g); signatures{j}=sig;
    records=LOCAL_concat(records,sig.wall.signature_parity);
    records=LOCAL_concat(records,sig.circle.signature_parity);
    records=LOCAL_concat(records,sig.volume.signature_parity);
  end
  for j=1:2
    fa=final_factors; fb=final_factors;
    Na=c.full_p_levels(j); Nb=c.full_p_levels(j+1);
    fa.wall.endpoint_id=sprintf('final-wall-N%d',Na);
    fb.wall.endpoint_id=sprintf('final-wall-N%d',Nb);
    fa.circle.endpoint_id=sprintf('final-circle-N%d',Na);
    fb.circle.endpoint_id=sprintf('final-circle-N%d',Nb);
    fa.volume_circle.combined_endpoint_id=sprintf('final-volume-N%d',Na);
    fa.volume_wall.combined_endpoint_id=sprintf('final-volume-N%d',Na);
    fb.volume_circle.combined_endpoint_id=sprintf('final-volume-N%d',Nb);
    fb.volume_wall.combined_endpoint_id=sprintf('final-volume-N%d',Nb);
    pairs{j}=struct( ...
      'wall',LOCAL_factor_pair(c,fa.wall,fb.wall,z,Na,Nb), ...
      'circle',LOCAL_factor_pair(c,fa.circle,fb.circle,z,Na,Nb), ...
      'volume',LOCAL_combined_factor_pair(c,fa.volume_circle,fa.volume_wall, ...
        fb.volume_circle,fb.volume_wall,z,Na,Nb));
    records=LOCAL_concat(records,pairs{j}.wall.signature_parity);
    records=LOCAL_concat(records,pairs{j}.circle.signature_parity);
    records=LOCAL_concat(records,pairs{j}.volume.signature_parity);
  end
end

function [out,calls]=LOCAL_fullp_three_axis(c,z,signatures,pairs,component,calls)
  values=cell(1,3);
  for j=1:3
    sig=signatures{j};
    [values{j},calls]=LOCAL_project_components( ...
      c,z,sig,calls,'three_axis',true);
  end
  out=LOCAL_three_axis_metric(c,values, ...
    {pairs{1}.(component),pairs{2}.(component)},'fullp',component);
end

function out=LOCAL_three_axis_metric(c,values,pairs,axis,component)
  m1=LOCAL_project_pair(values{1}.(component),values{2}.(component),pairs{1});
  m2=LOCAL_project_pair(values{2}.(component),values{3}.(component),pairs{2});
  scale=max([realmin,values{1}.(component).B, ...
    values{2}.(component).B,values{3}.(component).B]);
  omega=100*values{3}.(component).augmented_length*eps*scale;
  m1.threshold=Inf; m1.absolute_threshold=Inf; m1.pass=isfinite(m1.numerator);
  m2.threshold=c.spectral_ratio_max;
  m2.absolute_threshold=max(c.spectral_ratio_max*m1.numerator,omega);
  m2.pass=isfinite(m2.numerator)&&m2.numerator<=m2.absolute_threshold;
  near=m1.value<=omega&&m2.value<=omega;
  contract=m2.value<=max(c.spectral_ratio_max*m1.value,omega);
  available=all(isfinite([m1.value,m2.value,omega]))&&(near||contract);
  if available, remainder=c.spectral_remainder_factor*max(m2.value,omega);
  else, remainder=NaN; end
  out=struct('axis',axis,'component',component,'d1',m1,'d2',m2, ...
    'omega',omega,'near_zero',near,'contraction_pass',contract, ...
    'numerator',m2.value,'scale',max(realmin,m1.value), ...
    'ratio',m2.value/max(realmin,m1.value), ...
    'threshold',c.spectral_ratio_max,'pass',available, ...
    'maximum_ratio',m2.value/max(realmin,m1.value), ...
    'remainder',remainder,'available',available, ...
    'all_projected_endpoint_parity',LOCAL_component_value_parity(values));
end

function [out,calls,gram]=LOCAL_interaction( ...
    c,z,lift,wall,circle,final_sig,final,fullp_sig,fullp_pairs,calls)
  gram=struct([]); cs=circle.cap_signatures.joint; ws=wall.cap_signatures.joint;
  repc=LOCAL_volume_circle_final_factor(z,lift,circle);
  repw=LOCAL_volume_wall_factors(z,wall.finest_factors, ...
    lift.wall_lift_weights{end}/z.gamma);
  repc.endpoint_id='representative-finest-volume-circle-N32';
  repc.combined_endpoint_id='representative-finest-volume-N32';
  repw.endpoint_id='representative-finest-volume-wall-N32';
  repw.combined_endpoint_id='representative-finest-volume-N32';
  repc16_factor=repc; repw16_factor=repw;
  repc16_factor.endpoint_id='representative-finest-volume-circle-N16';
  repw16_factor.endpoint_id='representative-finest-volume-wall-N16';
  repc16_factor.combined_endpoint_id='representative-finest-volume-N16';
  repw16_factor.combined_endpoint_id='representative-finest-volume-N16';
  repc16=LOCAL_factor_signature(c,repc16_factor.endpoint_id, ...
    'volume-circle',repc16_factor,z,16);
  repw16=LOCAL_factor_signature(c,repw16_factor.endpoint_id, ...
    'volume-wall',repw16_factor,z,16);
  [~,g]=LOCAL_combine_volume(c,'representative-finest-volume-N16', ...
    repc16,repw16,repc16_factor,repw16_factor,z,16,false, ...
    'structural-representative');
  gram=LOCAL_concat(gram,g);
  representative_pair=LOCAL_combined_factor_pair(c,repc16_factor, ...
    repw16_factor,repc,repw,z,16,32);
  representative_pair.signature_parity.actual=false;
  representative_pair.signature_parity.representative=true;
  clear repc repw repc16 repw16 repc16_factor repw16_factor;
  joint_sig.wall=ws.wall; joint_sig.circle=cs.circle;
  [joint_sig.volume,g]=LOCAL_combine_volume(c,'joint-volume', ...
    cs.volume_circle,ws.volume_wall,[],[],z,16,false,'joint-producer');
  gram=LOCAL_concat(gram,g);
  [joint,calls]=LOCAL_project_components(c,z,joint_sig,calls,'interaction',true);
  joint_pairs.wall=ws.pair_to_final.wall;
  joint_pairs.circle=cs.pair_to_final.circle;
  joint_pairs.volume=LOCAL_combine_pair( ...
    cs.pair_to_final.volume_circle,ws.pair_to_final.volume_wall);
  names={'wall','circle','volume'}; lhs=0; scale=realmin;
  joint_metrics=struct();
  for j=1:3
    name=names{j};
    joint_metrics.(name)=LOCAL_project_pair(joint.(name), ...
      final.(name),joint_pairs.(name));
    lhs=lhs+joint_metrics.(name).factor_shift;
    scale=max(scale,final.(name).B);
  end

  legs=cell(1,6); pairs=cell(1,6); affected={ ...
    {'circle','volume'},{'circle','volume'},{'wall','volume'}, ...
    {'circle'},{'volume'},{'wall','circle','volume'}};
  [sig,~]=LOCAL_existing_choice(c,z,wall,circle,6,3,3,32);
  [legs{1},calls]=LOCAL_project_components(c,z,sig,calls,'interaction',true);
  pairs{1}=struct('circle',circle.cap_signatures.image_pairs{5}.circle, ...
    'volume',LOCAL_combine_pair( ...
    circle.cap_signatures.image_pairs{5}.volume_circle, ...
    LOCAL_zero_pair_like(wall.cap_signatures.output_pairs{2}.volume_wall, ...
      wall.cap_signatures.output{3}.volume_wall.endpoint_id)));

  [sig,~]=LOCAL_existing_choice(c,z,wall,circle,0,2,3,32);
  [legs{2},calls]=LOCAL_project_components(c,z,sig,calls,'interaction',true);
  pairs{2}=struct('circle',circle.cap_signatures.angular_pairs{2}.circle, ...
    'volume',LOCAL_combine_pair( ...
    circle.cap_signatures.angular_pairs{2}.volume_circle, ...
    LOCAL_zero_pair_like(wall.cap_signatures.output_pairs{2}.volume_wall, ...
      wall.cap_signatures.output{3}.volume_wall.endpoint_id)));

  [sig,~]=LOCAL_existing_choice(c,z,wall,circle,0,3,2,32);
  [legs{3},calls]=LOCAL_project_components(c,z,sig,calls,'interaction',true);
  pairs{3}=struct('wall',wall.cap_signatures.output_pairs{2}.wall, ...
    'volume',LOCAL_combine_pair( ...
    LOCAL_zero_pair_like(circle.cap_signatures.angular_pairs{2}.volume_circle, ...
      circle.cap_signatures.angular{3}.volume_circle.endpoint_id), ...
    wall.cap_signatures.output_pairs{2}.volume_wall));

  bc=lift.circle_weights{2}; rf=struct('minus',LOCAL_weight_rows( ...
    circle.finest_factors.jump_minus,1./sqrt(bc)), ...
    'plus',LOCAL_weight_rows(circle.finest_factors.jump_plus,1./sqrt(bc)), ...
    'center',zeros(0,1),'endpoint_id','riccati-leg-circle');
  sig=final_sig; sig.circle=LOCAL_factor_signature(c,'riccati-leg-circle', ...
    'circle',rf,z,32);
  [legs{4},calls]=LOCAL_project_components(c,z,sig,calls,'interaction',true);
  ff=LOCAL_circle_final_factor(lift,circle);
  ff.endpoint_id='final-circle';
  pairs{4}=struct('circle',LOCAL_factor_pair(c,rf,ff,z,32,32));
  clear rf ff;

  cv=lift.collar_weights{2}/z.gamma;
  wv=lift.wall_lift_weights{2}/z.gamma;
  gc=struct('minus',LOCAL_weight_rows(circle.finest_factors.delta_minus,sqrt(cv)), ...
    'plus',LOCAL_weight_rows(circle.finest_factors.delta_plus,sqrt(cv)), ...
    'center',zeros(0,1));
  gw=LOCAL_volume_wall_factors(z,wall.finest_factors,wv);
  gc.endpoint_id='gauss-leg-volume-circle';
  gc.combined_endpoint_id='gauss-leg-volume';
  gw.endpoint_id='gauss-leg-volume-wall';
  gw.combined_endpoint_id='gauss-leg-volume';
  sc=LOCAL_factor_signature(c,'gauss-leg-volume-circle','volume-circle',gc,z,32);
  sw=LOCAL_factor_signature(c,'gauss-leg-volume-wall','volume-wall',gw,z,32);
  [sig.volume,g]=LOCAL_combine_volume(c,'gauss-leg-volume',sc,sw, ...
    gc,gw,z,32,true,'actual-interaction-leg');
  gram=LOCAL_concat(gram,g); sig.wall=final_sig.wall; sig.circle=final_sig.circle;
  [legs{5},calls]=LOCAL_project_components(c,z,sig,calls,'interaction',true);
  fcfinal=LOCAL_volume_circle_final_factor(z,lift,circle);
  fwfinal=LOCAL_volume_wall_factors(z,wall.finest_factors, ...
    lift.wall_lift_weights{end}/z.gamma);
  fcfinal.endpoint_id='final-volume-circle';
  fcfinal.combined_endpoint_id='final-volume';
  fwfinal.endpoint_id='final-volume-wall';
  fwfinal.combined_endpoint_id='final-volume';
  pairs{5}=struct('volume',LOCAL_combined_factor_pair( ...
    c,gc,gw,fcfinal,fwfinal,z,32,32));
  clear gc gw sc sw fcfinal fwfinal;

  sig=fullp_sig{2};
  [legs{6},calls]=LOCAL_project_components(c,z,sig,calls,'interaction',true);
  pairs{6}=fullp_pairs{2};

  finallegs=0; leg_metrics=cell(1,6);
  for a=1:6
    leg_metrics{a}=struct();
    for j=1:numel(affected{a})
      name=affected{a}{j}; metric=LOCAL_project_pair( ...
        legs{a}.(name),final.(name),pairs{a}.(name));
      leg_metrics{a}.(name)=metric; finallegs=finallegs+metric.factor_shift;
    end
  end
  omega=100*(final.wall.augmented_length+final.circle.augmented_length+ ...
    final.volume.augmented_length)*eps*scale;
  out=struct('joint_shift',lhs,'official_final_leg_sum',finallegs, ...
    'omega',omega,'numerator',lhs,'scale',max(realmin,finallegs+omega), ...
    'ratio',lhs/max(realmin,finallegs+omega),'threshold',1, ...
    'pass',isfinite(lhs)&&lhs<=finallegs+omega, ...
    'joint_metrics',joint_metrics,'official_leg_metrics',{leg_metrics}, ...
    'all_projected_endpoint_parity', ...
      LOCAL_component_value_parity([{joint},legs]), ...
    'representative_finest_N16_to_N32_signature_parity', ...
      representative_pair.signature_parity, ...
    'joint_actual_producer_parity',true, ...
    'combined_joint_end_to_end_representative_only',true);
end

function out=LOCAL_circle_final_factor(lift,circle)
  bc=lift.circle_weights{end};
  out=struct('minus',LOCAL_weight_rows( ...
    circle.finest_factors.jump_minus,1./sqrt(bc)), ...
    'plus',LOCAL_weight_rows(circle.finest_factors.jump_plus,1./sqrt(bc)), ...
    'center',zeros(0,1));
end

function out=LOCAL_volume_circle_final_factor(z,lift,circle)
  cv=lift.collar_weights{end}/z.gamma;
  out=struct('minus',LOCAL_weight_rows(circle.finest_factors.delta_minus,sqrt(cv)), ...
    'plus',LOCAL_weight_rows(circle.finest_factors.delta_plus,sqrt(cv)), ...
    'center',zeros(0,1));
end

%% ==================== Fourier shells ====================
% Each masked finest factor is projected and cleared before the next family.

function [out,warnings,calls,gram]= ...
    LOCAL_shells(c,z,lift,wall,circle,calls)
  warnings=LOCAL_empty_warnings(); gram=struct([]);
  [out.circle_circle,calls,g]=LOCAL_shell_family( ...
    c,z,lift,wall,circle,'circle','circle',calls); gram=LOCAL_concat(gram,g);
  [out.circle_volume,calls,g]=LOCAL_shell_family( ...
    c,z,lift,wall,circle,'circle','volume',calls); gram=LOCAL_concat(gram,g);
  [out.wall_wall,calls,g]=LOCAL_shell_family( ...
    c,z,lift,wall,circle,'wall','wall',calls); gram=LOCAL_concat(gram,g);
  [out.wall_volume,calls,g]=LOCAL_shell_family( ...
    c,z,lift,wall,circle,'wall','volume',calls); gram=LOCAL_concat(gram,g);
  names=fieldnames(out);
  for j=1:numel(names)
    if ~out.(names{j}).available
      warnings(end+1)=LOCAL_warning('FOURIER_TAIL_EMPIRICALLY_UNRESOLVED', ...
        out.(names{j}).ratio); %#ok<AGROW>
    end
  end
end

function [out,calls,gram]=LOCAL_shell_family( ...
    c,z,lift,wall,circle,family,component,calls)
  if strcmp(family,'circle'), bands=[512,1024;1024,2048];
  else, bands=[1024,2048;2048,4096]; end
  values=cell(1,2); gram=struct([]);
  for j=1:2
    [f,label]=LOCAL_shell_factor(z,lift,wall,circle,family,component, ...
      bands(j,1),bands(j,2));
    sig=LOCAL_factor_signature(c,label,component,f,z,32);
    if strcmp(component,'volume')
      empty=struct('minus',zeros(0,size(f.minus,2)), ...
        'plus',zeros(0,size(f.plus,2)),'center',zeros(0,1));
      gram=LOCAL_concat(gram,LOCAL_gram_parity(label,'minus', ...
        f.minus,empty.minus,sig.minus.W,true,'actual-shell'));
      gram=LOCAL_concat(gram,LOCAL_gram_parity(label,'plus', ...
        f.plus,empty.plus,sig.plus.W,true,'actual-shell'));
    end
    [values{j},calls]=LOCAL_project_endpoint( ...
      c,z,sig,calls,'shell',true); clear f sig;
  end
  S1=values{1}.B; S2=values{2}.B; scale=max([realmin,S1,S2]);
  omega=100*(values{1}.augmented_length+values{2}.augmented_length)*eps*scale;
  near=S1<=omega&&S2<=omega; pass=near||S2<=max(.5*S1,omega);
  if pass, allowance=2*max(S2,omega); else, allowance=NaN; end
  out=struct('family',family,'component',component,'shell_1',S1, ...
    'shell_2',S2,'omega',omega,'near_zero',near,'contraction_pass',pass, ...
    'shell_1_metric',LOCAL_scalar_metric(S1,realmin,Inf,isfinite(S1)), ...
    'shell_2_metric',LOCAL_scalar_metric(S2,max(realmin,S1),.5,pass), ...
    'numerator',S2,'scale',max(realmin,S1), ...
    'ratio',S2/max(realmin,S1),'threshold',.5,'pass',pass, ...
    'allowance',allowance,'available',pass, ...
    'center_QZ_value_mismatch_shell_structural_zero', ...
      strcmp(family,'wall')&&strcmp(component,'volume'), ...
    'center_QZ_source_bandwidth','I_512 contained in I_1024', ...
    'endpoint_parity',{{values{1}.signature.signature_parity, ...
      values{2}.signature.signature_parity}});
end

function [f,label]=LOCAL_shell_factor(z,lift,wall,circle,family,component,inner,outer)
  if strcmp(family,'circle')
    orders=(-1024:1023).'; mask=LOCAL_shell_mask(orders,inner,outer);
    if strcmp(component,'circle')
      weight=lift.circle_weights{end}(mask);
      f=struct('minus',LOCAL_weight_rows(circle.jump_minus(mask,:),1./sqrt(weight)), ...
        'plus',LOCAL_weight_rows(circle.jump_plus(mask,:),1./sqrt(weight)), ...
        'center',zeros(0,1));
    else
      weight=lift.collar_weights{end}(mask)/z.gamma;
      f=struct('minus',LOCAL_weight_rows(circle.delta_minus(mask,:),sqrt(weight)), ...
        'plus',LOCAL_weight_rows(circle.delta_plus(mask,:),sqrt(weight)), ...
        'center',zeros(0,1));
    end
  else
    orders=(-2048:2047).'; mask=LOCAL_shell_mask(orders,inner,outer);
    if strcmp(component,'wall')
      weight=lift.wall_trace(mask);
      f=struct('minus',LOCAL_weight_rows(wall.normal_minus(mask,:),1./sqrt(weight)), ...
        'plus',LOCAL_weight_rows(wall.normal_plus(mask,:),1./sqrt(weight)), ...
        'center',[wall.center_wall.left(mask)./sqrt(weight); ...
          wall.center_wall.right(mask)./sqrt(weight)]);
    else
      weight=lift.wall_lift_weights{end}(mask)/z.gamma;
      DLp=LOCAL_weight_rows(wall.defect_left_plus(mask,:),sqrt(weight));
      DRp=LOCAL_weight_rows(wall.defect_right_plus(mask,:),sqrt(weight));
      DLm=LOCAL_weight_rows(wall.defect_left_minus(mask,:),sqrt(weight));
      DRm=LOCAL_weight_rows(wall.defect_right_minus(mask,:),sqrt(weight));
      f=struct('minus',[DLm;DRm*z.Pminus], ...
        'plus',[DRp;DLp*z.Pplus], ...
        'center',[DLp*z.cplus;DRm*z.cminus]);
    end
  end
  label=sprintf('shell-%s-%s-%d-%d',family,component,inner,outer);
end

function mask=LOCAL_shell_mask(orders,innerN,outerN)
  outer=orders>=-outerN/2&orders<=outerN/2-1;
  inner=orders>=-innerN/2&orders<=innerN/2-1;
  mask=outer&~inner;
  if ~any(mask), error('i32f:FourierShell','A required Fourier shell is empty.'); end
end

function out=LOCAL_scalar_metric(numerator,scale,threshold,pass)
  out=struct('numerator',numerator,'left_norm',0,'right_norm',numerator, ...
    'zero_component',numerator==0,'scale',scale, ...
    'ratio',numerator/max(realmin,scale),'threshold',threshold, ...
    'pass',logical(pass));
end

%% ==================== Arithmetic, cap, and field ledgers ====================
% Direct, Gram, and compensated paths remain separately recorded.

function [out,warnings]=LOCAL_arithmetic(c,final)
  warnings=LOCAL_empty_warnings(); names={'wall','circle','volume'};
  for j=1:3
    name=names{j}; item=final.(name); tail=item.tail;
    gram_squared=tail.center_squared+tail.minus.finite_partial+ ...
      tail.plus.finite_partial+tail.minus.value+tail.plus.value;
    scale_squared=max([realmin,item.B^2,abs(gram_squared)]);
    significant=gram_squared<-100*eps*scale_squared;
    if gram_squared<0&&~significant, gram_squared=0; end
    terms=[tail.center_squared;tail.direct_minus_squares;tail.minus.value; ...
      tail.direct_plus_squares;tail.plus.value];
    compensated_squared=LOCAL_compensated_sum(terms);
    compensated_tolerance=100*eps*max([realmin,abs(terms(:).')]);
    compensated_negative=compensated_squared<-compensated_tolerance;
    if compensated_squared<0&&~compensated_negative, compensated_squared=0; end
    paths=[item.B,sqrt(gram_squared),sqrt(compensated_squared)];
    spread=max(paths)-min(paths); scale=max([realmin,paths]);
    nops=4*item.augmented_length+16; omega=100*nops*eps*scale;
    pass=~significant&&~compensated_negative&&all(isfinite(paths))&& ...
      isreal(paths)&&spread<=omega;
    out.(name)=struct('paths',paths,'maximum_pairwise_spread',spread, ...
      'operations',nops,'component_scale',scale,'omega',omega, ...
      'numerator',spread,'scale',max(realmin,omega), ...
      'ratio',spread/max(realmin,omega),'threshold',1,'pass',pass, ...
      'compensated_squared',compensated_squared, ...
      'compensated_negative_significant',compensated_negative, ...
      'remainder',2*max(spread,omega),'available',pass);
    if ~pass
      warnings(end+1)=LOCAL_warning( ...
        'COMPONENT_ARITHMETIC_EMPIRICALLY_UNRESOLVED', ...
        spread/max(realmin,omega)); %#ok<AGROW>
    end
  end
end

function value=LOCAL_compensated_sum(terms)
  value=0; correction=0;
  for j=1:numel(terms)
    y=terms(j)-correction; updated=value+y;
    correction=(updated-value)-y; value=updated;
  end
end

function out=LOCAL_component_caps(anchor,axes,shells,arith)
  out.wall=LOCAL_one_cap(anchor.wall,{axes.wall_wall,axes.fullp_wall}, ...
    shells.wall_wall,arith.wall);
  out.circle=LOCAL_one_cap(anchor.circle,{axes.image_circle, ...
    axes.angular_circle,axes.riccati_circle,axes.fullp_circle}, ...
    shells.circle_circle,arith.circle);
  volume_shell=struct('available',shells.circle_volume.available&& ...
    shells.wall_volume.available,'allowance', ...
    shells.circle_volume.allowance+shells.wall_volume.allowance);
  out.volume=LOCAL_one_cap(anchor.volume,{axes.image_volume, ...
    axes.angular_volume,axes.wall_volume,axes.gauss_volume,axes.fullp_volume}, ...
    volume_shell,arith.volume);
end

function out=LOCAL_one_cap(anchor,axes,shell,arith)
  axis_sum=0; available=anchor.available&&shell.available&&arith.available;
  records=cell(1,numel(axes));
  for j=1:numel(axes)
    records{j}=axes{j}; available=available&&axes{j}.available;
    if axes{j}.available, axis_sum=axis_sum+axes{j}.remainder; end
  end
  if available
    epsilon=anchor.A+axis_sum+shell.allowance+arith.remainder;
  else, epsilon=NaN; end
  out=struct('available',available,'anchor',anchor,'axes',{records}, ...
    'axis_remainder_sum',axis_sum,'fourier_tail_allowance',shell.allowance, ...
    'arithmetic_remainder',arith.remainder,'epsilon_emp',epsilon);
end

function [out,warnings,calls]=LOCAL_field_cap(c,s,calls)
  warnings=LOCAL_empty_warnings(); z=s.certificate;
  bm=z.beta+2*pi*(-256:255).'/z.d; kappa=sqrt(bm.^2+z.gamma);
  bw=2*kappa.*tanh(kappa/2); retained=abs((-256:255).')<=z.M;
  center=sum(bw(retained).*abs(z.center_shared_left_trace(retained,:)).^2,'all')+ ...
    sum(bw(retained).*abs(z.center_shared_right_trace(retained,:)).^2,'all');
  Hm=s.ordinary_anchor.lead_field_factor_minus;
  Hp=s.ordinary_anchor.lead_field_factor_plus;
  Nm=round(s.ordinary_anchor.tail_minus.selected_N);
  Np=round(s.ordinary_anchor.tail_plus.selected_N);
  same=center+LOCAL_partial(Hm,z.Pminus,z.cminus,Nm)+ ...
    LOCAL_partial(Hp,z.Pplus,z.cplus,Np);
  anchor=s.ordinary_anchor.N_tilde; observed=max(0,anchor-same);
  absolute=abs(anchor-same); ncmp=4*(numel(Hm)+numel(Hp))+64;
  omega_cmp=100*ncmp*eps*max([realmin,abs(anchor),abs(same)]);
  paths=[same,LOCAL_field_gram(center,Hm,Hp,z,Nm,Np), ...
    LOCAL_field_compensated(center,Hm,Hp,z,Nm,Np)];
  spread=max(paths)-min(paths); nops=4*(numel(Hm)+numel(Hp))+64;
  omega=100*nops*eps*max([realmin,abs(paths)]); arithmetic=spread<=omega;
  growth=zeros(1,3);
  for j=1:3
    N=c.full_p_levels(j);
    growth(j)=center+LOCAL_partial(Hm,z.Pminus,z.cminus,N)+ ...
      LOCAL_partial(Hp,z.Pplus,z.cplus,N);
  end
  calls=LOCAL_category_increment(calls,'field',12);
  epsilon=observed+omega_cmp+2*max(spread,omega);
  tolerance=100*z.K*eps*max([realmin,abs(growth)]);
  increments=diff(growth); direction=all(increments>=-tolerance);
  available=all(isfinite([same,paths,epsilon,growth]))&&arithmetic&&direction&& ...
    anchor-epsilon>0;
  if ~arithmetic
    warnings(end+1)=LOCAL_warning('FIELD_ARITHMETIC_EMPIRICALLY_UNRESOLVED', ...
      spread/max(realmin,omega)); %#ok<AGROW>
  end
  if ~direction
    warnings(end+1)=LOCAL_warning('FIELD_PARTIAL_DIRECTION_UNRESOLVED', ...
      max(-increments/max(realmin,tolerance))); %#ok<AGROW>
  end
  out=struct('available',available,'artifact_N_tilde',anchor, ...
    'same_partial',same,'absolute_discrepancy',absolute, ...
    'downward_observed',observed,'comparison_operations',ncmp, ...
    'comparison_omega',omega_cmp,'arithmetic_paths',paths, ...
    'arithmetic_spread',spread,'arithmetic_operations',nops, ...
    'arithmetic_omega',omega,'R_N',2*max(spread,omega), ...
    'epsilon_N_emp',epsilon,'growth_N',[8,16,32], ...
    'growth_values',growth,'growth_increments',increments, ...
    'growth_roundoff_tolerance',tolerance, ...
    'growth_is_diagnostic_only',true, ...
    'omitted_positive_tail_added_to_cap',false, ...
    'dependency_audit',struct('same_partial_only',true, ...
      'structural_zero_axes_proved',true, ...
      'evaluator_boundary_actions_consumed',false));
end

function value=LOCAL_partial(H,P,c0,N)
  value=0; state=c0;
  for j=1:N, value=value+norm(H*state)^2; state=P*state; end
end

function value=LOCAL_field_gram(center,Hm,Hp,z,Nm,Np)
  value=center+LOCAL_quadratic_sum(Hm'*Hm,z.Pminus,z.cminus,Nm)+ ...
    LOCAL_quadratic_sum(Hp'*Hp,z.Pplus,z.cplus,Np);
end

function value=LOCAL_quadratic_sum(W,P,c0,N)
  value=0; state=c0;
  for j=1:N, value=value+real(state'*W*state); state=P*state; end
end

function value=LOCAL_field_compensated(center,Hm,Hp,z,Nm,Np)
  terms=center; state=z.cminus;
  for j=1:Nm
    terms(end+1)=norm(Hm*state)^2; state=z.Pminus*state; %#ok<AGROW>
  end
  state=z.cplus;
  for j=1:Np
    terms(end+1)=norm(Hp*state)^2; state=z.Pplus*state; %#ok<AGROW>
  end
  value=LOCAL_compensated_sum(terms);
end

function out=LOCAL_caps(s,components,field,numok,denok)
  if numok
    eW=components.wall.epsilon_emp; eG=components.circle.epsilon_emp;
    eV=components.volume.epsilon_emp; eM=eW+eG+eV;
  else, eW=NaN; eG=NaN; eV=NaN; eM=NaN; end
  if denok, eN=field.epsilon_N_emp; else, eN=NaN; end
  out=struct('M_tilde',s.ordinary_anchor.M_tilde, ...
    'N_tilde',s.ordinary_anchor.N_tilde,'epsilon_W_emp',eW, ...
    'epsilon_Gamma_emp',eG,'epsilon_V_emp',eV, ...
    'epsilon_M_emp',eM,'epsilon_N_emp',eN, ...
    'numerator_triangle_combination',true, ...
    'same_trial_evaluation_cap',numok&&denok, ...
    'rigorous_cap',false,'directed_rounding',false);
end

function out=LOCAL_estimator(s,c,caps,numok,denok)
  q=NaN; lambda=[NaN,NaN]; kval=lambda; width=NaN;
  available=numok&&denok&&isfinite(caps.epsilon_M_emp)&& ...
    isfinite(caps.epsilon_N_emp)&&caps.N_tilde-caps.epsilon_N_emp>0;
  if available
    q=(caps.M_tilde+caps.epsilon_M_emp)/ ...
      sqrt(caps.N_tilde-caps.epsilon_N_emp);
    if q<1
      mu=s.certificate.mu_h; gamma=s.certificate.gamma;
      lambda=[max(0,(mu-q*gamma)/(1+q)),(mu+q*gamma)/(1-q)];
      kval=sqrt(lambda); width=diff(kval);
    end
  end
  out=struct('available',available,'q_emp',q, ...
    'interval_available',available&&q<1,'lambda_lower',lambda(1), ...
    'lambda_upper',lambda(2),'k_lower',kval(1),'k_upper',kval(2), ...
    'width',width,'width_target',c.width_target, ...
    'resolution_pass',available&&q<1&&width<=c.width_target, ...
    'label','EMPIRICAL_NOMINAL_TRANSFORM','ordinary_double',true, ...
    'strict_conditional_theorem_triggered',false,'reliable',false);
end

%% ==================== Qualification, parity, and audit ====================
% Typed scientific failures remain nonblocking execution diagnostics.

function out=LOCAL_component_value_parity(values)
  records=struct([]);
  for j=1:numel(values)
    value=values{j}; names={'wall','circle','volume'};
    for k=1:3
      records=LOCAL_concat(records,value.(names{k}).signature.signature_parity);
    end
  end
  out=LOCAL_parity_summary(records);
end

function out=LOCAL_producer_parity(wall,circle)
  records=LOCAL_concat(wall.public_metrics.producer_signature_parity.records, ...
    circle.public_metrics.producer_signature_parity.records);
  out=LOCAL_parity_summary(records);
  out.wall_coverage=wall.public_metrics.producer_signature_parity.coverage;
  out.circle_coverage=circle.public_metrics.producer_signature_parity.coverage;
  out.pass=out.pass&&out.wall_coverage.pass&&out.circle_coverage.pass;
end

function out=LOCAL_collect_endpoint_parity(varargin)
  records=struct([]);
  for j=1:nargin
    records=LOCAL_concat(records,LOCAL_recursive_parity(varargin{j}));
  end
  records=LOCAL_filter_cap_records(records);
  out=LOCAL_parity_summary(records);
  out.coverage=LOCAL_validate_parity_coverage(out.records, ...
    LOCAL_expected_cap_parity());
  out.pass=out.pass&&out.coverage.pass;
end

function records=LOCAL_recursive_parity(value)
  records=struct([]);
  if iscell(value)
    for j=1:numel(value)
      records=LOCAL_concat(records,LOCAL_recursive_parity(value{j}));
    end
  elseif isstruct(value)
    if isscalar(value)&&all(isfield(value, ...
        {'coverage_class','n_op','pass','numerator'}))
      records=value; return;
    end
    for k=1:numel(value)
      names=fieldnames(value(k));
      for j=1:numel(names)
        records=LOCAL_concat(records, ...
          LOCAL_recursive_parity(value(k).(names{j})));
      end
    end
  end
end

function out=LOCAL_join_parity(a,b)
  out=LOCAL_parity_summary(LOCAL_concat(a.records,b.records));
  out.producer_required_count=a.required_count;
  out.cap_required_count=b.coverage.required_count;
  out.cap_observed_unique_count=b.required_count;
  out.producer_coverage_pass=a.pass;
  out.cap_coverage=b.coverage;
  out.pass=out.pass&&a.pass&&b.pass;
end

function out=LOCAL_parity_summary(records)
  records=LOCAL_unique_parity(records);
  if isempty(records)
    out=struct('records',records,'required_count',0,'pass',false, ...
      'total_operations',0,'maximum_allowance_ratio',Inf); return;
  end
  out=struct('records',records,'required_count',numel(records), ...
    'pass',all([records.pass]),'total_operations',sum([records.n_op]), ...
    'maximum_allowance_ratio',max([records.ratio]));
end

function out=LOCAL_gram_parity_summary(records)
  coverage=LOCAL_validate_gram_coverage(records,LOCAL_expected_gram_parity());
  if isempty(records)
    out=struct('records',records,'required_count',0,'pass',false, ...
      'total_operations',0,'maximum_allowance_ratio',Inf, ...
      'actual_count',0,'representative_count',0,'coverage',coverage); return;
  end
  out=struct('records',records,'required_count',numel(records), ...
    'pass',all([records.pass])&&coverage.pass, ...
    'total_operations',sum([records.n_gram]), ...
    'maximum_allowance_ratio',max([records.ratio]), ...
    'actual_count',sum([records.actual]), ...
    'representative_count',sum([records.representative]), ...
    'coverage',coverage);
end

function expected=LOCAL_expected_gram_parity()
  rows={ ...
    'final-volume','minus','actual-final',true,false; ...
    'final-volume','plus','actual-final',true,false; ...
    'artifact-volume','minus','actual-artifact',true,false; ...
    'artifact-volume','plus','actual-artifact',true,false; ...
    'gauss-volume-1','minus','actual-gauss-axis',true,false; ...
    'gauss-volume-1','plus','actual-gauss-axis',true,false; ...
    'gauss-volume-2','minus','actual-gauss-axis',true,false; ...
    'gauss-volume-2','plus','actual-gauss-axis',true,false; ...
    'gauss-volume-3','minus','actual-gauss-axis',true,false; ...
    'gauss-volume-3','plus','actual-gauss-axis',true,false; ...
    'final-volume-N32','minus','actual-fullp-final',true,false; ...
    'final-volume-N32','plus','actual-fullp-final',true,false; ...
    'representative-finest-volume-N16','minus', ...
      'structural-representative',false,true; ...
    'representative-finest-volume-N16','plus', ...
      'structural-representative',false,true; ...
    'gauss-leg-volume','minus','actual-interaction-leg',true,false; ...
    'gauss-leg-volume','plus','actual-interaction-leg',true,false; ...
    'shell-circle-volume-512-1024','minus','actual-shell',true,false; ...
    'shell-circle-volume-512-1024','plus','actual-shell',true,false; ...
    'shell-circle-volume-1024-2048','minus','actual-shell',true,false; ...
    'shell-circle-volume-1024-2048','plus','actual-shell',true,false; ...
    'shell-wall-volume-1024-2048','minus','actual-shell',true,false; ...
    'shell-wall-volume-1024-2048','plus','actual-shell',true,false; ...
    'shell-wall-volume-2048-4096','minus','actual-shell',true,false; ...
    'shell-wall-volume-2048-4096','plus','actual-shell',true,false};
  expected=cell2struct(rows, ...
    {'label','side','object_class','actual','representative'},2);
end

function out=LOCAL_validate_gram_coverage(records,expected)
  observed=false(numel(expected),1); duplicates=false(numel(expected),1);
  expected_record=false(1,numel(records));
  for j=1:numel(expected)
    hit=find(strcmp({records.label},expected(j).label)& ...
      strcmp({records.side},expected(j).side)& ...
      strcmp({records.object_class},expected(j).object_class)& ...
      [records.actual]==expected(j).actual& ...
      [records.representative]==expected(j).representative);
    observed(j)=numel(hit)==1; duplicates(j)=numel(hit)>1;
    expected_record(hit)=true;
  end
  out=struct('expected',expected,'required_count',numel(expected), ...
    'observed_exactly_once',observed,'duplicate_expected',duplicates, ...
    'missing_count',sum(~observed),'duplicate_count',sum(duplicates), ...
    'unexpected_count',sum(~expected_record),'empty_records',isempty(records), ...
    'pass',~isempty(records)&&all(observed)&&~any(duplicates)&& ...
      all(expected_record)&&numel(records)==numel(expected));
end

function records=LOCAL_filter_cap_records(records)
  if isempty(records), return; end
  keep=true(1,numel(records));
  for j=1:numel(records)
    keep(j)=~startsWith(records(j).coverage_class,'producer_')&& ...
      ~strcmp(records(j).coverage_class,'unchanged-family');
  end
  records=records(keep);
end

function records=LOCAL_unique_parity(records)
  if isempty(records), return; end
  keys=cell(1,numel(records));
  for j=1:numel(records)
    keys{j}=sprintf('%s|%s|%d|%d',records(j).label, ...
      records(j).coverage_class,records(j).actual,records(j).representative);
  end
  [~,first]=unique(keys,'stable'); records=records(first);
end

function expected=LOCAL_expected_cap_parity()
  rows={ ...
    'final-wall','cap_actual_endpoint_augmented',true,false; ...
    'final-circle','cap_actual_endpoint_augmented',true,false; ...
    'final-volume','combined_volume_augmented',true,false; ...
    'shell-circle-circle-512-1024','cap_actual_endpoint_augmented',true,false; ...
    'shell-circle-circle-1024-2048','cap_actual_endpoint_augmented',true,false; ...
    'shell-circle-volume-512-1024','cap_actual_endpoint_augmented',true,false; ...
    'shell-circle-volume-1024-2048','cap_actual_endpoint_augmented',true,false; ...
    'shell-wall-wall-1024-2048','cap_actual_endpoint_augmented',true,false; ...
    'shell-wall-wall-2048-4096','cap_actual_endpoint_augmented',true,false; ...
    'shell-wall-volume-1024-2048','cap_actual_endpoint_augmented',true,false; ...
    'shell-wall-volume-2048-4096','cap_actual_endpoint_augmented',true,false; ...
    'final-wall-N8','cap_actual_endpoint_augmented',true,false; ...
    'final-circle-N8','cap_actual_endpoint_augmented',true,false; ...
    'final-volume-N8','combined_volume_augmented',true,false; ...
    'final-wall-N16','cap_actual_endpoint_augmented',true,false; ...
    'final-circle-N16','cap_actual_endpoint_augmented',true,false; ...
    'final-volume-N16','combined_volume_augmented',true,false; ...
    'final-wall-N32','cap_actual_endpoint_augmented',true,false; ...
    'final-circle-N32','cap_actual_endpoint_augmented',true,false; ...
    'final-volume-N32','combined_volume_augmented',true,false; ...
    'final-wall-N8->final-wall-N16','cap_actual_pair_augmented',true,false; ...
    'final-circle-N8->final-circle-N16','cap_actual_pair_augmented',true,false; ...
    'final-volume-N8->final-volume-N16','combined_volume_actual_pair_augmented',true,false; ...
    'final-wall-N16->final-wall-N32','cap_actual_pair_augmented',true,false; ...
    'final-circle-N16->final-circle-N32','cap_actual_pair_augmented',true,false; ...
    'final-volume-N16->final-volume-N32','combined_volume_actual_pair_augmented',true,false; ...
    'representative-finest-volume-N16->representative-finest-volume-N32', ...
      'combined_volume_actual_pair_augmented',false,true};
  expected=cell2struct(rows,{'label','coverage_class','actual','representative'},2);
end

function out=LOCAL_validate_parity_coverage(records,expected)
  observed=false(numel(expected),1); duplicates=false(numel(expected),1);
  expected_record=false(1,numel(records));
  for j=1:numel(expected)
    hit=find(strcmp({records.label},expected(j).label)& ...
      strcmp({records.coverage_class},expected(j).coverage_class)& ...
      [records.actual]==expected(j).actual& ...
      [records.representative]==expected(j).representative);
    observed(j)=numel(hit)==1; duplicates(j)=numel(hit)>1;
    expected_record(hit)=true;
  end
  out=struct('expected',expected,'required_count',numel(expected), ...
    'observed_exactly_once',observed,'duplicate_expected',duplicates, ...
    'missing_count',sum(~observed),'duplicate_count',sum(duplicates), ...
    'unexpected_count',sum(~expected_record),'empty_records',isempty(records), ...
    'pass',~isempty(records)&&all(observed)&&~any(duplicates)&& ...
      all(expected_record)&&numel(records)==numel(expected));
end

function out=LOCAL_qualification(wall,circle,signature,gram)
  cp=circle.public_metrics;
  out=struct('kernel_oracle_available',cp.kernel_oracles_available, ...
    'kernel_qualified',cp.kernel_qualified, ...
    'conformity_qualified',cp.conformity_qualified&& ...
      wall.public_metrics.repaired_value_qualified, ...
    'actual_T_qualified',cp.actual_T_action_qualified, ...
    'finite_bloch_qualified',cp.finite_image_Bloch_qualified, ...
    'signature_parity_qualified',signature.pass, ...
    'combined_gram_parity_qualified',gram.pass);
end

function out=LOCAL_first_unavailable(components,axes,shells,arithmetic,state, ...
    q,signature,gram)
  if ~q.kernel_oracle_available
    out=LOCAL_condition('KERNEL_ORACLE_UNAVAILABLE', ...
      'A required analytic kernel oracle is numerically unavailable.'); return;
  elseif ~q.kernel_qualified
    out=LOCAL_condition('KERNEL_ORACLE_EMPIRICALLY_UNRESOLVED', ...
      'A preregistered analytic kernel oracle failed qualification.'); return;
  elseif ~q.conformity_qualified
    out=LOCAL_condition('SAME_TRIAL_CONFORMITY_EMPIRICALLY_UNRESOLVED', ...
      'A repaired-trace identity failed qualification.'); return;
  elseif ~q.actual_T_qualified
    out=LOCAL_condition('ACTUAL_DELTA_T_ACTION_EMPIRICALLY_UNRESOLVED', ...
      'The fixed-density Delta-T action ladder failed qualification.'); return;
  elseif ~q.finite_bloch_qualified
    out=LOCAL_condition('FINITE_IMAGE_BLOCH_EMPIRICALLY_UNRESOLVED', ...
      'The finite-image Bloch action failed qualification.'); return;
  elseif ~signature.pass
    out=LOCAL_condition('SIGNATURE_PARITY_UNRESOLVED', ...
      'A required compact-signature arithmetic parity gate failed.'); return;
  elseif ~gram.pass
    out=LOCAL_condition('COMBINED_GRAM_PARITY_UNRESOLVED', ...
      'A required stacked-versus-summed volume Gram parity gate failed.'); return;
  end
  names={'wall','circle','volume'};
  for j=1:3
    if ~components.(names{j}).available
      out=LOCAL_condition('EMPIRICAL_COMPONENT_CAP_UNRESOLVED', ...
        ['The ',names{j},' component cap is unresolved.']); return;
    end
  end
  if ~axes.interaction.pass
    out=LOCAL_condition('AXIS_INTERACTION_EMPIRICALLY_UNRESOLVED', ...
      'The joint holdout exceeds the final-leg ledger.'); return;
  end
  if ~state.available
    out=LOCAL_condition('MANDATORY_STATE_TAIL_UNAVAILABLE', ...
      'The mandatory W=I full-P state tail is unavailable.'); return;
  end
  if any(~structfun(@(x) x.available,shells))
    out=LOCAL_condition('FOURIER_TAIL_EMPIRICALLY_UNRESOLVED', ...
      'A preregistered Fourier shell is unresolved.'); return;
  end
  if any(~structfun(@(x) x.available,arithmetic))
    out=LOCAL_condition('COMPONENT_ARITHMETIC_EMPIRICALLY_UNRESOLVED', ...
      'A component arithmetic path is unresolved.'); return;
  end
  out=LOCAL_condition('EMPIRICAL_CAP_UNRESOLVED', ...
    'A required numerator ledger is unresolved.');
end

function out=LOCAL_unresolved(axes,shells,arithmetic,state,q,signature,gram)
  out={}; names=fieldnames(axes);
  for j=1:numel(names)
    item=axes.(names{j});
    if isfield(item,'available'), pass=item.available; else, pass=item.pass; end
    if ~pass, out{end+1}=names{j}; end %#ok<AGROW>
  end
  names=fieldnames(shells);
  for j=1:numel(names)
    if ~shells.(names{j}).available
      out{end+1}=['shell_',names{j}]; %#ok<AGROW>
    end
  end
  names=fieldnames(arithmetic);
  for j=1:numel(names)
    if ~arithmetic.(names{j}).available
      out{end+1}=['arithmetic_',names{j}]; %#ok<AGROW>
    end
  end
  if ~state.available, out{end+1}='mandatory_state_tail'; end
  if ~q.actual_T_qualified, out{end+1}='actual_DeltaT_action'; end
  if ~q.finite_bloch_qualified, out{end+1}='finite_image_Bloch'; end
  if ~signature.pass, out{end+1}='signature_parity'; end
  if ~gram.pass, out{end+1}='combined_gram_parity'; end
end

function warnings=LOCAL_tail_warnings(c,final,state)
  warnings=LOCAL_empty_warnings(); names={'wall','circle','volume'};
  for j=1:3
    t=final.(names{j}).tail; share=max(t.minus.tail_share,t.plus.tail_share);
    if isfinite(share)&&share>c.tail_share_warning
      warnings(end+1)=LOCAL_warning('FULL_P_TAIL_SHARE_WARNING',share); %#ok<AGROW>
    end
  end
  if state.available
    share=state.levels(state.selected_index).maximum_share;
    if isfinite(share)&&share>c.tail_share_warning
      warnings(end+1)=LOCAL_warning('FULL_P_STATE_TAIL_SHARE_WARNING',share); %#ok<AGROW>
    end
  end
end

function out=LOCAL_public_tails(final)
  out=struct('wall',final.wall.tail,'circle',final.circle.tail, ...
    'volume',final.volume.tail);
end

function out=LOCAL_public_components(value)
  out=struct('wall_norm',value.wall.B,'circle_norm',value.circle.B, ...
    'volume_norm',value.volume.B, ...
    'wall_length',value.wall.augmented_length, ...
    'circle_length',value.circle.augmented_length, ...
    'volume_length',value.volume.augmented_length);
end

function out=LOCAL_category_audit(calls)
  expected=struct('final',6,'state',6,'artifact',6,'image',42, ...
    'three_axis',162,'interaction',42,'shell',16,'field',12);
  names=fieldnames(expected); pass=true; total=0;
  for j=1:numel(names)
    name=names{j}; actual=calls.full_p_contraction_category.(name);
    records.(name)=struct('expected',expected.(name),'actual',actual, ...
      'pass',actual==expected.(name)); %#ok<AGROW>
    pass=pass&&records.(name).pass; total=total+actual;
  end
  out=struct('unit','one side-specific tail/partial contraction sequence', ...
    'categories',records,'recorded',total,'expected',292, ...
    'pass',pass&&total==292&&calls.full_p_contraction_calls==292);
end

function out=LOCAL_eig_audit(calls)
  small=calls.small_hermitian_gram_diagnostic_eig_calls;
  out=struct('small_hermitian_gram_diagnostic_eig_calls',small, ...
    'expected_small_gram',274,'gauss_golub_welsch_eig_calls_here', ...
    calls.gauss_golub_welsch_eig_calls, ...
    'candidate_solve_calls',calls.candidate_solve_calls, ...
    'pass',small==274&&calls.gauss_golub_welsch_eig_calls==0);
end

%% ==================== Small utilities and resource record ====================
% Counters and active-object proxies are compact and mergeable by the entry.

function out=LOCAL_parity_record(label,class_name,long,sig,nops)
  scale=max([realmin,abs(long),abs(sig)]); allowance=100*nops*eps*scale;
  numerator=abs(long-sig);
  out=struct('label',label,'coverage_class',class_name,'actual',true, ...
    'representative',false,'long_value',long,'signature_value',sig, ...
    'n_op',nops,'scale',scale,'allowance',allowance, ...
    'numerator',numerator,'ratio',numerator/max(realmin,allowance), ...
    'pass',isfinite(numerator)&&numerator<=allowance);
end

function class_name=LOCAL_endpoint_parity_class(label,combined)
  ordinary={'final-wall','final-circle', ...
    'shell-circle-circle-512-1024','shell-circle-circle-1024-2048', ...
    'shell-circle-volume-512-1024','shell-circle-volume-1024-2048', ...
    'shell-wall-wall-1024-2048','shell-wall-wall-2048-4096', ...
    'shell-wall-volume-1024-2048','shell-wall-volume-2048-4096', ...
    'final-wall-N8','final-circle-N8','final-wall-N16', ...
    'final-circle-N16','final-wall-N32','final-circle-N32'};
  volume={'final-volume', ...
    'final-volume-N8','final-volume-N16','final-volume-N32'};
  class_name='';
  if ~combined&&ismember(label,ordinary)
    class_name='cap_actual_endpoint_augmented';
  elseif combined&&ismember(label,volume)
    class_name='combined_volume_augmented';
  end
end

function class_name=LOCAL_pair_parity_class(label,combined)
  ordinary={'final-wall-N8->final-wall-N16', ...
    'final-circle-N8->final-circle-N16', ...
    'final-wall-N16->final-wall-N32', ...
    'final-circle-N16->final-circle-N32'};
  volume={'final-volume-N8->final-volume-N16', ...
    'final-volume-N16->final-volume-N32', ...
    'representative-finest-volume-N16->representative-finest-volume-N32'};
  class_name='';
  if ~combined&&ismember(label,ordinary)
    class_name='cap_actual_pair_augmented';
  elseif combined&&ismember(label,volume)
    class_name='combined_volume_actual_pair_augmented';
  end
end

function value=LOCAL_concat(value,item)
  if isempty(item), return; end
  if isempty(value), value=item; else, value=[value,item]; end
end

function calls=LOCAL_category_increment(calls,category,n)
  calls.full_p_contraction_calls=calls.full_p_contraction_calls+n;
  calls.full_p_contraction_category.(category)= ...
    calls.full_p_contraction_category.(category)+n;
end

function calls=LOCAL_increment(calls,name,n)
  calls.(name)=calls.(name)+n;
end

function LOCAL_weight_gate(bw,bc,cv,wv)
  if any(~isfinite([bw;bc;cv;wv]))||any(bw<=0)||any(bc<=0)|| ...
      any(cv<0)||any(wv<0)
    error('i32f:ComponentWeight','A required component weight is invalid.');
  end
end

function value=LOCAL_weight_rows(A,w)
  if size(A,1)~=numel(w)
    error('i32f:FactorDimensions','A factor weight dimension is wrong.');
  end
  value=bsxfun(@times,A,w);
end

function Y=LOCAL_pad_orders(X,N,Nout)
  if N==Nout, Y=X; return; end
  if N>Nout||mod(N,2)||mod(Nout,2)
    error('i32f:OrderPadding','Invalid Fourier order padding.');
  end
  Y=zeros(Nout,size(X,2),'like',X); source=(-N/2:N/2-1).';
  target=(-Nout/2:Nout/2-1).'; [tf,at]=ismember(source,target);
  if ~all(tf), error('i32f:OrderPadding','A source order is not nested.'); end
  Y(at,:)=X;
end

function code=LOCAL_axis_code(name)
  if startsWith(name,'image')
    code='IMAGE_TAIL_EMPIRICALLY_UNRESOLVED';
  elseif strcmp(name,'interaction')
    code='AXIS_INTERACTION_EMPIRICALLY_UNRESOLVED';
  else
    code='EMPIRICAL_AXIS_UNRESOLVED';
  end
end

function LOCAL_hard_time(timer,c,stage)
  if toc(timer)>c.hard_seconds
    error('i32f:HardTime','The hard limit was reached in %s.',stage);
  end
end

function out=LOCAL_warning(code,value)
  out=struct('code',char(code),'value',double(value),'blocking',false);
end

function out=LOCAL_condition(code,message)
  out=struct('code',char(code),'message',char(message));
end

function out=LOCAL_empty_warnings()
  out=struct('code',{},'value',{},'blocking',{});
end

function out=LOCAL_unavailable_public()
  out=struct('components',struct(),'caps',struct(), ...
    'estimator',struct('interval_available',false), ...
    'tails',struct(),'axis_metrics',struct(),'arithmetic',struct(), ...
    'field_same_partial',struct(),'artifact_association',struct(), ...
    'signature_parity',struct(),'combined_gram_parity',struct(), ...
    'qualification',struct(),'numerator_available',false, ...
    'denominator_available',false,'all_modes_included',false, ...
    'unresolved_axes',{{'EXECUTION_UNAVAILABLE'}});
end

function out=LOCAL_zero_counters()
  category=struct('final',0,'state',0,'artifact',0,'image',0, ...
    'three_axis',0,'interaction',0,'shell',0,'field',0);
  out=struct('candidate_solve_calls',0,'qz_solve_calls',0, ...
    'coordinate_solve_calls',0,'propagation_solve_calls',0, ...
    'wall_density_solve_calls',0,'circle_density_solve_calls',0, ...
    'schur_solve_calls',0,'proxy_build_calls',0, ...
    'harmonic_action_calls',0,'image_pair_updates',0, ...
    'kress_oracle_calls',0,'linton_oracle_calls',0, ...
    'actual_deltaT_action_calls',0,'finite_bloch_image_updates',0, ...
    'riccati_calls',0,'gauss_factor_calls',0, ...
    'full_p_contraction_calls',0,'full_p_contraction_category',category, ...
    'small_hermitian_gram_diagnostic_eig_calls',0, ...
    'gauss_golub_welsch_eig_calls',0, ...
    'n_op_signature_parity',0,'n_op_combined_gram_parity',0);
end

function out=LOCAL_liveness_ledger()
  out=repmat(struct('field_path','','consumer_set',{{'result_output'}}, ...
    'unique_last_consumer','result_output','death','after publication'),6,1);
  paths={'public_metrics.components','public_metrics.caps', ...
    'public_metrics.estimator','public_metrics.axis_metrics', ...
    'public_metrics.arithmetic','public_metrics.field_same_partial'};
  for j=1:numel(paths), out(j).field_path=paths{j}; end
end

function out=LOCAL_resource_record(before,input_alias,peak,returned,c)
  exclusive=max(0,peak-input_alias);
  out=struct('retained_before_mib',before,'input_alias_nominal_mib',input_alias, ...
    'local_workspace_peak_mib',peak,'module_exclusive_peak_mib',exclusive, ...
    'frozen_streaming_transient_mib',c.worst_transient_mib, ...
    'concurrent_peak_candidate_mib', ...
      before+max(c.worst_transient_mib,exclusive), ...
    'return_payload_mib',returned,'retained_after_mib',NaN, ...
    'cumulative_peak_candidate_mib',NaN, ...
    'proxy_semantics',[ ...
      'deterministic active-object proxy; not RSS, allocator high-water, ', ...
      'reference-count, or copy-on-write proof']);
end

function value=LOCAL_workspace_mib()
  info=evalin('caller','whos'); value=sum([info.bytes])/2^20;
end

function value=LOCAL_value_mib(item)
  info=whos('item'); value=info.bytes/2^20;
end

function out=LOCAL_owner_inventory()
  info=evalin('caller','whos'); out=cell(numel(info),1);
  for j=1:numel(info)
    out{j}=struct('name',info(j).name,'class',info(j).class, ...
      'size',info(j).size,'bytes',info(j).bytes);
  end
end
