function out = i32_certificate_input(input_path,c,retained_before_mib)
%I32_CERTIFICATE_INPUT Load and prune the frozen I3.2 certificate.
% Purpose:
%   Validate the explicit staged fbie-a1 certificate, normalize its integer
%   storage exactly, and retain only arrays with a registered REV_F consumer.
% Input:
%   input_path          - Explicit staged certificate MAT file.
%   c                   - Frozen REV_F numerical and resource contract.
%   retained_before_mib - Caller active-object proxy before this call.
% Output:
%   out                 - Typed total module result.  Its private staged
%                         payload is consumed by later science modules only.
% Main algorithm:
%   Load one named variable, normalize preregistered integer fields, verify
%   scalar/branch/center/raw-map/anchor identity, and prune dead dense maps.
% Based on:
%   check_e_cap.m Revision E certificate and identity helpers.
% Main changes:
%   Uses mechanical side dimensions and records an explicit last-use ledger.
% Numerical goal:
%   Preserve the frozen certificate without any solve or reconstruction.

  peak=LOCAL_workspace_mib(); warnings=LOCAL_empty_warnings();
  calls=LOCAL_zero_counters(); identity=struct(); conversion=struct();
  staged=struct(); first=LOCAL_condition('NONE','Certificate input is available.');
  available=false;
  try
    staged_original=LOCAL_load_input(input_path);
    original_mib=LOCAL_value_mib(staged_original);
    peak=max(peak,LOCAL_workspace_mib());
    [staged,conversion]=LOCAL_normalize_integer_storage(staged_original);
    normalized_mib=LOCAL_value_mib(staged);
    normalization_peak=original_mib+normalized_mib+LOCAL_value_mib(conversion);
    peak=max([peak,LOCAL_workspace_mib(),normalization_peak]);
    clear staged_original;

    LOCAL_input_gate(staged,c);
    identity=LOCAL_identity(staged,c);
    if isfield(identity,'branch_and_Wood')&&identity.branch_and_Wood.exact_Wood
      error('i32f:ExactWood','The frozen branch contains an exact Wood point.');
    end
    if isfield(identity,'branch_and_Wood')&&~identity.branch_and_Wood.pass
      error('i32f:BranchUnavailable', ...
        'The frozen branch/Wood identity is unavailable.');
    end
    if ~identity.pass
      error('i32f:CertificateIdentity','The staged certificate identity failed.');
    end

    [staged,clear_ledger,pruning_audit]=LOCAL_prune_staged(staged);
    peak=max(peak,LOCAL_workspace_mib());
    available=true;
  catch ME
    clear_ledger=LOCAL_empty_clear_ledger();
    pruning_audit=struct();
    first=LOCAL_condition(ME.identifier,ME.message);
    staged=struct();
  end

  public=struct('identity',identity,'input_storage_conversion',conversion, ...
    'input_contract',LOCAL_compact_field(staged,'input_contract'), ...
    'historical_diagnostics',LOCAL_compact_field(staged,'historical_diagnostics'), ...
    'ordinary_anchor',LOCAL_anchor_summary(staged), ...
    'M_role','artificial-wall trace order only', ...
    'wall_trace_order_M',48,'wall_trace_coefficient_count',97, ...
    'certificate_trial_redefined',false);
  if available
    staged=rmfield(staged,{'input_contract','historical_diagnostics'});
    clear_ledger(end+1)=LOCAL_clear_item('input_contract', ...
      {'certificate gate','result provenance'},'result provenance','cleared');
    clear_ledger(end+1)=LOCAL_clear_item('historical_diagnostics', ...
      {'result background disclosure'},'result background disclosure','cleared');
    pruning_audit.compact_provenance_removed_from_private_staged=true;
  end
  private=struct('staged',staged);
  audit=struct('storage_normalized',available, ...
    'mechanical_dimensions',LOCAL_dimension_summary(staged), ...
    'pruning',pruning_audit,'last_use_clear_ledger',clear_ledger, ...
    'post_clear_local_owner_inventory',{LOCAL_owner_inventory()}, ...
    'returned_field_inventory',{{}},'returned_numeric_shape_inventory',{{}}, ...
    'prohibited_field_count',NaN,'prohibited_shape_count',NaN, ...
    'finest_factor_whitelist',{LOCAL_return_whitelist()}, ...
    'exact_shape_contract',{LOCAL_exact_shape_contract(staged)}, ...
    'registered_consumer_death',{LOCAL_consumer_death_ledger()}, ...
    'certificate_blanket_exception',false, ...
    'raw_map_blanket_exception',false, ...
    'denominator_factor_whitelist',{{ ...
      'finest_factors.staged.ordinary_anchor.lead_field_factor_minus', ...
      'finest_factors.staged.ordinary_anchor.lead_field_factor_plus'}}, ...
    'compact_signature_whitelist',{{}},'signature_parity_coverage',struct());
  payload=struct('available',available,'first_unavailable',first, ...
    'public_metrics',public,'finest_factors',private,'cap_signatures',struct(), ...
    'audit_summary',audit,'warnings',warnings,'call_counters',calls, ...
    'resource_record',struct());
  payload.resource_record=LOCAL_resource_record( ...
    retained_before_mib,0,peak,LOCAL_value_mib(payload),c);
  out=payload;
end

%% ==================== Load and storage normalization ====================
% These helpers touch only the explicit staged MAT input.

function staged=LOCAL_load_input(path)
  if ~(ischar(path)||isstring(path))||~isfile(char(path))
    error('i32f:InputMissing','The explicit staged input is unavailable.');
  end
  loaded=load(char(path),'staged');
  if ~isfield(loaded,'staged')||~isstruct(loaded.staged)
    error('i32f:InputSchema','The input does not contain staged.');
  end
  staged=loaded.staged;
end

function [staged,ledger]=LOCAL_normalize_integer_storage(staged)
  specs=LOCAL_integer_storage_contract();
  template=struct('path','','original_class','','original_size',[], ...
    'semantic_range',[],'original_scalar_value',NaN,'original_min',NaN, ...
    'original_max',NaN,'maximum_absolute_value',NaN, ...
    'within_flintmax',false,'exact_roundtrip',false, ...
    'converted_class','','downstream_arithmetic','','pass',false);
  ledger=repmat(template,numel(specs),1);
  for j=1:numel(specs)
    spec=specs(j); value=LOCAL_nested_value(staged,spec.path);
    if ~isinteger(value)||~strcmp(class(value),spec.original_class)|| ...
        ~isequal(size(value),spec.expected_size)
      error('i32f:InputStorageClass', ...
        'Integer storage class/size mismatch at %s.',spec.path);
    end
    converted=double(value); maximum=max(abs(converted),[],'all');
    within_flintmax=maximum<=flintmax;
    roundtrip=within_flintmax&&isequal(feval(spec.original_class,converted),value);
    range_pass=all(converted>=spec.minimum&converted<=spec.maximum,'all');
    if ~roundtrip||~range_pass
      error('i32f:InputStorageValue', ...
        'Integer storage value/range mismatch at %s.',spec.path);
    end
    scalar_value=NaN;
    if isscalar(converted), scalar_value=converted; end
    ledger(j)=struct('path',spec.path,'original_class',spec.original_class, ...
      'original_size',size(value),'semantic_range',[spec.minimum,spec.maximum], ...
      'original_scalar_value',scalar_value,'original_min',min(converted,[],'all'), ...
      'original_max',max(converted,[],'all'), ...
      'maximum_absolute_value',maximum,'within_flintmax',within_flintmax, ...
      'exact_roundtrip',roundtrip,'converted_class','double', ...
      'downstream_arithmetic',spec.downstream_arithmetic,'pass',true);
    staged=LOCAL_nested_assign(staged,spec.path,converted);
  end
end

function specs=LOCAL_integer_storage_contract()
  rows={ ...
    'input_contract.eta_source_nodes','int64',[1,1],256,256,'input node-count equality'; ...
    'input_contract.wall_source_orders','int64',[1,1],512,512,'input order-count equality'; ...
    'certificate.d','int64',[1,1],1,1,'scalar and Fourier-grid identity'; ...
    'certificate.rho_disk','int64',[1,1],17,17,'material scalar identity'; ...
    'certificate.L','int64',[1,1],1,1,'phase and center-trace identity'; ...
    'certificate.M','int64',[1,1],48,48,'retained-order identity'; ...
    'certificate.K','int64',[1,1],97,97,'state-dimension arithmetic'; ...
    'certificate.wall_input_unit_512','uint8',[1024,194],0,1,'shared-wall action'; ...
    'certificate.wall_orders_512','int16',[512,1],-256,255,'wall-order identity'; ...
    'raw_maps.circle_orders_512','int64',[512,1],-256,255,'circle-order identity'; ...
    'raw_maps.wall_input_unit_512','uint8',[1024,194],0,1,'artifact wall defect'; ...
    'certificate.branch_port.classification','int8',[97,1],-1,1,'branch classes'; ...
    'certificate.branch_port.outgoing_sign_pass','uint8',[97,1],0,1,'branch sign'; ...
    'certificate.branch_port.axis_pass','uint8',[97,1],0,1,'branch axis'; ...
    'certificate.branch_port.available','int64',[1,1],0,1,'branch availability'; ...
    'certificate.branch_port.pass','int64',[1,1],0,1,'branch qualification'; ...
    'certificate.center_wall_jumps.field_lower_uses_shared_trace','int64',[1,1],0,1,'field lower trace'; ...
    'ordinary_anchor.center_wall_jumps.field_lower_uses_shared_trace','int64',[1,1],0,1,'anchor trace'; ...
    'ordinary_anchor.tail_minus.selected_N','int64',[1,1],1,32,'minus full-P association'; ...
    'ordinary_anchor.tail_plus.selected_N','int64',[1,1],1,32,'plus full-P association'; ...
    'ordinary_anchor.first_level_indices.minus_physical_start','uint8',[5,1],0,1,'minus start'; ...
    'ordinary_anchor.first_level_indices.plus_physical_start','uint8',[5,1],0,1,'plus start'; ...
    'ordinary_anchor.first_level_indices.minus_selected_N','int64',[1,1],1,32,'minus selected'; ...
    'ordinary_anchor.first_level_indices.plus_selected_N','int64',[1,1],1,32,'plus selected'; ...
    'historical_diagnostics.circle_action_metric.zero_component','int64',[1,1],0,1,'historical Boolean'; ...
    'historical_diagnostics.circle_angular_tail_metric.zero_component','int64',[1,1],0,1,'historical Boolean'; ...
    'historical_diagnostics.outside_M_metric.zero_component','int64',[1,1],0,1,'historical Boolean'; ...
    'historical_diagnostics.outside_M_metric.computed_modes_all_in_residual','int64',[1,1],0,1,'historical inclusion'};
  template=struct('path','','original_class','','expected_size',[], ...
    'minimum',NaN,'maximum',NaN,'downstream_arithmetic','');
  specs=repmat(template,size(rows,1),1);
  for j=1:size(rows,1)
    specs(j)=struct('path',rows{j,1},'original_class',rows{j,2}, ...
      'expected_size',rows{j,3},'minimum',rows{j,4}, ...
      'maximum',rows{j,5},'downstream_arithmetic',rows{j,6});
  end
end

function value=LOCAL_nested_value(staged,path)
  try
    value=subsref(staged,LOCAL_nested_chain(path));
  catch ME
    error('i32f:InputStoragePath', ...
      'Required integer storage path is unavailable: %s (%s).',path,ME.message);
  end
end

function staged=LOCAL_nested_assign(staged,path,value)
  staged=subsasgn(staged,LOCAL_nested_chain(path),value);
end

function chain=LOCAL_nested_chain(path)
  parts=strsplit(path,'.');
  chain=repmat(struct('type','.','subs',''),1,numel(parts));
  for j=1:numel(parts), chain(j).subs=parts{j}; end
end

%% ==================== Frozen identity ====================
% Identity checks are copied from Revision E except for mechanical side sizes.

function LOCAL_input_gate(s,c)
  required={'input_contract','certificate','ordinary_anchor','raw_maps', ...
    'historical_diagnostics'};
  for j=1:numel(required)
    if ~isfield(s,required{j})||~isstruct(s.(required{j}))
      error('i32f:InputSchema','Missing staged struct %s.',required{j});
    end
  end
  contract_fields={'schema','source_attempt','staging_only', ...
    'formal_runtime_must_not_read_historical_output','no_resolve_required', ...
    'M_role','eta_source_nodes','wall_source_orders','density_coordinate', ...
    'circle_basis','wall_basis','circle_ordering','wall_output_ordering', ...
    'branch_classification_encoding','circle_value_only_lift', ...
    'wall_value_only_lift','lift_shape','exact_lift_amplitude_rule'};
  certificate_fields={'source_attempt','khat','mu_h','gamma','beta','d','R', ...
    'rho_disk','X_L','X_R','L','M','K','delta_c','delta_w','q_center', ...
    'Pplus','Pminus','cplus','cminus','Dplus','Dminus','Gplus','Gminus', ...
    'branch_port','eta_unit_256','xi_left_unit_512','xi_right_unit_512', ...
    'wall_input_unit_512','wall_orders_512','center_actual_left_trace', ...
    'center_actual_right_trace','center_shared_left_trace', ...
    'center_shared_right_trace','center_left_value_mismatch', ...
    'center_right_value_mismatch','center_wall_jumps','density_coordinate', ...
    'global_normal_label','lift_contract'};
  raw_fields={'delta_plus','delta_minus','circle_jump_plus', ...
    'circle_jump_minus','QLplus','QRplus','QLminus','QRminus','Jplus', ...
    'Jminus','wall_flux_left_unit_512','wall_flux_right_unit_512', ...
    'circle_delta_D_unit_wall_512','circle_j_Gamma_unit_wall_512', ...
    'circle_orders_512','circle_theta_512','wall_common_y_1024', ...
    'wall_common_value_1024','wall_common_flux_1024','wall_input_unit_512', ...
    'circle_value_residual_unit_512','circle_normal_residual_unit_512'};
  anchor_fields={'B_wall','B_circle','B_volume','M_tilde','N_tilde', ...
    'lead_wall_factor_plus','lead_wall_factor_minus', ...
    'lead_circle_factor_plus','lead_circle_factor_minus', ...
    'lead_volume_factor_plus','lead_volume_factor_minus', ...
    'lead_field_factor_plus','lead_field_factor_minus', ...
    'center_plus_wall_lift_factor','center_minus_wall_lift_factor', ...
    'center_left_value_lift_source','center_right_value_lift_source', ...
    'center_wall_jumps','tail_minus','tail_plus','first_level_indices'};
  if ~all(isfield(s.input_contract,contract_fields))|| ...
      ~all(isfield(s.certificate,certificate_fields))|| ...
      ~all(isfield(s.raw_maps,raw_fields))|| ...
      ~all(isfield(s.ordinary_anchor,anchor_fields))|| ...
      ~isstruct(s.certificate.lift_contract)|| ...
      ~all(isfield(s.ordinary_anchor.tail_minus,{'selected_N'}))|| ...
      ~all(isfield(s.ordinary_anchor.tail_plus,{'selected_N'}))|| ...
      ~all(isfield(s.ordinary_anchor.first_level_indices, ...
        {'minus_physical_start','plus_physical_start', ...
        'minus_selected_N','plus_selected_N'}))
    error('i32f:InputSchema','A required semantic input field is missing.');
  end
  if ~strcmp(char(s.input_contract.schema),c.input_schema)|| ...
      ~strcmp(char(s.input_contract.source_attempt),c.source_attempt)|| ...
      ~logical(s.input_contract.staging_only)|| ...
      ~logical(s.input_contract.formal_runtime_must_not_read_historical_output)|| ...
      ~logical(s.input_contract.no_resolve_required)|| ...
      round(s.certificate.M)~=48||round(s.certificate.K)~=97
    error('i32f:InputIdentity','The frozen input identity is wrong.');
  end
  arrays={s.certificate.q_center,s.certificate.Pplus,s.certificate.Pminus, ...
    s.certificate.cplus,s.certificate.cminus,s.certificate.Dplus, ...
    s.certificate.Dminus,s.certificate.Gplus,s.certificate.Gminus, ...
    s.certificate.eta_unit_256,s.certificate.xi_left_unit_512, ...
    s.certificate.xi_right_unit_512,s.certificate.wall_input_unit_512, ...
    s.raw_maps.delta_plus, ...
    s.raw_maps.delta_minus,s.raw_maps.circle_jump_plus, ...
    s.raw_maps.circle_jump_minus,s.raw_maps.QLplus,s.raw_maps.QRplus, ...
    s.raw_maps.QLminus,s.raw_maps.QRminus,s.raw_maps.Jplus,s.raw_maps.Jminus, ...
    s.raw_maps.wall_flux_left_unit_512,s.raw_maps.wall_flux_right_unit_512, ...
    s.raw_maps.circle_delta_D_unit_wall_512, ...
    s.raw_maps.circle_j_Gamma_unit_wall_512,s.raw_maps.wall_input_unit_512, ...
    s.raw_maps.wall_common_y_1024,s.raw_maps.wall_common_value_1024, ...
    s.raw_maps.wall_common_flux_1024, ...
    s.raw_maps.circle_value_residual_unit_512, ...
    s.raw_maps.circle_normal_residual_unit_512};
  for j=1:numel(arrays)
    if isempty(arrays{j})||~isnumeric(arrays{j})||any(~isfinite(arrays{j}),'all')
      error('i32f:InputValues','A required certificate array is unavailable.');
    end
  end
  a=s.ordinary_anchor; values=[a.B_wall,a.B_circle,a.B_volume,a.M_tilde,a.N_tilde];
  if any(~isfinite(values))||any(values<=0)|| ...
      abs(a.M_tilde-sum(values(1:3)))>100*eps*sum(values(1:3))
    error('i32f:InputAnchors','The ordinary component anchors are inconsistent.');
  end
end

function out=LOCAL_identity(s,c)
  z=s.certificate; q=z.q_center; K=round(z.K);
  rminus=size(z.Pminus,1); rplus=size(z.Pplus,1);
  finite=all(isfinite([z.khat,z.mu_h,z.gamma,z.beta,z.d,z.R, ...
    z.rho_disk,z.delta_c,z.delta_w]));
  scalars=[z.khat,z.beta,z.d,z.R,z.rho_disk,z.X_L,z.X_R,z.L, ...
    z.M,z.K,z.delta_c,z.delta_w];
  references=[c.khat,c.beta,c.d,c.R,c.rho_disk,c.X_L,c.X_R,c.L, ...
    c.M,c.K,c.delta_c,c.delta_w];
  scalar_defect=max(abs(scalars-references)./max(realmin,abs(references)));
  dims=isequal(size(z.Pminus),[rminus,rminus])&& ...
    isequal(size(z.Pplus),[rplus,rplus])&& ...
    numel(z.cminus)==rminus&&numel(z.cplus)==rplus&& ...
    isequal(size(z.Gminus),[2*K,rminus])&& ...
    isequal(size(z.Gplus),[2*K,rplus])&&rminus==K&&rplus==K&& ...
    isequal(size(z.Dminus),[K,K])&&isequal(size(z.Dplus),[K,K])&& ...
    numel(q)==2*K&&isequal(size(z.eta_unit_256),[512,2*K])&& ...
    isequal(size(z.xi_left_unit_512),[512,2*K])&& ...
    isequal(size(z.xi_right_unit_512),[512,2*K])&& ...
    isequal(size(z.wall_input_unit_512),[1024,2*K]);
  mu_defect=abs(z.mu_h-z.khat^2)/max([realmin,abs(z.mu_h),abs(z.khat^2)]);
  gamma_defect=abs(z.gamma-z.mu_h)/max([realmin,abs(z.gamma),abs(z.mu_h)]);
  q_norm_defect=abs(norm(q)-1);
  Gplus_defect=LOCAL_relative_difference(z.Gplus,[z.Dplus;z.Dplus*z.Pplus]);
  Gminus_defect=LOCAL_relative_difference(z.Gminus,[z.Dminus*z.Pminus;z.Dminus]);
  [branch_pass,branch_record,E]=LOCAL_branch_identity(z,c);
  [center_pass,center_record]=LOCAL_center_identity(z,q,E,c);
  [raw_pass,raw_record]=LOCAL_raw_map_identity(s.raw_maps,z,c);
  [anchor_pass,anchor_record]=LOCAL_anchor_identity(s.ordinary_anchor,c,rminus,rplus);
  labels=strcmp(char(z.density_coordinate),'[tau;zeta], zeta=-sigma')&& ...
    contains(lower(char(z.global_normal_label)),'global +r')&& ...
    contains(lower(char(z.global_normal_label)),'cell outward')&& ...
    strcmp(char(s.input_contract.M_role),'97 retained QZ wall-input modes only')&& ...
    strcmp(char(s.input_contract.density_coordinate),'[tau;zeta], zeta=-sigma')&& ...
    round(s.input_contract.eta_source_nodes)==256&& ...
    round(s.input_contract.wall_source_orders)==512&& ...
    strcmp(char(s.input_contract.circle_basis), ...
      'exp(i*l*theta)/sqrt(2*pi*R) in L2(ds)')&& ...
    strcmp(char(s.input_contract.wall_basis), ...
      'd^(-1/2)*exp(i*(beta+2*pi*m/d)*y)')&& ...
    strcmp(char(s.input_contract.circle_ordering), ...
      '-N/2:N/2-1 with negative Nyquist retained')&& ...
    strcmp(char(s.input_contract.wall_output_ordering), ...
      '-N/2:N/2-1 with negative Nyquist retained')&& ...
    strcmp(char(s.input_contract.branch_classification_encoding), ...
      'int8: +1 propagating, -1 evanescent, 0 Wood')&& ...
    logical(s.input_contract.circle_value_only_lift)&& ...
    logical(s.input_contract.wall_value_only_lift)&& ...
    strcmp(char(s.input_contract.lift_shape),'chi(t)=1-3*t^2+2*t^3')&& ...
    strcmp(char(s.input_contract.exact_lift_amplitude_rule), ...
      'shared value minus exact continuous raw trace')&& ...
    logical(z.lift_contract.circle_value_only)&&logical(z.lift_contract.wall_value_only)&& ...
    strcmp(char(z.lift_contract.shape),'chi(t)=1-3*t^2+2*t^3')&& ...
    strcmp(char(z.lift_contract.exact_amplitude_rule), ...
      'shared value minus exact continuous raw trace');
  levels=isequal(c.circle_levels,[512,1024,2048])&& ...
    isequal(c.wall_levels,[1024,2048,4096]);
  pass=finite&&dims&&labels&&levels&&branch_pass&&center_pass&&raw_pass&& ...
    anchor_pass&&scalar_defect<=c.identity_tol&&q_norm_defect<=c.identity_tol&& ...
    mu_defect<=c.identity_tol&&gamma_defect<=c.identity_tol&& ...
    Gplus_defect<=c.identity_tol&&Gminus_defect<=c.identity_tol;
  out=struct('pass',pass,'finite',finite,'dimensions',dims,'labels',labels, ...
    'rminus',rminus,'rplus',rplus,'K',K, ...
    'rminus_equals_K',rminus==K,'rplus_equals_K',rplus==K, ...
    'frozen_scalar_relative_defect',scalar_defect,'q_norm_defect',q_norm_defect, ...
    'Gplus_relative_defect',Gplus_defect,'Gminus_relative_defect',Gminus_defect, ...
    'mu_relative_defect',mu_defect,'gamma_relative_defect',gamma_defect, ...
    'branch_and_Wood',branch_record,'center_traces',center_record, ...
    'raw_map_schema',raw_record,'ordinary_anchor',anchor_record, ...
    'M_role','artificial-wall trace order only','circle_density_nodes',256, ...
    'wall_density_orders',512,'certificate_trial_redefined',false);
end

function [pass,out]=LOCAL_anchor_identity(a,c,rminus,rplus)
  values=[a.B_wall,a.B_circle,a.B_volume,a.M_tilde,a.N_tilde];
  reference=[c.anchor_components,c.anchor_M,c.anchor_N];
  scalar_defect=max(abs(values-reference)./max(realmin,abs(reference)));
  names={'lead_wall_factor_plus','lead_wall_factor_minus', ...
    'lead_circle_factor_plus','lead_circle_factor_minus', ...
    'lead_volume_factor_plus','lead_volume_factor_minus', ...
    'lead_field_factor_plus','lead_field_factor_minus'};
  dims=true; finite=true;
  for j=1:numel(names)
    value=a.(names{j}); expected=rplus;
    if contains(names{j},'minus'), expected=rminus; end
    dims=dims&&size(value,2)==expected&&~isempty(value);
    finite=finite&&all(isfinite(value),'all');
  end
  selected=[a.tail_minus.selected_N,a.tail_plus.selected_N];
  selected_pass=all(isfinite(selected))&&all(selected==round(selected))&& ...
    all(selected>=1)&&all(selected<=max(c.full_p_levels));
  index=a.first_level_indices;
  index_pass=isequal(index.minus_physical_start(:).',[0,0,0,1,0])&& ...
    isequal(index.plus_physical_start(:).',[0,0,0,1,0])&& ...
    index.minus_selected_N==selected(1)&&index.plus_selected_N==selected(2);
  center_dims=numel(a.center_left_value_lift_source)==512&& ...
    numel(a.center_right_value_lift_source)==512;
  pass=scalar_defect<=c.identity_tol&&dims&&finite&&selected_pass&& ...
    index_pass&&center_dims;
  out=struct('pass',pass,'scalar_relative_defect',scalar_defect, ...
    'factor_dimensions',dims,'factor_finite',finite, ...
    'selected_N_minus_plus',selected,'index_contract_pass',index_pass, ...
    'same_finite_field_partial_center',true);
end

function [pass,out,E]=LOCAL_branch_identity(z,c)
  b=z.branch_port; required={'beta_m','gamma_m','t_m','classification', ...
    'outgoing_reference','outgoing_relative_defects','outgoing_sign_pass', ...
    'axis_pass','available','pass'};
  fields=all(isfield(b,required)); E=[];
  if ~fields
    pass=false; out=struct('pass',false,'fields_available',false, ...
      'exact_Wood',false); return;
  end
  orders=(-c.M:c.M).'; beta=c.beta+2*pi*orders/c.d;
  t=c.khat^2-beta.^2; gamma=sqrt(complex(t));
  flip=imag(gamma)<0|(imag(gamma)==0&real(gamma)<0); gamma(flip)=-gamma(flip);
  exact_wood=any(t==0); prop=t>0; evan=t<0;
  classes=zeros(c.K,1,'int8'); classes(prop)=1; classes(evan)=-1;
  beta_defect=LOCAL_relative_difference(b.beta_m(:),beta);
  gamma_defect=LOCAL_relative_difference(b.gamma_m(:),gamma);
  t_defect=LOCAL_relative_difference(b.t_m(:),t);
  ref_defect=LOCAL_relative_difference(b.outgoing_reference(:),gamma);
  class_pass=numel(b.classification)==c.K&&all(int8(b.classification(:))==classes);
  sign_pass=numel(b.outgoing_sign_pass)==c.K&&all(b.outgoing_sign_pass(:))&& ...
    numel(b.axis_pass)==c.K&&all(b.axis_pass(:));
  wood_margin=min(abs(t)./(c.khat^2+beta.^2));
  E=diag(exp(1i*b.gamma_m(:)*c.L));
  finite=all(isfinite([b.beta_m(:);b.gamma_m(:);b.t_m(:); ...
    b.outgoing_reference(:);b.outgoing_relative_defects(:);wood_margin]));
  pass=fields&&finite&&~exact_wood&&logical(b.available)&& ...
    beta_defect<=c.identity_tol&&gamma_defect<=c.identity_tol&& ...
    t_defect<=c.identity_tol&&ref_defect<=c.identity_tol&&class_pass&&sign_pass;
  out=struct('pass',pass,'fields_available',fields,'exact_Wood',exact_wood, ...
    'relative_Wood_margin',wood_margin,'beta_relative_defect',beta_defect, ...
    'gamma_relative_defect',gamma_defect,'t_relative_defect',t_defect, ...
    'reference_relative_defect',ref_defect,'class_pass',class_pass, ...
    'sign_and_axis_pass',sign_pass,'stored_qualification_pass',logical(b.pass));
end

function [pass,out]=LOCAL_center_identity(z,q,E,c)
  orders=(-256:255).'; retained=(-c.M:c.M).'; embed=zeros(512,c.K);
  for j=1:c.K, embed(orders==retained(j),j)=1; end
  qL=q(1:c.K); qR=q(c.K+1:end);
  actual_left=embed*(qL+E*qR); actual_right=embed*(E*qL+qR);
  shared_left=embed*z.Dminus*z.cminus; shared_right=embed*z.Dplus*z.cplus;
  left_scale=max(norm(actual_left,'fro'),norm(shared_left,'fro'));
  right_scale=max(norm(actual_right,'fro'),norm(shared_right,'fro'));
  metrics=struct( ...
    'actual_left',LOCAL_center_metric(z.center_actual_left_trace,actual_left, ...
      max(norm(z.center_actual_left_trace,'fro'),norm(actual_left,'fro')),c), ...
    'actual_right',LOCAL_center_metric(z.center_actual_right_trace,actual_right, ...
      max(norm(z.center_actual_right_trace,'fro'),norm(actual_right,'fro')),c), ...
    'shared_left',LOCAL_center_metric(z.center_shared_left_trace,shared_left, ...
      max(norm(z.center_shared_left_trace,'fro'),norm(shared_left,'fro')),c), ...
    'shared_right',LOCAL_center_metric(z.center_shared_right_trace,shared_right, ...
      max(norm(z.center_shared_right_trace,'fro'),norm(shared_right,'fro')),c), ...
    'mismatch_left',LOCAL_center_metric(z.center_left_value_mismatch, ...
      shared_left-actual_left,left_scale,c), ...
    'mismatch_right',LOCAL_center_metric(z.center_right_value_mismatch, ...
      shared_right-actual_right,right_scale,c), ...
    'repaired_left',LOCAL_center_metric(z.center_actual_left_trace+ ...
      z.center_left_value_mismatch,z.center_shared_left_trace,left_scale,c), ...
    'repaired_right',LOCAL_center_metric(z.center_actual_right_trace+ ...
      z.center_right_value_mismatch,z.center_shared_right_trace,right_scale,c));
  names=fieldnames(metrics); defects=zeros(1,numel(names)); certificate_pass=true;
  for j=1:numel(names)
    defects(j)=metrics.(names{j}).ratio;
    certificate_pass=certificate_pass&&metrics.(names{j}).pass;
  end
  center=z.center_wall_jumps; required={'left_coefficients','right_coefficients', ...
    'actual_left_trace','actual_right_trace','shared_left_trace', ...
    'shared_right_trace','left_value_mismatch','right_value_mismatch'};
  fields=all(isfield(center,required)); stored=struct(); stored_defects=Inf(1,8);
  stored_pass=false; jump_dims=false;
  if fields
    stored=struct( ...
      'actual_left',LOCAL_center_metric(center.actual_left_trace,actual_left, ...
        max(norm(center.actual_left_trace,'fro'),norm(actual_left,'fro')),c), ...
      'actual_right',LOCAL_center_metric(center.actual_right_trace,actual_right, ...
        max(norm(center.actual_right_trace,'fro'),norm(actual_right,'fro')),c), ...
      'shared_left',LOCAL_center_metric(center.shared_left_trace,shared_left, ...
        max(norm(center.shared_left_trace,'fro'),norm(shared_left,'fro')),c), ...
      'shared_right',LOCAL_center_metric(center.shared_right_trace,shared_right, ...
        max(norm(center.shared_right_trace,'fro'),norm(shared_right,'fro')),c), ...
      'mismatch_left',LOCAL_center_metric(center.left_value_mismatch, ...
        shared_left-actual_left,left_scale,c), ...
      'mismatch_right',LOCAL_center_metric(center.right_value_mismatch, ...
        shared_right-actual_right,right_scale,c), ...
      'repaired_left',LOCAL_center_metric(center.actual_left_trace+ ...
        center.left_value_mismatch,center.shared_left_trace,left_scale,c), ...
      'repaired_right',LOCAL_center_metric(center.actual_right_trace+ ...
        center.right_value_mismatch,center.shared_right_trace,right_scale,c));
    names=fieldnames(stored); stored_pass=true;
    for j=1:numel(names)
      stored_defects(j)=stored.(names{j}).ratio;
      stored_pass=stored_pass&&stored.(names{j}).pass;
    end
    jump_dims=numel(center.left_coefficients)==512&&numel(center.right_coefficients)==512;
  end
  finite=all(isfinite([defects,stored_defects]));
  pass=fields&&jump_dims&&finite&&certificate_pass&&stored_pass;
  out=struct('pass',pass,'relative_defects',defects, ...
    'stored_center_relative_defects',stored_defects, ...
    'certificate_metrics',metrics,'stored_center_metrics',stored, ...
    'left_parent_trace_scale',left_scale,'right_parent_trace_scale',right_scale, ...
    'stored_center_fields_available',fields,'jump_dimensions',jump_dims, ...
    'actual_trace_formula','embed*[I,E]q / embed*[E,I]q', ...
    'shared_trace_formula','embed*Dminus*cminus / embed*Dplus*cplus');
end

function out=LOCAL_center_metric(x,y,parent_scale,c)
  compatible=isequal(size(x),size(y))&&isfinite(parent_scale)&& ...
    parent_scale>=0&&all(isfinite([x(:);y(:)]));
  if compatible
    numerator=norm(x-y,'fro'); scale=max(realmin,parent_scale);
    allowance=100*eps*parent_scale; ratio=numerator/scale;
  else
    numerator=Inf; scale=realmin; allowance=0; ratio=Inf;
  end
  pass=compatible&&isfinite(ratio)&& ...
    numerator<=c.identity_tol*scale+allowance;
  out=struct('absolute_defect',numerator,'left_norm',norm(x,'fro'), ...
    'right_norm',norm(y,'fro'),'scale',scale, ...
    'roundoff_allowance',allowance,'ratio',ratio,'threshold',c.identity_tol, ...
    'zero_scale',parent_scale==0,'pass',pass);
end

function [pass,out]=LOCAL_raw_map_identity(a,z,c)
  K=c.K; dimensions=struct( ...
    'delta_plus',isequal(size(a.delta_plus),[512,K]), ...
    'delta_minus',isequal(size(a.delta_minus),[512,K]), ...
    'circle_jump_plus',isequal(size(a.circle_jump_plus),[512,K]), ...
    'circle_jump_minus',isequal(size(a.circle_jump_minus),[512,K]), ...
    'QLplus',isequal(size(a.QLplus),[512,K]), ...
    'QRplus',isequal(size(a.QRplus),[512,K]), ...
    'QLminus',isequal(size(a.QLminus),[512,K]), ...
    'QRminus',isequal(size(a.QRminus),[512,K]), ...
    'Jplus',isequal(size(a.Jplus),[512,K]), ...
    'Jminus',isequal(size(a.Jminus),[512,K]), ...
    'wall_flux_left_unit',isequal(size(a.wall_flux_left_unit_512),[512,2*K]), ...
    'wall_flux_right_unit',isequal(size(a.wall_flux_right_unit_512),[512,2*K]), ...
    'circle_delta_unit',isequal(size(a.circle_delta_D_unit_wall_512),[512,2*K]), ...
    'circle_jump_unit',isequal(size(a.circle_j_Gamma_unit_wall_512),[512,2*K]), ...
    'wall_input_unit',isequal(size(a.wall_input_unit_512),[1024,2*K]), ...
    'circle_value_residual_unit', ...
      isequal(size(a.circle_value_residual_unit_512),[512,2*K]), ...
    'circle_normal_residual_unit', ...
      isequal(size(a.circle_normal_residual_unit_512),[512,2*K]), ...
    'wall_common_value',isequal(size(a.wall_common_value_1024),[2048,2*K]), ...
    'wall_common_flux',isequal(size(a.wall_common_flux_1024),[2048,2*K]));
  names=fieldnames(dimensions); dim_pass=true;
  for j=1:numel(names), dim_pass=dim_pass&&dimensions.(names{j}); end
  wall_orders=(-256:255).'; circle_theta=(0:511)'*2*pi/512;
  order_defect=LOCAL_relative_difference(z.wall_orders_512(:),wall_orders);
  circle_order_defect=LOCAL_relative_difference(a.circle_orders_512(:),wall_orders);
  theta_defect=LOCAL_relative_difference(a.circle_theta_512(:),circle_theta);
  y=a.wall_common_y_1024(:); reference=-c.d/2+c.d*(0:1023)'/1024;
  y_defect=LOCAL_relative_difference(y,reference);
  q=z.q_center; qL=q(1:K); qR=q(K+1:end); gamma=z.branch_port.gamma_m(:);
  E=exp(1i*gamma*z.L); dxL=1i*gamma.*(qL-E.*qR); dxR=1i*gamma.*(E.*qL-qR);
  embed=zeros(512,K); retained=(-c.M:c.M).';
  for j=1:K, embed(wall_orders==retained(j),j)=1; end
  reconstructed_left=a.QRminus*z.cminus-embed*dxL;
  reconstructed_right=embed*dxR+a.QLplus*z.cplus;
  center_jump_defect=max( ...
    LOCAL_relative_difference(reconstructed_left,z.center_wall_jumps.left_coefficients), ...
    LOCAL_relative_difference(reconstructed_right,z.center_wall_jumps.right_coefficients));
  finite=all(isfinite([order_defect,circle_order_defect,theta_defect, ...
    y_defect,center_jump_defect]));
  pass=dim_pass&&finite&&max([order_defect,circle_order_defect, ...
    theta_defect,y_defect,center_jump_defect])<=c.identity_tol;
  out=struct('pass',pass,'dimensions',dimensions, ...
    'wall_order_relative_defect',order_defect, ...
    'circle_order_relative_defect',circle_order_defect, ...
    'circle_theta_relative_defect',theta_defect, ...
    'wall_common_grid_relative_defect',y_defect, ...
    'center_wall_jump_association_defect',center_jump_defect);
end

function value=LOCAL_relative_difference(x,y)
  if ~isequal(size(x),size(y))||any(~isfinite([x(:);y(:)]))
    value=Inf;
  else
    value=norm(x-y,'fro')/max([realmin,norm(x,'fro'),norm(y,'fro')]);
  end
end

%% ==================== Pruning and audit ====================
% Only paths with a registered later consumer remain reachable.

function [s,ledger,audit]=LOCAL_prune_staged(s)
  certificate_keep={'source_attempt','khat','mu_h','gamma','beta','d','R', ...
    'rho_disk','X_L','X_R','L','M','K','delta_c','delta_w','q_center', ...
    'Pplus','Pminus','cplus','cminus','Gplus','Gminus','branch_port', ...
    'eta_unit_256','xi_left_unit_512','xi_right_unit_512', ...
    'wall_input_unit_512','center_actual_left_trace', ...
    'center_actual_right_trace','center_shared_left_trace', ...
    'center_shared_right_trace','center_left_value_mismatch', ...
    'center_right_value_mismatch','center_wall_jumps'};
  raw_keep={'delta_plus','delta_minus','circle_jump_plus','circle_jump_minus', ...
    'Jplus','Jminus','wall_common_y_1024','wall_common_value_1024', ...
    'wall_input_unit_512'};
  ledger=LOCAL_empty_clear_ledger(); removed_certificate={};
  certificate_names=fieldnames(s.certificate);
  for j=1:numel(certificate_names)
    name=certificate_names{j};
    if ~ismember(name,certificate_keep)
      value=s.certificate.(name);
      removed_certificate{end+1}=LOCAL_removed_summary(name,value); %#ok<AGROW>
      s.certificate=rmfield(s.certificate,name);
      ledger(end+1)=LOCAL_clear_item(['certificate.',name], ...
        {'certificate identity'},'certificate identity','cleared'); %#ok<AGROW>
    end
  end
  gamma_m=s.certificate.branch_port.gamma_m;
  branch_removed=setdiff(fieldnames(s.certificate.branch_port),{'gamma_m'});
  s.certificate.branch_port=struct('gamma_m',gamma_m);
  for j=1:numel(branch_removed)
    ledger(end+1)=LOCAL_clear_item( ...
      ['certificate.branch_port.',branch_removed{j}], ...
      {'certificate identity'},'certificate identity','cleared'); %#ok<AGROW>
  end
  center=s.certificate.center_wall_jumps;
  center_keep={'left_coefficients','right_coefficients', ...
    'field_lower_uses_shared_trace'};
  center_removed=setdiff(fieldnames(center),center_keep);
  reduced_center=struct('left_coefficients',center.left_coefficients, ...
    'right_coefficients',center.right_coefficients);
  if isfield(center,'field_lower_uses_shared_trace')
    reduced_center.field_lower_uses_shared_trace= ...
      center.field_lower_uses_shared_trace;
  end
  s.certificate.center_wall_jumps=reduced_center;
  for j=1:numel(center_removed)
    ledger(end+1)=LOCAL_clear_item( ...
      ['certificate.center_wall_jumps.',center_removed{j}], ...
      {'certificate identity'},'certificate identity','cleared'); %#ok<AGROW>
  end

  raw_names=fieldnames(s.raw_maps);
  removed_raw={};
  for j=1:numel(raw_names)
    name=raw_names{j};
    if ~ismember(name,raw_keep)
      s.raw_maps=rmfield(s.raw_maps,name); removed_raw{end+1}=name; %#ok<AGROW>
      ledger(end+1)=LOCAL_clear_item(['raw_maps.',name], ...
        {'certificate identity'},'certificate identity','cleared'); %#ok<AGROW>
    end
  end
  anchor_keep={'B_wall','B_circle','B_volume','M_tilde','N_tilde', ...
    'lead_field_factor_plus','lead_field_factor_minus','tail_minus','tail_plus', ...
    'first_level_indices'};
  anchor_names=fieldnames(s.ordinary_anchor); removed_anchor={};
  for j=1:numel(anchor_names)
    name=anchor_names{j};
    if ~ismember(name,anchor_keep)
      value=s.ordinary_anchor.(name);
      removed_anchor{end+1}=struct('name',name,'class',class(value), ...
        'size',size(value),'norm',LOCAL_safe_norm(value)); %#ok<AGROW>
      s.ordinary_anchor=rmfield(s.ordinary_anchor,name);
      ledger(end+1)=LOCAL_clear_item(['ordinary_anchor.',name], ...
        {'certificate identity'},'certificate identity','cleared'); %#ok<AGROW>
    end
  end
  audit=struct('retained_certificate_fields',{certificate_keep}, ...
    'removed_certificate_summary',{removed_certificate}, ...
    'removed_branch_identity_fields',{branch_removed}, ...
    'removed_center_duplicate_fields',{center_removed}, ...
    'retained_raw_map_whitelist',{raw_keep}, ...
    'retained_raw_map_count',numel(raw_keep),'removed_raw_maps',{removed_raw}, ...
    'retained_anchor_fields',{anchor_keep}, ...
    'removed_anchor_dense_summary',{removed_anchor}, ...
    'canonical_certificate_prefix', ...
      'finest_factors.staged.certificate', ...
    'canonical_raw_map_prefix','finest_factors.staged.raw_maps', ...
    'certificate_blanket_exception',false, ...
    'raw_map_blanket_exception',false, ...
    'no_unregistered_dense_owner_retained',true);
end

function out=LOCAL_removed_summary(name,value)
  out=struct('name',name,'class',class(value),'size',size(value), ...
    'norm',LOCAL_safe_norm(value));
end

function value=LOCAL_safe_norm(x)
  if isnumeric(x), value=norm(x(:)); else, value=NaN; end
end

function out=LOCAL_empty_clear_ledger()
  out=struct('field_path',{},'consumer_set',{}, ...
    'unique_last_consumer',{},'last_use',{},'clear_status',{});
end

function out=LOCAL_clear_item(path,consumers,last_consumer,status)
  out=struct('field_path',path,'consumer_set',{consumers}, ...
    'unique_last_consumer',last_consumer,'last_use',last_consumer, ...
    'clear_status',status);
end

function out=LOCAL_return_whitelist()
  prefix='finest_factors.staged.certificate.';
  names={'Pminus','Pplus','Gminus','Gplus','eta_unit_256', ...
    'xi_left_unit_512','xi_right_unit_512','wall_input_unit_512'};
  out=cell(1,numel(names));
  for j=1:numel(names), out{j}=[prefix,names{j}]; end
  raw={'delta_plus','delta_minus','circle_jump_plus','circle_jump_minus', ...
    'Jplus','Jminus','wall_common_y_1024','wall_common_value_1024', ...
    'wall_input_unit_512'};
  for j=1:numel(raw)
    out{end+1}=['finest_factors.staged.raw_maps.',raw{j}]; %#ok<AGROW>
  end
  out{end+1}= ...
    'finest_factors.staged.ordinary_anchor.lead_field_factor_minus';
  out{end+1}= ...
    'finest_factors.staged.ordinary_anchor.lead_field_factor_plus';
end

function out=LOCAL_exact_shape_contract(staged)
  if ~isfield(staged,'certificate')
    out=struct('field_path',{},'expected_shape',{}, ...
      'actual_shape',{},'pass',{}); return;
  end
  z=staged.certificate; a=staged.raw_maps; anchor=staged.ordinary_anchor;
  K=z.K; rm=size(z.Pminus,1); rp=size(z.Pplus,1);
  rows={ ...
    'finest_factors.staged.certificate.Pminus',[rm,rm],size(z.Pminus); ...
    'finest_factors.staged.certificate.Pplus',[rp,rp],size(z.Pplus); ...
    'finest_factors.staged.certificate.Gminus',[2*K,rm],size(z.Gminus); ...
    'finest_factors.staged.certificate.Gplus',[2*K,rp],size(z.Gplus); ...
    'finest_factors.staged.certificate.eta_unit_256',[512,2*K],size(z.eta_unit_256); ...
    'finest_factors.staged.certificate.xi_left_unit_512',[512,2*K],size(z.xi_left_unit_512); ...
    'finest_factors.staged.certificate.xi_right_unit_512',[512,2*K],size(z.xi_right_unit_512); ...
    'finest_factors.staged.certificate.wall_input_unit_512',[1024,2*K],size(z.wall_input_unit_512); ...
    'finest_factors.staged.raw_maps.delta_plus',[512,K],size(a.delta_plus); ...
    'finest_factors.staged.raw_maps.delta_minus',[512,K],size(a.delta_minus); ...
    'finest_factors.staged.raw_maps.circle_jump_plus',[512,K],size(a.circle_jump_plus); ...
    'finest_factors.staged.raw_maps.circle_jump_minus',[512,K],size(a.circle_jump_minus); ...
    'finest_factors.staged.raw_maps.Jplus',[512,K],size(a.Jplus); ...
    'finest_factors.staged.raw_maps.Jminus',[512,K],size(a.Jminus); ...
    'finest_factors.staged.raw_maps.wall_common_y_1024',[1024,1],size(a.wall_common_y_1024); ...
    'finest_factors.staged.raw_maps.wall_common_value_1024',[2048,2*K],size(a.wall_common_value_1024); ...
    'finest_factors.staged.raw_maps.wall_input_unit_512',[1024,2*K],size(a.wall_input_unit_512); ...
    'finest_factors.staged.ordinary_anchor.lead_field_factor_minus', ...
      [size(anchor.lead_field_factor_minus,1),rm],size(anchor.lead_field_factor_minus); ...
    'finest_factors.staged.ordinary_anchor.lead_field_factor_plus', ...
      [size(anchor.lead_field_factor_plus,1),rp],size(anchor.lead_field_factor_plus)};
  template=struct('field_path','','expected_shape',[], ...
    'actual_shape',[],'pass',false);
  out=repmat(template,size(rows,1),1);
  for j=1:size(rows,1)
    out(j)=struct('field_path',rows{j,1},'expected_shape',rows{j,2}, ...
      'actual_shape',rows{j,3},'pass',isequal(rows{j,2},rows{j,3}));
  end
end

function out=LOCAL_consumer_death_ledger()
  rows={ ...
    'finest_factors.staged.certificate.Pminus',{'wall','circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.Pplus',{'wall','circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.Gminus',{'wall','circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.Gplus',{'wall','circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.cminus',{'wall','circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.cplus',{'wall','circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.eta_unit_256',{'wall','circle'},'circle'; ...
    'finest_factors.staged.certificate.xi_left_unit_512',{'wall','circle'},'circle'; ...
    'finest_factors.staged.certificate.xi_right_unit_512',{'wall','circle'},'circle'; ...
    'finest_factors.staged.certificate.wall_input_unit_512',{'wall'},'wall'; ...
    'finest_factors.staged.certificate.q_center',{'wall'},'wall'; ...
    'finest_factors.staged.certificate.branch_port.gamma_m',{'wall'},'wall'; ...
    'finest_factors.staged.certificate.center_actual_left_trace',{'circle'},'circle'; ...
    'finest_factors.staged.certificate.center_actual_right_trace',{'circle'},'circle'; ...
    'finest_factors.staged.certificate.center_shared_left_trace',{'circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.center_shared_right_trace',{'circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.center_left_value_mismatch',{'circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.center_right_value_mismatch',{'circle','fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.center_wall_jumps.left_coefficients',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.certificate.center_wall_jumps.right_coefficients',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.delta_plus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.delta_minus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.circle_jump_plus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.circle_jump_minus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.Jplus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.Jminus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.wall_common_y_1024',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.wall_common_value_1024',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.raw_maps.wall_input_unit_512',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.B_wall',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.B_circle',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.B_volume',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.M_tilde',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.N_tilde',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.tail_minus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.tail_plus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.first_level_indices',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.lead_field_factor_minus',{'fullp_cap'},'fullp_cap'; ...
    'finest_factors.staged.ordinary_anchor.lead_field_factor_plus',{'fullp_cap'},'fullp_cap'};
  template=struct('field_path','','consumer_set',{{}}, ...
    'unique_last_consumer','','death','');
  out=repmat(template,size(rows,1),1);
  for j=1:size(rows,1)
    out(j)=struct('field_path',rows{j,1},'consumer_set',{rows{j,2}}, ...
      'unique_last_consumer',rows{j,3}, ...
      'death',['immediately after ',rows{j,3}]);
  end
end

%% ==================== Typed result utilities ====================
% Resource values are deterministic active-object proxies, not process RSS.

function out=LOCAL_anchor_summary(s)
  if ~isfield(s,'ordinary_anchor'), out=struct(); return; end
  a=s.ordinary_anchor;
  out=struct('B_wall',a.B_wall,'B_circle',a.B_circle, ...
    'B_volume',a.B_volume,'M_tilde',a.M_tilde,'N_tilde',a.N_tilde, ...
    'tail_minus_selected_N',a.tail_minus.selected_N, ...
    'tail_plus_selected_N',a.tail_plus.selected_N,'ordinary_double',true);
end

function out=LOCAL_dimension_summary(s)
  if ~isfield(s,'certificate'), out=struct(); return; end
  z=s.certificate;
  out=struct('K',z.K,'rminus',size(z.Pminus,1), ...
    'rplus',size(z.Pplus,1),'Pminus_shape',size(z.Pminus), ...
    'Pplus_shape',size(z.Pplus),'Gminus_shape',size(z.Gminus), ...
    'Gplus_shape',size(z.Gplus));
end

function out=LOCAL_compact_field(s,name)
  if isfield(s,name), out=s.(name); else, out=struct(); end
end

function out=LOCAL_resource_record(before,input_alias,peak,returned,c)
  exclusive=max(0,peak-input_alias);
  concurrent=before+max(c.worst_transient_mib,exclusive);
  out=struct('retained_before_mib',before, ...
    'input_alias_nominal_mib',input_alias, ...
    'local_workspace_peak_mib',peak,'module_exclusive_peak_mib',exclusive, ...
    'frozen_streaming_transient_mib',c.worst_transient_mib, ...
    'concurrent_peak_candidate_mib',concurrent, ...
    'return_payload_mib',returned,'retained_after_mib',NaN, ...
    'cumulative_peak_candidate_mib',NaN, ...
    'proxy_semantics',[ ...
      'deterministic active-object proxy; not RSS, allocator high-water, ', ...
      'reference-count, or copy-on-write proof']);
end

function out=LOCAL_zero_counters()
  out=struct('candidate_solve_calls',0,'qz_solve_calls',0, ...
    'coordinate_solve_calls',0,'propagation_solve_calls',0, ...
    'wall_density_solve_calls',0,'circle_density_solve_calls',0, ...
    'schur_solve_calls',0,'proxy_build_calls',0, ...
    'harmonic_action_calls',0,'image_pair_updates',0, ...
    'kress_oracle_calls',0,'linton_oracle_calls',0, ...
    'actual_deltaT_action_calls',0,'finite_bloch_image_updates',0, ...
    'riccati_calls',0,'gauss_factor_calls',0, ...
    'full_p_contraction_calls',0, ...
    'small_hermitian_gram_diagnostic_eig_calls',0, ...
    'gauss_golub_welsch_eig_calls',0, ...
    'n_op_signature_parity',0,'n_op_combined_gram_parity',0);
end

function out=LOCAL_empty_warnings()
  out=struct('code',{},'value',{},'blocking',{});
end

function out=LOCAL_condition(code,message)
  out=struct('code',char(code),'message',char(message));
end

function value=LOCAL_workspace_mib()
  info=evalin('caller','whos'); value=sum([info.bytes])/2^20;
end

function value=LOCAL_value_mib(item)
  info=whos('item'); value=info.bytes/2^20;
end

function out=LOCAL_owner_inventory()
  info=evalin('caller','whos'); out=cell(numel(info),1);
  for j=1:numel(info)
    out{j}=struct('name',info(j).name,'class',info(j).class, ...
      'size',info(j).size,'bytes',info(j).bytes);
  end
end
