function plot_geom = build_col_lat_geom(plot_window, col_lat, opts)
% BUILD_COL_LAT_GEOM Build visible geometry for a column lattice.
%
% Purpose:
%   Construct geometry metadata for all column-lattice cells whose complete
%   cell boxes intersect a plotting window.  The function does not draw
%   anything and does not mask field values.
%
% Input:
%   plot_window:
%     Struct describing the visible window.  Preferred fields are
%       plot_window.xlim = [x_min, x_max]
%       plot_window.ylim = [y_min, y_max].
%     For compatibility with existing scripts, fields x_min, x_max, y_min,
%     and y_max are also accepted.
%
%   col_lat:
%     Struct describing a column lattice with one possible obstacle per cell:
%       col_lat.C0 = [X0_minus, X0_plus; Y0_minus, Y0_plus]
%       col_lat.left.Lx = L_minus
%       col_lat.left.flag_geom = flag_geom_minus
%       col_lat.left.q = q_minus
%       col_lat.center.flag_geom = flag_geom_0
%       col_lat.center.q = q_0
%       col_lat.right.Lx = L_plus
%       col_lat.right.flag_geom = flag_geom_plus
%       col_lat.right.q = q_plus.
%     The q vectors are 2-by-1 translation centers for the origin-centered
%     contour generated by geom.construct_cont in each reference cell.  The
%     y-period is inferred from C0 and is not assumed to be [0,d].  Optional
%     fields left.geom_args, center.geom_args, and right.geom_args may be
%     cell arrays passed to geom.construct_cont after nt_contour, flag_geom,
%     0, 0.  If flag_geom is 'none', no contour is constructed for that
%     region.
%
%   opts:
%     Optional geometry options:
%       opts.nt_contour - Contour samples for geom.construct_cont.
%       opts.cell_lines - 'none', 'center', or 'all'.  The function records
%                         the corresponding vertical line x-coordinates but
%                         does not draw them.
%
% Output:
%   plot_geom:
%     Struct with fields:
%       window, C0, Cminus, Cplus, x_period_minus, x_period_plus, y_period,
%       cells, cell_lines, and opts.
%     Each plot_geom.cells(k) has fields:
%       region     - 'left', 'center', or 'right'
%       ix         - x-cell index, with ix=0 center, ix>0 right, ix<0 left
%       iy         - y-period index
%       box        - [x_min, x_max; y_min, y_max] complete global cell box
%       flag_geom  - Geometry flag such as 'circle', 'star', or 'none'
%       instance   - [] for 'none', otherwise a struct with fields center
%                    and xy, where xy is an n-by-2 global boundary array.
%
% Notes:
%   plot_geom.cells(k).box is always the full cell box and is never clipped
%   to plot_window.  Display clipping is left to axes xlim/ylim.

  if nargin < 3 || isempty(opts)
    opts = struct();
  end

  plot_window = LOCAL_normalize_plot_window(plot_window);
  opts = LOCAL_default_opts(opts);
  col_lat = LOCAL_normalize_col_lat(col_lat);

  C0 = col_lat.C0;
  X0_minus = C0(1, 1);
  X0_plus = C0(1, 2);
  Y0_minus = C0(2, 1);
  Y0_plus = C0(2, 2);
  d = Y0_plus - Y0_minus;
  L_minus = col_lat.left.Lx;
  L_plus = col_lat.right.Lx;

  Cminus = [X0_minus - L_minus, X0_minus; Y0_minus, Y0_plus];
  Cplus = [X0_plus, X0_plus + L_plus; Y0_minus, Y0_plus];

  ref.center = LOCAL_reference_obstacle(col_lat.center, C0, opts.nt_contour, ...
    'center');
  ref.left = LOCAL_reference_obstacle(col_lat.left, Cminus, opts.nt_contour, ...
    'left');
  ref.right = LOCAL_reference_obstacle(col_lat.right, Cplus, opts.nt_contour, ...
    'right');

  cells = LOCAL_visible_cells(plot_window, C0, Cminus, Cplus, ...
    L_minus, L_plus, d, col_lat, ref);
  x_cell_lines = LOCAL_cell_line_positions(plot_window.xlim, C0, ...
    L_minus, L_plus, opts.cell_lines);

  plot_geom.window = plot_window;
  plot_geom.C0 = C0;
  plot_geom.Cminus = Cminus;
  plot_geom.Cplus = Cplus;
  plot_geom.x_period_minus = L_minus;
  plot_geom.x_period_plus = L_plus;
  plot_geom.y_period = d;
  plot_geom.cells = cells;
  plot_geom.cell_lines.mode = opts.cell_lines;
  plot_geom.cell_lines.x = x_cell_lines(:);
  plot_geom.opts = opts;

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function plot_window = LOCAL_normalize_plot_window(plot_window)
% LOCAL_NORMALIZE_PLOT_WINDOW Accept xlim/ylim or x_min/x_max fields.

  if ~isstruct(plot_window)
    error('viz:build_col_lat_geom:InvalidPlotWindow', ...
      'plot_window must be a struct.');
  end

  if isfield(plot_window, 'xlim') && ~isempty(plot_window.xlim)
    xlim_val = plot_window.xlim(:).';
  elseif all(isfield(plot_window, {'x_min', 'x_max'}))
    xlim_val = [plot_window.x_min, plot_window.x_max];
  else
    error('viz:build_col_lat_geom:MissingXLim', ...
      'plot_window must contain xlim or x_min/x_max.');
  end

  if isfield(plot_window, 'ylim') && ~isempty(plot_window.ylim)
    ylim_val = plot_window.ylim(:).';
  elseif all(isfield(plot_window, {'y_min', 'y_max'}))
    ylim_val = [plot_window.y_min, plot_window.y_max];
  else
    error('viz:build_col_lat_geom:MissingYLim', ...
      'plot_window must contain ylim or y_min/y_max.');
  end

  if length(xlim_val) ~= 2 || length(ylim_val) ~= 2 || ...
      any(~isfinite(xlim_val)) || any(~isfinite(ylim_val)) || ...
      xlim_val(2) <= xlim_val(1) || ylim_val(2) <= ylim_val(1)
    error('viz:build_col_lat_geom:InvalidWindowLimits', ...
      'xlim and ylim must be finite increasing two-entry vectors.');
  end

  plot_window.xlim = xlim_val;
  plot_window.ylim = ylim_val;
  plot_window.x_min = xlim_val(1);
  plot_window.x_max = xlim_val(2);
  plot_window.y_min = ylim_val(1);
  plot_window.y_max = ylim_val(2);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function opts = LOCAL_default_opts(opts)
% LOCAL_DEFAULT_OPTS Fill missing geometry options.

  if ~isfield(opts, 'nt_contour') || isempty(opts.nt_contour)
    opts.nt_contour = 160;
  end
  if ~isfield(opts, 'cell_lines') || isempty(opts.cell_lines)
    opts.cell_lines = 'center';
  end

  if ~(isscalar(opts.nt_contour) && isfinite(opts.nt_contour) && ...
      opts.nt_contour >= 3 && opts.nt_contour == floor(opts.nt_contour))
    error('viz:build_col_lat_geom:InvalidNtContour', ...
      'opts.nt_contour must be an integer at least 3.');
  end
  opts.cell_lines = LOCAL_normalize_string(opts.cell_lines);
  if ~any(strcmp(opts.cell_lines, {'none', 'center', 'all'}))
    error('viz:build_col_lat_geom:InvalidCellLines', ...
      'opts.cell_lines must be ''none'', ''center'', or ''all''.');
  end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function col_lat = LOCAL_normalize_col_lat(col_lat)
% LOCAL_NORMALIZE_COL_LAT Validate the column-lattice struct.

  if ~isstruct(col_lat) || ~isfield(col_lat, 'C0')
    error('viz:build_col_lat_geom:InvalidColLat', ...
      'col_lat must be a struct containing C0.');
  end
  C0 = col_lat.C0;
  if ~isequal(size(C0), [2, 2]) || any(~isfinite(C0(:))) || ...
      C0(1, 2) <= C0(1, 1) || C0(2, 2) <= C0(2, 1)
    error('viz:build_col_lat_geom:InvalidC0', ...
      'col_lat.C0 must be [x_min,x_max; y_min,y_max] with increasing limits.');
  end
  col_lat.C0 = C0;

  col_lat.left = LOCAL_normalize_region(col_lat, 'left', true);
  col_lat.center = LOCAL_normalize_region(col_lat, 'center', false);
  col_lat.right = LOCAL_normalize_region(col_lat, 'right', true);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function region = LOCAL_normalize_region(col_lat, name, needs_period)
% LOCAL_NORMALIZE_REGION Validate one region struct.

  if ~isfield(col_lat, name) || ~isstruct(col_lat.(name))
    error('viz:build_col_lat_geom:MissingRegion', ...
      'col_lat.%s must be provided.', name);
  end
  region = col_lat.(name);

  if needs_period
    if ~isfield(region, 'Lx') || isempty(region.Lx) || ...
        ~(isscalar(region.Lx) && isfinite(region.Lx) && region.Lx > 0)
      error('viz:build_col_lat_geom:InvalidPeriod', ...
        'col_lat.%s.Lx must be a positive finite scalar.', name);
    end
  else
    region.Lx = NaN;
  end

  if ~isfield(region, 'flag_geom') || isempty(region.flag_geom)
    error('viz:build_col_lat_geom:MissingFlagGeom', ...
      'col_lat.%s.flag_geom must be provided.', name);
  end
  region.flag_geom = LOCAL_normalize_string(region.flag_geom);

  if ~isfield(region, 'q') || isempty(region.q)
    region.q = [0; 0];
  end
  region.q = region.q(:);
  if length(region.q) ~= 2 || any(~isfinite(region.q))
    error('viz:build_col_lat_geom:InvalidCenter', ...
      'col_lat.%s.q must be a finite two-entry vector.', name);
  end

  if ~isfield(region, 'geom_args') || isempty(region.geom_args)
    region.geom_args = {};
  elseif ~iscell(region.geom_args)
    region.geom_args = {region.geom_args};
  end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function ref = LOCAL_reference_obstacle(region, ref_box, nt_contour, name)
% LOCAL_REFERENCE_OBSTACLE Build and validate a reference obstacle contour.

  ref.flag_geom = region.flag_geom;
  ref.center = region.q(:).';
  ref.xy = [];

  if strcmp(region.flag_geom, 'none')
    return;
  end

  [C, ~, ~, ~] = geom.construct_cont(nt_contour, region.flag_geom, ...
    0, 0, region.geom_args{:});
  xy = [C(1, :).', C(4, :).'] + region.q(:).';

  tol_box = 100 * eps(max(1, max(abs(ref_box(:)))));
  inside_x = xy(:, 1) >= ref_box(1, 1) - tol_box & ...
    xy(:, 1) <= ref_box(1, 2) + tol_box;
  inside_y = xy(:, 2) >= ref_box(2, 1) - tol_box & ...
    xy(:, 2) <= ref_box(2, 2) + tol_box;
  if any(~inside_x | ~inside_y)
    error('viz:build_col_lat_geom:ContourOutsideCell', ...
      '%s contour is not contained in its reference cell.', name);
  end

  ref.xy = xy;

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function cells = LOCAL_visible_cells(plot_window, C0, Cminus, Cplus, ...
    L_minus, L_plus, d, col_lat, ref)
% LOCAL_VISIBLE_CELLS Expand visible cells intersecting the plot window.

  iy_min = floor((plot_window.ylim(1) - C0(2, 2)) / d) - 1;
  iy_max = ceil((plot_window.ylim(2) - C0(2, 1)) / d) + 1;

  cells = LOCAL_empty_cells();

  for iy = iy_min:iy_max
    y_shift = iy * d;
    center_box = C0 + [0, 0; y_shift, y_shift];
    if LOCAL_boxes_intersect(center_box, plot_window)
      cells(end + 1) = LOCAL_make_cell('center', 0, iy, center_box, ...
        col_lat.center.flag_geom, ref.center, [0, y_shift]); %#ok<AGROW>
    end
  end

  ix_right_min = max(1, floor((plot_window.xlim(1) - C0(1, 2)) / L_plus) - 1);
  ix_right_max = max(0, ceil((plot_window.xlim(2) - C0(1, 2)) / L_plus) + 1);
  for ix = ix_right_min:ix_right_max
    x_shift = (ix - 1) * L_plus;
    for iy = iy_min:iy_max
      y_shift = iy * d;
      box = Cplus + [x_shift, x_shift; y_shift, y_shift];
      if LOCAL_boxes_intersect(box, plot_window)
        cells(end + 1) = LOCAL_make_cell('right', ix, iy, box, ...
          col_lat.right.flag_geom, ref.right, [x_shift, y_shift]); %#ok<AGROW>
      end
    end
  end

  j_left_min = max(1, floor((C0(1, 1) - plot_window.xlim(2)) / L_minus) - 1);
  j_left_max = max(0, ceil((C0(1, 1) - plot_window.xlim(1)) / L_minus) + 1);
  for j = j_left_min:j_left_max
    ix = -j;
    x_shift = -(j - 1) * L_minus;
    for iy = iy_min:iy_max
      y_shift = iy * d;
      box = Cminus + [x_shift, x_shift; y_shift, y_shift];
      if LOCAL_boxes_intersect(box, plot_window)
        cells(end + 1) = LOCAL_make_cell('left', ix, iy, box, ...
          col_lat.left.flag_geom, ref.left, [x_shift, y_shift]); %#ok<AGROW>
      end
    end
  end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function cells = LOCAL_empty_cells()
% LOCAL_EMPTY_CELLS Return an empty cell-geometry struct array.

  cells = struct('region', {}, 'ix', {}, 'iy', {}, 'box', {}, ...
    'flag_geom', {}, 'instance', {});

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function cell_entry = LOCAL_make_cell(region_name, ix, iy, box, flag_geom, ...
    ref, shift)
% LOCAL_MAKE_CELL Construct one visible cell entry.

  cell_entry.region = region_name;
  cell_entry.ix = ix;
  cell_entry.iy = iy;
  cell_entry.box = box;
  cell_entry.flag_geom = flag_geom;

  if strcmp(flag_geom, 'none')
    cell_entry.instance = [];
  else
    xy = ref.xy + shift;
    cell_entry.instance.center = ref.center + shift;
    cell_entry.instance.xy = xy;
  end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function tf = LOCAL_boxes_intersect(box, plot_window)
% LOCAL_BOXES_INTERSECT Return true when a cell box intersects the window.

  tf = box(1, 1) <= plot_window.xlim(2) && ...
    box(1, 2) >= plot_window.xlim(1) && ...
    box(2, 1) <= plot_window.ylim(2) && ...
    box(2, 2) >= plot_window.ylim(1);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function x_lines = LOCAL_cell_line_positions(xlim_val, C0, L_minus, L_plus, mode)
% LOCAL_CELL_LINE_POSITIONS Choose visible vertical cell-boundary lines.

  switch mode
    case 'none'
      x_lines = zeros(0, 1);
    case 'center'
      x_lines = [C0(1, 1); C0(1, 2)];
      x_lines = x_lines(x_lines >= xlim_val(1) & x_lines <= xlim_val(2));
    case 'all'
      x_lines = [C0(1, 1); C0(1, 2)];

      n_right_min = floor((xlim_val(1) - C0(1, 2)) / L_plus) - 1;
      n_right_max = ceil((xlim_val(2) - C0(1, 2)) / L_plus) + 1;
      for n = n_right_min:n_right_max
        x_lines(end + 1, 1) = C0(1, 2) + n * L_plus; %#ok<AGROW>
      end

      n_left_min = floor((C0(1, 1) - xlim_val(2)) / L_minus) - 1;
      n_left_max = ceil((C0(1, 1) - xlim_val(1)) / L_minus) + 1;
      for n = n_left_min:n_left_max
        x_lines(end + 1, 1) = C0(1, 1) - n * L_minus; %#ok<AGROW>
      end

      x_lines = unique(x_lines);
      x_lines = x_lines(x_lines >= xlim_val(1) & x_lines <= xlim_val(2));
    otherwise
      error('viz:build_col_lat_geom:InvalidCellLines', ...
        'Unsupported cell line mode.');
  end

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function str = LOCAL_normalize_string(str)
% LOCAL_NORMALIZE_STRING Convert string scalars to trimmed lower char rows.

  if isstring(str)
    if ~isscalar(str)
      error('viz:build_col_lat_geom:InvalidString', ...
        'Expected a character vector or string scalar.');
    end
    str = char(str);
  end
  if ~(ischar(str) && isrow(str))
    error('viz:build_col_lat_geom:InvalidString', ...
      'Expected a character vector or string scalar.');
  end
  str = lower(strtrim(str));

end
