function result = check_h_struct(attempt)
%CHECK_H_STRUCT Run the compact I2.2 two-endpoint structure diagnostic.
% Purpose:
%   Reproduce the I2.2 endpoint objects with the reviewed I2.1 evaluator and
%   stop before inertia because the exact Hermitian and interval-continuity
%   proofs remain unavailable.
% Input:
%   attempt - New append-only output tag, for example 'compact-a1'.
% Output:
%   result  - Configuration, endpoint objects, diagnostics, and verdict.
% Main algorithm:
%   Seed the frozen fine-M48 evaluator at the I1.3 center, evaluate only the
%   two registered L14 shoulder points, construct T, N0, L, H=A/T and C0,
%   check the unchanged numerical gates, and record unavailable inertia.
% Based on:
%   The historical cfg_i22, eval_i22, and run_i22 files archived below the
%   experiment output directory.
% Main changes:
%   One portable numerical entry point; no repository discovery, provenance
%   manifests, history reads, scan, root solve, symmetrization, or inertia.
% Numerical goal:
%   Preserve the reviewed finite-dimensional endpoint calculation while
%   making the theory-gate stop explicit and inexpensive to reproduce.

  attempt = LOCAL_attempt(attempt);
  here = fileparts(mfilename('fullpath'));
  output = fullfile(here,'output',attempt);
  if exist(output,'dir') || exist(output,'file')
    error('i22:OutputExists','Output already exists: %s.',output);
  end
  LOCAL_runtime();

  c = LOCAL_config();
  timer = tic;
  peak_active_mib = 0;
  selectors = LOCAL_selectors();
  [seed,frame] = eval_i21('seed',c,selectors);
  LOCAL_seed_gate(seed,frame,c);
  peak_active_mib = LOCAL_budget(timer,c,peak_active_mib,{seed,frame});

  labels = {'L','R'};
  kvals = [c.k_left,c.k_right];
  nodes = repmat(LOCAL_empty_endpoint(),2,1);
  for j = 1:2
    node = eval_i21('point',kvals(j),c,frame);
    LOCAL_node_gate(node,kvals(j),frame,c);
    [objects,diagnostics] = LOCAL_objects(node,c);
    nodes(j) = LOCAL_endpoint(labels{j},node,objects,diagnostics,c);
    peak_active_mib = LOCAL_budget(timer,c,peak_active_mib, ...
      {node,frame,objects,diagnostics,nodes});
  end

  gates = LOCAL_gates(nodes,c);
  if ~gates.branch_qz_chart
    error('i22:BranchQZChart','The inherited branch, QZ, or chart gate failed.');
  end
  if ~gates.factor_health
    error('i22:FactorHealth','An inherited factor gate failed.');
  end
  if ~gates.T_invertible
    error('i22:TNotInvertible','A shoulder failed the registered T gate.');
  end
  if ~gates.object_equivalence
    error('i22:ObjectEquivalence','A registered A/H identity gate failed.');
  end
  if ~gates.structure_finite
    error('i22:StructureNonfinite','A raw structure diagnostic is nonfinite.');
  end

  inertia = repmat(struct('endpoint','','available',false, ...
    'n_pos',NaN,'n_neg',NaN,'n_zero',NaN,'min_abs_eig',NaN, ...
    'algorithm','NOT_RUN_EXACT_HERMITIAN_GATE'),2,1);
  inertia(1).endpoint = 'L';
  inertia(2).endpoint = 'R';
  result = struct( ...
    'experiment_id','I2-H-STRUCTURE-DIAGNOSTIC-V1', ...
    'attempt',attempt, ...
    'status','I2_2_STOP_THEORY_GATE', ...
    'pass',false, ...
    'first_unmet_condition','EXACT_HERMITIAN_NOT_ESTABLISHED', ...
    'claim_boundary','FROZEN_FINE_M48_FINITE_DIMENSIONAL_OBJECT', ...
    'elapsed_seconds',toc(timer), ...
    'peak_active_mib',peak_active_mib, ...
    'configuration',c, ...
    'seed',LOCAL_seed_summary(seed,frame), ...
    'endpoints',nodes, ...
    'gates',gates, ...
    'exact_finite_hermitian_proof',false, ...
    'continuous_same_family_interval_proof',false, ...
    'inertia_available',false, ...
    'inertia',inertia, ...
    'inertia_jump','UNAVAILABLE', ...
    'conclusion',['Both frozen endpoints were evaluated, but inertia is ' ...
      'not mathematically available because both structure proofs are open.']);

  mkdir(output);
  save(fullfile(output,'result.mat'),'result','-v7');
  LOCAL_report(fullfile(output,'report.md'),result);
end

%% ==================== Frozen numerical configuration ====================
% These helpers contain only inputs required by the I2.1 evaluator and I2.2.

function c = LOCAL_config()
  c = struct();
  c.beta = 0.5; c.d = 1.0; c.R = 0.2; c.s = 1.0;
  c.X_L = -0.5; c.X_R = 0.5; c.H = 1.1; c.proxy_dist = 0.2;
  c.M = 48; c.K = 97; c.kstar = 1.8327703475952146;
  c.level = struct('name','fine','ntot',256,'N_side',160, ...
    'N_top',160,'N_proxy_edge',80,'M_pw',32);
  c.expected = struct('proxy_rows',960,'proxy_columns',450, ...
    'proxy_shifted_rows',1920,'proxy_shifted_columns',450, ...
    'proxy_rank',260,'bie_order',512,'pencil_order',194, ...
    'chart_order',97,'adef_order',194,'graph_order',388);

  c.proxy_rank_ratio = 1e-8;
  c.proxy_rank_gap_min = 2;
  c.proxy_projector_repeat_tol = 1e-10;
  c.proxy_rcond_min = 1e-8;
  c.proxy_projected_tol = 1e-11;
  c.proxy_full_residual_max = 1e-5;
  c.proxy_shifted_residual_max = 1e-5;
  c.proxy_seed_identity_tol = 1e-12;
  c.branch_tol = 1e-12;
  c.qz_residual_tol = 1e-10;
  c.qz_overlap_min = 0.9;
  c.cross_cluster_margin_min = 100*c.K*eps;
  c.chart_margin_min = 100*c.K*eps;
  c.chart_condition_eps_tol = 1e-9;
  c.small_solve_residual_tol = 1e3*c.K*eps;
  c.bie_rcond_min = 1e-8;
  c.bie_residual_tol = 1e-10;
  c.schur_tol = 1e3*c.K*eps;
  c.dirichlet_rcond_min = 1e-8;
  c.participation_min = 1e-3;
  c.lift_residual_tol = 1e-10;

  c.k_left = 1.8327701568603514;
  c.k_right = 1.8327705383300779;
  c.l14_outer = [1.8327697753906247,1.8327705383300779];
  c.i21_real_diameter = [1.8327699661254881,1.8327707290649411];
  c.T_rcond_min = 1e-8;
  c.phase_square_separation_min = 1e-8;
  c.identity_residual_max = 1e3*(2*c.K)*eps;
  c.target_seconds = 60;
  c.hard_seconds = 180;
  c.memory_mib_max = 512;
end

function rows = LOCAL_selectors()
  rows.plus = [89 41 35 71 92 12 16 10 66 70 93 33 9 69 79 30 36 ...
    62 64 84 95 40 18 91 94 58 61 13 85 90 24 32 42 60 28 74 21 ...
    97 22 55 77 96 38 14 17 2 20 1 67 75 37 43 72 5 80 81 82 7 ...
    68 39 25 19 78 29 6 76 86 59 8 4 65 83 23 31 3 73 57 63 56 ...
    26 88 27 11 87 15 34 54 44 53 45 52 46 51 47 50 48 49];
  rows.minus = [162 132 117 174 103 124 134 140 173 194 101 172 186 ...
    120 167 168 170 178 189 100 153 180 192 110 118 121 125 169 175 ...
    176 185 119 160 164 179 108 113 114 131 165 171 183 193 111 128 ...
    133 139 159 181 190 191 106 129 157 163 135 116 127 155 177 102 ...
    104 126 130 137 156 184 109 138 187 115 136 154 161 166 158 123 ...
    98 122 105 188 112 152 99 182 107 151 141 150 142 149 143 148 ...
    144 147 145 146];
end

function attempt = LOCAL_attempt(value)
  if nargin ~= 1 || ~(ischar(value) || (isstring(value) && isscalar(value)))
    error('i22:Attempt','Supply one explicit attempt name.');
  end
  attempt = char(value);
  if isempty(regexp(attempt,'^[a-z0-9][a-z0-9-]*$','once'))
    error('i22:Attempt','Attempt names use lowercase letters, digits, and hyphens.');
  end
end

function LOCAL_runtime()
  matches = which('eval_i21','-all');
  if ischar(matches), matches = cellstr(matches); end
  solver = which('lsqminnorm');
  if exist('OCTAVE_VERSION','builtin') ~= 0 || isempty(solver) || ...
      ~startsWith(solver,matlabroot)
    error('i22:MATLABRequired','MATLAB with lsqminnorm is required.');
  end
  if numel(matches) ~= 1
    error('i22:EvaluatorPath','Exactly one eval_i21 must be on the MATLAB path.');
  end
end

function peak = LOCAL_budget(timer,c,peak,values)
  info = whos('values');
  peak = max(peak,sum([info.bytes])/2^20);
  if toc(timer) > c.hard_seconds || peak > c.memory_mib_max
    error('i22:Resource','The registered time or active-memory gate failed.');
  end
end

%% ==================== Same-object construction ====================
% These helpers preserve the historical A, T, N0, L, H, and C0 formulas.

function [o,d] = LOCAL_objects(node,c)
  K = c.K;
  LOCAL_shape(node.AdefD,2*K,2*K,'AdefD');
  LOCAL_shape(node.pair.A,2*K,2*K,'pencil A');
  LOCAL_shape(node.pair.B,2*K,2*K,'pencil B');
  LOCAL_shape(node.Dm,K,K,'Dm'); LOCAL_shape(node.Nm,K,K,'Nm');
  LOCAL_shape(node.Dp,K,K,'Dp'); LOCAL_shape(node.Np,K,K,'Np');
  LOCAL_shape(node.cm.Lambda,K,K,'Lambda minus');
  LOCAL_shape(node.cp.Lambda,K,K,'Lambda plus');
  if numel(node.gamma) ~= K || numel(node.phase) ~= K
    error('i22:ObjectShape','Channel dimensions drifted.');
  end
  I = eye(K); Gamma = diag(node.gamma(:)); E = diag(node.phase(:));
  T = [I,E;E,I];
  N0 = [-1i*Gamma,1i*Gamma*E;1i*Gamma*E,-1i*Gamma];
  L = blkdiag(node.cm.Lambda,node.cp.Lambda);
  A = node.AdefD; H = A/T; C0 = N0/T;
  d = struct( ...
    'T_rcond',rcond(T), ...
    'T_sigma_min',min(svd(T,'econ')), ...
    'min_abs_1_minus_E2',min(abs(1-node.phase(:).^2)), ...
    'H_right_solve_residual',LOCAL_product(A,H,T), ...
    'C0_right_solve_residual',LOCAL_product(N0,C0,T), ...
    'block_identity_defect',LOCAL_sum(A,N0,L,T), ...
    'A_HT_defect',LOCAL_product(A,H,T), ...
    'C0_hermitian_defect',LOCAL_hermitian(C0), ...
    'Lambda_minus_hermitian_defect',LOCAL_hermitian(node.cm.Lambda), ...
    'Lambda_plus_hermitian_defect',LOCAL_hermitian(node.cp.Lambda), ...
    'graph_minus_lagrangian_defect',LOCAL_graph(node.Dm,node.Nm), ...
    'graph_plus_lagrangian_defect',LOCAL_graph(node.Dp,node.Np), ...
    'H_hermitian_defect',LOCAL_hermitian(H), ...
    'block_model_direct_defect',norm(A-(N0-L*T),'fro')/ ...
      max(1,norm(A,'fro')+norm(N0-L*T,'fro')));
  values = struct2cell(d);
  d.all_finite = all(cellfun(@(x) isscalar(x) && isfinite(x),values));
  o = struct('k',node.k,'A',A,'Gamma',Gamma,'E',E,'T',T,'N0',N0, ...
    'L',L,'H',H,'C0',C0,'D_minus',node.Dm,'N_minus',node.Nm, ...
    'D_plus',node.Dp,'N_plus',node.Np, ...
    'Lambda_minus',node.cm.Lambda,'Lambda_plus',node.cp.Lambda, ...
    'pencil_A',node.pair.A,'pencil_B',node.pair.B);
end

function LOCAL_shape(A,m,n,name)
  if ~isequal(size(A),[m,n]) || ~all(isfinite(A(:)))
    error('i22:ObjectShape','%s shape or finite-value gate failed.',name);
  end
end

function value = LOCAL_hermitian(X)
  value = norm(X-X','fro')/max(1,norm(X,'fro'));
end

function value = LOCAL_graph(D,N)
  X = D'*N;
  value = norm(X-X','fro')/max(1,norm(X,'fro'));
end

function value = LOCAL_product(A,B,C)
  value = norm(A-B*C,'fro')/max(1, ...
    norm(A,'fro')+norm(B,'fro')*norm(C,'fro'));
end

function value = LOCAL_sum(A,N0,L,T)
  value = norm(A-(N0-L*T),'fro')/max(1, ...
    norm(A,'fro')+norm(N0,'fro')+norm(L,'fro')*norm(T,'fro'));
end

%% ==================== Endpoint gates and compact result ====================
% These helpers retain the reviewed numerical predicates without ledgers.

function LOCAL_seed_gate(seed,frame,c)
  ok = seed.k == c.kstar && seed.pass && all([seed.factors.pass]) && ...
    isequal(size(seed.R),[c.expected.proxy_rank,c.expected.proxy_rank]) && ...
    isequal(seed.proxy_shape,[c.expected.proxy_rows, ...
      c.expected.proxy_columns]) && ...
    isequal(seed.proxy_shifted_shape,[c.expected.proxy_shifted_rows, ...
      c.expected.proxy_shifted_columns]) && ...
    isequal(size(seed.Aqp),[c.expected.bie_order,c.expected.bie_order]) && ...
    isequal(size(seed.AdefD),[2*c.K,2*c.K]) && ...
    isequal(size(seed.pair.A),[2*c.K,2*c.K]) && ...
    isequal(size(seed.pair.B),[2*c.K,2*c.K]) && ...
    isequal(size(frame.Z0_plus),[2*c.K,c.K]) && ...
    isequal(size(frame.Z0_minus),[2*c.K,c.K]) && ...
    numel(frame.rows_plus) == c.K && numel(frame.rows_minus) == c.K && ...
    frame.proxy_chart.r == c.expected.proxy_rank;
  if ~ok, error('i22:SeedGate','The frozen seed/frame gate failed.'); end
end

function LOCAL_node_gate(node,k,frame,c)
  ok = node.k == k && strcmp(node.name,'fine') && node.pass && ...
    node.plus.pass && node.minus.pass && node.branch_port.pass && ...
    node.branch_proxy.pass && node.cp.safe && node.cm.safe && ...
    all([node.factors.pass]) && ...
    strcmp(node.branch_port.fingerprint,frame.port_anchor.fingerprint) && ...
    strcmp(node.branch_proxy.fingerprint, ...
      frame.proxy_chart.anchor.fingerprint) && ...
    strcmp(node.proxy_chart.fingerprint,frame.proxy_chart.fingerprint) && ...
    isequal(node.H_plus_rows,frame.rows_plus) && ...
    isequal(node.H_minus_rows,frame.rows_minus) && ...
    isequal(size(node.AdefD),[2*c.K,2*c.K]) && ...
    isequal(size(node.AdefG),[4*c.K,4*c.K]) && ...
    k > c.i21_real_diameter(1) && k < c.i21_real_diameter(2);
  if ~ok, error('i22:EndpointGate','An endpoint inherited gate failed.'); end
end

function out = LOCAL_endpoint(label,node,objects,diagnostics,c)
  out = LOCAL_empty_endpoint();
  out.label = label; out.k = node.k; out.inside_i21_disk = ...
    node.k > c.i21_real_diameter(1) && node.k < c.i21_real_diameter(2);
  out.branch_pass = node.branch_port.pass && node.branch_proxy.pass;
  out.qz_pass = node.plus.pass && node.minus.pass;
  out.chart_pass = node.cp.safe && node.cm.safe;
  out.factor_pass = all([node.factors.pass]);
  out.factors = node.factors;
  out.qz = struct('plus',LOCAL_qz(node.plus),'minus',LOCAL_qz(node.minus));
  out.fixed_rows = node.row;
  out.safe_dtn = struct('minus',node.cm,'plus',node.cp);
  out.schur_defect = node.schur;
  out.diagnostics = diagnostics;
  out.objects = objects;
end

function out = LOCAL_empty_endpoint()
  out = struct('label','','k',NaN,'inside_i21_disk',false, ...
    'branch_pass',false,'qz_pass',false,'chart_pass',false, ...
    'factor_pass',false,'factors',struct([]),'qz',struct(), ...
    'fixed_rows',struct(),'safe_dtn',struct(),'schur_defect',NaN, ...
    'diagnostics',struct(),'objects',struct());
end

function out = LOCAL_qz(q)
  out = struct('stable',q.stable_diagnostic,'unstable',q.unstable_diagnostic, ...
    'neutral',q.neutral_count,'infinite',q.infinite_count, ...
    'indeterminate',q.indeterminate_count,'unit_gap',q.unit_gap, ...
    'chordal_separation',q.chordal_separation,'overlap',q.overlap, ...
    'score_gap',q.score_gap,'classification_gap',q.classification_gap, ...
    'cluster_tau',q.cluster_tau, ...
    'raw_residual',q.raw_residual,'ordered_residual',q.residual, ...
    'match_pass',q.match_pass,'pass',q.pass);
end

function out = LOCAL_seed_summary(seed,frame)
  out = struct('k',seed.k,'pass',seed.pass,'factor_pass', ...
    all([seed.factors.pass]),'proxy_rank',frame.proxy_chart.r, ...
    'row_count_plus',numel(frame.rows_plus), ...
    'row_count_minus',numel(frame.rows_minus));
end

function g = LOCAL_gates(nodes,c)
  d = [nodes.diagnostics];
  g = struct( ...
    'branch_qz_chart',all([nodes.branch_pass]) && all([nodes.qz_pass]) && ...
      all([nodes.chart_pass]), ...
    'factor_health',all([nodes.factor_pass]), ...
    'T_invertible',all([d.T_rcond] >= c.T_rcond_min) && ...
      all([d.min_abs_1_minus_E2] >= c.phase_square_separation_min), ...
    'object_equivalence',all([d.block_identity_defect] <= ...
      c.identity_residual_max) && all([d.A_HT_defect] <= ...
      c.identity_residual_max) && all([d.H_right_solve_residual] <= ...
      c.identity_residual_max) && all([d.C0_right_solve_residual] <= ...
      c.identity_residual_max), ...
    'structure_finite',all([d.all_finite]), ...
    'exact_finite_hermitian_proof',false, ...
    'continuous_same_family_interval_proof',false, ...
    'endpoint_separation','NOT_REACHED', ...
    'inertia_jump','UNAVAILABLE');
end

%% ==================== Compact report ====================
% The report summarizes only the numerical result stored in result.mat.

function LOCAL_report(path,r)
  fid = fopen(path,'w');
  if fid < 0, error('i22:Report','Cannot create report.md.'); end
  cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
  fprintf(fid,'# I2.2 compact endpoint diagnostic\n\n');
  fprintf(fid,'- Attempt: `%s`\n',r.attempt);
  fprintf(fid,'- Status: `%s`\n',r.status);
  fprintf(fid,'- First unmet condition: `%s`\n',r.first_unmet_condition);
  fprintf(fid,'- Runtime / active-object peak: `%.3f s` / `%.3f MiB`\n', ...
    r.elapsed_seconds,r.peak_active_mib);
  fprintf(fid,'- Scientific endpoints: `%.17g`, `%.17g`\n', ...
    r.endpoints(1).k,r.endpoints(2).k);
  fprintf(fid,'- Inertia: `UNAVAILABLE`; positive, negative, and zero counts are `NaN`.\n\n');
  fprintf(fid,'| endpoint | rcond(T) | min abs(1-E^2) | A=N0-LT defect | A=HT defect | H Hermitian defect |\n');
  fprintf(fid,'|---|---:|---:|---:|---:|---:|\n');
  for j = 1:2
    d = r.endpoints(j).diagnostics;
    fprintf(fid,'| %s | %.6e | %.6e | %.6e | %.6e | %.6e |\n', ...
      r.endpoints(j).label,d.T_rcond,d.min_abs_1_minus_E2, ...
      d.block_identity_defect,d.A_HT_defect,d.H_hermitian_defect);
  end
  fprintf(fid,['\nThe same frozen fine-M48 evaluator completed both endpoints and the ' ...
    'registered numerical equivalence gates. The exact finite Hermitian and ' ...
    'whole-interval same-family proofs remain false, so this attempt does not ' ...
    'compute inertia, locate a root, or support a real-root conclusion.\n']);
end
