function [tau, zeta, tau_s, theta, audit] = ...
    i32v2_circle_density_grid(z, n)
%I32V2_CIRCLE_DENSITY_GRID Evaluate the frozen circle-density interpolant.
% Purpose:
%   Evaluate the same 256-node endpoint-grid Nystrom density on a requested
%   midpoint circle source/target grid without resolving the density.
% Input:
%   z - canonical certificate containing eta_unit_256.
%   n - requested even midpoint count (double integer).
% Output:
%   tau, zeta - n-by-194 double- and single-layer density coordinates.
%   tau_s    - angular derivative of the same tau interpolant.
%   theta    - n-by-1 midpoint angles.
%   audit    - compact interpolation and operation ledger.
% Based on:
%   design-3-2d fixed endpoint-density trigonometric prolongation.
% Notes:
%   This is density interpolation only, never a Fourier/Rayleigh field action.

n = double(n);
if ~isstruct(z) || ~isfield(z, 'eta_unit_256') || ...
    ~isa(z.eta_unit_256, 'double') || ...
    ~isequal(double(size(z.eta_unit_256)), [512.0, 194.0]) || ...
    any(~isfinite(z.eta_unit_256(:))) || ~isscalar(n) || ~isfinite(n) || ...
    n < 2.0 || n ~= fix(n) || mod(n, 2.0) ~= 0.0
  error('I32V2:CircleDensityGridInterface', ...
    'The frozen circle density or requested midpoint grid is invalid.');
end
native_count = double(size(z.eta_unit_256, 1)) / 2.0;
orders = (-native_count / 2.0:native_count / 2.0 - 1.0).';
tau_native = z.eta_unit_256(1.0:native_count, :);
zeta_native = z.eta_unit_256(native_count + 1.0:end, :);
tau_coeff = fftshift(fft(tau_native, [], 1), 1) / native_count;
zeta_coeff = fftshift(fft(zeta_native, [], 1), 1) / native_count;
theta = 2.0 * pi * ((0.0:n - 1.0).' + 0.5) / n;
basis = exp(1i * theta * orders.');
tau = basis * tau_coeff;
zeta = basis * zeta_coeff;
tau_s = basis * bsxfun(@times, 1i * orders, tau_coeff);
state_count = double(size(tau_coeff, 2));
audit = struct('schema', 'I32V2_CIRCLE_DENSITY_GRID_V1', ...
  'native_source_count', native_count, 'target_count', n, ...
  'state_count', state_count, 'endpoint_native_grid', true, ...
  'midpoint_evaluation_grid', true, 'negative_nyquist_order', orders(1), ...
  'density_resolve_count', 0.0, 'rayleigh_field_calls', 0.0, ...
  'complex_multiply_add_count', ...
  3.0 * n * native_count * state_count, ...
  'finite', all(isfinite([tau(:); zeta(:); tau_s(:)])), ...
  'symbol_ledger', struct( ...
  'tau', 'same frozen circle double-layer density interpolant', ...
  'zeta', 'same frozen circle coordinate zeta=-sigma interpolant', ...
  'tau_s', 'angular derivative of the tau interpolant'));
end
