function [value, normal, ledger, audit] = i32v2_circle_wall_action( ...
    z, g, cfg, trg, ntn, nw, level, variant)
%I32V2_CIRCLE_WALL_ACTION Stream both wall-density actions to circle targets.
% Purpose:
%   Apply the complete MFS-only quasi-periodic single-layer wall action to
%   circle value and material-normal targets using the same frozen density.
% Input:
%   z       - canonical certificate scalar/geometry struct.
%   g       - completed compact GQP table module.
%   cfg     - preregistered panel configuration.
%   trg     - 2-by-target_count circle targets.
%   ntn     - 2-by-target_count material normals.
%   nw      - even wall source count (double integer).
%   level   - i32v2_gqp_pair table level.
%   variant - registered GQP variant id.
% Output:
%   value, normal - target-by-state_count complete wall actions.
%   ledger        - typed executed interpolation/factor operation counts.
%   audit         - compact source-grid, panel, and forbidden-path record.
% Based on:
%   design-3-2d complete wall-to-circle cross interaction.
% Notes:
%   i32v2_gqp_pair is the sole Green-kernel gateway; no image sum is present.

nw = double(nw);
if ~isstruct(z) || ~all(isfield(z, {'d', 'X_L', 'X_R', ...
    'xi_left_unit_512', 'xi_right_unit_512'})) || ...
    ~isstruct(g) || ~isfield(g, 'available') || ~g.available || ...
    ~isstruct(cfg) || ~isfield(cfg, 'boundary_source_panel') || ...
    ~isa(trg, 'double') || ~isa(ntn, 'double') || ...
    ~isequal(size(trg), size(ntn)) || size(trg, 1) ~= 2 || ...
    any(~isfinite([trg(:); ntn(:)])) || ~isscalar(nw) || ...
    nw < 2.0 || nw ~= fix(nw) || mod(nw, 2.0) ~= 0.0
  error('I32V2:CircleWallActionInterface', ...
    'The canonical wall-to-circle action interface is invalid.');
end
[xi_left, y, ds, ~, left_density_audit] = ...
  i32v2_wall_density_grid(z.xi_left_unit_512, z, nw);
[xi_right, y_right, ds_right, ~, right_density_audit] = ...
  i32v2_wall_density_grid(z.xi_right_unit_512, z, nw);
if ~isequal(y, y_right) || ~isequal(ds, ds_right)
  error('I32V2:WallDensityGridMismatch', ...
    'The two frozen wall densities do not share one source grid.');
end

target_count = double(size(trg, 2));
state_count = double(size(xi_left, 2));
value = complex(zeros(target_count, state_count));
normal = value;
ledger = LOCAL_count_zero();
ledger.boundary_factor_cma = ...
  left_density_audit.complex_multiply_add_count + ...
  right_density_audit.complex_multiply_add_count;
completed_panels = 0.0;
source_panel = double(cfg.boundary_source_panel);
for side = 1.0:2.0
  if side == 1.0
    x = z.X_L;
    xi = xi_left;
  else
    x = z.X_R;
    xi = xi_right;
  end
  src = [x * ones(1.0, nw); y.'];
  for first = 1.0:source_panel:nw
    last = min(nw, first + source_panel - 1.0);
    ids = first:last;
    full = level;
    full.include_primary = true;
    [pot, gx, gy, ~, ~, ~, pair_audit] = ...
      i32v2_gqp_pair(g, src(:, ids), trg, full, variant);
    value = value + ds * pot * xi(ids, :);
    normal_kernel = bsxfun(@times, gx, ntn(1, :).') + ...
      bsxfun(@times, gy, ntn(2, :).');
    normal = normal + ds * normal_kernel * xi(ids, :);
    ledger.interpolation_cma = ledger.interpolation_cma + ...
      pair_audit.interpolation.all_field_complex_operation_count;
    ledger.kernel_phase_multiply = ledger.kernel_phase_multiply + ...
      pair_audit.bloch_phase_multiply_count;
    ledger.boundary_factor_cma = ledger.boundary_factor_cma + ...
      2.0 * target_count * double(numel(ids)) * state_count;
    completed_panels = completed_panels + 1.0;
  end
end
ledger.total = ledger.interpolation_cma + ledger.kernel_phase_multiply + ...
  ledger.boundary_factor_cma;
audit = struct('schema', 'I32V2_CIRCLE_WALL_ACTION_V1', ...
  'wall_source_count', nw, 'target_count', target_count, ...
  'completed_source_panels', completed_panels, ...
  'left_density', left_density_audit, 'right_density', right_density_audit, ...
  'density_resolve_count', 0.0, 'image_sum_calls', 0.0, ...
  'rayleigh_field_calls', 0.0, 'finite', ...
  all(isfinite([value(:); normal(:)])), ...
  'symbol_ledger', struct( ...
  'value', 'complete two-wall single-layer value action at circle targets', ...
  'normal', 'target-normal derivative of the same complete action'));
end

function ledger = LOCAL_count_zero()
ledger = struct('interpolation_cma', 0.0, ...
  'kernel_phase_multiply', 0.0, 'boundary_factor_cma', 0.0, ...
  'gram_cma', 0.0, 'factor_comparison', 0.0, ...
  'scalar_arithmetic', 0.0, 'total', 0.0);
end
