function [xi, y, ds, kappa, audit] = i32v2_wall_density_grid(coeff, z, n)
%I32V2_WALL_DENSITY_GRID Evaluate one frozen wall density interpolant.
% Purpose:
%   Evaluate the same 512-order physical Bloch density on a requested
%   midpoint source grid without resolving or redefining the trial.
% Input:
%   coeff - frozen physical Bloch density coefficients, 512-by-state_count.
%   z     - canonical certificate scalar/geometry struct.
%   n     - requested even midpoint source count (double integer).
% Output:
%   xi    - n-by-state_count physical density samples.
%   y     - n-by-1 midpoint coordinates on [-d/2,d/2].
%   ds    - periodic trapezoid source weight d/n.
%   kappa - 512-by-1 physical Bloch wave numbers.
%   audit - compact fixed-density and operation ledger.
% Based on:
%   design-3-2d periodic-gauge density-prolongation contract.

n = double(n);
if ~isa(coeff, 'double') || ~ismatrix(coeff) || size(coeff, 1) ~= 512 || ...
    any(~isfinite(coeff(:))) || ~isstruct(z) || ...
    ~all(isfield(z, {'beta', 'd'})) || ...
    ~isa(z.beta, 'double') || ~isa(z.d, 'double') || ...
    ~isequal(z.d, 1.0) || ~isscalar(n) || ~isfinite(n) || ...
    n < 2.0 || n ~= fix(n) || mod(n, 2.0) ~= 0.0
  error('I32V2:WallDensityGridInterface', ...
    'The frozen wall density or requested midpoint grid is invalid.');
end
orders = (-double(size(coeff, 1)) / 2.0: ...
  double(size(coeff, 1)) / 2.0 - 1.0).';
y = -z.d / 2.0 + z.d * ((0.0:n - 1.0).' + 0.5) / n;
ds = z.d / n;
kappa = z.beta + 2.0 * pi * orders / z.d;
xi = exp(1i * y * kappa.') * coeff / sqrt(z.d);
audit = struct('schema', 'I32V2_WALL_DENSITY_GRID_V1', ...
  'native_order_count', double(size(coeff, 1)), ...
  'target_count', n, 'state_count', double(size(coeff, 2)), ...
  'midpoint_origin', y(1), 'negative_nyquist_order', orders(1), ...
  'physical_bloch_gauge', true, 'density_resolve_count', 0.0, ...
  'complex_multiply_add_count', ...
  n * double(size(coeff, 1)) * double(size(coeff, 2)), ...
  'finite', all(isfinite(xi(:))), ...
  'symbol_ledger', struct( ...
  'xi', 'same frozen physical Bloch wall density on the requested grid', ...
  'kappa', 'beta plus 2*pi*wall_order/d'));
end
