function audit = i32v2_validate_computation_view(view, cfg, stage)
%I32V2_VALIDATE_COMPUTATION_VIEW Authenticate a scientific module input.
% Purpose:
%   Reject canonical-data drift, forged self-consistent identity, inherited
%   integer arithmetic, nonfinite data, and stage-interface mismatch before
%   a scientific module performs work.
% Input:
%   view  - i32v2_computation_view return.
%   cfg   - preregistered configuration with the independent digest literal.
%   stage - one of gqp, circle, wall, lifting, or fullp.
% Output:
%   audit - compact authentication and stage-interface record.
% Based on:
%   design-3-2d sections 12.1 and 12.4.

if ~isstruct(view) || ~isscalar(view) || ...
    ~all(isfield(view, {'schema', 'data', 'authentication'}))
  error('I32V2:ComputationViewInterface', ...
    'An authenticated computation view is required.');
end
if ~isstruct(cfg) || ~isfield(cfg, 'identity') || ...
    ~isfield(cfg.identity, 'expected_canonical_digest')
  error('I32V2:ExpectedCanonicalDigestConfig', ...
    'The preregistered canonical digest literal is unavailable.');
end
expected_digest = cfg.identity.expected_canonical_digest;
stage = char(stage);
if strcmp(view.schema, 'I32V2_COMPUTATION_VIEW_V1')
  if ismember(stage, {'lifting', 'fullp'})
    error('I32V2:ComputationViewDensityDeath', ...
      'Lifting and full-P require the authenticated post-wall released view.');
  end
  audit = LOCAL_validate_full(view, expected_digest, cfg, stage);
elseif strcmp(view.schema, 'I32V2_RELEASED_COMPUTATION_VIEW_V1')
  if ~ismember(stage, {'lifting', 'fullp'})
    error('I32V2:ReleasedComputationViewStage', ...
      'The released view cannot authorize a boundary or GQP action.');
  end
  audit = LOCAL_validate_released(view, expected_digest, cfg, stage);
else
  error('I32V2:ComputationViewInterface', ...
    'The computation-view schema is not registered.');
end
end

%% ==================== Full and released authentication ====================
% Live data are always rehashed; no copied Boolean authorizes a module.

function audit = LOCAL_validate_full(view, expected_digest, cfg, stage)
auth = view.authentication;
required_auth = {'schema', 'view_schema', 'canonical_digest', ...
  'expected_canonical_digest', 'numeric_leaf_count', ...
  'converted_numeric_leaf_count', 'logical_leaf_count', ...
  'nonnumeric_leaf_count', 'leaf_equivalence_pass', ...
  'raw_unchanged_pass', 'stamp_digest'};
if ~isstruct(auth) || ~isscalar(auth) || ~all(isfield(auth, required_auth)) || ...
    ~strcmp(auth.schema, 'I32V2_COMPUTATION_VIEW_AUTH_V1') || ...
    ~strcmp(auth.view_schema, view.schema) || ...
    ~strcmp(auth.expected_canonical_digest, expected_digest) || ...
    ~islogical(auth.leaf_equivalence_pass) || ...
    ~isscalar(auth.leaf_equivalence_pass) || ~auth.leaf_equivalence_pass || ...
    ~islogical(auth.raw_unchanged_pass) || ...
    ~isscalar(auth.raw_unchanged_pass) || ~auth.raw_unchanged_pass
  error('I32V2:ComputationViewAuthentication', ...
    'The computation-view authentication stamp is invalid.');
end
stamp = rmfield(auth, 'stamp_digest');
if ~strcmp(i32v2_trial_digest(stamp), auth.stamp_digest)
  error('I32V2:ComputationViewAuthentication', ...
    'The computation-view authentication stamp was modified.');
end
canonical_digest = i32v2_trial_digest(view.data, expected_digest);
if ~strcmp(canonical_digest, auth.canonical_digest)
  error('I32V2:CertificateNumericalIdentity', ...
    'The live canonical view differs from its authenticated identity.');
end

leaf_audit = LOCAL_validate_leaves(view.data);
if ~leaf_audit.all_numeric_double || ~leaf_audit.all_numeric_finite
  error('I32V2:ComputationViewNumericType', ...
    'Scientific computation-view numeric leaves must be finite doubles.');
end
if leaf_audit.numeric_leaf_count ~= auth.numeric_leaf_count || ...
    leaf_audit.logical_leaf_count ~= auth.logical_leaf_count || ...
    leaf_audit.nonnumeric_leaf_count ~= auth.nonnumeric_leaf_count
  error('I32V2:ComputationViewAuthentication', ...
    'The live computation-view leaf schema differs from its stamp.');
end

LOCAL_validate_stage(view.data, cfg, stage);
audit = struct('schema', 'I32V2_COMPUTATION_VIEW_VALIDATION_V1', ...
  'stage', stage, 'canonical_digest', canonical_digest, ...
  'expected_canonical_match', true, 'authenticated_stamp_match', true, ...
  'all_numeric_double', leaf_audit.all_numeric_double, ...
  'all_numeric_finite', leaf_audit.all_numeric_finite, ...
  'numeric_leaf_count', leaf_audit.numeric_leaf_count, ...
  'logical_leaf_count', leaf_audit.logical_leaf_count, ...
  'nonnumeric_leaf_count', leaf_audit.nonnumeric_leaf_count, ...
  'd_is_double_one', isa(view.data.certificate.d, 'double') && ...
  isequal(view.data.certificate.d, 1.0), ...
  'density_maps_released_after_wall', false);
end

function audit = LOCAL_validate_released(view, expected_digest, cfg, stage)
if ~all(isfield(cfg.identity, {'expected_released_digest', ...
    'expected_release_manifest_digest'}))
  error('I32V2:ExpectedReleaseIdentityConfig', ...
    'The independent released-view identity literals are unavailable.');
end
auth = view.authentication;
required_auth = {'schema', 'view_schema', 'released_digest', ...
  'full_canonical_digest', 'expected_canonical_digest', ...
  'expected_released_digest', 'release_manifest_digest', ...
  'expected_release_manifest_digest', ...
  'source_authentication_stamp_digest', 'numeric_leaf_count', ...
  'logical_leaf_count', 'nonnumeric_leaf_count', ...
  'density_maps_released_after_wall', 'stamp_digest'};
if ~isstruct(auth) || ~isscalar(auth) || ~all(isfield(auth, required_auth)) || ...
    ~strcmp(auth.schema, 'I32V2_RELEASED_COMPUTATION_VIEW_AUTH_V1') || ...
    ~strcmp(auth.view_schema, view.schema) || ...
    ~strcmp(auth.expected_canonical_digest, expected_digest) || ...
    ~strcmp(auth.full_canonical_digest, expected_digest) || ...
    ~strcmp(auth.expected_released_digest, ...
    cfg.identity.expected_released_digest) || ...
    ~strcmp(auth.expected_release_manifest_digest, ...
    cfg.identity.expected_release_manifest_digest) || ...
    ~islogical(auth.density_maps_released_after_wall) || ...
    ~isscalar(auth.density_maps_released_after_wall) || ...
    ~auth.density_maps_released_after_wall
  error('I32V2:ReleasedComputationViewAuthentication', ...
    'The released computation-view authentication stamp is invalid.');
end
stamp = rmfield(auth, 'stamp_digest');
if ~strcmp(i32v2_trial_digest(stamp), auth.stamp_digest)
  error('I32V2:ReleasedComputationViewAuthentication', ...
    'The released computation-view authentication stamp was modified.');
end
released_digest = i32v2_trial_digest(view.data);
if ~strcmp(released_digest, auth.released_digest) || ...
    ~strcmp(released_digest, cfg.identity.expected_released_digest)
  error('I32V2:CertificateNumericalIdentity', ...
    'The live released view differs from its authenticated compact identity.');
end
[~, manifest_digest] = i32v2_release_manifest( ...
  auth.full_canonical_digest, released_digest);
if ~strcmp(manifest_digest, auth.release_manifest_digest) || ...
    ~strcmp(manifest_digest, cfg.identity.expected_release_manifest_digest)
  error('I32V2:ReleaseManifestIdentity', ...
    'The live compact projection has invalid parent-child lineage.');
end
leaf_audit = LOCAL_validate_leaves(view.data);
if ~leaf_audit.all_numeric_double || ~leaf_audit.all_numeric_finite || ...
    leaf_audit.numeric_leaf_count ~= auth.numeric_leaf_count || ...
    leaf_audit.logical_leaf_count ~= auth.logical_leaf_count || ...
    leaf_audit.nonnumeric_leaf_count ~= auth.nonnumeric_leaf_count
  error('I32V2:ReleasedComputationViewNumericType', ...
    'The released computation-view type or leaf schema is invalid.');
end
LOCAL_validate_release_fields(view.data);
if ~islogical(view.data.input_contract.density_maps_released_after_wall) || ...
    ~isscalar(view.data.input_contract.density_maps_released_after_wall) || ...
    ~view.data.input_contract.density_maps_released_after_wall || ...
    ~strcmp(view.data.input_contract.projection_id, ...
    'I32V2_POST_WALL_RELEASE_V1')
  error('I32V2:ReleasedComputationViewDeathPoint', ...
    'The compact view lacks its authenticated density death-point record.');
end
LOCAL_validate_stage(view.data, cfg, stage);
audit = struct('schema', 'I32V2_COMPUTATION_VIEW_VALIDATION_V1', ...
  'stage', stage, 'canonical_digest', auth.full_canonical_digest, ...
  'released_digest', released_digest, ...
  'release_manifest_digest', manifest_digest, ...
  'expected_canonical_match', true, 'authenticated_stamp_match', true, ...
  'all_numeric_double', leaf_audit.all_numeric_double, ...
  'all_numeric_finite', leaf_audit.all_numeric_finite, ...
  'numeric_leaf_count', leaf_audit.numeric_leaf_count, ...
  'logical_leaf_count', leaf_audit.logical_leaf_count, ...
  'nonnumeric_leaf_count', leaf_audit.nonnumeric_leaf_count, ...
  'd_is_double_one', isa(view.data.certificate.d, 'double') && ...
  isequal(view.data.certificate.d, 1.0), ...
  'density_maps_released_after_wall', true);
end

%% ==================== Leaf and stage contracts ====================
% These checks authorize only the frozen canonical numerical object.

function audit = LOCAL_validate_leaves(value)
audit = struct('numeric_leaf_count', 0.0, 'logical_leaf_count', 0.0, ...
  'nonnumeric_leaf_count', 0.0, 'all_numeric_double', true, ...
  'all_numeric_finite', true);
if isstruct(value)
  names = fieldnames(value);
  for k = 1:numel(value)
    for j = 1:numel(names)
      audit = LOCAL_add_audit(audit, ...
        LOCAL_validate_leaves(value(k).(names{j})));
    end
  end
elseif iscell(value)
  for k = 1:numel(value)
    audit = LOCAL_add_audit(audit, LOCAL_validate_leaves(value{k}));
  end
elseif isnumeric(value)
  audit.numeric_leaf_count = 1.0;
  audit.all_numeric_double = isa(value, 'double');
  audit.all_numeric_finite = all(isfinite(value(:)));
elseif islogical(value)
  audit.logical_leaf_count = 1.0;
elseif ischar(value) || isstring(value)
  audit.nonnumeric_leaf_count = 1.0;
else
  error('I32V2:CanonicalUnsupportedClass', ...
    'Unsupported computation-view leaf class: %s.', class(value));
end
end

function total = LOCAL_add_audit(total, child)
total.numeric_leaf_count = total.numeric_leaf_count + child.numeric_leaf_count;
total.logical_leaf_count = total.logical_leaf_count + child.logical_leaf_count;
total.nonnumeric_leaf_count = total.nonnumeric_leaf_count + ...
  child.nonnumeric_leaf_count;
total.all_numeric_double = total.all_numeric_double && ...
  child.all_numeric_double;
total.all_numeric_finite = total.all_numeric_finite && ...
  child.all_numeric_finite;
end

function LOCAL_validate_stage(data, cfg, stage)
if ~isstruct(data) || ~all(isfield(data, ...
    {'input_contract', 'certificate', 'ordinary_anchor'}))
  error('I32V2:ComputationViewSchema', ...
    'The canonical whitelist schema is incomplete.');
end
c = data.certificate;
if ~isstruct(c) || ~all(isfield(c, {'d', 'K'})) || ...
    ~isa(c.d, 'double') || ~isequal(c.d, 1.0) || ...
    ~isa(c.K, 'double') || c.K ~= 97.0
  error('I32V2:ComputationViewScalarIdentity', ...
    'The canonical d/K identity or type is invalid.');
end
is_released = isfield(data.input_contract, ...
  'density_maps_released_after_wall');
if ~is_released && (~isfield(c, 'M') || ~isa(c.M, 'double') || c.M ~= 48.0)
  error('I32V2:ComputationViewScalarIdentity', ...
    'The full canonical wall-trace order M identity or type is invalid.');
end
LOCAL_validate_cfg_counts(cfg);
switch stage
  case 'gqp'
    LOCAL_require(c, {'khat', 'beta', 'd'}, 'GQP');
  case 'circle'
    LOCAL_require(c, {'khat', 'gamma', 'rho_disk', 'R', 'd', 'beta', ...
      'X_L', 'X_R', 'delta_c', 'eta_unit_256', ...
      'xi_left_unit_512', 'xi_right_unit_512', 'Gplus', 'Gminus'}, ...
      'circle');
    LOCAL_shape(c.eta_unit_256, [512.0, 194.0], 'eta_unit_256');
    LOCAL_shape(c.xi_left_unit_512, [512.0, 194.0], ...
      'xi_left_unit_512');
    LOCAL_shape(c.xi_right_unit_512, [512.0, 194.0], ...
      'xi_right_unit_512');
    LOCAL_green_shapes(c);
  case 'wall'
    LOCAL_require(c, {'khat', 'R', 'd', 'beta', 'X_L', 'X_R', 'M', ...
      'eta_unit_256', 'xi_left_unit_512', 'xi_right_unit_512', ...
      'Gplus', 'Gminus', 'Pplus', 'Pminus', 'cplus', 'cminus', ...
      'center_wall_jumps', 'gamma'}, 'wall');
    LOCAL_propagation_shapes(c);
    LOCAL_green_shapes(c);
  case 'lifting'
    LOCAL_require(c, {'K', 'R', 'beta', 'd', 'delta_c', 'delta_w', ...
      'mu_h', 'gamma', 'rho_disk', 'Pplus', 'Pminus', 'cplus', ...
      'cminus', 'center_wall_jumps'}, 'lifting');
    LOCAL_propagation_shapes(c);
  case 'fullp'
    LOCAL_require(c, {'K', 'mu_h', 'gamma', 'Pplus', 'Pminus', ...
      'cplus', 'cminus', 'center_wall_jumps'}, 'full-P');
    LOCAL_propagation_shapes(c);
    a = data.ordinary_anchor;
    LOCAL_require(a, {'N_tilde', 'lead_field_factor_plus', ...
      'lead_field_factor_minus'}, 'ordinary anchor');
    LOCAL_shape(a.lead_field_factor_plus, [97.0, 97.0], ...
      'lead_field_factor_plus');
    LOCAL_shape(a.lead_field_factor_minus, [97.0, 97.0], ...
      'lead_field_factor_minus');
  otherwise
    error('I32V2:ComputationViewStage', ...
      'Unknown computation-view validation stage: %s.', stage);
end
end

function LOCAL_validate_cfg_counts(cfg)
required = {'levels', 'panel'};
if ~isstruct(cfg) || ~all(isfield(cfg, required))
  error('I32V2:ComputationViewConfig', ...
    'The preregistered count configuration is unavailable.');
end
counts = {cfg.levels.circle_source, cfg.levels.circle_target, ...
  cfg.levels.wall_source, cfg.levels.wall_target, cfg.levels.riccati, ...
  cfg.levels.lift_gauss, cfg.levels.fullp, cfg.levels.gqp_interp, ...
  cfg.panel.target_max, cfg.panel.source_max};
for k = 1:numel(counts)
  value = counts{k};
  if ~isa(value, 'double') || any(~isfinite(value(:))) || ...
      any(value(:) < 1.0) || any(value(:) ~= fix(value(:)))
    error('I32V2:ComputationViewCountType', ...
      'All preregistered computation counts must be finite integer-valued doubles.');
  end
end
end

function LOCAL_propagation_shapes(c)
LOCAL_shape(c.Pplus, [97.0, 97.0], 'Pplus');
LOCAL_shape(c.Pminus, [97.0, 97.0], 'Pminus');
LOCAL_shape(c.cplus, [97.0, 1.0], 'cplus');
LOCAL_shape(c.cminus, [97.0, 1.0], 'cminus');
end

function LOCAL_green_shapes(c)
LOCAL_shape(c.Gplus, [194.0, 97.0], 'Gplus');
LOCAL_shape(c.Gminus, [194.0, 97.0], 'Gminus');
end

function LOCAL_validate_release_fields(data)
top = {'input_contract'; 'certificate'; 'ordinary_anchor'};
input_fields = {'density_maps_released_after_wall'; 'projection_id'};
certificate_fields = {'K'; 'R'; 'beta'; 'd'; 'rho_disk'; 'gamma'; ...
  'delta_c'; 'delta_w'; 'Pplus'; 'Pminus'; 'cplus'; 'cminus'; ...
  'center_wall_jumps'; 'mu_h'};
anchor_fields = {'N_tilde'; 'lead_field_factor_plus'; ...
  'lead_field_factor_minus'};
if ~isequal(fieldnames(data), top) || ...
    ~isequal(fieldnames(data.input_contract), input_fields) || ...
    ~isequal(fieldnames(data.certificate), certificate_fields) || ...
    ~isequal(fieldnames(data.ordinary_anchor), anchor_fields)
  error('I32V2:ReleasedComputationViewProjection', ...
    'The released view does not have the exact registered fields and order.');
end
end

function LOCAL_require(value, names, label)
if ~isstruct(value) || ~all(isfield(value, names))
  error('I32V2:ComputationViewStageInterface', ...
    'Missing required %s computation-view fields.', label);
end
end

function LOCAL_shape(value, expected, label)
if ~isequal(double(size(value)), expected)
  error('I32V2:ComputationViewShape', ...
    'Unexpected canonical shape for %s.', label);
end
end
