function out = i32v2_certificate_input(certificate_path, cfg)
%I32V2_CERTIFICATE_INPUT Load and whitelist the frozen fbie-a1 certificate.
% Purpose:
%   Validate the explicit certificate input, discard prohibited historical
%   maps immediately, and expose only the frozen objects needed by v2.
% Input:
%   certificate_path - explicit MAT-file input supplied by the caller.
%   cfg              - preregistered v2 configuration.
% Output:
%   out - common module schema with compact whitelisted data and audit.
% Notes:
%   No filename or repository-relative path is part of certificate identity.

entry_tic = tic;
out = LOCAL_empty_return();
out.audit.symbol_ledger = struct( ...
  'z_h', 'frozen finite certificate', ...
  'q_center', 'frozen two-wall center state', ...
  'Pplus', 'right-lead propagation matrix', ...
  'Pminus', 'left-lead propagation matrix', ...
  'eta_unit_256', 'circle [tau;zeta] response map', ...
  'xi_left_unit_512', 'left-wall single-layer density response map', ...
  'xi_right_unit_512', 'right-wall single-layer density response map');

try
  if ~(ischar(certificate_path) || (isstring(certificate_path) && isscalar(certificate_path)))
    error('I32V2:CertificatePathType', ...
      'The certificate input must be a character vector or scalar string.');
  end
  certificate_path = char(certificate_path);
  if ~isfile(certificate_path)
    error('I32V2:CertificateMissing', 'The explicit certificate input is missing.');
  end

  loaded = load(certificate_path, 'staged');
  if ~isfield(loaded, 'staged') || ~isstruct(loaded.staged)
    error('I32V2:CertificateSchema', 'Missing staged certificate struct.');
  end
  staged = loaded.staged;
  clear loaded
  required_top = {'input_contract', 'certificate', 'ordinary_anchor'};
  LOCAL_require_fields(staged, required_top, 'staged');

  prohibited_present = isfield(staged, 'raw_maps') || ...
    isfield(staged, 'historical_diagnostics');
  staged = rmfield(staged, intersect(fieldnames(staged), ...
    {'raw_maps', 'historical_diagnostics'}));
  out.counters.raw_map_consumption = 0;
  out.audit.prohibited_fields_present_then_cleared = prohibited_present;

  input_contract = staged.input_contract;
  certificate = staged.certificate;
  anchor = staged.ordinary_anchor;
  clear staged

  LOCAL_require_fields(input_contract, {'schema', 'source_attempt', ...
    'staging_only', 'formal_runtime_must_not_read_historical_output', ...
    'M_role', 'eta_source_nodes', 'wall_source_orders', ...
    'no_resolve_required', 'density_coordinate', 'circle_basis', ...
    'wall_basis', 'circle_ordering', 'wall_output_ordering', ...
    'circle_value_only_lift', 'wall_value_only_lift', 'lift_shape', ...
    'exact_lift_amplitude_rule'}, 'input_contract');
  LOCAL_require_fields(certificate, {'source_attempt', 'khat', 'mu_h', ...
    'gamma', 'beta', 'd', 'R', 'rho_disk', 'X_L', 'X_R', 'M', 'K', ...
    'delta_c', 'delta_w', 'q_center', 'Pplus', 'Pminus', 'cplus', ...
    'cminus', 'Dplus', 'Dminus', 'Gplus', 'Gminus', 'branch_port', ...
    'eta_unit_256', 'xi_left_unit_512', 'xi_right_unit_512', ...
    'wall_orders_512', 'center_actual_left_trace', ...
    'center_actual_right_trace', 'center_shared_left_trace', ...
    'center_shared_right_trace', 'center_left_value_mismatch', ...
    'center_right_value_mismatch', 'center_wall_jumps', ...
    'density_coordinate', 'global_normal_label', 'lift_contract'}, ...
    'certificate');
  LOCAL_require_fields(anchor, {'B_wall', 'B_circle', 'B_volume', ...
    'M_tilde', 'N_tilde', 'lead_field_factor_plus', ...
    'lead_field_factor_minus', 'tail_minus', 'tail_plus', ...
    'first_level_indices'}, 'ordinary_anchor');

  LOCAL_validate_semantics(input_contract, certificate, anchor, cfg);

  data.input_contract = input_contract;
  data.certificate = certificate;
  data.ordinary_anchor = struct( ...
    'B_wall', anchor.B_wall, ...
    'B_circle', anchor.B_circle, ...
    'B_volume', anchor.B_volume, ...
    'M_tilde', anchor.M_tilde, ...
    'N_tilde', anchor.N_tilde, ...
    'lead_field_factor_plus', anchor.lead_field_factor_plus, ...
    'lead_field_factor_minus', anchor.lead_field_factor_minus, ...
    'tail_minus', anchor.tail_minus, ...
    'tail_plus', anchor.tail_plus, ...
    'first_level_indices', anchor.first_level_indices);
  clear input_contract certificate anchor

  out.audit.identity_digest = i32v2_trial_digest( ...
    data, cfg.identity.expected_trial_digest);
  out.audit.expected_identity_digest = cfg.identity.expected_trial_digest;
  out.audit.expected_identity_match = true;
  out.data = data;
  out.audit.identity_checks = struct( ...
    'schema', true, 'dimensions', true, 'finite', true, ...
    'basis', true, 'ordering', true, 'density_sign', true, ...
    'no_resolve', true);
  out.counters.candidate_solves = 0;
  out.counters.qz_solves = 0;
  out.counters.propagation_solves = 0;
  out.counters.bie_solves = 0;
  out.counters.density_solves = 0;
  out.counters.old_ecap_calls = 0;
  out.counters.image_sum_calls = 0;
  out.counters.rayleigh_field_calls = 0;
  out.counters.interpft_calls = 0;
  out.available = true;
  out.status = 'COMPLETE';
catch err
  out.available = false;
  out.status = 'BLOCKED';
  out.first_blocker = LOCAL_identifier(err);
  out.audit.exception_message = err.message;
end

out.memory.entry_mib = 0;
info = whos('out');
out.memory.local_peak_mib = info.bytes / 2^20;
out.memory.retained_mib = info.bytes / 2^20;
out.memory.largest_object = 'whitelisted certificate data';
out.memory.cleared_objects = {'loaded', 'staged', 'raw_maps', ...
  'historical_diagnostics'};
out.audit.elapsed_s = toc(entry_tic);
end

%% ==================== Schema and semantic validation ====================
% These helpers reject identity drift without relying on a file path.

function LOCAL_require_fields(value, names, label)
if ~isstruct(value) || ~all(isfield(value, names))
  error('I32V2:CertificateSchema', 'Missing required fields in %s.', label);
end
end

function LOCAL_validate_semantics(ic, c, a, cfg)
if ~strcmp(ic.source_attempt, 'fbie-a1') || ~strcmp(c.source_attempt, 'fbie-a1')
  error('I32V2:CertificateIdentity', 'Unexpected frozen source attempt.');
end
if ~logical(ic.staging_only) || ...
    ~logical(ic.formal_runtime_must_not_read_historical_output) || ...
    ~logical(ic.no_resolve_required)
  error('I32V2:CertificateIdentity', 'Frozen staging/no-resolve flags drifted.');
end
checks = [double(c.M) == cfg.physics.M, double(c.K) == cfg.physics.K, ...
  double(c.d) == cfg.physics.d, c.R == cfg.physics.R, ...
  c.beta == cfg.physics.beta, double(c.rho_disk) == cfg.physics.rho_disk, ...
  c.delta_c == cfg.lift.delta_circle, c.delta_w == cfg.lift.delta_wall];
if ~all(checks)
  error('I32V2:CertificateIdentity', 'Frozen scalar identity drifted.');
end
if ~strcmp(c.density_coordinate, '[tau;zeta], zeta=-sigma') || ...
    ~strcmp(ic.density_coordinate, '[tau;zeta], zeta=-sigma')
  error('I32V2:CertificateIdentity', 'Density coordinate/sign drifted.');
end
if double(ic.eta_source_nodes) ~= 256 || double(ic.wall_source_orders) ~= 512
  error('I32V2:CertificateIdentity', 'Native density orders drifted.');
end
sizes_ok = isequal(size(c.q_center), [194, 1]) && ...
  isequal(size(c.Pplus), [97, 97]) && isequal(size(c.Pminus), [97, 97]) && ...
  isequal(size(c.cplus), [97, 1]) && isequal(size(c.cminus), [97, 1]) && ...
  isequal(size(c.Dplus), [97, 97]) && isequal(size(c.Dminus), [97, 97]) && ...
  isequal(size(c.Gplus), [194, 97]) && isequal(size(c.Gminus), [194, 97]) && ...
  isequal(size(c.eta_unit_256), [512, 194]) && ...
  isequal(size(c.xi_left_unit_512), [512, 194]) && ...
  isequal(size(c.xi_right_unit_512), [512, 194]) && ...
  isequal(size(c.wall_orders_512), [512, 1]) && ...
  isequal(size(a.lead_field_factor_plus), [97, 97]) && ...
  isequal(size(a.lead_field_factor_minus), [97, 97]);
if ~sizes_ok
  error('I32V2:CertificateDimension', 'Frozen array dimensions drifted.');
end
numeric_values = {c.khat, c.mu_h, c.gamma, c.q_center, c.Pplus, c.Pminus, ...
  c.cplus, c.cminus, c.Dplus, c.Dminus, c.Gplus, c.Gminus, ...
  c.eta_unit_256, c.xi_left_unit_512, c.xi_right_unit_512, ...
  c.center_actual_left_trace, c.center_actual_right_trace, ...
  c.center_shared_left_trace, c.center_shared_right_trace, ...
  c.center_left_value_mismatch, c.center_right_value_mismatch, ...
  a.B_wall, a.B_circle, a.B_volume, a.M_tilde, a.N_tilde, ...
  a.lead_field_factor_plus, a.lead_field_factor_minus};
for k = 1:numel(numeric_values)
  if ~all(isfinite(numeric_values{k}(:)))
    error('I32V2:CertificateNonfinite', 'Frozen numerical data are nonfinite.');
  end
end
orders = double(c.wall_orders_512(:));
if ~isequal(orders, (-256:255).')
  error('I32V2:CertificateOrdering', 'Negative-Nyquist wall ordering drifted.');
end
if ~contains(ic.M_role, 'wall') || ~logical(ic.circle_value_only_lift) || ...
    ~logical(ic.wall_value_only_lift)
  error('I32V2:CertificateIdentity', 'Wall-M or value-lift semantics drifted.');
end
end

%% ==================== Common return schema ====================
% The empty return remains serializable after any caught blocker.

function out = LOCAL_empty_return()
out.schema = 'I32V2_CERTIFICATE_INPUT_V1';
out.status = 'INITIALIZED';
out.available = false;
out.warnings = {};
out.first_blocker = '';
out.audit = struct();
out.counters = struct();
out.memory = struct();
out.data = struct();
end

function identifier = LOCAL_identifier(err)
identifier = err.identifier;
if isempty(identifier)
  identifier = 'I32V2:UNIDENTIFIED_BLOCKER';
end
end
