function [manifest, digest] = i32v2_release_manifest( ...
    full_canonical_digest, released_digest)
%I32V2_RELEASE_MANIFEST Build the fixed post-wall projection lineage.
% Purpose:
%   Give the release helper and validator one exact machine definition of
%   the compact field projection whose independent digest is preregistered.
% Input:
%   full_canonical_digest - expected full canonical computation identity.
%   released_digest       - expected/live compact projection identity.
% Output:
%   manifest - fixed projection schema and parent/child lineage.
%   digest   - deterministic numerical-serialization manifest digest.
% Based on:
%   design-3-2d section 12.4 released-view amendment.

LOCAL_digest(full_canonical_digest);
LOCAL_digest(released_digest);
manifest = struct( ...
  'schema', 'I32V2_RELEASE_MANIFEST_V1', ...
  'projection_id', 'I32V2_POST_WALL_RELEASE_V1', ...
  'full_view_schema', 'I32V2_COMPUTATION_VIEW_V1', ...
  'released_view_schema', 'I32V2_RELEASED_COMPUTATION_VIEW_V1', ...
  'full_canonical_digest', full_canonical_digest, ...
  'released_digest', released_digest, ...
  'certificate_fields', {{'K', 'R', 'beta', 'd', 'rho_disk', 'gamma', ...
  'delta_c', 'delta_w', 'Pplus', 'Pminus', 'cplus', 'cminus', ...
  'center_wall_jumps', 'mu_h'}}, ...
  'anchor_fields', {{'N_tilde', 'lead_field_factor_plus', ...
  'lead_field_factor_minus'}}, ...
  'input_contract_fields', {{'density_maps_released_after_wall', ...
  'projection_id'}});
digest = i32v2_trial_digest(manifest);
end

function LOCAL_digest(value)
if ~(ischar(value) && numel(value) == 64 && ...
    ~isempty(regexp(value, '^[0-9a-f]{64}$', 'once')))
  error('I32V2:ReleaseManifestDigest', ...
    'Release-manifest lineage requires lowercase SHA-256 literals.');
end
end
