function [released, audit] = i32v2_release_computation_view(view, cfg)
%I32V2_RELEASE_COMPUTATION_VIEW Release density maps after boundary actions.
% Purpose:
%   Retain only the authenticated canonical scalars and propagation/field
%   objects needed by lifting and full-P after the wall density death point.
% Input:
%   view - live authenticated full computation view.
%   cfg  - preregistered configuration with expected canonical identity.
% Output:
%   released - compact authenticated released computation view.
%   audit    - compact death-point identity and retained-schema record.
% Main algorithm:
%   Authenticate the full live view, project the preregistered keep sets,
%   hash the compact projection, and bind it to the full canonical identity
%   and source authentication stamp.
% Based on:
%   design-3-2d density death-point and section 12.4 stamp contract.

if ~isstruct(cfg) || ~isfield(cfg, 'identity') || ...
    ~all(isfield(cfg.identity, {'expected_canonical_digest', ...
    'expected_released_digest', 'expected_release_manifest_digest'}))
  error('I32V2:ExpectedReleaseIdentityConfig', ...
    'The independent released-view identity literals are unavailable.');
end
full_audit = i32v2_validate_computation_view(view, cfg, 'wall');
c = view.data.certificate;
a = view.data.ordinary_anchor;
keep_c = {'K', 'R', 'beta', 'd', 'rho_disk', 'gamma', 'delta_c', ...
  'delta_w', 'Pplus', 'Pminus', 'cplus', 'cminus', ...
  'center_wall_jumps', 'mu_h'};
keep_a = {'N_tilde', 'lead_field_factor_plus', 'lead_field_factor_minus'};
if ~all(isfield(c, keep_c)) || ~all(isfield(a, keep_a))
  error('I32V2:ReleasedComputationViewSchema', ...
    'The preregistered post-wall keep set is incomplete.');
end
data = struct();
data.input_contract = struct( ...
  'density_maps_released_after_wall', true, ...
  'projection_id', 'I32V2_POST_WALL_RELEASE_V1');
data.certificate = LOCAL_project(c, keep_c);
data.ordinary_anchor = LOCAL_project(a, keep_a);

released_schema = 'I32V2_RELEASED_COMPUTATION_VIEW_V1';
released_digest = i32v2_trial_digest(data);
if ~strcmp(released_digest, cfg.identity.expected_released_digest)
  error('I32V2:ReleasedComputationViewIdentity', ...
    'The compact projection differs from its independent expected identity.');
end
[~, manifest_digest] = i32v2_release_manifest( ...
  full_audit.canonical_digest, released_digest);
if ~strcmp(manifest_digest, cfg.identity.expected_release_manifest_digest)
  error('I32V2:ReleaseManifestIdentity', ...
    'The compact projection lineage differs from its independent manifest.');
end
leaf_audit = LOCAL_leaf_counts(data);
authentication = struct( ...
  'schema', 'I32V2_RELEASED_COMPUTATION_VIEW_AUTH_V1', ...
  'view_schema', released_schema, ...
  'released_digest', released_digest, ...
  'full_canonical_digest', full_audit.canonical_digest, ...
  'expected_canonical_digest', cfg.identity.expected_canonical_digest, ...
  'expected_released_digest', cfg.identity.expected_released_digest, ...
  'release_manifest_digest', manifest_digest, ...
  'expected_release_manifest_digest', ...
  cfg.identity.expected_release_manifest_digest, ...
  'source_authentication_stamp_digest', ...
  view.authentication.stamp_digest, ...
  'numeric_leaf_count', leaf_audit.numeric_leaf_count, ...
  'logical_leaf_count', leaf_audit.logical_leaf_count, ...
  'nonnumeric_leaf_count', leaf_audit.nonnumeric_leaf_count, ...
  'density_maps_released_after_wall', true);
authentication.stamp_digest = i32v2_trial_digest(authentication);
released = struct('schema', released_schema, 'data', data, ...
  'authentication', authentication);
audit = struct('schema', 'I32V2_RELEASED_COMPUTATION_VIEW_AUDIT_V1', ...
  'full_canonical_digest', full_audit.canonical_digest, ...
  'released_digest', released_digest, ...
  'release_manifest_digest', manifest_digest, ...
  'source_authentication_stamp_digest', ...
  view.authentication.stamp_digest, ...
  'released_authentication_stamp_digest', authentication.stamp_digest, ...
  'density_maps_released_after_wall', true, ...
  'retained_certificate_fields', {keep_c}, ...
  'retained_anchor_fields', {keep_a}, ...
  'symbol_ledger', struct( ...
  'released_digest', 'live digest of the post-wall compact canonical view', ...
  'full_canonical_digest', 'authenticated full identity before density death', ...
  'release_manifest_digest', 'independent parent-child projection lineage identity'));
end

%% ==================== Compact projection and audit ====================
% Projection is a fixed keep-set operation after all density actions finish.

function projected = LOCAL_project(source, names)
projected = struct();
for k = 1:numel(names)
  projected.(names{k}) = source.(names{k});
end
end

function counts = LOCAL_leaf_counts(value)
counts = struct('numeric_leaf_count', 0.0, 'logical_leaf_count', 0.0, ...
  'nonnumeric_leaf_count', 0.0);
if isstruct(value)
  names = fieldnames(value);
  for k = 1:numel(value)
    for j = 1:numel(names)
      counts = LOCAL_add(counts, LOCAL_leaf_counts(value(k).(names{j})));
    end
  end
elseif iscell(value)
  for k = 1:numel(value)
    counts = LOCAL_add(counts, LOCAL_leaf_counts(value{k}));
  end
elseif isnumeric(value)
  counts.numeric_leaf_count = 1.0;
elseif islogical(value)
  counts.logical_leaf_count = 1.0;
elseif ischar(value) || isstring(value)
  counts.nonnumeric_leaf_count = 1.0;
else
  error('I32V2:CanonicalUnsupportedClass', ...
    'Unsupported released-view leaf class: %s.', class(value));
end
end

function total = LOCAL_add(total, child)
total.numeric_leaf_count = total.numeric_leaf_count + child.numeric_leaf_count;
total.logical_leaf_count = total.logical_leaf_count + child.logical_leaf_count;
total.nonnumeric_leaf_count = total.nonnumeric_leaf_count + ...
  child.nonnumeric_leaf_count;
end
