function result = preflight_i32v2_actual_types(certificate_path)
%PREFLIGHT_I32V2_ACTUAL_TYPES Exercise actual-certificate type-safe helpers.
% Purpose:
%   Dynamically verify the production double computation view, MFS GQP,
%   wall-to-circle action, actual Kress/T-difference panel, lift weights,
%   propagation products, released-view identity, and mutation blockers.
% Input:
%   certificate_path - explicit frozen fbie-a1 certificate MAT file.
% Output:
%   result - compact nonformal preflight record; no artifact is written.
% Main algorithm:
%   Load and authenticate raw data, canonicalize all numeric leaves, execute
%   production-shared helpers on the frozen trial, release density maps, and
%   run adversarial identity mutations before returning compact metrics.
% Notes:
%   This function never calls check_e_cap_v2 and never creates an attempt.

timer = tic;
result = struct('schema', 'I32V2_ACTUAL_TYPE_PREFLIGHT_V1', ...
  'status', 'INITIALIZED', 'pass', false, 'first_blocker', '', ...
  'type', struct(), 'gqp', struct(), 'circle_wall', struct(), ...
  'kress', struct(), 'lifting', struct(), 'fullp', struct(), ...
  'identity', struct(), 'audit', struct(), 'resources', struct());
try
  cfg = i32v2_config();
  experiment_dir = fileparts(mfilename('fullpath'));
  formal_dir = fullfile(experiment_dir, 'output', cfg.attempt);
  formal_exists_before = isfolder(formal_dir) || isfile(formal_dir);

  % --- stage 1: raw identity and canonical double view ---
  raw = i32v2_certificate_input(certificate_path, cfg);
  if ~raw.available
    error('I32V2:ActualPreflightCertificate', '%s', raw.first_blocker);
  end
  raw_digest = raw.audit.identity_digest;
  raw_classes = struct('d', class(raw.data.certificate.d), ...
    'rho_disk', class(raw.data.certificate.rho_disk), ...
    'M', class(raw.data.certificate.M), ...
    'K', class(raw.data.certificate.K), ...
    'wall_orders', class(raw.data.certificate.wall_orders_512));
  [view, view_audit] = i32v2_computation_view(raw.data, cfg);
  z = view.data.certificate;
  if ~strcmp(raw_digest, view_audit.raw_digest_after)
    error('I32V2:ActualPreflightRawMutation', ...
      'Canonicalization changed the raw frozen identity.');
  end
  result.type.raw_classes = raw_classes;
  result.type.canonical_classes = struct('d', class(z.d), ...
    'rho_disk', class(z.rho_disk), 'M', class(z.M), ...
    'K', class(z.K), 'wall_orders', class(z.wall_orders_512));
  result.type.view_audit = view_audit;

  counts = unique(double([cfg.levels.circle_source(:); ...
    cfg.levels.circle_target(:); cfg.levels.wall_source(:); ...
    cfg.levels.wall_target(:)]));
  spacing = z.d ./ counts;
  if ~isa(spacing, 'double') || any(~isfinite(spacing)) || ...
      any(spacing <= 0.0)
    error('I32V2:ActualPreflightSpacing', ...
      'A registered d/N spacing is not a positive finite double.');
  end
  result.type.registered_counts = counts;
  result.type.d_over_N = spacing;
  result.type.d_over_4096 = z.d / 4096.0;

  [~, wall_y, wall_ds, wall_kappa, wall_density_audit] = ...
    i32v2_wall_density_grid(z.xi_left_unit_512, z, ...
    double(cfg.levels.wall_source(end)));
  [tau, zeta, tau_s, theta, circle_density_audit] = ...
    i32v2_circle_density_grid(z, ...
    double(cfg.levels.circle_source(end)));
  k_out = z.khat;
  k_in = z.khat * sqrt(z.rho_disk);
  floating_values = [wall_y(:); wall_ds; wall_kappa(:); theta(:); ...
    k_out; k_in; 2.0 * pi * z.R / double(numel(theta))];
  if ~isa(floating_values, 'double') || any(~isfinite(floating_values))
    error('I32V2:ActualPreflightFloatingGeometry', ...
      'A Fourier, midpoint, wavenumber, or quadrature value is invalid.');
  end
  result.type.wall_grid = wall_density_audit;
  result.type.circle_grid = circle_density_audit;
  result.type.k_out = k_out;
  result.type.k_in = k_in;
  result.type.circle_ds = 2.0 * pi * z.R / double(numel(theta));

  % --- stage 2: production MFS and actual wall-to-circle panel stream ---
  resource = struct('start_tic', tic, ...
    'soft_s', cfg.resource.soft_s, 'hard_s', cfg.resource.hard_s, ...
    'memory_mib_max', cfg.resource.memory_mib_max, ...
    'retained_mib', 0.0, 'cow_mib', 0.0, 'publication_mib', 0.0);
  gqp = i32v2_gqp_module(view, cfg, resource);
  if ~gqp.available
    error('I32V2:ActualPreflightGQP', '%s', gqp.first_blocker);
  end
  result.gqp = struct('proxy_tuple', cfg.gqp_production, ...
    'proxy_constructions', gqp.counters.precomp_proxy, ...
    'lsqminnorm_calls', gqp.counters.lsqminnorm_selected, ...
    'pinv_calls', gqp.counters.pinv_fallback, ...
    'outer_branch_calls', ...
    gqp.counters.mfs_outer_plane_wave_evaluator, ...
    'image_sum_calls', gqp.counters.image_sum_calls, ...
    'bloch_defect', gqp.audit.oracles.bloch_shift_defect, ...
    'interpolation_defect', ...
    max(gqp.audit.oracles.interpolation_relative_by_field));

  target_count = 128.0;
  target_ids = 1.0:target_count;
  target_theta = theta(target_ids);
  target = z.R * [cos(target_theta).'; sin(target_theta).'];
  target_normal = [cos(target_theta).'; sin(target_theta).'];
  [wall_value, wall_normal, wall_ledger, wall_action_audit] = ...
    i32v2_circle_wall_action(z, gqp, cfg, target, target_normal, ...
    double(cfg.levels.wall_source(end)), ...
    struct('n', double(cfg.levels.gqp_interp(end)), ...
    'include_primary', false), 0.0);
  if ~all(isfinite([wall_value(:); wall_normal(:)])) || ...
      ~wall_action_audit.finite
    error('I32V2:ActualPreflightCircleWall', ...
      'The actual wall-to-circle action is nonfinite.');
  end
  result.circle_wall = struct('audit', wall_action_audit, ...
    'operation_ledger', wall_ledger, ...
    'value_fro', norm(wall_value, 'fro'), ...
    'normal_fro', norm(wall_normal, 'fro'));

  % --- stage 3: actual off-grid Kress and T_out-T_in source panel ---
  source_ids = 1.0:double(cfg.panel.source_max);
  log_weights = i32v2_rect_kress_weights( ...
    theta(source_ids), target_theta, double(numel(theta)), source_ids);
  [free_value, free_normal, free_piece, free_blocks] = ...
    i32v2_circle_free_action(k_out, k_in, z.R, ...
    theta(source_ids), target_theta, log_weights, tau(source_ids, :), ...
    zeta(source_ids, :), tau_s(source_ids, :), double(numel(theta)));
  if ~all(isfinite([free_value(:); free_normal(:); ...
      free_piece.normal_double(:); free_blocks.Tdiff(:)]))
    error('I32V2:ActualPreflightKress', ...
      'The actual Kress/T-difference panel is nonfinite.');
  end
  result.kress = struct('source_count_total', double(numel(theta)), ...
    'source_panel_count', double(numel(source_ids)), ...
    'target_panel_count', target_count, ...
    'log_weight_class', class(log_weights), ...
    'T_difference_fro', norm(free_blocks.Tdiff, 'fro'), ...
    'value_fro', norm(free_value, 'fro'), ...
    'normal_fro', norm(free_normal, 'fro'));
  clear tau zeta tau_s wall_y wall_kappa wall_value wall_normal
  clear log_weights free_value free_normal free_piece free_blocks

  % --- stage 4: wall/lifting/full-P type entries and actual products ---
  wall_validation = i32v2_validate_computation_view(view, cfg, 'wall');
  circle_weight = i32v2_lift_mode_weights('circle', ...
    double(cfg.levels.circle_target(end)), ...
    double(cfg.levels.lift_gauss(end)), z);
  wall_weight = i32v2_lift_mode_weights('wall', ...
    double(cfg.levels.wall_target(end)), ...
    double(cfg.levels.lift_gauss(end)), z);
  p_plus_c_plus = z.Pplus * z.cplus;
  p_minus_c_minus = z.Pminus * z.cminus;
  [released, release_audit] = i32v2_release_computation_view(view, cfg);
  lifting_validation = ...
    i32v2_validate_computation_view(released, cfg, 'lifting');
  fullp_validation = ...
    i32v2_validate_computation_view(released, cfg, 'fullp');
  if any(~isfinite([circle_weight(:); wall_weight(:); ...
      p_plus_c_plus(:); p_minus_c_minus(:)]))
    error('I32V2:ActualPreflightLateArithmetic', ...
      'A lifting weight or full-P propagation product is nonfinite.');
  end
  result.lifting = struct('entry_validation', lifting_validation, ...
    'circle_weight_min', min(circle_weight), ...
    'circle_weight_max', max(circle_weight), ...
    'wall_weight_min', min(wall_weight), ...
    'wall_weight_max', max(wall_weight));
  result.fullp = struct('entry_validation', fullp_validation, ...
    'Pplus_cplus_norm', norm(p_plus_c_plus), ...
    'Pminus_cminus_norm', norm(p_minus_c_minus));
  result.identity.wall_entry_validation = wall_validation;
  result.identity.release = release_audit;

  % --- stage 5: adversarial full/released-view identity tests ---
  result.identity.negative = LOCAL_negative_tests(view, released, cfg);
  negative_names = fieldnames(result.identity.negative);
  for k = 1.0:double(numel(negative_names))
    item = result.identity.negative.(negative_names{k});
    if ~item.blocked || ~startsWith(item.identifier, 'I32V2:')
      error('I32V2:ActualPreflightNegativeTest', ...
        'A computation-view mutation was not typed-blocked.');
    end
  end

  formal_exists_after = isfolder(formal_dir) || isfile(formal_dir);
  if formal_exists_after ~= formal_exists_before
    error('I32V2:ActualPreflightFormalMutation', ...
      'The nonformal preflight changed formal-attempt existence.');
  end
  result.audit = struct('raw_digest_unchanged', true, ...
    'raw_classes_unchanged', true, 'density_solves', 0.0, ...
    'scientific_solves', 0.0, 'image_sum_calls', 0.0, ...
    'rayleigh_field_calls', 0.0, 'old_ecap_calls', 0.0, ...
    'formal_attempt_exists_before', formal_exists_before, ...
    'formal_attempt_exists_after', formal_exists_after, ...
    'formal_attempt_created', false, ...
    'claim_label', cfg.claim_label);
  result.status = 'PASS';
  result.pass = true;
catch err
  result.status = 'BLOCKED';
  result.first_blocker = LOCAL_identifier(err);
  result.audit.exception_message = err.message;
  result.audit.exception_stack = err.stack;
end
result.resources.elapsed_s = toc(timer);
held = result; %#ok<NASGU>
info = whos('held');
result.resources.retained_mib = double(info.bytes) / 2.0^20.0;
end

%% ==================== Adversarial authentication tests ====================
% Each mutation must fail at the production validator before scientific work.

function negative = LOCAL_negative_tests(view, released, cfg)
mutated = view;
mutated.data.certificate.q_center(1) = ...
  mutated.data.certificate.q_center(1) + 1.0e-12;
negative.full_numeric_mutation = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(mutated, cfg, 'gqp'));

deleted = view;
deleted.data.certificate = rmfield(deleted.data.certificate, 'Gplus');
negative.full_field_deletion = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(deleted, cfg, 'gqp'));

swapped = view;
temporary = swapped.data.certificate.Pplus;
swapped.data.certificate.Pplus = swapped.data.certificate.Pminus;
swapped.data.certificate.Pminus = temporary;
negative.full_field_exchange = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(swapped, cfg, 'wall'));

retained_mutation = released;
retained_mutation.data.certificate.Pplus(1) = ...
  retained_mutation.data.certificate.Pplus(1) + 1.0e-12;
negative.released_numeric_mutation = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(retained_mutation, cfg, 'lifting'));

released_delete = released;
released_delete.data.certificate = ...
  rmfield(released_delete.data.certificate, 'gamma');
negative.released_field_deletion = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(released_delete, cfg, 'lifting'));

released_add = released;
released_add.data.certificate.unregistered = 1.0;
negative.released_field_addition = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(released_add, cfg, 'lifting'));

forged = retained_mutation;
forged.authentication.released_digest = i32v2_trial_digest(forged.data);
stamp = rmfield(forged.authentication, 'stamp_digest');
forged.authentication.stamp_digest = i32v2_trial_digest(stamp);
negative.self_consistent_forgery = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(forged, cfg, 'fullp'));

parent = released;
parent.authentication.full_canonical_digest = repmat('0', 1.0, 64.0);
stamp = rmfield(parent.authentication, 'stamp_digest');
parent.authentication.stamp_digest = i32v2_trial_digest(stamp);
negative.parent_digest_rewrite = LOCAL_expect_block( ...
  @() i32v2_validate_computation_view(parent, cfg, 'fullp'));
end

function result = LOCAL_expect_block(action)
result = struct('blocked', false, 'identifier', '');
try
  action();
catch err
  result.blocked = true;
  result.identifier = LOCAL_identifier(err);
end
end

function identifier = LOCAL_identifier(err)
identifier = err.identifier;
if isempty(identifier)
  identifier = 'I32V2:UNIDENTIFIED_BLOCKER';
end
end
