function result = selftest_i32v2_fullp()
%SELFTEST_I32V2_FULLP Exercise compact full-P and Fourier-shell contracts.
% Purpose:
%   Run the cap aggregator on small manufactured state dimension while
%   retaining the preregistered 2048/4096 boundary-coordinate layouts.
% Output:
%   result - Compact pass record for shell bands and zero double counting.
% Main algorithm:
%   Place manufactured residual energy only in central Fourier coordinates,
%   use contractive complete propagation matrices, and provide zero GQP/axis
%   diagnostic Grams.  The four outer shells must be near zero and their
%   ledger contributions must remain exactly zero.
% Notes:
%   This is not a formal attempt and creates no output directory.

cfg = i32v2_config();
K = 2;
Nc = cfg.levels.circle_target(end);
Nw = cfg.levels.wall_target(end);
c = struct('K', K, 'Pplus', 0.1 * eye(K), ...
  'Pminus', 0.08 * eye(K), 'cplus', [1; 0.25i], ...
  'cminus', [0.5; -0.125i], 'gamma', 1, 'mu_h', 1, ...
  'center_wall_jumps', struct('field_squared', 1));
ordinary = struct('N_tilde', 1, 'lead_field_factor_plus', zeros(1, K), ...
  'lead_field_factor_minus', zeros(1, K));
cert = struct('certificate', c, 'ordinary_anchor', ordinary);

circle_factor = complex(zeros(Nc, K));
circle_factor(Nc / 2 + 1, :) = [1, 0.25i];
wall_factor = complex(zeros(Nw, K));
wall_factor(Nw / 2 + 1, :) = [0.5, -0.125i];
volume_factor = [circle_factor; wall_factor; wall_factor * c.Pplus];

zero_axis = LOCAL_zero_axis(K);
circle = struct('data', struct());
circle.data.finest = struct('normal_plus', circle_factor, ...
  'normal_minus', 0.5 * circle_factor);
circle.data.axis_metrics = struct('target', struct('normal', zero_axis), ...
  'source', struct('normal', zero_axis), ...
  'riccati', LOCAL_zero_riccati(K));
circle.data.gqp_metrics = LOCAL_zero_gqp(K);

wall = struct('data', struct());
wall.data.finest = struct('internal_plus', wall_factor, ...
  'internal_minus', 0.25 * wall_factor);
wall.data.center_first_left_flux = complex(zeros(Nw, 1));
wall.data.center_first_right_flux = complex(zeros(Nw, 1));
wall.data.axis_metrics = struct('target', struct('normal', zero_axis), ...
  'source', struct('normal', zero_axis));
wall.data.gqp_metrics = LOCAL_zero_gqp(K);

lifting = struct('data', struct());
lifting.data.finest = struct('volume_plus', volume_factor, ...
  'volume_minus', 0.2 * volume_factor, ...
  'singleton', complex(zeros(4 * Nw, 1)));
lifting.data.axis_metrics = struct('target', struct('remainder', 0), ...
  'source', struct('remainder', 0), ...
  'gauss', struct('remainder', 0));
lifting.data.gqp_metrics = struct('cap', 0, 'proxy_remainder', 0, ...
  'interp_remainder', 0);

resource = struct('start_tic', tic, 'hard_s', 1800, ...
  'memory_mib_max', 2048, 'retained_mib', 0, 'cow_mib', 0, ...
  'publication_mib', 64);
cap = i32v2_fullp_cap_module(cert, circle, wall, lifting, cfg, resource);
if ~cap.available
  error('I32V2:FullPSelftestBlocked', '%s: %s', ...
    cap.first_blocker, cap.audit.exception_message);
end
assert(cap.data.caps.wall.fourier == 0);
assert(cap.data.caps.circle.fourier == 0);
assert(cap.data.caps.volume.fourier == 0);
names = fieldnames(cap.data.fourier_shell);
for j = 1:numel(names)
  row = cap.data.fourier_shell.(names{j});
  assert(row.near_zero && row.contraction_pass);
  assert(row.S1 == 0 && row.S2 == 0 && row.R_Fourier == 0);
  assert(strcmp(row.counted_in, 'corresponding target-axis remainder'));
end
result = struct('status', 'PASS', 'shell_rows', {names}, ...
  'epsilon_M_emp', cap.data.caps.epsilon_M_emp, ...
  'field_lower', cap.data.estimator.field_lower, ...
  'q_emp', cap.data.estimator.q_emp, ...
  'formal_attempt_created', false);
fprintf('I32V2 FULLP SELFTEST PASS shells=%d epsilon_M=%.17g q=%.17g\n', ...
  numel(names), result.epsilon_M_emp, result.q_emp);
end

%% ==================== Compact manufactured schemas ====================
% These helpers contain only the fields consumed by the full-P module.

function value = LOCAL_zero_axis(K)
value = struct('level_plus_gram', complex(zeros(K, K, 3)), ...
  'level_minus_gram', complex(zeros(K, K, 3)), ...
  'singleton_squared', zeros(3, 1), ...
  'delta01_plus_gram', complex(zeros(K)), ...
  'delta01_minus_gram', complex(zeros(K)), ...
  'delta01_singleton_squared', 0, ...
  'delta12_plus_gram', complex(zeros(K)), ...
  'delta12_minus_gram', complex(zeros(K)), ...
  'delta12_singleton_squared', 0, ...
  'operation_ledger', struct('total', 0));
end

function value = LOCAL_zero_riccati(K)
grams = {complex(zeros(K)), complex(zeros(K)), complex(zeros(K))};
differences = {complex(zeros(K)), complex(zeros(K))};
side = struct('level', {grams}, 'difference', {differences});
value = struct('normal_plus', side, 'normal_minus', side, ...
  'operation_ledger', struct('total', 0));
end

function value = LOCAL_zero_gqp(K)
proxy = struct('high_plus_gram', complex(zeros(K)), ...
  'high_minus_gram', complex(zeros(K)), 'high_singleton_squared', 0, ...
  'variant_plus_grams', complex(zeros(K, K, 5)), ...
  'variant_minus_grams', complex(zeros(K, K, 5)), ...
  'variant_singleton_squared', zeros(5, 1), ...
  'delta_plus_grams', complex(zeros(K, K, 5)), ...
  'delta_minus_grams', complex(zeros(K, K, 5)), ...
  'singleton_squared', zeros(5, 1));
interp = struct('level_plus_grams', complex(zeros(K, K, 3)), ...
  'level_minus_grams', complex(zeros(K, K, 3)), ...
  'singleton_squared', zeros(3, 1), ...
  'delta01_plus_gram', complex(zeros(K)), ...
  'delta01_minus_gram', complex(zeros(K)), ...
  'delta01_singleton_squared', 0, ...
  'delta12_plus_gram', complex(zeros(K)), ...
  'delta12_minus_gram', complex(zeros(K)), ...
  'delta12_singleton_squared', 0);
scale = struct('piece_plus_grams', complex(zeros(K, K, 3)), ...
  'piece_minus_grams', complex(zeros(K, K, 3)), ...
  'piece_singleton_norms', zeros(3, 1));
value = struct('proxy', proxy, 'interp', interp, ...
  'scale_diag', scale, 'scale_fine', scale, ...
  'operation_ledger', struct('total', 0));
end
