function experiment_input = build_residual_numerator_input_a1( ...
    artifact_path, curve_contract_path, input_path)
%BUILD_RESIDUAL_NUMERATOR_INPUT_A1 Build the frozen I5 material input.
% Purpose:
%   Extend the accepted circle curve contract with the finite geometry and
%   cutoff data required by the shape-general local-panel and exact Ewald
%   material evaluators, without changing or resolving the frozen trial.
% Input:
%   artifact_path       - Explicit frozen fbie-a1 certificate MAT path.
%   curve_contract_path - Explicit accepted circle curve-contract MAT path.
%   input_path          - Explicit create-once MAT output path.
% Output:
%   experiment_input    - Data-only TEP I5 residual material contract.
% Main algorithm:
%   Read the frozen physical scalars, re-evaluate the same circle through
%   geom.construct_cont, and attach exact circle instances of the general
%   curve, complex-tube, collar, Ewald, panel, and stopping contracts.
% Notes:
%   Runtime inputs are MAT data only.  No Markdown, Git data, historical
%   result, MFS proxy, eigenpair solve, density solve, QZ solve, or
%   propagation solve is used.

[artifact_path, curve_contract_path, input_path] = LOCAL_paths( ...
  artifact_path, curve_contract_path, input_path);
loaded_artifact = load(artifact_path, 'staged');
loaded_curve = load(curve_contract_path, 'curve_contract');
if ~isfield(loaded_artifact, 'staged') || ...
    ~isfield(loaded_artifact.staged, 'certificate') || ...
    ~isfield(loaded_curve, 'curve_contract')
  error('I5ResidualInput:Schema', ...
    'The frozen artifact or curve contract has the wrong top-level schema.');
end
z = loaded_artifact.staged.certificate;
accepted_curve = loaded_curve.curve_contract;
required = {'source_attempt', 'khat', 'gamma', 'mu_h', 'beta', 'd', ...
  'R', 'rho_disk', 'X_L', 'X_R', 'delta_c', 'delta_w', 'M', 'K', ...
  'eta_unit_256', 'xi_left_unit_512', 'xi_right_unit_512'};
if ~all(isfield(z, required)) || ...
    ~strcmp(accepted_curve.schema, 'TEP_I5_WALL_CURVE_CONTRACT_V1')
  error('I5ResidualInput:Schema', ...
    'A required frozen field or accepted curve schema is unavailable.');
end

% The explicit run-04 lifting tail required the proof-driven 512-node tier.
boundary_node_count = 512.0;
circle_radius = double(z.R);
[contour, parameter_period] = geom.construct_cont( ...
  boundary_node_count, 'circle', 0, 0, circle_radius);
if parameter_period ~= 2.0 * pi || ...
    ~isequal(size(contour), [6, boundary_node_count]) || ...
    circle_radius ~= double(accepted_curve.adapter_metadata.radius)
  error('I5ResidualInput:Geometry', ...
    'The frozen circle cannot be reproduced by geom.construct_cont.');
end

curve_strip_width = 0.2;
complex_speed = circle_radius;
complex_position_abs = circle_radius * cosh(curve_strip_width);
complex_position_imag = circle_radius * sinh(curve_strip_width);
displacement_abs_upper = 2.0 * complex_position_abs * [1.0, 1.0];
displacement_imag_upper = 2.0 * complex_position_imag * [1.0, 1.0];
displacement_real_upper = displacement_abs_upper;
target_normal_component_upper = cosh(curve_strip_width) * [1.0, 1.0];
source_normal_component_upper = target_normal_component_upper;
boundary_length = 2.0 * pi * circle_radius;

theta = 2.0 * pi * (0.0:boundary_node_count - 1.0).' / ...
  boundary_node_count;
arclength_nodes = circle_radius * theta;
speed = hypot(contour(2, :).', contour(5, :).');
normal = [contour(5, :).', -contour(2, :).'] ./ speed;

configuration = struct( ...
  'boundary_node_count', boundary_node_count, ...
  'retained_mode_cutoff', boundary_node_count / 2.0 - 1.0, ...
  'cell_cutoff', 16.0, ...
  'block_length', 32.0, ...
  'curve_strip_width', curve_strip_width, ...
  'parameter_strip_width', curve_strip_width, ...
  'arclength_strip_width', circle_radius * curve_strip_width, ...
  'ewald_split', 2.0, ...
  'reciprocal_cutoff', 5.0, ...
  'image_cutoff', 3.0, ...
  'taylor_cutoff', 18.0, ...
  'local_cauchy_radius_factor', 1.5, ...
  'kernel_series_cutoff', 24.0, ...
  'panel_half_width', 0.05, ...
  'panel_taylor_order', 8.0, ...
  'wall_lift_mode_cutoff', 256.0, ...
  'material_tail_tolerance', 1.0e-6, ...
  'lifting_tail_tolerance', 1.0e-6, ...
  'accepted_B_Gamma_pm', 1.8732039079101324e-10, ...
  'accepted_B_Gamma_pm_source_path', ...
    'test/i5/wall-curve-a1/output/attempt-1/result.mat', ...
  'accepted_B_Gamma_pm_source_field', 'result.quadratic_bound', ...
  'roundoff_label', 'NON_CERTIFIED_ROUNDOFF_EXCLUDED');

self_tube_certificate = struct( ...
  'displacement_abs_upper', displacement_abs_upper, ...
  'displacement_imag_upper', displacement_imag_upper, ...
  'displacement_real_upper', displacement_real_upper, ...
  'target_normal_component_upper', target_normal_component_upper, ...
  'source_normal_component_upper', source_normal_component_upper, ...
  'target_parameter_strip_domain', 'abs(Im(t))<=0.2', ...
  'source_parameter_strip_domain', 'abs(Im(tau))<=0.2', ...
  'target_arclength_strip_domain', 'abs(Im(s))<=0.04', ...
  'source_arclength_strip_domain', 'abs(Im(sigma))<=0.04', ...
  'nonzero_image_null_cone_margin_lower', ...
    double(z.d) - displacement_real_upper(2) - ...
      displacement_abs_upper(1), ...
  'curve_analytic', true, ...
  'embedded_complex_tube', true, ...
  'bounds_mathematically_explicit', true, ...
  'authority', 'exact circle complex-angle formulas');

curve_certificate = struct( ...
  'parameter_period', parameter_period, ...
  'boundary_length', boundary_length, ...
  'reach_lower', circle_radius, ...
  'curvature_upper', 1.0 / circle_radius, ...
  'speed_lower', circle_radius, ...
  'speed_upper', circle_radius, ...
  'speed_derivative_upper', 0.0, ...
  'parameter_strip_width', curve_strip_width, ...
  'arclength_strip_width', circle_radius * curve_strip_width, ...
  'curve_jet_order', configuration.panel_taylor_order + 3.0, ...
  'arclength_jet_orders', 0:configuration.panel_taylor_order + 3.0, ...
  'arclength_jet_upper', circle_radius .^ ( ...
    1.0 - (0:configuration.panel_taylor_order + 3.0)), ...
  'arclength_jet_units', ...
    'position derivative order j has length^(1-j)', ...
  'strip_speed_upper', complex_speed, ...
  'strip_tangent_x_upper', complex_position_abs, ...
  'strip_tangent_y_upper', complex_position_abs, ...
  'strip_imag_x_upper', complex_position_imag, ...
  'strip_imag_y_upper', complex_position_imag, ...
  'arclength_imag_upper', circle_radius * curve_strip_width, ...
  'signed_arclength_strip_lower', circle_radius * curve_strip_width, ...
  'off_diagonal_chord_lower', 2.0 * circle_radius * ...
    sin(configuration.panel_half_width / (2.0 * circle_radius)), ...
  'left_clearance_lower', abs(double(z.X_L)) - complex_position_abs, ...
  'right_clearance_lower', abs(double(z.X_R)) - complex_position_abs, ...
  'orientation', 'counter-clockwise; outward=(dy_dt,-dx_dt)/speed', ...
  'exact_circle_instance_only', true);

cancellation_safe_certificate = struct( ...
  'q_abs_upper', 4.0 * circle_radius^2, ...
  'q_s_abs_upper', 2.0 * circle_radius, ...
  'q_ss_abs_upper', 2.0, ...
  'p_abs_upper', 2.0 * circle_radius, ...
  'pi_s_abs_upper', 2.0 * circle_radius, ...
  'p_s_abs_upper', 1.0, ...
  'p_ss_abs_upper', 1.0 / circle_radius, ...
  'normal_dot_abs_upper', 1.0, ...
  'chord_quotient', circle_radius^2, ...
  'log_chord_quotient_upper', abs(log(circle_radius^2)), ...
  'p_over_q_upper', 1.0 / (2.0 * circle_radius), ...
  'pi_s_pi_t_over_q_upper', 1.0, ...
  'q_s_squared_over_q_upper', 4.0, ...
  'p_s_q_s_over_q_upper', 2.0 / circle_radius, ...
  'p_q_ss_over_q_upper', 1.0 / circle_radius, ...
  'p_q_s_squared_over_q_upper', 2.0 * circle_radius, ...
  'p_q_s_squared_over_q_squared_upper', 2.0 / circle_radius, ...
  'density_arclength_derivative_factor', 1.0 / circle_radius, ...
  'bare_q_inverse_evaluated', false, ...
  'authority', 'exact circle arclength identities for P10/P23/P24');

joint_parameter_difference_width = 2.0 * curve_strip_width;
complex_q_upper = 4.0 * circle_radius^2 * cosh(curve_strip_width)^2;
complex_q_s_upper = 2.0 * circle_radius * ...
  cosh(joint_parameter_difference_width);
complex_q_ss_upper = 2.0 * cosh(joint_parameter_difference_width);
local_complex_strip_certificate = struct( ...
  'parameter_strip_width', curve_strip_width, ...
  'arclength_strip_width', circle_radius * curve_strip_width, ...
  'normalized_chord_constant', circle_radius^2, ...
  'normalized_chord_zero_free', true, ...
  'log_chord_branch_fixed', true, ...
  'simultaneous_shift_admissible', true, ...
  'strip_speed_upper', circle_radius, ...
  'strip_path_length_upper', 2.0 * pi * circle_radius, ...
  'arclength_imag_upper', circle_radius * sinh(curve_strip_width), ...
  'q_abs_upper', complex_q_upper, ...
  'q_s_abs_upper', complex_q_s_upper, ...
  'q_ss_abs_upper', complex_q_ss_upper, ...
  'p_abs_upper', complex_q_upper / (2.0 * circle_radius), ...
  'pi_s_abs_upper', complex_q_upper / (2.0 * circle_radius), ...
  'p_s_abs_upper', complex_q_s_upper / (2.0 * circle_radius), ...
  'p_ss_abs_upper', complex_q_ss_upper / (2.0 * circle_radius), ...
  'normal_dot_abs_upper', cosh(joint_parameter_difference_width), ...
  'normalized_tangent_dot_abs_upper', ...
    cosh(joint_parameter_difference_width), ...
  'target_tangent_projection_abs_upper', ...
    complex_q_upper / (2.0 * circle_radius), ...
  'chord_quotient', circle_radius^2, ...
  'log_chord_quotient_upper', abs(log(circle_radius^2)), ...
  'p_over_q_upper', 1.0 / (2.0 * circle_radius), ...
  'pi_s_pi_t_over_q_upper', cosh(curve_strip_width)^2, ...
  'q_s_squared_over_q_upper', 4.0 * cosh(curve_strip_width)^2, ...
  'p_s_q_s_over_q_upper', ...
    2.0 * cosh(curve_strip_width)^2 / circle_radius, ...
  'p_q_ss_over_q_upper', ...
    cosh(joint_parameter_difference_width) / circle_radius, ...
  'p_q_s_squared_over_q_upper', ...
    2.0 * circle_radius * cosh(joint_parameter_difference_width)^2, ...
  'p_q_s_squared_over_q_squared_upper', ...
    2.0 * cosh(curve_strip_width)^2 / circle_radius, ...
  'density_arclength_derivative_factor', 1.0 / circle_radius, ...
  'authority', ...
    'exact normalized-chord and complex-angle bounds for circle input');

ewald_h = configuration.ewald_split / double(z.d);
ewald_eta = (double(z.khat) * double(z.d) / ...
  (2.0 * configuration.ewald_split))^2;
reciprocal_orders = (-(configuration.reciprocal_cutoff - 1.0): ...
  configuration.reciprocal_cutoff - 1.0).';
reciprocal_beta = double(z.beta) + 2.0 * pi * reciprocal_orders / double(z.d);
reciprocal_q = sqrt(complex(reciprocal_beta.^2 - double(z.khat)^2));
flip = real(reciprocal_q) < 0.0 | ...
  (real(reciprocal_q) == 0.0 & imag(reciprocal_q) > 0.0);
reciprocal_q(flip) = -reciprocal_q(flip);
retained_images = [-(configuration.image_cutoff - 1.0):-1.0, ...
  1.0:configuration.image_cutoff - 1.0];
retained_image_u_lower = ewald_h^2 * ((abs(retained_images) * ...
  double(z.d) - displacement_real_upper(2)).^2 - ...
  displacement_imag_upper(1)^2 - displacement_imag_upper(2)^2);
local_R0 = ewald_h^2 * sum(displacement_abs_upper.^2);
local_B = configuration.local_cauchy_radius_factor * local_R0;
local_x = ewald_eta * local_B;
local_xQ = ewald_eta * (1.0 + local_B);
local_N = configuration.taylor_cutoff;
local_series_ratios = [ ...
  local_x / (local_N + 2.0)^2, ...
  local_B * (local_N + 1.0) / (local_N + 2.0)^2, ...
  local_x / (local_N + 2.0)^2 * (1.0 + 1.0 / (local_N + 2.0)), ...
  local_xQ * (local_N + 1.0) / (local_N + 2.0)^2];
ewald_gate_certificate = struct( ...
  'split_h', ewald_h, ...
  'eta', ewald_eta, ...
  'finite_reciprocal_orders', reciprocal_orders, ...
  'finite_transverse_wavenumber', reciprocal_beta, ...
  'finite_q_branch', reciprocal_q, ...
  'finite_q_abs_lower', min(abs(reciprocal_q)), ...
  'finite_inverse_q_upper', max(1.0 ./ abs(reciprocal_q)), ...
  'finite_nonwood_pass', all(reciprocal_q ~= 0.0), ...
  'retained_image_indices', retained_images, ...
  'retained_image_u_lower', retained_image_u_lower, ...
  'retained_image_positive_pass', all(retained_image_u_lower > 0.0), ...
  'local_R0', local_R0, ...
  'local_cauchy_B', local_B, ...
  'local_series_ratios', local_series_ratios, ...
  'local_series_ratio_pass', local_B > local_R0 && ...
    all(local_series_ratios < 1.0));

panel_gate = configuration.panel_half_width <= min([ ...
  boundary_length / 6.0, ...
  1.0 / (2.0 * curve_certificate.curvature_upper), ...
  curve_certificate.reach_lower / 2.0]);
if min([curve_certificate.left_clearance_lower, ...
    curve_certificate.right_clearance_lower, ...
    self_tube_certificate.nonzero_image_null_cone_margin_lower]) <= 0.0 || ...
    ~panel_gate || ~ewald_gate_certificate.finite_nonwood_pass || ...
    ~ewald_gate_certificate.retained_image_positive_pass || ...
    ~ewald_gate_certificate.local_series_ratio_pass
  error('I5ResidualInput:GeometryGate', ...
    'A positive-distance or local-panel width gate is not satisfied.');
end

experiment_input = struct( ...
  'schema', 'TEP_I5_RESIDUAL_NUMERATOR_INPUT_V1', ...
  'claim_scope', 'B_UPSILON_AND_MATERIAL_B_LIFT', ...
  'curve_kind', 'circle-instance-of-shape-general-contract', ...
  'contour', contour, ...
  'parameter_nodes', theta, ...
  'arclength_nodes', arclength_nodes, ...
  'speed', speed, ...
  'normal', normal, ...
  'curve_certificate', curve_certificate, ...
  'cancellation_safe_certificate', cancellation_safe_certificate, ...
  'local_complex_strip_certificate', local_complex_strip_certificate, ...
  'ewald_gate_certificate', ewald_gate_certificate, ...
  'self_tube_certificate', self_tube_certificate, ...
  'configuration', configuration, ...
  'panel_width_gate', panel_gate, ...
  'provenance', struct( ...
    'artifact_path', artifact_path, ...
    'curve_contract_path', curve_contract_path, ...
    'source_attempt', char(z.source_attempt), ...
    'geometry_constructor', 'geom.construct_cont', ...
    'eigenpair_solves', 0.0, ...
    'bie_density_solves', 0.0, ...
    'qz_decompositions', 0.0, ...
    'propagation_matrix_solves', 0.0));
save(input_path, 'experiment_input', '-v7.3');
end

%% ==================== Explicit paths ====================
% The builder is append-only and does not discover repository layout.

function [artifact_path, curve_contract_path, input_path] = LOCAL_paths( ...
    artifact_path, curve_contract_path, input_path)
artifact_path = LOCAL_char_path(artifact_path, 'artifact_path');
curve_contract_path = LOCAL_char_path( ...
  curve_contract_path, 'curve_contract_path');
input_path = LOCAL_char_path(input_path, 'input_path');
if ~isfile(artifact_path) || ~isfile(curve_contract_path)
  error('I5ResidualInput:InputPath', ...
    'Both input arguments must name existing MAT files.');
end
if isfile(input_path) || isfolder(input_path)
  error('I5ResidualInput:OutputExists', ...
    'input_path must be a new append-only MAT target.');
end
output_directory = fileparts(input_path);
if ~isempty(output_directory) && ~isfolder(output_directory)
  error('I5ResidualInput:OutputDirectory', ...
    'The explicit input output directory does not exist.');
end
end

function value = LOCAL_char_path(value, name)
if isstring(value) && isscalar(value)
  value = char(value);
end
if ~ischar(value) || isempty(value)
  error('I5ResidualInput:Path', '%s must be a nonempty path.', name);
end
end
