function result = residual_numerator_a1(artifact_path, input_path, output_path)
%RESIDUAL_NUMERATOR_A1 Evaluate the I5 continuous residual numerator.
% Purpose:
%   Evaluate ordinary retained material value/normal rows and attach explicit
%   exact-Ewald, local-panel, angular, and full-propagation omission bounds;
%   add the frozen accepted artificial-wall normal module and both wall and
%   material value-defect lifts.
% Input:
%   artifact_path - Explicit frozen fbie-a1 certificate MAT path.
%   input_path    - Explicit residual-numerator input MAT path.
%   output_path   - Explicit create-once result MAT path.
% Output:
%   result        - B_Gamma_pm, B_Upsilon, and complete B_lift assembly.
% Main algorithm:
%   Reconstruct frozen finite densities; evaluate shape-general Kress local
%   rows, a finite exact Ewald representation of the regular images, and the
%   separated finite wall action; widen rows by analytic bounds; then apply
%   a whole-matrix block-power certificate to the frozen half-guide states.
% Based on:
%   (M-R)--(M-L), (M-off), and (M-weight) in s-material-tail.md; (P1)--
%   (P29) in s-local-panel.md; and (T-lift) in s-lift-tail.md.
% Main changes:
%   The governing QP kernel is Ewald, never the MFS proxy.  The local action
%   is assembled on a parameterized curve and never uses circular Bessel or
%   Fourier diagonalization.  Kress values are only enclosure centers.
% Numerical goal:
%   Produce a finite, possibly wide, drift-free ordinary display of the full
%   continuous residual numerator for the frozen reconstruction.
% Notes:
%   Floating-point rounding is deliberately not enclosed.  Every persisted
%   result is labeled NON_CERTIFIED_ROUNDOFF_EXCLUDED.

timer = tic;
[artifact_path, input_path, output_path] = LOCAL_paths( ...
  artifact_path, input_path, output_path);
loaded_artifact = load(artifact_path, 'staged');
loaded_input = load(input_path, 'experiment_input');
if ~isfield(loaded_artifact, 'staged') || ...
    ~isfield(loaded_input, 'experiment_input')
  error('I5Residual:Schema', 'A required top-level MAT variable is absent.');
end
staged = loaded_artifact.staged;
experiment_input = loaded_input.experiment_input;
z = staged.certificate;
cfg = experiment_input.configuration;
LOCAL_validate(z, staged, experiment_input, output_path);

% --- stage 1: frozen density, geometry, branch, and propagation gates ---
density = LOCAL_density(z, experiment_input);
geometry = LOCAL_geometry(experiment_input);
branch = LOCAL_branch(z);
propagation_minus = LOCAL_block_certificate(z.Pminus, cfg.block_length);
propagation_plus = LOCAL_block_certificate(z.Pplus, cfg.block_length);
if ~branch.pass || ~propagation_minus.contraction_pass || ...
    ~propagation_plus.contraction_pass
  error('I5Residual:FiniteGate', ...
    'A branch, non-Wood, geometry, or block-power gate failed.');
end

% --- stage 2: local, regular-image, and off-surface action rows ---
local_factors = LOCAL_local_factor_bounds(z, geometry, cfg);
local_action = LOCAL_local_action(z, geometry, density, local_factors, cfg);
regular_certificate = LOCAL_ewald_certificate(z, geometry, cfg);
regular_action = LOCAL_regular_action( ...
  z, geometry, density, regular_certificate, cfg);
off_surface_action = LOCAL_off_surface_action(z, geometry, cfg);
rows = LOCAL_combined_rows( ...
  geometry, local_action, regular_action, off_surface_action, cfg);
wall_value_action = LOCAL_wall_value_action( ...
  z, geometry, density, propagation_minus, propagation_plus, cfg);

% --- stage 3: material trace and tubular lifting assemblies ---
weights = LOCAL_weights(z, geometry, cfg);
material = LOCAL_material_assembly(z, geometry, rows, weights, local_action, ...
  regular_action, off_surface_action, propagation_minus, ...
  propagation_plus, cfg);
material_lifting = LOCAL_lifting_assembly(z, geometry, rows, weights, local_action, ...
  regular_action, off_surface_action, propagation_minus, ...
  propagation_plus, cfg);
lifting = LOCAL_total_lifting(material_lifting, wall_value_action, cfg);

% --- stage 4: conditional eigenvalue-error display from the numerator ---
wall_normal = struct( ...
  'B_Gamma_pm', cfg.accepted_B_Gamma_pm, ...
  'source_path', cfg.accepted_B_Gamma_pm_source_path, ...
  'source_field', cfg.accepted_B_Gamma_pm_source_field, ...
  'read_from_historical_output_at_runtime', false, ...
  'ordinary_floating_point', true);
numerator_majorant = wall_normal.B_Gamma_pm + material.bound + lifting.bound;
prediction = LOCAL_prediction(z, staged.ordinary_anchor, numerator_majorant);
acceptance_pass = local_action.gate.pass && regular_certificate.gate.pass && ...
  off_surface_action.gate.pass && wall_value_action.gate.pass && ...
  material.tail_budget_pass && lifting.tail_budget_pass;
if acceptance_pass
  run_status = 'COMPLETE_RESIDUAL_NUMERATOR_ORDINARY';
else
  run_status = 'FINITE_BOUND_STOPPING_TOLERANCE_FAILED_ORDINARY';
end
component_scale = struct( ...
  'B_Gamma_pm', wall_normal.B_Gamma_pm, ...
  'B_Upsilon', material.bound, ...
  'B_lift', lifting.bound, ...
  'B_Gamma_pm_share', wall_normal.B_Gamma_pm / numerator_majorant, ...
  'B_Upsilon_share', material.bound / numerator_majorant, ...
  'B_lift_share', lifting.bound / numerator_majorant);
workspace = whos;
result = struct( ...
  'status', run_status, ...
  'claim_scope', 'B_GAMMA_PM_PLUS_B_UPSILON_PLUS_B_LIFT', ...
  'certification_label', cfg.roundoff_label, ...
  'roundoff_excluded', true, ...
  'reliability_certified', false, ...
  'numerator_majorant', numerator_majorant, ...
  'component_scale', component_scale, ...
  'wall_normal', wall_normal, ...
  'material', material, ...
  'lifting', lifting, ...
  'prediction', prediction, ...
  'rows', rows, ...
  'local_panel', local_action, ...
  'regular_image', regular_action, ...
  'regular_image_certificate', regular_certificate, ...
  'off_surface', off_surface_action, ...
  'wall_value_action', wall_value_action, ...
  'weights', weights, ...
  'density_audit', density.audit, ...
  'branch_audit', branch, ...
  'propagation_minus', propagation_minus, ...
  'propagation_plus', propagation_plus, ...
  'theorem_gate', struct( ...
    'local_panel_finite_enclosure', local_action.gate.pass, ...
    'regular_image_truncation', regular_certificate.gate.pass, ...
    'off_surface_finite_support', off_surface_action.gate.pass, ...
    'material_tail_tolerance', material.tail_budget_pass, ...
    'lifting_tail_tolerance', lifting.tail_budget_pass, ...
    'outward_rounding', false, ...
    'wall_value_lifting_complete', wall_value_action.gate.pass, ...
    'analytic_coverage_complete', local_action.gate.pass && ...
      regular_certificate.gate.pass && off_surface_action.gate.pass && ...
      wall_value_action.gate.pass, ...
    'total_residual_numerator_complete', acceptance_pass), ...
  'missing_modules', {{}}, ...
  'provenance', struct( ...
    'artifact_path', artifact_path, ...
    'input_path', input_path, ...
    'governing_kernel', 'finite exact Ewald representation plus analytic tails', ...
    'mfs_proxy_used', false, ...
    'circle_bessel_diagonalization_used', false, ...
    'sampling_drift_used', false, ...
    'eigenpair_solves', 0.0, ...
    'bie_density_solves', 0.0, ...
    'qz_decompositions', 0.0, ...
    'propagation_matrix_solves', 0.0), ...
  'resource', struct( ...
    'elapsed_seconds_before_save', toc(timer), ...
    'workspace_proxy_mib_before_save', ...
      sum([workspace.bytes]) / 2.0^20));
save(output_path, 'result', '-v7.3');
end

%% ==================== Input contracts ====================
% These helpers validate explicit MAT interfaces and frozen dimensions.

function [artifact_path, input_path, output_path] = LOCAL_paths( ...
    artifact_path, input_path, output_path)
artifact_path = LOCAL_char_path(artifact_path, 'artifact_path');
input_path = LOCAL_char_path(input_path, 'input_path');
output_path = LOCAL_char_path(output_path, 'output_path');
if ~isfile(artifact_path) || ~isfile(input_path)
  error('I5Residual:InputPath', 'Both explicit MAT inputs must exist.');
end
if isfile(output_path) || isfolder(output_path)
  error('I5Residual:OutputExists', 'output_path must be a new MAT target.');
end
output_directory = fileparts(output_path);
if ~isempty(output_directory) && ~isfolder(output_directory)
  error('I5Residual:OutputDirectory', ...
    'The explicit result directory does not exist.');
end
end

function value = LOCAL_char_path(value, name)
if isstring(value) && isscalar(value)
  value = char(value);
end
if ~ischar(value) || isempty(value)
  error('I5Residual:Path', '%s must be a nonempty path.', name);
end
end

function LOCAL_validate(z, staged, input, output_path)
required = {'khat', 'gamma', 'mu_h', 'beta', 'd', 'R', 'rho_disk', ...
  'delta_c', 'M', 'K', 'q_center', 'Gplus', 'Gminus', 'Pplus', ...
  'Pminus', 'cplus', 'cminus', 'eta_unit_256', ...
  'xi_left_unit_512', 'xi_right_unit_512', 'density_coordinate'};
required = [required, {'wall_input_unit_512', 'wall_orders_512', ...
  'center_wall_jumps', 'delta_w'}];
input_required = {'schema', 'contour', 'parameter_nodes', ...
  'arclength_nodes', 'speed', 'normal', 'curve_certificate', ...
  'self_tube_certificate', 'cancellation_safe_certificate', ...
  'local_complex_strip_certificate', ...
  'ewald_gate_certificate', 'configuration'};
if ~all(isfield(z, required)) || ~all(isfield(input, input_required)) || ...
    ~isfield(staged, 'ordinary_anchor') || ...
    ~strcmp(input.schema, 'TEP_I5_RESIDUAL_NUMERATOR_INPUT_V1')
  error('I5Residual:Schema', 'The frozen artifact or input schema is incomplete.');
end
K = double(z.K);
N = double(input.configuration.boundary_node_count);
if ~isequal(size(z.eta_unit_256), [512, 2 * K]) || ...
    ~ismember(N, [256.0, 512.0]) || ...
    double(input.configuration.retained_mode_cutoff) ~= N / 2.0 - 1.0 || ...
    ~isequal(size(input.contour), [6, N]) || ...
    ~isequal(size(z.Gplus), [2 * K, K]) || ...
    ~isequal(size(z.Gminus), [2 * K, K]) || ...
    ~isequal(size(z.Pplus), [K, K]) || ...
    ~isequal(size(z.Pminus), [K, K]) || ...
    ~strcmp(strtrim(z.density_coordinate), '[tau;zeta], zeta=-sigma') || ...
    ~all(isfield(z.center_wall_jumps, ...
      {'left_coefficients', 'right_coefficients'})) || ...
    ~input.ewald_gate_certificate.finite_nonwood_pass || ...
    ~input.ewald_gate_certificate.retained_image_positive_pass || ...
    ~input.ewald_gate_certificate.local_series_ratio_pass || ...
    ~input.local_complex_strip_certificate.normalized_chord_zero_free || ...
    ~input.local_complex_strip_certificate.log_chord_branch_fixed || ...
    ~input.local_complex_strip_certificate.simultaneous_shift_admissible || ...
    ~all(isfield(input.local_complex_strip_certificate, ...
      {'normalized_tangent_dot_abs_upper', ...
      'target_tangent_projection_abs_upper'})) || ...
    z.gamma ~= z.mu_h || z.khat <= 0.0 || z.d <= 0.0 || ...
    isfile(output_path)
  error('I5Residual:FrozenGate', 'A frozen dimension or convention failed.');
end
end

%% ==================== Frozen data and geometry ====================
% Density signs, arclength coordinates, and Rayleigh branches are fixed here.

function density = LOCAL_density(z, input)
N = 256.0;
orders = (-N / 2.0:N / 2.0 - 1.0).';
tau_native = double(z.eta_unit_256(1:N, :));
zeta_native = double(z.eta_unit_256(N + 1.0:end, :));
tau_coeff_map = fftshift(fft(tau_native, [], 1), 1) / N;
zeta_coeff_map = fftshift(fft(zeta_native, [], 1), 1) / N;
sigma_coeff_map = -zeta_coeff_map;
tau_values = exp(1i * input.parameter_nodes * orders.') * tau_coeff_map;
sigma_values = exp(1i * input.parameter_nodes * orders.') * sigma_coeff_map;
tau_parseval = abs(norm(tau_native, 'fro')^2 / N - ...
  norm(tau_coeff_map, 'fro')^2) / max(realmin, norm(tau_coeff_map, 'fro')^2);
sigma_parseval = abs(norm(zeta_native, 'fro')^2 / N - ...
  norm(sigma_coeff_map, 'fro')^2) / max(realmin, norm(sigma_coeff_map, 'fro')^2);
density = struct( ...
  'orders', orders, ...
  'tau_coeff_map', tau_coeff_map, ...
  'sigma_coeff_map', sigma_coeff_map, ...
  'tau_values', tau_values, ...
  'sigma_values', sigma_values, ...
  'tau_linf_upper', sum(vecnorm(tau_coeff_map, 2, 2)), ...
  'sigma_linf_upper', sum(vecnorm(sigma_coeff_map, 2, 2)), ...
  'audit', struct( ...
    'transform', 'fftshift(fft(native_samples))/256', ...
    'midpoint_phase_applied', false, ...
    'stored_zeta_changed_to_sigma_once', true, ...
    'tau_parseval_relative_defect', tau_parseval, ...
    'sigma_parseval_relative_defect', sigma_parseval, ...
    'pass', max(tau_parseval, sigma_parseval) <= 4096.0 * eps));
if ~density.audit.pass
  error('I5Residual:DensityAudit', 'The frozen density transform failed.');
end
end

function geometry = LOCAL_geometry(input)
C = double(input.contour);
geometry = struct( ...
  'position', [C(1, :).', C(4, :).'], ...
  'derivative', [C(2, :).', C(5, :).'], ...
  'second_derivative', [C(3, :).', C(6, :).'], ...
  'speed', double(input.speed(:)), ...
  'normal', double(input.normal), ...
  'parameter_nodes', double(input.parameter_nodes(:)), ...
  'arclength_nodes', double(input.arclength_nodes(:)), ...
  'certificate', input.curve_certificate, ...
  'tube', input.self_tube_certificate, ...
  'cancellation', input.cancellation_safe_certificate, ...
  'local_complex', input.local_complex_strip_certificate);
if any(~isfinite([geometry.position(:); geometry.derivative(:); ...
    geometry.speed(:); geometry.normal(:)])) || ...
    min(geometry.speed) <= 0.0 || ...
    ~input.panel_width_gate || ...
    ~geometry.tube.embedded_complex_tube
  error('I5Residual:GeometryGate', 'The curve certificate is invalid.');
end
end

function branch = LOCAL_branch(z)
orders = (-256.0:255.0).';
transverse_wavenumber = double(z.beta) + 2.0 * pi * orders / double(z.d);
radicand = double(z.khat)^2 - transverse_wavenumber.^2;
rayleigh_wavenumber = sqrt(complex(radicand));
flip = imag(rayleigh_wavenumber) < 0.0 | ...
  (imag(rayleigh_wavenumber) == 0.0 & real(rayleigh_wavenumber) < 0.0);
rayleigh_wavenumber(flip) = -rayleigh_wavenumber(flip);
exact_wood = any(rayleigh_wavenumber == 0.0);
branch = struct( ...
  'orders', orders, ...
  'transverse_wavenumber', transverse_wavenumber, ...
  'rayleigh_wavenumber', rayleigh_wavenumber, ...
  'minimum_nonwood_margin', min(abs(radicand)), ...
  'exact_wood', exact_wood, ...
  'pass', ~exact_wood && all(isfinite(rayleigh_wavenumber)));
end

%% ==================== Shape-general local action ====================
% Kress matrices are retained centers; P19/P28 bounds enclose all row error.

function action = LOCAL_local_action(z, geometry, density, factors, cfg)
N = numel(geometry.parameter_nodes);
dt = 2.0 * pi / N;
geom_data = struct( ...
  'z', geometry.position, ...
  'zp', geometry.derivative, ...
  'zpp', geometry.second_derivative, ...
  'speed', geometry.speed);
[parameter_nodes, D] = utils.triginterp(N);
if max(abs(parameter_nodes(:) - geometry.parameter_nodes(:))) > 4096.0 * eps
  error('I5Residual:ParameterGrid', 'The Kress grid differs from the contract.');
end
R = LOCAL_kress_matrix(N);
k_outer = double(z.khat);
k_inner = sqrt(double(z.rho_disk)) * k_outer;
[M1e, M2e, N1e, N2e] = kernel.kress_mn_splits( ...
  k_outer, parameter_nodes, geom_data);
[M1i, M2i, N1i, N2i] = kernel.kress_mn_splits( ...
  k_inner, parameter_nodes, geom_data);
[L1e, L2e, Ls1e, Ls2e] = kernel.kress_l_splits( ...
  k_outer, parameter_nodes, geom_data);
[L1i, L2i, Ls1i, Ls2i] = kernel.kress_l_splits( ...
  k_inner, parameter_nodes, geom_data);
A11 = R .* (L1e - L1i) + dt * (L2e - L2i);
A12 = R .* (M1i - M1e) + dt * (M2i - M2e);
A22 = R .* (Ls1i - Ls1e) + dt * (Ls2i - Ls2e);
G = (geom_data.zp * geom_data.zp.') ./ ...
  (geom_data.speed * geom_data.speed.');
delta_M1 = k_outer^2 * M1e - k_inner^2 * M1i;
delta_M2 = k_outer^2 * M2e - k_inner^2 * M2i;
delta_N1 = N1e - N1i;
delta_N2 = N2e - N2i;
Tdiff = (R .* delta_M1 + dt * delta_M2) .* G + ...
  bsxfun(@rdivide, R .* delta_N1 + dt * delta_N2, ...
  geom_data.speed) * D;
zeta_values = -density.sigma_values;
value_samples = (eye(N) + A11) * density.tau_values + ...
  A12 * zeta_values;
normal_samples = -(Tdiff * density.tau_values + ...
  (eye(N) + A22) * zeta_values);
[value_rows, mode_orders] = LOCAL_rows(value_samples, geometry, cfg);
[normal_rows, ~] = LOCAL_rows(normal_samples, geometry, cfg);
P = geometry.certificate.boundary_length;
a = geometry.local_complex.parameter_strip_width;
strip_geometry = geometry;
strip_geometry.cancellation = geometry.local_complex;
strip_factors = LOCAL_local_factor_bounds(z, strip_geometry, cfg);
maue_geometry = strip_geometry;
maue_geometry.cancellation.pi_s_abs_upper = ...
  geometry.local_complex.target_tangent_projection_abs_upper;
maue_factors = LOCAL_local_factor_bounds(z, maue_geometry, cfg);
density_weight = exp(a * abs(density.orders));
tau_strip = sum(density_weight .* ...
  vecnorm(density.tau_coeff_map, 2, 2));
tau_prime_strip = sum(abs(density.orders) .* density_weight .* ...
  vecnorm(density.tau_coeff_map, 2, 2));
sigma_strip = sum(density_weight .* ...
  vecnorm(density.sigma_coeff_map, 2, 2));
strip_speed = geometry.local_complex.strip_speed_upper;
strip_path_length = geometry.local_complex.strip_path_length_upper;
value_log_integrand = strip_speed * (...
  strip_factors.C_K * tau_strip + strip_factors.C_S * sigma_strip);
value_smooth_integrand = strip_speed * (...
  strip_factors.R_K * tau_strip + strip_factors.R_S * sigma_strip);
k_outer = double(z.khat);
k_inner = sqrt(double(z.rho_disk)) * k_outer;
J_outer = strip_factors.series_outer.J(1);
J_inner = strip_factors.series_inner.J(1);
D_outer = strip_factors.series_outer.D(1);
D_inner = strip_factors.series_inner.D(1);
euler_constant = 0.57721566490153286060;
c_outer = abs(1i / 4.0 - ...
  (log(k_outer / 2.0) + euler_constant) / (2.0 * pi));
c_inner = abs(1i / 4.0 - ...
  (log(k_inner / 2.0) + euler_constant) / (2.0 * pi));
maue_M_log = (k_outer^2 * J_outer + k_inner^2 * J_inner) / ...
  (4.0 * pi);
maue_M_smooth = maue_M_log * ...
  geometry.local_complex.log_chord_quotient_upper + ...
  k_outer^2 * (c_outer * J_outer + D_outer / (2.0 * pi)) + ...
  k_inner^2 * (c_inner * J_inner + D_inner / (2.0 * pi));
tangent_dot = geometry.local_complex.normalized_tangent_dot_abs_upper;
normal_log_integrand = strip_speed * tangent_dot * maue_M_log * ...
  tau_strip + maue_factors.C_Kstar * tau_prime_strip;
normal_smooth_integrand = strip_speed * tangent_dot * maue_M_smooth * ...
  tau_strip + maue_factors.R_Kstar * tau_prime_strip;
alias_factor = 4.0 * pi * exp(-a * N / 2.0) * ...
  (1.0 + exp(-a)) / (1.0 - exp(-a));
smooth_factor = 4.0 * pi / expm1(a * N);
source_value_error = alias_factor * value_log_integrand + ...
  smooth_factor * value_smooth_integrand;
source_normal_error = alias_factor * normal_log_integrand + ...
  smooth_factor * normal_smooth_integrand;
value_strip_upper = tau_strip + ...
  (4.0 * strip_path_length * log(2.0) * strip_factors.C_K + ...
  strip_path_length * strip_factors.R_K) * tau_strip + ...
  (4.0 * strip_path_length * log(2.0) * strip_factors.C_S + ...
  strip_path_length * strip_factors.R_S) * sigma_strip;
normal_strip_upper = sigma_strip + ...
  (4.0 * strip_path_length * log(2.0) * strip_factors.C_T + ...
  strip_path_length * strip_factors.R_T) * tau_strip + ...
  (4.0 * strip_path_length * log(2.0) * strip_factors.C_Kstar + ...
  strip_path_length * strip_factors.R_Kstar) * sigma_strip;
xi = 2.0 * pi * mode_orders / P;
phase_growth = exp(abs(xi) * ...
  geometry.local_complex.arclength_imag_upper);
target_factor = 4.0 * pi * strip_speed / ...
  (sqrt(P) * expm1(a * N));
target_value_error = target_factor * value_strip_upper .* phase_growth;
target_normal_error = target_factor * normal_strip_upper .* phase_growth;
source_to_row = sum((2.0 * pi / N) * geometry.speed) / sqrt(P);
value_error = source_to_row * source_value_error + target_value_error;
normal_error = source_to_row * source_normal_error + target_normal_error;
tau_identity_l2 = sqrt(2.0 * pi * ...
  geometry.certificate.speed_upper) * density.tau_linf_upper;
sigma_identity_l2 = sqrt(2.0 * pi * ...
  geometry.certificate.speed_upper) * density.sigma_linf_upper;
value_action = (4.0 * P * log(2.0) * factors.C_K + ...
  P * factors.R_K) * density.tau_linf_upper + ...
  (4.0 * P * log(2.0) * factors.C_S + ...
  P * factors.R_S) * density.sigma_linf_upper;
normal_action = (4.0 * P * log(2.0) * factors.C_T + ...
  P * factors.R_T) * density.tau_linf_upper + ...
  (4.0 * P * log(2.0) * factors.C_Kstar + ...
  P * factors.R_Kstar) * density.sigma_linf_upper;
value_l2_upper = tau_identity_l2 + sqrt(P) * value_action;
normal_l2_upper = sigma_identity_l2 + sqrt(P) * normal_action;
tau_second_l2 = sqrt(2.0 * pi * geometry.certificate.speed_upper) * ...
  (geometry.certificate.speed_lower^(-2.0) * ...
  sum((density.orders.^2) .* vecnorm(density.tau_coeff_map, 2, 2)) + ...
  geometry.certificate.speed_derivative_upper * ...
  geometry.certificate.speed_lower^(-3.0) * ...
  sum(abs(density.orders) .* vecnorm(density.tau_coeff_map, 2, 2)));
value_second_action = (4.0 * P * log(2.0) * factors.C_K2 + ...
  P * factors.R_K2) * density.tau_linf_upper + ...
  (4.0 * P * log(2.0) * factors.C_S2 + ...
  P * factors.R_S2) * density.sigma_linf_upper;
value_second_l2_upper = tau_second_l2 + sqrt(P) * value_second_action;
action = struct( ...
  'mode_orders', mode_orders, ...
  'value_rows', value_rows, ...
  'normal_rows', normal_rows, ...
  'value_row_error', value_error, ...
  'normal_row_error', normal_error, ...
  'value_l2_upper', value_l2_upper, ...
  'normal_l2_upper', normal_l2_upper, ...
  'value_second_l2_upper', value_second_l2_upper, ...
  'value_strip_upper', value_strip_upper, ...
  'normal_strip_upper', normal_strip_upper, ...
  'factor_bounds', factors, ...
  'complex_strip_factor_bounds', strip_factors, ...
  'maue_strip_factor_bounds', struct( ...
    'tau_prime_strip_upper', tau_prime_strip, ...
    'weighted_single_layer_log_upper', maue_M_log, ...
    'weighted_single_layer_smooth_upper', maue_M_smooth, ...
    'tangent_derivative_log_upper', maue_factors.C_Kstar, ...
    'tangent_derivative_smooth_upper', maue_factors.R_Kstar, ...
    'cotangent_difference_cancelled_before_bound', true), ...
  'panel_fields', struct( ...
    'panel_half_width', cfg.panel_half_width, ...
    'panel_taylor_order', cfg.panel_taylor_order, ...
    'kernel_series_cutoff', cfg.kernel_series_cutoff, ...
    'periodic_log_moment_enclosure', factors.log_moment_upper, ...
    'P11_P14_taylor_panel_used', false, ...
    'equivalent_kress_alias_enclosure_used', true, ...
    'kress_log_alias_factor', alias_factor, ...
    'smooth_trapezoid_factor', smooth_factor, ...
    'singular_panel_remainder', source_to_row * alias_factor * ...
      value_log_integrand, ...
    'regular_panel_remainder', source_to_row * smooth_factor * ...
      value_smooth_integrand, ...
    'retained_target_row_remainder', target_value_error, ...
    'normal_singular_panel_remainder', source_to_row * alias_factor * ...
      normal_log_integrand, ...
    'normal_regular_panel_remainder', source_to_row * smooth_factor * ...
      normal_smooth_integrand, ...
    'normal_retained_target_row_remainder', target_normal_error, ...
    'sampling_drift_used', false), ...
  'gate', struct( ...
    'cancellation_safe_factors', factors.gate.pass, ...
    'panel_width', true, ...
    'series_ratio', factors.gate.series_ratio_pass, ...
    'normalized_chord_zero_free', ...
      geometry.local_complex.normalized_chord_zero_free, ...
    'log_chord_branch_fixed', geometry.local_complex.log_chord_branch_fixed, ...
    'simultaneous_shift_admissible', ...
      geometry.local_complex.simultaneous_shift_admissible, ...
    'global_action_triangle_enclosure', false, ...
    'pass', factors.gate.pass && strip_factors.gate.pass && ...
      geometry.local_complex.normalized_chord_zero_free && ...
      geometry.local_complex.log_chord_branch_fixed && ...
      geometry.local_complex.simultaneous_shift_admissible && ...
      all(isfinite([value_error; normal_error]))));
end

function R = LOCAL_kress_matrix(N)
rvec = quad.quad_kress_rvec(N);
offset = mod((0:N - 1) - (0:N - 1).', N) + 1;
R = rvec(offset);
end

function factors = LOCAL_local_factor_bounds(z, geometry, cfg)
c = geometry.cancellation;
Q = c.q_abs_upper;
k_outer = double(z.khat);
k_inner = sqrt(double(z.rho_disk)) * k_outer;
series_outer = LOCAL_kernel_series_bounds( ...
  k_outer, Q, cfg.kernel_series_cutoff);
series_inner = LOCAL_kernel_series_bounds( ...
  k_inner, Q, cfg.kernel_series_cutoff);
A = (series_outer.J + series_inner.J) / (4.0 * pi);
a = (series_outer.a + series_inner.a) / (4.0 * pi);
euler_constant = 0.57721566490153286060;
c_outer = abs(1i / 4.0 - ...
  (log(k_outer / 2.0) + euler_constant) / (2.0 * pi));
c_inner = abs(1i / 4.0 - ...
  (log(k_inner / 2.0) + euler_constant) / (2.0 * pi));
B = c_outer * series_outer.J + c_inner * series_inner.J + ...
  (series_outer.D + series_inner.D) / (2.0 * pi);
lc = geometry.cancellation.log_chord_quotient_upper;
C_S = A(1);
R_S = A(1) * lc + B(1);
U1 = (a(1) + Q * a(2)) * lc + a(1) + B(2);
C_K = 2.0 * c.p_abs_upper * A(2);
R_K = 2.0 * c.p_abs_upper * U1;
C_Kstar = 2.0 * c.pi_s_abs_upper * A(2);
R_Kstar = 2.0 * c.pi_s_abs_upper * U1;
pi_product = c.p_abs_upper * c.pi_s_abs_upper;
C_T = 2.0 * c.normal_dot_abs_upper * A(2) + ...
  4.0 * pi_product * A(3);
R_T = 2.0 * c.normal_dot_abs_upper * U1 + ...
  4.0 * pi_product * (2.0 * a(2) + Q * a(3)) * lc + ...
  4.0 * c.pi_s_pi_t_over_q_upper * a(1) + ...
  8.0 * pi_product * a(2) + 4.0 * pi_product * B(3);
q_s_squared = c.q_s_abs_upper^2;
p_s_q_s = c.p_s_abs_upper * c.q_s_abs_upper;
p_q_ss = c.p_abs_upper * c.q_ss_abs_upper;
p_q_s_squared = c.p_abs_upper * q_s_squared;
C_S2 = q_s_squared * A(3) + c.q_ss_abs_upper * A(2);
R_S2 = q_s_squared * (2.0 * a(2) + Q * a(3)) * lc + ...
  c.q_s_squared_over_q_upper * a(1) + ...
  2.0 * q_s_squared * a(2) + q_s_squared * B(3) + ...
  c.q_ss_abs_upper * U1;
C_K2 = 2.0 * (c.p_ss_abs_upper * A(2) + ...
  2.0 * p_s_q_s * A(3) + ...
  c.p_abs_upper * (q_s_squared * A(4) + c.q_ss_abs_upper * A(3)));
R_K2 = 2.0 * (c.p_ss_abs_upper * U1 + ...
  2.0 * p_s_q_s * (2.0 * a(2) + Q * a(3)) * lc + ...
  2.0 * c.p_s_q_s_over_q_upper * a(1) + ...
  4.0 * p_s_q_s * a(2) + 2.0 * p_s_q_s * B(3) + ...
  p_q_ss * (2.0 * a(2) + Q * a(3)) * lc + ...
  c.p_q_ss_over_q_upper * a(1) + 2.0 * p_q_ss * a(2) + ...
  p_q_ss * B(3) + ...
  p_q_s_squared * (3.0 * a(3) + Q * a(4)) * lc + ...
  3.0 * c.p_q_s_squared_over_q_upper * a(2) + ...
  3.0 * p_q_s_squared * a(3) + ...
  c.p_q_s_squared_over_q_squared_upper * a(1) + ...
  p_q_s_squared * B(4));
j = 0:cfg.panel_taylor_order + 1.0;
delta = cfg.panel_half_width;
P = geometry.certificate.boundary_length;
log_moment_upper = 4.0 * delta.^(j + 1.0) ./ (j + 1.0) .* ...
  (log(P / (4.0 * delta)) + 1.0 ./ (j + 1.0));
series_ratio_pass = series_outer.ratio_pass && series_inner.ratio_pass;
factors = struct( ...
  'C_S', C_S, 'R_S', R_S, ...
  'C_K', C_K, 'R_K', R_K, ...
  'C_Kstar', C_Kstar, 'R_Kstar', R_Kstar, ...
  'C_T', C_T, 'R_T', R_T, ...
  'C_S2', C_S2, 'R_S2', R_S2, ...
  'C_K2', C_K2, 'R_K2', R_K2, ...
  'log_moment_upper', log_moment_upper, ...
  'series_outer', series_outer, ...
  'series_inner', series_inner, ...
  'gate', struct( ...
    'series_ratio_pass', series_ratio_pass, ...
    'bare_q_inverse_evaluated', false, ...
    'all_finite', all(isfinite([A, a, B, C_S, R_S, C_K, R_K, ...
      C_T, R_T, C_S2, R_S2, C_K2, R_K2])), ...
    'pass', series_ratio_pass && all(isfinite([A, a, B, C_S, R_S, ...
      C_K, R_K, C_T, R_T, C_S2, R_S2, C_K2, R_K2]))));
end

function out = LOCAL_kernel_series_bounds(k, Q, N)
J = zeros(1, 4);
D = zeros(1, 4);
a = zeros(1, 4);
ratios = zeros(3, 4);
for r = 0:3
  [J(r + 1), ratios(1, r + 1)] = ...
    LOCAL_series_derivative_bound(k, Q, N, r, 'J');
  [D(r + 1), ratios(2, r + 1)] = ...
    LOCAL_series_derivative_bound(k, Q, N, r, 'D');
  [a(r + 1), ratios(3, r + 1)] = ...
    LOCAL_series_derivative_bound(k, Q, N, r, 'a');
end
out = struct('J', J, 'D', D, 'a', a, 'ratios', ratios, ...
  'ratio_pass', all(ratios(:) < 1.0));
end

function [bound, rho] = LOCAL_series_derivative_bound(k, Q, N, r, kind)
x = k^2 / 4.0;
bound = 0.0;
if strcmp(kind, 'a')
  start = r;
  for m = start:N
    bound = bound + exp(gammaln(m + 1.0) - gammaln(m - r + 1.0) + ...
      (m + 1.0) * log(x) + (m - r) * log(Q) - ...
      2.0 * gammaln(m + 2.0));
  end
  m = N + 1.0;
  first = exp(gammaln(m + 1.0) - gammaln(m - r + 1.0) + ...
    (m + 1.0) * log(x) + (m - r) * log(Q) - ...
    2.0 * gammaln(m + 2.0));
  rho = x * Q * (m + 1.0) / ((m + 1.0 - r) * (m + 2.0)^2);
else
  start = max(0.0, r);
  if strcmp(kind, 'D')
    start = max(1.0, r);
  end
  for n = start:N
    harmonic = 1.0;
    if strcmp(kind, 'D')
      harmonic = sum(1.0 ./ (1.0:n));
    end
    bound = bound + harmonic * exp(gammaln(n + 1.0) - ...
      gammaln(n - r + 1.0) + n * log(x) + ...
      (n - r) * log(Q) - 2.0 * gammaln(n + 1.0));
  end
  n = N + 1.0;
  harmonic = 1.0;
  if strcmp(kind, 'D')
    harmonic = sum(1.0 ./ (1.0:n));
  end
  first = harmonic * exp(gammaln(n + 1.0) - ...
    gammaln(n - r + 1.0) + n * log(x) + ...
    (n - r) * log(Q) - 2.0 * gammaln(n + 1.0));
  rho = x * Q / ((n + 1.0) * (n + 1.0 - r));
  if strcmp(kind, 'D')
    rho = rho * (1.0 + 1.0 / (n + 1.0));
  end
end
if rho >= 1.0
  bound = Inf;
else
  bound = bound + first / (1.0 - rho);
end
end

%% ==================== Exact Ewald regular-image action ====================
% The finite exact representation is separated from its four analytic tails.

function action = LOCAL_regular_action(z, geometry, density, certificate, cfg)
N = numel(geometry.parameter_nodes);
value_samples = zeros(N, size(density.tau_values, 2));
normal_samples = value_samples;
source_weight = geometry.speed.' * (2.0 * pi / N);
for first = 1:32:N
  ids = first:min(first + 31, N);
  target = geometry.position(ids, :);
  coordinate = LOCAL_ewald_regular_coordinates( ...
    target, geometry.position, double(z.khat), double(z.beta), ...
    double(z.d), cfg);
  nsx = geometry.normal(:, 1).';
  nsy = geometry.normal(:, 2).';
  ntx = geometry.normal(ids, 1);
  nty = geometry.normal(ids, 2);
  source_normal = -(coordinate.dx .* nsx + coordinate.dy .* nsy);
  target_normal = coordinate.dx .* ntx + coordinate.dy .* nty;
  mixed_normal = -(coordinate.dxx .* (ntx * nsx) + ...
    coordinate.dxy .* (ntx * nsy + nty * nsx) + ...
    coordinate.dyy .* (nty * nsy));
  weighted_tau = density.tau_values .* source_weight.';
  weighted_sigma = density.sigma_values .* source_weight.';
  value_samples(ids, :) = source_normal * weighted_tau + ...
    coordinate.value * weighted_sigma;
  normal_samples(ids, :) = mixed_normal * weighted_tau + ...
    target_normal * weighted_sigma;
end
[value_rows, mode_orders] = LOCAL_rows(value_samples, geometry, cfg);
[normal_rows, ~] = LOCAL_rows(normal_samples, geometry, cfg);
P = geometry.certificate.boundary_length;
A_tau = P * density.tau_linf_upper;
A_sigma = P * density.sigma_linf_upper;
K = certificate.kernel_constant_upper;
a = geometry.certificate.parameter_strip_width;
strip_speed = geometry.certificate.strip_speed_upper;
density_weight = exp(a * abs(density.orders));
tau_strip = sum(density_weight .* ...
  vecnorm(density.tau_coeff_map, 2, 2));
sigma_strip = sum(density_weight .* ...
  vecnorm(density.sigma_coeff_map, 2, 2));
strip_path_length = 2.0 * pi * strip_speed;
value_strip_upper = strip_path_length * (...
  K(3) * tau_strip + K(1) * sigma_strip);
normal_strip_upper = strip_path_length * (...
  K(4) * tau_strip + K(2) * sigma_strip);
Kfinite = certificate.kernel_finite_upper;
Ktail = certificate.kernel_tail_upper;
finite_source_integrand_value = strip_speed * (...
  Kfinite(3) * tau_strip + Kfinite(1) * sigma_strip);
finite_source_integrand_normal = strip_speed * (...
  Kfinite(4) * tau_strip + Kfinite(2) * sigma_strip);
source_trapezoid_value = 4.0 * pi * finite_source_integrand_value / ...
  expm1(a * N);
source_trapezoid_normal = 4.0 * pi * finite_source_integrand_normal / ...
  expm1(a * N);
ewald_tail_value = Ktail(3) * A_tau + Ktail(1) * A_sigma;
ewald_tail_normal = Ktail(4) * A_tau + Ktail(2) * A_sigma;
sample_value_error = source_trapezoid_value + ewald_tail_value;
sample_normal_error = source_trapezoid_normal + ewald_tail_normal;
xi = 2.0 * pi * mode_orders / P;
phase_growth = exp(abs(xi) * geometry.certificate.arclength_imag_upper);
target_factor = 4.0 * pi * strip_speed / ...
  (sqrt(P) * expm1(a * N));
target_value_error = target_factor * value_strip_upper .* phase_growth;
target_normal_error = target_factor * normal_strip_upper .* phase_growth;
source_to_row = sum((2.0 * pi / N) * geometry.speed) / sqrt(P);
value_row_error = source_to_row * sample_value_error + target_value_error;
normal_row_error = source_to_row * sample_normal_error + target_normal_error;
action = struct( ...
  'mode_orders', mode_orders, ...
  'value_rows', value_rows, ...
  'normal_rows', normal_rows, ...
  'value_row_error', value_row_error, ...
  'normal_row_error', normal_row_error, ...
  'value_strip_upper', value_strip_upper, ...
  'normal_strip_upper', normal_strip_upper, ...
  'source_trapezoid_value_error', source_trapezoid_value, ...
  'source_trapezoid_normal_error', source_trapezoid_normal, ...
  'ewald_truncation_value_error', ewald_tail_value, ...
  'ewald_truncation_normal_error', ewald_tail_normal, ...
  'retained_target_value_error', target_value_error, ...
  'retained_target_normal_error', target_normal_error, ...
  'gate', certificate.gate);
end

function coordinate = LOCAL_ewald_regular_coordinates( ...
    target, source, k, beta, d, cfg)
X = target(:, 1) - source(:, 1).';
Y = target(:, 2) - source(:, 2).';
h = cfg.ewald_split / d;
eta = (k * d / (2.0 * cfg.ewald_split))^2;
value = zeros(size(X)); dx = value; dy = value;
dxx = value; dxy = value; dyy = value;
modes = -(cfg.reciprocal_cutoff - 1.0):cfg.reciprocal_cutoff - 1.0;
for m = modes
  t = beta + 2.0 * pi * m / d;
  q = sqrt(complex(t^2 - k^2));
  if real(q) < 0.0 || (real(q) == 0.0 && imag(q) > 0.0)
    q = -q;
  end
  if q == 0.0
    error('I5Residual:ExactWood', 'A retained Ewald denominator is zero.');
  end
  phase = exp(1i * t * Y) / (4.0 * d * q);
  F0 = zeros(size(X)); F1 = F0; F2 = F0;
  for sign_value = [-1.0, 1.0]
    u = q / (2.0 * h) + sign_value * h * X;
    exponential = exp(sign_value * q * X);
    erfc_value = Faddeeva_erfc(u);
    erfc_first = -2.0 / sqrt(pi) * exp(-u.^2);
    erfc_second = 4.0 / sqrt(pi) * u .* exp(-u.^2);
    F0 = F0 + exponential .* erfc_value;
    F1 = F1 + sign_value * exponential .* ...
      (q * erfc_value + h * erfc_first);
    F2 = F2 + exponential .* (q^2 * erfc_value + ...
      2.0 * q * h * erfc_first + h^2 * erfc_second);
  end
  value = value + phase .* F0;
  dx = dx + phase .* F1;
  dy = dy + 1i * t * phase .* F0;
  dxx = dxx + phase .* F2;
  dxy = dxy + 1i * t * phase .* F1;
  dyy = dyy - t^2 * phase .* F0;
end
for image = [-(cfg.image_cutoff - 1.0):-1.0, ...
    1.0:cfg.image_cutoff - 1.0]
  shifted_y = Y - image * d;
  zeta = h^2 * (X.^2 + shifted_y.^2);
  [H0, H1, H2] = LOCAL_H_eta(zeta, eta, cfg.taylor_cutoff);
  phase = exp(1i * beta * image * d) / (4.0 * pi);
  zx = 2.0 * h^2 * X;
  zy = 2.0 * h^2 * shifted_y;
  value = value + phase * H0;
  dx = dx + phase * (H1 .* zx);
  dy = dy + phase * (H1 .* zy);
  dxx = dxx + phase * (H2 .* zx.^2 + 2.0 * h^2 * H1);
  dxy = dxy + phase * (H2 .* zx .* zy);
  dyy = dyy + phase * (H2 .* zy.^2 + 2.0 * h^2 * H1);
end
zeta = h^2 * (X.^2 + Y.^2);
[C0, C1, C2] = LOCAL_C_eta(zeta, eta, cfg.taylor_cutoff);
zx = 2.0 * h^2 * X;
zy = 2.0 * h^2 * Y;
value = value - C0;
dx = dx - C1 .* zx;
dy = dy - C1 .* zy;
dxx = dxx - (C2 .* zx.^2 + 2.0 * h^2 * C1);
dxy = dxy - C2 .* zx .* zy;
dyy = dyy - (C2 .* zy.^2 + 2.0 * h^2 * C1);
coordinate = struct('value', value, 'dx', dx, 'dy', dy, ...
  'dxx', dxx, 'dxy', dxy, 'dyy', dyy);
end

function [H0, H1, H2] = LOCAL_H_eta(z, eta, N)
exp_minus = exp(-z);
Eminus = exp_minus .* (1.0 ./ z + 1.0 ./ z.^2);
Ezero = exp_minus ./ z;
Eplus = expint(z);
H0 = zeros(size(z)); H1 = H0; H2 = H0;
coefficient = 1.0;
for n = 0:N
  H0 = H0 + coefficient * Eplus;
  H1 = H1 - coefficient * Ezero;
  H2 = H2 + coefficient * Eminus;
  if n < N
    Enext = (exp_minus - z .* Eplus) / (n + 1.0);
    Eminus = Ezero;
    Ezero = Eplus;
    Eplus = Enext;
    coefficient = coefficient * eta / (n + 1.0);
  end
end
end

function [C0, C1, C2] = LOCAL_C_eta(z, eta, N)
gamma_e = 0.57721566490153286060;
J = zeros(1, N + 1); S = J; D = J; Q = J;
harmonic = 0.0;
for n = 0:N
  J(n + 1) = (-eta)^n / exp(2.0 * gammaln(n + 1.0));
  if n >= 1
    harmonic = harmonic + 1.0 / n;
    S(n + 1) = (-1.0)^n / (n * exp(gammaln(n + 1.0)));
    D(n + 1) = (-1.0)^n * harmonic * eta^n / ...
      exp(2.0 * gammaln(n + 1.0));
    for j = 0:n - 1
      Q(j + 1) = Q(j + 1) + eta^n / ...
        exp(2.0 * gammaln(n + 1.0)) * ...
        exp(gammaln(n - j)) * (-1.0)^j;
    end
  end
end
c_eta = log(eta) + gamma_e - 1i * pi;
polynomial = conv(J, S);
polynomial(1:numel(J)) = polynomial(1:numel(J)) - c_eta * J;
polynomial(1:numel(D)) = polynomial(1:numel(D)) + 2.0 * D;
polynomial = polynomial / (4.0 * pi);
[P0, P1, P2] = LOCAL_polynomial_012(polynomial, z);
[Q0, Q1, Q2] = LOCAL_polynomial_012(Q, z);
ez = exp(-z) / (4.0 * pi);
C0 = P0 - ez .* Q0;
C1 = P1 - ez .* (Q1 - Q0);
C2 = P2 - ez .* (Q2 - 2.0 * Q1 + Q0);
end

function [v0, v1, v2] = LOCAL_polynomial_012(coefficients, z)
n = 0:numel(coefficients) - 1;
v0 = polyval(fliplr(coefficients), z);
if numel(coefficients) > 1
  first = coefficients(2:end) .* n(2:end);
  v1 = polyval(fliplr(first), z);
else
  v1 = zeros(size(z));
end
if numel(coefficients) > 2
  second = coefficients(3:end) .* n(3:end) .* (n(3:end) - 1.0);
  v2 = polyval(fliplr(second), z);
else
  v2 = zeros(size(z));
end
end

function certificate = LOCAL_ewald_certificate(z, geometry, cfg)
k = double(z.khat); d = double(z.d); beta = double(z.beta);
h = cfg.ewald_split / d;
eta = (k * d / (2.0 * cfg.ewald_split))^2;
tube = geometry.tube;
RX = tube.displacement_abs_upper(1); RY = tube.displacement_abs_upper(2);
IX = tube.displacement_imag_upper(1); IY = tube.displacement_imag_upper(2);
UX = tube.displacement_real_upper(1); UY = tube.displacement_real_upper(2);
finite = LOCAL_ewald_finite_upper(k, beta, d, h, eta, ...
  RX, RY, IX, IY, UX, UY, cfg);
[reciprocal_tail, reciprocal_gate] = LOCAL_reciprocal_tail( ...
  k, beta, d, h, RX, IX, IY, UX, cfg.reciprocal_cutoff);
[image_tail, image_gate] = LOCAL_image_tail( ...
  d, h, eta, RX, RY, IX, IY, UY, cfg.image_cutoff);
[taylor_tail, taylor_gate] = LOCAL_taylor_tail( ...
  d, h, eta, RX, RY, IX, IY, UY, cfg.image_cutoff, ...
  cfg.taylor_cutoff);
[local_finite, local_tail, local_gate] = LOCAL_local_ewald_bound( ...
  h, eta, RX, RY, cfg);
coordinate_finite_upper = finite + local_finite;
coordinate_tail_upper = reciprocal_tail + image_tail + ...
  taylor_tail + local_tail;
coordinate_upper = coordinate_finite_upper + coordinate_tail_upper;
Nt = tube.target_normal_component_upper;
Ns = tube.source_normal_component_upper;
kernel_constant_upper = [ ...
  coordinate_upper(1), ...
  Nt(1) * coordinate_upper(2) + Nt(2) * coordinate_upper(3), ...
  Ns(1) * coordinate_upper(2) + Ns(2) * coordinate_upper(3), ...
  Nt(1) * Ns(1) * coordinate_upper(4) + ...
    (Nt(1) * Ns(2) + Nt(2) * Ns(1)) * coordinate_upper(5) + ...
    Nt(2) * Ns(2) * coordinate_upper(6)];
kernel_finite_upper = [ ...
  coordinate_finite_upper(1), ...
  Nt(1) * coordinate_finite_upper(2) + ...
    Nt(2) * coordinate_finite_upper(3), ...
  Ns(1) * coordinate_finite_upper(2) + ...
    Ns(2) * coordinate_finite_upper(3), ...
  Nt(1) * Ns(1) * coordinate_finite_upper(4) + ...
    (Nt(1) * Ns(2) + Nt(2) * Ns(1)) * ...
      coordinate_finite_upper(5) + ...
    Nt(2) * Ns(2) * coordinate_finite_upper(6)];
kernel_tail_upper = [ ...
  coordinate_tail_upper(1), ...
  Nt(1) * coordinate_tail_upper(2) + ...
    Nt(2) * coordinate_tail_upper(3), ...
  Ns(1) * coordinate_tail_upper(2) + ...
    Ns(2) * coordinate_tail_upper(3), ...
  Nt(1) * Ns(1) * coordinate_tail_upper(4) + ...
    (Nt(1) * Ns(2) + Nt(2) * Ns(1)) * coordinate_tail_upper(5) + ...
    Nt(2) * Ns(2) * coordinate_tail_upper(6)];
gate_pass = reciprocal_gate.pass && image_gate.pass && ...
  taylor_gate.pass && local_gate.pass && ...
  all(isfinite(kernel_constant_upper));
certificate = struct( ...
  'coordinate_order', {{'00', '10', '01', '20', '11', '02'}}, ...
  'coordinate_finite_upper', coordinate_finite_upper, ...
  'reciprocal_coordinate_tail', reciprocal_tail, ...
  'omitted_image_coordinate_tail', image_tail, ...
  'retained_image_taylor_tail', taylor_tail, ...
  'local_factorial_coordinate_tail', local_tail, ...
  'coordinate_tail_upper', coordinate_tail_upper, ...
  'kernel_constant_upper', kernel_constant_upper, ...
  'kernel_finite_upper', kernel_finite_upper, ...
  'kernel_tail_upper', kernel_tail_upper, ...
  'reciprocal_tail_gate', reciprocal_gate, ...
  'image_tail_gate', image_gate, ...
  'taylor_tail_gate', taylor_gate, ...
  'local_series_gate', local_gate, ...
  'gate', struct( ...
    'exact_wood_excluded', reciprocal_gate.nonwood, ...
    'all_ratio_gates', gate_pass, ...
    'finite_special_functions_ordinary', true, ...
    'analytic_truncation_complete', gate_pass, ...
    'pass', gate_pass));
end

function upper = LOCAL_ewald_finite_upper( ...
    k, beta, d, h, eta, RX, RY, IX, IY, UX, UY, cfg)
upper = zeros(1, 6);
mu = [sqrt(pi) / 2.0, 0.5, sqrt(pi) / 4.0];
Pr = [mu(1), 2.0 * h^2 * RX * mu(1) + 2.0 * h * mu(2), ...
  (4.0 * h^4 * RX^2 + 2.0 * h^2) * mu(1) + ...
  8.0 * h^3 * RX * mu(2) + 4.0 * h^2 * mu(3)];
derivative_orders = [0, 0; 1, 0; 0, 1; 2, 0; 1, 1; 0, 2];
for m = -(cfg.reciprocal_cutoff - 1.0):cfg.reciprocal_cutoff - 1.0
  t = beta + 2.0 * pi * m / d;
  q = sqrt(complex(t^2 - k^2));
  if real(q) < 0.0 || (real(q) == 0.0 && imag(q) > 0.0), q = -q; end
  qa = abs(q);
  if qa == 0.0, upper(:) = Inf; return; end
  if isreal(q) && q >= 2.0 * h^2 * UX
    for index = 1:6
      r = derivative_orders(index, 1);
      s = derivative_orders(index, 2);
      upper(index) = upper(index) + Pr(r + 1) / (d * sqrt(pi)) * ...
        abs(t)^s / q * exp(-q^2 / (4.0 * h^2) + ...
          h^2 * IX^2 + abs(t) * IY);
    end
    continue;
  end
  u = qa / (2.0 * h) + h * RX;
  eu = exp(u^2);
  E0 = 1.0 + 2.0 * u * eu / sqrt(pi);
  E1 = 2.0 * eu / sqrt(pi);
  E2 = 4.0 * u * eu / sqrt(pi);
  ex = exp(qa * RX + abs(t) * IY) / (2.0 * d * qa);
  F0 = ex * E0;
  F1 = ex * (qa * E0 + h * E1);
  F2 = ex * (qa^2 * E0 + 2.0 * qa * h * E1 + h^2 * E2);
  upper = upper + [F0, F1, abs(t) * F0, F2, ...
    abs(t) * F1, t^2 * F0];
end
for image = [-(cfg.image_cutoff - 1.0):-1.0, ...
    1.0:cfg.image_cutoff - 1.0]
  u = h^2 * ((abs(image) * d - UY)^2 - IX^2 - IY^2);
  if u <= 0.0, upper(:) = Inf; return; end
  H01 = exp(eta - u) / u;
  H2 = exp(eta - u) * (1.0 / u + 1.0 / u^2);
  zx = 2.0 * h^2 * RX;
  zy = 2.0 * h^2 * (abs(image) * d + RY);
  upper = upper + [H01, zx * H01, zy * H01, ...
    zx^2 * H2 + 2.0 * h^2 * H01, zx * zy * H2, ...
    zy^2 * H2 + 2.0 * h^2 * H01] / (4.0 * pi);
end
end

function [tail, gate] = LOCAL_reciprocal_tail( ...
    k, beta, d, h, RX, IX, IY, UX, NR)
b = 2.0 * pi / d;
mu = [sqrt(pi) / 2.0, 0.5, sqrt(pi) / 4.0];
P = [mu(1), 2.0 * h^2 * RX * mu(1) + 2.0 * h * mu(2), ...
  (4.0 * h^4 * RX^2 + 2.0 * h^2) * mu(1) + ...
  8.0 * h^3 * RX * mu(2) + 4.0 * h^2 * mu(3)];
tail = zeros(1, 6);
orders = [0, 0; 1, 0; 0, 1; 2, 0; 1, 1; 0, 2];
ratios = zeros(2, 3); all_gate = true;
for side_index = 1:2
  side_sign = [-1.0, 1.0];
  t0 = b * NR + side_sign(side_index) * beta;
  q0 = sqrt(t0^2 - k^2);
  all_gate = all_gate && t0 > k && q0 >= 2.0 * h^2 * UX;
  for s = 0:2
    rho = (1.0 + b / t0)^s * ...
      exp(-b * (2.0 * t0 + b) / (4.0 * h^2) + b * IY);
    ratios(side_index, s + 1) = rho;
  end
  for index = 1:6
    r = orders(index, 1); s = orders(index, 2);
    first = t0^s / q0 * exp(-q0^2 / (4.0 * h^2) + t0 * IY);
    tail(index) = tail(index) + P(r + 1) * exp(h^2 * IX^2) / ...
      (d * sqrt(pi)) * first / (1.0 - ratios(side_index, s + 1));
  end
end
gate = struct('nonwood', all_gate, 'ratios', ratios, ...
  'pass', all_gate && all(ratios(:) < 1.0));
end

function [tail, gate] = LOCAL_image_tail( ...
    d, h, eta, RX, RY, IX, IY, UY, NI)
u = h^2 * ((NI * d - UY)^2 - IX^2 - IY^2);
L = NI * d + RY;
rho = zeros(1, 3); S1 = rho; S2 = rho;
for alpha = 0:2
  rho(alpha + 1) = (1.0 + d / L)^alpha * ...
    exp(-h^2 * d * (2.0 * (NI * d - UY) + d));
  S1(alpha + 1) = 2.0 * L^alpha * exp(-u) / ...
    (u * (1.0 - rho(alpha + 1)));
  S2(alpha + 1) = 2.0 * L^alpha * exp(-u) / ...
    (u^2 * (1.0 - rho(alpha + 1)));
end
c = exp(eta) / (4.0 * pi);
zx = 2.0 * h^2 * RX;
tail = c * [S1(1), zx * S1(1), 2.0 * h^2 * S1(2), ...
  zx^2 * (S1(1) + S2(1)) + 2.0 * h^2 * S1(1), ...
  zx * 2.0 * h^2 * (S1(2) + S2(2)), ...
  (2.0 * h^2)^2 * (S1(3) + S2(3)) + ...
    2.0 * h^2 * S1(1)];
gate = struct('u_first', u, 'ratios', rho, ...
  'pass', NI * d > UY && u > 0.0 && all(rho < 1.0));
end

function [tail, gate] = LOCAL_taylor_tail( ...
    d, h, eta, RX, RY, IX, IY, UY, NI, N)
poisson_tail = exp(eta) - sum(eta.^(0:N) ./ exp(gammaln((0:N) + 1.0)));
poisson_tail = max(0.0, poisson_tail);
tail = zeros(1, 6); positive = true;
u_values = zeros(1, 2 * (NI - 1)); cursor = 0;
for image = [-(NI - 1.0):-1.0, 1.0:NI - 1.0]
  cursor = cursor + 1;
  u = h^2 * ((abs(image) * d - UY)^2 - IX^2 - IY^2);
  u_values(cursor) = u;
  positive = positive && u > 0.0;
  theta = poisson_tail * exp(-u) / u;
  zx = 2.0 * h^2 * RX;
  zy = 2.0 * h^2 * (abs(image) * d + RY);
  tail = tail + theta / (4.0 * pi) * [1.0, zx, zy, ...
    zx^2 + 2.0 * h^2, zx * zy, zy^2 + 2.0 * h^2];
end
gate = struct('retained_image_real_lower', u_values, ...
  'taylor_poisson_tail', poisson_tail, 'pass', positive);
end

function [finite, tail, gate] = LOCAL_local_ewald_bound(h, eta, RX, RY, cfg)
R0 = h^2 * (RX^2 + RY^2);
B = cfg.local_cauchy_radius_factor * R0;
if B <= R0, B = R0 + 1.0; end
N = cfg.taylor_cutoff;
x = eta * B; xQ = eta * (1.0 + B);
rho = [x / (N + 2.0)^2, B * (N + 1.0) / (N + 2.0)^2, ...
  x / (N + 2.0)^2 * (1.0 + 1.0 / (N + 2.0)), ...
  xQ * (N + 1.0) / (N + 2.0)^2];
HN = sum(1.0 ./ (1.0:N + 1.0));
tauJ = x^(N + 1.0) / ...
  (exp(2.0 * gammaln(N + 2.0)) * (1.0 - rho(1)));
tauS = B^(N + 1.0) / ((N + 1.0) * ...
  exp(gammaln(N + 2.0)) * (1.0 - rho(2)));
tauD = HN * x^(N + 1.0) / ...
  (exp(2.0 * gammaln(N + 2.0)) * (1.0 - rho(3)));
tauQ = xQ^(N + 1.0) / ((1.0 + B) * (N + 1.0) * ...
  exp(gammaln(N + 2.0)) * (1.0 - rho(4)));
ceta = abs(log(eta) + 0.57721566490153286060 - 1i * pi);
tauC = (tauJ * (exp(B) - 1.0 + ceta) + ...
  exp(eta * B) * tauS + exp(B) * tauQ) / (4.0 * pi) + ...
  tauD / (2.0 * pi);
L = [tauC, tauC / (B - R0), 2.0 * tauC / (B - R0)^2];
tail = [L(1), 2.0 * h^2 * RX * L(2), ...
  2.0 * h^2 * RY * L(2), ...
  4.0 * h^4 * RX^2 * L(3) + 2.0 * h^2 * L(2), ...
  4.0 * h^4 * RX * RY * L(3), ...
  4.0 * h^4 * RY^2 * L(3) + 2.0 * h^2 * L(2)];
JN = sum((eta * B).^(0:N) ./ exp(2.0 * gammaln((0:N) + 1.0)));
SN = sum(B.^(1:N) ./ ((1:N) .* exp(gammaln((1:N) + 1.0))));
harmonic = cumsum(1.0 ./ (1.0:N));
DN = sum(harmonic .* (eta * B).^(1:N) ./ ...
  exp(2.0 * gammaln((1:N) + 1.0)));
QN = 0.0;
for n = 1:N
  inner = sum(exp(gammaln(n - (0:n - 1))) .* B.^(0:n - 1));
  QN = QN + eta^n / exp(2.0 * gammaln(n + 1.0)) * inner;
end
MN = JN * (SN + ceta) / (4.0 * pi) + ...
  exp(B) * QN / (4.0 * pi) + DN / (2.0 * pi);
F = [MN, MN / (B - R0), 2.0 * MN / (B - R0)^2];
finite = [F(1), 2.0 * h^2 * RX * F(2), ...
  2.0 * h^2 * RY * F(2), ...
  4.0 * h^4 * RX^2 * F(3) + 2.0 * h^2 * F(2), ...
  4.0 * h^4 * RX * RY * F(3), ...
  4.0 * h^4 * RY^2 * F(3) + 2.0 * h^2 * F(2)];
gate = struct('local_z_radius', R0, 'local_cauchy_radius', B, ...
  'ratios', rho, 'pass', B > R0 && all(rho < 1.0));
end

%% ==================== Separated wall action ====================
% Finite wall support is evaluated directly with its non-Wood multipliers.

function action = LOCAL_off_surface_action(z, geometry, cfg)
orders = (-256.0:255.0).';
beta_m = double(z.beta) + 2.0 * pi * orders / double(z.d);
gamma_m = sqrt(complex(double(z.khat)^2 - beta_m.^2));
flip = imag(gamma_m) < 0.0 | ...
  (imag(gamma_m) == 0.0 & real(gamma_m) < 0.0);
gamma_m(flip) = -gamma_m(flip);
if any(gamma_m == 0.0)
  error('I5Residual:OffSurfaceWood', 'A wall mode is exactly at Wood.');
end
x = geometry.position(:, 1); y = geometry.position(:, 2);
nx = geometry.normal(:, 1); ny = geometry.normal(:, 2);
psi = exp(1i * y * beta_m.') / sqrt(double(z.d));
left_phase = exp(1i * (x - double(z.X_L)) * gamma_m.');
right_phase = exp(1i * (double(z.X_R) - x) * gamma_m.');
multiplier = 1i ./ (2.0 * gamma_m);
SL = (psi .* left_phase) .* multiplier.';
SR = (psi .* right_phase) .* multiplier.';
dSL = SL .* (nx * (1i * gamma_m).' + ny * (1i * beta_m).');
dSR = SR .* (nx * (-1i * gamma_m).' + ny * (1i * beta_m).');
value_samples = SL * double(z.xi_left_unit_512) + ...
  SR * double(z.xi_right_unit_512);
normal_samples = dSL * double(z.xi_left_unit_512) + ...
  dSR * double(z.xi_right_unit_512);
[value_rows, mode_orders] = LOCAL_rows(value_samples, geometry, cfg);
[normal_rows, ~] = LOCAL_rows(normal_samples, geometry, cfg);
strip = geometry.certificate.parameter_strip_width;
imaginary = geometry.certificate.strip_imag_x_upper;
clearance = min(geometry.certificate.left_clearance_lower, ...
  geometry.certificate.right_clearance_lower);
speed_lower = geometry.certificate.speed_lower;
tangent = geometry.certificate.strip_tangent_x_upper;
A0 = 0.0; A1 = 0.0;
for index = 1:numel(orders)
  row_norm = abs(multiplier(index)) * ( ...
    norm(z.xi_left_unit_512(index, :), 2) + ...
    norm(z.xi_right_unit_512(index, :), 2)) / sqrt(double(z.d));
  if isreal(gamma_m(index))
    phi = exp((abs(gamma_m(index)) + abs(beta_m(index))) * imaginary);
  else
    phi = exp(-imag(gamma_m(index)) * clearance + ...
      abs(beta_m(index)) * imaginary);
  end
  normal_weight = (abs(gamma_m(index)) + abs(beta_m(index))) * ...
    tangent / speed_lower;
  A0 = A0 + row_norm * phi;
  A1 = A1 + row_norm * phi * normal_weight;
end
P = geometry.certificate.boundary_length;
xi = 2.0 * pi * mode_orders / P;
quad0 = 4.0 * pi * geometry.certificate.strip_speed_upper * A0 .* ...
  exp(abs(xi) * geometry.certificate.arclength_imag_upper) / ...
  (sqrt(P) * (exp(strip * numel(x)) - 1.0));
quad1 = 4.0 * pi * geometry.certificate.strip_speed_upper * A1 .* ...
  exp(abs(xi) * geometry.certificate.arclength_imag_upper) / ...
  (sqrt(P) * (exp(strip * numel(x)) - 1.0));
action = struct( ...
  'mode_orders', mode_orders, ...
  'value_rows', value_rows, ...
  'normal_rows', normal_rows, ...
  'value_row_error', quad0, ...
  'normal_row_error', quad1, ...
  'value_strip_upper', A0, ...
  'normal_strip_upper', A1, ...
  'gate', struct( ...
    'finite_support', true, ...
    'nonwood', all(gamma_m ~= 0.0), ...
    'positive_clearance', clearance > 0.0, ...
    'signed_arclength', geometry.certificate.signed_arclength_strip_lower > 0.0, ...
    'pass', clearance > 0.0 && all(gamma_m ~= 0.0)));
end

function [rows, mode_orders] = LOCAL_rows(samples, geometry, cfg)
mode_orders = (-cfg.retained_mode_cutoff:cfg.retained_mode_cutoff).';
P = geometry.certificate.boundary_length;
xi = 2.0 * pi * mode_orders / P;
phase = exp(-1i * xi * geometry.arclength_nodes.');
weights = (2.0 * pi / numel(geometry.parameter_nodes)) * geometry.speed;
rows = phase * (samples .* weights) / sqrt(P);
end

%% ==================== Artificial-wall value lifts ====================
% The finite wall data are combined with a shape-general curve-to-wall row.

function out = LOCAL_wall_value_action(z, geometry, density, pm, pp, cfg)
M = cfg.wall_lift_mode_cutoff;
orders = (-M:M).';
beta_m = double(z.beta) + 2.0 * pi * orders / double(z.d);
gamma_m = sqrt(complex(double(z.khat)^2 - beta_m.^2));
flip = imag(gamma_m) < 0.0 | ...
  (imag(gamma_m) == 0.0 & real(gamma_m) < 0.0);
gamma_m(flip) = -gamma_m(flip);
if any(gamma_m == 0.0) || ...
    2.0 * pi * (M + 1.0) / double(z.d) - abs(double(z.beta)) <= ...
      double(z.khat)
  error('I5Residual:WallLiftBranch', ...
    'The retained or first omitted wall-lift mode fails the non-Wood gate.');
end
[circle_left, error_left] = LOCAL_curve_to_wall_value( ...
  z, geometry, density, orders, beta_m, gamma_m, 'left');
[circle_right, error_right] = LOCAL_curve_to_wall_value( ...
  z, geometry, density, orders, beta_m, gamma_m, 'right');
xi_left = LOCAL_embed_wall_orders( ...
  z.xi_left_unit_512, z.wall_orders_512, orders);
xi_right = LOCAL_embed_wall_orders( ...
  z.xi_right_unit_512, z.wall_orders_512, orders);
wall_input = double(z.wall_input_unit_512);
input_left = LOCAL_embed_wall_orders( ...
  wall_input(1:512, :), z.wall_orders_512, orders);
input_right = LOCAL_embed_wall_orders( ...
  wall_input(513:end, :), z.wall_orders_512, orders);
s0 = 1i ./ (2.0 * gamma_m);
cell_phase = exp(1i * gamma_m * (double(z.X_R) - double(z.X_L)));
raw_left = s0 .* (xi_left + cell_phase .* xi_right) + circle_left;
raw_right = s0 .* (cell_phase .* xi_left + xi_right) + circle_right;
rows_left = input_left - raw_left;
rows_right = input_right - raw_right;
wall_weight = 6.0 / (5.0 * double(z.delta_w)) + ...
  13.0 * double(z.delta_w) / 35.0 * ...
  (beta_m.^2 + double(z.mu_h));
center_left = LOCAL_embed_wall_orders( ...
  z.center_left_value_mismatch, z.wall_orders_512, orders);
center_right = LOCAL_embed_wall_orders( ...
  z.center_right_value_mismatch, z.wall_orders_512, orders);

finite_squared = LOCAL_wall_defect_energy( ...
  center_left, zeros(size(error_left)), wall_weight, 1.0) + ...
  LOCAL_wall_defect_energy( ...
    center_right, zeros(size(error_right)), wall_weight, 1.0) + ...
  LOCAL_wall_defect_energy( ...
    rows_left, error_left, wall_weight, z.Gplus * z.cplus) + ...
  LOCAL_wall_defect_energy( ...
    rows_right, error_right, wall_weight, z.Gminus * z.cminus);
plus_state = z.cplus;
minus_state = z.cminus;
for cell_index = 0:cfg.cell_cutoff - 1.0
  finite_squared = finite_squared + ...
    LOCAL_wall_defect_energy(rows_right, error_right, wall_weight, ...
      z.Gplus * plus_state) + ...
    LOCAL_wall_defect_energy(rows_left, error_left, wall_weight, ...
      z.Gplus * z.Pplus * plus_state) + ...
    LOCAL_wall_defect_energy(rows_left, error_left, wall_weight, ...
      z.Gminus * minus_state) + ...
    LOCAL_wall_defect_energy(rows_right, error_right, wall_weight, ...
      z.Gminus * z.Pminus * minus_state);
  plus_state = z.Pplus * plus_state;
  minus_state = z.Pminus * minus_state;
end
omega_plus = LOCAL_wall_row_omega( ...
  rows_right, error_right, z.Gplus, wall_weight) + ...
  LOCAL_wall_row_omega( ...
    rows_left, error_left, z.Gplus * z.Pplus, wall_weight);
omega_minus = LOCAL_wall_row_omega( ...
  rows_left, error_left, z.Gminus, wall_weight) + ...
  LOCAL_wall_row_omega( ...
    rows_right, error_right, z.Gminus * z.Pminus, wall_weight);
low_tail_squared = omega_plus * pp.sum_power_squared_upper * ...
  norm(plus_state)^2 + omega_minus * pm.sum_power_squared_upper * ...
  norm(minus_state)^2;
high_plus = LOCAL_wall_lift_high_squared( ...
  z, geometry, density, cfg, z.Gplus, 'right') + ...
  LOCAL_wall_lift_high_squared( ...
    z, geometry, density, cfg, z.Gplus * z.Pplus, 'left');
high_minus = LOCAL_wall_lift_high_squared( ...
  z, geometry, density, cfg, z.Gminus, 'left') + ...
  LOCAL_wall_lift_high_squared( ...
    z, geometry, density, cfg, z.Gminus * z.Pminus, 'right');
high_singleton = LOCAL_wall_lift_high_squared( ...
  z, geometry, density, cfg, z.Gplus * z.cplus, 'left') + ...
  LOCAL_wall_lift_high_squared( ...
    z, geometry, density, cfg, z.Gminus * z.cminus, 'right');
high_tail_squared = high_plus * pp.sum_power_squared_upper * ...
  norm(z.cplus)^2 + high_minus * pm.sum_power_squared_upper * ...
  norm(z.cminus)^2 + high_singleton;
tail_squared = low_tail_squared + high_tail_squared;
out = struct( ...
  'mode_orders', orders, ...
  'left_rows', rows_left, 'right_rows', rows_right, ...
  'left_row_error', error_left, 'right_row_error', error_right, ...
  'wall_lift_weights', wall_weight, ...
  'finite_squared', finite_squared, ...
  'low_mode_propagation_tail_squared', low_tail_squared, ...
  'high_mode_tail_squared', high_tail_squared, ...
  'tail_squared', tail_squared, ...
  'energy_upper', finite_squared + tail_squared, ...
  'gate', struct( ...
    'nonwood', all(gamma_m ~= 0.0), ...
    'finite_support_embedded', true, ...
    'positive_distance', min([geometry.certificate.left_clearance_lower, ...
      geometry.certificate.right_clearance_lower]) > 0.0, ...
    'tail_budget_pass', 2.0 * sqrt(tail_squared) <= ...
      cfg.lifting_tail_tolerance, ...
    'pass', all(isfinite([finite_squared, tail_squared]))));
end

function [value_rows, row_error] = LOCAL_curve_to_wall_value( ...
    z, geometry, density, orders, beta_m, gamma_m, side)
if strcmp(side, 'left')
  side_sign = -1.0;
  wall_x = double(z.X_L);
  clearance = geometry.certificate.left_clearance_lower;
elseif strcmp(side, 'right')
  side_sign = 1.0;
  wall_x = double(z.X_R);
  clearance = geometry.certificate.right_clearance_lower;
else
  error('I5Residual:WallLiftSide', 'Wall side must be left or right.');
end
travel = side_sign * (wall_x - geometry.position(:, 1));
if any(travel <= 0.0)
  error('I5Residual:WallLiftDistance', 'The curve touches a wall.');
end
phase = exp(1i * travel * gamma_m.' - ...
  1i * geometry.position(:, 2) * beta_m.');
derivative_measure = 1i * (side_sign * geometry.derivative(:, 2) * ...
  gamma_m.' - geometry.derivative(:, 1) * beta_m.');
common = 1i ./ (2.0 * gamma_m * sqrt(double(z.d)));
integrand_action = -(phase .* derivative_measure).' * density.tau_values + ...
  phase.' * (geometry.speed .* density.sigma_values);
value_rows = (2.0 * pi / numel(geometry.parameter_nodes)) * ...
  (common .* integrand_action);
a = geometry.certificate.parameter_strip_width;
growth = exp(abs(density.orders) * a);
D_tau = sum(vecnorm(density.tau_coeff_map, 2, 2) .* growth);
D_sigma = sum(vecnorm(density.sigma_coeff_map, 2, 2) .* growth);
TX = geometry.certificate.strip_tangent_x_upper;
TY = geometry.certificate.strip_tangent_y_upper;
V = geometry.certificate.strip_speed_upper;
IX = geometry.certificate.strip_imag_x_upper;
IY = geometry.certificate.strip_imag_y_upper;
row_error = zeros(size(orders));
for index = 1:numel(orders)
  if isreal(gamma_m(index))
    phi = exp(abs(gamma_m(index)) * IX + abs(beta_m(index)) * IY);
  else
    phi = exp(-imag(gamma_m(index)) * clearance + ...
      abs(beta_m(index)) * IY);
  end
  integrand_upper = phi / ...
    (2.0 * abs(gamma_m(index)) * sqrt(double(z.d))) * ...
    ((abs(gamma_m(index)) * TY + abs(beta_m(index)) * TX) * ...
      D_tau + V * D_sigma);
  row_error(index) = 4.0 * pi * integrand_upper / ...
    expm1(a * numel(geometry.parameter_nodes));
end
end

function energy = LOCAL_wall_defect_energy(rows, errors, weight, state)
if isscalar(state)
  center = rows;
  radius = errors * abs(state);
else
  center = rows * state;
  radius = errors * norm(state);
end
energy = sum((abs(center) + radius).^2 .* weight);
end

function omega = LOCAL_wall_row_omega(rows, errors, state_map, weight)
row_norm = vecnorm(rows * state_map, 2, 2) + errors * norm(state_map);
omega = sum(row_norm.^2 .* weight);
end

function squared = LOCAL_wall_lift_high_squared( ...
    z, geometry, density, cfg, state_map, side)
if strcmp(side, 'left')
  positive_distance = geometry.certificate.left_clearance_lower;
else
  positive_distance = geometry.certificate.right_clearance_lower;
end
density_factor = 2.0 * pi * geometry.certificate.speed_upper;
A_tau = density_factor * norm(density.tau_coeff_map * state_map, 'fro');
A_sigma = density_factor * norm(density.sigma_coeff_map * state_map, 'fro');
q0 = 2.0 * pi / double(z.d);
N = cfg.wall_lift_mode_cutoff + 1.0;
tN = q0 * N - abs(double(z.beta));
kappaN = sqrt(tN^2 - double(z.khat)^2);
r = exp(-2.0 * positive_distance * q0);
S0 = r^N / (1.0 - r);
S1 = r^N * (N / (1.0 - r) + r / (1.0 - r)^2);
S2 = r^N * (N^2 / (1.0 - r) + ...
  2.0 * N * r / (1.0 - r)^2 + ...
  r * (1.0 + r) / (1.0 - r)^3);
HN = (1.0 + tN / kappaN) * A_tau + A_sigma / kappaN;
Cw0 = 6.0 / (5.0 * double(z.delta_w)) + ...
  13.0 * double(z.delta_w) * double(z.mu_h) / 35.0;
Cw2 = 13.0 * double(z.delta_w) / 35.0;
squared = exp(2.0 * positive_distance * ...
  (double(z.khat) + abs(double(z.beta)))) * HN^2 / ...
  (2.0 * double(z.d)) * (Cw0 * S0 + Cw2 * ...
  (q0^2 * S2 + 2.0 * q0 * abs(double(z.beta)) * S1 + ...
    double(z.beta)^2 * S0));
end

function embedded = LOCAL_embed_wall_orders(values, source_orders, target_orders)
[present, indices] = ismember(double(source_orders(:)), target_orders);
if ~all(present) || size(values, 1) ~= numel(source_orders)
  error('I5Residual:WallLiftEmbedding', 'A finite wall order is absent.');
end
embedded = complex(zeros(numel(target_orders), size(values, 2)));
embedded(indices, :) = double(values);
end

function rows = LOCAL_combined_rows( ...
    geometry, local, regular, off_surface, cfg)
if ~isequal(local.mode_orders, regular.mode_orders, off_surface.mode_orders)
  error('I5Residual:ModeAssociation', 'The retained mode grids differ.');
end
rows = struct( ...
  'mode_orders', local.mode_orders, ...
  'value', local.value_rows + regular.value_rows + off_surface.value_rows, ...
  'normal', local.normal_rows - regular.normal_rows - off_surface.normal_rows, ...
  'value_error', local.value_row_error + regular.value_row_error + ...
    off_surface.value_row_error, ...
  'normal_error', local.normal_row_error + regular.normal_row_error + ...
    off_surface.normal_row_error, ...
  'component_triangle_before_propagation', true, ...
  'boundary_length', geometry.certificate.boundary_length, ...
  'retained_mode_cutoff', cfg.retained_mode_cutoff);
end

%% ==================== Trace, lifting, and propagation ====================
% The four singleton/cell/mode partitions are kept disjoint.

function weights = LOCAL_weights(z, geometry, cfg)
ell = (-cfg.retained_mode_cutoff:cfg.retained_mode_cutoff).';
P = geometry.certificate.boundary_length;
xi = 2.0 * pi * ell / P;
hminus = double(z.delta_c); hplus = double(z.delta_c);
kappa = geometry.certificate.curvature_upper;
theta_minus = 1.0 - hminus * kappa;
theta_plus = 1.0 - hplus * kappa;
Theta_minus = 1.0 + hminus * kappa;
Theta_plus = 1.0 + hplus * kappa;
lambda_minus = sqrt(double(z.mu_h) * double(z.rho_disk) + ...
  xi.^2 / (theta_minus * Theta_minus));
lambda_plus = sqrt(double(z.mu_h) + ...
  xi.^2 / (theta_plus * Theta_plus));
trace = theta_minus * lambda_minus .* tanh(hminus * lambda_minus) + ...
  theta_plus * lambda_plus .* tanh(hplus * lambda_plus);
I0 = 13.0 / 35.0; I1 = 6.0 / 5.0;
cminus = 0.5; cplus = -0.5;
C0 = abs(cminus)^2 * Theta_minus * ...
  (I1 / hminus + double(z.mu_h) * double(z.rho_disk) * hminus * I0) + ...
  abs(cplus)^2 * Theta_plus * ...
  (I1 / hplus + double(z.mu_h) * hplus * I0);
C1 = abs(cminus)^2 * hminus * I0 / theta_minus + ...
  abs(cplus)^2 * hplus * I0 / theta_plus;
lifting = C0 + C1 * xi.^2;
weights = struct( ...
  'mode_orders', ell, ...
  'trace', trace, ...
  'lifting', lifting, ...
  'tubular_C0', C0, ...
  'tubular_C1', C1, ...
  'theta_minus', theta_minus, ...
  'theta_plus', theta_plus, ...
  'Theta_minus', Theta_minus, ...
  'Theta_plus', Theta_plus, ...
  'collar_gate', min([theta_minus, theta_plus, trace.']) > 0.0);
if ~weights.collar_gate
  error('I5Residual:CollarGate', 'A material collar weight is nonpositive.');
end
end

function material = LOCAL_material_assembly( ...
    z, geometry, rows, weights, local, regular, off_surface, pm, pp, cfg)
[finite_squared, low_tail_squared] = LOCAL_finite_and_low_tail( ...
  z, rows.normal, rows.normal_error, weights.trace, pm, pp, cfg);
[local_high, analytic_high, combined_high] = LOCAL_material_high_constants( ...
  z, geometry, weights, local, regular, off_surface, cfg);
fallback_high = (sqrt(local_high) + sqrt(analytic_high))^2;
high_unit = min(fallback_high, combined_high);
state_sum = norm(z.q_center)^2 + ...
  norm(z.Gminus)^2 * pm.sum_power_squared_upper * norm(z.cminus)^2 + ...
  norm(z.Gplus)^2 * pp.sum_power_squared_upper * norm(z.cplus)^2;
high_tail_squared = high_unit * state_sum;
tail_squared = low_tail_squared + high_tail_squared;
material = struct( ...
  'finite_squared', finite_squared, ...
  'low_mode_propagation_tail_squared', low_tail_squared, ...
  'high_mode_tail_squared', high_tail_squared, ...
  'high_mode_unit_fallback_squared', fallback_high, ...
  'high_mode_unit_combined_strip_squared', combined_high, ...
  'high_mode_unit_selected_squared', high_unit, ...
  'high_mode_selected_route', ...
    LOCAL_selected_route(fallback_high, combined_high), ...
  'tail_squared', tail_squared, ...
  'bound', sqrt(finite_squared + tail_squared), ...
  'tail_budget_pass', sqrt(tail_squared) <= cfg.material_tail_tolerance, ...
  'stopping_tolerance', cfg.material_tail_tolerance);
end

function lifting = LOCAL_lifting_assembly( ...
    z, geometry, rows, weights, local, regular, off_surface, pm, pp, cfg)
[finite_squared, low_tail_squared] = LOCAL_finite_and_low_tail( ...
  z, rows.value, rows.value_error, weights.lifting, pm, pp, cfg);
[local_high, analytic_high, combined_high] = LOCAL_lifting_high_constants( ...
  z, geometry, weights, local, regular, off_surface, cfg);
fallback_high = (sqrt(local_high) + sqrt(analytic_high))^2;
high_unit = min(fallback_high, combined_high);
state_sum = norm(z.q_center)^2 + ...
  norm(z.Gminus)^2 * pm.sum_power_squared_upper * norm(z.cminus)^2 + ...
  norm(z.Gplus)^2 * pp.sum_power_squared_upper * norm(z.cplus)^2;
high_tail_squared = high_unit * state_sum;
tail_squared = low_tail_squared + high_tail_squared;
lifting = struct( ...
  'finite_squared', finite_squared, ...
  'low_mode_propagation_tail_squared', low_tail_squared, ...
  'high_mode_tail_squared', high_tail_squared, ...
  'high_mode_unit_fallback_squared', fallback_high, ...
  'high_mode_unit_combined_strip_squared', combined_high, ...
  'high_mode_unit_selected_squared', high_unit, ...
  'high_mode_selected_route', ...
    LOCAL_selected_route(fallback_high, combined_high), ...
  'tail_squared', tail_squared, ...
  'material_collar_energy_upper', finite_squared + tail_squared, ...
  'bound', 2.0 * sqrt(finite_squared + tail_squared), ...
  'tail_budget_pass', 2.0 * sqrt(tail_squared) <= cfg.lifting_tail_tolerance, ...
  'stopping_tolerance', cfg.lifting_tail_tolerance, ...
  'artificial_wall_lifts_included', false);
end

function lifting = LOCAL_total_lifting(material_lifting, wall_lifting, cfg)
finite_squared = material_lifting.finite_squared + wall_lifting.finite_squared;
tail_squared = material_lifting.tail_squared + wall_lifting.tail_squared;
energy_upper = finite_squared + tail_squared;
lifting = struct( ...
  'material_interface', material_lifting, ...
  'artificial_walls', wall_lifting, ...
  'finite_squared', finite_squared, ...
  'tail_squared', tail_squared, ...
  'energy_upper', energy_upper, ...
  'bound', 2.0 * sqrt(energy_upper), ...
  'tail_budget_pass', 2.0 * sqrt(tail_squared) <= ...
    cfg.lifting_tail_tolerance, ...
  'stopping_tolerance', cfg.lifting_tail_tolerance, ...
  'artificial_wall_lifts_included', true);
end

function [finite_squared, tail_squared] = LOCAL_finite_and_low_tail( ...
    z, unit_rows, unit_error, mode_weight, pm, pp, cfg)
finite_squared = LOCAL_state_energy( ...
  unit_rows, unit_error, mode_weight, z.q_center);
side = {struct('G', z.Gminus, 'P', z.Pminus, 'c', z.cminus, 'cap', pm), ...
  struct('G', z.Gplus, 'P', z.Pplus, 'c', z.cplus, 'cap', pp)};
tail_squared = 0.0;
for side_index = 1:2
  data = side{side_index};
  state = data.c;
  for cell_index = 0:cfg.cell_cutoff - 1.0
    finite_squared = finite_squared + LOCAL_state_energy( ...
      unit_rows, unit_error, mode_weight, data.G * state);
    state = data.P * state;
  end
  row_operator = vecnorm(unit_rows * data.G, 2, 2) + ...
    unit_error * norm(data.G);
  omega = sum(row_operator.^2 ./ mode_weight);
  tail_squared = tail_squared + omega * ...
    data.cap.sum_power_squared_upper * norm(state)^2;
end
end

function energy = LOCAL_state_energy(rows, errors, weight, state)
center = rows * state;
radius = errors * norm(state);
energy = sum((abs(center) + radius).^2 ./ weight);
end

function [local_tail, analytic_tail, combined_tail] = ...
    LOCAL_material_high_constants( ...
    z, geometry, weights, local, regular, off_surface, cfg)
N = cfg.retained_mode_cutoff + 1.0;
P = geometry.certificate.boundary_length;
xiN = 2.0 * pi * N / P;
dN = weights.theta_minus * tanh(double(z.delta_c) * xiN) + ...
  weights.theta_plus * tanh(double(z.delta_c) * xiN);
local_tail = local.normal_l2_upper^2 / (dN * xiN);
a_s = geometry.certificate.arclength_strip_width;
A = regular.normal_strip_upper + off_surface.normal_strip_upper;
r = exp(-4.0 * pi * a_s / P);
cminus = sqrt(weights.theta_minus / weights.Theta_minus);
cplus = sqrt(weights.theta_plus / weights.Theta_plus);
dminus = double(z.delta_c) / ...
  sqrt(weights.theta_minus * weights.Theta_minus);
dplus = double(z.delta_c) / ...
  sqrt(weights.theta_plus * weights.Theta_plus);
DN = cminus * tanh(xiN * dminus) + cplus * tanh(xiN * dplus);
analytic_tail = P^2 * A^2 / (pi * DN) * r^N / (N * (1.0 - r));
combined_A = local.normal_strip_upper + A;
combined_tail = P^2 * combined_A^2 / (pi * DN) * ...
  r^N / (N * (1.0 - r));
end

function [local_tail, analytic_tail, combined_tail] = ...
    LOCAL_lifting_high_constants( ...
    ~, geometry, weights, local, regular, off_surface, cfg)
N = cfg.retained_mode_cutoff + 1.0;
P = geometry.certificate.boundary_length;
xiN = 2.0 * pi * N / P;
local_tail = (weights.tubular_C0 / xiN^4 + ...
  weights.tubular_C1 / xiN^2) * local.value_second_l2_upper^2;
a_s = geometry.certificate.arclength_strip_width;
A = regular.value_strip_upper + off_surface.value_strip_upper;
r = exp(-4.0 * pi * a_s / P);
S0 = r^N / (1.0 - r);
S2 = r^N * (N^2 / (1.0 - r) + ...
  2.0 * N * r / (1.0 - r)^2 + r * (1.0 + r) / (1.0 - r)^3);
analytic_tail = 2.0 * P * A^2 * ...
  (weights.tubular_C0 * S0 + ...
  weights.tubular_C1 * (2.0 * pi / P)^2 * S2);
combined_A = local.value_strip_upper + A;
combined_tail = 2.0 * P * combined_A^2 * ...
  (weights.tubular_C0 * S0 + ...
  weights.tubular_C1 * (2.0 * pi / P)^2 * S2);
end

function route = LOCAL_selected_route(fallback, combined)
if combined <= fallback
  route = 'combined_analytic_strip';
else
  route = 'P20_P29_Sobolev_plus_regular_analytic';
end
end

function out = LOCAL_block_certificate(P, block_length)
power = eye(size(P));
prefix = 0.0;
for j = 0:block_length - 1.0
  prefix = prefix + norm(power)^2;
  power = P * power;
end
block_norm = norm(power);
out = struct( ...
  'block_length', block_length, ...
  'block_norm', block_norm, ...
  'contraction_pass', block_norm < 1.0, ...
  'sum_power_squared_upper', prefix / (1.0 - block_norm^2));
end

function prediction = LOCAL_prediction(z, ordinary_anchor, majorant)
if ~isfield(ordinary_anchor, 'N_tilde') || ordinary_anchor.N_tilde <= 0.0
  error('I5Residual:PredictionInput', 'ordinary_anchor.N_tilde is unavailable.');
end
q_pred = majorant / sqrt(double(ordinary_anchor.N_tilde));
gate = q_pred < 1.0;
if gate
  lambda_lower = (double(z.mu_h) - q_pred * double(z.gamma)) / ...
    (1.0 + q_pred);
  lambda_upper = (double(z.mu_h) + q_pred * double(z.gamma)) / ...
    (1.0 - q_pred);
  if lambda_lower > 0.0
    k_lower = sqrt(lambda_lower);
    k_upper = sqrt(lambda_upper);
  else
    k_lower = NaN; k_upper = NaN;
  end
  k_center = double(z.khat) / sqrt(1.0 - q_pred^2);
  k_half_width = double(z.khat) * q_pred / sqrt(1.0 - q_pred^2);
  lambda_center = 0.5 * (lambda_lower + lambda_upper);
  lambda_half_width = 0.5 * (lambda_upper - lambda_lower);
else
  lambda_lower = NaN; lambda_upper = NaN;
  k_lower = NaN; k_upper = NaN; k_center = NaN; k_half_width = NaN;
  lambda_center = NaN; lambda_half_width = NaN;
end
prediction = struct( ...
  'q_pred', q_pred, ...
  'q_less_than_one_gate', gate, ...
  'lambda_lower', lambda_lower, ...
  'lambda_upper', lambda_upper, ...
  'lambda_center', lambda_center, ...
  'lambda_half_width', lambda_half_width, ...
  'lambda_full_width', 2.0 * lambda_half_width, ...
  'k_lower', k_lower, ...
  'k_upper', k_upper, ...
  'k_center', k_center, ...
  'k_half_width', k_half_width, ...
  'k_full_width', 2.0 * k_half_width, ...
  'complete_residual_numerator_used', true, ...
  'claim_is_conditional_display_only', true);
end
