function result = wall_tail_a1(artifact_path, output_path)
%WALL_TAIL_A1 Evaluate the I5 artificial-wall finite part and strict tails.
% Purpose:
%   Instantiate the B_{Gamma_pm}-only theorem in s-wall-tail.md from one
%   frozen I3
%   certificate without resolving any eigenpair, BIE density, QZ data, or
%   propagation matrix.
% Input:
%   artifact_path - Explicit path to fbie-a1-certificate.mat.
%   output_path   - Explicit path for the result MAT file.
% Output:
%   result        - Ordinary floating-point finite/tail assembly and audits.
% Main algorithm:
%   Transform the frozen circle density once with its source-node FFT,
%   evaluate finite circle-to-wall Rayleigh rows by periodic trapezoidal
%   quadrature, add exact finite flat-wall modal rows, attach analytic strip
%   remainders, and close the cell index with full-matrix block powers.
% Based on:
%   research/projects/eig-apost/phase3-analysis/residual-bound/s-wall-tail.md
%   and research/projects/eig-apost/implementation/i5/design-5-1.md.
% Main changes:
%   No v4 MFS table, interpolation factor, stored normal_factor, or empirical
%   resolution tail enters the reported finite/tail assembly.
% Numerical goal:
%   Produce a traceable artificial-wall-only ordinary evaluation.  Since
%   floating-point
%   rounding is not enclosed, every output remains non-certified.

timer = tic;
cfg = LOCAL_config();
[artifact_path, output_path] = LOCAL_paths(artifact_path, output_path);
staged = LOCAL_load_artifact(artifact_path);
z = staged.certificate;
z.d = double(z.d);
z.M = double(z.M);
z.K = double(z.K);
z.L = double(z.L);
raw_maps = staged.raw_maps;
LOCAL_validate_schema(z, raw_maps, output_path, cfg);

% --- stage 1: branch, support, and frozen density audits ---
modal = LOCAL_modal_data(z, cfg);
density = LOCAL_density_data(z);

% --- stage 2: finite coefficient rows and analytic remainders ---
circle_flux = LOCAL_circle_flux_rows(z, density, modal, cfg);
rows = LOCAL_wall_rows(z, density, modal, circle_flux, cfg);
side_index_audit = LOCAL_side_index_audit( ...
  z, raw_maps, modal, rows, circle_flux, cfg);
if ~modal.audit.pass || ~density.audit.pass || ...
    ~side_index_audit.structural_pass
  error('I5WallTail:Audit', ...
    ['Audit failed: branch=%d density=%d side=%d; branchDef=%.3e ', ...
    'transverseDef=%.3e tauParseval=%.3e slParseval=%.3e ', ...
    'Gp=%.3e Gm=%.3e Jp=%.3e Jm=%.3e dxL=%.3e dxR=%.3e.'], ...
    modal.audit.pass, density.audit.pass, ...
    side_index_audit.structural_pass, ...
    modal.audit.stored_branch_relative_defect, ...
    modal.audit.stored_transverse_wavenumber_relative_defect, ...
    density.audit.tau_parseval_relative_defect, ...
    density.audit.single_layer_density_parseval_relative_defect, ...
    side_index_audit.G_plus_relative_defect, ...
    side_index_audit.G_minus_relative_defect, ...
    side_index_audit.stored_J_plus_association_defect, ...
    side_index_audit.stored_J_minus_association_defect, ...
    side_index_audit.center_dx_left_relative_defect, ...
    side_index_audit.center_dx_right_relative_defect);
end

% --- stage 3: full-matrix propagation and positive-distance tails ---
propagation_minus = LOCAL_block_certificate(z.Pminus, cfg.block_length);
propagation_plus = LOCAL_block_certificate(z.Pplus, cfg.block_length);
if ~propagation_minus.contraction_pass || ...
    ~propagation_plus.contraction_pass
  error('I5WallTail:BlockPower', ...
    'An ordinary full-matrix block-power contraction is unavailable.');
end
density_constants = LOCAL_density_constants(z, density);
high_mode = LOCAL_high_mode_constants(z, density_constants, modal, cfg);

% --- stage 4: disjoint finite and omitted pieces ---
finite = LOCAL_finite_part(z, modal, rows, cfg);
tail = LOCAL_tail_part(z, modal, rows, finite, high_mode, ...
  propagation_minus, propagation_plus);
coefficient_enclosures = struct( ...
  'wall_orders', modal.wall_orders, ...
  'wall_weights', modal.wall_weights, ...
  'ell_plus_tilde', rows.ell_plus_tilde, ...
  'ell_plus_error', rows.ell_plus_error, ...
  'ell_minus_tilde', rows.ell_minus_tilde, ...
  'ell_minus_error', rows.ell_minus_error, ...
  'singleton_plus_tilde', rows.singleton_plus_tilde, ...
  'singleton_plus_error', rows.singleton_plus_error, ...
  'singleton_minus_tilde', rows.singleton_minus_tilde, ...
  'singleton_minus_error', rows.singleton_minus_error, ...
  'strip_remainder_records', rows.remainder_records, ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
quadratic_bound = sqrt(finite.finite_squared + tail.tail_squared);
triangle_bound = sqrt(finite.finite_squared) + sqrt(tail.tail_squared);
if any(~isfinite([quadratic_bound, triangle_bound])) || ...
    any([quadratic_bound, triangle_bound] < 0.0)
  error('I5WallTail:Assembly', ...
    'The artificial-wall finite/tail assembly is nonfinite or negative.');
end

workspace = whos;
workspace_proxy_mib = sum([workspace.bytes]) / 2.0^20;
result = struct( ...
  'status', 'COMPLETE', ...
  'claim_scope', 'B_GAMMA_PM_ONLY', ...
  'certification_label', cfg.roundoff_label, ...
  'roundoff_excluded', true, ...
  'reliability_certified', false, ...
  'quadratic_bound', quadratic_bound, ...
  'triangle_bound', triangle_bound, ...
  'finite', finite, ...
  'tail', tail, ...
  'coefficient_enclosures', coefficient_enclosures, ...
  'config', cfg, ...
  'branch_audit', modal.audit, ...
  'density_audit', density.audit, ...
  'side_index_audit', side_index_audit, ...
  'propagation_minus', propagation_minus, ...
  'propagation_plus', propagation_plus, ...
  'density_constants', density_constants, ...
  'high_mode', high_mode, ...
  'evaluation', circle_flux.audit, ...
  'theorem_gate', struct( ...
    'finite_bundle_ordinary_complete', true, ...
    'outward_rounding_gate_closed', false, ...
    'reported_number_reliable', false), ...
  'provenance', struct( ...
    'artifact_path', artifact_path, ...
    'artifact_variable', 'staged', ...
    'source_density_transform', ...
      'fftshift(fft(native_samples))/256; no midpoint phase', ...
    'stored_v4_normal_factor_used', false, ...
    'stored_raw_maps_used_in_bound', false, ...
    'eigenpair_solves', 0.0, ...
    'bie_density_solves', 0.0, ...
    'qz_decompositions', 0.0, ...
    'propagation_matrix_solves', 0.0), ...
  'resource', struct( ...
    'elapsed_seconds_before_save', toc(timer), ...
    'workspace_proxy_mib_before_save', workspace_proxy_mib));
save(output_path, 'result', '-v7.3');
end

%% ==================== Fixed experiment contract ====================
% These constants instantiate design-5-1 and are not adaptive fit controls.

function cfg = LOCAL_config()
cfg = struct( ...
  'mode_cutoff', 256.0, ...
  'cell_cutoff', 32.0, ...
  'block_length', 32.0, ...
  'quadrature_nodes', 4096.0, ...
  'circle_center_x', 0.0, ...
  'circle_center_y', 0.0, ...
  'trace_half_width', 0.5, ...
  'roundoff_label', 'NON_CERTIFIED_ROUNDOFF_EXCLUDED');
end

function [artifact_path, output_path] = LOCAL_paths( ...
    artifact_path, output_path)
if isstring(artifact_path) && isscalar(artifact_path)
  artifact_path = char(artifact_path);
end
if isstring(output_path) && isscalar(output_path)
  output_path = char(output_path);
end
if ~ischar(artifact_path) || isempty(artifact_path) || ...
    ~isfile(artifact_path)
  error('I5WallTail:ArtifactPath', ...
    'artifact_path must name an existing MAT file.');
end
if ~ischar(output_path) || isempty(output_path)
  error('I5WallTail:OutputPath', ...
    'output_path must be an explicit nonempty path.');
end
output_directory = fileparts(output_path);
if ~isempty(output_directory) && ~isfolder(output_directory)
  error('I5WallTail:OutputDirectory', ...
    'The explicit output directory does not exist.');
end
end

function staged = LOCAL_load_artifact(artifact_path)
loaded = load(artifact_path, 'staged');
if ~isfield(loaded, 'staged') || ~isstruct(loaded.staged)
  error('I5WallTail:ArtifactSchema', ...
    'The MAT file does not contain the staged structure.');
end
staged = loaded.staged;
if ~all(isfield(staged, {'certificate', 'raw_maps'}))
  error('I5WallTail:ArtifactSchema', ...
    'The staged certificate or raw_maps structure is missing.');
end
end

function LOCAL_validate_schema(z, raw_maps, output_path, cfg)
required = {'khat', 'gamma', 'mu_h', 'beta', 'd', 'R', 'X_L', ...
  'X_R', 'L', 'M', 'K', 'eta_unit_256', 'xi_left_unit_512', ...
  'xi_right_unit_512', 'wall_orders_512', 'q_center', 'Dplus', ...
  'Dminus', 'Gplus', 'Gminus', 'Pplus', 'Pminus', 'cplus', ...
  'cminus', 'branch_port', 'center_wall_jumps', ...
  'density_coordinate', 'global_normal_label'};
if ~all(isfield(z, required))
  error('I5WallTail:ArtifactSchema', ...
    'The frozen certificate is missing a required field.');
end
raw_required = {'QLplus', 'QRplus', 'QLminus', 'QRminus', ...
  'Jplus', 'Jminus', 'wall_flux_left_unit_512', ...
  'wall_flux_right_unit_512'};
if ~all(isfield(raw_maps, raw_required))
  error('I5WallTail:ArtifactSchema', ...
    'The frozen raw map bundle is missing an audit field.');
end
center_required = {'center_left_global_dx', 'center_right_global_dx', ...
  'left_coefficients', 'right_coefficients'};
if ~all(isfield(z.center_wall_jumps, center_required))
  error('I5WallTail:ArtifactSchema', ...
    'The frozen center/first wall record is incomplete.');
end
K = double(z.K);
shape_pass = isequal(size(z.eta_unit_256), [512, 2 * K]) && ...
  isequal(size(z.xi_left_unit_512), [512, 2 * K]) && ...
  isequal(size(z.xi_right_unit_512), [512, 2 * K]) && ...
  isequal(size(z.Gplus), [2 * K, K]) && ...
  isequal(size(z.Gminus), [2 * K, K]) && ...
  isequal(size(z.Pplus), [K, K]) && ...
  isequal(size(z.Pminus), [K, K]) && ...
  isequal(size(z.cplus), [K, 1]) && ...
  isequal(size(z.cminus), [K, 1]) && ...
  isequal(size(z.q_center), [2 * K, 1]);
if ~shape_pass
  error('I5WallTail:ArtifactShape', ...
    'A frozen state or density map has the wrong shape.');
end
if double(z.M) > cfg.mode_cutoff || cfg.mode_cutoff < 256.0 || ...
    cfg.cell_cutoff < 0.0 || cfg.block_length < 1.0 || ...
    mod(cfg.quadrature_nodes, 2.0) ~= 0.0
  error('I5WallTail:Configuration', ...
    'The fixed modal, cell, block, or quadrature configuration is invalid.');
end
if z.X_L >= -z.R || z.X_R <= z.R || ...
    z.X_R - z.X_L ~= z.L || z.L ~= 1.0
  error('I5WallTail:Geometry', ...
    'The frozen origin-centered unit-cell geometry is unavailable.');
end
if z.gamma ~= z.mu_h || z.gamma <= 0.0 || z.khat <= 0.0 || ...
    z.d <= 0.0 || z.R <= 0.0
  error('I5WallTail:PhysicalScalars', ...
    'A frozen physical scalar or shifted norm parameter is invalid.');
end
if exist(output_path, 'dir') == 7
  error('I5WallTail:OutputPath', ...
    'output_path names a directory rather than a MAT file.');
end
end

%% ==================== Branch and density coordinates ====================
% The Rayleigh branch and source-density FFT are reconstructed from frozen data.

function modal = LOCAL_modal_data(z, cfg)
k_outer = double(z.khat);
mu_shift = double(z.gamma);
beta_bloch = double(z.beta);
period_y = double(z.d);
wall_orders = (-cfg.mode_cutoff:cfg.mode_cutoff).';
transverse_wavenumber = beta_bloch + 2.0 * pi * wall_orders / period_y;
branch_radicand = k_outer^2 - transverse_wavenumber.^2;
rayleigh_wavenumber = sqrt(complex(branch_radicand));
flip = imag(rayleigh_wavenumber) < 0.0 | ...
  (imag(rayleigh_wavenumber) == 0.0 & real(rayleigh_wavenumber) < 0.0);
rayleigh_wavenumber(flip) = -rayleigh_wavenumber(flip);
exact_wood = any(branch_radicand == 0.0);
propagating = branch_radicand > 0.0;
evanescent = branch_radicand < 0.0;
outgoing_pass = all(real(rayleigh_wavenumber(propagating)) > 0.0) && ...
  all(imag(rayleigh_wavenumber(evanescent)) > 0.0);

stored_orders = (-double(z.M):double(z.M)).';
[present, retained_indices] = ismember(stored_orders, wall_orders);
if ~all(present)
  error('I5WallTail:BranchEmbedding', ...
    'A frozen branch order is absent from the finite wall range.');
end
stored_gamma = z.branch_port.gamma_m(:);
stored_alpha = z.branch_port.beta_m(:);
branch_defect = LOCAL_relative_difference( ...
  rayleigh_wavenumber(retained_indices), stored_gamma);
transverse_defect = LOCAL_relative_difference( ...
  transverse_wavenumber(retained_indices), stored_alpha);
ordinary_identity_tolerance = 4096.0 * eps;
stored_branch_pass = branch_defect <= ordinary_identity_tolerance && ...
  transverse_defect <= ordinary_identity_tolerance;

q0 = 2.0 * pi / period_y;
omitted_alpha_lower = q0 * (cfg.mode_cutoff + 1.0) - abs(beta_bloch);
omitted_evanescent_pass = omitted_alpha_lower > k_outer;
support_pass = isequal(double(z.wall_orders_512(:)), (-256.0:255.0).') && ...
  cfg.mode_cutoff >= 256.0 && cfg.mode_cutoff >= double(z.M);
lambda_modes = sqrt(transverse_wavenumber.^2 + mu_shift);
wall_weights = 2.0 * lambda_modes .* ...
  tanh(cfg.trace_half_width * lambda_modes);
weight_pass = all(isfinite(wall_weights) & wall_weights > 0.0);
audit = struct( ...
  'exact_wood', exact_wood, ...
  'outgoing_branch_pass', outgoing_pass, ...
  'stored_branch_relative_defect', branch_defect, ...
  'stored_transverse_wavenumber_relative_defect', transverse_defect, ...
  'stored_branch_ordinary_tolerance', ordinary_identity_tolerance, ...
  'stored_branch_pass', stored_branch_pass, ...
  'omitted_alpha_lower', omitted_alpha_lower, ...
  'omitted_modes_strictly_evanescent', omitted_evanescent_pass, ...
  'finite_support_pass', support_pass, ...
  'wall_weight_pass', weight_pass, ...
  'pass', ~exact_wood && outgoing_pass && stored_branch_pass && ...
    omitted_evanescent_pass && support_pass && weight_pass);
modal = struct( ...
  'wall_orders', wall_orders, ...
  'transverse_wavenumber', transverse_wavenumber, ...
  'branch_radicand', branch_radicand, ...
  'rayleigh_wavenumber', rayleigh_wavenumber, ...
  'propagating', propagating, ...
  'evanescent', evanescent, ...
  'lambda_modes', lambda_modes, ...
  'wall_weights', wall_weights, ...
  'audit', audit);
end

function density = LOCAL_density_data(z)
native_count = 256.0;
density_orders = (-native_count / 2.0:native_count / 2.0 - 1.0).';
tau_native = z.eta_unit_256(1:native_count, :);
single_layer_density_native = z.eta_unit_256(native_count + 1.0:end, :);
tau_coeff_map = fftshift(fft(tau_native, [], 1), 1) / native_count;
single_layer_density_coeff_map = fftshift( ...
  fft(single_layer_density_native, [], 1), 1) / native_count;
tau_parseval = LOCAL_parseval_defect(tau_native, tau_coeff_map);
single_layer_density_parseval = LOCAL_parseval_defect( ...
  single_layer_density_native, single_layer_density_coeff_map);
density_label_pass = strcmp(strtrim(z.density_coordinate), ...
  '[tau;zeta], zeta=-sigma');
finite_pass = all(isfinite([tau_coeff_map(:); ...
  single_layer_density_coeff_map(:)]));
ordinary_identity_tolerance = 4096.0 * eps;
audit = struct( ...
  'source_node_count', native_count, ...
  'source_orders', density_orders, ...
  'transform', 'fftshift(fft(native_samples))/256', ...
  'midpoint_phase_applied', false, ...
  'tau_parseval_relative_defect', tau_parseval, ...
  'single_layer_density_parseval_relative_defect', ...
    single_layer_density_parseval, ...
  'density_coordinate_label', z.density_coordinate, ...
  'single_layer_density_label_pass', density_label_pass, ...
  'ordinary_identity_tolerance', ordinary_identity_tolerance, ...
  'pass', finite_pass && density_label_pass && ...
    max(tau_parseval, single_layer_density_parseval) <= ...
    ordinary_identity_tolerance);
density = struct( ...
  'density_orders', density_orders, ...
  'tau_coeff_map', tau_coeff_map, ...
  'single_layer_density_coeff_map', single_layer_density_coeff_map, ...
  'tau_normalized_map', sqrt(2.0 * pi * z.R) * tau_coeff_map, ...
  'single_layer_density_normalized_map', ...
    sqrt(2.0 * pi * z.R) * single_layer_density_coeff_map, ...
  'audit', audit);
end

function defect = LOCAL_parseval_defect(native_values, coefficient_values)
native_energy = norm(native_values, 'fro')^2 / size(native_values, 1);
coefficient_energy = norm(coefficient_values, 'fro')^2;
defect = abs(native_energy - coefficient_energy) / ...
  max([realmin, native_energy, coefficient_energy]);
end

%% ==================== Finite circle and flat-wall rows ====================
% The stored empirical v4 normal factors are not used in these rows.

function circle_flux = LOCAL_circle_flux_rows(z, density, modal, cfg)
quadrature_nodes = cfg.quadrature_nodes;
theta = 2.0 * pi * (0.0:quadrature_nodes - 1.0).' / quadrature_nodes;
density_basis = exp(1i * theta * density.density_orders.');
tau_values = density_basis * density.tau_coeff_map;
single_layer_density_values = density_basis * ...
  density.single_layer_density_coeff_map;
clear density_basis

[circle_flux_left, left_kernel_mib] = LOCAL_circle_side_rows( ...
  z, modal, theta, tau_values, single_layer_density_values, ...
  z.X_L, -1.0);
[circle_flux_right, right_kernel_mib] = LOCAL_circle_side_rows( ...
  z, modal, theta, tau_values, single_layer_density_values, ...
  z.X_R, 1.0);

left_distance = abs(z.X_L - cfg.circle_center_x);
right_distance = abs(z.X_R - cfg.circle_center_x);
strip_width = 0.5 * log(min(left_distance, right_distance) / z.R);
if ~(strip_width > 0.0 && ...
    strip_width < log(min(left_distance, right_distance) / z.R))
  error('I5WallTail:StripWidth', ...
    'The fixed analytic strip does not fit between the circle and a wall.');
end
identity_state = eye(size(density.tau_coeff_map, 2));
left_q_error = LOCAL_strip_remainder( ...
  z, density, modal, identity_state, left_distance, strip_width, ...
  quadrature_nodes);
right_q_error = LOCAL_strip_remainder( ...
  z, density, modal, identity_state, right_distance, strip_width, ...
  quadrature_nodes);
audit = struct( ...
  'quadrature_nodes', quadrature_nodes, ...
  'strip_width', strip_width, ...
  'strip_rule', '0.5*log(minimum wall-center distance/R)', ...
  'left_wall_distance', left_distance, ...
  'right_wall_distance', right_distance, ...
  'left_q_error_max', max(left_q_error.display), ...
  'right_q_error_max', max(right_q_error.display), ...
  'left_q_error_log_max', max(left_q_error.log_value), ...
  'right_q_error_log_max', max(right_q_error.log_value), ...
  'underflow_floor_used', left_q_error.underflow_floor_used || ...
    right_q_error.underflow_floor_used, ...
  'kernel_workspace_proxy_mib', max(left_kernel_mib, right_kernel_mib), ...
  'finite', all(isfinite([circle_flux_left(:); circle_flux_right(:)])), ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
if ~audit.finite
  error('I5WallTail:CircleRows', ...
    'A finite circle-to-wall coefficient row is nonfinite.');
end
circle_flux = struct( ...
  'left', circle_flux_left, ...
  'right', circle_flux_right, ...
  'left_q_error', left_q_error, ...
  'right_q_error', right_q_error, ...
  'strip_width', strip_width, ...
  'audit', audit);
end

function [circle_rows, workspace_proxy_mib] = LOCAL_circle_side_rows( ...
    z, modal, theta, tau_values, single_layer_density_values, ...
    wall_x, wall_side_sign)
distance = abs(wall_x);
cos_theta = cos(theta);
sin_theta = sin(theta);
travel = distance - wall_side_sign * z.R * cos_theta;
source_y = z.R * sin_theta;
phase = exp(1i * travel * modal.rayleigh_wavenumber.' - ...
  1i * source_y * modal.transverse_wavenumber.');
derivative_factor = 1i * ( ...
  wall_side_sign * cos_theta * modal.rayleigh_wavenumber.' + ...
  sin_theta * modal.transverse_wavenumber.');
scale = (2.0 * pi / numel(theta)) * z.R / (2.0 * sqrt(z.d));
circle_rows = scale * ( ...
  (phase .* derivative_factor).' * tau_values + ...
  phase.' * single_layer_density_values);
workspace = whos;
workspace_proxy_mib = sum([workspace.bytes]) / 2.0^20;
end

function remainder = LOCAL_strip_remainder( ...
    z, density, modal, state_map, distance, strip_width, quadrature_nodes)
tau_composed = density.tau_coeff_map * state_map;
single_layer_density_composed = ...
  density.single_layer_density_coeff_map * state_map;
order_growth = exp(abs(density.density_orders) * strip_width);
D_tau = sum(LOCAL_row_norms(tau_composed) .* order_growth);
D_single_layer_density = sum( ...
  LOCAL_row_norms(single_layer_density_composed) .* order_growth);
if D_tau < 0.0 || D_single_layer_density < 0.0 || ...
    any(~isfinite([D_tau, D_single_layer_density]))
  error('I5WallTail:StripDensity', ...
    'A strip density constant is invalid.');
end

abs_gamma = abs(modal.rayleigh_wavenumber);
abs_transverse = abs(modal.transverse_wavenumber);
log_phase_bound = zeros(size(abs_gamma));
log_phase_bound(modal.propagating) = z.R * ( ...
  abs_gamma(modal.propagating) + abs_transverse(modal.propagating)) * ...
  sinh(strip_width);
kappa_modes = imag(modal.rayleigh_wavenumber(modal.evanescent));
log_phase_bound(modal.evanescent) = -kappa_modes * distance + ...
  z.R * (kappa_modes * cosh(strip_width) + ...
  abs_transverse(modal.evanescent) * sinh(strip_width));
derivative_density_bound = (abs_gamma + abs_transverse) * ...
  cosh(strip_width) * D_tau + D_single_layer_density;
if any(derivative_density_bound <= 0.0)
  error('I5WallTail:StripDensity', ...
    'A strip integrand bound is nonpositive.');
end
log_integrand_bound = log(z.R / (2.0 * sqrt(z.d))) + ...
  log_phase_bound + log(derivative_density_bound);
denominator_argument = strip_width * quadrature_nodes;
log_denominator = denominator_argument + ...
  log1p(-exp(-denominator_argument));
log_value = log(4.0 * pi) + log_integrand_bound - log_denominator;
[display_value, underflow_floor_used] = LOCAL_exp_display(log_value);
remainder = struct( ...
  'display', display_value, ...
  'log_value', log_value, ...
  'D_tau', D_tau, ...
  'D_single_layer_density', D_single_layer_density, ...
  'underflow_floor_used', underflow_floor_used, ...
  'branch_aware_conservative_bound', true);
end

function rows = LOCAL_wall_rows(z, density, modal, circle_flux, cfg)
xi_left = LOCAL_embed_orders( ...
  z.xi_left_unit_512, double(z.wall_orders_512(:)), modal.wall_orders);
xi_right = LOCAL_embed_orders( ...
  z.xi_right_unit_512, double(z.wall_orders_512(:)), modal.wall_orders);
wall_phase = exp(1i * modal.rayleigh_wavenumber * z.L);
flat_flux_left = 0.5 * (xi_left - wall_phase .* xi_right);
flat_flux_right = 0.5 * (-wall_phase .* xi_left + xi_right);
Q_left_tilde = flat_flux_left + circle_flux.left;
Q_right_tilde = flat_flux_right + circle_flux.right;

ell_plus_tilde = Q_right_tilde * z.Gplus + ...
  Q_left_tilde * z.Gplus * z.Pplus;
ell_minus_tilde = Q_left_tilde * z.Gminus + ...
  Q_right_tilde * z.Gminus * z.Pminus;
left_distance = abs(z.X_L - cfg.circle_center_x);
right_distance = abs(z.X_R - cfg.circle_center_x);
plus_right_error = LOCAL_strip_remainder( ...
  z, density, modal, z.Gplus, right_distance, ...
  circle_flux.strip_width, cfg.quadrature_nodes);
plus_left_error = LOCAL_strip_remainder( ...
  z, density, modal, z.Gplus * z.Pplus, left_distance, ...
  circle_flux.strip_width, cfg.quadrature_nodes);
minus_left_error = LOCAL_strip_remainder( ...
  z, density, modal, z.Gminus, left_distance, ...
  circle_flux.strip_width, cfg.quadrature_nodes);
minus_right_error = LOCAL_strip_remainder( ...
  z, density, modal, z.Gminus * z.Pminus, right_distance, ...
  circle_flux.strip_width, cfg.quadrature_nodes);
ell_plus_error = plus_right_error.display + plus_left_error.display;
ell_minus_error = minus_left_error.display + minus_right_error.display;

[center_dx_left, center_dx_right] = LOCAL_center_derivatives(z, modal);
plus_state = z.Gplus * z.cplus;
minus_state = z.Gminus * z.cminus;
singleton_plus_tilde = center_dx_right + Q_left_tilde * plus_state;
singleton_minus_tilde = -center_dx_left + Q_right_tilde * minus_state;
singleton_plus_record = LOCAL_strip_remainder( ...
  z, density, modal, plus_state, left_distance, ...
  circle_flux.strip_width, cfg.quadrature_nodes);
singleton_minus_record = LOCAL_strip_remainder( ...
  z, density, modal, minus_state, right_distance, ...
  circle_flux.strip_width, cfg.quadrature_nodes);
rows = struct( ...
  'Q_left_tilde', Q_left_tilde, ...
  'Q_right_tilde', Q_right_tilde, ...
  'ell_plus_tilde', ell_plus_tilde, ...
  'ell_minus_tilde', ell_minus_tilde, ...
  'ell_plus_error', ell_plus_error, ...
  'ell_minus_error', ell_minus_error, ...
  'singleton_plus_tilde', singleton_plus_tilde, ...
  'singleton_minus_tilde', singleton_minus_tilde, ...
  'singleton_plus_error', singleton_plus_record.display, ...
  'singleton_minus_error', singleton_minus_record.display, ...
  'center_dx_left', center_dx_left, ...
  'center_dx_right', center_dx_right, ...
  'remainder_records', struct( ...
    'plus_right', plus_right_error, ...
    'plus_left', plus_left_error, ...
    'minus_left', minus_left_error, ...
    'minus_right', minus_right_error, ...
    'singleton_plus', singleton_plus_record, ...
    'singleton_minus', singleton_minus_record));
end

function [center_dx_left, center_dx_right] = LOCAL_center_derivatives(z, modal)
K = double(z.K);
center_left_state = z.q_center(1:K);
center_right_state = z.q_center(K + 1.0:end);
retained_orders = (-double(z.M):double(z.M)).';
[present, retained_indices] = ismember(retained_orders, modal.wall_orders);
if ~all(present)
  error('I5WallTail:CenterEmbedding', ...
    'A center Rayleigh order is absent from the finite wall range.');
end
retained_gamma = modal.rayleigh_wavenumber(retained_indices);
retained_phase = exp(1i * retained_gamma * z.L);
left_retained = 1i * retained_gamma .* ( ...
  center_left_state - retained_phase .* center_right_state);
right_retained = 1i * retained_gamma .* ( ...
  retained_phase .* center_left_state - center_right_state);
center_dx_left = complex(zeros(size(modal.wall_orders)));
center_dx_right = center_dx_left;
center_dx_left(retained_indices) = left_retained;
center_dx_right(retained_indices) = right_retained;
end

%% ==================== Side, sign, and index audit ====================
% Stored ordinary maps are cross-checks only and never enter the wall bound.

function audit = LOCAL_side_index_audit( ...
    z, raw_maps, modal, rows, circle_flux, cfg)
G_plus_reference = [z.Dplus; z.Dplus * z.Pplus];
G_minus_reference = [z.Dminus * z.Pminus; z.Dminus];
G_plus_defect = LOCAL_relative_difference(z.Gplus, G_plus_reference);
G_minus_defect = LOCAL_relative_difference(z.Gminus, G_minus_reference);
stored_plus_defect = LOCAL_relative_difference( ...
  raw_maps.Jplus, raw_maps.QRplus + raw_maps.QLplus * z.Pplus);
stored_minus_defect = LOCAL_relative_difference( ...
  raw_maps.Jminus, raw_maps.QLminus + raw_maps.QRminus * z.Pminus);

stored_orders = double(z.wall_orders_512(:));
[present, finite_indices] = ismember(stored_orders, modal.wall_orders);
if ~all(present)
  error('I5WallTail:AuditEmbedding', ...
    'An I3 audit order is absent from the finite I5 range.');
end
Q_left_defect = LOCAL_relative_difference( ...
  rows.Q_left_tilde(finite_indices, :), ...
  raw_maps.wall_flux_left_unit_512);
Q_right_defect = LOCAL_relative_difference( ...
  rows.Q_right_tilde(finite_indices, :), ...
  raw_maps.wall_flux_right_unit_512);
ell_plus_defect = LOCAL_relative_difference( ...
  rows.ell_plus_tilde(finite_indices, :), raw_maps.Jplus);
ell_minus_defect = LOCAL_relative_difference( ...
  rows.ell_minus_tilde(finite_indices, :), raw_maps.Jminus);

stored_center_left = z.center_wall_jumps.center_left_global_dx;
stored_center_right = z.center_wall_jumps.center_right_global_dx;
center_left_defect = LOCAL_relative_difference( ...
  rows.center_dx_left(finite_indices), stored_center_left);
center_right_defect = LOCAL_relative_difference( ...
  rows.center_dx_right(finite_indices), stored_center_right);
singleton_left_defect = LOCAL_relative_difference( ...
  rows.singleton_minus_tilde(finite_indices), ...
  z.center_wall_jumps.left_coefficients);
singleton_right_defect = LOCAL_relative_difference( ...
  rows.singleton_plus_tilde(finite_indices), ...
  z.center_wall_jumps.right_coefficients);

ordinary_identity_tolerance = 4096.0 * eps;
structural_pass = ...
  G_plus_defect <= ordinary_identity_tolerance && ...
  G_minus_defect <= ordinary_identity_tolerance && ...
  stored_plus_defect <= ordinary_identity_tolerance && ...
  stored_minus_defect <= ordinary_identity_tolerance && ...
  center_left_defect <= ordinary_identity_tolerance && ...
  center_right_defect <= ordinary_identity_tolerance && ...
  strcmp(strtrim(z.global_normal_label), ...
    'global +r on the circle; cell outward on walls') && ...
  strcmp(strtrim(z.density_coordinate), '[tau;zeta], zeta=-sigma') && ...
  cfg.mode_cutoff >= 256.0;
audit = struct( ...
  'structural_pass', structural_pass, ...
  'ordinary_identity_tolerance', ordinary_identity_tolerance, ...
  'G_plus_relative_defect', G_plus_defect, ...
  'G_minus_relative_defect', G_minus_defect, ...
  'stored_J_plus_association_defect', stored_plus_defect, ...
  'stored_J_minus_association_defect', stored_minus_defect, ...
  'center_dx_left_relative_defect', center_left_defect, ...
  'center_dx_right_relative_defect', center_right_defect, ...
  'analytic_Q_left_crosscheck_defect', Q_left_defect, ...
  'analytic_Q_right_crosscheck_defect', Q_right_defect, ...
  'analytic_ell_plus_crosscheck_defect', ell_plus_defect, ...
  'analytic_ell_minus_crosscheck_defect', ell_minus_defect, ...
  'analytic_singleton_left_crosscheck_defect', singleton_left_defect, ...
  'analytic_singleton_right_crosscheck_defect', singleton_right_defect, ...
  'analytic_crosschecks_enter_bound', false, ...
  'stored_raw_maps_enter_bound', false, ...
  'q_row_remainder_log_max', max([ ...
    circle_flux.left_q_error.log_value; ...
    circle_flux.right_q_error.log_value]), ...
  'plus_formula', 'QR*Gplus + QL*Gplus*Pplus', ...
  'minus_formula', 'QL*Gminus + QR*Gminus*Pminus', ...
  'singleton_minus_formula', '-dxL + QR*Gminus*cminus', ...
  'singleton_plus_formula', 'dxR + QL*Gplus*cplus', ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
end

%% ==================== Full-matrix propagation ====================
% Block powers retain nonnormal transients and complete Jordan coupling.

function certificate = LOCAL_block_certificate(P, block_length)
state = eye(size(P));
power_norms = zeros(block_length, 1);
for power_index = 0.0:block_length - 1.0
  power_norms(power_index + 1.0) = norm(state, 2);
  state = state * P;
end
block_norm = norm(state, 2);
contraction_pass = isfinite(block_norm) && block_norm < 1.0;
if contraction_pass
  propagation_constant = sum(power_norms.^2) / (1.0 - block_norm^2);
else
  propagation_constant = Inf;
end
certificate = struct( ...
  'block_length', block_length, ...
  'power_norms', power_norms, ...
  'block_norm', block_norm, ...
  'propagation_constant', propagation_constant, ...
  'contraction_pass', contraction_pass, ...
  'whole_matrix_norms', true, ...
  'spectral_radius_substitution', false, ...
  'ordinary_floating_point', true, ...
  'outward_norm_upper_bounds', false, ...
  'reliability_certified', false);
end

%% ==================== Positive-distance high-mode constants ====================
% The C(M;A,B) formula is evaluated in logarithmic form.

function constants = LOCAL_density_constants(z, density)
normalization = sqrt(2.0 * pi * z.R);
T_tau = density.tau_normalized_map;
T_single_layer_density = density.single_layer_density_normalized_map;
constants = struct( ...
  'A_tau_plus', normalization * ( ...
    norm(T_tau * z.Gplus, 'fro') + ...
    norm(T_tau * z.Gplus * z.Pplus, 'fro')), ...
  'A_single_layer_density_plus', normalization * ( ...
    norm(T_single_layer_density * z.Gplus, 'fro') + ...
    norm(T_single_layer_density * z.Gplus * z.Pplus, 'fro')), ...
  'A_tau_minus', normalization * ( ...
    norm(T_tau * z.Gminus, 'fro') + ...
    norm(T_tau * z.Gminus * z.Pminus, 'fro')), ...
  'A_single_layer_density_minus', normalization * ( ...
    norm(T_single_layer_density * z.Gminus, 'fro') + ...
    norm(T_single_layer_density * z.Gminus * z.Pminus, 'fro')), ...
  'A_tau_plus_singleton', normalization * ...
    norm(T_tau * z.Gplus * z.cplus), ...
  'A_single_layer_density_plus_singleton', normalization * ...
    norm(T_single_layer_density * z.Gplus * z.cplus), ...
  'A_tau_minus_singleton', normalization * ...
    norm(T_tau * z.Gminus * z.cminus), ...
  'A_single_layer_density_minus_singleton', normalization * ...
    norm(T_single_layer_density * z.Gminus * z.cminus), ...
  'normalization', ...
    'sqrt(2*pi*R)*normalized Fourier-coordinate Frobenius bound');
values = cell2mat(struct2cell(rmfield(constants, 'normalization')));
if any(~isfinite(values) | values < 0.0)
  error('I5WallTail:DensityConstants', ...
    'A normalized density constant is invalid.');
end
end

function high_mode = LOCAL_high_mode_constants( ...
    z, constants, modal, cfg)
positive_distance = min(-z.X_L - z.R, z.X_R - z.R);
if ~(positive_distance > 0.0)
  error('I5WallTail:PositiveDistance', ...
    'The circle-to-wall distance is not strictly positive.');
end
plus = LOCAL_C_squared(z, constants.A_tau_plus, ...
  constants.A_single_layer_density_plus, positive_distance, cfg);
minus = LOCAL_C_squared(z, constants.A_tau_minus, ...
  constants.A_single_layer_density_minus, positive_distance, cfg);
plus_singleton = LOCAL_C_squared(z, ...
  constants.A_tau_plus_singleton, ...
  constants.A_single_layer_density_plus_singleton, ...
  positive_distance, cfg);
minus_singleton = LOCAL_C_squared(z, ...
  constants.A_tau_minus_singleton, ...
  constants.A_single_layer_density_minus_singleton, ...
  positive_distance, cfg);
high_mode = struct( ...
  'positive_distance', positive_distance, ...
  'mode_cutoff', cfg.mode_cutoff, ...
  'omitted_modes_strictly_evanescent', ...
    modal.audit.omitted_modes_strictly_evanescent, ...
  'C_plus_squared', plus.display_squared, ...
  'C_minus_squared', minus.display_squared, ...
  'C_plus_singleton_squared', plus_singleton.display_squared, ...
  'C_minus_singleton_squared', minus_singleton.display_squared, ...
  'log_C_plus_squared', plus.log_squared, ...
  'log_C_minus_squared', minus.log_squared, ...
  'log_C_plus_singleton_squared', plus_singleton.log_squared, ...
  'log_C_minus_singleton_squared', minus_singleton.log_squared, ...
  'underflow_floor_used', plus.underflow_floor_used || ...
    minus.underflow_floor_used || plus_singleton.underflow_floor_used || ...
    minus_singleton.underflow_floor_used, ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
end

function C = LOCAL_C_squared( ...
    z, A_tau, A_single_layer_density, positive_distance, cfg)
k_outer = double(z.khat);
beta_bloch = double(z.beta);
period_y = double(z.d);
q0 = 2.0 * pi / period_y;
first_omitted_index = cfg.mode_cutoff + 1.0;
a0 = q0 * first_omitted_index - abs(beta_bloch);
if ~(a0 > k_outer)
  error('I5WallTail:HighModeCutoff', ...
    'The first omitted order is not proved evanescent.');
end
r = exp(-2.0 * positive_distance * q0);
log_S0 = first_omitted_index * log(r) - log1p(-r);
S1_over_S0 = first_omitted_index + r / (1.0 - r);
t0 = tanh(cfg.trace_half_width * a0);
bracket_over_S0 = 4.0 * A_tau^2 * ( ...
  q0 * S1_over_S0 + abs(beta_bloch)) + ...
  4.0 * A_tau * A_single_layer_density + ...
  A_single_layer_density^2 / a0;
if bracket_over_S0 == 0.0
  log_squared = -Inf;
else
  log_squared = 2.0 * positive_distance * ...
    (k_outer + abs(beta_bloch)) - log(4.0 * period_y * t0) + ...
    log_S0 + log(bracket_over_S0);
end
[display_squared, underflow_floor_used] = LOCAL_exp_display(log_squared);
C = struct( ...
  'display_squared', display_squared, ...
  'log_squared', log_squared, ...
  'underflow_floor_used', underflow_floor_used);
end

%% ==================== Finite and omitted assembly ====================
% The four theorem pieces are disjoint in wall, mode, and cell index.

function finite = LOCAL_finite_part(z, modal, rows, cfg)
[plus_squared, plus_state_after] = LOCAL_side_finite( ...
  rows.ell_plus_tilde, rows.ell_plus_error, ...
  rows.singleton_plus_tilde, rows.singleton_plus_error, ...
  modal.wall_weights, z.Pplus, z.cplus, cfg.cell_cutoff);
[minus_squared, minus_state_after] = LOCAL_side_finite( ...
  rows.ell_minus_tilde, rows.ell_minus_error, ...
  rows.singleton_minus_tilde, rows.singleton_minus_error, ...
  modal.wall_weights, z.Pminus, z.cminus, cfg.cell_cutoff);
finite_squared = plus_squared + minus_squared;
finite = struct( ...
  'finite_squared', finite_squared, ...
  'finite_norm', sqrt(finite_squared), ...
  'plus_squared', plus_squared, ...
  'minus_squared', minus_squared, ...
  'plus_state_after_J', plus_state_after, ...
  'minus_state_after_J', minus_state_after, ...
  'mode_cutoff', cfg.mode_cutoff, ...
  'cell_cutoff', cfg.cell_cutoff);
end

function [side_squared, state_after] = LOCAL_side_finite( ...
    ell_tilde, ell_error, singleton_tilde, singleton_error, ...
    wall_weights, P, starting_state, cell_cutoff)
side_squared = sum((abs(singleton_tilde) + singleton_error).^2 ./ ...
  wall_weights);
state = starting_state;
for cell_index = 0.0:cell_cutoff - 1.0
  row_actions = ell_tilde * state;
  enclosed_actions = abs(row_actions) + ell_error * norm(state);
  side_squared = side_squared + ...
    sum(enclosed_actions.^2 ./ wall_weights);
  state = P * state;
end
state_after = state;
end

function tail = LOCAL_tail_part( ...
    z, modal, rows, finite, high_mode, ...
    propagation_minus, propagation_plus)
omega_plus = sum((LOCAL_row_norms(rows.ell_plus_tilde) + ...
  rows.ell_plus_error).^2 ./ modal.wall_weights);
omega_minus = sum((LOCAL_row_norms(rows.ell_minus_tilde) + ...
  rows.ell_minus_error).^2 ./ modal.wall_weights);
plus_finite_mode_propagation = omega_plus * ...
  propagation_plus.propagation_constant * ...
  norm(finite.plus_state_after_J)^2;
minus_finite_mode_propagation = omega_minus * ...
  propagation_minus.propagation_constant * ...
  norm(finite.minus_state_after_J)^2;
plus_high_internal = high_mode.C_plus_squared * ...
  propagation_plus.propagation_constant * norm(z.cplus)^2;
minus_high_internal = high_mode.C_minus_squared * ...
  propagation_minus.propagation_constant * norm(z.cminus)^2;
plus_high_singleton = high_mode.C_plus_singleton_squared;
minus_high_singleton = high_mode.C_minus_singleton_squared;
tail_squared = plus_finite_mode_propagation + ...
  minus_finite_mode_propagation + plus_high_internal + ...
  minus_high_internal + plus_high_singleton + minus_high_singleton;
if ~isfinite(tail_squared) || tail_squared < 0.0
  error('I5WallTail:TailAssembly', ...
    'The omitted artificial-wall contribution is nonfinite or negative.');
end
tail = struct( ...
  'tail_squared', tail_squared, ...
  'tail_norm', sqrt(tail_squared), ...
  'omega_plus', omega_plus, ...
  'omega_minus', omega_minus, ...
  'plus_finite_mode_propagation', plus_finite_mode_propagation, ...
  'minus_finite_mode_propagation', minus_finite_mode_propagation, ...
  'plus_high_internal', plus_high_internal, ...
  'minus_high_internal', minus_high_internal, ...
  'plus_high_singleton', plus_high_singleton, ...
  'minus_high_singleton', minus_high_singleton, ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
end

%% ==================== Small numerical helpers ====================
% These helpers implement only finite algebra used by the displayed formulas.

function embedded = LOCAL_embed_orders(values, source_orders, target_orders)
[present, target_indices] = ismember(source_orders, target_orders);
if ~all(present) || size(values, 1) ~= numel(source_orders)
  error('I5WallTail:OrderEmbedding', ...
    'A finite coefficient order cannot be embedded.');
end
embedded = complex(zeros(numel(target_orders), size(values, 2)));
embedded(target_indices, :) = values;
end

function norms = LOCAL_row_norms(values)
norms = sqrt(sum(abs(values).^2, 2));
end

function defect = LOCAL_relative_difference(left, right)
if ~isequal(size(left), size(right))
  defect = Inf;
  return
end
defect = norm(left - right, 'fro') / ...
  max([realmin, norm(left, 'fro'), norm(right, 'fro')]);
end

function [display_value, underflow_floor_used] = LOCAL_exp_display(log_value)
display_value = zeros(size(log_value));
positive = isfinite(log_value);
if any(log_value(positive) > log(realmax))
  error('I5WallTail:ExponentialOverflow', ...
    'A logarithmic upper bound exceeds the floating-point display range.');
end
underflow = positive & log_value < log(realmin);
regular = positive & ~underflow;
display_value(regular) = exp(log_value(regular));
display_value(underflow) = realmin;
underflow_floor_used = any(underflow);
end
