function inspect_i4_1c_artifacts()
%INSPECT_I4_1C_ARTIFACTS Read and cross-check current-run I4.1c artifacts.
% Purpose:
%   Inspect the six immutable run-001/execution-001 MAT leaves and their
%   terminal, summary, and resource records without solving or writing data.
% Input:
%   None. The current-run location is resolved relative to this source file.
% Output:
%   Tab-delimited evidence is printed to stdout for the create-once external
%   artifact-review controller.
% Main algorithm:
%   Cross-check scalar/text authority, print selected field objects and rank,
%   inspect mathematical validations and observed refinement, and recompute
%   read-only common-grid overlaps for the stored matched-axis fields.
% Notes:
%   This function does not call the FEM core, eigs, or any publisher. It reads
%   no historical output, BIE/QZ data, estimator data, Markdown, or Git state.

  source_dir = fileparts(mfilename('fullpath'));
  run_dir = fullfile(source_dir, 'output', 'run-001', 'execution-001');
  required = {'preliminary-result.mat', 'preliminary-fields.mat', ...
    'final-result.mat', 'final-fields.mat', 'refinement-result.mat', ...
    'refinement-fields.mat', 'run-summary.csv', 'resource.tsv', ...
    fullfile('work', 'terminal.tsv')};
  for index = 1:numel(required)
    LOCAL_require(isfile(fullfile(run_dir, required{index})), ...
      ['Missing current-run artifact: ' required{index}]);
  end

  fprintf('CORE_MARKER\tartifact-review\tLOAD_BEGIN\n');
  preliminary = load(fullfile(run_dir, 'preliminary-result.mat'));
  preliminary_fields = load(fullfile(run_dir, 'preliminary-fields.mat'));
  final = load(fullfile(run_dir, 'final-result.mat'));
  final_fields = load(fullfile(run_dir, 'final-fields.mat'));
  refinement = load(fullfile(run_dir, 'refinement-result.mat'));
  refinement_fields = load(fullfile(run_dir, 'refinement-fields.mat'));
  fprintf('CORE_MARKER\tartifact-review\tLOAD_END\n');

  LOCAL_validate_text_authority(run_dir, final, refinement);
  LOCAL_require(abs(preliminary.lambda_pre - preliminary.k_pre^2) <= ...
    32 * eps * max(1, abs(preliminary.lambda_pre)), ...
    'The preliminary scalar violates lambda=k^2.');
  LOCAL_require(abs(final.lambda_ref - final.k_ref^2) <= ...
    32 * eps * max(1, abs(final.lambda_ref)), ...
    'The final scalar violates lambda=k^2.');
  fprintf('SCALAR\tpreliminary\tlambda=%.17g\tk=%.17g\n', ...
    preliminary.lambda_pre, preliminary.k_pre);
  fprintf('SCALAR\tfinal\tlambda=%.17g\tk=%.17g\n', ...
    final.lambda_ref, final.k_ref);

  LOCAL_print_authority('preliminary', preliminary, preliminary_fields);
  LOCAL_print_authority('final', final, final_fields);
  LOCAL_require(all(size(final.preliminary_final_overlap) == ...
    [numel(preliminary_fields.objects), numel(final_fields.objects)]), ...
    'The preliminary-final overlap matrix shape is inconsistent.');
  fprintf('PRE_FINAL_OVERLAP\tmatrix=%s\tminimum_match=%.17g\n', ...
    mat2str(final.preliminary_final_overlap, 17), ...
    final.preliminary_match_min_overlap);

  LOCAL_print_validation('preliminary', preliminary.validation);
  LOCAL_print_validation('final', final.validation);
  LOCAL_print_refinement(refinement, refinement_fields, final_fields);
  LOCAL_print_field_leaf('preliminary', preliminary_fields);
  LOCAL_print_field_leaf('final', final_fields);

  caveats = LOCAL_schema_caveats(preliminary_fields, final_fields, ...
    refinement, refinement_fields);
  for index = 1:numel(caveats)
    fprintf('SCHEMA_CAVEAT\t%s\n', caveats{index});
  end
  if isempty(caveats)
    terminal = 'PASS';
  else
    terminal = 'PASS_WITH_SCHEMA_CAVEATS';
  end
  fprintf(['ARTIFACT_REVIEW_SUMMARY\tpre_k=%.17g\tfinal_k=%.17g\t' ...
    'Delta_ref_obs=%.17g\tmatched_axes=%d\tschema_caveats=%d\n'], ...
    preliminary.k_pre, final.k_ref, refinement.Delta_ref_obs, ...
    numel(refinement_fields.matched_axes), numel(caveats));
  fprintf('ARTIFACT_REVIEW_TERMINAL\t%s\n', terminal);
end

%% ==================== Authority and text consistency ====================
% These helpers compare immutable scalar and field authorities.

function LOCAL_validate_text_authority(run_dir, final, refinement)
  summary_lines = LOCAL_nonempty_lines( ...
    fileread(fullfile(run_dir, 'run-summary.csv')));
  LOCAL_require(numel(summary_lines) == 2, ...
    'run-summary.csv must contain exactly one data row.');
  summary = strsplit(summary_lines{2}, ',');
  LOCAL_require(numel(summary) == 12, ...
    'run-summary.csv has the wrong column count.');
  terminal = LOCAL_key_values( ...
    fileread(fullfile(run_dir, 'work', 'terminal.tsv')));
  resource_lines = LOCAL_nonempty_lines( ...
    fileread(fullfile(run_dir, 'resource.tsv')));
  resource = strsplit(resource_lines{end}, sprintf('\t'));
  LOCAL_require(numel(resource) == 7 && ...
    strcmp(resource{2}, 'WHOLE_COMMAND_TERMINAL'), ...
    'resource.tsv lacks its whole-command terminal row.');
  LOCAL_require(strcmp(summary{1}, 'run-001') && ...
    strcmp(summary{2}, 'execution-001') && ...
    strcmp(summary{3}, 'NATURAL_EXIT') && ...
    strcmp(summary{4}, terminal.scientific_terminal) && ...
    strcmp(summary{5}, terminal.claim_boundary) && ...
    str2double(summary{6}) == str2double(terminal.attempted_solves) && ...
    str2double(summary{7}) == str2double(terminal.completed_solves) && ...
    str2double(summary{8}) == str2double(terminal.planned_solves) && ...
    str2double(summary{6}) == 71 && str2double(summary{7}) == 71 && ...
    str2double(summary{8}) == 71, ...
    'Summary and terminal identities or solve counts disagree.');
  LOCAL_require(abs(str2double(summary{9}) - final.lambda_ref) <= ...
    8 * eps * max(1, abs(final.lambda_ref)) && ...
    abs(str2double(summary{10}) - final.k_ref) <= ...
    8 * eps * max(1, abs(final.k_ref)) && ...
    strcmp(summary{4}, 'CURVED_P2_EMPIRICAL_REFERENCE_REFINEMENT_COMPLETE') && ...
    strcmp(refinement.resolution_status, 'EMPIRICAL_RESOLUTION_COMPLETE'), ...
    'Summary scalar or completion status disagrees with MAT authority.');
  LOCAL_require(abs(str2double(summary{11}) - str2double(resource{3})) <= ...
    5e-6 && str2double(summary{12}) == str2double(resource{4}) && ...
    strcmp(resource{5}, 'NATURAL_EXIT') && ...
    str2double(resource{6}) == 0 && str2double(resource{7}) == 0, ...
    'Summary and final resource event disagree.');
  fprintf(['TEXT_AUTHORITY\tterminal=%s\tattempted=%s\tcompleted=%s\t' ...
    'planned=%s\twall=%s\tpeak_rss=%s\n'], ...
    summary{4}, summary{6}, summary{7}, summary{8}, summary{11}, summary{12});
end

function LOCAL_print_authority(label, result, fields)
  ids = result.selection.object_ids;
  LOCAL_require(numel(ids) == numel(fields.objects) && ...
    isequal([fields.objects.object_id], [result.objects(ids).object_id]), ...
    [label ' result and field selections disagree.']);
  fprintf(['SELECTION\t%s\tobject_ids=%s\trank_key=%s\t' ...
    'classification=%s\n'], label, mat2str(ids), ...
    mat2str(result.selection.rank_key, 17), ...
    LOCAL_text_list(result.selection.classification));
  component_index = find(arrayfun(@(item) ...
    isequal(sort(item.realization_ids), sort(ids)), ...
    result.tracking.components), 1);
  if isempty(component_index)
    component_index = 0;
  end
  edges = result.tracking.edges;
  selected_edge = false(size(edges));
  if ~isempty(edges)
    selected_edge = [edges.real_pair] & ...
      ismember([edges.source_object_id], ids) & ...
      ismember([edges.target_object_id], ids);
  end
  if any(selected_edge)
    minimum_overlap = min([edges(selected_edge).overlap]);
  else
    minimum_overlap = NaN;
  end
  fprintf(['TRACKING\t%s\tcomponent_index=%d\treal_edges=%d\t' ...
    'minimum_overlap=%.17g\n'], label, component_index, ...
    nnz(selected_edge), minimum_overlap);
  selected = result.objects(ids);
  for index = 1:numel(selected)
    object = selected(index);
    fprintf(['OBJECT\t%s\tobject_id=%d\ttheta_index=%d\tphase=%.17g\t' ...
      'root_index=%d\troot_indices=%s\tdimension=%d\t' ...
      'k_envelope=%s\tresidual_max=%.17g\tL0=%.17g\tLcore=%.17g\t' ...
      'tail=%.17g\tlocalization=%s\tparity=%s\tparity_status=%s\t' ...
      'parity_invariance=%.17g\n'], label, object.object_id, ...
      object.theta_index, object.phase, object.root_index, ...
      mat2str(object.root_indices), object.dimension, ...
      mat2str(object.k_envelope, 17), object.residual_max, ...
      object.L0_min, object.Lcore_min, object.tail_max, ...
      object.localization_status, object.parity_label, ...
      object.parity_status, object.parity_invariance_defect);
  end
  if isfield(result, 'coverage_classification')
    fprintf('COVERAGE\t%s\toverall=%s\n', ...
      label, result.coverage_classification);
  end
  for index = 1:numel(result.spectrum_authority)
    row = result.spectrum_authority(index);
    fprintf(['COVERAGE_SLICE\t%s\tphase=%.17g\tauthority=%s\t' ...
      'roots=%d\tcoverage=%s\tagreement=%s\n'], label, row.phase, ...
      row.active_authority, row.active_root_count, ...
      row.coverage_classification, row.agreement_status);
  end
end

%% ==================== Mathematical diagnostics ====================
% Validation fields are printed without changing their epistemic status.

function LOCAL_print_validation(label, validation)
  element = validation.element;
  local_embedding = validation.local_embedding;
  global_embedding = validation.global_embedding;
  quadrature = validation.quadrature;
  mapping = validation.mapping;
  geometry = validation.geometry;
  field_map = validation.field_map;
  fprintf(['VALIDATION_ELEMENT\t%s\tnodal=%.17g\tpartition=%.17g\t' ...
    'gradient=%.17g\tinterval=%s\ttriangle=%s\n'], label, ...
    element.nodal_defect, element.partition_value_defect, ...
    element.partition_gradient_defect, ...
    mat2str(element.interval_monomial_defects, 17), ...
    mat2str(element.triangle_monomial_defects, 17));
  fprintf(['VALIDATION_EMBEDDING\t%s\tlocal_K=%s\tlocal_M=%s\t' ...
    'full_K=%.17g\tfull_M=%.17g\tphase=%.17g\treduced_K=%.17g\t' ...
    'reduced_M=%.17g\n'], label, ...
    mat2str(local_embedding.maximum_stiffness_embedding_defects, 17), ...
    mat2str(local_embedding.maximum_mass_embedding_defects, 17), ...
    global_embedding.full_stiffness_defect, ...
    global_embedding.full_mass_defect, ...
    global_embedding.phase_commutation_defect, ...
    global_embedding.reduced_stiffness_defect, ...
    global_embedding.reduced_mass_defect);
  fprintf(['VALIDATION_QUADRATURE\t%s\torders=%s\tmass_4_6=%.17g\t' ...
    'mass_6_8=%.17g\tstiffness_4_6=%.17g\tstiffness_6_8=%.17g\t' ...
    'monomial_4_6=%.17g\tmonomial_6_8=%.17g\n'], label, ...
    mat2str(quadrature.orders), quadrature.mass_change_4_6, ...
    quadrature.mass_change_6_8, quadrature.stiffness_change_4_6, ...
    quadrature.stiffness_change_6_8, ...
    quadrature.low_monomial_change_4_6, ...
    quadrature.low_monomial_change_6_8);
  fprintf(['VALIDATION_MAP\t%s\tdet_min=%.17g\tdet_tol=%.17g\t' ...
    'det_polynomial=%.17g\tinterface_edges=%d\tendpoint_radius=%.17g\t' ...
    'midpoint_radius=%.17g\ttrace=%.17g\tradial_trace=%.17g\t' ...
    'noninterface_midpoint=%.17g\tloop=%s\n'], label, ...
    mapping.determinant_minimum, mapping.determinant_tolerance_maximum, ...
    mapping.determinant_polynomial_defect, geometry.interface_edge_count, ...
    geometry.endpoint_radius_error, geometry.midpoint_radius_error, ...
    geometry.trace_consistency_defect, geometry.radial_trace_defect, ...
    geometry.noninterface_midpoint_defect, geometry.loop_status);
  fprintf(['VALIDATION_FIELD\t%s\tinverse=%.17g\tuncovered=%d\t' ...
    'ambiguous=%d\tshared=%d\taffine_fixture=%.17g\t' ...
    'two_sided=%d\ttrace_owner=%d\n'], label, ...
    field_map.maximum_inverse_residual, field_map.uncovered_count, ...
    field_map.ambiguous_interior_count, field_map.shared_trace_count, ...
    field_map.curved_affine_fixture_defect, ...
    field_map.two_sided_fixture_material_change, ...
    field_map.trace_owner_triangle);
end

function LOCAL_print_refinement(refinement, refinement_fields, final_fields)
  scalars = refinement.scalars;
  fprintf(['REFINEMENT\th0=%.17g\th2=%.17g\tg0=%.17g\tg2=%.17g\t' ...
    'N3=%.17g\tN5=%.17g\ttheta9=%.17g\tq4=%.17g\tq6=%.17g\t' ...
    'loose=%.17g\n'], scalars.h0, scalars.h2, scalars.g0, scalars.g2, ...
    scalars.N3, scalars.N5, scalars.theta9, scalars.q4, scalars.q6, ...
    scalars.loose);
  fprintf(['REFINEMENT_DELTA\th=%.17g\tg=%.17g\tN=%.17g\t' ...
    'theta=%.17g\tQ=%.17g\ttol=%.17g\tDelta_ref_obs=%.17g\t' ...
    'finite=%s\tstatus=%s\n'], refinement.delta_h, refinement.delta_g, ...
    refinement.delta_N, refinement.delta_theta, refinement.delta_Q, ...
    refinement.delta_tol, refinement.Delta_ref_obs, ...
    mat2str(refinement.finite_components), refinement.resolution_status);
  for index = 1:numel(refinement.bulk)
    row = refinement.bulk(index);
    if row.valid && ~isempty(row.frequencies)
      range = [min(row.frequencies), max(row.frequencies)];
    else
      range = [NaN, NaN];
    end
    fprintf(['BULK\tindex=%d\tphase=%.17g\tvalid=%d\tk_range=%s\t' ...
      'code=%s\treason=%s\n'], index, row.phase, row.valid, ...
      mat2str(range, 17), row.code, row.reason);
  end
  for index = 1:numel(refinement_fields.matched_axes)
    axis = refinement_fields.matched_axes(index);
    overlaps = NaN(1, numel(axis.objects));
    nearest_phase = NaN(1, numel(axis.objects));
    for object_index = 1:numel(axis.objects)
      object = axis.objects(object_index);
      [~, match] = min(abs([final_fields.objects.phase] - object.phase));
      nearest_phase(object_index) = final_fields.objects(match).phase;
      overlaps(object_index) = LOCAL_common_overlap( ...
        object, final_fields.objects(match));
    end
    fprintf(['MATCHED_AXIS\tconfiguration=%s\tobject_ids=%s\tphases=%s\t' ...
      'dimensions=%s\tnearest_final_phases=%s\toverlaps=%s\t' ...
      'minimum_overlap=%.17g\n'], axis.configuration, ...
      mat2str([axis.objects.object_id]), mat2str([axis.objects.phase], 17), ...
      mat2str([axis.objects.dimension]), mat2str(nearest_phase, 17), ...
      mat2str(overlaps, 17), min(overlaps));
  end
end

function overlap = LOCAL_common_overlap(first, second)
  LOCAL_require(numel(first.common_core_weights) == ...
    numel(second.common_core_weights) && ...
    max(abs(first.common_core_weights - second.common_core_weights)) <= 1e-14, ...
    'Matched-axis common-grid weights disagree.');
  singular_values = svd(first.common_core_samples' * ...
    (first.common_core_weights .* second.common_core_samples));
  dimension = min(first.dimension, second.dimension);
  overlap = sum(singular_values(1:dimension) .^ 2) / dimension;
end

function LOCAL_print_field_leaf(label, fields)
  finite = all(isfinite(fields.points), 'all') && ...
    all(isfinite(fields.triangles), 'all') && ...
    all(isfinite(fields.p2_points), 'all') && ...
    all(isfinite(fields.triangle_p2), 'all');
  for index = 1:numel(fields.objects)
    object = fields.objects(index);
    finite = finite && ~isempty(object.subspace) && ...
      ~isempty(object.common_core_samples) && ...
      ~isempty(object.common_core_weights) && ...
      all(isfinite(object.subspace), 'all') && ...
      all(isfinite(object.common_core_samples), 'all') && ...
      all(isfinite(object.common_core_weights));
  end
  LOCAL_require(finite, [label ' field leaf is empty or nonfinite.']);
  fprintf(['FIELD_LEAF\t%s\tvertices=%d\ttriangles=%d\tedges=%d\t' ...
    'p2_dof=%d\tselected_objects=%d\tfinite=%d\n'], label, ...
    size(fields.points, 1), size(fields.triangles, 1), ...
    size(fields.edges, 1), size(fields.p2_points, 1), ...
    numel(fields.objects), finite);
end

%% ==================== Schema and parsing helpers ====================
% Missing duplicated metadata is reported as a caveat, not silently ignored.

function caveats = LOCAL_schema_caveats(preliminary_fields, final_fields, ...
    refinement, refinement_fields)
  caveats = {};
  field_required = {'spec', 'validation', 'selection', ...
    'spectrum_authority'};
  for index = 1:numel(field_required)
    if ~isfield(preliminary_fields, field_required{index})
      caveats{end + 1} = ['preliminary-fields.mat missing ' ...
        field_required{index}]; %#ok<AGROW>
    end
    if ~isfield(final_fields, field_required{index})
      caveats{end + 1} = ['final-fields.mat missing ' ...
        field_required{index}]; %#ok<AGROW>
    end
  end
  if ~isfield(preliminary_fields, 'lambda_pre') || ...
      ~isfield(preliminary_fields, 'k_pre')
    caveats{end + 1} = ...
      'preliminary-fields.mat missing lambda_pre/k_pre'; %#ok<AGROW>
  end
  if ~isfield(final_fields, 'lambda_ref') || ~isfield(final_fields, 'k_ref')
    caveats{end + 1} = 'final-fields.mat missing lambda_ref/k_ref'; %#ok<AGROW>
  end
  if ~isfield(preliminary_fields, 'interface_edges')
    caveats{end + 1} = ...
      'preliminary-fields.mat missing interface_edges'; %#ok<AGROW>
  end
  if ~isfield(refinement, 'spec')
    caveats{end + 1} = 'refinement-result.mat missing spec'; %#ok<AGROW>
  end
  if ~isfield(refinement_fields, 'spec') || ...
      ~isfield(refinement_fields, 'validation')
    caveats{end + 1} = ...
      'refinement-fields.mat missing spec/validation'; %#ok<AGROW>
  end
end

function lines = LOCAL_nonempty_lines(text)
  lines = regexp(text, '\r?\n', 'split');
  lines = lines(~cellfun(@isempty, lines));
end

function values = LOCAL_key_values(text)
  lines = LOCAL_nonempty_lines(text);
  values = struct();
  for index = 1:numel(lines)
    pair = strsplit(lines{index}, sprintf('\t'));
    LOCAL_require(numel(pair) == 2, 'A key/value artifact row is malformed.');
    values.(pair{1}) = pair{2};
  end
end

function text = LOCAL_text_list(value)
  if iscell(value)
    text = strjoin(value, '|');
  elseif isstring(value)
    text = strjoin(cellstr(value), '|');
  else
    text = char(value);
  end
end

function LOCAL_require(condition, message)
  if ~condition
    error('I4C:ArtifactReviewInvalid', '%s', message);
  end
end
