function result = check_s_resid(attempt)
%CHECK_S_RESID Compute the I3.1 compact-support strong-residual indicator.
% Purpose:
%   Re-evaluate the saved I2 candidate, reconstruct its explicit Fourier
%   field in the homogeneous empty center column, apply a fixed compact
%   cutoff, and compute a continuous strong-residual norm ratio.
% Input:
%   attempt - New append-only output tag. The reviewed tag is 'center-a1'.
% Output:
%   result  - Finite-input diagnostics, three Simpson levels, the computed
%             residual indicator, resource data, and strict claim limits.
% Main algorithm:
%   Use one frozen I2.1 seed and one saved-candidate point, form q=Dc*v1,
%   evaluate the cutoff field mode by mode, and exploit Fourier orthogonality
%   to reduce both continuous norms to one-dimensional Simpson quadrature.
% Based on:
%   research/projects/eig-apost/implementation/i3/design-3-1.md.
% Numerical goal:
%   Produce a computed continuous strong-residual estimator candidate. The
%   result is not a certified enclosure or a discrete-eigenvalue existence
%   claim because rigorous quadrature and the projected gap are unavailable.

  if nargin ~= 1 || ~strcmp(char(attempt),'center-a1')
    error('i31:Attempt','The reviewed attempt name is center-a1.');
  end
  here = fileparts(mfilename('fullpath'));
  output = fullfile(here,'output',char(attempt));
  if exist(output,'dir') || exist(output,'file')
    error('i31:OutputExists','Output already exists: %s.',output);
  end
  if exist('OCTAVE_VERSION','builtin') ~= 0
    error('i31:MATLABRequired','This experiment requires MATLAB.');
  end

  timer = tic;
  c = LOCAL_config();
  result = LOCAL_empty_result(char(attempt),c);
  peak_mib = 0;
  try
    rows = LOCAL_selectors();
    [seed,frame] = eval_i21('seed',c,rows);
    LOCAL_seed_gate(seed,frame,c);
    peak_mib = max(peak_mib,LOCAL_mib({seed,frame}));

    node = eval_i21('point',c.khat,c,frame);
    LOCAL_point_gate(node,frame,c);
    finite = LOCAL_finite_diagnostics(node,c);
    result.finite_input = finite;
    peak_mib = max(peak_mib,LOCAL_mib({seed,frame,node,finite}));
    if toc(timer) > c.soft_seconds
      error('i31:SoftTime','The soft time limit was reached before quadrature.');
    end

    levels = repmat(LOCAL_empty_level(),numel(c.simpson_intervals),1);
    for j = 1:numel(c.simpson_intervals)
      levels(j) = LOCAL_strong_norms(finite.q,node.beta_m,node.gamma,c, ...
        c.simpson_intervals(j));
      peak_mib = max(peak_mib,LOCAL_mib({seed,frame,node,finite})+ ...
        levels(j).workspace_mib);
    end
    if toc(timer) > c.soft_seconds
      error('i31:SoftTime','The soft time limit was reached before the scale check.');
    end
    scaled = LOCAL_strong_norms(c.scale_oracle*finite.q, ...
      node.beta_m,node.gamma,c,c.simpson_intervals(end));
    peak_mib = max(peak_mib,LOCAL_mib({seed,frame,node,finite})+ ...
      scaled.workspace_mib);

    result = LOCAL_qualify(result,finite,node,levels,scaled,c);
  catch ME
    failure = LOCAL_exception_failure(ME);
    result.first_failure = failure;
    if strcmp(failure.code,'FINITE_DISCRETE_INPUT_UNAVAILABLE') || ...
        strcmp(failure.code,'NONZERO_CONFORMING_FIELD_UNAVAILABLE')
      result.execution_pass = true;
      result.status = ['I3_1_',failure.code];
      result.scientific_outcome = failure.code;
    else
      result.execution_pass = false;
      result.status = 'I3_1_EXECUTION_UNAVAILABLE';
      result.scientific_outcome = 'UNAVAILABLE';
    end
  end

  result.elapsed_seconds = toc(timer);
  result.peak_active_mib = peak_mib;
  result.soft_time_exceeded = result.elapsed_seconds > c.soft_seconds;
  if result.elapsed_seconds > c.hard_seconds || peak_mib > c.memory_mib_max
    result.execution_pass = false;
    result.indicator_available = false;
    if isstruct(result.estimator) && isfield(result.estimator,'available')
      result.estimator.available = false;
    end
    result.status = 'I3_1_EXECUTION_UNAVAILABLE';
    result.scientific_outcome = 'UNAVAILABLE';
    result.first_failure = LOCAL_failure('EXECUTION_UNAVAILABLE','RESOURCE', ...
      'The hard time or active-object memory limit was exceeded.','i31:Resource');
  end

  if exist(output,'dir') || exist(output,'file')
    error('i31:OutputExists','Output appeared during the run: %s.',output);
  end
  mkdir(output);
  save(fullfile(output,'result.mat'),'result','-v7');
  LOCAL_report(fullfile(output,'report.md'),result);
end

%% ==================== Frozen inputs ====================
% These values define the reviewed fine-M48 point, cutoff, and numerical gates.

function c = LOCAL_config()
  c = struct('beta',0.5,'d',1.0,'R',0.2,'s',1.0,'X_L',-0.5, ...
    'X_R',0.5,'H',1.1,'proxy_dist',0.2,'M',48,'K',97, ...
    'kstar',1.8327703475952146,'khat',1.832770289108157, ...
    'simpson_intervals',[512,1024,2048], ...
    'simpson_relative_max',1e-10,'field_norm_min',1e-12, ...
    'scale_oracle',1e8*exp(1i*pi/7),'scale_relative_max',1e-12, ...
    'tau_k_pre',1e-6,'rho_G_pre',0.1, ...
    'soft_seconds',60,'hard_seconds',180,'memory_mib_max',256);
  c.level = struct('name','fine','ntot',256,'N_side',160, ...
    'N_top',160,'N_proxy_edge',80,'M_pw',32);
  c.expected = struct('proxy_rows',960,'proxy_columns',450, ...
    'proxy_shifted_rows',1920,'proxy_shifted_columns',450, ...
    'proxy_rank',260,'bie_order',512,'pencil_order',194, ...
    'chart_order',97,'adef_order',194,'graph_order',388);
  c.proxy_rank_ratio=1e-8; c.proxy_rank_gap_min=2;
  c.proxy_projector_repeat_tol=1e-10; c.proxy_rcond_min=1e-8;
  c.proxy_projected_tol=1e-11; c.proxy_full_residual_max=1e-5;
  c.proxy_shifted_residual_max=1e-5; c.proxy_seed_identity_tol=1e-12;
  c.branch_tol=1e-12; c.qz_residual_tol=1e-10; c.qz_overlap_min=0.9;
  c.cross_cluster_margin_min=100*c.K*eps; c.chart_margin_min=100*c.K*eps;
  c.chart_condition_eps_tol=1e-9; c.small_solve_residual_tol=1e3*c.K*eps;
  c.bie_rcond_min=1e-8; c.bie_residual_tol=1e-10;
  c.schur_tol=1e3*c.K*eps; c.dirichlet_rcond_min=1e-8;
  c.participation_min=1e-3; c.lift_residual_tol=1e-10;
end

function rows = LOCAL_selectors()
  rows.plus = [89 41 35 71 92 12 16 10 66 70 93 33 9 69 79 30 36 ...
    62 64 84 95 40 18 91 94 58 61 13 85 90 24 32 42 60 28 74 21 ...
    97 22 55 77 96 38 14 17 2 20 1 67 75 37 43 72 5 80 81 82 7 ...
    68 39 25 19 78 29 6 76 86 59 8 4 65 83 23 31 3 73 57 63 56 ...
    26 88 27 11 87 15 34 54 44 53 45 52 46 51 47 50 48 49];
  rows.minus = [162 132 117 174 103 124 134 140 173 194 101 172 186 ...
    120 167 168 170 178 189 100 153 180 192 110 118 121 125 169 175 ...
    176 185 119 160 164 179 108 113 114 131 165 171 183 193 111 128 ...
    133 139 159 181 190 191 106 129 157 163 135 116 127 155 177 102 ...
    104 126 130 137 156 184 109 138 187 115 136 154 161 166 158 123 ...
    98 122 105 188 112 152 99 182 107 151 141 150 142 149 143 148 ...
    144 147 145 146];
end

%% ==================== Finite input ====================
% These checks reproduce only the minimum I2 object and near-null diagnostics.

function LOCAL_seed_gate(seed,frame,c)
  ok = seed.k == c.kstar && seed.pass && all([seed.factors.pass]) && ...
    isequal(size(seed.R),[260,260]) && isequal(size(seed.Aqp),[512,512]) && ...
    isequal(size(seed.AdefD),[194,194]) && ...
    isequal(size(frame.Z0_plus),[194,97]) && ...
    isequal(size(frame.Z0_minus),[194,97]) && frame.proxy_chart.r == 260;
  if ~ok
    error('i31:FiniteInput','The frozen seed/frame health gate failed.');
  end
end

function LOCAL_point_gate(node,frame,c)
  ok = node.k == c.khat && strcmp(node.name,'fine') && ...
    node.spec.ntot == 256 && node.pass && node.plus.pass && ...
    node.minus.pass && node.branch_port.pass && node.branch_proxy.pass && ...
    node.cp.safe && node.cm.safe && all([node.factors.pass]) && ...
    isequal(node.H_plus_rows,frame.rows_plus) && ...
    isequal(node.H_minus_rows,frame.rows_minus) && ...
    isequal(size(node.AdefD),[194,194]) && ...
    isequal(size(node.AdefG),[388,388]) && ...
    all(isfinite(node.beta_m)) && all(isfinite(node.gamma));
  if ~ok
    error('i31:FiniteInput','The saved-candidate point health gate failed.');
  end
end

function out = LOCAL_finite_diagnostics(node,c)
  beta = node.beta_m(:); gamma = node.gamma(:);
  b = sqrt(1+abs(beta).^2);
  wr = repmat(sqrt(1./b),2,1);
  wc = repmat(1./sqrt(b+abs(gamma).^2./b),2,1);
  A = node.AdefD;
  B = wr.*A.*wc.';
  [U,S,V] = svd(B,'econ');
  singular = diag(S);
  u1 = U(:,end); v1 = V(:,end);
  q_raw = wc.*v1;
  q_norm = norm(q_raw);
  if ~isfinite(q_norm) || q_norm == 0 || any(~isfinite(q_raw))
    error('i31:NonzeroField','The physical near-null vector is unavailable.');
  end
  q = q_raw/q_norm;
  ell = wr.*u1;
  anorm = max(realmin,norm(A,2));
  right = norm(A*q_raw);
  left = norm(ell'*A);
  triplet = max(norm(B*v1-singular(end)*u1), ...
    norm(B'*u1-singular(end)*v1))/max(realmin,singular(1));
  physical = LOCAL_physical_summary(node,q,c);
  factor_rcond = [node.factors.rcond];
  factor_residual = [node.factors.residual];
  out = struct('pass',true,'Aphys_score',singular(end)/singular(1), ...
    'near_null_ratio',singular(end)/singular(end-1), ...
    'sigma_min',singular(end),'sigma_next',singular(end-1), ...
    'sigma_max',singular(1),'raw_right_residual',right, ...
    'raw_left_residual',left, ...
    'raw_right_backward',right/max(realmin,anorm*norm(q_raw)), ...
    'raw_left_backward',left/max(realmin,anorm*norm(ell)), ...
    'svd_triplet_residual',triplet,'q_raw_norm',q_norm,'q',q, ...
    'factor_names',{string({node.factors.name})}, ...
    'factor_rcond',factor_rcond,'factor_residual',factor_residual, ...
    'factor_pass',logical([node.factors.pass]), ...
    'minimum_factor_rcond',min(factor_rcond), ...
    'maximum_factor_residual',max(factor_residual), ...
    'physical',physical);
end

function out = LOCAL_physical_summary(node,q,c)
  K = c.K; I = eye(K); E = diag(node.phase(:));
  qL = q(1:K); qR = q(K+1:end);
  cminus = node.Dm\([I,E]*q);
  cplus = node.Dp\([E,I]*q);
  lift = [q;cminus;cplus];
  drow = [1:K,2*K+1:3*K];
  nrow = [K+1:2*K,3*K+1:4*K];
  Gd = node.AdefG(drow,:); Gn = node.AdefG(nrow,:);
  ed = norm(Gd*lift)/max(1,norm(Gd,2)*norm(lift));
  en = norm(Gn*lift-node.AdefD*q)/max(1, ...
    norm(Gn,2)*norm(lift)+norm(node.AdefD,2)*norm(q));
  kernel = norm(node.AdefG*lift)/max(1,norm(node.AdefG,'fro')*norm(lift));
  dL = qL+node.phase(:).*qR;
  dR = node.phase(:).*qL+qR;
  b = sqrt(1+abs(node.beta_m(:)).^2);
  wall = [sqrt(b).*dL;sqrt(b).*dR];
  [px,py] = ndgrid([-0.25,0,0.25],[-0.25,0,0.25]);
  probes = zeros(9,1);
  for j = 1:9
    basis = exp(1i*node.beta_m(:)*py(j))/sqrt(c.d);
    right = exp(1i*node.gamma(:)*(px(j)-c.X_L));
    left = exp(-1i*node.gamma(:)*(px(j)-c.X_R));
    probes(j) = sum((qL.*right+qR.*left).*basis);
  end
  out = struct('center_participation', ...
    min(norm(qL),norm(qR))/max(realmin,norm(q)), ...
    'graph_participation',min(norm(cminus),norm(cplus))/ ...
    max(realmin,norm(lift)),'dirichlet_defect',ed, ...
    'neumann_defect',en,'kernel_defect',kernel, ...
    'wall_participation',norm(wall)/max(realmin,norm(q)), ...
    'probe_participation',norm(probes)/max(realmin,norm(q)), ...
    'probe_field',probes);
end

%% ==================== Continuous strong residual ====================
% These helpers evaluate the fixed compact-support field and all residual terms.

function out = LOCAL_strong_norms(q,beta,gamma,c,N)
  x = linspace(c.X_L,c.X_R,N+1);
  q = q(:); beta = beta(:); gamma = gamma(:);
  qL = q(1:c.K); qR = q(c.K+1:end);
  eL = exp(1i*gamma.*(x-c.X_L));
  eR = exp(-1i*gamma.*(x-c.X_R));
  phi = qL.*eL+qR.*eR;
  phix = 1i*gamma.*qL.*eL-1i*gamma.*qR.*eR;
  chi = cos(pi*x).^2;
  chip = -pi*sin(2*pi*x);
  chipp = -2*pi^2*cos(2*pi*x);
  mu = c.khat^2;
  delta = beta.^2+gamma.^2-mu;
  r_second = -chipp.*phi;
  r_first = -2*chip.*phix;
  r_dispersion = chi.*(delta.*phi);
  residual = r_second+r_first+r_dispersion;

  field_norm = sqrt(max(0,LOCAL_simpson(sum(abs(chi.*phi).^2,1),c,N)));
  residual_norm = sqrt(max(0,LOCAL_simpson(sum(abs(residual).^2,1),c,N)));
  second_norm = sqrt(max(0,LOCAL_simpson(sum(abs(r_second).^2,1),c,N)));
  first_norm = sqrt(max(0,LOCAL_simpson(sum(abs(r_first).^2,1),c,N)));
  dispersion_norm = sqrt(max(0, ...
    LOCAL_simpson(sum(abs(r_dispersion).^2,1),c,N)));
  eta = residual_norm/max(realmin,field_norm);
  delta_scale = max([mu*ones(c.K,1),abs(beta).^2+abs(gamma).^2, ...
    realmin*ones(c.K,1)],[],2);
  info = whos;
  out = struct('N',N,'field_norm',field_norm, ...
    'residual_norm',residual_norm,'eta_lambda',eta, ...
    'cutoff_second_norm',second_norm,'cutoff_first_norm',first_norm, ...
    'dispersion_norm',dispersion_norm, ...
    'dispersion_fraction',dispersion_norm/max(realmin,residual_norm), ...
    'delta_m',delta,'normalized_dispersion_max', ...
    max(abs(delta)./delta_scale),'workspace_mib',sum([info.bytes])/2^20);
end

function value = LOCAL_simpson(samples,c,N)
  h = (c.X_R-c.X_L)/N;
  value = h/3*(samples(1)+samples(end)+ ...
    4*sum(samples(2:2:end-1))+2*sum(samples(3:2:end-2)));
  value = real(value);
end

function result = LOCAL_qualify(result,finite,node,levels,scaled,c)
  finest = levels(end); previous = levels(end-1);
  convergence = abs(finest.eta_lambda-previous.eta_lambda)/ ...
    max(abs(finest.eta_lambda),realmin);
  scale_defect = abs(scaled.eta_lambda-finest.eta_lambda)/ ...
    max(abs(finest.eta_lambda),realmin);
  values = [[levels.field_norm],[levels.residual_norm], ...
    [levels.eta_lambda],convergence,scale_defect];
  field_finite = isfinite(finest.field_norm);
  all_norms_finite = all(isfinite(values));
  nonzero = field_finite && finest.field_norm > c.field_norm_min;
  stable = all_norms_finite && convergence <= c.simpson_relative_max && ...
    scale_defect <= c.scale_relative_max;

  result.execution_pass = true;
  result.finite_input = finite;
  result.field = struct('q',finite.q,'beta_m',node.beta_m(:), ...
    'gamma_m',node.gamma(:),'cutoff','cos(pi*x)^2 on [-1/2,1/2], zero outside', ...
    'operator','A=-rho^{-1}Delta; rho=1 on support', ...
    'conforming_domain','H2 quasi-periodic compact support', ...
    'nonzero',nonzero);
  result.quadrature = struct('method','COMPOSITE_SIMPSON', ...
    'levels',levels,'finest_relative_change',convergence, ...
    'relative_change_max',c.simpson_relative_max, ...
    'scale_factor',c.scale_oracle,'scaled_finest',scaled, ...
    'scale_phase_relative_defect',scale_defect, ...
    'scale_phase_relative_max',c.scale_relative_max, ...
    'stable',stable);
  result.estimator = struct('available',false, ...
    'lambda_scale',finest.eta_lambda, ...
    'field_norm',finest.field_norm,'residual_norm',finest.residual_norm, ...
    'cutoff_second_norm',finest.cutoff_second_norm, ...
    'cutoff_first_norm',finest.cutoff_first_norm, ...
    'dispersion_norm',finest.dispersion_norm, ...
    'dispersion_fraction',finest.dispersion_fraction, ...
    'normalized_dispersion_max',finest.normalized_dispersion_max);

  if ~field_finite || ~all_norms_finite
    result.status = 'I3_1_CONTINUOUS_STRONG_RESIDUAL_UNRESOLVED';
    result.scientific_outcome = 'CONTINUOUS_STRONG_RESIDUAL_UNRESOLVED';
    result.first_failure = LOCAL_failure( ...
      'CONTINUOUS_STRONG_RESIDUAL_UNRESOLVED','QUADRATURE', ...
      'A computed field, residual, ratio, or comparison was nonfinite.','');
  elseif ~nonzero
    result.status = 'I3_1_NONZERO_CONFORMING_FIELD_UNAVAILABLE';
    result.scientific_outcome = 'NONZERO_CONFORMING_FIELD_UNAVAILABLE';
    result.first_failure = LOCAL_failure( ...
      'NONZERO_CONFORMING_FIELD_UNAVAILABLE','FIELD', ...
      'The compact-support field norm was unavailable or too small.','');
  elseif ~stable
    result.status = 'I3_1_CONTINUOUS_STRONG_RESIDUAL_UNRESOLVED';
    result.scientific_outcome = 'CONTINUOUS_STRONG_RESIDUAL_UNRESOLVED';
    result.first_failure = LOCAL_failure( ...
      'CONTINUOUS_STRONG_RESIDUAL_UNRESOLVED','QUADRATURE', ...
      'A Simpson refinement or phase/scale invariance gate failed.','');
  else
    result.status = 'I3_1_CONTINUOUS_STRONG_RESIDUAL_ESTIMATOR_CANDIDATE';
    result.scientific_outcome = ...
      'CONTINUOUS_STRONG_RESIDUAL_ESTIMATOR_CANDIDATE';
    result.indicator_available = true;
    result.estimator.available = true;
    result.first_failure = LOCAL_failure( ...
      'RELIABLE_NUMERICAL_ENCLOSURE_UNAVAILABLE','STRICT_UPGRADE', ...
      'The computed residual ratio has no reliable numerical enclosure.','');
  end
end

function out = LOCAL_empty_level()
  out = struct('N',0,'field_norm',NaN,'residual_norm',NaN, ...
    'eta_lambda',NaN,'cutoff_second_norm',NaN,'cutoff_first_norm',NaN, ...
    'dispersion_norm',NaN,'dispersion_fraction',NaN,'delta_m',[], ...
    'normalized_dispersion_max',NaN,'workspace_mib',0);
end

%% ==================== Result and report ====================
% The output keeps the computed indicator separate from every strict upgrade.

function result = LOCAL_empty_result(attempt,c)
  claims = struct('exact_strong_residual_theorem',true, ...
    'computed_value_is_certified',false, ...
    'reliable_numerical_enclosure',false, ...
    'projected_gap_established',false,'gap_containment','NOT_REACHED', ...
    'discrete_eigenvalue_existence','NOT_REACHED', ...
    'absolute_resolution','NOT_REACHED','gap_relative_resolution','NOT_REACHED', ...
    'unique_target','NOT_REACHED','continuous_error_bound',false);
  coverage = struct('saved_candidate',true,'center_fourier_field',true, ...
    'homogeneous_center_pde',true,'cutoff_volume_residual',true, ...
    'stored_gamma_dispersion',true,'lead_field',false,'bie_density',false, ...
    'halfguide_tail',false,'material_interface_reconstruction',false, ...
    'omitted_fourier_tail',false,'reliable_quadrature_enclosure',false);
  config = struct('khat',c.khat,'mu',c.khat^2,'kstar',c.kstar, ...
    'beta',c.beta,'d',c.d,'X_L',c.X_L,'X_R',c.X_R, ...
    'ntot',c.level.ntot,'M',c.M,'K',c.K, ...
    'simpson_intervals',c.simpson_intervals, ...
    'simpson_relative_max',c.simpson_relative_max, ...
    'field_norm_min',c.field_norm_min, ...
    'scale_relative_max',c.scale_relative_max, ...
    'tau_k_pre',c.tau_k_pre,'rho_G_pre',c.rho_G_pre, ...
    'soft_seconds',c.soft_seconds,'hard_seconds',c.hard_seconds, ...
    'memory_mib_max',c.memory_mib_max);
  result = struct('schema','TEP_I3_1_CENTER_STRONG_RESID_V1', ...
    'experiment_id','I3-CENTER-STRONG-RESID-V1', ...
    'design_id','I3.1-CENTER-STRONG-RESIDUAL-V1', ...
    'attempt',attempt,'status','I3_1_UNAVAILABLE', ...
    'execution_pass',false,'scientific_outcome','UNAVAILABLE', ...
    'indicator_available',false,'config',config,'finite_input',struct(), ...
    'field',struct(),'quadrature',struct(),'estimator',struct(), ...
    'coverage',coverage,'claims',claims, ...
    'strict_upgrade_blockers',{{'RELIABLE_NUMERICAL_ENCLOSURE_UNAVAILABLE', ...
      'PROJECTED_GAP_NOT_ESTABLISHED'}}, ...
    'first_failure',LOCAL_failure('NONE','NONE','',''), ...
    'elapsed_seconds',NaN,'peak_active_mib',NaN,'soft_time_exceeded',false, ...
    'retry_count',0,'retry_history','NONE', ...
    'command',['matlab -batch "addpath(fullfile(pwd,''test'',''i3'',', ...
      '''s-resid''),fullfile(pwd,''test'',''i2'',''k-count'')); ' ...
      'check_s_resid(''center-a1'');"'], ...
    'output_files',{{'result.mat','report.md'}}, ...
    'reads_git_docs_history_or_hashes',false);
end

function out = LOCAL_exception_failure(ME)
  if strcmp(ME.identifier,'i31:NonzeroField')
    code = 'NONZERO_CONFORMING_FIELD_UNAVAILABLE'; stage = 'FIELD';
  elseif strcmp(ME.identifier,'i31:FiniteInput') || ...
      startsWith(ME.identifier,'i21:') || startsWith(ME.identifier,'kready')
    code = 'FINITE_DISCRETE_INPUT_UNAVAILABLE'; stage = 'FINITE_INPUT';
  else
    code = 'EXECUTION_UNAVAILABLE'; stage = 'EXECUTION';
  end
  out = LOCAL_failure(code,stage,ME.message,ME.identifier);
end

function out = LOCAL_failure(code,stage,message,identifier)
  out = struct('code',code,'stage',stage,'message',message, ...
    'identifier',identifier);
end

function value = LOCAL_mib(objects)
  info = whos('objects');
  value = sum([info.bytes])/2^20;
end

function LOCAL_report(path,r)
  fid = fopen(path,'w');
  if fid < 0, error('i31:Report','Cannot create report.md.'); end
  cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
  fprintf(fid,'# I3.1 compact-support strong residual\n\n');
  fprintf(fid,'- Attempt: `%s`\n',r.attempt);
  fprintf(fid,'- Status: `%s`\n',r.status);
  fprintf(fid,'- Candidate: `%.17g`; lambda: `%.17g`\n', ...
    r.config.khat,r.config.mu);
  fprintf(fid,'- First unavailable condition: `%s`\n',r.first_failure.code);
  fprintf(fid,'- Runtime / active-object peak: `%.6f s` / `%.6f MiB`\n', ...
    r.elapsed_seconds,r.peak_active_mib);
  fprintf(fid,'- Retry count: `%d` (`%s`)\n\n',r.retry_count,r.retry_history);
  if r.execution_pass && isfield(r.estimator,'field_norm')
    fprintf(fid,'## Computed object\n\n');
    fprintf(fid,'- Field: `u_c=cos(pi*x)^2*u0` in the empty center column, zero outside.\n');
    fprintf(fid,'- Field norm: `%.17g`\n',r.estimator.field_norm);
    fprintf(fid,'- Strong residual norm: `%.17g`\n',r.estimator.residual_norm);
    fprintf(fid,'- Computed lambda-scale ratio: `%.17g`\n', ...
      r.estimator.lambda_scale);
    fprintf(fid,'- Cutoff second / first / dispersion norms: `%.6e / %.6e / %.6e`\n', ...
      r.estimator.cutoff_second_norm,r.estimator.cutoff_first_norm, ...
      r.estimator.dispersion_norm);
    fprintf(fid,'- Normalized stored-gamma dispersion: `%.6e`\n\n', ...
      r.estimator.normalized_dispersion_max);
    fprintf(fid,'| Simpson intervals | field norm | residual norm | eta_lambda |\n');
    fprintf(fid,'|---:|---:|---:|---:|\n');
    for j = 1:numel(r.quadrature.levels)
      x = r.quadrature.levels(j);
      fprintf(fid,'| %d | %.17g | %.17g | %.17g |\n', ...
        x.N,x.field_norm,x.residual_norm,x.eta_lambda);
    end
    fprintf(fid,'\n- Finest relative change: `%.6e` (limit `%.6e`).\n', ...
      r.quadrature.finest_relative_change,r.quadrature.relative_change_max);
    fprintf(fid,'- Phase/scale relative defect: `%.6e` (limit `%.6e`).\n\n', ...
      r.quadrature.scale_phase_relative_defect, ...
      r.quadrature.scale_phase_relative_max);
    p = r.finite_input.physical;
    fprintf(fid,'## Input quality\n\n');
    fprintf(fid,'- Aphys score / near-null ratio: `%.6e / %.6e`\n', ...
      r.finite_input.Aphys_score,r.finite_input.near_null_ratio);
    fprintf(fid,'- Raw right/left backward errors: `%.6e / %.6e`\n', ...
      r.finite_input.raw_right_backward,r.finite_input.raw_left_backward);
    fprintf(fid,'- Minimum factor rcond: `%.6e`\n', ...
      r.finite_input.minimum_factor_rcond);
    fprintf(fid,'- Graph D/N/kernel defects: `%.6e / %.6e / %.6e`\n\n', ...
      p.dirichlet_defect,p.neumann_defect,p.kernel_defect);
  end
  fprintf(fid,'## Interpretation\n\n');
  fprintf(fid,['The exact compact-support field construction acts on the continuous ', ...
    'self-adjoint operator, but the computed Simpson ratio has no reliable ', ...
    'numerical enclosure. The current sharp-disk projected essential gap is ', ...
    'also not established. Therefore no explicit interval is certified to ', ...
    'contain a continuous discrete eigenvalue, and no target mode or ', ...
    'continuous eigenvalue error is identified. The fixed one-cell cutoff ', ...
    'terms do not vanish under the I2 discretization refinements and may ', ...
    'make this baseline too wide for the preregistered resolution.\n']);
end
