function curve_contract = build_circle_contract_a1( ...
    artifact_path, curve_contract_path)
%BUILD_CIRCLE_CONTRACT_A1 Build the circle regression curve contract.
% Purpose:
%   Re-evaluate the geometry omitted from the frozen I3 certificate without
%   changing that artifact or resolving any spectral or BIE object.
% Input:
%   artifact_path       - Explicit path to fbie-a1-certificate.mat.
%   curve_contract_path - Explicit new MAT path under this experiment input.
% Output:
%   curve_contract      - Data-only 2*pi-periodic curve contract.
% Main algorithm:
%   Read only the frozen radius and wall positions, call
%   geom.construct_cont at the source and evaluation node counts, and attach
%   the exact circle strip and real-axis bounds used by the general evaluator.
% Notes:
%   This function is the circle-only adapter.  wall_tail_curve_a1 contains
%   no circle parametrization and consumes only the resulting general data.

[artifact_path, curve_contract_path] = LOCAL_paths( ...
  artifact_path, curve_contract_path);
loaded = load(artifact_path, 'staged');
if ~isfield(loaded, 'staged') || ...
    ~isfield(loaded.staged, 'certificate')
  error('I5CurveContract:ArtifactSchema', ...
    'The MAT file does not contain staged.certificate.');
end
z = loaded.staged.certificate;
required = {'source_attempt', 'R', 'X_L', 'X_R', 'eta_unit_256', ...
  'density_coordinate', 'global_normal_label'};
if ~all(isfield(z, required))
  error('I5CurveContract:ArtifactSchema', ...
    'The frozen certificate lacks a required circle regression field.');
end

circle_radius = double(z.R);
wall_left_x = double(z.X_L);
wall_right_x = double(z.X_R);
source_node_count = 0.5 * size(z.eta_unit_256, 1);
quadrature_node_count = 4096.0;
if source_node_count ~= 256.0 || circle_radius <= 0.0 || ...
    wall_left_x >= -circle_radius || wall_right_x <= circle_radius
  error('I5CurveContract:FrozenCircle', ...
    'The frozen circle geometry or density node count is unavailable.');
end

[source_contour, source_period] = geom.construct_cont( ...
  source_node_count, 'circle', 0, 0, circle_radius);
[evaluation_contour, evaluation_period] = geom.construct_cont( ...
  quadrature_node_count, 'circle', 0, 0, circle_radius);
if source_period ~= 2.0 * pi || evaluation_period ~= 2.0 * pi
  error('I5CurveContract:ParameterPeriod', ...
    'The circle adapter requires the project 2*pi parameter convention.');
end

center_x = 0.0;
left_center_distance = abs(wall_left_x - center_x);
right_center_distance = abs(wall_right_x - center_x);
minimum_center_distance = min(left_center_distance, right_center_distance);
strip_width = 0.5 * log(minimum_center_distance / circle_radius);
imaginary_coordinate_upper = circle_radius * sinh(strip_width);
tangent_coordinate_upper = circle_radius * cosh(strip_width);
left_strip_clearance_lower = left_center_distance - ...
  circle_radius * cosh(strip_width);
right_strip_clearance_lower = right_center_distance - ...
  circle_radius * cosh(strip_width);
left_real_clearance_lower = left_center_distance - circle_radius;
right_real_clearance_lower = right_center_distance - circle_radius;
if strip_width <= 0.0 || left_strip_clearance_lower <= 0.0 || ...
    right_strip_clearance_lower <= 0.0 || ...
    min(left_real_clearance_lower, right_real_clearance_lower) <= 0.0
  error('I5CurveContract:PositiveDistance', ...
    'The exact circle strip does not remain separated from both walls.');
end

curve_contract = struct( ...
  'schema', 'TEP_I5_WALL_CURVE_CONTRACT_V1', ...
  'geometry_kind', 'circle-regression', ...
  'parameter_period', 2.0 * pi, ...
  'source_node_count', source_node_count, ...
  'quadrature_node_count', quadrature_node_count, ...
  'source_contour', source_contour, ...
  'evaluation_contour', evaluation_contour, ...
  'wall_left_x', wall_left_x, ...
  'wall_right_x', wall_right_x, ...
  'density_coordinate', char(z.density_coordinate), ...
  'density_normal_label', char(z.global_normal_label), ...
  'orientation', ...
    'counter-clockwise; outward normal=(dy_dt,-dx_dt)/speed', ...
  'node_rule', 't_j=2*pi*j/N, j=0,...,N-1; no midpoint shift', ...
  'real_certificate', struct( ...
    'speed_upper', circle_radius, ...
    'left_clearance_lower', left_real_clearance_lower, ...
    'right_clearance_lower', right_real_clearance_lower), ...
  'strip_certificate', struct( ...
    'width', strip_width, ...
    'imag_x_upper', imaginary_coordinate_upper, ...
    'imag_y_upper', imaginary_coordinate_upper, ...
    'tangent_x_upper', tangent_coordinate_upper, ...
    'tangent_y_upper', tangent_coordinate_upper, ...
    'speed_upper', circle_radius, ...
    'left_clearance_lower', left_strip_clearance_lower, ...
    'right_clearance_lower', right_strip_clearance_lower, ...
    'curve_analytic', true, ...
    'speed_branch_analytic_and_nonzero', true, ...
    'bounds_mathematically_explicit', true), ...
  'adapter_metadata', struct( ...
    'center', [0.0, 0.0], ...
    'radius', circle_radius, ...
    'geometry_constructor', 'geom.construct_cont', ...
    'geometry_constructor_arguments', ...
      'N, circle, 0, 0, certificate.R', ...
    'strip_bound_source', 'exact circle complex-angle formulas'), ...
  'provenance', struct( ...
    'artifact_path', artifact_path, ...
    'artifact_variable', 'staged.certificate', ...
    'source_attempt', char(z.source_attempt), ...
    'eigenpair_solves', 0.0, ...
    'bie_density_solves', 0.0, ...
    'qz_decompositions', 0.0, ...
    'propagation_matrix_solves', 0.0));
save(curve_contract_path, 'curve_contract', '-v7.3');
end

%% ==================== Input and output paths ====================
% Paths are supplied explicitly and the contract target is append-only.

function [artifact_path, curve_contract_path] = LOCAL_paths( ...
    artifact_path, curve_contract_path)
if isstring(artifact_path) && isscalar(artifact_path)
  artifact_path = char(artifact_path);
end
if isstring(curve_contract_path) && isscalar(curve_contract_path)
  curve_contract_path = char(curve_contract_path);
end
if ~ischar(artifact_path) || isempty(artifact_path) || ...
    ~isfile(artifact_path)
  error('I5CurveContract:ArtifactPath', ...
    'artifact_path must name an existing MAT file.');
end
if ~ischar(curve_contract_path) || isempty(curve_contract_path)
  error('I5CurveContract:OutputPath', ...
    'curve_contract_path must be an explicit nonempty path.');
end
if isfile(curve_contract_path) || isfolder(curve_contract_path)
  error('I5CurveContract:OutputExists', ...
    'curve_contract_path must be a new append-only target.');
end
target_directory = fileparts(curve_contract_path);
if ~isempty(target_directory) && ~isfolder(target_directory)
  error('I5CurveContract:OutputDirectory', ...
    'The explicit curve-contract directory does not exist.');
end
end
