function result = wall_tail_curve_a1( ...
    artifact_path, curve_contract_path, output_path)
%WALL_TAIL_CURVE_A1 Evaluate the I5 wall bound for a parameterized curve.
% Purpose:
%   Apply the B_{Gamma_pm}-only finite-plus-tail algorithm to a frozen I3
%   state and a separate data-only 2*pi-periodic curve contract.
% Input:
%   artifact_path       - Explicit frozen I3 certificate MAT path.
%   curve_contract_path - Explicit curve-contract MAT path.
%   output_path         - Explicit result MAT path.
% Output:
%   result              - Ordinary floating-point finite/tail evaluation.
% Main algorithm:
%   Reconstruct finite density trigonometric polynomials, evaluate the
%   target-normal Rayleigh rows from curve position, tangent, speed, and
%   parameter measure, attach a general analytic-strip remainder, and close
%   the mode/cell tails with positive distance and full matrix powers.
% Based on:
%   research/projects/eig-apost/phase3-analysis/residual-bound/s-wall-tail.md
%   and research/projects/eig-apost/implementation/i5/design-5-1.md.
% Main changes:
%   Geometry-specific formulas are isolated in the supplied curve contract;
%   this evaluator contains no circular parametrization or Bessel formula.
% Numerical goal:
%   Regress the shape-general formulation on the frozen I5 circle instance.
% Notes:
%   Floating-point rounding is not enclosed.  The output is therefore
%   always labeled NON_CERTIFIED_ROUNDOFF_EXCLUDED.

timer = tic;
cfg = LOCAL_config();
[artifact_path, curve_contract_path, output_path] = LOCAL_paths( ...
  artifact_path, curve_contract_path, output_path);
[staged, curve_contract] = LOCAL_load_inputs( ...
  artifact_path, curve_contract_path);
z = staged.certificate;
z.d = double(z.d);
z.M = double(z.M);
z.K = double(z.K);
z.L = double(z.L);
raw_maps = staged.raw_maps;
LOCAL_validate_schema(z, raw_maps, curve_contract, output_path, cfg);

% --- stage 1: curve, branch, and density audits ---
curve = LOCAL_curve_data(curve_contract, z, cfg);
modal = LOCAL_modal_data(z, cfg);
density = LOCAL_density_data(z, curve);

% --- stage 2: general curve rows and analytic remainders ---
curve_flux = LOCAL_curve_flux_rows(z, curve, density, modal);
rows = LOCAL_wall_rows(z, curve, density, modal, curve_flux);
side_index_audit = LOCAL_side_index_audit( ...
  z, raw_maps, modal, rows, curve_flux, curve, cfg);
if ~curve.audit.pass || ~modal.audit.pass || ~density.audit.pass || ...
    ~side_index_audit.structural_pass || ...
    ~side_index_audit.ordinary_regression_pass
  error('I5WallCurve:Audit', ...
    'A curve, branch, density, side, sign, or index audit failed.');
end

% --- stage 3: full-matrix propagation and positive-distance tails ---
propagation_minus = LOCAL_block_certificate(z.Pminus, cfg.block_length);
propagation_plus = LOCAL_block_certificate(z.Pplus, cfg.block_length);
if ~propagation_minus.contraction_pass || ...
    ~propagation_plus.contraction_pass
  error('I5WallCurve:BlockPower', ...
    'An ordinary full-matrix block-power contraction is unavailable.');
end
density_constants = LOCAL_density_constants(z, curve, density);
high_mode = LOCAL_high_mode_constants( ...
  z, curve, density_constants, modal, cfg);

% --- stage 4: disjoint finite and omitted pieces ---
finite = LOCAL_finite_part(z, modal, rows, cfg);
tail = LOCAL_tail_part(z, modal, rows, finite, high_mode, ...
  propagation_minus, propagation_plus);
coefficient_enclosures = struct( ...
  'wall_orders', modal.wall_orders, ...
  'wall_weights', modal.wall_weights, ...
  'ell_plus_tilde', rows.ell_plus_tilde, ...
  'ell_plus_error', rows.ell_plus_error, ...
  'ell_minus_tilde', rows.ell_minus_tilde, ...
  'ell_minus_error', rows.ell_minus_error, ...
  'singleton_plus_tilde', rows.singleton_plus_tilde, ...
  'singleton_plus_error', rows.singleton_plus_error, ...
  'singleton_minus_tilde', rows.singleton_minus_tilde, ...
  'singleton_minus_error', rows.singleton_minus_error, ...
  'strip_remainder_records', rows.remainder_records, ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
quadratic_bound = sqrt(finite.finite_squared + tail.tail_squared);
triangle_bound = sqrt(finite.finite_squared) + sqrt(tail.tail_squared);
if any(~isfinite([quadratic_bound, triangle_bound])) || ...
    any([quadratic_bound, triangle_bound] < 0.0)
  error('I5WallCurve:Assembly', ...
    'The artificial-wall finite/tail assembly is invalid.');
end

workspace = whos;
workspace_proxy_mib = sum([workspace.bytes]) / 2.0^20;
result = struct( ...
  'status', 'COMPLETE', ...
  'claim_scope', 'B_GAMMA_PM_ONLY', ...
  'method', 'SHAPE_GENERAL_PARAMETER_CURVE', ...
  'certification_label', cfg.roundoff_label, ...
  'roundoff_excluded', true, ...
  'reliability_certified', false, ...
  'quadratic_bound', quadratic_bound, ...
  'triangle_bound', triangle_bound, ...
  'finite', finite, ...
  'tail', tail, ...
  'coefficient_enclosures', coefficient_enclosures, ...
  'config', cfg, ...
  'curve_audit', curve.audit, ...
  'branch_audit', modal.audit, ...
  'density_audit', density.audit, ...
  'side_index_audit', side_index_audit, ...
  'propagation_minus', propagation_minus, ...
  'propagation_plus', propagation_plus, ...
  'density_constants', density_constants, ...
  'high_mode', high_mode, ...
  'evaluation', curve_flux.audit, ...
  'theorem_gate', struct( ...
    'shape_general_finite_bundle_ordinary_complete', true, ...
    'outward_rounding_gate_closed', false, ...
    'reported_number_reliable', false), ...
  'provenance', struct( ...
    'artifact_path', artifact_path, ...
    'curve_contract_path', curve_contract_path, ...
    'artifact_variable', 'staged', ...
    'curve_contract_variable', 'curve_contract', ...
    'curve_contract_schema', curve_contract.schema, ...
    'geometry_kind', curve_contract.geometry_kind, ...
    'source_density_transform', ...
      'fftshift(fft(native_samples))/N; no midpoint phase', ...
    'stored_raw_maps_used_in_bound', false, ...
    'circle_special_formula_used_in_core', false, ...
    'eigenpair_solves', 0.0, ...
    'bie_density_solves', 0.0, ...
    'qz_decompositions', 0.0, ...
    'propagation_matrix_solves', 0.0), ...
  'resource', struct( ...
    'elapsed_seconds_before_save', toc(timer), ...
    'workspace_proxy_mib_before_save', workspace_proxy_mib));
save(output_path, 'result', '-v7.3');
end

%% ==================== Fixed experiment contract ====================
% These resolution values match the accepted circle-special I5 evaluation.

function cfg = LOCAL_config()
cfg = struct( ...
  'mode_cutoff', 256.0, ...
  'cell_cutoff', 32.0, ...
  'block_length', 32.0, ...
  'quadrature_nodes', 4096.0, ...
  'trace_half_width', 0.5, ...
  'ordinary_identity_tolerance', 4096.0 * eps, ...
  'roundoff_label', 'NON_CERTIFIED_ROUNDOFF_EXCLUDED');
end

function [artifact_path, curve_contract_path, output_path] = LOCAL_paths( ...
    artifact_path, curve_contract_path, output_path)
artifact_path = LOCAL_char_path(artifact_path, 'artifact_path');
curve_contract_path = LOCAL_char_path( ...
  curve_contract_path, 'curve_contract_path');
output_path = LOCAL_char_path(output_path, 'output_path');
if ~isfile(artifact_path)
  error('I5WallCurve:ArtifactPath', ...
    'artifact_path must name an existing MAT file.');
end
if ~isfile(curve_contract_path)
  error('I5WallCurve:CurveContractPath', ...
    'curve_contract_path must name an existing MAT file.');
end
output_directory = fileparts(output_path);
if ~isempty(output_directory) && ~isfolder(output_directory)
  error('I5WallCurve:OutputDirectory', ...
    'The explicit output directory does not exist.');
end
if isfolder(output_path)
  error('I5WallCurve:OutputPath', ...
    'output_path names a directory rather than a MAT file.');
end
end

function value = LOCAL_char_path(value, argument_name)
if isstring(value) && isscalar(value)
  value = char(value);
end
if ~ischar(value) || isempty(value)
  error('I5WallCurve:Path', '%s must be an explicit nonempty path.', ...
    argument_name);
end
end

function [staged, curve_contract] = LOCAL_load_inputs( ...
    artifact_path, curve_contract_path)
loaded_artifact = load(artifact_path, 'staged');
loaded_curve = load(curve_contract_path, 'curve_contract');
if ~isfield(loaded_artifact, 'staged') || ...
    ~isstruct(loaded_artifact.staged) || ...
    ~all(isfield(loaded_artifact.staged, {'certificate', 'raw_maps'}))
  error('I5WallCurve:ArtifactSchema', ...
    'The MAT file lacks staged.certificate or staged.raw_maps.');
end
if ~isfield(loaded_curve, 'curve_contract') || ...
    ~isstruct(loaded_curve.curve_contract)
  error('I5WallCurve:CurveContractSchema', ...
    'The curve MAT file lacks curve_contract.');
end
staged = loaded_artifact.staged;
curve_contract = loaded_curve.curve_contract;
end

function LOCAL_validate_schema(z, raw_maps, contract, output_path, cfg)
required = {'khat', 'gamma', 'mu_h', 'beta', 'd', 'X_L', 'X_R', ...
  'L', 'M', 'K', 'eta_unit_256', 'xi_left_unit_512', ...
  'xi_right_unit_512', 'wall_orders_512', 'q_center', 'Dplus', ...
  'Dminus', 'Gplus', 'Gminus', 'Pplus', 'Pminus', 'cplus', ...
  'cminus', 'branch_port', 'center_wall_jumps', ...
  'density_coordinate', 'global_normal_label'};
if ~all(isfield(z, required))
  error('I5WallCurve:ArtifactSchema', ...
    'The frozen certificate is missing a required field.');
end
raw_required = {'QLplus', 'QRplus', 'QLminus', 'QRminus', ...
  'Jplus', 'Jminus', 'wall_flux_left_unit_512', ...
  'wall_flux_right_unit_512'};
if ~all(isfield(raw_maps, raw_required))
  error('I5WallCurve:ArtifactSchema', ...
    'The frozen raw-map bundle is missing an audit field.');
end
center_required = {'center_left_global_dx', 'center_right_global_dx', ...
  'left_coefficients', 'right_coefficients'};
if ~all(isfield(z.center_wall_jumps, center_required))
  error('I5WallCurve:ArtifactSchema', ...
    'The frozen center/first wall record is incomplete.');
end
contract_required = {'schema', 'geometry_kind', 'parameter_period', ...
  'source_node_count', 'quadrature_node_count', 'source_contour', ...
  'evaluation_contour', 'wall_left_x', 'wall_right_x', ...
  'density_coordinate', 'density_normal_label', 'orientation', ...
  'node_rule', 'real_certificate', 'strip_certificate', ...
  'adapter_metadata', 'provenance'};
if ~all(isfield(contract, contract_required)) || ...
    ~strcmp(contract.schema, 'TEP_I5_WALL_CURVE_CONTRACT_V1')
  error('I5WallCurve:CurveContractSchema', ...
    'The supplied curve contract has the wrong schema.');
end
real_required = {'speed_upper', 'left_clearance_lower', ...
  'right_clearance_lower'};
strip_required = {'width', 'imag_x_upper', 'imag_y_upper', ...
  'tangent_x_upper', 'tangent_y_upper', 'speed_upper', ...
  'left_clearance_lower', 'right_clearance_lower', ...
  'curve_analytic', 'speed_branch_analytic_and_nonzero', ...
  'bounds_mathematically_explicit'};
if ~all(isfield(contract.real_certificate, real_required)) || ...
    ~all(isfield(contract.strip_certificate, strip_required))
  error('I5WallCurve:CurveContractSchema', ...
    'A real-axis or strip certificate field is missing.');
end
K = double(z.K);
shape_pass = isequal(size(z.eta_unit_256), [512, 2 * K]) && ...
  isequal(size(z.xi_left_unit_512), [512, 2 * K]) && ...
  isequal(size(z.xi_right_unit_512), [512, 2 * K]) && ...
  isequal(size(z.Gplus), [2 * K, K]) && ...
  isequal(size(z.Gminus), [2 * K, K]) && ...
  isequal(size(z.Pplus), [K, K]) && ...
  isequal(size(z.Pminus), [K, K]) && ...
  isequal(size(z.cplus), [K, 1]) && ...
  isequal(size(z.cminus), [K, 1]) && ...
  isequal(size(z.q_center), [2 * K, 1]);
if ~shape_pass
  error('I5WallCurve:ArtifactShape', ...
    'A frozen state or density map has the wrong shape.');
end
if double(z.M) > cfg.mode_cutoff || cfg.mode_cutoff < 256.0 || ...
    cfg.cell_cutoff < 0.0 || cfg.block_length < 1.0 || ...
    mod(cfg.quadrature_nodes, 2.0) ~= 0.0
  error('I5WallCurve:Configuration', ...
    'The fixed modal, cell, block, or quadrature configuration is invalid.');
end
if z.X_R - z.X_L ~= z.L || z.L <= 0.0 || ...
    z.gamma ~= z.mu_h || z.gamma <= 0.0 || z.khat <= 0.0 || ...
    z.d <= 0.0
  error('I5WallCurve:PhysicalScalars', ...
    'A frozen wall, physical, or shifted-norm scalar is invalid.');
end
if isfile(output_path)
  error('I5WallCurve:OutputExists', ...
    'The result target already exists.');
end
end

%% ==================== Parameterized curve contract ====================
% The core consumes positions and derivatives, never a shape formula.

function curve = LOCAL_curve_data(contract, z, cfg)
source_count = double(contract.source_node_count);
quadrature_count = double(contract.quadrature_node_count);
source_contour = double(contract.source_contour);
evaluation_contour = double(contract.evaluation_contour);
if contract.parameter_period ~= 2.0 * pi || source_count ~= 256.0 || ...
    quadrature_count ~= cfg.quadrature_nodes || ...
    ~isequal(size(source_contour), [6, source_count]) || ...
    ~isequal(size(evaluation_contour), [6, quadrature_count])
  error('I5WallCurve:CurveGrid', ...
    'The curve grids do not match the fixed 2*pi parameter contract.');
end
if contract.wall_left_x ~= z.X_L || contract.wall_right_x ~= z.X_R || ...
    ~strcmp(strtrim(contract.density_coordinate), ...
      strtrim(z.density_coordinate)) || ...
    ~strcmp(strtrim(contract.density_normal_label), ...
      strtrim(z.global_normal_label))
  error('I5WallCurve:CurveArtifactPair', ...
    'The curve contract does not describe the frozen artifact walls or density.');
end

x = evaluation_contour(1, :).';
dx_dt = evaluation_contour(2, :).';
y = evaluation_contour(4, :).';
dy_dt = evaluation_contour(5, :).';
speed = sqrt(dx_dt.^2 + dy_dt.^2);
normal_x = dy_dt ./ speed;
normal_y = -dx_dt ./ speed;
finite_pass = all(isfinite([source_contour(:); evaluation_contour(:); ...
  speed; normal_x; normal_y])) && all(speed > 0.0);
orientation_area = 0.5 * contract.parameter_period / quadrature_count * ...
  sum(x .* dy_dt - y .* dx_dt);
orientation_pass = orientation_area > 0.0 && strcmp( ...
  contract.orientation, ...
  'counter-clockwise; outward normal=(dy_dt,-dx_dt)/speed');
normal_unit_defect = max(abs(normal_x.^2 + normal_y.^2 - 1.0));

grid_ratio = quadrature_count / source_count;
grid_nested = grid_ratio == floor(grid_ratio);
if grid_nested
  shared_indices = 1.0:grid_ratio:quadrature_count;
  grid_defect = LOCAL_relative_difference( ...
    source_contour, evaluation_contour(:, shared_indices));
else
  grid_defect = Inf;
end

real_certificate = contract.real_certificate;
strip_certificate = contract.strip_certificate;
left_clearance_nodes = min(x - z.X_L);
right_clearance_nodes = min(z.X_R - x);
speed_upper_nodes = max(speed);
ordinary_slack = cfg.ordinary_identity_tolerance * max(1.0, ...
  max(abs([z.X_L, z.X_R, x.'])));
real_pass = real_certificate.speed_upper > 0.0 && ...
  real_certificate.left_clearance_lower > 0.0 && ...
  real_certificate.right_clearance_lower > 0.0 && ...
  speed_upper_nodes <= real_certificate.speed_upper + ordinary_slack && ...
  left_clearance_nodes + ordinary_slack >= ...
    real_certificate.left_clearance_lower && ...
  right_clearance_nodes + ordinary_slack >= ...
    real_certificate.right_clearance_lower;
strip_values = [strip_certificate.width, ...
  strip_certificate.imag_x_upper, strip_certificate.imag_y_upper, ...
  strip_certificate.tangent_x_upper, ...
  strip_certificate.tangent_y_upper, strip_certificate.speed_upper, ...
  strip_certificate.left_clearance_lower, ...
  strip_certificate.right_clearance_lower];
strip_pass = all(isfinite(strip_values)) && ...
  strip_certificate.width > 0.0 && ...
  all(strip_values(2:end) > 0.0) && ...
  logical(strip_certificate.curve_analytic) && ...
  logical(strip_certificate.speed_branch_analytic_and_nonzero) && ...
  logical(strip_certificate.bounds_mathematically_explicit);
audit = struct( ...
  'schema_pass', true, ...
  'finite_regular_curve_pass', finite_pass, ...
  'counter_clockwise_orientation_pass', orientation_pass, ...
  'orientation_area', orientation_area, ...
  'normal_unit_maximum_defect', normal_unit_defect, ...
  'source_evaluation_grid_nested', grid_nested, ...
  'source_evaluation_grid_relative_defect', grid_defect, ...
  'real_certificate_pass', real_pass, ...
  'strip_certificate_pass', strip_pass, ...
  'left_clearance_at_nodes', left_clearance_nodes, ...
  'right_clearance_at_nodes', right_clearance_nodes, ...
  'maximum_speed_at_nodes', speed_upper_nodes, ...
  'ordinary_identity_tolerance', cfg.ordinary_identity_tolerance, ...
  'pass', finite_pass && orientation_pass && ...
    normal_unit_defect <= cfg.ordinary_identity_tolerance && ...
    grid_nested && grid_defect <= cfg.ordinary_identity_tolerance && ...
    real_pass && strip_pass);
curve = struct( ...
  'parameter_period', double(contract.parameter_period), ...
  'source_node_count', source_count, ...
  'quadrature_node_count', quadrature_count, ...
  'x', x, ...
  'y', y, ...
  'dx_dt', dx_dt, ...
  'dy_dt', dy_dt, ...
  'speed', speed, ...
  'normal_x', normal_x, ...
  'normal_y', normal_y, ...
  'real_certificate', real_certificate, ...
  'strip_certificate', strip_certificate, ...
  'audit', audit);
end

%% ==================== Rayleigh branch and density ====================
% The branch and source-density FFT follow the frozen artifact conventions.

function modal = LOCAL_modal_data(z, cfg)
k_outer = double(z.khat);
mu_shift = double(z.gamma);
beta_bloch = double(z.beta);
period_y = double(z.d);
wall_orders = (-cfg.mode_cutoff:cfg.mode_cutoff).';
transverse_wavenumber = beta_bloch + 2.0 * pi * wall_orders / period_y;
branch_radicand = k_outer^2 - transverse_wavenumber.^2;
rayleigh_wavenumber = sqrt(complex(branch_radicand));
flip = imag(rayleigh_wavenumber) < 0.0 | ...
  (imag(rayleigh_wavenumber) == 0.0 & ...
  real(rayleigh_wavenumber) < 0.0);
rayleigh_wavenumber(flip) = -rayleigh_wavenumber(flip);
exact_wood = any(branch_radicand == 0.0);
propagating = branch_radicand > 0.0;
evanescent = branch_radicand < 0.0;
outgoing_pass = all(real(rayleigh_wavenumber(propagating)) > 0.0) && ...
  all(imag(rayleigh_wavenumber(evanescent)) > 0.0);

stored_orders = (-double(z.M):double(z.M)).';
[present, retained_indices] = ismember(stored_orders, wall_orders);
if ~all(present)
  error('I5WallCurve:BranchEmbedding', ...
    'A frozen branch order is absent from the finite wall range.');
end
branch_defect = LOCAL_relative_difference( ...
  rayleigh_wavenumber(retained_indices), z.branch_port.gamma_m(:));
transverse_defect = LOCAL_relative_difference( ...
  transverse_wavenumber(retained_indices), z.branch_port.beta_m(:));
stored_branch_pass = ...
  branch_defect <= cfg.ordinary_identity_tolerance && ...
  transverse_defect <= cfg.ordinary_identity_tolerance;
q0 = 2.0 * pi / period_y;
omitted_alpha_lower = q0 * (cfg.mode_cutoff + 1.0) - abs(beta_bloch);
omitted_evanescent_pass = omitted_alpha_lower > k_outer;
support_pass = isequal(double(z.wall_orders_512(:)), ...
  (-256.0:255.0).') && cfg.mode_cutoff >= max(256.0, double(z.M));
lambda_modes = sqrt(transverse_wavenumber.^2 + mu_shift);
wall_weights = 2.0 * lambda_modes .* ...
  tanh(cfg.trace_half_width * lambda_modes);
weight_pass = all(isfinite(wall_weights) & wall_weights > 0.0);
audit = struct( ...
  'exact_wood', exact_wood, ...
  'outgoing_branch_pass', outgoing_pass, ...
  'stored_branch_relative_defect', branch_defect, ...
  'stored_transverse_wavenumber_relative_defect', transverse_defect, ...
  'stored_branch_pass', stored_branch_pass, ...
  'omitted_alpha_lower', omitted_alpha_lower, ...
  'omitted_modes_strictly_evanescent', omitted_evanescent_pass, ...
  'finite_support_pass', support_pass, ...
  'wall_weight_pass', weight_pass, ...
  'pass', ~exact_wood && outgoing_pass && stored_branch_pass && ...
    omitted_evanescent_pass && support_pass && weight_pass);
modal = struct( ...
  'wall_orders', wall_orders, ...
  'transverse_wavenumber', transverse_wavenumber, ...
  'branch_radicand', branch_radicand, ...
  'rayleigh_wavenumber', rayleigh_wavenumber, ...
  'propagating', propagating, ...
  'evanescent', evanescent, ...
  'lambda_modes', lambda_modes, ...
  'wall_weights', wall_weights, ...
  'audit', audit);
end

function density = LOCAL_density_data(z, curve)
native_count = curve.source_node_count;
density_orders = (-native_count / 2.0:native_count / 2.0 - 1.0).';
tau_native = z.eta_unit_256(1:native_count, :);
single_layer_density_native = z.eta_unit_256(native_count + 1.0:end, :);
tau_coeff_map = fftshift(fft(tau_native, [], 1), 1) / native_count;
single_layer_density_coeff_map = fftshift( ...
  fft(single_layer_density_native, [], 1), 1) / native_count;
tau_parseval = LOCAL_parseval_defect(tau_native, tau_coeff_map);
single_layer_density_parseval = LOCAL_parseval_defect( ...
  single_layer_density_native, single_layer_density_coeff_map);
finite_pass = all(isfinite([tau_coeff_map(:); ...
  single_layer_density_coeff_map(:)]));
audit = struct( ...
  'source_node_count', native_count, ...
  'source_orders', density_orders, ...
  'transform', 'fftshift(fft(native_samples))/N', ...
  'midpoint_phase_applied', false, ...
  'tau_parseval_relative_defect', tau_parseval, ...
  'single_layer_density_parseval_relative_defect', ...
    single_layer_density_parseval, ...
  'density_coordinate_label', z.density_coordinate, ...
  'single_layer_density_label_pass', strcmp( ...
    strtrim(z.density_coordinate), '[tau;zeta], zeta=-sigma'), ...
  'pass', finite_pass && ...
    max(tau_parseval, single_layer_density_parseval) <= ...
    4096.0 * eps && strcmp(strtrim(z.density_coordinate), ...
    '[tau;zeta], zeta=-sigma'));
density = struct( ...
  'density_orders', density_orders, ...
  'tau_coeff_map', tau_coeff_map, ...
  'single_layer_density_coeff_map', ...
    single_layer_density_coeff_map, ...
  'audit', audit);
end

function defect = LOCAL_parseval_defect(native_values, coefficient_values)
native_energy = norm(native_values, 'fro')^2 / size(native_values, 1);
coefficient_energy = norm(coefficient_values, 'fro')^2;
defect = abs(native_energy - coefficient_energy) / ...
  max([realmin, native_energy, coefficient_energy]);
end

%% ==================== General curve and flat-wall rows ====================
% The finite curve action uses position, tangent, speed, and parameter measure.

function curve_flux = LOCAL_curve_flux_rows(z, curve, density, modal)
theta = curve.parameter_period * ...
  (0.0:curve.quadrature_node_count - 1.0).' / ...
  curve.quadrature_node_count;
density_basis = exp(1i * theta * density.density_orders.');
tau_values = density_basis * density.tau_coeff_map;
single_layer_density_values = density_basis * ...
  density.single_layer_density_coeff_map;
clear density_basis

[curve_flux_left, left_kernel_mib] = LOCAL_curve_side_rows( ...
  z, curve, modal, tau_values, single_layer_density_values, ...
  z.X_L, -1.0);
[curve_flux_right, right_kernel_mib] = LOCAL_curve_side_rows( ...
  z, curve, modal, tau_values, single_layer_density_values, ...
  z.X_R, 1.0);
identity_state = eye(size(density.tau_coeff_map, 2));
left_q_error = LOCAL_strip_remainder( ...
  z, curve, density, modal, identity_state, 'left');
right_q_error = LOCAL_strip_remainder( ...
  z, curve, density, modal, identity_state, 'right');
audit = struct( ...
  'quadrature_nodes', curve.quadrature_node_count, ...
  'strip_width', curve.strip_certificate.width, ...
  'left_q_error_max', max(left_q_error.display), ...
  'right_q_error_max', max(right_q_error.display), ...
  'left_q_error_log_max', max(left_q_error.log_value), ...
  'right_q_error_log_max', max(right_q_error.log_value), ...
  'underflow_floor_used', left_q_error.underflow_floor_used || ...
    right_q_error.underflow_floor_used, ...
  'kernel_workspace_proxy_mib', max(left_kernel_mib, right_kernel_mib), ...
  'finite', all(isfinite([curve_flux_left(:); curve_flux_right(:)])), ...
  'general_curve_formula', true, ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
if ~audit.finite
  error('I5WallCurve:CurveRows', ...
    'A finite curve-to-wall coefficient row is nonfinite.');
end
curve_flux = struct( ...
  'left', curve_flux_left, ...
  'right', curve_flux_right, ...
  'left_q_error', left_q_error, ...
  'right_q_error', right_q_error, ...
  'audit', audit);
end

function [curve_rows, workspace_proxy_mib] = LOCAL_curve_side_rows( ...
    z, curve, modal, tau_values, single_layer_density_values, ...
    wall_x, wall_side_sign)
travel = wall_side_sign * (wall_x - curve.x);
if any(travel <= 0.0)
  error('I5WallCurve:PositiveDistance', ...
    'The parameterized source curve crosses or touches a target wall.');
end
phase = exp(1i * travel * modal.rayleigh_wavenumber.' - ...
  1i * curve.y * modal.transverse_wavenumber.');
derivative_measure = 1i * ( ...
  wall_side_sign * curve.dy_dt * modal.rayleigh_wavenumber.' - ...
  curve.dx_dt * modal.transverse_wavenumber.');
single_layer_measure = curve.speed .* single_layer_density_values;
quadrature_weight = curve.parameter_period / curve.quadrature_node_count;
scale = quadrature_weight / (2.0 * sqrt(z.d));
curve_rows = scale * ( ...
  (phase .* derivative_measure).' * tau_values + ...
  phase.' * single_layer_measure);
workspace = whos;
workspace_proxy_mib = sum([workspace.bytes]) / 2.0^20;
end

function remainder = LOCAL_strip_remainder( ...
    z, curve, density, modal, state_map, wall_side)
tau_composed = density.tau_coeff_map * state_map;
single_layer_density_composed = ...
  density.single_layer_density_coeff_map * state_map;
strip = curve.strip_certificate;
order_growth = exp(abs(density.density_orders) * strip.width);
D_tau = sum(LOCAL_row_norms(tau_composed) .* order_growth);
D_single_layer_density = sum( ...
  LOCAL_row_norms(single_layer_density_composed) .* order_growth);
if strcmp(wall_side, 'left')
  strip_clearance = strip.left_clearance_lower;
elseif strcmp(wall_side, 'right')
  strip_clearance = strip.right_clearance_lower;
else
  error('I5WallCurve:WallSide', 'wall_side must be left or right.');
end

abs_gamma = abs(modal.rayleigh_wavenumber);
abs_transverse = abs(modal.transverse_wavenumber);
log_phase_bound = abs_gamma * strip.imag_x_upper + ...
  abs_transverse * strip.imag_y_upper;
kappa_modes = imag(modal.rayleigh_wavenumber(modal.evanescent));
log_phase_bound(modal.evanescent) = ...
  -kappa_modes * strip_clearance + ...
  abs_transverse(modal.evanescent) * strip.imag_y_upper;
derivative_density_bound = ( ...
  abs_gamma * strip.tangent_y_upper + ...
  abs_transverse * strip.tangent_x_upper) * D_tau + ...
  strip.speed_upper * D_single_layer_density;
if any(derivative_density_bound <= 0.0) || ...
    any(~isfinite(derivative_density_bound))
  error('I5WallCurve:StripDensity', ...
    'A general-curve strip integrand bound is invalid.');
end
log_integrand_bound = -log(2.0 * sqrt(z.d)) + ...
  log_phase_bound + log(derivative_density_bound);
denominator_argument = strip.width * curve.quadrature_node_count;
log_denominator = denominator_argument + ...
  log1p(-exp(-denominator_argument));
log_value = log(4.0 * pi) + log_integrand_bound - log_denominator;
[display_value, underflow_floor_used] = LOCAL_exp_display(log_value);
remainder = struct( ...
  'display', display_value, ...
  'log_value', log_value, ...
  'D_tau', D_tau, ...
  'D_single_layer_density', D_single_layer_density, ...
  'wall_side', wall_side, ...
  'underflow_floor_used', underflow_floor_used, ...
  'shape_general_conservative_bound', true);
end

function rows = LOCAL_wall_rows(z, curve, density, modal, curve_flux)
xi_left = LOCAL_embed_orders( ...
  z.xi_left_unit_512, double(z.wall_orders_512(:)), modal.wall_orders);
xi_right = LOCAL_embed_orders( ...
  z.xi_right_unit_512, double(z.wall_orders_512(:)), modal.wall_orders);
wall_phase = exp(1i * modal.rayleigh_wavenumber * z.L);
flat_flux_left = 0.5 * (xi_left - wall_phase .* xi_right);
flat_flux_right = 0.5 * (-wall_phase .* xi_left + xi_right);
Q_left_tilde = flat_flux_left + curve_flux.left;
Q_right_tilde = flat_flux_right + curve_flux.right;

ell_plus_tilde = Q_right_tilde * z.Gplus + ...
  Q_left_tilde * z.Gplus * z.Pplus;
ell_minus_tilde = Q_left_tilde * z.Gminus + ...
  Q_right_tilde * z.Gminus * z.Pminus;
plus_right_error = LOCAL_strip_remainder( ...
  z, curve, density, modal, z.Gplus, 'right');
plus_left_error = LOCAL_strip_remainder( ...
  z, curve, density, modal, z.Gplus * z.Pplus, 'left');
minus_left_error = LOCAL_strip_remainder( ...
  z, curve, density, modal, z.Gminus, 'left');
minus_right_error = LOCAL_strip_remainder( ...
  z, curve, density, modal, z.Gminus * z.Pminus, 'right');
ell_plus_error = plus_right_error.display + plus_left_error.display;
ell_minus_error = minus_left_error.display + minus_right_error.display;

[center_dx_left, center_dx_right] = LOCAL_center_derivatives(z, modal);
plus_state = z.Gplus * z.cplus;
minus_state = z.Gminus * z.cminus;
singleton_plus_tilde = center_dx_right + Q_left_tilde * plus_state;
singleton_minus_tilde = -center_dx_left + Q_right_tilde * minus_state;
singleton_plus_record = LOCAL_strip_remainder( ...
  z, curve, density, modal, plus_state, 'left');
singleton_minus_record = LOCAL_strip_remainder( ...
  z, curve, density, modal, minus_state, 'right');
rows = struct( ...
  'Q_left_tilde', Q_left_tilde, ...
  'Q_right_tilde', Q_right_tilde, ...
  'ell_plus_tilde', ell_plus_tilde, ...
  'ell_minus_tilde', ell_minus_tilde, ...
  'ell_plus_error', ell_plus_error, ...
  'ell_minus_error', ell_minus_error, ...
  'singleton_plus_tilde', singleton_plus_tilde, ...
  'singleton_minus_tilde', singleton_minus_tilde, ...
  'singleton_plus_error', singleton_plus_record.display, ...
  'singleton_minus_error', singleton_minus_record.display, ...
  'center_dx_left', center_dx_left, ...
  'center_dx_right', center_dx_right, ...
  'remainder_records', struct( ...
    'plus_right', plus_right_error, ...
    'plus_left', plus_left_error, ...
    'minus_left', minus_left_error, ...
    'minus_right', minus_right_error, ...
    'singleton_plus', singleton_plus_record, ...
    'singleton_minus', singleton_minus_record));
end

function [center_dx_left, center_dx_right] = ...
    LOCAL_center_derivatives(z, modal)
K = double(z.K);
center_left_state = z.q_center(1:K);
center_right_state = z.q_center(K + 1.0:end);
retained_orders = (-double(z.M):double(z.M)).';
[present, retained_indices] = ismember(retained_orders, modal.wall_orders);
if ~all(present)
  error('I5WallCurve:CenterEmbedding', ...
    'A center Rayleigh order is absent from the finite wall range.');
end
retained_gamma = modal.rayleigh_wavenumber(retained_indices);
retained_phase = exp(1i * retained_gamma * z.L);
left_retained = 1i * retained_gamma .* ( ...
  center_left_state - retained_phase .* center_right_state);
right_retained = 1i * retained_gamma .* ( ...
  retained_phase .* center_left_state - center_right_state);
center_dx_left = complex(zeros(size(modal.wall_orders)));
center_dx_right = center_dx_left;
center_dx_left(retained_indices) = left_retained;
center_dx_right(retained_indices) = right_retained;
end

%% ==================== Side, sign, and index audit ====================
% Frozen ordinary maps are comparison data and never enter the bound.

function audit = LOCAL_side_index_audit( ...
    z, raw_maps, modal, rows, curve_flux, curve, cfg)
G_plus_reference = [z.Dplus; z.Dplus * z.Pplus];
G_minus_reference = [z.Dminus * z.Pminus; z.Dminus];
G_plus_defect = LOCAL_relative_difference(z.Gplus, G_plus_reference);
G_minus_defect = LOCAL_relative_difference(z.Gminus, G_minus_reference);
stored_plus_defect = LOCAL_relative_difference( ...
  raw_maps.Jplus, raw_maps.QRplus + raw_maps.QLplus * z.Pplus);
stored_minus_defect = LOCAL_relative_difference( ...
  raw_maps.Jminus, raw_maps.QLminus + raw_maps.QRminus * z.Pminus);
stored_orders = double(z.wall_orders_512(:));
[present, finite_indices] = ismember(stored_orders, modal.wall_orders);
if ~all(present)
  error('I5WallCurve:AuditEmbedding', ...
    'An I3 audit order is absent from the finite wall range.');
end
Q_left_defect = LOCAL_relative_difference( ...
  rows.Q_left_tilde(finite_indices, :), ...
  raw_maps.wall_flux_left_unit_512);
Q_right_defect = LOCAL_relative_difference( ...
  rows.Q_right_tilde(finite_indices, :), ...
  raw_maps.wall_flux_right_unit_512);
ell_plus_defect = LOCAL_relative_difference( ...
  rows.ell_plus_tilde(finite_indices, :), raw_maps.Jplus);
ell_minus_defect = LOCAL_relative_difference( ...
  rows.ell_minus_tilde(finite_indices, :), raw_maps.Jminus);
center_left_defect = LOCAL_relative_difference( ...
  rows.center_dx_left(finite_indices), ...
  z.center_wall_jumps.center_left_global_dx);
center_right_defect = LOCAL_relative_difference( ...
  rows.center_dx_right(finite_indices), ...
  z.center_wall_jumps.center_right_global_dx);
singleton_left_defect = LOCAL_relative_difference( ...
  rows.singleton_minus_tilde(finite_indices), ...
  z.center_wall_jumps.left_coefficients);
singleton_right_defect = LOCAL_relative_difference( ...
  rows.singleton_plus_tilde(finite_indices), ...
  z.center_wall_jumps.right_coefficients);
ell_plus_scaled_absolute_defect = norm( ...
  rows.ell_plus_tilde(finite_indices, :) - raw_maps.Jplus, 'fro') / ...
  max(1.0, norm(raw_maps.Jplus, 'fro'));
ell_minus_scaled_absolute_defect = norm( ...
  rows.ell_minus_tilde(finite_indices, :) - raw_maps.Jminus, 'fro') / ...
  max(1.0, norm(raw_maps.Jminus, 'fro'));
singleton_left_scaled_absolute_defect = norm( ...
  rows.singleton_minus_tilde(finite_indices) - ...
  z.center_wall_jumps.left_coefficients) / ...
  max(1.0, norm(z.center_wall_jumps.left_coefficients));
singleton_right_scaled_absolute_defect = norm( ...
  rows.singleton_plus_tilde(finite_indices) - ...
  z.center_wall_jumps.right_coefficients) / ...
  max(1.0, norm(z.center_wall_jumps.right_coefficients));
ordinary_regression_pass = ...
  Q_left_defect <= cfg.ordinary_identity_tolerance && ...
  Q_right_defect <= cfg.ordinary_identity_tolerance && ...
  ell_plus_scaled_absolute_defect <= cfg.ordinary_identity_tolerance && ...
  ell_minus_scaled_absolute_defect <= cfg.ordinary_identity_tolerance && ...
  singleton_left_scaled_absolute_defect <= ...
    cfg.ordinary_identity_tolerance && ...
  singleton_right_scaled_absolute_defect <= ...
    cfg.ordinary_identity_tolerance;
structural_pass = ...
  G_plus_defect <= cfg.ordinary_identity_tolerance && ...
  G_minus_defect <= cfg.ordinary_identity_tolerance && ...
  stored_plus_defect <= cfg.ordinary_identity_tolerance && ...
  stored_minus_defect <= cfg.ordinary_identity_tolerance && ...
  center_left_defect <= cfg.ordinary_identity_tolerance && ...
  center_right_defect <= cfg.ordinary_identity_tolerance && ...
  curve.audit.pass;
audit = struct( ...
  'structural_pass', structural_pass, ...
  'ordinary_identity_tolerance', cfg.ordinary_identity_tolerance, ...
  'G_plus_relative_defect', G_plus_defect, ...
  'G_minus_relative_defect', G_minus_defect, ...
  'stored_J_plus_association_defect', stored_plus_defect, ...
  'stored_J_minus_association_defect', stored_minus_defect, ...
  'center_dx_left_relative_defect', center_left_defect, ...
  'center_dx_right_relative_defect', center_right_defect, ...
  'general_Q_left_crosscheck_defect', Q_left_defect, ...
  'general_Q_right_crosscheck_defect', Q_right_defect, ...
  'general_ell_plus_crosscheck_defect', ell_plus_defect, ...
  'general_ell_minus_crosscheck_defect', ell_minus_defect, ...
  'general_singleton_left_crosscheck_defect', singleton_left_defect, ...
  'general_singleton_right_crosscheck_defect', singleton_right_defect, ...
  'ell_plus_scaled_absolute_defect', ell_plus_scaled_absolute_defect, ...
  'ell_minus_scaled_absolute_defect', ell_minus_scaled_absolute_defect, ...
  'singleton_left_scaled_absolute_defect', ...
    singleton_left_scaled_absolute_defect, ...
  'singleton_right_scaled_absolute_defect', ...
    singleton_right_scaled_absolute_defect, ...
  'ordinary_regression_pass', ordinary_regression_pass, ...
  'ordinary_regression_only', true, ...
  'regression_enters_remainder', false, ...
  'regression_enters_stopping_rule', false, ...
  'stored_raw_maps_enter_bound', false, ...
  'q_row_remainder_log_max', max([ ...
    curve_flux.left_q_error.log_value; ...
    curve_flux.right_q_error.log_value]), ...
  'plus_formula', 'QR*Gplus + QL*Gplus*Pplus', ...
  'minus_formula', 'QL*Gminus + QR*Gminus*Pminus', ...
  'singleton_minus_formula', '-dxL + QR*Gminus*cminus', ...
  'singleton_plus_formula', 'dxR + QL*Gplus*cplus', ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
end

%% ==================== Full-matrix propagation ====================
% Whole matrix norms retain nonnormal transients and Jordan coupling.

function certificate = LOCAL_block_certificate(P, block_length)
state = eye(size(P));
power_norms = zeros(block_length, 1);
for power_index = 0.0:block_length - 1.0
  power_norms(power_index + 1.0) = norm(state, 2);
  state = state * P;
end
block_norm = norm(state, 2);
contraction_pass = isfinite(block_norm) && block_norm < 1.0;
if contraction_pass
  propagation_constant = sum(power_norms.^2) / (1.0 - block_norm^2);
else
  propagation_constant = Inf;
end
certificate = struct( ...
  'block_length', block_length, ...
  'power_norms', power_norms, ...
  'block_norm', block_norm, ...
  'propagation_constant', propagation_constant, ...
  'contraction_pass', contraction_pass, ...
  'whole_matrix_norms', true, ...
  'spectral_radius_substitution', false, ...
  'ordinary_floating_point', true, ...
  'outward_norm_upper_bounds', false, ...
  'reliability_certified', false);
end

%% ==================== Positive-distance high-mode constants ====================
% A general speed upper bound supplies the density L1 constants.

function constants = LOCAL_density_constants(z, curve, density)
l1_density_factor = curve.parameter_period * ...
  curve.real_certificate.speed_upper;
T_tau = density.tau_coeff_map;
T_single_layer_density = density.single_layer_density_coeff_map;
constants = struct( ...
  'A_tau_plus', l1_density_factor * ( ...
    norm(T_tau * z.Gplus, 'fro') + ...
    norm(T_tau * z.Gplus * z.Pplus, 'fro')), ...
  'A_single_layer_density_plus', l1_density_factor * ( ...
    norm(T_single_layer_density * z.Gplus, 'fro') + ...
    norm(T_single_layer_density * z.Gplus * z.Pplus, 'fro')), ...
  'A_tau_minus', l1_density_factor * ( ...
    norm(T_tau * z.Gminus, 'fro') + ...
    norm(T_tau * z.Gminus * z.Pminus, 'fro')), ...
  'A_single_layer_density_minus', l1_density_factor * ( ...
    norm(T_single_layer_density * z.Gminus, 'fro') + ...
    norm(T_single_layer_density * z.Gminus * z.Pminus, 'fro')), ...
  'A_tau_plus_singleton', l1_density_factor * ...
    norm(T_tau * z.Gplus * z.cplus), ...
  'A_single_layer_density_plus_singleton', l1_density_factor * ...
    norm(T_single_layer_density * z.Gplus * z.cplus), ...
  'A_tau_minus_singleton', l1_density_factor * ...
    norm(T_tau * z.Gminus * z.cminus), ...
  'A_single_layer_density_minus_singleton', l1_density_factor * ...
    norm(T_single_layer_density * z.Gminus * z.cminus), ...
  'l1_density_factor', l1_density_factor, ...
  'formula', 'parameter_period*speed_upper*Fourier-Frobenius bound');
values = cell2mat(struct2cell(rmfield(constants, 'formula')));
if any(~isfinite(values) | values < 0.0)
  error('I5WallCurve:DensityConstants', ...
    'A general-curve density L1 constant is invalid.');
end
end

function high_mode = LOCAL_high_mode_constants( ...
    z, curve, constants, modal, cfg)
positive_distance = min( ...
  curve.real_certificate.left_clearance_lower, ...
  curve.real_certificate.right_clearance_lower);
if ~(positive_distance > 0.0)
  error('I5WallCurve:PositiveDistance', ...
    'The curve-to-wall distance lower bound is not strictly positive.');
end
plus = LOCAL_C_squared(z, constants.A_tau_plus, ...
  constants.A_single_layer_density_plus, positive_distance, cfg);
minus = LOCAL_C_squared(z, constants.A_tau_minus, ...
  constants.A_single_layer_density_minus, positive_distance, cfg);
plus_singleton = LOCAL_C_squared(z, ...
  constants.A_tau_plus_singleton, ...
  constants.A_single_layer_density_plus_singleton, ...
  positive_distance, cfg);
minus_singleton = LOCAL_C_squared(z, ...
  constants.A_tau_minus_singleton, ...
  constants.A_single_layer_density_minus_singleton, ...
  positive_distance, cfg);
high_mode = struct( ...
  'positive_distance', positive_distance, ...
  'mode_cutoff', cfg.mode_cutoff, ...
  'omitted_modes_strictly_evanescent', ...
    modal.audit.omitted_modes_strictly_evanescent, ...
  'C_plus_squared', plus.display_squared, ...
  'C_minus_squared', minus.display_squared, ...
  'C_plus_singleton_squared', plus_singleton.display_squared, ...
  'C_minus_singleton_squared', minus_singleton.display_squared, ...
  'log_C_plus_squared', plus.log_squared, ...
  'log_C_minus_squared', minus.log_squared, ...
  'log_C_plus_singleton_squared', plus_singleton.log_squared, ...
  'log_C_minus_singleton_squared', minus_singleton.log_squared, ...
  'underflow_floor_used', plus.underflow_floor_used || ...
    minus.underflow_floor_used || plus_singleton.underflow_floor_used || ...
    minus_singleton.underflow_floor_used, ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
end

function C = LOCAL_C_squared( ...
    z, A_tau, A_single_layer_density, positive_distance, cfg)
k_outer = double(z.khat);
beta_bloch = double(z.beta);
period_y = double(z.d);
q0 = 2.0 * pi / period_y;
first_omitted_index = cfg.mode_cutoff + 1.0;
a0 = q0 * first_omitted_index - abs(beta_bloch);
if ~(a0 > k_outer)
  error('I5WallCurve:HighModeCutoff', ...
    'The first omitted order is not proved evanescent.');
end
r = exp(-2.0 * positive_distance * q0);
log_S0 = first_omitted_index * log(r) - log1p(-r);
S1_over_S0 = first_omitted_index + r / (1.0 - r);
t0 = tanh(cfg.trace_half_width * a0);
bracket_over_S0 = 4.0 * A_tau^2 * ( ...
  q0 * S1_over_S0 + abs(beta_bloch)) + ...
  4.0 * A_tau * A_single_layer_density + ...
  A_single_layer_density^2 / a0;
if bracket_over_S0 == 0.0
  log_squared = -Inf;
else
  log_squared = 2.0 * positive_distance * ...
    (k_outer + abs(beta_bloch)) - log(4.0 * period_y * t0) + ...
    log_S0 + log(bracket_over_S0);
end
[display_squared, underflow_floor_used] = LOCAL_exp_display(log_squared);
C = struct( ...
  'display_squared', display_squared, ...
  'log_squared', log_squared, ...
  'underflow_floor_used', underflow_floor_used);
end

%% ==================== Finite and omitted assembly ====================
% The pieces remain disjoint in wall, mode, and cell indices.

function finite = LOCAL_finite_part(z, modal, rows, cfg)
[plus_squared, plus_state_after] = LOCAL_side_finite( ...
  rows.ell_plus_tilde, rows.ell_plus_error, ...
  rows.singleton_plus_tilde, rows.singleton_plus_error, ...
  modal.wall_weights, z.Pplus, z.cplus, cfg.cell_cutoff);
[minus_squared, minus_state_after] = LOCAL_side_finite( ...
  rows.ell_minus_tilde, rows.ell_minus_error, ...
  rows.singleton_minus_tilde, rows.singleton_minus_error, ...
  modal.wall_weights, z.Pminus, z.cminus, cfg.cell_cutoff);
finite_squared = plus_squared + minus_squared;
finite = struct( ...
  'finite_squared', finite_squared, ...
  'finite_norm', sqrt(finite_squared), ...
  'plus_squared', plus_squared, ...
  'minus_squared', minus_squared, ...
  'plus_state_after_J', plus_state_after, ...
  'minus_state_after_J', minus_state_after, ...
  'mode_cutoff', cfg.mode_cutoff, ...
  'cell_cutoff', cfg.cell_cutoff);
end

function [side_squared, state_after] = LOCAL_side_finite( ...
    ell_tilde, ell_error, singleton_tilde, singleton_error, ...
    wall_weights, P, starting_state, cell_cutoff)
side_squared = sum((abs(singleton_tilde) + singleton_error).^2 ./ ...
  wall_weights);
state = starting_state;
for cell_index = 0.0:cell_cutoff - 1.0
  row_actions = ell_tilde * state;
  enclosed_actions = abs(row_actions) + ell_error * norm(state);
  side_squared = side_squared + ...
    sum(enclosed_actions.^2 ./ wall_weights);
  state = P * state;
end
state_after = state;
end

function tail = LOCAL_tail_part( ...
    z, modal, rows, finite, high_mode, ...
    propagation_minus, propagation_plus)
omega_plus = sum((LOCAL_row_norms(rows.ell_plus_tilde) + ...
  rows.ell_plus_error).^2 ./ modal.wall_weights);
omega_minus = sum((LOCAL_row_norms(rows.ell_minus_tilde) + ...
  rows.ell_minus_error).^2 ./ modal.wall_weights);
plus_finite_mode_propagation = omega_plus * ...
  propagation_plus.propagation_constant * ...
  norm(finite.plus_state_after_J)^2;
minus_finite_mode_propagation = omega_minus * ...
  propagation_minus.propagation_constant * ...
  norm(finite.minus_state_after_J)^2;
plus_high_internal = high_mode.C_plus_squared * ...
  propagation_plus.propagation_constant * norm(z.cplus)^2;
minus_high_internal = high_mode.C_minus_squared * ...
  propagation_minus.propagation_constant * norm(z.cminus)^2;
plus_high_singleton = high_mode.C_plus_singleton_squared;
minus_high_singleton = high_mode.C_minus_singleton_squared;
tail_squared = plus_finite_mode_propagation + ...
  minus_finite_mode_propagation + plus_high_internal + ...
  minus_high_internal + plus_high_singleton + minus_high_singleton;
if ~isfinite(tail_squared) || tail_squared < 0.0
  error('I5WallCurve:TailAssembly', ...
    'The omitted artificial-wall contribution is invalid.');
end
tail = struct( ...
  'tail_squared', tail_squared, ...
  'tail_norm', sqrt(tail_squared), ...
  'omega_plus', omega_plus, ...
  'omega_minus', omega_minus, ...
  'plus_finite_mode_propagation', plus_finite_mode_propagation, ...
  'minus_finite_mode_propagation', minus_finite_mode_propagation, ...
  'plus_high_internal', plus_high_internal, ...
  'minus_high_internal', minus_high_internal, ...
  'plus_high_singleton', plus_high_singleton, ...
  'minus_high_singleton', minus_high_singleton, ...
  'ordinary_floating_point', true, ...
  'reliability_certified', false);
end

%% ==================== Small numerical helpers ====================
% These helpers implement only finite algebra used by the formulas above.

function embedded = LOCAL_embed_orders(values, source_orders, target_orders)
[present, target_indices] = ismember(source_orders, target_orders);
if ~all(present) || size(values, 1) ~= numel(source_orders)
  error('I5WallCurve:OrderEmbedding', ...
    'A finite coefficient order cannot be embedded.');
end
embedded = complex(zeros(numel(target_orders), size(values, 2)));
embedded(target_indices, :) = values;
end

function norms = LOCAL_row_norms(values)
norms = sqrt(sum(abs(values).^2, 2));
end

function defect = LOCAL_relative_difference(left, right)
defect = norm(left - right, 'fro') / ...
  max([realmin, norm(left, 'fro'), norm(right, 'fro')]);
end

function [display_value, underflow_floor_used] = LOCAL_exp_display(log_value)
display_value = zeros(size(log_value));
positive = isfinite(log_value);
underflow = positive & log_value < log(realmin);
regular = positive & ~underflow;
display_value(regular) = exp(log_value(regular));
display_value(underflow) = realmin;
underflow_floor_used = any(underflow);
end
