function result = tep_mc_zoom2(stage)
%TEP_MC_ZOOM2 Run the preregistered M48 quarter-grid zoom experiment.
% Purpose:
%   Evaluate I1-K-SCAN-ZOOM-V2 without modifying v1 code or artifacts.
% Input:
%   stage - 'pilot' validates lineage and pivot reproduction; 'full' runs
%   levels 0 through 14 under the frozen quarter-grid contract.
% Output:
%   result - compact stage result saved under output/zoom2[-pilot]/.
% Main algorithm:
%   Freeze one pivot frame, retain a rolling set of at most five dense nodes,
%   evaluate five nodes per level, and choose the fine minimum's neighbors.
% Based on:
%   p-zoom2.md, zoom2_cfg.m, and the read-only public zoom_core.m point API.
% Numerical goal:
%   Record fail-closed M48 discrete-grid evidence without a locator claim.

  if nargin < 1 || isempty(stage), stage = 'pilot'; end
  if exist('OCTAVE_VERSION','builtin') ~= 0
    error('tep_mc_zoom2:MATLABRequired','MATLAB is required.');
  end
  if isempty(which('lsqminnorm'))
    error('tep_mc_zoom2:LsqminnormRequired','MATLAB lsqminnorm is required.');
  end
  here = fileparts(mfilename('fullpath'));
  repo = fileparts(fileparts(fileparts(here)));
  addpath(repo);
  cfg = zoom2_cfg();
  provenance = LOCAL_provenance(here,repo);
  LOCAL_runtime_contract(cfg,provenance);
  [parent,parent_note] = LOCAL_parent(here,cfg,provenance);
  stage = lower(char(stage));
  if strcmp(stage,'pilot')
    result = LOCAL_pilot(cfg,here,parent,parent_note,provenance);
  elseif strcmp(stage,'full')
    pilot = LOCAL_pilot_parent(here,cfg,provenance,parent);
    result = LOCAL_full(cfg,here,parent,pilot,provenance);
  else
    error('tep_mc_zoom2:Stage','Unknown stage %s.',stage);
  end
end

%% ==================== Stage drivers ====================
% These helpers execute the source-current pilot and bounded full run.

function result = LOCAL_pilot(cfg,here,parent,parent_note,p)
  output_dir = fullfile(here,'output','zoom2-pilot'); LOCAL_mkdir(output_dir);
  timer = tic;
  [seed,frame] = zoom_core('seed',cfg);
  reference = LOCAL_parent_score(here,cfg.pivot_seed_k);
  match = LOCAL_score_match(seed,reference,cfg.parent_score_match_tol);
  retained_bytes = LOCAL_state_bytes(seed,frame);
  memory_ok = retained_bytes/2^20 <= cfg.active_memory_mib;
  count_ok = numel(seed) <= cfg.active_node_limit;
  pass = seed.pass && match.pass && memory_ok && count_ok;
  gates = [ ...
    LOCAL_gate(-1,'parent_lineage',true,1,1,parent_note); ...
    LOCAL_gate(-1,'matlab_lsqminnorm',true,1,1, ...
      'MATLAB lsqminnorm with zero fallback and rank switch'); ...
    LOCAL_gate(-1,'pivot_seed_scientific',seed.pass,double(seed.pass),1, ...
      'M48 coarse/fine pivot under one shared fixed-row selector'); ...
    LOCAL_gate(-1,'parent_score_roundoff',match.pass,match.value, ...
      cfg.parent_score_match_tol,'pivot score versus confirm48 scores.csv'); ...
    LOCAL_gate(-1,'active_node_count',count_ok,numel(seed), ...
      cfg.active_node_limit,'rolling dense-node count'); ...
    LOCAL_gate(-1,'active_state_memory',memory_ok,retained_bytes/2^20, ...
      cfg.active_memory_mib,'estimated active dense state in MiB')];
  if pass, status = 'ZOOM2_PILOT_PASS'; else, status = 'ZOOM2_PILOT_FAIL'; end
  lineage = LOCAL_lineage('zoom2-pilot',status,parent.lineage.token,p,cfg);
  memory = struct('retained_bytes',retained_bytes,'max_active_nodes',1, ...
    'max_active_bytes',retained_bytes);
  result = LOCAL_result(cfg,'zoom2-pilot',status,pass,toc(timer),gates, ...
    LOCAL_point_rows(seed,-1),LOCAL_score_rows(seed,-1), ...
    LOCAL_level_rows(seed,-1),LOCAL_qz_rows(seed,-1), ...
    LOCAL_chart_rows(seed,-1),cell(0,9),cell(0,46),p,lineage,parent, ...
    parent.lineage.token,struct([]),frame,match,memory, ...
    'PIVOT_RECOMPUTATION_ONLY');
  LOCAL_write(output_dir,result);
  fprintf('TEP_MC_ZOOM2_STAGE=pilot STATUS=%s seconds=%.6g retained_mib=%.6g\n', ...
    status,result.elapsed_seconds,retained_bytes/2^20);
end

function result = LOCAL_full(cfg,here,parent,pilot,p)
  output_dir = fullfile(here,'output','zoom2'); LOCAL_mkdir(output_dir);
  timer = tic;
  [seed,frame] = zoom_core('seed',cfg); active = seed;
  interval = cfg.initial_interval;
  gates = [LOCAL_gate(-1,'scientific_parent_lineage',true,1,1, ...
    'confirm48 scientific parent verified'); ...
    LOCAL_gate(-1,'zoom2_pilot_lineage',true,1,1, ...
    'source-current passing zoom2 pilot verified')];
  points = cell(0,10); scores = cell(0,15); levels = cell(0,17);
  qz = cell(0,22); charts = cell(0,13); transports = cell(0,9);
  layer_rows = cell(0,46); q_history = [];
  stop_code = 'MAX_LEVEL'; status = 'ZOOM2_MAX_LEVEL_FAIL'; pass = false;
  final = struct(); initial_shoulders = struct(); completed_level = -1;
  max_active_nodes = numel(active);
  max_active_bytes = LOCAL_state_bytes(active,frame);

  for layer = cfg.first_level:cfg.max_level
    if toc(timer) >= cfg.hard_seconds
      stop_code = 'HARD_TIME'; status = 'ZOOM2_HARD_TIME_FAIL'; break;
    end
    width = interval(2)-interval(1); h = width/4;
    kvals = interval(1)+(0:4)*h;
    hard_time = false; new_count = 0;
    for j = 1:5
      if toc(timer) >= cfg.hard_seconds
        hard_time = true; break;
      end
      [active,node,is_new] = LOCAL_cached(active,kvals(j),cfg,frame);
      new_count = new_count+double(is_new);
      if is_new || layer == cfg.first_level
        [points,scores,levels,qz,charts] = LOCAL_append( ...
          points,scores,levels,qz,charts,node,layer);
      end
    end
    if hard_time
      stop_code = 'HARD_TIME'; status = 'ZOOM2_HARD_TIME_FAIL'; break;
    end
    nodes = LOCAL_select(active,kvals);
    active = nodes;
    active_bytes = LOCAL_state_bytes(active,frame);
    max_active_nodes = max(max_active_nodes,numel(active));
    max_active_bytes = max(max_active_bytes,active_bytes);
    count_ok = numel(active) <= cfg.active_node_limit;
    memory_ok = active_bytes/2^20 <= cfg.active_memory_mib;
    if layer == cfg.first_level, expected_new = 4; else, expected_new = 2; end
    rolling_ok = new_count == expected_new;
    if layer == cfg.first_level
      initial_shoulders = LOCAL_shoulders(nodes);
    end
    assessment = LOCAL_assess(nodes,layer,width,h,initial_shoulders,cfg);
    transports = [transports;assessment.transport_rows]; %#ok<AGROW>
    engineering_gates = [ ...
      LOCAL_gate(layer,'active_node_count',count_ok,numel(active), ...
        cfg.active_node_limit,'rolling dense-node count'); ...
      LOCAL_gate(layer,'active_state_memory',memory_ok,active_bytes/2^20, ...
        cfg.active_memory_mib,'estimated active dense state in MiB'); ...
      LOCAL_gate(layer,'rolling_new_node_count',rolling_ok,new_count, ...
        expected_new,'level 0 adds four nodes; later levels add two')];
    gates = [gates;assessment.gates;engineering_gates]; %#ok<AGROW>
    q_history(end+1) = assessment.q; %#ok<AGROW>
    [plateau_available,plateau,class_name,changes] = ...
      LOCAL_plateau(q_history,cfg);
    magnitude = assessment.q <= cfg.magnitude_tol;
    hard_gate_pass = assessment.pass && count_ok && memory_ok && rolling_ok;
    completed_level = layer;
    final = struct('coarse',nodes(assessment.coarse.index), ...
      'fine',nodes(assessment.fine.index),'assessment',assessment);

    width_complete = hard_gate_pass && width < cfg.width_tol;
    next_interval = [NaN,NaN]; next_note = 'FAIL_NO_NEXT_INTERVAL';
    if width_complete
      next_note = 'WIDTH_COMPLETE_NO_NEXT_INTERVAL';
    elseif hard_gate_pass && layer == cfg.max_level
      next_note = 'MAX_LEVEL_NO_NEXT_INTERVAL';
    elseif hard_gate_pass
      m = assessment.selected_fine_index;
      next_interval = [kvals(m-1),kvals(m+1)];
      next_note = 'FINE_MINIMUM_TWO_NEIGHBOR_INTERVAL';
    end
    layer_rows(end+1,:) = LOCAL_layer_row(assessment,nodes,layer,width,h, ...
      next_interval,next_note,hard_gate_pass,width_complete,magnitude, ...
      plateau_available,plateau,class_name,changes); %#ok<AGROW>

    if ~hard_gate_pass
      if assessment.pass, stop_code = 'SCIENTIFIC_GATE';
      else, stop_code = assessment.stop_code; end
      if ~ismember(stop_code,cfg.failure_allowlist)
        error('tep_mc_zoom2:StopCode','Unregistered stop code %s.',stop_code);
      end
      status = ['ZOOM2_',stop_code,'_FAIL'];
      break;
    end
    % Width is checked only after all level gates have been evaluated.
    if width_complete
      pass = true; stop_code = 'NORMAL_WIDTH_COMPLETE';
      status = 'ZOOM2_M48_DISCRETE_GRID_COMPLETE'; break;
    end
    if layer == cfg.max_level
      stop_code = 'MAX_LEVEL'; status = 'ZOOM2_MAX_LEVEL_FAIL'; break;
    end
    interval = next_interval;
    m = assessment.selected_fine_index;
    active = nodes(m-1:m+1);
  end

  [~,plateau,class_name,changes] = LOCAL_plateau(q_history,cfg);
  magnitude = ~isempty(q_history) && q_history(end) <= cfg.magnitude_tol;
  if pass
    candidate = LOCAL_candidate(final,completed_level,q_history(end), ...
      magnitude,plateau,class_name,changes);
  else
    candidate = struct([]);
  end
  lineage = LOCAL_lineage('zoom2',status,pilot.lineage.token,p,cfg);
  memory = struct('retained_bytes',LOCAL_state_bytes(active,frame), ...
    'max_active_nodes',max_active_nodes,'max_active_bytes',max_active_bytes);
  result = LOCAL_result(cfg,'zoom2',status,pass,toc(timer),gates,points, ...
    scores,levels,qz,charts,transports,layer_rows,p,lineage,parent, ...
    pilot.lineage.token,candidate,frame,struct('pass',true,'value',0),memory, ...
    'M48_DISCRETE_NESTED_GRID_ONLY');
  result.stop_code = stop_code;
  result.completed_level = completed_level;
  result.q_history = q_history;
  result.magnitude_q_le_1e_3 = magnitude;
  result.plateau_diagnostic = plateau;
  result.plateau_class = class_name;
  result.plateau_relative_changes = changes;
  if ~isempty(fieldnames(final)), result.final_summary = LOCAL_summary(final); end
  result.scientific_parent_token = parent.lineage.token;
  LOCAL_write(output_dir,result);
  fprintf(['TEP_MC_ZOOM2_STAGE=full STATUS=%s stop=%s pass=%d ', ...
    'seconds=%.6g level=%d\n'],status,stop_code,pass, ...
    result.elapsed_seconds,completed_level);
end

%% ==================== Rolling state and frozen gates ====================
% These helpers retain only active nodes and evaluate the frozen contract.

function [cache,node,is_new] = LOCAL_cached(cache,k,cfg,frame)
  index = find(abs([cache.k]-k) <= 1e-13,1);
  is_new = isempty(index);
  if is_new
    node = zoom_core('point',k,cfg,frame);
    cache(end+1) = node;
  else
    node = cache(index);
  end
end

function nodes = LOCAL_select(cache,kvals)
  nodes = repmat(cache(1),1,5);
  for j = 1:5
    index = find(abs([cache.k]-kvals(j)) <= 1e-13,1);
    if isempty(index), error('tep_mc_zoom2:Cache','Missing cached point.'); end
    nodes(j) = cache(index);
  end
end

function shoulders = LOCAL_shoulders(nodes)
  shoulders = struct('coarse',[nodes(1).coarse.score.s1, ...
    nodes(end).coarse.score.s1],'fine',[nodes(1).fine.score.s1, ...
    nodes(end).fine.score.s1]);
end

function a = LOCAL_assess(nodes,layer,width,h,shoulders,cfg)
  coarse = arrayfun(@(n) n.coarse.score.s1,nodes);
  fine = arrayfun(@(n) n.fine.score.s1,nodes);
  cmin = LOCAL_minimum(coarse);
  fmin = LOCAL_minimum(fine);
  ci = cmin.index; fi = fmin.index;
  point_ok = all([nodes.pass]);
  [transport_rows,transport_ok,transport_min] = ...
    LOCAL_transports(nodes,layer,cfg);
  endpoint = ~strcmp(cmin.endpoint_side,'NONE') || ...
    ~strcmp(fmin.endpoint_side,'NONE');
  unique = strcmp(cmin.state,'INTERIOR') && strcmp(fmin.state,'INTERIOR');
  index_drift = abs(ci-fi); k_drift = abs(nodes(ci).k-nodes(fi).k);
  drift_ok = unique && index_drift <= 1 && k_drift <= h+10*eps;
  score_ratio = max(coarse(ci),fine(fi))/ ...
    max(min(coarse(ci),fine(fi)),realmin);
  ratio_ok = unique && score_ratio <= cfg.score_ratio_max;
  [left_overlap,right_overlap] = LOCAL_vector_overlap( ...
    nodes(ci).coarse,nodes(fi).fine);
  vector_ok = unique && ...
    min(left_overlap,right_overlap) >= cfg.neighbor_overlap_min;
  raw_coarse = arrayfun(@(n) n.coarse.score.raw_sigma1 / ...
    n.coarse.score.raw_sigmamax,nodes);
  raw_fine = arrayfun(@(n) n.fine.score.raw_sigma1 / ...
    n.fine.score.raw_sigmamax,nodes);
  [~,rc] = min(raw_coarse); [~,rf] = min(raw_fine);
  raw_diff_c = abs(rc-ci); raw_diff_f = abs(rf-fi);
  raw_ok = unique && raw_diff_c <= 1 && raw_diff_f <= 1;
  r12 = max(nodes(ci).coarse.score.r12,nodes(fi).fine.score.r12);
  r12_ok = unique && r12 <= cfg.r12_zoom_max;
  if unique
    local_prominence = min( ...
      min(coarse(ci-1),coarse(ci+1))/max(coarse(ci),realmin), ...
      min(fine(fi-1),fine(fi+1))/max(fine(fi),realmin));
  else
    local_prominence = NaN;
  end
  shoulder_prominence = min( ...
    min(shoulders.coarse)/max(coarse(ci),realmin), ...
    min(shoulders.fine)/max(fine(fi),realmin));
  q = max(coarse(ci),fine(fi));
  gates = [ ...
    LOCAL_gate(layer,'all_point_scientific',point_ok,double(point_ok),1, ...
      'all five nodes pass unchanged M48 scientific gates'); ...
    LOCAL_gate(layer,'neighbor_transport',transport_ok,transport_min, ...
      cfg.neighbor_overlap_min,'adjacent QZ-subspace overlap'); ...
    LOCAL_gate(layer,'unique_interior_minima',unique,double(unique),1, ...
      'one strict interior global minimum per spatial level'); ...
    LOCAL_gate(layer,'coarse_fine_drift',drift_ok,k_drift,h, ...
      'minimum index difference <=1 and k drift <= spacing'); ...
    LOCAL_gate(layer,'coarse_fine_score_ratio',ratio_ok,score_ratio, ...
      cfg.score_ratio_max,'physical minimum score ratio'); ...
    LOCAL_gate(layer,'minimum_vector_overlap',vector_ok, ...
      min(left_overlap,right_overlap),cfg.neighbor_overlap_min, ...
      'coarse/fine left and right minimum-vector overlaps'); ...
    LOCAL_gate(layer,'raw_physical_minimum_index',raw_ok, ...
      max(raw_diff_c,raw_diff_f),1,'per-level raw/physical index difference'); ...
    LOCAL_gate(layer,'minimum_r12',r12_ok,r12,cfg.r12_zoom_max, ...
      'coarse/fine physical minimum r12')];
  pass = point_ok && transport_ok && unique && drift_ok && ratio_ok && ...
    vector_ok && raw_ok && r12_ok;
  stop_code = '';
  if ~point_ok || ~transport_ok
    stop_code = 'SCIENTIFIC_GATE';
  elseif endpoint
    stop_code = 'UNBRACKETED_ENDPOINT';
  elseif ~unique
    stop_code = 'NONUNIQUE_MINIMUM';
  elseif ~drift_ok
    stop_code = 'COARSE_FINE_DRIFT';
  elseif ~ratio_ok || ~vector_ok || ~raw_ok || ~r12_ok
    stop_code = 'SCIENTIFIC_GATE';
  end
  selected = NaN;
  if unique, selected = fi; end
  a = struct('pass',pass,'stop_code',stop_code,'q',q, ...
    'width',width,'grid_spacing',h, ...
    'coarse',cmin,'fine',fmin,'selected_fine_index',selected, ...
    'selection_rule','FINE_MINIMUM_TWO_NEIGHBOR_INTERVAL', ...
    'coarse_min_k',nodes(ci).k,'fine_min_k',nodes(fi).k, ...
    'coarse_min_s1',coarse(ci),'fine_min_s1',fine(fi), ...
    'index_drift',index_drift,'k_drift',k_drift, ...
    'score_ratio',score_ratio,'r12',r12,'left_overlap',left_overlap, ...
    'right_overlap',right_overlap,'raw_diff_coarse',raw_diff_c, ...
    'raw_diff_fine',raw_diff_f,'local_prominence',local_prominence, ...
    'fixed_prominence',shoulder_prominence,'min_transport',transport_min, ...
    'transport_rows',{transport_rows},'gates',{gates});
end

function result = LOCAL_minimum(values)
  minimum = min(values); found = find(values == minimum);
  index = found(1); multiplicity = numel(found);
  left = any(found == 1); right = any(found == numel(values));
  if left && right
    endpoint_side = 'BOTH';
  elseif left
    endpoint_side = 'LEFT';
  elseif right
    endpoint_side = 'RIGHT';
  else
    endpoint_side = 'NONE';
  end
  if multiplicity > 1
    state = 'NONUNIQUE';
  elseif left || right
    state = 'ENDPOINT';
  elseif values(index) < values(index-1) && values(index) < values(index+1)
    state = 'INTERIOR';
  else
    state = 'NONUNIQUE';
  end
  result = struct('index',index,'value',minimum,'multiplicity',multiplicity, ...
    'endpoint_side',endpoint_side,'state',state);
end

function row = LOCAL_layer_row(a,nodes,layer,width,h,next_interval, ...
    next_note,hard_gate_pass,width_complete,magnitude,plateau_available, ...
    plateau,class_name,changes)
  change1 = NaN; change2 = NaN;
  if plateau_available, change1 = changes(1); change2 = changes(2); end
  row = {layer,width,h,nodes(1).k,nodes(2).k,nodes(3).k,nodes(4).k, ...
    nodes(5).k,a.coarse.state,a.coarse.index,a.coarse.multiplicity, ...
    a.coarse.endpoint_side,a.fine.state,a.fine.index,a.fine.multiplicity, ...
    a.fine.endpoint_side,a.selected_fine_index,a.selection_rule, ...
    next_interval(1),next_interval(2),diff(next_interval),next_note, ...
    a.coarse_min_k,a.coarse_min_s1,a.fine_min_k,a.fine_min_s1,a.q, ...
    a.index_drift,a.k_drift,a.score_ratio,a.r12,a.left_overlap, ...
    a.right_overlap,a.raw_diff_coarse,a.raw_diff_fine,a.local_prominence, ...
    a.fixed_prominence,a.min_transport,hard_gate_pass,width_complete, ...
    magnitude,plateau_available,change1,change2,plateau,class_name};
end

function [rows,pass,min_value] = LOCAL_transports(nodes,layer,cfg)
  rows = cell(0,9); pass = true; min_value = 1;
  levels = {'coarse','fine'}; sides = {'plus','minus'};
  for j = 1:4
    for l = 1:2
      for s = 1:2
        [value,~] = LOCAL_overlap(nodes(j).(levels{l}).(sides{s}).Z, ...
          nodes(j+1).(levels{l}).(sides{s}).Z);
        ok = value >= cfg.neighbor_overlap_min;
        rows(end+1,:) = {layer,nodes(j).k,nodes(j+1).k,levels{l}, ...
          sides{s},value,cfg.neighbor_overlap_min,ok,'ADJACENT_QZ_OVERLAP'}; %#ok<AGROW>
        pass = pass && ok; min_value = min(min_value,value);
      end
    end
  end
end

function [left,right] = LOCAL_vector_overlap(coarse,fine)
  [Uc,~,Vc] = svd(coarse.Aphys/coarse.score.seed_scale,'econ');
  [Uf,~,Vf] = svd(fine.Aphys/fine.score.seed_scale,'econ');
  left = abs(Uc(:,end)'*Uf(:,end)); right = abs(Vc(:,end)'*Vf(:,end));
end

function [available,plateau,class_name,changes] = LOCAL_plateau(q,cfg)
  available = numel(q) >= 3; plateau = false; changes = [];
  if available
    tail = q(end-2:end);
    changes = abs(diff(tail))./max(abs(tail(1:2)),realmin);
    plateau = all(tail > cfg.magnitude_tol) && ...
      all(changes <= cfg.plateau_relative_tol);
  end
  if ~isempty(q) && q(end) <= cfg.magnitude_tol
    class_name = 'LE_1E3_MAGNITUDE';
  elseif plateau
    class_name = 'GT_1E3_THREE_LEVEL_PLATEAU';
  else
    class_name = 'GT_1E3_UNSETTLED';
  end
end

%% ==================== Lineage and artifacts ====================
% These helpers verify both parents and write compact reproducible evidence.

function LOCAL_runtime_contract(cfg,p)
  ok = strcmp(p.runtime,'MATLAB') && strcmp(p.solver,'lsqminnorm') && ...
    ~isempty(p.solver_path) && p.fallbacks == 0 && p.silent_rank_changes == 0;
  interval_width = cfg.initial_interval(2)-cfg.initial_interval(1);
  width_consistent = abs(interval_width-cfg.initial_width) <= ...
    10*eps(max(1,abs(cfg.initial_width)));
  width_reachable = cfg.initial_width/2^cfg.max_level < cfg.width_tol;
  memory_contract = cfg.active_node_limit == 5 && ...
    cfg.active_memory_mib == 512;
  if ~ok || cfg.prominence_is_gate || ~width_consistent || ...
      ~width_reachable || ~memory_contract
    error('tep_mc_zoom2:Runtime','Runtime, solver, or diagnostic contract failed.');
  end
end

function [parent,note] = LOCAL_parent(here,cfg,p)
  path = fullfile(here,'output','confirm48','result.mat');
  if ~isfile(path), error('tep_mc_zoom2:Parent','Missing scientific parent.'); end
  loaded = load(path,'result'); parent = loaded.result;
  fields = {'schema','experiment_id','stage','status','pass', ...
    'next_authorized','all_gates_pass','candidates','lineage'};
  if ~all(isfield(parent,fields)), error('tep_mc_zoom2:Parent','Fields missing.'); end
  old_source = LOCAL_hash(fullfile(here,'tep_mc_scan.m'));
  old_config = LOCAL_hash(fullfile(here,'scan_cfg.m'));
  token = LOCAL_text_hash(strjoin({parent.schema,parent.experiment_id, ...
    parent.stage,parent.status,parent.lineage.parent_token,old_config, ...
    old_source},'|'));
  ok = strcmp(parent.schema,cfg.schema) && ...
    strcmp(parent.experiment_id,cfg.experiment_id) && ...
    strcmp(parent.stage,cfg.scientific_parent_stage) && ...
    strcmp(parent.status,cfg.scientific_parent_status) && ...
    parent.pass && parent.next_authorized && parent.all_gates_pass && ...
    numel(parent.candidates) == 1 && ...
    abs(parent.candidates(1).k-cfg.parent_candidate_k) <= 1e-14 && ...
    abs(parent.candidates(1).k2_metadata-parent.candidates(1).k^2) <= 1e-14 && ...
    strcmp(parent.lineage.token,cfg.scientific_parent_token) && ...
    strcmp(parent.lineage.token,token) && ...
    strcmp(parent.lineage.source_hash,old_source) && ...
    strcmp(parent.lineage.config_fingerprint,old_config) && ...
    strcmp(p.source_hashes.tep_mc_scan,old_source) && ...
    strcmp(p.source_hashes.scan_cfg,old_config);
  if ~ok, error('tep_mc_zoom2:Parent','Scientific parent validation failed.'); end
  note = 'confirm48 status/candidate/hash/lineage token verified';
end

function prior = LOCAL_pilot_parent(here,cfg,p,parent)
  path = fullfile(here,'output','zoom2-pilot','result.mat');
  if ~isfile(path), error('tep_mc_zoom2:Pilot','Missing v2 pilot.'); end
  loaded = load(path,'result'); prior = loaded.result;
  expected = LOCAL_lineage('zoom2-pilot',prior.status,parent.lineage.token,p,cfg);
  ok = strcmp(prior.schema,cfg.zoom2_schema) && ...
    strcmp(prior.experiment_id,cfg.zoom2_experiment_id) && ...
    strcmp(prior.stage,'zoom2-pilot') && strcmp(prior.status,'ZOOM2_PILOT_PASS') && ...
    prior.pass && prior.all_gates_pass && ...
    strcmp(prior.scientific_parent_token,parent.lineage.token) && ...
    strcmp(prior.lineage.token,expected.token);
  if ~ok, error('tep_mc_zoom2:Pilot','V2 pilot lineage failed.'); end
end

function reference = LOCAL_parent_score(here,k)
  table = readtable(fullfile(here,'output','confirm48','scores.csv'), ...
    'TextType','string');
  reference = table(abs(table.k-k)<=1e-13,:);
  if height(reference) ~= 2
    error('tep_mc_zoom2:ParentCSV','Parent pivot score rows missing.');
  end
end

function match = LOCAL_score_match(node,reference,tol)
  names = {'coarse','fine'}; fields = ...
    {'raw_sigma1','raw_sigmamax','sigma1','sigmamax','s1'}; value = 0;
  for j = 1:2
    row = reference(reference.level == names{j},:);
    if height(row) ~= 1, value = Inf; break; end
    for f = 1:numel(fields)
      a = node.(names{j}).score.(fields{f}); b = row.(fields{f});
      value = max(value,abs(a-b)/max(1,abs(b)));
    end
  end
  match = struct('pass',value <= tol,'value',value);
end

function candidate = LOCAL_candidate(final,layer,q,magnitude,plateau,class_name,changes)
  candidate = struct('k',final.fine.k,'k2_metadata',final.fine.k^2, ...
    'layer',layer,'q',q,'magnitude_q_le_1e_3',magnitude, ...
    'plateau_diagnostic',plateau,'plateau_class',class_name, ...
    'plateau_relative_changes',changes, ...
    'claim','M48_DISCRETE_NESTED_GRID_ONLY', ...
    'coarse',LOCAL_audit(final.coarse.coarse), ...
    'fine',LOCAL_audit(final.fine.fine));
end

function audit = LOCAL_audit(level)
  [U,~,V] = svd(level.Aphys/level.score.seed_scale,'econ');
  b = sqrt(1+abs(level.beta_m(:)).^2);
  audit = struct('Adef_D_unbalanced',level.Adef.D, ...
    'normalized_min_left_singular_vector',U(:,end)/norm(U(:,end)), ...
    'normalized_min_right_singular_vector',V(:,end)/norm(V(:,end)), ...
    'physical_row_weight',repmat(sqrt(1./b),2,1), ...
    'physical_column_weight',repmat(1./sqrt(b+abs(level.gamma).^2./b),2,1), ...
    'seed_scale',level.score.seed_scale,'s1',level.score.s1, ...
    'raw_sigma1',level.score.raw_sigma1, ...
    'raw_sigmamax',level.score.raw_sigmamax,'r12',level.score.r12);
end

function summary = LOCAL_summary(final)
  a = final.assessment;
  coarse = final.coarse.coarse; fine = final.fine.fine;
  qz_nodes = {coarse.plus,coarse.minus,fine.plus,fine.minus};
  chart_nodes = {coarse.cp,coarse.cm,fine.cp,fine.cm};
  unit_gap = cellfun(@(x) x.unit_gap,qz_nodes);
  residual = cellfun(@(x) x.residual,qz_nodes);
  ref_residual = cellfun(@(x) x.ref_residual,qz_nodes);
  ref_available = cellfun(@(x) x.ref_available,qz_nodes);
  stable = cellfun(@(x) x.stable_count,qz_nodes);
  unstable = cellfun(@(x) x.unstable_count,qz_nodes);
  neutral = cellfun(@(x) x.neutral_count,qz_nodes);
  infinite = cellfun(@(x) x.infinite_count,qz_nodes);
  indeterminate = cellfun(@(x) x.indeterminate_count,qz_nodes);
  chart_margin = cellfun(@(x) x.margin,chart_nodes);
  chart_condition_eps = cellfun(@(x) x.condition_eps,chart_nodes);
  chart_solve = cellfun(@(x) x.solve_residual,chart_nodes);
  finite_ref = ref_residual(ref_available & isfinite(ref_residual));
  if isempty(finite_ref), max_ref_residual = NaN;
  else, max_ref_residual = max(finite_ref); end
  summary = struct('final_k',final.fine.k, ...
    'coarse_k',final.coarse.k,'fine_k',final.fine.k, ...
    'coarse_sigma1',coarse.score.sigma1, ...
    'coarse_sigmamax',coarse.score.sigmamax,'coarse_s1',coarse.score.s1, ...
    'fine_sigma1',fine.score.sigma1, ...
    'fine_sigmamax',fine.score.sigmamax,'fine_s1',fine.score.s1, ...
    'q',a.q,'width',a.width,'grid_spacing',a.grid_spacing, ...
    'index_drift',a.index_drift,'k_drift',a.k_drift,'r12',a.r12, ...
    'left_vector_overlap',a.left_overlap, ...
    'right_vector_overlap',a.right_overlap, ...
    'min_transport',a.min_transport,'qz_stable_counts',stable, ...
    'qz_unstable_counts',unstable,'qz_neutral_counts',neutral, ...
    'qz_infinite_counts',infinite, ...
    'qz_indeterminate_counts',indeterminate, ...
    'qz_min_unit_gap',min(unit_gap),'qz_max_residual',max(residual), ...
    'qz_max_reference_residual',max_ref_residual, ...
    'chart_min_margin',min(chart_margin), ...
    'chart_max_condition_eps',max(chart_condition_eps), ...
    'chart_max_solve',max(chart_solve));
end

function result = LOCAL_result(cfg,stage,status,pass,elapsed,gates,points, ...
    scores,levels,qz,charts,transports,layer_rows,p,lineage,parent, ...
    lineage_parent,candidate,frame,match,memory,claim)
  result = struct('schema',cfg.zoom2_schema, ...
    'experiment_id',cfg.zoom2_experiment_id,'stage',stage,'status',status, ...
    'pass',pass,'all_gates_pass',~isempty(gates) && all(cell2mat(gates(:,4))), ...
    'elapsed_seconds',elapsed,'gates',{gates},'point_rows',{points}, ...
    'score_rows',{scores},'level_rows',{levels},'qz_rows',{qz}, ...
    'chart_rows',{charts},'transport_rows',{transports}, ...
    'layer_rows',{layer_rows},'provenance',p,'lineage',lineage, ...
    'lineage_parent_token',lineage_parent, ...
    'scientific_parent_token',parent.lineage.token, ...
    'candidate',{candidate},'frame_rows_plus',frame.rows_plus, ...
    'frame_rows_minus',frame.rows_minus,'coarse_seed_scale',frame.coarse_scale, ...
    'fine_seed_scale',frame.fine_scale,'parent_score_match',match, ...
    'retained_state_bytes',memory.retained_bytes, ...
    'retained_state_mib',memory.retained_bytes/2^20, ...
    'max_active_nodes',memory.max_active_nodes, ...
    'max_active_state_bytes',memory.max_active_bytes, ...
    'max_active_state_mib',memory.max_active_bytes/2^20, ...
    'active_node_limit',cfg.active_node_limit, ...
    'active_memory_limit_mib',cfg.active_memory_mib,'claim_boundary',claim, ...
    'locator_authorized',false,'root_isolation_authorized',false, ...
    'derivative_authorized',false,'estimator_authorized',false,'config',cfg);
end

function [p,s,l,q,c] = LOCAL_append(p,s,l,q,c,node,layer)
  p = [p;LOCAL_point_rows(node,layer)];
  s = [s;LOCAL_score_rows(node,layer)];
  l = [l;LOCAL_level_rows(node,layer)];
  q = [q;LOCAL_qz_rows(node,layer)];
  c = [c;LOCAL_chart_rows(node,layer)];
end

function rows = LOCAL_point_rows(n,layer)
  rows = {layer,n.k,n.pass,max(n.coarse.solve_residual,n.fine.solve_residual), ...
    min(n.coarse.wood_distance,n.fine.wood_distance), ...
    max(n.coarse.gamma_identity,n.fine.gamma_identity), ...
    n.coarse.branch_ok && n.fine.branch_ok,n.metric.block_abs, ...
    n.metric.block_action,n.metric.pencil_action};
end

function rows = LOCAL_score_rows(n,layer)
  rows = cell(2,15); names = {'coarse','fine'};
  for j = 1:2
    x = n.(names{j}).score;
    rows(j,:) = {layer,n.k,names{j},x.raw_sigma1,x.raw_sigmamax, ...
      x.sigma1,x.sigmamax,x.s1,x.r12,x.g12,x.scalar_mutation, ...
      x.seed_scale,n.(names{j}).mutation.lambda, ...
      n.(names{j}).mutation.adef,n.(names{j}).mutation.score};
  end
end

function rows = LOCAL_level_rows(n,layer)
  m = n.metric;
  rows = {layer,n.k,m.block_abs,m.block_action,m.pencil_action, ...
    m.subspace_plus,m.subspace_minus,m.cauchy_plus,m.cauchy_minus, ...
    m.dtn_plus,m.dtn_minus,m.adef_action,m.schur_max,m.row_solve_max, ...
    m.wall_ok,n.pass,'M48_COARSE_FINE'};
end

function rows = LOCAL_qz_rows(n,layer)
  rows = cell(4,22); levels = {'coarse','fine'}; sides = {'plus','minus'}; r = 0;
  for l = 1:2
    for s = 1:2
      r = r+1; x = n.(levels{l}).(sides{s});
      rows(r,:) = {layer,n.k,levels{l},sides{s},x.stable_count, ...
        x.unstable_count,x.neutral_count,x.infinite_count, ...
        x.indeterminate_count,x.tau_proj,x.raw_residual,x.residual,x.unit_gap, ...
        x.ref_available,x.ref_rcond_D,x.ref_rcond_F,x.ref_residual, ...
        x.row_margin,x.row_condition,x.row_solve,x.regular_infinity,x.pass};
    end
  end
end

function rows = LOCAL_chart_rows(n,layer)
  rows = cell(4,13); levels = {'coarse','fine'}; sides = {'plus','minus'};
  names = {'cp','cm'}; r = 0;
  for l = 1:2
    for s = 1:2
      r = r+1; q = n.(levels{l}).(sides{s}); x = n.(levels{l}).(names{s});
      rows(r,:) = {layer,n.k,levels{l},sides{s},q.row_margin, ...
        q.row_condition,q.row_condition*eps,q.row_solve,x.margin, ...
        x.condition,x.condition_eps,x.solve_residual,x.safe};
    end
  end
end

function row = LOCAL_gate(layer,name,pass,value,tolerance,note)
  if pass, status = 'PASS'; else, status = 'FAIL'; end
  row = {layer,name,status,logical(pass),value,tolerance,note};
end

function LOCAL_write(output_dir,r)
  LOCAL_csv(fullfile(output_dir,'points.csv'), ...
    {'level','k','pass','solve_max','wood_distance','gamma_identity', ...
    'branch_ok','block_abs','block_action','pencil_action'},r.point_rows);
  LOCAL_csv(fullfile(output_dir,'scores.csv'), ...
    {'level_index','k','spatial_level','raw_sigma1','raw_sigmamax', ...
    'sigma1','sigmamax','s1','r12','g12','scalar_mutation','seed_scale', ...
    'basis_lambda','basis_adef','basis_score'},r.score_rows);
  LOCAL_csv(fullfile(output_dir,'levels.csv'), ...
    {'level','k','block_abs','block_action','pencil_action','subspace_plus', ...
    'subspace_minus','cauchy_plus','cauchy_minus','dtn_plus','dtn_minus', ...
    'adef_action','schur_max','row_solve_max','wall_ok','pass','claim'}, ...
    r.level_rows);
  LOCAL_csv(fullfile(output_dir,'qz.csv'), ...
    {'level_index','k','spatial_level','side','stable','unstable','neutral', ...
    'infinite','indeterminate','tau_proj','raw_residual','residual','unit_gap', ...
    'ref_available','ref_rcond_D','ref_rcond_F','ref_residual','row_margin', ...
    'row_condition','row_solve','regular_infinity','pass'},r.qz_rows);
  LOCAL_csv(fullfile(output_dir,'charts.csv'), ...
    {'level_index','k','spatial_level','side','row_margin','row_condition', ...
    'row_condition_eps','row_solve','chart_margin','chart_condition', ...
    'chart_condition_eps','chart_solve','safe'},r.chart_rows);
  LOCAL_csv(fullfile(output_dir,'transports.csv'), ...
    {'level','k_left','k_right','spatial_level','side','overlap','threshold', ...
    'pass','claim'},r.transport_rows);
  LOCAL_csv(fullfile(output_dir,'gates.csv'), ...
    {'level','gate','status','pass','value','tolerance','note'},r.gates);
  LOCAL_csv(fullfile(output_dir,'layers.csv'), ...
    {'level','width','grid_spacing','node_1','node_2','node_3','node_4', ...
    'node_5','coarse_state','coarse_index','coarse_multiplicity', ...
    'coarse_endpoint_side','fine_state','fine_index','fine_multiplicity', ...
    'fine_endpoint_side','selected_fine_index','selection_rule','next_left', ...
    'next_right','next_width','next_interval_note','coarse_min_k', ...
    'coarse_min_s1','fine_min_k','fine_min_s1','q','index_drift','k_drift', ...
    'score_ratio','r12','left_vector_overlap','right_vector_overlap', ...
    'raw_index_diff_coarse','raw_index_diff_fine', ...
    'local_prominence_diagnostic','fixed_shoulder_prominence_diagnostic', ...
    'min_transport','hard_gate_pass','width_complete','q_le_1e3', ...
    'plateau_available','plateau_change_1','plateau_change_2', ...
    'plateau_diagnostic','plateau_class'}, ...
    r.layer_rows);
  LOCAL_write_provenance(fullfile(output_dir,'provenance.csv'),r.provenance);
  LOCAL_csv(fullfile(output_dir,'lineage.csv'),{'field','value'}, { ...
    'stage',r.lineage.stage;'parent_token',r.lineage.parent_token; ...
    'scientific_parent_token',r.scientific_parent_token; ...
    'config_fingerprint',r.lineage.config_fingerprint; ...
    'source_hash',r.lineage.source_hash; ...
    'plan_hash',r.lineage.plan_hash;'grid_fingerprint',r.lineage.grid_fingerprint; ...
    'token',r.lineage.token});
  result = r; save(fullfile(output_dir,'result.mat'),'result','-v7');
  LOCAL_report(fullfile(output_dir,'report.md'),r);
  LOCAL_log(fullfile(output_dir,'run.log'),r);
end

function p = LOCAL_provenance(here,repo)
  [status,sha] = system(sprintf('git -C "%s" rev-parse HEAD',repo));
  if status ~= 0, error('tep_mc_zoom2:Git','Cannot record Git SHA.'); end
  paths = struct('tep_mc_zoom2',LOCAL_source_path(mfilename('fullpath')), ...
    'zoom2_cfg',fullfile(here,'zoom2_cfg.m'), ...
    'p_zoom2',fullfile(here,'p-zoom2.md'), ...
    'zoom_core',fullfile(here,'zoom_core.m'), ...
    'tep_mc_scan',fullfile(here,'tep_mc_scan.m'), ...
    'scan_cfg',fullfile(here,'scan_cfg.m'), ...
    'precomp_proxy',which('kernel.precomp_proxy'), ...
    'construct_S',which('bloch.construct_S'), ...
    'construct_A_QP',which('op.construct_A_QP'), ...
    'rayleigh_channels',which('bloch.rayleigh_channels'), ...
    'construct_cont',which('geom.construct_cont'));
  names = fieldnames(paths); hashes = struct();
  for j = 1:numel(names), hashes.(names{j}) = LOCAL_hash(paths.(names{j})); end
  p = struct('runtime','MATLAB','version',version,'solver','lsqminnorm', ...
    'solver_path',which('lsqminnorm'),'git_sha',strtrim(sha), ...
    'source_paths',paths,'source_hashes',hashes,'fallbacks',0, ...
    'silent_rank_changes',0,'generated_utc',char(datetime('now', ...
    'TimeZone','UTC','Format','yyyy-MM-dd''T''HH:mm:ss''Z''')));
end

function lineage = LOCAL_lineage(stage,status,parent_token,p,cfg)
  config_hash = p.source_hashes.zoom2_cfg; plan_hash = p.source_hashes.p_zoom2;
  source_hash = LOCAL_text_hash(strjoin({p.source_hashes.tep_mc_zoom2, ...
    p.source_hashes.zoom_core},'|'));
  grid = sprintf('I=[%.17g,%.17g]|quarter=4|max=%d|seed=%.17g|width=%.17g', ...
    cfg.initial_interval,cfg.max_level,cfg.pivot_seed_k,cfg.width_tol);
  payload = strjoin({cfg.zoom2_schema,cfg.zoom2_experiment_id,stage,status, ...
    parent_token,cfg.scientific_parent_token,config_hash,source_hash, ...
    plan_hash,grid},'|');
  lineage = struct('stage',stage,'parent_token',parent_token, ...
    'scientific_parent_token',cfg.scientific_parent_token, ...
    'config_fingerprint',config_hash,'source_hash',source_hash, ...
    'plan_hash',plan_hash,'grid_fingerprint',LOCAL_text_hash(grid), ...
    'token',LOCAL_text_hash(payload));
end

function LOCAL_write_provenance(path,p)
  names = fieldnames(p.source_paths); rows = cell(numel(names)+4,4);
  rows(1,:) = {'runtime',p.runtime,p.version,p.solver_path};
  rows(2,:) = {'generated_utc',p.generated_utc,'',''};
  rows(3,:) = {'fallbacks',p.fallbacks,'',''};
  rows(4,:) = {'silent_rank_changes',p.silent_rank_changes,'',''};
  for j = 1:numel(names)
    rows(j+4,:) = {names{j},p.source_paths.(names{j}), ...
      p.source_hashes.(names{j}),p.git_sha};
  end
  LOCAL_csv(path,{'object','path_or_runtime','hash_or_version','git_or_solver'},rows);
end

function LOCAL_report(path,r)
  fid = fopen(path,'w'); cleanup = onCleanup(@() fclose(fid));
  fprintf(fid,'# I1-K-SCAN-ZOOM-V2 %s Report\n\n',r.stage);
  fprintf(fid,'- Status: `%s`\n- Pass: `%d`\n',r.status,r.pass);
  if isfield(r,'stop_code'), fprintf(fid,'- Stop code: `%s`\n',r.stop_code); end
  fprintf(fid,'- Wall time: `%.6g s`\n',r.elapsed_seconds);
  fprintf(fid,'- Lineage parent: `%s`\n',r.lineage_parent_token);
  fprintf(fid,'- Scientific parent: `%s`\n',r.scientific_parent_token);
  fprintf(fid,'- Claim boundary: `%s`\n',r.claim_boundary);
  fprintf(fid,'- Locator/root/derivative/estimator: `0/0/0/0`\n');
  fprintf(fid,'- Max active dense nodes: `%d` / `%d`\n', ...
    r.max_active_nodes,r.active_node_limit);
  fprintf(fid,'- Max active state: `%.6g MiB` / `%.6g MiB`\n', ...
    r.max_active_state_mib,r.active_memory_limit_mib);
  if isfield(r,'q_history') && ~isempty(r.q_history)
    fprintf(fid,'- Final q: `%.17g`\n',r.q_history(end));
    fprintf(fid,'- q <= 1e-3 metadata: `%d`\n',r.magnitude_q_le_1e_3);
    fprintf(fid,'- Plateau diagnostic/class: `%d` / `%s`\n', ...
      r.plateau_diagnostic,r.plateau_class);
    fprintf(fid,'- q history: `%s`\n',LOCAL_number_list(r.q_history));
  end
  if isfield(r,'final_summary')
    s = r.final_summary;
    fprintf(fid,'\n## Final evaluated minimum summary\n\n');
    fprintf(fid,['- Final selected k: `%.17g`; coarse/fine k: ', ...
      '`%.17g` / `%.17g`\n'],s.final_k,s.coarse_k,s.fine_k);
    fprintf(fid,['- Coarse physical sigma1/sigmamax/s1: ', ...
      '`%.17g` / `%.17g` / `%.17g`\n'], ...
      s.coarse_sigma1,s.coarse_sigmamax,s.coarse_s1);
    fprintf(fid,['- Fine physical sigma1/sigmamax/s1: ', ...
      '`%.17g` / `%.17g` / `%.17g`\n'], ...
      s.fine_sigma1,s.fine_sigmamax,s.fine_s1);
    fprintf(fid,'- Width/grid spacing: `%.17g` / `%.17g`\n', ...
      s.width,s.grid_spacing);
    fprintf(fid,'- Index/k drift: `%.17g` / `%.17g`\n', ...
      s.index_drift,s.k_drift);
    fprintf(fid,'- r12: `%.17g`; vector overlap left/right: `%.17g` / `%.17g`\n', ...
      s.r12,s.left_vector_overlap,s.right_vector_overlap);
    fprintf(fid,'- Minimum adjacent transport overlap: `%.17g`\n', ...
      s.min_transport);
    fprintf(fid,['- QZ counts stable/unstable/neutral/infinite/indeterminate: ', ...
      '`%s` / `%s` / `%s` / `%s` / `%s`\n'], ...
      LOCAL_number_list(s.qz_stable_counts), ...
      LOCAL_number_list(s.qz_unstable_counts), ...
      LOCAL_number_list(s.qz_neutral_counts), ...
      LOCAL_number_list(s.qz_infinite_counts), ...
      LOCAL_number_list(s.qz_indeterminate_counts));
    fprintf(fid,['- QZ min unit gap/max residual/max available reference ', ...
      'residual: `%.17g` / `%.17g` / `%.17g`\n'], ...
      s.qz_min_unit_gap,s.qz_max_residual,s.qz_max_reference_residual);
    fprintf(fid,['- Chart min margin/max condition*eps/max solve residual: ', ...
      '`%.17g` / `%.17g` / `%.17g`\n'], ...
      s.chart_min_margin,s.chart_max_condition_eps,s.chart_max_solve);
  end
  if isfield(r,'layer_rows') && ~isempty(r.layer_rows)
    fprintf(fid,'\n## Interval progression\n\n');
    for j = 1:size(r.layer_rows,1)
      x = r.layer_rows(j,:);
      fprintf(fid,['- L%d: nodes `[%.17g, %.17g]`, width `%.17g`, ', ...
        'spacing `%.17g`, q `%.17g`, next `[%.17g, %.17g]`, `%s`\n'], ...
        x{1},x{4},x{8},x{2},x{3},x{27},x{19},x{20},x{22});
    end
  end
  fprintf(fid,'\nProminence is diagnostic only and is never a gate.\n');
  clear cleanup;
end

function LOCAL_log(path,r)
  fid = fopen(path,'w'); cleanup = onCleanup(@() fclose(fid));
  fprintf(fid,'experiment_id=%s\nstage=%s\nstatus=%s\npass=%d\n', ...
    r.experiment_id,r.stage,r.status,r.pass);
  if isfield(r,'stop_code'), fprintf(fid,'stop_code=%s\n',r.stop_code); end
  fprintf(fid,'elapsed_seconds=%.17g\nlineage_parent_token=%s\n', ...
    r.elapsed_seconds,r.lineage_parent_token);
  fprintf(fid,'scientific_parent_token=%s\nlineage_token=%s\n', ...
    r.scientific_parent_token,r.lineage.token);
  fprintf(fid,'fallbacks=%d\nsilent_rank_changes=%d\nclaim_boundary=%s\n', ...
    r.provenance.fallbacks,r.provenance.silent_rank_changes,r.claim_boundary);
  fprintf(fid,'max_active_nodes=%d\nmax_active_state_bytes=%.17g\n', ...
    r.max_active_nodes,r.max_active_state_bytes);
  clear cleanup;
end

function bytes = LOCAL_state_bytes(active,frame) %#ok<INUSD>
  variables = whos('active','frame'); bytes = sum([variables.bytes]);
end

function value = LOCAL_number_list(values)
  parts = arrayfun(@(x) sprintf('%.17g',x),values,'UniformOutput',false);
  value = strjoin(parts,', ');
end

function path = LOCAL_source_path(path)
  if ~isfile(path) && isfile([path,'.m']), path = [path,'.m']; end
  if ~isfile(path), error('tep_mc_zoom2:Source','Cannot resolve %s.',path); end
end

function value = LOCAL_hash(path)
  fid = fopen(path,'r');
  if fid < 0, error('tep_mc_zoom2:Hash','Cannot read %s.',path); end
  cleanup = onCleanup(@() fclose(fid)); bytes = fread(fid,Inf,'*uint8');
  digest = javaMethod('getInstance','java.security.MessageDigest','SHA-256');
  digest.update(typecast(bytes(:),'int8')); raw = typecast(digest.digest(),'uint8');
  value = lower(reshape(dec2hex(raw,2).',1,[])); clear cleanup;
end

function value = LOCAL_text_hash(payload)
  digest = javaMethod('getInstance','java.security.MessageDigest','SHA-256');
  digest.update(typecast(uint8(payload(:)),'int8'));
  raw = typecast(digest.digest(),'uint8');
  value = lower(reshape(dec2hex(raw,2).',1,[]));
end

function LOCAL_mkdir(path)
  if ~exist(path,'dir'), mkdir(path); end
end

function LOCAL_csv(path,headers,rows)
  fid = fopen(path,'w');
  if fid < 0, error('tep_mc_zoom2:Artifact','Cannot open %s.',path); end
  cleanup = onCleanup(@() fclose(fid)); LOCAL_csv_row(fid,headers);
  for j = 1:size(rows,1), LOCAL_csv_row(fid,rows(j,:)); end
  clear cleanup;
end

function LOCAL_csv_row(fid,row)
  fields = cell(1,numel(row));
  for j = 1:numel(row)
    value = row{j};
    if islogical(value), item = sprintf('%d',value);
    elseif isnumeric(value)
      if isempty(value), item = ''; else, item = sprintf('%.17g',value); end
    else, item = char(value);
    end
    fields{j} = ['"',strrep(item,'"','""'),'"'];
  end
  fprintf(fid,'%s\n',strjoin(fields,','));
end

function [sigma_min,distance] = LOCAL_overlap(A,B)
  [Qa,~] = qr(A,0); [Qb,~] = qr(B,0);
  singular = svd(Qa'*Qb,'econ'); sigma_min = min(singular);
  distance = sqrt(max(0,1-sigma_min^2));
end
